### PR TITLE
fixed scenario where `region_instance_group_manager` would not start update

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/10648 and https://github.com/hashicorp/terraform-provider-google/issues/10792

duplicate pr of https://github.com/GoogleCloudPlatform/magic-modules/pull/5506 just against RIGM

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed scenario where `region_instance_group_manager` would not start update if `wait_for_instances` was set and initial status was not `STABLE`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
What's up w/ the PR title and history?

**Comment by ScottSuarez** [comment]
ooops, yes I branched this from another change I was working on and had to go about scrubbing that from the branch. 

I updated the title

**Comment by rileykarson** [comment]
Do you mind isolating the change to a single commit as well? It probably won't matter w/ squash, but I've found branches with merges to be a little funky sometimes.

**Comment by ScottSuarez** [comment]
sure @rileykarson 

closing this in favor of https://github.com/GoogleCloudPlatform/magic-modules/pull/5584

**Pull request closed without merging**
