### PR TITLE
Change datastream stream merge and append_only to conflicts with

### PR DESCRIPTION
**Pull request by c2thorn**
fix-forward part of https://github.com/hashicorp/terraform-provider-google/issues/18890 

manual confirmation: 
error recreation: gpaste/6276707390849024
after fix: gpaste/5739342071070720

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
datastream: removed a breaking change in `google_datastream_stream` that made one of `destination_config.0.bigquery_destination_config.0.merge` or `destination_config.0.bigquery_destination_config.0.append_only` required
```

### CODE REVIEW

**Comment by c2thorn** [comment]
Trying to verify manually, the example I'm using takes 30 minutes

**Comment by c2thorn** [comment]
@slevenick 
I'm not sure why the tgc unit test is showing the previous failure. The VCR tests pass as well as my manual testing

**Comment by c2thorn** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/10166055628/job/28115320223?pr=11292#step:8:12996

`append_only` is no longer referencing itself. Maybe it's using a cached version or something

**Review by slevenick — APPROVED** [review]

**Pull request merged**
