### PR TITLE
[Terraform] Add custom Service Account support to Dataflow Job resource

### PR DESCRIPTION
**Pull request by whd**
Fixes https://github.com/terraform-providers/terraform-provider-google/issues/2072
Hopefully supersedes: https://github.com/terraform-providers/terraform-provider-google/pull/2071 https://github.com/terraform-providers/terraform-provider-google/pull/3009
Refiled here per https://github.com/terraform-providers/terraform-provider-google/pull/1834#issuecomment-453666966

-----------------------------------------------------------------
# [all]
## [terraform]
Add custom Service Account support to Dataflow Job resource
### [terraform-beta]
Add custom Service Account support to Dataflow Job resource

### CODE REVIEW

**Comment by whd** [comment]
I had spoken previously with @migibert about my intent to submit this. @migibert please confirm your consent for the CLA bot, thanks.

**Comment by migibert** [comment]
I confirm I signed the CLA.

**Comment by rileykarson** [comment]
Hmm- looks like the Magician got confused while merging. I'll work this out shortly.

**Comment by chrisst** [comment]
@whd You created this PR from the `master` branch on your fork, which is a protected branch. Our automation needs to be able to update the branch that created the PR in order to merge the changes but it can't because the branch the PR came from is protected.

I'm going to close this PR and use https://github.com/GoogleCloudPlatform/magic-modules/pull/1551 to merge in the changes.

**Pull request closed without merging**
