### PR TITLE
Add MaxStaleness to Support Query Acceleration and Object Tables

### PR DESCRIPTION
**Pull request by nevzheng**
The `max_staleness` field is used by both External Table Query Acceleration and Object Tables. 

Query Acceleration requires the `max_staleness` field and this PR enables using Terraform to CRUD tables with query acceleration.

A prior contributor added Object Table Support. This PR extends the tests added by including `max_staleness`.

## Changes
+ Add `max_staleness` field: [godoc link](https://pkg.go.dev/google.golang.org/api/bigquery/v2#Table.MaxStaleness:~:text=Interval%0A%09//%20type.-,MaxStaleness%20string%20%60json%3A%22maxStaleness%2Comitempty%22%60,-//%20Query%3A%20%5BRequired%5D%20A) [bq rest api link](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource:-table)
+ Update: Extended Object Table Tests w/ `max_staleness`
+ Add: Test demonstrating External Table with Query Acceleration

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery: added `max_staleness` to `google_bigquery_table`
```

### CODE REVIEW

**Comment by nevzheng** [comment]
currently running / fixing tests...

**Comment by rileykarson** [comment]
I'm seeing the following on latest revision! `Error: google-beta/resource_bigquery_table_test.go:1633:9: fmt.Sprintf format %s reads arg #7, but call has 6 args`

**Comment by rileykarson** [comment]
Can you access the failed test logs? They're a little noisy, but `Error: googleapi` will show the issues we're running into in each.

**Comment by nevzheng** [comment]
I've managed to reproduce the issues locally and will try to fix them before uploading again. 👍

**Comment by nevzheng** [comment]
checking to see the effect of my changes

query acceleration may still need some work

**Review by rileykarson — APPROVED** [review]
LGTM

**Pull request merged**
