### PR TITLE
add datasource to google_compute_security_policy resource

### PR DESCRIPTION
**Pull request by maxi-cit**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/3321

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_compute_security_policy`
```

### CODE REVIEW

**Comment by maxi-cit** [comment]
Hello @c2thorn could you run the tests please?

**Review by c2thorn — CHANGES_REQUESTED** [review]
Please see the above comment

**Comment by maxi-cit** [comment]
Hello @c2thorn I updated the PR with the lint fixes. I saw that the test I am adding is passing but I do not know why other tests are failing. is these something related to newest changes in the repo?

**Comment by c2thorn** [comment]
> Hello @c2thorn I updated the PR with the lint fixes. I saw that the test I am adding is passing but I do not know why other tests are failing. is these something related to newest changes in the repo?

No these, are just already failing tests that my team needs to address at some point. Shouldn't impede this

**Comment by c2thorn** [comment]
hit a quota issue, should be resolved now.
Rerunning

**Comment by c2thorn** [comment]
Just been informed we have an issue with our sweepers in the CI project, which means we are hitting many quota limits every test run. Will rerun once it seems resolved

**Comment by c2thorn** [comment]
Apologies for the delay again, just notifying that I still am aware of this. Should get this merged before the next cutoff.

**Comment by maxi-cit** [comment]
Hello @c2thorn, thanks for the response. It looks like there are still some issues with the tests. do you have an estimate on when this will be solved?

**Review by c2thorn — APPROVED** [review]

**Comment by c2thorn** [comment]
should be resolved with https://github.com/GoogleCloudPlatform/magic-modules/pull/10871, but safe to merge now

**Pull request merged**
