### PR TITLE
Update api.yaml to add DEVELOPER version for Google cloud data fusion

### PR DESCRIPTION
**Pull request by bramanscg**
Added a provision to create a "DEVELOPER" instance for google data fusion.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
datafusion: added `DEVELOPER` field to `google_data_fusion_instance` resource
```

### CODE REVIEW

**Comment by bramanscg** [comment]
```release-note:enhancement
data fusion: added `DEVELOPER` field to `google_data_fusion_instance` resource
```

**Comment by c2thorn** [comment]
Hey @bramanscg would you mind taking a look at the steps in this comment about the CLA: https://github.com/GoogleCloudPlatform/magic-modules/pull/4494#issuecomment-778917199

**Comment by c2thorn** [comment]
This has since become a dupe of https://github.com/GoogleCloudPlatform/magic-modules/pull/4514

**Pull request closed without merging**
