### PR TITLE
Forcenew on projects, setting as empty doesn't work

### PR DESCRIPTION
**Pull request by slevenick**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8210

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
billing: added ForceNew to `google_billing_budget` `budget_filter.projects` as it could not be unset
```

### CODE REVIEW

**Comment by slevenick** [comment]
@c2thorn requesting review because I think you had some related changes in billing budget recently?

**Review by melinath — APPROVED** [review]
This seems reasonable to me.

**Comment by c2thorn** [comment]
@slevenick Do we explicitly set the project as empty or do we just omit from the request?

**Comment by slevenick** [comment]
> @slevenick Do we explicitly set the project as empty or do we just omit from the request?

I believe we omit it from the request when it is empty

**Comment by c2thorn** [comment]
Is this a case where `send_empty_value` could work?

**Review by c2thorn — APPROVED** [review]
Looks like another memory failure for the VCR tests

**Comment by slevenick** [comment]
> Looks like another memory failure for the VCR tests

Ran the tests independently on this branch, looks like it fails with the same error:
```
~ projects               = [
- "projects/1067888929963",
]
```
I don't think the API will unset the projects field. I'll revert to making this input only if that sounds reasonable

**Comment by slevenick** [comment]
Well actually, trying updating a couple other fields. I'm not sure update works on this resource, and there's a note about update mask potentially being needed

**Comment by melinath** [comment]
@slevenick is this still an active PR?

**Comment by melinath** [comment]
@slevenick are you still working on this?

**Comment by philip-harvey** [comment]
any news on this?  The issue still exists in the current provider version

**Pull request closed without merging**
