### PR TITLE
fix overwriting of `name` field for IAM Group user in resourceSqlUserRead method

### PR DESCRIPTION
**Pull request by pratikgarg10**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
sql: fix overwriting of `name` field for IAM Group user for resource `google_sql_user`
```

### CODE REVIEW

**Comment by pratikgarg10** [comment]
Hi @BBBmau, Could you please take a look at this pull request for review?

**Comment by ScottSuarez** [comment]
Is there a ticket for this issue or could you provide an explanation of the change? I am not familiar with this resource.

**Comment by ScottSuarez** [comment]
Also if a testcase could be added showing exactly what was broken and is now fixed that would be great !

**Comment by pratikgarg10** [comment]
> Is there a ticket for this issue or could you provide an explanation of the change? I am not familiar with this resource.
Here is the issue: https://github.com/hashicorp/terraform-provider-google/issues/17040

**Issue:**
Creating IAM group user resource fails with error "Root resource was present, │ but now absent. "

**Explanation:**
The code snippet in Condition 1 below truncates the SQL user `name` field and overwrites it if the condition is satisfied for any user in the users list, but later the comparison in Condition 2 will fail for valid SQL user `name` due to overwritten truncation of previous user in the list.

Condition 1:
```
if !(strings.Contains(databaseInstance.DatabaseVersion, "POSTGRES") || currentUser.Type == "CLOUD_IAM_GROUP") {
            name = strings.Split(name, "@")[0]
        }
```

Condition 2:
```
if currentUser.Name == name {
	// Host can only be empty for postgres instances,
	// so don't compare the host if the API host is empty.
	if host == "" || currentUser.Host == host {
		user = currentUser
		break
	}
}
```

During IAM group creation on the instance, the condition that triggers the issue is the naming convention used for the built-in users & IAM user/groups and corresponding alphabetical order. If the IAM group user comes last in the order, we'll see the issue.

**Comment by pratikgarg10** [comment]
> Also if a testcase could be added showing exactly what was broken and is now fixed that would be great !

It was tested locally, but difficult to reproduce via unit test

**Comment by ScottSuarez** [comment]
Got it!! This change seems reasonable. We are currently frozen for 6.0 release but I'll approve this once things move along. 

I'm going to leave this PR as unreviewed simply to maintain it in my review queue and that I don't lose track of it.

**Review by ScottSuarez — APPROVED** [review]
unfroze early.. merging now.

**Pull request merged**
