### PR TITLE
Add the beta support for Port Mapping NEG and endpoint

### PR DESCRIPTION
**Pull request by Cheriit**
Add the beta support for Port Mapping NEG and endpoint. New NEG type is a regional type of `GCE_VM_IP_PORTMAP` that requires endpoints with Instance, Port and Client Destination Port

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added the beta support for Port Mapping NEG and endpoint. New NEG type is a regional type of `GCE_VM_IP_PORTMAP` that requires endpoints with `instance`, `port` and `client_destination_port` (beta)
```

### CODE REVIEW

**Comment by Cheriit** [comment]
I see that the failing tests are not related to the changes in Regional NEGs

**Comment by slevenick** [comment]
/gcbrun I've cleaned up some resources to clear quota

**Comment by Cheriit** [comment]
The error is not related to my changes

**Comment by Cheriit** [comment]
@BBBmau Can you review this change? We want to have this feature in the next release?

**Review by BBBmau — APPROVED** [review]

**Pull request merged**
