### PR TITLE
feat: add most_recent option to google_compute_image datasource

### PR DESCRIPTION
**Pull request by darkweaver87**
This PR aims to add `most_recent` argument the same way [AWS does](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#most_recent).

I didn't really find where I could add an example, but here it is:

```
data "google_compute_image" "image" {
  project     = "debian-cloud"
  filter      = "architecture:amd64"
}
# ==> Error: your filter has returned more than one image or no image. Please refine your filter to return exactly one image

data "google_compute_image" "image" {
  project     = "debian-cloud"
  filter      = "architecture:amd64"
  most_recent = true
}
# ==> debian-12-bookworm-arm64-v20230711
```

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `most_recent` argument to `google_compute_image` datasource
```

### CODE REVIEW

**Review by NickElliot — CHANGES_REQUESTED** [review]
Looks like the build is currently failing due to a missing `time` import to enable the code you added. Could you include that? Thanks!

**Comment by darkweaver87** [comment]
Hello @NickElliot,

Oh yes! Sorry, I forgot to copy/paste back from my go code to the ruby template :sweat_smile:

**Review by NickElliot — COMMENTED** [review]
LGTM! to @ScottSuarez for final review

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
Looks good to me. @NickElliot can you approve and merge. Merging gets block if there is a `requested_changes` bit on the pr.

**Review by NickElliot — APPROVED** [review]

**Comment by darkweaver87** [comment]
Many thanks guys ;-)

**Pull request merged**
