### PR TITLE
Generate UrlMap in Terraform.

### PR DESCRIPTION
**Pull request by rileykarson**
Generate UrlMap in Terraform.

-----------------------------------------------------------------
# [all]
Minor docs changes for UrlMap
## [terraform]
Autogenerate google_compute_url_map

### CODE REVIEW

**Comment by rileykarson** [comment]
Also @danawillow can you look over the docs changes to other providers as a sanity check as well? I don't want to collect new LGTMs for like +- 8 characters of text in each

**Comment by danawillow** [comment]
Docs changes to other providers LGTM, though I think you need to do another round of generation because this seems to have picked up some things that have already been merged.

**Comment by rileykarson** [comment]
I caught a missing Required - let me know if you think I should get LGTM's from the other providers.

**Comment by danawillow** [comment]
I think it's fine, though I'm confused why the puppet-google and chef-google changes are showing up in this PR and don't seem to be showing up in others.

**Comment by rileykarson** [comment]
Those changes are actually already merged by [the downsteams of Nathan's PR here](https://github.com/GoogleCloudPlatform/magic-modules/pull/554), I'm not sure why they still show up as diffs - I can close out those PRs since they will no-op anyways. The Magician gets confused when a PR exists for a long time I guess.

**Pull request merged**
