### PR TITLE
Upgrade DCL version to 1.57.0

### PR DESCRIPTION
**Pull request by rileykarson**
This puts a `go.mod` in tpgtools/handwritten so that it's not part of the `tpgtools` module anymore. This will need to be updated if we start using new methods in the limited handwritten files in that dir- really, we should move those files over to MMv1 and drop the functionality, but this is a smaller change.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
gkehub: added support for `membership_location` to `google_gke_hub_feature_membership`
```

```release-note:deprecation
gkehub: deprecated `config_management.binauthz` in `google_gke_hub_feature_membership`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
I tested basic `membership_location` functionality locally, and confirmed it was working. Not sure what extra steps are needed for the sample tests to get updated.

**Review by zli82016 — APPROVED** [review]
LGTM.

**Comment by zli82016** [comment]
I remember Cameron mentioned he updated the test samples previously. We may need a documentation from him.

**Comment by zli82016** [comment]
Created the issue to move folder tpgtools/handwritten https://github.com/hashicorp/terraform-provider-google/issues/16537

**Comment by rileykarson** [comment]
Thanks!

**Comment by slevenick** [comment]
FYI it looks like the docs did not get updated

**Pull request merged**
