### PR TITLE
Fix some validator build issues

### PR DESCRIPTION
**Pull request by daniel-cit**
This PR:

- Add missing func `GetProviderMeta` from `terraform-plugin-sdk/v2/helper/schema` `schema.ResourceData` in `ResourceDataMock` and `TerraformResourceData`
- Fix some issues in handwritten `resources sql_database_instance.go` and `compute_instance.go`
- add missing imports in `config.go.erb ` 

This PR Fiesx some issues from https://github.com/GoogleCloudPlatform/terraform-google-conversion/issues/572

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
Add missing func `GetProviderMeta` from `terraform-plugin-sdk/v2/helper/schema` `schema.ResourceData` in `ResourceDataMock` and `TerraformResourceData`
```

### CODE REVIEW

**Review by ndmckinley — APPROVED** [review]
LGTM as long as this doesn't break linters / tests in TPG.  I'll wait for the result, should be in in a few minutes.

**Comment by daniel-cit** [comment]
@ndmckinley one question, when I run 
```
bundle exec compiler -a -v ga -e terraform -f validator -o ${GOPATH}/src/github.com/GoogleCloudPlatform/terraform-google-conversion
```
to check if the fix is OK, I also see in the git diff two missing imports been autonatically fixed:

```
diff --git a/google/bigtable_app_profile.go b/google/bigtable_app_profile.go
index 9e7f440..51e2e51 100644
--- a/google/bigtable_app_profile.go
+++ b/google/bigtable_app_profile.go
@@ -17,6 +17,8 @@ package google
 import (
 	"fmt"
 	"reflect"
+
+	"google.golang.org/api/bigtableadmin/v2"
 )
```

and 

```
diff --git a/google/compute_subnetwork.go b/google/compute_subnetwork.go
index ff8e01e..78073a7 100644
--- a/google/compute_subnetwork.go
+++ b/google/compute_subnetwork.go
@@ -20,6 +20,7 @@ import (
 	"net"
 	"reflect"
 
+	"github.com/apparentlymart/go-cidr/cidr"
 	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
 )
``` 

How can these import error be fixed in a PR? is it necessary to touch the files for the missing import to be fixed and included in the diff ?

**Comment by ndmckinley** [comment]
We automatically run `goimports` on any `.go.erb` file, so it's just subject to the goimports rules.  I assume that modifying the file isn't necessary but goimports is surprisingly hard to reverse engineer, and it's extremely subject to the particular version of goimports you're using and the state of your particular system.  Is that correctly changed in the diff that the Magician just posted?  We use docker containers to keep those sorts of variations from causing instability.

**Comment by ndmckinley** [comment]
One good way to add imports is just to literally add them to the top of the relevant files - goimports treats the imports already provided as a "hint", which can usually persuade it to add them.

**Comment by daniel-cit** [comment]
Those two imports

- "github.com/apparentlymart/go-cidr/cidr"
- "google.golang.org/api/bigtableadmin/v2"

 were not added into the Magician diff.

They were removed in  this PR

https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/437 

But I can't see the reason for removing them since removing them broke the GO compilation in those files that were changed

**Comment by daniel-cit** [comment]
The strange thing is that the Terraform provider generated files have the missing imports:

- "github.com/apparentlymart/go-cidr/cidr"
- "google.golang.org/api/bigtableadmin/v2"

https://github.com/hashicorp/terraform-provider-google/blob/ec61f73f9cdb49e513ffdd612368c47323e60677/google/resource_compute_subnetwork.go#L25


```
package google

import (
	"context"
	"fmt"
	"log"
	"net"
	"reflect"
	"time"

	"github.com/apparentlymart/go-cidr/cidr"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

// Whether the IP CIDR change shrinks the block.
func isShrinkageIpCidr(_ context.Context, old, new, _ interface{}) bool {
```

https://github.com/hashicorp/terraform-provider-google/blob/ec61f73f9cdb49e513ffdd612368c47323e60677/google/resource_bigtable_app_profile.go#L25

```
package google

import (
	"fmt"
	"log"
	"reflect"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"google.golang.org/api/bigtableadmin/v2"
)

func resourceBigtableAppProfile() *schema.Resource {
```

**Comment by ndmckinley** [comment]
Yeah - goimports considers all the other files in the package, so I assume it's got something to do with one or more of those files having those imports so that goimports can find them.  Pretty hard to be sure, but that's my intuition.

You can add those imports to the relevant files, that will probably get you what you need.

**Comment by daniel-cit** [comment]
@ndmckinley  

There is an issue that I tried to fix in this PR but I had to revert my change. 

It was to replace this line

https://github.com/GoogleCloudPlatform/magic-modules/blob/250e3bbeae988e063a817da069626ebcd016ad19/templates/terraform/encoders/disk.erb#L8

with

```
userAgent, err := generateUserAgentString(d.(*schema.ResourceData), config.userAgent)
```

in the `disk.erb` encoder.

with this change, I would solve this error in validator

```
google\compute_disk.go:331:43: cannot use d (type TerraformResourceData) as type *"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema".ResourceData in argument to generateUserAgentString: need type assertion
```

but after this change I got this error in the provider

```
# github.com/hashicorp/terraform-provider-google/google
google/resource_compute_disk.go:1451:45: invalid type assertion: d.(*schema.ResourceData) (non-interface type *schema.ResourceData on left)
```

**and because of that I reverted the change.**


The source of this issue is caused by differences in the func signatures.

In the validator the func signature is

```
func resourceComputeDiskEncoder(d TerraformResourceData, meta interface{}, obj map[string]interface{}) (map[string]interface{}, error) {
```

and in the provider it is  

```
func resourceComputeDiskEncoder(d *schema.ResourceData, meta interface{}, obj map[string]interface{}) (map[string]interface{}, error) {
```

and `TerraformResourceData` is an interface and `*schema.ResourceData` is a struct thus the error :( 

Do you know of any way to solve this kind of issue?

**Comment by ndmckinley** [comment]
I see!  I would suggest changing the function signature of generateUserAgentString - we control that code, right?

**Comment by daniel-cit** [comment]
@ndmckinley  sounds good, we control the code. I will try it on another Pull Request not to hold this one.

**Pull request merged**
