### PR TITLE
Enhance BigQuery table schema input validation

### PR DESCRIPTION
**Pull request by wj-chen**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/14659.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
added more input validations for BigQuery table schema
```

### CODE REVIEW

**Comment by wj-chen** [comment]
Received an email about [test failure](https://ff46141979bf39ff9c7fa2f174df1b5c72ef05397c52de6fa411a24-apidata.googleusercontent.com/download/storage/v1/b/ci-vcr-logs/o/beta%2Frefs%2Fheads%2Fauto-pr-8460%2Fartifacts%2F9f365b8a-d37d-4098-9c67-3969f057dea1%2Fbuild-log%2Freplaying_build_after_recording%2FTestAccBigQueryTable_invalidSchemas_replaying_test.log?jk=AYvHSRG3nVYI5Bsu1UOIeZG_R2h5_lyuWmIdgEeNUYGHWlLMJpn6SqRPr6osfW-L7zj6XX7GAlCP7VzS8jOv8fWR1r0gh9BiR_OCvW45UYebTGmVHUYl9XF_MTvZqjcuZpvL-Yh5JYYHluIMS4USzgYsvFmx1LQZQiAn70UwhKIENf_DAjpyrWXTHw800OcZCo2gvhwm1m68f913s7bWCTlvo8yfkQi8lC_H_bGVD68H_9YCdFl0JS6SAwniKdDy3goDFIb2I4_0U9ehrceLTAMR67BwQL2rZoPaWzx3G2bA8EkBW6rmZWnCUNmickptMgeUWJFO5x9rDSWxAxcY-W2IcxPr767owp9AUpCC3wPnlH1mEUnZ4qgrdE5aZ5WV5dzu8jYEUKgqmNIvObTjV4kbwVuTkuZAtM9VlNEnNxU1dC6Bf0LY93k8B7LSNckfpjfT6kSyq756-VsU2qsQIhXZ07AYzLl0nxLeG6U8_zyf57GgrFwoWzug3AAqPhjE8B6Ym_3TEE6viZchYBsUvRCL9L9mfvVKMZGRoYtCvAQOY2KMuobRA3jCV_7hE806p3ZNEZVbJPxobCq07oLxcK7kzGjxvYFFQcrFv-o4FJxXXrs7N0bwkBlpRw96cPd6q71SJ6irPYk4wpD34_64d_gs6DZg8nKk7HwqLmzu5bGAQ3Bs6cnR_ubAO7Ts64fE_1k0M0vkDbW0FNb3JKtQGYMg8Po3ABBP9mQ1-iznpyB1sDxgdXcrob9C8FpgPd-AQKvT3Q7hsPo5XZERYd-qIIRLOsUYIdoMM9CsPGZjXz6BFkjONUOd6tsd4IZ-pMHLi1o7L_GvCvdpAihBtPid00jxyXc1KI5swG0cagv_KqglXnaxwebwgbyeDmcC9cm4qcG6VX_LaDfTM8JyeP31vNNXKi7dbO21EIZea3eW47mM2nyA6r8RrWHY5K87AWQMdtZDixjRfvLmXmNgujJOgtMlQB3n2Vz3sl7QGMS5HyULlKm6VBnOUqo6mpvcgM7juzuQRwPscCcmQAx-W2y9WVAP8g0mpIXfoBX3O6mVp_EO1KTr9AspfdbrZ1zkMLLnAjduGarqFaOGwNJPq7VFsgx-oOM2Y1682Ye1Uj6_gNU1xNUCZsO0QtKif78ObtThBxl2bQVPSS9sK_DGj52mqOX5fGP5XQhQXnNhXnu2BDJom1NcSYOkPx9NnT7fnysU9wpzr3eWLVHFaowiLcI8HyxTSZwh1pFeqzZbGPmiUwxv0KVoYDtkwSsLC1a_t3t7ZPJnhrGu0MZMR5NIe5jzOcL2JB58x_MhiT1eUOEBarGaMldxRqM6PLRGy6ALTV_4i1DVSD-7oJdVXKI0DpqN5E6giXUMG__qqsbuciqGEcifLhTHtSKelBE9w3knh_m-_CgTXBNvYM0TKMUohZPrJN7QuYqPfVbwUA&isca=1):
```
test_utils.go:98: no cassette found on disk for TestAccBigQueryTable_invalidSchemas, please replay this testcase in recording mode - open /go/src/github.com/hashicorp/terraform-provider-google-beta/fixtures/TestAccBigQueryTable_invalidSchemas.seed: no such file or directory
```
Do I need to do something with the provider?

**Comment by wj-chen** [comment]
Seeing the same failure for my test `TestAccBigQueryTable_invalidSchemas`: "test_utils.go:98: no cassette found on disk for TestAccBigQueryTable_invalidSchemas, please replay this testcase in recording mode - open /go/src/github.com/hashicorp/terraform-provider-google-beta/fixtures/TestAccBigQueryTable_invalidSchemas.seed: no such file or directory". I don't quite understand the suggested action.

Then there is another separate failure in `TestAccContainerAwsNodePool_BetaBasicHandWritten` which is unrelated to this change.

**Comment by hao-nan-li** [comment]
I talked to my team about this, this test is more a unit test rather than an acceptance test, reason why we see that error message. I would suggest the following: 
1) Paste the log of local run showing this passed.
2) add skip_test.

And don't worry about the other failed test, it is unrelated.

**Comment by wj-chen** [comment]
> I talked to my team about this, this test is more a unit test rather than an acceptance test, reason why we see that error message. I would suggest the following:
> 
> 1. Paste the log of local run showing this passed.
> 2. add skip_test.
> 
> And don't worry about the other failed test, it is unrelated.

Thank you for the guidance! Here is the local test run result:
```
wjchen@wjchen:/google/src/cloud/wjchen/osconfig-agent-cider/google3/experimental/users/wjchen/terraform-provider-google$ make testacc TEST=./google TESTARGS="-run=TestAccBigQueryTable_invalidSchemas"
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccBigQueryTable_invalidSchemas -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccBigQueryTable_invalidSchemas
=== PAUSE TestAccBigQueryTable_invalidSchemas
=== CONT  TestAccBigQueryTable_invalidSchemas
--- PASS: TestAccBigQueryTable_invalidSchemas (0.87s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   0.996s
```

What's the difference between unit test and acceptance test? And by adding `skip_test` did you mean adding it in mmv1/products/bigquery/Table.yaml? Doesn't that only do something to the "examples"?

**Comment by hao-nan-li** [comment]
> > I talked to my team about this, this test is more a unit test rather than an acceptance test, reason why we see that error message. I would suggest the following:
> > 
> > 1. Paste the log of local run showing this passed.
> > 2. add skip_test.
> > 
> > And don't worry about the other failed test, it is unrelated.
> 
> Thank you for the guidance! Here is the local test run result:
> 
> ```
> wjchen@wjchen:/google/src/cloud/wjchen/osconfig-agent-cider/google3/experimental/users/wjchen/terraform-provider-google$ make testacc TEST=./google TESTARGS="-run=TestAccBigQueryTable_invalidSchemas"
> TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccBigQueryTable_invalidSchemas -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
> === RUN   TestAccBigQueryTable_invalidSchemas
> === PAUSE TestAccBigQueryTable_invalidSchemas
> === CONT  TestAccBigQueryTable_invalidSchemas
> --- PASS: TestAccBigQueryTable_invalidSchemas (0.87s)
> PASS
> ok      github.com/hashicorp/terraform-provider-google/google   0.996s
> ```
> 
> What's the difference between unit test and acceptance test? And by adding `skip_test` did you mean adding it in mmv1/products/bigquery/Table.yaml? Doesn't that only do something to the "examples"?

Thanks for sharing the log. As far as skipping the test, I think we can start with something like https://github.com/GoogleCloudPlatform/magic-modules/commit/366d6841dced251fc2b2339d172f5efdcb46f1a6 to skip the VCR test.

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
