### PR TITLE
Remove project field from IAM documentation

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7170

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by upodroid** [comment]
I'm getting weird behaviour by the generator.

It removes project field correctly from `google_storage_bucket_iam_*` and others such as `google_service_directory_namespace_iam_*` but it also removes it from `google_artifact_registry_repository_iam_*` and `google_pubsub_topic_iam_*` that need it.

**Comment by ScottSuarez** [comment]
Yeah this won't fix it since you need to look if the base_url includes the tag project. Problem is we aren't looking at the override.

If might be able to fix it.
  `base_url = object.iam_policy.base_url || object.base_url || object.self_link_uri`

base_url.include?("{{project}}")

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
need changes requested previously... rerequest review if those are submitted

**Comment by upodroid** [comment]
Sorry, I tried it before and couldn't get the generator to work properly. Can you finish it?

**Pull request closed without merging**
