### PR TITLE
perform nil check on bucket_policy_only

### LINKED ISSUE #2234: expandIamConfiguration in storage_bucket.go panics
The code actual panics when a nil interface is passing in:

```
        panic: interface conversion: interface {} is nil, not bool

        goroutine 1 [running]:
        github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandIamConfiguration(...)
        	<redacted>/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:269
```

The code in line 269 in my local snapshot is same as https://github.com/GoogleCloudPlatform/magic-modules/blame/e6b8eca0203975ecad275fb93fa9d4ece1537a33/third_party/validator/storage_bucket.go#L269

```
			Enabled:         d.Get("bucket_policy_only").(bool),
```

### PR DESCRIPTION
**Pull request by yukinying**
This should fix #2234.

# Release Note for Downstream PRs (will be copied)
```releasenote

```

### CODE REVIEW

**Comment by yukinying** [comment]
It turns out that validator is using a older version of terraform provider (vendored). The code in validator would be able to get the default value if the provider got the schema.

**Comment by rileykarson** [comment]
Cool! As I understand, Validator can vendor a newer version of the provider to resolve this issue then?

**Comment by yukinying** [comment]
I tried upgrading the vendored packages in validator but there is an issue blocking that: https://github.com/GoogleCloudPlatform/terraform-validator/issues/69 :(

**Comment by yukinying** [comment]
This is no longer required as the downstream dependency has fixed the issue.

**Pull request closed without merging**
