### PR TITLE
Remove default value from sample_method 

### PR DESCRIPTION
**Pull request by Wallace99**
It seems that if `sample_method` is set in DLP inspection trigger scanning BigQuery, you are forced to specify `rows_limit` or `rows_limit_percentage` with values > 0 and < 100% which prevents doing a full table scan. This PR removes the default value.

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/13451

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
dlp: Removed default value for sample_method
```

### CODE REVIEW

**Comment by slevenick** [comment]
As noted above this appears to be a breaking change. Removing defaults is not an easy task though it may be possible. We would need a very convincing reason to do so.

It seems like the problem is that you can't do a full table scan when this field is set, but maybe that's a separate issue? Should we see if there is a fix for setting row_limits_percentage or row_limits so that the full scan can take place?

**Review by slevenick — CHANGES_REQUESTED** [review]
See note above

**Comment by Wallace99** [comment]
Hi @slevenick sorry for the slow reply, I have done some initial testing and seen that removing the field allowed row_limits_percentage or row_limit to be omitted and the full table be scanned. I understand it is a pain to remove a default value though and will try see if there's any alternative fixes. It does seem from what I can see that the docs make no mention of row_limits_percentage or row_limit needing to be >0 or <100%

**Comment by slevenick** [comment]
It looks like if we can specify an unspecified sample_method and we will be able to configure a full scan.

We may need to add a new value to the sample_method enum:
```
        "sampleMethod": "SAMPLE_METHOD_UNSPECIFIED",
        "rowsLimitPercent": 100
```
Should work

**Comment by Wallace99** [comment]
> It looks like if we can specify an unspecified sample_method and we will be able to configure a full scan.
> 
> We may need to add a new value to the sample_method enum:
> 
> ```
>         "sampleMethod": "SAMPLE_METHOD_UNSPECIFIED",
>         "rowsLimitPercent": 100
> ```
> 
> Should work

Hi @slevenick, I've just made those changes. Do you think it would be worth removing the default value for the next major release or is this sufficient? Not particularly elegant having people need to add this sample method in, but agree it's better than a breaking change

**Comment by slevenick** [comment]
Looks like there are some conflicts. The changes in api.yaml and terraform.yaml should be consolidated into a single file now.  Can you make those and I'll rerun the build?

**Pull request closed without merging**
