### PR TITLE
Add `expire_time` output field to multiple ssl certificate resources

### PR DESCRIPTION
**Pull request by SarahFrench**
(No linked issue)

This PR adds the expiry time output field to 2 SSL certificate resources

- [API docs for global SSL cert expireTime field](https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates/get#body.SslCertificate.FIELDS.expire_time)
- [API docs for the field in regional SSL certs](https://cloud.google.com/compute/docs/reference/rest/v1/regionSslCertificates#SslCertificate.FIELDS.expire_time)

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added field `expire_time` to resource `google_compute_ssl_certificate`
```

```release-note:enhancement
compute: added field `expire_time` to resource `google_compute_region_ssl_certificate`
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
The validator check is failing due to multiple declarations of flatten functions in the managed SSL cert resource. I thought my latest commit would fix that issue 🤔  - I'll investigate after the holidays

**Comment by SarahFrench** [comment]
\gcbrun

**Review by megan07 — COMMENTED** [review]
LGTM, thanks!

**Review by megan07 — APPROVED** [review]

**Pull request merged**
