### PR TITLE
Added COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY support to github pullRequest commentControl

### PR DESCRIPTION
**Pull request by melinath**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/7366.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudbuild: Added `COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY` support to `google_cloudbuild_trigger.github.pull_request.comment_control` field
```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
Can we include the field in a test? I would probably add it to [this step](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_cloudbuild_trigger_test.go#L240) personally, but up to you.

**Comment by melinath** [comment]
Yeah, I can definitely add a test! Thanks.

**Comment by melinath** [comment]
@rileykarson So, it looks like I can't add it directly to `testAccCloudBuildTrigger_updated` because `github` is mutually exclusive with `trigger_template`.

Any new test (or test step) that exercises a `github` block fails with:

```
Error: Error creating Trigger: googleapi: Error 400: Repository mapping does not exist.  Please visit https://console.cloud.google.com/cloud-build/triggers/connect?project=<project_id> to connect a repository to your project
```

Visiting the URL asks me to connect the project to my GitHub account via OAuth. I can do that, but I suspect it will fail in CI, unless that's something we can set up there. What are your thoughts?

**Review by rileykarson — APPROVED** [review]
Ah, yeah, that'll fail in CI. Good with me as-is in that case!

**Pull request merged**
