### PR TITLE
[terraform] Add sensitive_content argument to resource_storage_bucket_object

### PR DESCRIPTION
**Pull request by rcoy-v**
Implementation of https://github.com/terraform-providers/terraform-provider-google/issues/3153.

### CODE REVIEW

**Comment by rcoy-v** [comment]
I signed it!

**Comment by rileykarson** [comment]
What about marking `content` as sensitive instead of adding a new field? I don't see a problem with doing so; it won't have an effect on Terraform's operation and the only end-user impact is that users need to define an output to see the raw value.

**Comment by rcoy-v** [comment]
I don't mind either way. Since I was not getting any discussion on the original issue, I thought it would be safer to not change an existing functionality for an initial pull request.

**Comment by rileykarson** [comment]
Ah you're right, sorry for the lack of comment from our side on your issue! It's not a change with any impact on behaviour, so feel free to update this to add `Sensitive: true` to `content` instead.

**Comment by rcoy-v** [comment]
I will change the pull request to only add the `Sensitive: true` on `content` then. Is there a test that needs to be added for that? I'm not sure how to check for that change in an acceptance test.

**Pull request merged**
