### PR TITLE
Add region security policy in target pool

### PR DESCRIPTION
**Pull request by felipegc**
Fixes:
https://github.com/hashicorp/terraform-provider-google/issues/15464

Adding security_policy field in google_compute_target_pool resource.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added support for `security_policy` field to `google_compute_target_pool`
```

### CODE REVIEW

**Comment by felipegc** [comment]
@NickElliot I am moving this task to draft because this feature is only available for whitelist projects. The build project has already been whitelisted so we can start reviewing it. It is expected that this feature might be public available in few days so it would be nice if we are prepared for merging once this happens.
Thanks

**Review by NickElliot — COMMENTED** [review]
LGTM, please update when it is ready for a final passover when feature officially reaches public beta status

**Comment by felipegc** [comment]
@NickElliot the feature is public available now. There were bunch of updates on the main branch. Could you please trigger the test once more before we merge it? Thanks

**Review by NickElliot — APPROVED** [review]
LGTM! Missing test field report is inaccurate, verified through CI debug logs.

**Pull request merged**
