### PR TITLE
Fix resource_bigquery_dataset ID validation

### PR DESCRIPTION
**Pull request by wj-chen**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/12284.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery: fixed dataset ID validation
```

### CODE REVIEW

**Comment by wj-chen** [comment]
Test error:
```
    test_utils.go:108: no cassette found on disk for TestAccBigQueryDataset_invalidCharacterInID, please replay this testcase in recording mode - open /workspace/.ci/magician/cassettes/beta/TestAccBigQueryDataset_invalidCharacterInID.seed: no such file or directory
```

Will skip VCR for these validation tests.

**Comment by wj-chen** [comment]
Investigating unit test failures - seems that some other tests have been specifying invalid dataset IDs in their TF configs...

**Comment by wj-chen** [comment]
@trodge some checks didn't trigger as part of the last commit but this PR is ready for review.

**Comment by wj-chen** [comment]
Spoke too soon...Maybe the corresponding CAI assets need to be updated too?
```
logger.go:130: 2024-02-22T20:19:28.240Z	DEBUG	google_bigquery_dataset.example_dataset: resource uses the google-beta provider and may not be convertible
        logger.go:130: 2024-02-22T20:19:28.240Z	DEBUG	google_bigquery_dataset_iam_member.dataset: resource uses the google-beta provider and may not be convertible
        logger.go:130: 2024-02-22T20:19:28.240Z	INFO	Retrieving ancestry from resource (type=bigquery.googleapis.com/Dataset)
        logger.go:130: 2024-02-22T20:19:28.240Z	INFO	Retrieving ancestry from resource (type=bigquery.googleapis.com/Dataset)
        read_test.go:205: TestReadPlannedAssetsCoverage/example_bigquery_dataset_iam_member diff(-want, +got):
              []caiasset.Asset{
              	{
              		Name: strings.Join({
              			"//bigquery.googleapis.com/projects/foobar/datasets/test",
            - 			"-",
            + 			"_",
              			"dataset",
              		}, ""),
              		Type:     "bigquery.googleapis.com/Dataset",
              		Resource: &{DiscoveryName: "Dataset", Parent: "//cloudresourcemanager.googleapis.com/projects/foobar", Data: {"datasetReference": map[string]any{"datasetId": string("test_dataset")}, "defaultTableExpirationMs": float64(3.6e+06), "friendlyName": string(""), "labels": map[string]any{"env": string("dev")}, ...}},
              		... // 4 identical fields
              	},
              }
```
@trodge Could you advise?

**Comment by wj-chen** [comment]
> Spoke too soon...Maybe the corresponding CAI assets need to be updated too?
> 
> ```
> logger.go:130: 2024-02-22T20:19:28.240Z	DEBUG	google_bigquery_dataset.example_dataset: resource uses the google-beta provider and may not be convertible
>         logger.go:130: 2024-02-22T20:19:28.240Z	DEBUG	google_bigquery_dataset_iam_member.dataset: resource uses the google-beta provider and may not be convertible
>         logger.go:130: 2024-02-22T20:19:28.240Z	INFO	Retrieving ancestry from resource (type=bigquery.googleapis.com/Dataset)
>         logger.go:130: 2024-02-22T20:19:28.240Z	INFO	Retrieving ancestry from resource (type=bigquery.googleapis.com/Dataset)
>         read_test.go:205: TestReadPlannedAssetsCoverage/example_bigquery_dataset_iam_member diff(-want, +got):
>               []caiasset.Asset{
>               	{
>               		Name: strings.Join({
>               			"//bigquery.googleapis.com/projects/foobar/datasets/test",
>             - 			"-",
>             + 			"_",
>               			"dataset",
>               		}, ""),
>               		Type:     "bigquery.googleapis.com/Dataset",
>               		Resource: &{DiscoveryName: "Dataset", Parent: "//cloudresourcemanager.googleapis.com/projects/foobar", Data: {"datasetReference": map[string]any{"datasetId": string("test_dataset")}, "defaultTableExpirationMs": float64(3.6e+06), "friendlyName": string(""), "labels": map[string]any{"env": string("dev")}, ...}},
>               		... // 4 identical fields
>               	},
>               }
> ```
> 
> @trodge Could you advise?

Unit test still fails for the same error: https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/8025781983/job/21927071653

**Comment by melinath** [comment]
Taking a look re: the TGC error. In theory, that error should mean that the CAI json file needs to be updated - but I see that you've already updated it 🤔  I'll see if I can figure out what's going on.

**Review by melinath — CHANGES_REQUESTED** [review]
oh I see the problem - you updated the `datasetId` field but you also need to update the `name` field for each CAI json file.

For example, https://github.com/GoogleCloudPlatform/magic-modules/pull/10027/files#diff-263d15159fcdbf11bc3a6c18f4b4e106456f3a47c4769c92d18aa8119bc137b2R3 should be:

```json
    "name": "//bigquery.googleapis.com/projects/{{.Provider.project}}/datasets/test_dataset",
```

**Comment by wj-chen** [comment]
> oh I see the problem - you updated the `datasetId` field but you also need to update the `name` field for each CAI json file.
> 
> For example, https://github.com/GoogleCloudPlatform/magic-modules/pull/10027/files#diff-263d15159fcdbf11bc3a6c18f4b4e106456f3a47c4769c92d18aa8119bc137b2R3 should be:
> 
> ```json
>     "name": "//bigquery.googleapis.com/projects/{{.Provider.project}}/datasets/test_dataset",
> ```

Thank you! Fixed. I should have just done a find-and-replace 😂

**Review by trodge — APPROVED** [review]

**Pull request merged**
