### PR TITLE
promote oidc key upload to GA

### PR DESCRIPTION
**Pull request by bohengy**
Promote the new field jwks-json to GA.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
iamworkforcepool: promoted field `oidc.jwks_json` in resource `google_iam_workforce_pool` to GA
```

### CODE REVIEW

**Review by NickElliot — COMMENTED** [review]
Hi! Could you share a log of the test passing locally on the GA provider, as our CI run only runs the beta one

**Comment by bohengy** [comment]
> Hi! Could you share a log of the test passing locally on the GA provider, as our CI run only runs the beta one

Hi, Nick. Is https://paste.googleplex.com/5569334062612480 what you need?

**Comment by NickElliot** [comment]
Specifically the output log from running `TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcUploadKeyExample`, you could just run the following command and provide the output.log file over email/etc

`TF_LOG=DEBUG TF_LOG_SDK_FRAMEWORK=INFO make testacc TEST=./google-beta/services/iamworkforcepool TESTARGS='-run=TestAccIAMWorkforcePoolWorkforcePoolProvider_iamWorkforcePoolProviderOidcUploadKeyExample' > output.log` is the command you should run

**Review by NickElliot — APPROVED** [review]
LGTM

**Pull request merged**
