### PR TITLE
feat(bigtable): update deps

### PR DESCRIPTION
**Pull request by ron-gal**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
Looks like this broke some tests, could you take a look and run some locally?

**Comment by ron-gal** [comment]
Minor irrelevant changes to https://github.com/GoogleCloudPlatform/magic-modules/pull/11258 cause the same errors, so it's safe to assume no new errors are introduced by this PR

**Comment by hao-nan-li** [comment]
> Minor irrelevant changes to #11258 cause the same errors, so it's safe to assume no new errors are introduced by this PR

I saw in the test run that not all these tests are failing at each run, are you sure these acceptance tests are at this state?

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
