### PR TITLE
Add tests around how plugin framework provider configuration code handles `impersonate_service_account`, `impersonate_service_account_delegates` values

### PR DESCRIPTION
**Pull request by SarahFrench**
### `impersonate_service_account`
- [x] Add test cases to match [existing impersonate_service_account SDK tests](https://github.com/hashicorp/terraform-provider-google/blob/5086ae311f097e15acb43812ec4ae131f5792ccb/google/provider/provider_internal_test.go#L369-L417)
- [x] Ensure tests present about handling empty strings (will not be passing, add link to related issue)
- [x] Ensure tests present about handling Unknown values (will not be passing, add link to related issue)

### `impersonate_service_account_delegates`
- [x] Add test cases to match [existing impersonate_service_account_delegates SDK tests](https://github.com/hashicorp/terraform-provider-google/blob/5086ae311f097e15acb43812ec4ae131f5792ccb/google/provider/provider_internal_test.go#L471-L513)
- [x] Ensure tests present about handling empty strings (will not be passing, add link to related issue)
- [x] Ensure tests present about handling Unknown values (will not be passing, add link to related issue)

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
May I quickly ask which use cases did the tests cover? Or why it's necessary to match existing tests?

**Comment by SarahFrench** [comment]
Hi @hao-nan-li  - thanks for your questions, I overlooked that I should have put more context on the PR description.

The Google provider is currently "muxed" , meaning that it is written using a mix of both the SDK and the plugin framework (PF). In the future the provider will hopefully be fully migrated to using the plugin framework, as it contains new features and addresses some issues in how the SDK works.

What muxing means for us as maintainers of the Google provider is that there are two parallel implementations of the core provider configuration code ([see SDK provider schema here](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/provider/provider.go#L125), [see PF version here](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/fwprovider/framework_provider.go#L62)). [This function in the SDK code](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/provider/provider.go#L1651) takes in a user's provider config information to configure the provider, and [this is the equivalent function written using the plugin framework](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/fwtransport/framework_config.go#L156). They should contain the same logic and behave the same way from a user's perspective.

When a user runs terraform plan/apply both the SDK and PF versions of the provider run their configuration logic. This means even if someone isn't using a resource/data source that's implemented using the PF in their Terraform configuration they can be impacted by issues in the PF version of the config code. An example of this is that if a user set `credentials = ""` in their provider block in the past that empty string was ignored by Terraform and any relevant ENV-supplied values would be used instead. After muxing, those empty strings were un-ignored and caused problems for some users ([see github issue here](https://github.com/hashicorp/terraform-provider-google/issues/14255)).

When muxing was implemented there weren't tests like the one's I'm adding in this PR. These tests assert that the SDK and PF versions of the provider configuration code behave the same way by matching test cases in tests that already exist for the SDK config code. These tests can protect against defects, like accidentally changing the order that ENVs are used in to set a given argument in the provider's config, or to detect issues like the  `credentials = ""`  issue above where we need to consciously make the PF code behave in a more SDK-like way.

**Comment by SarahFrench** [comment]
These are the [SDK test's test cases for how `impersonate_service_account` is handled](https://github.com/hashicorp/terraform-provider-google/blob/5086ae311f097e15acb43812ec4ae131f5792ccb/google/provider/provider_internal_test.go#L369-L417), and these are the SDK test cases for [`impersonate_service_account_delegates`](https://github.com/hashicorp/terraform-provider-google/blob/5086ae311f097e15acb43812ec4ae131f5792ccb/google/provider/provider_internal_test.go#L471-L513).

The test's I've added in this PR are addressing the same scenarios like 'does an ENV overrule a value set directly in the config?'.

Some test cases are commented out, and above them are links to GitHub issues describing why they don't pass currently and why they should be fixed to pass soon (I'll address those issues once the tests are present in the provider).

**Comment by hao-nan-li** [comment]
> Hi @hao-nan-li - thanks for your questions, I overlooked that I should have put more context on the PR description.
> 
> The Google provider is currently "muxed" , meaning that it is written using a mix of both the SDK and the plugin framework (PF). In the future the provider will hopefully be fully migrated to using the plugin framework, as it contains new features and addresses some issues in how the SDK works.
> 
> What muxing means for us as maintainers of the Google provider is that there are two parallel implementations of the core provider configuration code ([see SDK provider schema here](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/provider/provider.go#L125), [see PF version here](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/fwprovider/framework_provider.go#L62)). [This function in the SDK code](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/provider/provider.go#L1651) takes in a user's provider config information to configure the provider, and [this is the equivalent function written using the plugin framework](https://github.com/hashicorp/terraform-provider-google/blob/76738202c9bea7fa6e7901915edde1253b85f515/google/fwtransport/framework_config.go#L156). They should contain the same logic and behave the same way from a user's perspective.
> 
> When a user runs `terraform plan/apply` both the SDK and PF versions of the provider run their configuration logic. This means even if someone isn't using a resource/data source that's implemented using the PF in their Terraform configuration they can be impacted by issues in the PF version of the config code. An example of this is that if a user set `credentials = ""` in their provider block in the past that empty string was ignored by Terraform and any relevant ENV-supplied values would be used instead. After muxing, those empty strings were un-ignored and caused problems for some users ([see github issue here](https://github.com/hashicorp/terraform-provider-google/issues/14255)).
> 
> When muxing was implemented there weren't tests like the one's I'm adding in this PR. These tests assert that the SDK and PF versions of the provider configuration code behave the same way by matching test cases in tests that already exist for the SDK config code. These tests can protect against defects, like accidentally changing the order that ENVs are used in to set a given argument in the provider's config, or to detect issues like the `credentials = ""` issue above where we need to consciously make the PF code behave in a more SDK-like way.

Thank you so much for the detailed explanation. I actually learned a lot from you by reading through this. Thanks for adding the tests in.

**Comment by SarahFrench** [comment]
I'm glad it was helpful and that I was able to knowledge share a bit!

> P.S Looks like there's some git conflicts.

Thanks - I just pushed https://github.com/GoogleCloudPlatform/magic-modules/pull/8818/commits/c80ab6fd3ce90a02cc26dc759ee38f45f38dd290 to address this. I have a bunch of draft PRs open that add tests to this file, so lots of merge conflicts are in my future 😭

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
