### PR TITLE
Configure the 'deletion protection' of Cloud SQL database instances

### PR DESCRIPTION
**Pull request by multani**
This allows to configure the "deletion protection" of Cloud SQL database instances.

fixes https://github.com/hashicorp/terraform-provider-google/issues/12344

This can be made a bit better, but it would require to pass the `d *schema.ResourceData` to `expandSqlDatabaseInstanceSettings` and set all the "settings" fields inside this function; but then it's not really an "expand" function anymore.
Let me know if you want to make this kind of change.

I haven't run the acceptance tests yet.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
sql: added the support for configuring "deletion protection" of Cloud SQL database instances
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Do you know the history surrounding this feature on the API? 

From my point of view what has happened is we added `deletion_protection` to protect a client from accidentally deleted their SQL database. The API added their own deletion protection. I'm wondering if you are familiar with how this API has evolved.

**Comment by multani** [comment]
@ScottSuarez No, I'm not aware of the evolution of the API on Google's side. I'm using the Google API since ~1 year and as far as I remember, it was always present, but I don't remember for sure.

I started my change with a new field inside `settings {}`, then I thought I could simply piggy-back on the `deletion_protection` field (which duplicates the Terraform built-in `lifecycle`'s `prevent_destroy` if I understand correctly).

If you think it's preferable not to piggy-back on `deletion_protection`, I'm happy to add the extra field somewhere else (probably `deletion_protection_enabled` as it's easier if it mirrors the official API?)

**Comment by ScottSuarez** [comment]
Seems the value [within the latest version of the package](https://github.com/googleapis/google-api-go-client/blob/main/sqladmin/v1beta4/sqladmin-gen.go#L3509),but it does [not exist](https://github.com/googleapis/google-api-go-client/blob/v0.82.0/sqladmin/v1beta4/sqladmin-gen.go#L3409-L3484) within a previous version. This means it's most certainly a new feature.

The build is failing because you are attempting to modify a field that may be null. Notice conditional assignment on `872` and modification on `874`. I would recommend extending `expandSqlDatabaseInstanceSettings` to add this functionality. Is there a reason you are not doing this?

**Comment by multani** [comment]
> Seems the value is [within the latest version of the package](https://github.com/googleapis/google-api-go-client/blob/main/sqladmin/v1beta4/sqladmin-gen.go?rgh-link-date=2022-08-19T22%3A32%3A56Z#L3509), but it does [not exist](https://github.com/googleapis/google-api-go-client/blob/v0.82.0/sqladmin/v1beta4/sqladmin-gen.go?rgh-link-date=2022-08-19T22%3A32%3A56Z#L3409-L3484) within a previous version. This means it's most certainly a new feature.

Indeed, [it actually seems very new](https://cloud.google.com/sql/docs/postgres/release-notes#August_15_2022):

image

**Comment by multani** [comment]
> I would recommend extending `expandSqlDatabaseInstanceSettings` to add this functionality. Is there a reason you are not doing this?

I discussed that a bit in my first post:

* If I reused the existing `deletion_protection`, I will need to change the signature of `expandSqlDatabaseInstanceSettings` to pass in the full schema; this will be a change compared to the other `expand*` functions.
* Otherwise, I can introduce a new flag in `settings`, as I mentioned in https://github.com/GoogleCloudPlatform/magic-modules/pull/6434#issuecomment-1221035922

I guess I'll just add the new flag: it will make the Terraform provider more consistent with the Google Cloud API and will also make the change less invasive overall.

**Comment by multani** [comment]
I'll try to reproduce the test failures locally, I don't have the permissions to read the output logs from the previous message.

**Comment by multani** [comment]
@ScottSuarez Is it possible to access the logs of the failing tests?

I get a whole bunch of failures on my local machine, but I really don't see how they are related to my change...

**Comment by ScottSuarez** [comment]
> > I would recommend extending `expandSqlDatabaseInstanceSettings` to add this functionality. Is there a reason you are not doing this?
> 
> I discussed that a bit in my first post:
> 
> * If I reused the existing `deletion_protection`, I will need to change the signature of `expandSqlDatabaseInstanceSettings` to pass in the full schema; this will be a change compared to the other `expand*` functions.
> * Otherwise, I can introduce a new flag in `settings`, as I mentioned in [Configure the 'deletion protection' of Cloud SQL database instances #6434 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/6434#issuecomment-1221035922)
> 
> I guess I'll just add the new flag: it will make the Terraform provider more consistent with the Google Cloud API and will also make the change less invasive overall.


Lets use existing deletion protection, you don't have to pass the whole schema, expanding just for this flag would be fine imo.

The tests are failing because the sql databases can no longer be deleted due `deletion_protection` being set to true.

**Comment by edwardmedia** [comment]
@multani I have added comments [over here](https://github.com/hashicorp/terraform-provider-google/issues/12344#issuecomment-1222457399) 
Thank you very much for the PR, but I think `deletion_protection` works, and your PR is not going to fix a `bug` with it. I world suggest you go ahead to file an [enhancement](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) with your PR so it can be triaged. Please keep in mind the chance to keep both `deletion_protection` and `deletionProtectionEnabled` in place is very small. While there are numerous existing users around the world who are already using `deletion_protection`, to keep them compatible is another thing you need to consider.

**Comment by ShubhamAvasthi** [comment]
I just happened to look at this PR, when going through open PRs in the repository.

I am from Cloud SQL team and I have already created a PR to integrate Terraform's existing deletion protection with Cloud SQL's newly released cross-surface accidental deletion protection.

This is the PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/6441

**Pull request closed without merging**
