### PR TITLE
Add workforce identity federation config to secure source manager ins…

### PR DESCRIPTION
**Pull request by umairidris**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
securesourcemanager: added `workforce_identity_federation_config` field to `google_secure_source_manager_instance` resource
```

### CODE REVIEW

**Comment by umairidris** [comment]
Note for reviewer: This field is not yet publicly available. This PR will be kept in draft mode until it is ready.

**Review by ScottSuarez — COMMENTED** [review]
I notice this PR is still in draft. Let me know if there is anything I can do to help

**Comment by umairidris** [comment]
Thanks @ScottSuarez for checking in, this PR is good to go, but we are waiting for the functionality to roll out. Will update this PR once it is ready.

**Comment by umairidris** [comment]
Hi @ScottSuarez thanks for your patience on this, this PR is ready for review.

**Comment by umairidris** [comment]
@ericpang777 Could you PTAL as well?

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
