### PR TITLE
Add support for spanner_database with IAM

### PR DESCRIPTION
**Pull request by iyabchen**
Added spanner database IAM validator support. 
Downstream change is in https://github.com/GoogleCloudPlatform/terraform-validator/pull/388

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Added spanner database IAM validator support
```

### CODE REVIEW

**Comment by iyabchen** [comment]
close since the change should go to magic module

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
@melinath could you help to do a pass here? Things look okay to me but I am wondering why we need to explicitly copy the iam files. Can't these be auto generated?

**Comment by ScottSuarez** [comment]
ah I see it appears we don't currently have iam resources generated for this so we are manually creating this file. I wonder if it would be better practice to add iam support for terraform/mmv1 first. ala 2 birds one stone. Although the work here is already done.

**Comment by melinath** [comment]
@ScottSuarez it looks like the iam resources are already in TPG: https://github.com/hashicorp/terraform-provider-google/blob/d8b8c528b1487e91f16c5345abbc578b2ec0e0c0/google/provider.go#L1257

This PR seems to re-use the handwritten IAM updater that's also used for TPG, but the conversion code does have to be handwritten.

**Comment by ScottSuarez** [comment]
ah, got it ~ !

Everything else looks okay to me then as far as I can tell

**Pull request merged**
