### PR TITLE
feat: Add Pub/Sub Topic support for changing schema settings

### PR DESCRIPTION
**Pull request by kamalaboulhosn**
Allows topic schema settings to be change since that is now supported in the service. Partially resolves https://github.com/hashicorp/terraform-provider-google/issues/13997.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
pubsub: Allowed `schema_settings` of `google_pubsub_topic` to change without deleting and recreating the resource
```

### CODE REVIEW

**Review by SarahFrench — COMMENTED** [review]
👋 This looks good, though it'd be nice to update an acceptance test to reflect that this field can be updated now.

This could either be a new acceptance test or an addition to [existing handwritten acceptance tests](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_pubsub_topic_test.go). For example you could update the `testAccPubsubTopic_update` function, referenced in the [TestAccPubsubTopic_update](https://github.com/GoogleCloudPlatform/magic-modules/blob/25c15224ddc4ef250e6df06c70c1ec2ab30bd644/mmv1/third_party/terraform/tests/resource_pubsub_topic_test.go#L11) test, to create two `google_pubsub_schema` resources and make the `google_pubsub_topic` resource reference the 1st schema. Then `testAccPubsubTopic_updateWithRegion` could be updated similar to the above but have the topic reference the 2nd schema instead.

Once that's done I'm happy to merge

**Comment by SarahFrench** [comment]
Thanks for the new test - I'll return to this tomorrow to review as I'm EOD in the UK

**Comment by kamalaboulhosn** [comment]
@SarahFrench I ended up adding a new test just to keep the purpose of each test relatively isolated.

**Review by SarahFrench — APPROVED** [review]
This is great, thanks for the new test - merging now

**Comment by SarahFrench** [comment]
(Checks that are failing aren't related to this PR - VCR test failures are unrelated, and `magic-modules-pre-build-validation` is complaining about YAML linting issues in files unrelated to this PR)

**Pull request merged**
