### PR TITLE
Promoted `managed_prometheus` field in google_container_cluster` to GA

### PR DESCRIPTION
**Pull request by IIBenII**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted `managed_prometheus` field in google_container_cluster` to GA
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Do you know if we have tests on `managed_prometheus`? If so, can we promote the corresponding tests to GA as well; If not, would you mind adding a test / modifying an existing one? Please let me know if you have any questions!

**Comment by IIBenII** [comment]
> Do you know if we have tests on `managed_prometheus`? If so, can we promote the corresponding tests to GA as well; If not, would you mind adding a test / modifying an existing one? Please let me know if you have any questions!

Test already exists I just remove the flag beta

**Comment by IIBenII** [comment]
@shuyama1 I'm sorry i don't have access to it. Everything ok?

**Comment by shuyama1** [comment]
Tests failed due to:
```
provider_test.go:307: Step 7/16 error: Error running pre-apply refresh: exit status 1
2022/11/28 21:06:40 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.17.2
Error: expected monitoring_config.0.enable_components.4 to be one of [SYSTEM_COMPONENTS APISERVER CONTROLLER_MANAGER SCHEDULER], got WORKLOADS
on terraform_plugin_test.tf line 8, in resource "google_container_cluster" "primary":
8:          enable_components = [ "SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER", "WORKLOADS" ]
testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
2022/11/28 21:06:41 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.17.2
Error: expected monitoring_config.0.enable_components.4 to be one of [SYSTEM_COMPONENTS APISERVER CONTROLLER_MANAGER SCHEDULER], got WORKLOADS
on terraform_plugin_test.tf line 8, in resource "google_container_cluster" "primary":
8:          enable_components = [ "SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER", "WORKLOADS" ]
--- FAIL: TestAccContainerCluster_withMonitoringConfig (1094.60s)
FAIL
```

Did you happen to run the test against GA provider locally? If so, are you able to get them passed?

**Comment by IIBenII** [comment]
It's because inside the function `testAccContainerCluster_withLoggingConfigUpdated` the attributes `enable_components` has value `WORKLOADS`. This attributes is only in Beta and will be deprecated in GKE 1.24 https://cloud.google.com/stackdriver/docs/solutions/gke/workload-metrics

I think it's safe to remove the value in the test. Are you agree?

**Comment by shuyama1** [comment]
Thanks for the update. That sounds reasonable! Or we can keep this test step in beta (keep the beta flag) and add a new step in the test with `managed_prometheus` in GA. Just want to be extra cautious and make sure we will be able to catch any errors caused by deprecation in the future.

**Comment by IIBenII** [comment]
Ok got it, I pushed a version without workload just to make sure everything is ok. I will try tomorrow to add this new test, not ho, but I'll figure it out.

**Comment by IIBenII** [comment]
@shuyama1 the last version, I pushed, tests run without errors locally. Can you check on your CI if it's ok? Thanks 🙏

**Comment by IIBenII** [comment]
@shuyama1 everything is ok ?

**Comment by shuyama1** [comment]
Thanks for the ping! GA test passed https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/356471?buildTab=tests&status=passed

**Review by shuyama1 — APPROVED** [review]
Thank you!

**Pull request merged**
