### PR TITLE
Mark KMS Key as update for PubSub Topic

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/6386 

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
pubsub: marked `kms_key_name` field in `google_pubsub_topic` as updatable
```

### CODE REVIEW

**Comment by upodroid** [comment]
Testing with another KMS key is kind of annoying, there is only one key that is bootstrapped.

PATCH does work though
```
 REDACTED  MCW0CDP3YY  ~  ERROR  $  gcloud pubsub topics update devtest --topic-encryption-key=projects/REDACTED/locations/global/keyRings/kms-ring/cryptoKeys/key --log-http
=======================
==== request start ====
uri: https://pubsub.googleapis.com/v1/projects/REDACTED/topics/devtest?alt=json
method: PATCH
== headers start ==
b'accept': b'application/json'
b'accept-encoding': b'gzip, deflate'
b'authorization': --- Token Redacted ---
b'content-length': b'182'
b'content-type': b'application/json'
b'user-agent': b'google-cloud-sdk gcloud/321.0.0 command/gcloud.pubsub.topics.update invocation-id/b1f5e819d09b403fa3cd905473b31730 environment/None environment-version/None interactive/True from-script/False python/3.8.5 term/xterm-256color (Macintosh; Intel Mac OS X 19.6.0)'
== headers end ==
== body start ==
{"topic": {"kmsKeyName": "projects/REDACTED/locations/global/keyRings/kms-ring/cryptoKeys/key", "name": "projects/REDACTED/topics/devtest"}, "updateMask": "kmsKeyName"}
== body end ==
==== request end ====
---- response start ----
status: 200
-- headers start --
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Encoding: gzip
Content-Type: application/json; charset=UTF-8
Date: Tue, 05 Jan 2021 22:48:59 GMT
Server: ESF
Transfer-Encoding: chunked
Vary: Origin, X-Origin, Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
-- headers end --
-- body start --
{
  "name": "projects/REDACTED/topics/devtest",
  "messageStoragePolicy": {
    "allowedPersistenceRegions": [
      "europe-west2"
    ]
  },
  "kmsKeyName": "projects/REDACTED/locations/global/keyRings/kms-ring/cryptoKeys/key"
}

-- body end --
total round trip time (request+response): 1.429 secs
---- response end ----
----------------------
Updated topic [projects/REDACTED/topics/devtest].

```

**Comment by upodroid** [comment]
bump

**Comment by slevenick** [comment]
Looks like this needs to be merged or rebased off master to fix conflicts, otherwise should be good to go

**Comment by upodroid** [comment]
Rebased

**Comment by upodroid** [comment]
Bump

**Review by slevenick — APPROVED** [review]
Thanks!

**Pull request merged**
