### PR TITLE
Google Container Filesystem (GCFS) configuration support

### PR DESCRIPTION
**Pull request by paulbsch**
Google Container Filesysem (GCFS) recently went GA and GcfsConfig is now available with the release of google-api-go-client v0.60.0:
https://github.com/googleapis/google-api-go-client/releases/tag/v0.60.0

If this PR is for Terraform, I acknowledge that I have:

- [ X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added `gcfs_config` to `node_config` of `google_container_node_pool` resource
```

### CODE REVIEW

**Comment by paulbsch** [comment]
Some of the checks are likely failing due to needing:
google.golang.org/api v0.60.0

**Comment by rileykarson** [comment]
We'll need to update the copied `go.sum` alongside the change to `go.mod.erb`. To do that you can open one of the `terraform-provider` repos, run `go get` and `go mod tidy`, and copy over the new `go.sum` file replacing the existing one.

**Comment by rileykarson** [comment]
Hmm -let me try that again, the bot should have commented.

/gcbrun

**Comment by rileykarson** [comment]
Hmm- not sure how I feel about a couple of the errors that persisted after the recording step, running a test (https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215428?buildTab=overview)

**Comment by rileykarson** [comment]
Didn't fail on a subsequent run. Weird!

**Pull request merged**
