### PR TITLE
Sync 5.0.0 with main

### PR DESCRIPTION
**Pull request by c2thorn**
Syncing up to 4.84.0 cut + [Migrate tpg-test to go](https://github.com/GoogleCloudPlatform/magic-modules/commit/df0c808786447821e0c2dd263b9e61583db7698c) commit

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by c2thorn** [comment]
@shuyama1 do you think TestAccSecurityCenterProjectCustomModule_sccProjectCustomModuleBasicExample is related?

**Comment by shuyama1** [comment]
I think it's added from one of the sync commits. I copied the cassettes over from main. I think it should be good now. We can merge the PR if it's urgent; otherwise, we can rerun to to make sure the test passes.

**Review by shuyama1 — APPROVED** [review]

**Comment by c2thorn** [comment]
@shuyama1 merging now to unblock others

**Pull request merged**
