### PR TITLE
Bridge gap between Terraform and API for AlloyDB

### PR DESCRIPTION
**Pull request by GauravJain21**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

#### This PR contains multiple changes for AlloyDB cluster, instance, and backup. It adds all the attributes which were missing in Terraform but were present in REST API for these resources and the corresponding tests.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
alloydb: added additional fields to `google_alloydb_instance` and `google_alloydb_backup`

```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Can you add a test that sets this field? You can just add the field to an existing test

**Comment by GauravJain21** [comment]
sure.

**Comment by GauravJain21** [comment]
Most of the fields are output only or are not yet supported by the GET API. Added tests for other fields.

**Review by slevenick — COMMENTED** [review]
Looks like the tests hit transient internal errors. Do you know if these were really transient or caused by the test configs somehow?

You can push a new commit to rerun tests

**Comment by GauravJain21** [comment]
Hey Sam,
These tests are working fine on my machine. When I look at the debug logs, I am seeing transient error for the networking service (not AlloyDB). Any idea what to do?
``` 
Error waiting for Create Service Networking Connection: Error code 9, message: encountered some transient internal error, please try again later
```

**Comment by slevenick** [comment]
> Hey Sam, These tests are working fine on my machine. When I look at the debug logs, I am seeing transient error for the networking service (not AlloyDB). Any idea what to do?
> 
> ```
> Error waiting for Create Service Networking Connection: Error code 9, message: encountered some transient internal error, please try again later
> ```

I'm seeing some recent service networking changes that might be causing this. I'll ask around

**Comment by slevenick** [comment]
I think this is being tracked here and is unrelated to your changes: https://github.com/GoogleCloudPlatform/magic-modules/pull/8904

**Comment by GauravJain21** [comment]
Thank you so much for the update, Sam! :D

**Comment by GauravJain21** [comment]
Hey Sam,

As these two are passing on my local machine and the debug log suggest that it is an issue with the service networking, I have commented out these two tests for now. I will re-enable them once this issue from service networking team is fixed.

I have created b/301367801 to track it.

Can you please approve and merge the PR?

**Review by slevenick — CHANGES_REQUESTED** [review]
One small request, can you change the changelog to be formatted in our release notes format: https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/

Then I'll approve and merge

**Comment by GauravJain21** [comment]
done.

**Comment by slevenick** [comment]
> done.

See https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/#type-specific-guidelines-and-examples

And existing release notes: https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md

It should look like:

```release-note:enhancement
alloydb: added `x` field(s) to `y` resource
```

**Comment by GauravJain21** [comment]
updated as per suggested. please check and let me know if it looks good.

**Review by slevenick — APPROVED** [review]

**Review by slevenick — CHANGES_REQUESTED** [review]
Can you add these fields to tests as suggested by https://github.com/GoogleCloudPlatform/magic-modules/pull/8781#issuecomment-1728893928

**Comment by GauravJain21** [comment]
These fields are part of the tests which I have commented out. I will enable them once service networking issue is resolved and they will cover these fields.

**Review by slevenick — APPROVED** [review]

**Comment by GauravJain21** [comment]
Hey Sam,
Can you please merge it? I don't have the permission to merge.

**Pull request merged**
