### PR TITLE
Remove references to deprecated `google_datastore_index` feature.

### PR DESCRIPTION
**Pull request by vadimyushprakh**
Remove references to deprecated `google_datastore_index` feature.

Googlers, see b/347992152

fixes https://github.com/hashicorp/terraform-provider-google/issues/19149

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
datastore: `google_datastore_index` has been removed in favor of `google_firestore_index`
```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
Could you also add an entry in this 6.0.0 changelog? https://github.com/GoogleCloudPlatform/magic-modules/blob/FEATURE-BRANCH-major-release-6.0.0/mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown

**Comment by c2thorn** [comment]
> Could you also add an entry in this 6.0.0 changelog? [`FEATURE-BRANCH-major-release-6.0.0`/mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown](https://github.com/GoogleCloudPlatform/magic-modules/blob/FEATURE-BRANCH-major-release-6.0.0/mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown?rgh-link-date=2024-08-15T16%3A28%3A59Z)

Yes and please mention what users are supposed to use instead of `google_datastore_index` in the upgrade guide and release note. (with the `breaking-change` tag instead of `deprecation`)

**Comment by vadimyushprakh** [comment]
Addressed PR feedback:  updated description to `breaking-change` and added an entry to `version_6_upgrade.html.markdown`

**Review by hao-nan-li — COMMENTED** [review]
Looks like you removed the only resource from the `datastore` product, could you remove the entire product?

**Review by rwhogg — APPROVED** [review]

**Comment by vadimyushprakh** [comment]
> Looks like you removed the only resource from the `datastore` product, could you remove the entire product?

Removed. Thank you!

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
