### PR TITLE
Set override_value to 0 when not returned by the API

### PR DESCRIPTION
**Pull request by c2thorn**
Upstreams https://github.com/hashicorp/terraform-provider-google-beta/pull/2985

`default_if_empty` custom flattener will not work here since `override_value` is required and has no default value

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
serviceusage: fixed an issue in `google_service_usage_consumer_quota_override` where setting the `override_value` to 0 would result in a permanent diff
```

### CODE REVIEW

**Review by melinath — APPROVED** [review]
LGTM. Do you think we should have a new test case for this change? The test failure seems to be a more general failure but it is on one of the resources changed so I don't know if you want to make sure it runs - I think Riley was in the process of fixing it.

**Comment by melinath** [comment]
Out of curiosity, would it be possible to set a `default_value` even though `override_value` is required, and then use the default_if_empty flattener?

**Comment by melinath** [comment]
Ah, [terraform prevents `Default` if `Required` is `true`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#default).

**Comment by c2thorn** [comment]
Not sure why it failed in post_destroy, it passed locally. I'll try one more time?

**Comment by c2thorn** [comment]
The test I happened to copy and slightly modify is also just flakey:
https://ci-oss.hashicorp.engineering/project.html?tab=testDetails&testNameId=5541498329625519986&projectId=GoogleCloudBeta&buildTypeId=GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject

**Comment by c2thorn** [comment]
The flakiness my test and the existing `TestAccServiceUsageConsumerQuotaOverride_consumerQuotaOverrideExample` seems to be in the Test destroy producer: https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_service_usage_consumer_quota_override_generated_test.go#L141

The resource deletes, but when we check to make sure it deleted in the destroy producer, the API sometimes reports that the resource still exists. So there is some eventual consistency here. 

Not sure what the correct approach would be here. We have polling autogeneration in MMv1 that is possible: https://github.com/hashicorp/terraform-provider-google/wiki/Developer-Best-Practices#polling
but when I tried that out, it added a bunch of code that affected more than just the delete function. I think that goes outside of the scope of this PR. I could add handwrite the polling in the resource's delete function, or handwrite the destroy producer to poll/just skip checking in general. Or I could create an issue to tackle the flakiness later. What do you think @melinath

**Comment by melinath** [comment]
TIL about that wiki page. Thanks!

I think doing the more thorough fix as a separate issue sounds like the way to go.

**Comment by c2thorn** [comment]
Added. Let's try one more VCR recording. Surely I'll get lucky this time

**Pull request merged**
