### PR TITLE
upgraded dcl

### PR DESCRIPTION
**Pull request by avinash84**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `psc_connection_id` and `psc_connection_status` output fields to `google_compute_forwarding_rule` and `google_compute_global_forwarding_rule` resources
```
```release-note:enhancement
containeraws: made `config.instance_type` field updatable in `google_container_aws_node_pool`
```

### CODE REVIEW

**Review by shuyama1 — CHANGES_REQUESTED** [review]
Thanks for making the changes.
Looks like the PR removes `ForceNew` from `instance_type` field in `google_container_aws_node_pool` resource. Would you mind creating a new test / modifying an existing test to verify the update functionality of this field?
The other two fields added in `google_compute_global_forwarding_rule` and `google_compute_global_forwarding_rule` resources are output-only, which seems fine.

**Comment by shuyama1** [comment]
The failed tests seem unrelated to the changes in this PR

**Review by shuyama1 — CHANGES_REQUESTED** [review]
Looks like we are modifying the field `instance_type` in `google_container_aws_cluster` resource in the test. The actual field we want to test is the one in `google_container_aws_node_pool`, which is located at https://github.com/GoogleCloudPlatform/magic-modules/pull/6124/files#diff-8e948ccc53332078f1c953abb3da1451169a54388c19b1146507dab6c104813eL99 and https://github.com/GoogleCloudPlatform/magic-modules/pull/6124/files#diff-8b7068533bec8cf221a4ac85ffe16fc5d934fdb119acf3197cbffd85ff10f4c6L99.
Sorry for not noticing this earlier.

**Comment by avinash84** [comment]
My commit actually shows modification in 
tpgtools/overrides/containeraws/samples/nodepool/basic_update.tf.tmpl
tpgtools/overrides/containeraws/samples/nodepool/beta_basic_update.tf.tmpl

Diff link-
https://github.com/GoogleCloudPlatform/magic-modules/pull/6124/files

**Comment by shuyama1** [comment]
> My commit actually shows modification in tpgtools/overrides/containeraws/samples/nodepool/basic_update.tf.tmpl tpgtools/overrides/containeraws/samples/nodepool/beta_basic_update.tf.tmpl
> 
> Diff link- [#6124 (files)](https://github.com/GoogleCloudPlatform/magic-modules/pull/6124/files)

Sorry, looks like the link in my comment does not point to the correct line. The actual change should be the field `instance_type ` at Line 99 in both files. Sorry for the confusion.

**Review by shuyama1 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
