### PR TITLE
Add Update Connector Support for VPC Access Connectors

### PR DESCRIPTION
**Pull request by jashansudan**
Adds support for updating Serverless VPC Connectors.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
vpcaccess: added support for updates to `google_vpc_access_connector` resource
```

### CODE REVIEW

**Comment by jashansudan** [comment]
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Breaking Change(s) Detected
> The following breaking change(s) were detected within your pull request.
> 
> * Field `max_throughput` default value changed from 300 to  on `google_vpc_access_connector` - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-changing-default-value)
> * Field `min_throughput` default value changed from 200 to  on `google_vpc_access_connector` - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-changing-default-value)
> 
> If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8205-old..auto-pr-8205) ( 5 files changed, 188 insertions(+), 9 deletions(-)) Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8205-old..auto-pr-8205) ( 5 files changed, 188 insertions(+), 9 deletions(-)) TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8205-old..auto-pr-8205) ( 4 files changed, 15 insertions(+), 7 deletions(-)) TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8205-old..auto-pr-8205) ( 2 files changed, 4 insertions(+))

I discussed with the terraform team and I believe this change should not be breaking.

**Review by SarahFrench — APPROVED** [review]
Hi @jashansudan, thanks for your patience when waiting for my review 🙏 . 

I can see via the acceptance test that the three mutable fields can be updated successfully. And thank you for checking about the suspected breaking changes in relation to default values.

Also, I confirmed that updates where the values of `min_instances` and `max_instances` are reduced results in a forced replacement of the resource. The testing framework doesn't expose an easy way to assert whether an update or force-replace action occurs, and workarounds usually need access to a "create_time" field (which this resource lacks). Because of this, I'm happy to merge this PR without a test that checks the behaviour introduced via `resource_definition`.

**Comment by SarahFrench** [comment]
I'm going to re-run the acceptance tests in our CI, as I can see it timed out previously. The new test added in this PR passed when I ran it locally, so I don't expect any issues, but it would be good to have the test pass here before merging.

/gcbrun

**Review by SarahFrench — CHANGES_REQUESTED** [review]
It's a good thing I re-ran the tests, as a couple of failing tests are linked to this PR. Are you able to access the error message and debug [logs linked in this message](https://github.com/GoogleCloudPlatform/magic-modules/pull/8205#issuecomment-1629117086)?

The tests that appear linked to this PR's changes are:
- TestAccVPCAccessConnector_vpcAccessConnectorExample
    - Error = _"Operation failed: Invalid IP CIDR range was provided. It conflicts with an existing subnetwork. Please delete the connector manually."_
    - I'm not sure if it's something we can fix in this PR directly
- TestAccCloudFunctionsFunction_vpcConnector
    - Error = _"A Connector must specify either max_throughput or max_instances."_
    - [edits to this file](https://github.com/GoogleCloudPlatform/magic-modules/blob/c763482c7973c306367365255071afdf8094b365/mmv1/third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb) should address that failure
- TestAccAppEngineStandardAppVersion_update
    - Error = _"A Connector must specify either max_throughput or max_instances."_
    - [edit to this file](https://github.com/GoogleCloudPlatform/magic-modules/blob/c763482c7973c306367365255071afdf8094b365/mmv1/third_party/terraform/tests/resource_app_engine_standard_app_version_test.go) will address this

**Comment by jashansudan** [comment]
I've went ahead and hopefully fixed all the tests.

**Comment by SarahFrench** [comment]
Looks like the tests are all fixed, thanks! The two tests that failed above are unrelated to this PR.

I'm seeing an unexpected diff in the diff report - affecting the [.teamcity/components/generated/services.kt](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8205-old..auto-pr-8205#diff-9421d7cb744b78bbc26263ee07b4dc7dd8af369aa764c9c8ae60092973752358) file in the GA provider repo. That file is generated based on the service package directories present in the provider, and there were some new service packages created since this PR was started. Usually we'd ask for PRs to be rebased but in this case I believe that the unexpected diff won't actually happen after merging this PR. I want to test my understanding, so will approve and merge.

Thanks for your patience!

**Review by SarahFrench — APPROVED** [review]

**Comment by SarahFrench** [comment]
Ah, main branch is currently protected to help preparation of a patch release. I'll merge once it's possible.

**Pull request merged**
