### PR TITLE
Add type support

### PR DESCRIPTION
**Pull request by ron-gal**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigtable: added support for `column_family.type` in `google_bigtable_table`
```

### CODE REVIEW

**Comment by c2thorn** [comment]
Hey @ron-gal feel free to ping me when this is ready for review. I'm going to turn of notifications on this in the meantime

**Comment by ron-gal** [comment]
This PR's build is broken until we update to bigtable go client 1.30 that isn't out yet. Once out and updated - this PR is ready to go

**Review by c2thorn — COMMENTED** [review]
noting that I ran the test in TC and also ran a manual update test

**Review by c2thorn — CHANGES_REQUESTED** [review]
needs documentation, otherwise lgtm

**Comment by ron-gal** [comment]
> needs documentation, otherwise lgtm

Done :)

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
