### PR TITLE
Stateful MIG -> GA

### PR DESCRIPTION
**Pull request by melinath**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/7323.

Stateful MIG is controlled with PerInstanceConfig and RegionPerInstanceConfig. This PR makes those both available in GA as well as related utilities and tests.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Marked `stateful_disk` as GA in `google_compute_ instance_group_manager` 
```
```release-note:enhancement
compute: Marked `stateful_disk` as GA in `google_compute_ region_instance_group_manager` 
```
```release-note:enhancement
compute: Marked `google_compute_ per_instance_config` as GA
```
```release-note:enhancement
compute: Marked `google_compute_ region_per_instance_config` as GA
```

### CODE REVIEW

**Comment by rileykarson** [comment]
@melinath: Let me know if you'd like me to review this, or if you'd already had a reviewer in mind! You can register yourself on [this list](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/containers/contributor-checker/check-contributor.sh#L32-L34) so that the robot doesn't randomly pick one for you.

**Comment by melinath** [comment]
@rileykarson I didn't have a reviewer in mind; I can definitely reassign it if you prefer! I'll make a separate PR to remove myself from that list. :-)

**Review by rileykarson — COMMENTED** [review]
Generally looks good- using [a test run](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/150046) to double check, since VCR failed (due to unrelated reasons).

Just one small thing- you'll want to update the documentation for Instance Group Manager + the regional variant so that fields aren't unnecessarily marked as beta. See https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#stateful_disk for example.

I'd refer to specific resources (for newly GA resources) or fields in the changelog message as well, instead of the feature as whole. You can attach multiple messages to a single PR by specifying the `release-note` block multiple times, if that helps. For example, a recent field in GKE was noted as `container: marked workload_metadata_config as GA in google_container_node_pool`

**Comment by melinath** [comment]
Updated the docs to not mark stateful_disk as Beta and also updated api docs links to point to v1 instead of beta.

**Review by rileykarson — APPROVED** [review]
LGTM!

Just a couple small notes on the release notes. You'll want to break the release note up from one note with multiple lines to multiple notes with one line each (this will format the final changelog a little better), a la:

```release-note:enhancement
compute: Marked `stateful_disk` as GA in `instance_group_manager` 
```

```release-note:enhancement
compute: Marked `stateful_disk` as GA in `region_instance_group_manager` 
```

```release-note:enhancement
compute: Marked `per_instance_config` as GA
```

```release-note:enhancement
compute: Marked `region_per_instance_config` as GA
```

When referring to resource names, I'd use the full name of the resource as well. For these resources, that's including the `google_compute_` prefix, eg

```release-note:enhancement
compute: Marked `stateful_disk` as GA in `google_compute_instance_group_manager` 
```

**Comment by melinath** [comment]
@rileykarson I've updated the release notes section; thanks! It looks like the next step is that you would run the magician to generate downstream PRs and then, if those are approved, all the PRs get merged. Is that correct?

**Comment by rileykarson** [comment]
Ah- there may be a guide we need to update somewhere. The Magician generates diffs downstream (https://github.com/GoogleCloudPlatform/magic-modules/pull/4047#issuecomment-702987827 for example) but doesn't create pull requests until post-merge these days. Approval on the MM pr is enough (a practice we ended up adopting even when there *were* downstream PRs).

Once you've merged this PR, the Magician will asynchronously create and automatically merge PRs against each repo that had a diff in the diff comment.

**Pull request merged**
