### PR TITLE
Composer v2 GA

### PR DESCRIPTION
**Pull request by kubasieron**
Add support for Cloud Composer v2 in GA.

fixes hashicorp/terraform-provider-google/issues/10615

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Add support for Cloud Composer v2 in GA.
```

### CODE REVIEW

**Review by melinath — COMMENTED** [review]
Commenting to remove from my review queue. Please [re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/) when this is ready.

**Comment by kubasieron** [comment]
Please review, all blockers are removed now

**Comment by kubasieron** [comment]
@melinath can you share with me out[uts/logs from failed tests

**Comment by melinath** [comment]
Okay, it looks like the composer v2 test passed in beta. I'm running it in GA as well here: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/232705

This is just to make sure it's passing in GA, no action needed from you at this time.

**Review by melinath — CHANGES_REQUESTED** [review]
The GA test run passed, so this should be fine to merge once the merge conflicts are resolved.

**Comment by melinath** [comment]
Cool, looks like VCR tests failed for unrelated reasons; here's a new run of the GA test to be safe: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/235481

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
