### PR TITLE
Added support for in-place update for `rotation.rotation_period` field in `google_secret_manager_secret`

### PR DESCRIPTION
**Pull request by abheda-crest**
Added support for the in-place update for the `rotation.rotation_period` field in `google_secret_manager_secret`
fixes https://github.com/hashicorp/terraform-provider-google/issues/13770

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
secretmanager: allowed update for `rotation.rotation_period` field in `google_secret_manager_secret` resource
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
```
        Error: Error updating Secret "projects/------/secrets/tf-test-secret-e0pv0ufn0u": Patch "https://secretmanager.googleapis.com/v1/projects/-------/secrets/tf-test-secret-e0pv0ufn0u?alt=json&updateMask=topics%2Crotation": Requested interaction not found
        
          with google_secret_manager_secret.secret-basic,
          on terraform_plugin_test.tf line 14, in resource "google_secret_manager_secret" "secret-basic":
          14: resource "google_secret_manager_secret" "secret-basic" {
```

**Comment by abheda-crest** [comment]
@ScottSuarez `TestAccSecretManagerSecret_rotationPeriodUpdate` was passing locally. Also, according to the [comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/8983#issuecomment-1726344733), this test passed in recording mode but failed in replaying mode due to non-determinism or randomness. I suspect that this might be due to passing a [generated timestamp](https://github.com/GoogleCloudPlatform/magic-modules/pull/8983/commits/b28de19903c033c4b2e367101c9b29a0931d66e1#diff-0d9f3a58beb28b76e0fe278896045e0ba169a10239dfa2664b6a98a6bbbf8a99R292). To confirm this, I've updated the test to pass a static timestamp.

**Comment by ScottSuarez** [comment]
Ah, yep that tracks !! Sorry for the confusion. I should of looked a little closer! Lets check the rerun.

**Comment by abheda-crest** [comment]
@ScottSuarez Could you please review the changes?

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
