### PR TITLE
Prepared new instance template example for inclusion on C.G.C.

### PR DESCRIPTION
**Pull request by arunoo**
Intending to use this example on the following page: https://cloud.google.com/compute/docs/instance-templates/create-instance-templates (Working with betsyl@)

If this PR is for Terraform, I acknowledge that I have:

[x ] Searched through the issue tracker for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
[x ] Generated Terraform, and ran make test and make lint to ensure it passes unit and linter tests.
[ x] Ensured that all new fields I added that can be set by a user appear in at least one example (for generated resources) or third_party test (for handwritten resources or update tests).
[x ] Ran relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
[ x] Read the Release Notes Guide before writing my release note below.

```release-note:none
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
This is an interesting case. @c2thorn is there any guidance here for adding a test to docs when the resource generation is disabled.

**Comment by c2thorn** [comment]
@ScottSuarez I don't think there's a precedent for this. If it's been excluded from Terraform, the `api.yaml` schema has probably not bee kept up to date with the handwritten version.

We may be able to get away with adding a `docs_only` variable or something to MMV1, but I'd have to look into that. Otherwise we won't be able to support examples for this resource. Give me a day or two.

**Comment by arunoo** [comment]
Thanks, Scott and Cameron!

BTW, I'm new here. I'm not sure what "resource generation is disabled" means. Perhaps I did something wrong with the snippet?

FYI: Instance templates are a standard Compute resource (eg, they are required to make managed instance groups), so I believe we should be able to support examples for instance templates in magic modules.

Please let me know if I can help in any way.

**Comment by c2thorn** [comment]
@arunoo Sorry for the confusion. This information should probably be bubbled up to the MM-C.G.C instructions... This is the first time we've run into this although it was bound to happen eventually.

 "resource generation is disabled" means that Magic Modules does not automatically generate the resource by using the information from `api.yaml` and `terraform.yaml` files. Which is why `exclude: true` is shown in the `terraform.yaml` for this resource. Because of its complexity, Compute Instance Template is managed manually by editing these handwritten files:
[Resource code](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/resources/resource_compute_instance_template.go.erb)
[Documentation](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/website/docs/r/compute_instance_template.html.markdown)
[Tests](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/tests/data_source_google_compute_instance_template_test.go)

Snippets for C.G.C are currently not supported for handwritten resources ([listed here](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/terraform/resources)). Since the code is split between multiple files for these, it'll be tricky to get these included and will most likely require a different process than MM-generated resources.

**Comment by betsy-lichtenberg** [comment]
I think we can work around this by adding region tags to the instance template that resides in region_autoscaler_basic.tf.erb and is documented at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_autoscaler.

We can modify the instance template to suit our purposes.

Please correct me if I'm wrong. Thanks!

**Comment by c2thorn** [comment]
@betsy-lichtenberg That is a great workaround, thanks! This works because this is a "basic" example, but more specialized uses may not always fit elsewhere. I've made an issue to investigate how we can include more handwritten resources in the future: https://github.com/hashicorp/terraform-provider-google/issues/10651

**Comment by c2thorn** [comment]
The relevant test `TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample` has passed in our CI

**Review by c2thorn — APPROVED** [review]

**Comment by c2thorn** [comment]
@arunoo your snippet now shows in https://github.com/terraform-google-modules/terraform-docs-samples/blob/master/region_autoscaler_basic/main.tf#L17

**Pull request merged**
