### PR TITLE
update BigqueryDatapolicy to ga

### PR DESCRIPTION
**Pull request by DrFaust92**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquerydatapolicy: promoted `google_bigquery_datapolicy_data_policy` to GA
```

### CODE REVIEW

**Review by shuyama1 — CHANGES_REQUESTED** [review]
Looks like we also need to bump the version in handwritten test `TestAccBigqueryDatapolicyDataPolicy_bigqueryDatapolicyDataPolicyUpdate` at mmv1/third_party/terraform/tests/resource_bigquery_datapolicy_data_policy_test.go.erb

**Comment by DrFaust92** [comment]
missed that, fixing

**Comment by shuyama1** [comment]
Running GA test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/352254

**Review by shuyama1 — COMMENTED** [review]
@DrFaust92 GA tests failed. Looks like the tests have dependency on `google_data_catalog_policy_tag` and `google_data_catalog_taxonomy` which are both beta resources.

**Comment by DrFaust92** [comment]
[shuyama1](https://github.com/shuyama1) luckily these are GAable so ill open another PR https://github.com/GoogleCloudPlatform/magic-modules/pull/6989

**Comment by shuyama1** [comment]
@DrFaust92 Thanks for making the updates. Please let me know if this PR is ready to review.
Plus, we recently split the product level `api.yaml` file to individual resource files. You'll likely need to move the code change in `api.yaml` file in this PR to each resource `.yaml` file. Sorry about it.

**Comment by DrFaust92** [comment]
@shuyama1 done

**Comment by shuyama1** [comment]
tpg unit test failed due to 
```
google/resource_bigquery_datapolicy_data_policy_test.go:18:17: undefined: TestAccProvidersOiCS
```

We'll likely need to change the test provider from `TestAccProvidersOiCS` to `TestAccProviders`, as `TestAccProvidersOiCS` is set up for beta-only tests

**Review by shuyama1 — CHANGES_REQUESTED** [review]
tpg unit test failed due to 
```
google/resource_bigquery_datapolicy_data_policy_test.go:18:17: undefined: TestAccProvidersOiCS
```

We'll likely need to change the test provider from `TestAccProvidersOiCS` to `TestAccProviders`, as `TestAccProvidersOiCS` is set up for beta-only tests

**Comment by shuyama1** [comment]
Kicked off GA tests at https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/382506.

**Review by shuyama1 — APPROVED** [review]
Thank you!

**Pull request merged**
