### PR TITLE
Operation polling now supports custom endpoints

### PR DESCRIPTION
**Pull request by smithson-google**
Tests: I ran `make testacc TEST=./google TESTARGS='-run=TestAccRedis' ` and got the following output: https://gist.github.com/smithson-google/92d8957671e9459424a1e5452eddf538. Tl;dr it passed on most tests. It only failed on tests which tried to use an API that hadn't been activated. I also ran a separate test with `TF_LOG=DEBUG` to make sure that HTTP requests were being sent as expected and they were. I didn't try to do my own testing with a custom endpoint, if necessary I can do that tomorrow.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
Fixed operation polling to support custom endpoints.
```

### CODE REVIEW

**Comment by melinath** [comment]
b/213639906

**Comment by melinath** [comment]
I'm going to kick off a /gcbrun. I suspect there may be some test failures, because it looks like some operations have a different base url than what might be configured for the product overall.

**Comment by smithson-google** [comment]
So I'm re-looking through the code and the only problem I can think of is that `async.operation.base_url` is a url which might get set for some base paths but not others. Do you have more context on the `async.operation.base_url` field?

**Review by melinath — CHANGES_REQUESTED** [review]
Okay, so the generated code all looks correct. However, looking at this more, it seems that the reason this works is that in all (current?) cases, async.operation.base_url is `{{op_id}}` and thus gets converted to `%s`. There are also cases (that don't seem to end up getting generated as code atm?) where async.operation.base_url is longer, like `projects/{{project}}/global/operations/{{op_id}}`. (Previously I was misreading the ruby code and thought that it was falling back to the operation base url.)

It would be great to replace the product base url with Config.WhateverBasePath but keep the substitution for the operation base url; otherwise operation base url could end up unintentionally becoming a (more) vestigial field.

**Comment by smithson-google** [comment]
Oops I think I made a typo. Fixing now

**Comment by smithson-google** [comment]
Okay, I think I fixed the typo. I'm generating the changes on my box to make sure now. I reintroduced the whole `flatten.join.gsub` pattern because that's basically how I found it and I assume the writer at the time had some concerns about any two of the values being passed in being arrays. So It might be unneccessary but it will catch that edge case if it's ever reintroduced in the future.

**Comment by melinath** [comment]
failures seem unrelated.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
