### PR TITLE
added excluded_fields and included_fields to data_loss_prevention_job_trigger resource

### PR DESCRIPTION
**Pull request by JayS-crest**
Added `included_fields` and `excluded_fields` to `data_loss_prevention_job_trigger` with relevent tests
fixes https://github.com/hashicorp/terraform-provider-google/issues/8807
fixes https://github.com/hashicorp/terraform-provider-google/issues/8838

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note: enhancement
dlp: added fields `included_fields` and `excluded_fields` to resource `google_data_loss_prevention_job_trigger`
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
some of the helper functions used in handwritten test files were recently moved to a separate package & made exportable - it looks like you're still using the old names, which is causing the tests to not compile. Please fix that :-)

**Review by melinath — APPROVED** [review]
LGTM. In general it would be preferred to combine all update tests into a single (longer) case rather than having one test per field, but since these seem to run quickly and there isn't a clear single update test already, not blocking on it.

That said, it would be great to consider doing a separate PR to combine these update tests & reduce boilerplate.

**Comment by melinath** [comment]
VCR failures are unrelated.

**Comment by JayS-crest** [comment]
> LGTM. In general it would be preferred to combine all update tests into a single (longer) case rather than having one test per field, but since these seem to run quickly and there isn't a clear single update test already, not blocking on it.
> 
> That said, it would be great to consider doing a separate PR to combine these update tests & reduce boilerplate.

Got it, I'll do a seperate PR in order to combine the tests.

**Pull request merged**
