### PR TITLE
Add note to schema for bigquery table docs

### PR DESCRIPTION
**Pull request by emilymye**
Related to https://github.com/terraform-providers/terraform-provider-google/issues/5262

### CODE REVIEW

**Comment by danawillow** [comment]
Also looks like you'll want to get a clean magician run before merging

**Comment by emilymye** [comment]
like, add a function? or is there a util im not aware of? I think I was planning to do this doc change and then make a future chnage if we wanted to add DSF - I might do that in a different PR?

**Comment by danawillow** [comment]
There's a util! I thought we used it in IAM policy so I found it but turns out we do a custom one there. https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/structure/suppress_json_diff.go is the one though, and yeah doing it separately is totally fine

**Comment by emilymye** [comment]
I'll probably do a seperate one and see if we can reuse it, I'm sure we have more JSON somewhere

**Pull request merged**
