### PR TITLE
Changed filename and region tag

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
This sample needs a more accurate filename and region tag.

```release-note:none
Release note
```

### CODE REVIEW

**Review by megan07 — APPROVED** [review]
LGTM! Thanks!

**Comment by betsy-lichtenberg** [comment]
> LGTM! Thanks!

Megan, will I need to manually update this file and path, or will it get updated as a result of this PR?

**Comment by megan07** [comment]
It should be updated as a result of this PR. I must have forgotten to merge earlier. Sorry! Merging now :)

**Comment by betsy-lichtenberg** [comment]
Can you merge this one, too?

https://github.com/terraform-google-modules/terraform-docs-samples/pull/136

**Pull request merged**
