### PR TITLE
Fix import issue for Dataplex Datascan

### PR DESCRIPTION
**Pull request by saurabh-net**
Fix import issue for Datascan Dataprofile scans with existing jobs.
The TopN value message was incorrectly encoded as a map instead of as a array.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
dataplex: fixed a bug when importing `google_dataplex_datascan` after running a job
```

### CODE REVIEW

**Comment by saurabh-net** [comment]
@hao-nan-li This is just a change in one of our output only fields. 
I don't believe it will lead to any breaking changes.
---

I don't actually think the Result message as a whole is useful for Terraform at all. If we want to just ignore the entire message, can we just choose not to specify the message in the YAML file?

For context, dataProfileResult shows the result of the latest Job run under a DataScan definition. I don't think this is ever useful in a Terraform context at all.

**Review by hao-nan-li — COMMENTED** [review]
Thanks for the explanation. Looks like this field is not marked as an output only field, so I may still consider it as a breaking-change. 

We are currently preparing for a major release, breaking changes are accepted following these instructions https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#contributing-to-the-next-major-release-500.

**Comment by saurabh-net** [comment]
In line 644, we mark the parent message as output: true.

Wouldn't that apply to all inner nested fields and messages?

**Comment by hao-nan-li** [comment]
> In line 644, we mark the parent message as output: true.
> 
> Wouldn't that apply to all inner nested fields and messages?

Sorry I missed the part from the parent.

On the other hand, could you take a quick look at https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#what-counts-as-a-breaking-change? **Changing the output format of a field** is part of it.

**Comment by saurabh-net** [comment]
Ahh, okay, i'm comfortable modifying my PR and waiting for it to be released with the next major version. Let me update that by end-of-day

---

One question I have is, if I don't believe the message is ever useful, can I simply remove the entire parent message (name: 'dataProfileResult') entirely from the YAML spec?

I'm aware that this would also be a breaking change, I'd just rather keep the YAML spec simple where I can.

**Comment by hao-nan-li** [comment]
> Ahh, okay, i'm comfortable modifying my PR and waiting for it to be released with the next major version. Let me update that by end-of-day
> 
> One question I have is, if I don't believe the message is ever useful, can I simply remove the entire parent message (name: 'dataProfileResult') entirely from the YAML spec?
> 
> I'm aware that this would also be a breaking change, I'd just rather keep the YAML spec simple where I can.

For us, not having output:true field in the yaml file is always an option. Note that you can create PRs with breaking-change. Just need to merge it against the 5.0.0 major release branch. https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#contributing-to-the-next-major-release-500

**Comment by saurabh-net** [comment]
Thanks for the confirmation. I've created a fresh pull request targeting the next major release.
Will close this one.

https://github.com/GoogleCloudPlatform/magic-modules/pull/8583

**Comment by saurabh-net** [comment]
@hao-nan-li @c2thorn 
I'm still working on removing the dataprofileresult and dataqualityresult fields outright in parallel to this.

---
Given that we have a customer blocked on us fixing this, I'd like to check again whether the fix in this PR should really be considered a breaking change.

Anyone currently trying to import a Dataprofile datascan would just run into TF crashing, i.e. they would not have any state in a different format like typical field format changes. There should not be any risk of incompatible states / formats stored anywhere.

I understand the general guidance around field format changes, but in this case:
- There should be no breaking change for any existing customers
- We would like to unblock users earlier than later
- We are moving to GA as a product soon (order of weeks), and this would affect other users as well 

To be clear, in this PR, I'd like to do the minimal change to unblock existing users. The larger change of removing dataprofileresult and dataqualityresult entirely is definitely safer to do in a new major version.

For additional context: https://github.com/GoogleCloudPlatform/magic-modules/pull/8583#issuecomment-1670351785

**Comment by c2thorn** [comment]
@saurabh-net Looks like `ignore_read` did not interact as I'd hoped. We can try a custom flattener to just return `nil` like in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/custom_flatten/vertex_ai_index_ignore_contents_delta_uri.go.erb

The YAML looks like https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/vertexai/Index.yaml#L110

This should be helpful as the crash was in the generated flattener.

**Comment by saurabh-net** [comment]
Looks like the custom flatten did the trick :)

**Comment by c2thorn** [comment]
> Looks like the custom flatten did the trick :) (based on the diff)

great, let us know when you have been able to give a manual test a try. @hao-nan-li I can take over this PR at this point

**Comment by hao-nan-li** [comment]
> > Looks like the custom flatten did the trick :) (based on the diff)
> 
> great, let us know when you have been able to give a manual test a try. @hao-nan-li I can take over this PR at this point

Thanks!

**Comment by saurabh-net** [comment]
Ouch, looks like this affects all terraform operations (plan / apply) for Profile Datascans with any jobs created for them.

I locally tested it, and there were a few other fields which are incorrectly specified.
I've added a custom_flattener at the data_profile_result level now instead.

With that, it is working fine locally.

**Pull request merged**
