### PR TITLE
compute: changed default value of `enable_endpoint_independent_mapping` to false in `google_compute_router_nat`

### PR DESCRIPTION
**Pull request by shijeesh-ns**
fixes https://github.com/hashicorp/terraform-provider-google/issues/10547

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: changed default value of `enable_endpoint_independent_mapping` to false in `google_compute_router_nat`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Terraform's default reflects the original behaviour of the API mid-2021, "By default, NAT gateway uses Endpoint-Independent Mapping.". We're unable to make this change at this time, as it's a breaking change requiring a major version increment: https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments

This PR can be held until `5.0.0`, at which point the change will be considered. We'll publish internal guidance prior to that release to ensure that service teams are adequately aware.

**Comment by shijeesh-ns** [comment]
Thank you for looking into this change. Is there a branch for 5.0 where I can merge this change? What is the expected release date for 5.0?

**Comment by rileykarson** [comment]
We don't have a strict timeline, but not before Nov 2022, a year after `4.0.0` (https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0). We'll likely create a branch in the future, but don't have one yet.

**Comment by shijeesh-ns** [comment]
@rileykarson, can we merge this change now?

**Comment by rileykarson** [comment]
We have not planned a `5.0.0` release yet, sorry! We don't have a projection of when that will be planned for at the moment.

**Pull request closed without merging**
