### PR TITLE
Add trigger for downstream generation and test

### PR DESCRIPTION
**Pull request by ScottSuarez**
Apart of community checker removal
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — APPROVED** [review]

**Review by melinath — CHANGES_REQUESTED** [review]
apparently cloudbuild doesn't like secrets that are defined but unused. (which I guess makes sense)

**Comment by ScottSuarez** [comment]
Added to the secret env list

**Review by melinath — APPROVED** [review]

**Review by melinath — CHANGES_REQUESTED** [review]
sorry for the noise; looks like it's still failing but I don't see a clear error

**Comment by ScottSuarez** [comment]
/gcbrun

I think I know what happened. Need to grant the SA access

**Review by melinath — APPROVED** [review]

**Pull request merged**
