### PR TITLE
Created new resources: RegionSecurityPolicy and NetworkEdgeSecurityServices for google_compute_security_policy , google_compute_region_security_policy and google_compute_network_edge_security_services to support Cloud Armor

### PR DESCRIPTION
**Pull request by fernandoleonem**
API: https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies 

**Cloud Armor for NLB/VMs APIs**

1. New resource NetworkEdgeSecurityServices

2. New ddosProtectionConfig fields in SecurityPolicies

3. SecurityPolicyType: CLOUD_ARMOR_NETWORK

If this PR is for Terraform, I acknowledge that I have:
 
* [x]  Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
* [x]  [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran make test and make lint to ensure it passes unit and linter tests.
* [x]  Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
* [x]  [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
* [x]  Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:enhancement
compute: Created new resources: RegionSecurityPolicy and NetworkEdgeSecurityServices for google_compute_security_policy , google_compute_region_security_policy and google_compute_network_edge_security_services to support Cloud Armor (beta)
```

### CODE REVIEW

**Comment by fernandoleonem** [comment]
`/gcbrun
`

**Comment by afpesseti** [comment]
Hello @roaks3, how are you? We've some problem with generate-diffs and run-rake-tests, we already got this problem previously, the reviewer ran the command `\gcbrun` and it worked. We try to run the same command, but it didn't work, I think we don't have permition to do this. Could you help us please? This new changes are google internal request.

**Comment by roaks3** [comment]
Oh sure, sorry for the delay. Running the checks now.

**Comment by afpesseti** [comment]
> /gcbrun

Thank you again! I made some changes, can you run again?

**Comment by roaks3** [comment]
This is blocked on failing tests

**Comment by rileykarson** [comment]
Hey! I'm closing this PR as a part of a cleanup of older inactive PRs, using a threshold of PRs last updated over 3 months ago. This doesn't represent rejection of the change, and feel free to comment for me to reopen it if you plan to pick it back up, or feel free to start a new PR with the same changes in the future.

**Pull request closed without merging**
