### PR TITLE
migrating google and google-beta repos to hashicorp org

### PR DESCRIPTION
**Pull request by megan07**
While migrating google and google-beta provider repos to hashicorp org in github, want to make sure our URLs are correct.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by ndmckinley** [comment]
Okay, cool.  Are those diffs what you expected?

**Comment by megan07** [comment]
I guess so? I wasn't expecting `go.mod` changes though?

And it looks like the tests failed - although, I need to make some changes to the CI too. But I think they still should have passed? Maybe I'll skip ahead to that step and make those changes quick just to rule that out.

**Comment by ndmckinley** [comment]
I am also a little surprised to see the go.mod changes - let me know if you need anything from me!  I feel like the code changes are right, we just have to figure out what infra changes to make.  :)

**Comment by ndmckinley** [comment]
I think enough of the tests have passed that we can say that this works.  Let's go ahead and merge it to stop the freeze, what do you think?

**Pull request merged**
