### PR TITLE
Adding Resource: google_composer_user_workloads_config_map

### PR DESCRIPTION
**Pull request by spapi17**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_composer_user_workloads_config_map` (beta)
```

### CODE REVIEW

**Review by kosteev — APPROVED** [review]

**Comment by spapi17** [comment]
Could you please re-run the tests? The recent API changes should resolve the previous failures.

**Comment by zli82016** [comment]
> Could you please re-run the tests? The recent API changes should resolve the previous failures.

I rerun the tests.

**Comment by zli82016** [comment]
Are there any reasons that the new resource is added as a handwritten resource instead of MMv1 generated resource? The doc to add a  resource is [here](https://googlecloudplatform.github.io/magic-modules/develop/resource/)

**Comment by zli82016** [comment]
@spapi17 , are there any reasons that the new resource is added as a handwritten resource instead of MMv1 generated resource? The doc to add a  resource is [here](https://googlecloudplatform.github.io/magic-modules/develop/resource/)

**Comment by spapi17** [comment]
@zli82016, thanks for pointing that out. Currently, we don't have any MMv1 generated resources in Composer, so it's hard for me to predict it will be possible to cover all the functionality with generated resource or how long it might take to rewrite it. However, if this is a strong recommendation, I'm happy to discuss/investigate this further.

**Comment by zli82016** [comment]
> @zli82016, thanks for pointing that out. Currently, we don't have any MMv1 generated resources in Composer, so it's hard for me to predict it will be possible to cover all the functionality with generated resource or how long it might take to rewrite it. However, if this is a strong recommendation, I'm happy to discuss/investigate this further.

@spapi17 ,  currently we strongly recommend to use MMv1 generated resources when adding new resources and it should cover all of the functionality for standard resources.  `google_composer_user_workloads_config_map` is a standard resource and should be good using MMv1 to generate the new resource.

To use MMv1 to generate the resources, you need to create a new folder `composer` in [mmv1/products]( https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products) and add `product.yaml` and `UserWorkloadsConfigMap.yaml` for this resource.

We can discuss more if you have any concerns.

**Comment by spapi17** [comment]
Created separate (PR)[https://github.com/GoogleCloudPlatform/magic-modules/pull/10865] for mmv1 generated resource:

**Pull request closed without merging**
