### PR TITLE
Add Cai2Hcl converter for global ComputeBackendService

### PR DESCRIPTION
**Pull request by amirkaromashkin**
Adds provider-generated converter for GlobalBackendService. 

RegionBackendService flattener [uses helper method](https://github.com/GoogleCloudPlatform/magic-modules/blob/02700f26d946578bea2380669cb58583d148c3c6/mmv1/products/compute/RegionBackendService.yaml#L152) from GlobalBackendService flattener, therefore in order to add converter for RegionBackendService, we first need to  add one for GlobalBackendService.

Context:
This PR is a part of an initiative to allow Equivalent Terraform UIs in GCP Console. In order to support any GCP resource, the codegen based approach implementation was [started](https://github.com/amirkaromashkin/magic-modules/blob/feature/cai2hcl_provider_generators/mmv1/provider/terraform_tgc_cai2hcl.rb).
As agreed with magic-modules owners, while currently adding significant changes to providers for TGC is not allowed, we agreed to add minimal set of converters to support project a MVP. 
These are 2 resources: ForwardingRule and RegionBackendService.

```release-note:note
Adds cai2hcl/ converters for global ComputeBackendService.
```

### CODE REVIEW

**Comment by melinath** [comment]
Drive-by comment: Could you split this into separate PRs for each resource so that it's easier to review?

**Comment by amirkaromashkin** [comment]
> Drive-by comment: Could you split this into separate PRs for each resource so that it's easier to review?

Alright, done)

**Comment by roaks3** [comment]
The boilerplate and tests look good, but quick question: was mmv1/third_party/cai2hcl/services/compute/compute_backend_service.go generated or copied from somewhere? It is a very large file, so I'm just wondering how closely I need to review each line.

**Comment by amirkaromashkin** [comment]
> The boilerplate and tests look good, but quick question: was mmv1/third_party/cai2hcl/services/compute/compute_backend_service.go generated or copied from somewhere? It is a very large file, so I'm just wondering how closely I need to review each line.

Yes, it was generated using my prototype for generated cai2hcl converters:
https://github.com/amirkaromashkin/magic-modules/blob/feature/cai2hcl_provider_generators/mmv1/templates/cai2hcl/resource_converter.go.erb

As discussed previously with Stephen, we yet are not ready to merge the converter itself, but its ok to add minimal amount of converters.

**Review by roaks3 — APPROVED** [review]
@amirkaromashkin apologies for the delay on this review. I circled back and spotted checked compute_backend_service.go, and all LGTM

**Pull request merged**
