### PR TITLE
fix: added gcs name validation

### PR DESCRIPTION
**Pull request by nbugden**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/17831

**Release Note Template for Downstream PRs (will be copied)**

```release-note: bug
storage: added validation to `name` field in `google_storage_bucket` resource
```

### CODE REVIEW

**Comment by daniel-cit** [comment]
is this the same validation

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storage/resource_storage_bucket.go.erb#L581C1-L583C3

that was implented in https://github.com/GoogleCloudPlatform/magic-modules/pull/6250 ?

**Comment by nbugden** [comment]
@daniel-cit there is some overlap. The differences with  https://github.com/GoogleCloudPlatform/magic-modules/pull/6250 include:
* The validations **DON'T** run when `terraform plan` is run. They are only run when attempting to create the bucket as they are part of the [resourceStorageBucketCreate](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storage/resource_storage_bucket.go.erb#L567C6-L567C33) function.
* They are incomplete as they do not apply all of the rules from the [docs](https://cloud.google.com/storage/docs/buckets#naming)

IMO it would make sense to keep the validations in one place. I tried to follow the convention of the other validations which were in the [verify package](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/verify). I'd be happy to remove the changes from https://github.com/GoogleCloudPlatform/magic-modules/pull/6250 to deduplicate validations if that's preferred.

**Comment by nbugden** [comment]
@daniel-cit just pushed 8b1cbd00fd5942c8baa6674301a303df587244bf which removes the `CheckGCSName` function in favor of the validations proposed in this PR.

**Comment by daniel-cit** [comment]
> @daniel-cit just pushed [8b1cbd0](https://github.com/GoogleCloudPlatform/magic-modules/commit/8b1cbd00fd5942c8baa6674301a303df587244bf) which removes the `CheckGCSName` function in favor of the validations proposed in this PR.

Maybe it would be good to also cover the same test cases from the old validation code

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tpgresource/utils_test.go#L1262C1-L1285C36

to ensure that the changes are compatible.

**Comment by daniel-cit** [comment]
@nbugden 
what would happen if the name of the bucket uses a random resource to compose the name like 

```
resource "random_string" "suffix" {
  length  = 64
  numeric = true
  lower   = false
  upper   = false
  special = false
}

resource "google_storage_bucket" "after_plan" {
  name          = "plan-${random_string.suffix.result}"
  location      = "US"
}
```
the value `random_string.suffix.result` will only be known at apply(create) time.

in this case, will the resource delay validation to the apply phase ?

Will the new validation be used in all the execution flows: read, create, update, and destroy?

**Comment by nbugden** [comment]
> Maybe it would be good to also cover the same test cases from the old validation code
>https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tpgresource/utils_test.go#L1262C1-L1285C36
>to ensure that the changes are compatible.

@daniel-cit https://github.com/GoogleCloudPlatform/magic-modules/pull/10426/commits/b3f3d9eeecae614319cd8689f573e8fd5c14dbb7 adds the tests for parity from CheckGCSName

**Comment by nbugden** [comment]
> what would happen if the name of the bucket uses a random resource to compose the name

@daniel-cit in that case since the name cannot be known prior to apply the validation is not run during the plan (see below)

### Terraform Config
```tf
resource "random_string" "suffix" {
  length  = 64
  numeric = true
  lower   = false
  upper   = false
  special = false
}

resource "google_storage_bucket" "after_plan" {
  name     = "plan-${random_string.suffix.result}"
  location = "US"
}
```
### Terraform Plan
#### Terraform Command
```sh
TF_CLI_CONFIG_FILE="$HOME/terraform/magic-modules-dev-override.tfrc" terraform plan -target='google_storage_bucket.after_plan'
```

#### Output
```tf
│ Warning: Provider development overrides are in effect
│ 
│ The following provider
│ development overrides are
│ set in the CLI
│ configuration:
│  - hashicorp/google in /Users/nathan.bugden/go/bin
│ 
│ The behavior may
│ therefore not match any
│ released version of the
│ provider and applying
│ changes may cause the
│ state to become
│ incompatible with
│ published releases.
╵

Terraform used the selected
providers to generate the
following execution plan.
Resource actions are
indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # google_storage_bucket.after_plan will be created
  + resource "google_storage_bucket" "after_plan" {
      + effective_labels            = (known after apply)
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = (known after apply)
      + project                     = (known after apply)
      + project_number              = (known after apply)
      + public_access_prevention    = (known after apply)
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

  # random_string.suffix will be created
  + resource "random_string" "suffix" {
      + id          = (known after apply)
      + length      = 64
      + lower       = false
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Terraform Apply
When the same configuration is applied, the validation is run prior to creating the bucket.
#### Terraform Command
```sh
TF_CLI_CONFIG_FILE="$HOME/terraform/magic-modules-dev-override.tfrc" terraform apply -target='google_storage_bucket.after_plan'
```

#### Terraform Output
```tf
│ Warning: Provider development overrides are in effect
│ 
│ The following provider
│ development overrides are
│ set in the CLI
│ configuration:
│  - hashicorp/google in /Users/nathan.bugden/go/bin
│ 
│ The behavior may
│ therefore not match any
│ released version of the
│ provider and applying
│ changes may cause the
│ state to become
│ incompatible with
│ published releases.
╵

Terraform used the selected
providers to generate the
following execution plan.
Resource actions are
indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # google_storage_bucket.after_plan will be created
  + resource "google_storage_bucket" "after_plan" {
      + effective_labels            = (known after apply)
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = (known after apply)
      + project                     = (known after apply)
      + project_number              = (known after apply)
      + public_access_prevention    = (known after apply)
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = (known after apply)
      + url                         = (known after apply)
    }

  # random_string.suffix will be created
  + resource "random_string" "suffix" {
      + id          = (known after apply)
      + length      = 64
      + lower       = false
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

Plan: 2 to add, 0 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan
│ with the -target option,
│ which means that the
│ result of this plan may
│ not represent all of the
│ changes requested by the
│ current configuration.
│ 
│ The -target option is not
│ for routine use, and is
│ provided only for
│ exceptional situations
│ such as recovering from
│ errors or mistakes, or
│ when Terraform
│ specifically suggests to
│ use it as part of an
│ error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

random_string.suffix: Creating...
random_string.suffix: Creation complete after 0s [id=0808056569454331236561064499984914160477239699147199885142821831]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with
│ the -target option in
│ effect, so some changes
│ requested in the
│ configuration may have
│ been ignored and the
│ output values may not be
│ fully updated. Run the
│ following command to
│ verify that no other
│ changes are pending:
│     terraform plan
│ 
│ Note that the -target
│ option is not suitable
│ for routine use, and is
│ provided only for
│ exceptional situations
│ such as recovering from
│ errors or mistakes, or
│ when Terraform
│ specifically suggests to
│ use it as part of an
│ error message.
╵
╷
│ Error: "plan-0808056569454331236561064499984914160477239699147199885142821831" name value must contain 3-63 characters. Names containing dots can contain up to 222 characters, but each dot-separated component can be no longer than 63 characters
│ 
│   with google_storage_bucket.after_plan,
│   on test.tf line 10, in resource "google_storage_bucket" "after_plan":
│   10:   name     = "plan-${random_string.suffix.result}"
```

**Comment by nbugden** [comment]
> however, since the validation is only on the create function for the current resource, it is possible to fix this error reducing the length of the random_string
>since the validation is only on the create function for the current resource, it is possible to fix this error reducing the length of the random_string

@daniel-cit yes, updating the length of the suffix will fix the error as you mentioned. See output below.

### Updating the Random Suffix Length
#### Updated Terraform Config
```tf
resource "random_string" "suffix" {
  length  = 34
  numeric = true
  lower   = false
  upper   = false
  special = false
}
```
#### Terraform Command
```sh
TF_CLI_CONFIG_FILE="$HOME/terraform/magic-modules-dev-override.tfrc" terraform apply -target='google_storage_bucket.after_plan'
```

#### Terraform Output
```tf
Terraform used the selected
providers to generate the
following execution plan.
Resource actions are
indicated with the
following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_storage_bucket.after_plan will be created
  + resource "google_storage_bucket" "after_plan" {
      + effective_labels            = (known after apply)
      + force_destroy               = false
      + id                          = (known after apply)
      + location                    = "US"
      + name                        = (known after apply)
      + project                     = "prj-c-scc-5xv2"
      + project_number              = (known after apply)
      + public_access_prevention    = (known after apply)
      + rpo                         = (known after apply)
      + self_link                   = (known after apply)
      + storage_class               = "STANDARD"
      + terraform_labels            = (known after apply)
      + uniform_bucket_level_access = true
      + url                         = (known after apply)
    }

  # random_string.suffix must be replaced
-/+ resource "random_string" "suffix" {
      ~ id          = "4459658187874002848905409602733573523031843089159360765646519166" -> (known after apply)
      ~ length      = 64 -> 34 # forces replacement
      ~ result      = "4459658187874002848905409602733573523031843089159360765646519166" -> (known after apply)
        # (9 unchanged attributes hidden)
    }

Plan: 2 to add, 0 to change, 1 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan
│ with the -target option,
│ which means that the
│ result of this plan may
│ not represent all of the
│ changes requested by the
│ current configuration.
│ 
│ The -target option is not
│ for routine use, and is
│ provided only for
│ exceptional situations
│ such as recovering from
│ errors or mistakes, or
│ when Terraform
│ specifically suggests to
│ use it as part of an
│ error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

random_string.suffix: Destroying... [id=4459658187874002848905409602733573523031843089159360765646519166]
random_string.suffix: Destruction complete after 0s
random_string.suffix: Creating...
random_string.suffix: Creation complete after 0s [id=4905591332324978645088960881522615]
google_storage_bucket.after_plan: Creating...
google_storage_bucket.after_plan: Creation complete after 2s [id=plan-4905591332324978645088960881522615]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with
│ the -target option in
│ effect, so some changes
│ requested in the
│ configuration may have
│ been ignored and the
│ output values may not be
│ fully updated. Run the
│ following command to
│ verify that no other
│ changes are pending:
│     terraform plan
│ 
│ Note that the -target
│ option is not suitable
│ for routine use, and is
│ provided only for
│ exceptional situations
│ such as recovering from
│ errors or mistakes, or
│ when Terraform
│ specifically suggests to
│ use it as part of an
│ error message.
╵

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

**Comment by nbugden** [comment]
> Sorry asking all these questions but I was affect by the initial version of the validation and I would like this change to be a smooth one.
@daniel-cit no problem! They are great questions. I agree it's better to have a smooth transition

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Comment by zli82016** [comment]
@daniel-cit, do you have any other comments?

**Comment by daniel-cit** [comment]
> @daniel-cit, do you have any other comments?

@zli82016 No comments, LGTM

**Pull request merged**
