### PR TITLE
Update document for concurrency fields in Cloud Run service v1 and v2 resources

### PR DESCRIPTION
**Pull request by yanweiguo**
Fix https://github.com/hashicorp/terraform-provider-google/issues/12764

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by yanweiguo** [comment]
Friendly ping for review.

**Comment by BBBmau** [comment]
can you link where you got updates from?

**Comment by yanweiguo** [comment]
> can you link where you got updates from?

I already updated https://cloud.google.com/run/docs/reference/rest/v1/RevisionSpec internally and the change will be rolled out soon.

**Review by BBBmau — APPROVED** [review]
thanks for providing the info!

**Pull request merged**
