### PR TITLE
updated references to debian-9-stretch to instead reference debian-11-bullseye

### PR DESCRIPTION
**Pull request by melinath**
debian-9 has been retired and is no longer returned by the API

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by c2thorn** [comment]
Looks like this was large enough to time out the VCR test. What should we do? break up the PR?

**Comment by melinath** [comment]
Let's try splitting it; here's a first pass to get docs, inspec, and things related to compute_instance.

**Comment by melinath** [comment]
hmm.... 102 failed tests might still be too many 😅 guess we'll see....

**Comment by melinath** [comment]
Made this only contain non-test changes; I'll split the tests out into smaller PRs.

**Review by megan07 — APPROVED** [review]

**Comment by melinath** [comment]
Merging even though the tests are still running since this compiles and is test-only (and the test will fail without this change)

**Pull request merged**
