### PR TITLE
Sync 5.0.0 with main Part 3

### PR DESCRIPTION
**Pull request by shuyama1**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
For tests failed in https://github.com/GoogleCloudPlatform/magic-modules/pull/8552#issuecomment-1665143566. I think they are related to the recent cleanup of tenant resources b/293326201. Some tests start to fail for pre-existing bootstrapped networks. So I just copied the cassettes over from main as the tests passed https://github.com/GoogleCloudPlatform/magic-modules/pull/8473 which was before the cleanup in VCR projects. Plus, I just checked our nightly and these tests passed in both ga and beta projects (some other tests failed with the same issue though).

I'm reaching out to the service team and see if it can be resolved. Or simply renaming the pre-existing bootstrapped networks should also fix the problem. Either way, I'll create a fix against the main branch. So I just copied the cassettes over to avoid these tests failed for future 5.0.0 PRs

**Review by melinath — APPROVED** [review]
I'm not really able to confirm that this is correct but it does look like a list of commits by various authors. Were there any merge conflicts that had to be resolved to make this set of changes?

**Comment by shuyama1** [comment]
No merge conflicts for this one, but it's probably because we only have two changes merged to the 5.0

**Pull request merged**
