### PR TITLE
add compute route tests

### PR DESCRIPTION
**Pull request by kotarsky**
adding new tests for compute.googleapis.com/Route

```release-note:none
compute: added testes field to `compute.googleapis.com/Route` resource
```

### CODE REVIEW

**Comment by kotarsky** [comment]
@zli82016 any tips related to this CLA error? I was wondering if this error should occur or not, because this is a public repository

**Comment by zli82016** [comment]
> @zli82016 any tips related to this CLA error? I was wondering if this error should occur or not, because this is a public repository

Hello, @kotarsky , can you open this link https://github.com/GoogleCloudPlatform/magic-modules/pull/10521/checks?check_run_id=24214839145?

**Comment by kotarsky** [comment]
@zli82016 I can open this link. 
While I try to sort this, I just wanted to confirm if what is in my commit is all I need to add the tests to the repository.

**Comment by zli82016** [comment]
> @zli82016 I can open this link. While I try to sort this, I just wanted to confirm if what is in my commit is all I need to add the tests to the repository.

Your commit is adding a test to tgc. Is it what you want to do?

Or is there a Github issue for this PR? If yes, can you please add it to the description section of this PR? Thanks.

**Comment by kotarsky** [comment]
> > @zli82016 I can open this link. While I try to sort this, I just wanted to confirm if what is in my commit is all I need to add the tests to the repository.
> 
> Your commit is adding a test to tgc. Is it what you want to do?
> 
> Or is there a Github issue for this PR? If yes, can you please add it to the description section of this PR? Thanks.

There is no issue, it's just tests. But in this [documentation](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/main/docs/contributing/add_new_resource.md#handwritten-converters) it is saying that I should also include the _tfplan.json_ file, but I couldn't find any file like that in the target folder, so I was wondering if the documentation is wrong or if I'm missing something.

**Comment by zli82016** [comment]
> > > @zli82016 I can open this link. While I try to sort this, I just wanted to confirm if what is in my commit is all I need to add the tests to the repository.
> > 
> > 
> > Your commit is adding a test to tgc. Is it what you want to do?
> > Or is there a Github issue for this PR? If yes, can you please add it to the description section of this PR? Thanks.
> 
> There is no issue, it's just tests. But in this [documentation](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/main/docs/contributing/add_new_resource.md#handwritten-converters) it is saying that I should also include the _tfplan.json_ file, but I couldn't find any file like that in the target folder, so I was wondering if the documentation is wrong or if I'm missing something.

Sorry, the documentation is outdated. You don't need to include the _tfplan.json file.

**Comment by zli82016** [comment]
Created a Github issue to update the documentation. https://github.com/hashicorp/terraform-provider-google/issues/17959

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
