### PR TITLE
Sync main into FEATURE-BRANCH-provider-functions

### PR DESCRIPTION
**Pull request by SarahFrench**
This PR syncs `main` into `FEATURE-BRANCH-provider-functions` and includes the upgrade to Go 1.21. That upgrade was motivated by their feature branch as it partially unblocks https://github.com/GoogleCloudPlatform/magic-modules/pull/10109

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
The CLA failure appears to be a false alarm - the commit raising the issue comes from this PR and I can see the CLA check passed there: https://github.com/GoogleCloudPlatform/magic-modules/pull/9278

**Comment by SarahFrench** [comment]
`presubmit-generate-diffs` ran ok using the latest version of the `build-environment` image OK, so it looks like the Go version updates appear to be compatible.

**Comment by shuyama1** [comment]
> `presubmit-generate-diffs` ran ok using the latest version of the `build-environment` image, so it looks like the Go version updates are compatible with the feature branches.

I think we may still need to cherry-pick downstream commits to feature branch (tpg, tpgb, tgc). I can do it right before we're merging this PR

**Review by shuyama1 — APPROVED** [review]

**Comment by SarahFrench** [comment]
Merging - prior to merge we updated the sync branch in TGC to include the change to its go.mod file to upgrade to Go 1.21 : https://github.com/GoogleCloudPlatform/terraform-google-conversion/commit/fbcf753d50c8f49b1e6fe289cee1aa5c49c3af9f

**Pull request merged**
