### PR TITLE
fix pubsub topic schemaSettings removal

### PR DESCRIPTION
**Pull request by kamalaboulhosn**
Remove default_from_api from Pub/Sub Topic schemaSettings. I recognize that this is normally considered a breaking change for a field. However, I think it is okay here as the service has never returned a value for this field if it is not set explicitly by the user. I tested in cases with both the field set and it unset before making the change and it worked as expected. Fixes https://github.com/hashicorp/terraform-provider-google/issues/15925.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
pubsub: Allow `schema_settings` of `google_pubsub_topic` to be removed
```

### CODE REVIEW

**Comment by kamalaboulhosn** [comment]
I guess the once case to consider is those who deleted the `schema_settings` from their config, but it didn't take and they just ignored the lack of a diff. Now, the next time they update, it will show a diff and want to delete the schema settings. If that is considered backwards incompatible, we can consider this a change that needs to be part of a major version update.

**Comment by ScottSuarez** [comment]
> If that is considered backwards incompatible

unfortunately it would be :/

Could you make a ticket for a breaking change enhancement. We can make this change durring 6.0 next year?

**Comment by kamalaboulhosn** [comment]
Understood. Will make this change when 6.0.0 rolls around. The ticket https://github.com/hashicorp/terraform-provider-google/issues/15925. already exists. Is there any way to mark that as a breaking change? I don't have permission to make any changes to that issue.

**Comment by GustenT** [comment]
Can this be reopened now for 6.0.0?

**Comment by kamalaboulhosn** [comment]
Yes, it is on my list to ensure it is fixed in 6.0.0

**Pull request closed without merging**
