### PR TITLE
Fix eventarc handwritten test

### PR DESCRIPTION
**Pull request by RileyHYZ**
Fix the error in handwritten acceptance test for eventarc trigger. Remove the unnecessary sample tests for trigger update. Upgrade dcl version to v1.51.0

This pr fixes https://github.com/hashicorp/terraform-provider-google/issues/15255

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
eventarc: fix error caused by missing event_data_content_type in handwritten acceptance test
```

### CODE REVIEW

**Review by roaks3 — COMMENTED** [review]
@RileyHYZ I'm not certain I understand the fix here. The issue seems to imply that if `event_data_content_type` is not specified, the server will return a default value and store it in state, and subsequent plans will see a diff between the state and the config. Do I have that right?

If that's the case, then I think your fix is avoiding this condition, as opposed to resolving it. Curious if I'm missing something here.

**Comment by RileyHYZ** [comment]
> @RileyHYZ I'm not certain I understand the fix here. The issue seems to imply that if `event_data_content_type` is not specified, the server will return a default value and store it in state, and subsequent plans will see a diff between the state and the config. Do I have that right?
> 
> If that's the case, then I think your fix is avoiding this condition, as opposed to resolving it. Curious if I'm missing something here.

Hi @roaks3, yes that's correct. Thank you for pointing that out! I wasn't fully understanding the test setup before so I've made another change to DCL that marks the `event_data_content_type` as server_default. I'll update the change here once that is approved. Thanks again.

**Comment by roaks3** [comment]
Ah ok, that makes sense, sounds good!

**Comment by roaks3** [comment]
@RileyHYZ would you mind adding a message here when this is ready for another look?

**Comment by RileyHYZ** [comment]
Currently waiting for a new dcl release that fixes the error in `TestAccDataSourceGoogleServiceAccountAccessToken_basic`. I will update the version and let you know @roaks3  when the pr is ready. Thanks!

**Comment by roaks3** [comment]
Ok, sounds good. I might be on PTO when this is ready, so switching the reviewer while we wait

**Pull request closed without merging**
