### PR TITLE
docs: added required value for datapath_provider to enable Dataplane v2

### PR DESCRIPTION
**Pull request by guerzon**
Hey,

Here's a small MR that fixes https://github.com/hashicorp/terraform-provider-google/issues/13815.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

Note: checklist items 3 and 4 contain broken links. Please update the MR template to <https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/getting-started/generate-providers.md> and <https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/getting-started/run-provider-tests.md>, respectively.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Review by SarahFrench — COMMENTED** [review]
👋 Hi, thanks for your PR! I had a look at [the official API docs for this field](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#datapathprovider) and I think it'd be a good idea to include both `LEGACY_DATAPATH` and `ADVANCED_DATAPATH` in this description. Could you please update the description to include them both?

**Comment by guerzon** [comment]
Thanks @SarahFrench for the feedback.

I was not really confident about the default value so I left it out. To be more specific, I was not able to figure out what `DATAPATH_PROVIDER_UNSPECIFIED` does. Nevertheless, I could confirm that by default, the value was `LEGACY_DATAPATH` whose description matched the API docs you enclosed.

Cloud Console > try to create a cluster > click 'Equivalent REST':

```json
POST https://container.googleapis.com/v1beta1/projects/<PROJECT_ID>/zones/us-central1-c/clusters
{
  "cluster": {
    "name": "cluster-1",
    "masterAuth": {
      "clientCertificateConfig": {}
    },
...
    "networkConfig": {
      "datapathProvider": "LEGACY_DATAPATH"
    },
...
}
```

Additional commit pushed. Thanks

**Review by SarahFrench — APPROVED** [review]
Thanks for investigating the API's default value and updating the description - this will help users understand the two options and not rely on the default behaviour as much. Will merge once the automation finished running 🚀

**Comment by SarahFrench** [comment]
My bad- the automation needed a manual trigger outside of GitHub. It's running now

**Pull request merged**
