### PR TITLE
Sync 5.0.0 with main

### PR DESCRIPTION
**Pull request by shuyama1**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by c2thorn** [comment]
conflict just came up?

**Comment by shuyama1** [comment]
> conflict just came up?

fixed!

**Review by c2thorn — APPROVED** [review]

**Comment by shuyama1** [comment]
Looks like we hit the limit of stored info types, cleaned up the resources and rerun tests. /gcbrun

**Pull request merged**
