### PR TITLE
Adding support for Access Context Manager's VPC Sub-segmentation feature

### PR DESCRIPTION
**Pull request by vmoros**
Moving changes for Access Context Manager's VPC Sub-segmentation feature from Terraform EAP to the normal provider.

[Here](https://cloud-internal-review.git.corp.google.com/c/cloud-graphite-eng/magic-modules-private-overrides/+/42350) is the PR that added these same fields to Terraform EAP.

[Here](https://source.corp.google.com/piper///depot/google3/google/identity/accesscontextmanager/v1/service_perimeter.proto;rcl=562860862;l=450-457) are the new fields for Service Perimeters, so this PR adds these new fields (and associated sub-fields) to various Service Perimeter-related tests and resource files.

Similarly, [here](https://source.corp.google.com/piper///depot/google3/google/identity/accesscontextmanager/v1/access_level.proto;rcl=562860862;l=164-166) is the new field for Access Levels. This PR adds this new field (and associated sub-fields) to various Access Level-related tests and resource files.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Adding support for Access Context Manager's VPC Sub-segmentation feature
```

### CODE REVIEW

**Comment by vmoros** [comment]
Hi @SarahFrench, I see that the missing test report says that `source_restriction` and `access_level` are not tested but they are tested.  For example, both fields are tested [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/ad1898feeeeba6b08f2f1673ccd91444a0d1fec1/mmv1/third_party/terraform/services/accesscontextmanager/resource_access_context_manager_service_perimeter_test.go.erb#L341-L347) for the `ServicePerimeter` resource, and similarly for the other Service Perimeter-related resources.

How can I get the missing test report to recognize these tests?

**Comment by SarahFrench** [comment]
Ah, my apologies, it looks like you're also adding fields that are called the same thing and nested under the status field

**Review by SarahFrench — COMMENTED** [review]
Given the repetitive nature of these new fields and the confusion with acceptance tests, could you please split this PR into multiple PRs?

**Comment by SarahFrench** [comment]
Superseded by https://github.com/GoogleCloudPlatform/magic-modules/pull/9298

**Pull request closed without merging**
