### PR TITLE
Removing Chef README example

### PR DESCRIPTION
**Pull request by rambleraptor**
This is one of the reasons that Chef compilation sometimes fails.

-----------------------------------------------------------------
# [all]
Removing Chef README example
## [chef]
Removing README example

### CODE REVIEW

**Comment by ndmckinley** [comment]
Huh, are we not going to regret not having this?  I don't mind, but let's chat Monday so I understand why we don't need this.

**Comment by erjohnso** [comment]
What is the alternative for users to see examples?

**Comment by rambleraptor** [comment]
No strong feelings what we do with this. We have a TODO to remove it
because it’s duplicated information.

Just for the record though: this does not remove all examples from the
README.

Currently, we print out one full example per resource in the README.

At the top level of the README, we also print out a “README” example. This
is completely independent from all of the other examples, yet always
duplicates the most used resource in a product (compute + Instance, DNS +
ResourceRecordSet). This means we have the instance example in two files -
instance.rb and readme.rb

If this README example isn’t included, MM will crash which we’d like to
avoid.

**Comment by rambleraptor** [comment]
Sounds like we don't want this. Closing.

**Pull request closed without merging**
