### PR TITLE
Allow import steps in beta IAM resource tests

### PR DESCRIPTION
**Pull request by SarahFrench**
Closes https://github.com/hashicorp/terraform-provider-google/issues/12610

This PR contains:
- Fixing the IAM test template to allow import steps to be included in the beta provider ([mmv1/templates/terraform/examples/base_configs/iam_test_file.go.erb](https://github.com/GoogleCloudPlatform/magic-modules/pull/7185/files#diff-b7444f7a6749c23ec7b5bb95823bb3a2ec0e06cb6578c0600344ab40ccb2b057))
- Adds ability to skip import steps of IAM tests
- Skips the (newly-added) import steps of generated, beta IAM tests so that broken tests aren't produced by the template change

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by melinath** [comment]
In general I like the idea of making the changes to iam_test_file.go.erb in this PR but I'm concerned that it'll make these tests start failing on all PRs until they're fixed. What would you think about either backing out the template changes or else finding a way to temporarily skip specifically those tests?

**Comment by melinath** [comment]
After staring at this some more today, I'm leaning towards leaving the templates in this PR & skipping import tests for these IAM resources and fixing them in separate (bug) tickets / PRs.

**Review by melinath — CHANGES_REQUESTED** [review]
See above - the problem being that we don't have a way to skip import tests for iam resources yet - only for resource tests (via `skip_import_test`). what would you think about adding `skip_import_test` for iam resources to skip these for now? (I'm not sure that is the best name & might end up needing to be set in a place that doesn't parallel the `skip_import_test` placement...)

**Comment by SarahFrench** [comment]
> See above - the problem being that we don't have a way to skip import tests for iam resources yet - only for resource tests (via skip_import_test). what would you think about adding skip_import_test for iam resources to skip these for now? (I'm not sure that is the best name & might end up needing to be set in a place that doesn't parallel the skip_import_test placement...)

Sorry, I've been juggling a few things and I'll need to re-pick up this PR(s) next week.

I could have a go implementing skip import test for IAM resources, definitely. Another option for the acceptance test is to use this trick I learned recently: [test that pulls value out of test](https://github.com/GoogleCloudPlatform/magic-modules/blob/1ce4eb6963ed638b2569f6a4523e2f540e95d1e7/mmv1/third_party/terraform/tests/data_source_dns_record_set_test.go.erb#L16-L38), [function that does the pulling](https://github.com/GoogleCloudPlatform/magic-modules/blob/1ce4eb6963ed638b2569f6a4523e2f540e95d1e7/mmv1/third_party/terraform/framework_utils/framework_test_utils.go#L33-L53). However as this would also not fit nicely into generated tests I think the first option is best

**Comment by SarahFrench** [comment]
As an update re: doing the above skip test generation for IAM resources I'm hoping to complete it next week before I take a week of PTO from Thursday 9th Feb onwards

**Comment by SarahFrench** [comment]
Ok, I'm finding the split of PRs confusing so I'm going to make this PR a PR to fix the template and add the ability to skip import steps.

After, I'll open a new PR to fix the fixable tests

I'll close the original PR once that's all done

**Comment by SarahFrench** [comment]
Due to the new `skip_import_test`, the template changes now only impact these tests. They should all pass:

Screenshot 2023-02-07 at 11 51 02

**Comment by SarahFrench** [comment]
I'll add an ignore for Cloud Build IAM - added recently in https://github.com/GoogleCloudPlatform/magic-modules/pull/6778

**Comment by SarahFrench** [comment]
☝️ Failing `TestAccDataprocMetastoreFederationIam*` tests are due to the API's errors, not due to import steps

**Comment by SarahFrench** [comment]
As before, failing TestAccDataprocMetastoreFederationIam* tests are due to the API's errors, not due to import steps

**Comment by SarahFrench** [comment]
Just got back from PTO - thanks for the review and approval! I'll merge :shipit:

**Pull request merged**
