### PR TITLE
Add default url redirect to url maps

### PR DESCRIPTION
**Pull request by ctavan**
Fixes terraform-providers/terraform-provider-google#6081

A few things that came up while developing this:
* RegionTargetHttpProxies are currently in the google-beta terraform provider even though theses resources seem to be GA now: https://www.terraform.io/docs/providers/google/r/compute_region_target_http_proxy.html / https://cloud.google.com/compute/docs/reference/rest/v1/regionTargetHttpProxies -> I did not change the example yet.
* urlRedirect parameter seems to be slightly out-of-sync: #3378
* Not sure if/how to write tests for this new feature?
* Not sure if the `google_compute_target_http_proxy` resource is the best place for the example?
* Also the API docs state: "If `defaultUrlRedirect` is specified, `defaultService` or `defaultRouteAction` must not be set." **(How) is such mutual exclusivity modeled in magic-modules?**

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added support for default URL redirects to `google_compute_url_map`
```
```release-note:enhancement
compute: Added support for default URL redirects to `google_compute_region_url_map`
```

### CODE REVIEW

**Comment by ctavan** [comment]
@googlebot I signed it!

**Comment by danawillow** [comment]
Picking a new reviewer so we get someone who works on TF

**Comment by chrisst** [comment]
I'll be able to review this later this week but I'll start by answering some of your questions:
* re RegionTargetHttpProxies being beta when the feature is GA - we currently move features in the provider to GA only when somebody lets us know. We don't currently have a method to find this out proactively. Would you file a request for this? Or you can send a PR if you would like.
* writing tests - You can add a hand written test file even though these resources are generated. We frequently will do this for resources so we can test the update method or any special logic. These tests are added in `third_party/terraform/tests/*`
* Mutually exclusive logic can be enforced with the [`exactly_one_of` feature](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/api.yaml#L10747) or the [`conflicts` feature](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/api.yaml#L4641). At first glance it looks like conflicts is the better option here.

**Comment by ctavan** [comment]
Re GA, see https://github.com/GoogleCloudPlatform/magic-modules/pull/3381

I‘ll look into tests and conflicts later today.

**Comment by ctavan** [comment]
@chrisst
* I've added a basic test that covers the new property. Is it fine to have a separate test case here or should it be added as an additional step in an existing test case?
* I've added `exactly_one_of` rules. I think they are more appropriate than `conflicts` because "exactly one of" seems to be precisely what the API demands. At least I got the following error message when trying to define none of `defaultService` or `defaultUrlRedirect`:
    ```
    Error: Error updating UrlMap "projects/*/global/urlMaps/url-map": googleapi: Error 400: Invalid value for field 'resource.defaultService': ''. No default backend service specified., invalid
    ```
  And this  error when specifying both:
    ```
    Error: Error updating UrlMap "projects/*/global/urlMaps/url-map": googleapi: Error 400: Invalid value for field 'resource.defaultUrlRedirect': '{  "httpsRedirect": true}'. A default redirect can only be specified for a url map if it neither specifies a default service nor a default route action, invalid
    ```

I think this is ready for review now.

**Pull request merged**
