### PR TITLE
fix TestAccAlloydbInstance_updateDatabaseFlagInPrimaryInstance by increasing timeouts

### PR DESCRIPTION
**Pull request by ScottSuarez**
https://ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=1674360380034955101&tab=testDetails

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
alloydb: increased timeouts for `google_alloydb_instance` from 20m to 40m
```

### CODE REVIEW

**Review by zli82016 — APPROVED** [review]
LGTM

**Comment by paraggoyal92** [comment]
Can you please add the reason of this update in the PR request?

**Comment by ScottSuarez** [comment]
> ci-oss.hashicorp.engineering/project.html?projectId=GoogleCloud&testNameId=1674360380034955101&tab=testDetails

From our test run

```
        Error: Error waiting for Updating Instance: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 20m0s)
        
          with google_alloydb_instance.primary,
          on terraform_plugin_test.tf line 2, in resource "google_alloydb_instance" "primary":
           2: resource "google_alloydb_instance" "primary" {
        
--- FAIL: TestAccAlloydbInstance_updateDatabaseFlagInPrimaryInstance (2511.74s)
FAIL

````

If you believe this is incorrect feel free to open a new pr to adjust them into another range.

**Comment by paraggoyal92** [comment]
40 minutes seems too high. It could be an outlier. Could you please run this multiple times and come up with a better threshold, such as the 95th percentile of all the times? I am just worried that we might end up consuming actual errors with this high threshold number.

**Comment by ScottSuarez** [comment]
Unfortunately I won't have time to re-engage this issue since I'm no longer on duty. If you like, open a PR to reduce the timeout range. If our team infra sees repeated failures we may need to reraise.

**Pull request merged**
