### PR TITLE
Add Distributed Cloud Edge resources

### PR DESCRIPTION
**Pull request by benfogel**
Add configuration for Google Distributed Cloud Edge Container cluster resource. Partially fixes hashicorp/terraform-provider-google/pull/14275

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_edgecontainer_cluster
```

### CODE REVIEW

**Comment by benfogel** [comment]
@roaks3 - Could you start the tests? This PR is ready for review.

**Comment by roaks3** [comment]
Hey @benfogel , I'm kicking off the tests for you now, but 2 things:
- Could you make sure you have set up your GitHub groups properly according to go/terraform-contribution-guide#getting-started? It may require a rebase as well, but you should theoretically be able to run tests on your own as a Googler.
- I'm going to be out for the next 2 weeks, and given the size of this PR, I'm going to need to pass it off to another reviewer.

**Comment by rileykarson** [comment]
Note: We need to work out how we want to test this. We have an email thread.

**Comment by roaks3** [comment]
@benfogel we don't have automation built around `.ci/infra/terraform/main.tf`, so the current process is to request the change be made by someone on our team (most likely in a PR like this), and then update the file to keep track of the addition (see go/terraform-team-testing#modifying-test-infrastructure).

I will go ahead and make the change for this service, and I would suggest leaving the `.ci/infra/terraform/main.tf` change you made in this PR.

**Comment by roaks3** [comment]
Something appears to be canceling the build right near the beginning, but I don't see a change since the last successful run that would explain this behavior. I'm going to try a couple things to move this through.

**Comment by roaks3** [comment]
I'm not able to see why the jobs are being canceled, but it is happening consistently. @rileykarson do you have any ideas?

Worst case, since there hasn't been a lot of back-and-forth discussion on the code changes so far, it might be easiest to open a new PR.

**Pull request closed without merging**
