### PR TITLE
Place security policy under folder for easier cleanup

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/10004
possibly can help with https://github.com/hashicorp/terraform-provider-google/issues/9980

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by slevenick — APPROVED** [review]
Can you clean up the firewall policies in the CI project to fix the tests here? That's the only related failure

**Comment by ScottSuarez** [comment]
sure !

**Pull request merged**
