### PR TITLE
allow compute snapshot source to accept full url

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/10470

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: allowed `source_disk` to accept full image path on `google_compute_snapshot`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
/gcbrun (I just turned VCR back on)

**Comment by rileykarson** [comment]
I'm seeing a failure in `TestAccComputeSnapshot_snapshotBasicExample` in https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215434?buildTab=overview

**Comment by ScottSuarez** [comment]
> I'm seeing a failure in `TestAccComputeSnapshot_snapshotBasicExample` in [ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215434?buildTab=overview](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215434?buildTab=overview)

ah this was the issue you mentioned in the bug with the flattener

**Comment by ScottSuarez** [comment]
> ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215434?buildTab=overview

reran this build
https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/215448

**Comment by ScottSuarez** [comment]
test passed @rileykarson

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
