### PR TITLE
Bigtable: Update Bigtable go client version from 1.13 to 1.16

### PR DESCRIPTION
**Pull request by kevinsi4508**
Update Bigtable go client version from 1.13 to 1.16.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by kevinsi4508** [comment]
I believe I need to update go.sum as well.

**Comment by kevinsi4508** [comment]
@hoangpham95 Please take a look. thanks!

**Review by hoangpham95 — APPROVED** [review]

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like this is failing downstream because of issues with the go.sum file:

```
go generate  ./...
go: downloading cloud.google.com/go/bigtable v1.16.0
go: updates to go.mod needed; to update it:
	go mod tidy
make: *** [generate] Error 1
```

**Comment by kevinsi4508** [comment]
@c2thorn , please comment on updating go.mod error. I don't have much context. Thanks!

**Comment by kevinsi4508** [comment]
> 



> It looks like this is failing downstream because of issues with the go.sum file:
> 
> ```
> go generate  ./...
> go: downloading cloud.google.com/go/bigtable v1.16.0
> go: updates to go.mod needed; to update it:
> 	go mod tidy
> make: *** [generate] Error 1
> ```

@c2thorn , please comment on updating go.mod error. I don't have much context. Thanks!

**Comment by c2thorn** [comment]
> @c2thorn , please comment on updating go.mod error. I don't have much context. Thanks!
not sure what's going on here. you should just have to

1. go to downstream google-beta repo
2. update the dependency to 1.16
3. run `go mod tidy` (delete the scripts/diff.go for now)
4. copy the resulting changes over to the MMv1 versions

**Comment by kevinsi4508** [comment]
> > @c2thorn , please comment on updating go.mod error. I don't have much context. Thanks!
> > not sure what's going on here. you should just have to
> 
> 1. go to downstream google-beta repo
> 2. update the dependency to 1.16
> 3. run `go mod tidy` (delete the scripts/diff.go for now)
> 4. copy the resulting changes over to the MMv1 versions

Sorry! is that something I need to do? I already copied the change and updated go.sum file.

**Comment by melinath** [comment]
> Sorry! is that something I need to do? I already copied the change and updated go.sum file.

yes, that is something you need to do. I would add one step:

1. go to your clone of the [google-beta](https://github.com/hashicorp/terraform-provider-google-beta) repo
1. update the dependency to 1.16
1. run go mod tidy (delete the scripts/diff.go for now)
1. **verify that you are able to compile the code via `make build` _and_ that unit tests pass via `make test`**
   - if you're not, resolve any errors before proceeding.
1. copy the resulting changes over to the MMv1 versions

**Comment by kevinsi4508** [comment]
> > Sorry! is that something I need to do? I already copied the change and updated go.sum file.
> 
> yes, that is something you need to do. I would add one step:
> 
> 1. go to your clone of the [google-beta](https://github.com/hashicorp/terraform-provider-google-beta) repo
> 2. update the dependency to 1.16
> 3. run go mod tidy (delete the scripts/diff.go for now)
> 4. **verify that you are able to compile the code via `make build` _and_ that unit tests pass via `make test`**
>    
>    * if you're not, resolve any errors before proceeding.
> 5. copy the resulting changes over to the MMv1 versions

So sorry! I still don't understand this part: "copy the resulting changes over to the MMv1 versions".

What change am I expecting? In what file in the MMv1? I already added the change for go.sum:
cloud.google.com/go/bigtable v1.16.0 h1:sqJhhslzQOag49Mf2/uH3+u+NdfpPX0gjKAcgYpRUCU=
cloud.google.com/go/bigtable v1.16.0/go.mod h1:6f7WVXfeZaJz0xevUZoTA1s8sTmmrQqIAkRDVEHVg7I=

**Comment by melinath** [comment]
> So sorry! I still don't understand this part: "copy the resulting changes over to the MMv1 versions".
> 
> What change am I expecting? In what file in the MMv1? I already added the change for go.sum: cloud.google.com/go/bigtable v1.16.0 h1:sqJhhslzQOag49Mf2/uH3+u+NdfpPX0gjKAcgYpRUCU= cloud.google.com/go/bigtable v1.16.0/go.mod h1:6f7WVXfeZaJz0xevUZoTA1s8sTmmrQqIAkRDVEHVg7I=

the full sentence would be "copy the resulting changes over to the MMv1 versions of go.mod and go.sum" - you are editing the right files but the changes are incomplete; I'm not sure why. You need to resolve that locally in the downstream provider by following the steps above - in particular, making sure you can compile the provider and run tests after your changes.

**Comment by kevinsi4508** [comment]
> > So sorry! I still don't understand this part: "copy the resulting changes over to the MMv1 versions".
> > What change am I expecting? In what file in the MMv1? I already added the change for go.sum: cloud.google.com/go/bigtable v1.16.0 h1:sqJhhslzQOag49Mf2/uH3+u+NdfpPX0gjKAcgYpRUCU= cloud.google.com/go/bigtable v1.16.0/go.mod h1:6f7WVXfeZaJz0xevUZoTA1s8sTmmrQqIAkRDVEHVg7I=
> 
> the full sentence would be "copy the resulting changes over to the MMv1 versions of go.mod and go.sum" - you are editing the right files but the changes are incomplete; I'm not sure why. You need to resolve that locally in the downstream provider by following the steps above - in particular, making sure you can compile the provider and run tests after your changes.

I was able to compile and test. I should only care about the change I made. If there are  other changes that need to be there, that shouldn't be my responsibility and it could be some other problems entirely.

The same error happened in beta, doesn't that mean we test (is it a test?) need to be updated to remove  scripts/diff.go first (not by me).

It sounds to me that we should be fixing whatever the problem with diff.go before my PR.

**Comment by c2thorn** [comment]
> I was able to compile and test. I should only care about the change I made. If there are other changes that need to be there, that shouldn't be my responsibility and it could be some other problems entirely.

I think there is a misunderstanding. Our CI is stating that _this_ change is causing build issues. If I copy the changes pushed to this PR I also get the same build error. 

Running the steps outlined above results in a different set of changes in my environment.

**Comment by c2thorn** [comment]
> The same error happened in beta, doesn't that mean we test (is it a test?) need to be updated to remove scripts/diff.go first (not by me).
> 
> It sounds to me that we should be fixing whatever the problem with diff.go before my PR.

Agreed that the diff.go issue should be fixed and I believe someone is working on that. However even with that fix this PR would not build correctly.

**Comment by melinath** [comment]
Maybe this is due to Go version? @kevinsi4508 what go version are you using locally? (You can find out with `go version`)

**Comment by kevinsi4508** [comment]
> Maybe this is due to a mismatch between the Go version used in CI and the version being used to generate the changes in this PR? @kevinsi4508 what go version are you using locally? (You can find out with `go version`)

kevinsi@kevinsi:~/go/src/github.com/hashicorp/terraform-provider-google$ go version
go version go1.18.4 linux/amd64

**Comment by melinath** [comment]
> > Maybe this is due to a mismatch between the Go version used in CI and the version being used to generate the changes in this PR? @kevinsi4508 what go version are you using locally? (You can find out with `go version`)
> 
> kevinsi@kevinsi:~/go/src/github.com/hashicorp/terraform-provider-google$ go version go version go1.18.4 linux/amd64

hmm, that should be fine.

**Comment by kevinsi4508** [comment]
> 

Maybe I will just wait for diff.go to be fixed first.

**Comment by c2thorn** [comment]
Deferring to @melinath for the review here. Also sorry for the closed PR spam, big misclick from me

**Comment by melinath** [comment]
> I was able to compile and test. I should only care about the change I made. If there are other changes that need to be there, that shouldn't be my responsibility and it could be some other problems entirely.
> 
> The same error happened in beta, doesn't that mean we test (is it a test?) need to be updated to remove scripts/diff.go first (not by me).
> 
> It sounds to me that we should be fixing whatever the problem with diff.go before my PR.

You do need to remove scripts/diff.go (or add a go.mod file to the folder) to update the dependencies because of a quirk of how Golang handles dependency discovery, but that's not related to this failure - see Cameron's comments above.

**EVEN IF WE FIX THAT, YOUR PR WILL NOT BUILD.**

I've looked into this locally and confirmed that (after ensuring diff.go won't be discovered) running `go get cloud.google.com/go/bigtable@v1.16.0` updates a few subdependencies in go.mod as well, which are not updated in this PR.

Golang dependency upgrades require upgrading _all_ the subdependencies; this is not "other changes that need to be there", this is core behavior of Golang dependency management. It's a critical part of the change you are trying to make.

**Review by melinath — CHANGES_REQUESTED** [review]
marking as changes requested to remove from review queue pending resolution of the merge conflicts

**Comment by kevinsi4508** [comment]
Let me try it again with a different branch.

**Pull request closed without merging**
