### PR TITLE
Fix Failing test(s): TestAccComputeInstanceTemplate_*

### PR DESCRIPTION
**Pull request by BBBmau**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/16057

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by BBBmau** [comment]
It was necessary to move up from 18TB to 24 since it could only take an instance of [0, 1, 2, 4, 8, 16, 24] based off of the following error:
```
=== CONT  TestAccComputeInstanceTemplate_with18TbScratchDisk
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating instance template: googleapi: Error 400: Number of local SSDs for an instance of type n2-standard-32 should be one of [0, 1, 2, 4, 8, 16, 24], while [6] is requested., badRequest
        
          with google_compute_instance_template.foobar,
          on terraform_plugin_test.tf line 7, in resource "google_compute_instance_template" "foobar":
           7: resource "google_compute_instance_template" "foobar" {
        
--- FAIL: TestAccComputeInstanceTemplate_with18TbScratchDisk (7.92s)
```
disk size could also not be adjusted to match the previous 18Tb due to it being restricted to only [375, 3000] based on the following error:
```
=== PAUSE TestAccComputeInstanceTemplate_with18TbScratchDisk
=== CONT  TestAccComputeInstanceTemplate_with18TbScratchDisk
    vcr_utils.go:152: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: 1 error occurred:
                * SCRATCH disks must be one of [375 3000] GB, disk 3 is 300
        
        
        
          with google_compute_instance_template.foobar,
          on terraform_plugin_test.tf line 7, in resource "google_compute_instance_template" "foobar":
           7: resource "google_compute_instance_template" "foobar" {
        
--- FAIL: TestAccComputeInstanceTemplate_with18TbScratchDisk (2.86s)
```

**Review by NickElliot — COMMENTED** [review]
Could you resolve the merge conflict? I'll run the CI tests once thats done!

**Review by NickElliot — CHANGES_REQUESTED** [review]
Test is failing with the following:

`Error: Error creating instance template: googleapi: Error 400: Number of local SSDs for an instance of type n2-standard-16 should be one of [6], while [8] is requested.`,

**Review by NickElliot — CHANGES_REQUESTED** [review]
now failing with the following: 

```         
Error: Error creating instance template: googleapi: Error 400: Number of local SSDs for an instance of type n2-standard-2 should be one of [6], while [8] is requested.
      More details:
      Reason: badRequest, Message: Number of local SSDs for an instance of type n2-standard-2 should be one of [6], while [8] is requested.
      Reason: badRequest, Message: Large SSDs are not supported on an instance of type n2-standard-2.
      
      
        with google_compute_instance_template.foobar,
        on terraform_plugin_test.tf line 7, in resource "google_compute_instance_template" "foobar":
         7: resource "google_compute_instance_template" "foobar" {
```

**Comment by BBBmau** [comment]
After several attempts it looks like the GCP projects behaves differently to running tests locally. Because of this I'll be closing this PR due to how inconsistent it is when running locally compared to the GCP project from magic module.

**Pull request closed without merging**
