### PR TITLE
metastore - allow updating endpointProtocol

### PR DESCRIPTION
**Pull request by DrFaust92**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
metastore - allow updating `endpoint_protocol`
```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Can you add a test that updates this value?

**Comment by DrFaust92** [comment]
@slevenick failure unrelated. added test

**Comment by DrFaust92** [comment]
rebased + added grpc --> thrift as this might not work |:

**Comment by slevenick** [comment]
Failing with:
Error 400: Found 1 problem:
        	1) Updating endpoint protocol to THRIFT from GRPC is not supported.

**Comment by DrFaust92** [comment]
damn, docs were right. @slevenick any idea how i can allow thrift to grpc but force new for the other way around? anyway i can inject this custom logic into a diff func?

**Comment by slevenick** [comment]
> damn, docs were right. @slevenick any idea how i can allow thrift to grpc but force new for the other way around? anyway i can inject this custom logic into a diff func?

We can add a CustomizeDiff that checks if old == GRPC and new == THRIFT or something like that. It's a little difficult to get the customize diff set up, heres an example of a resource that uses one: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/resource_definition/disk.erb

I believe it can be included with an entry in the custom_code block in terraform.yaml of: `resource_definition` and it will be added to the right spot

**Pull request closed without merging**
