### PR TITLE
Move Cloud Build Worker Pool to GA.

### PR DESCRIPTION
**Pull request by ndmckinley**
Note: this includes some unusual changes in the DCL due to deviations between the beta and GA APIs.  Hopefully that oddness should be completely hidden from Terraform - if you see something that looks weird let me know, it is probably a symptom of incomplete conversion between beta and GA and should be fixed.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_cloudbuild_worker_pool in GA.
```

```release-note:enhancement
cloudbuild: added display_name and annotations to google_cloudbuild_worker_pool for compatibility with new GA.
```

### CODE REVIEW

**Comment by ndmckinley** [comment]
The team is going to get those features backported to the beta to maintain our rule about GA being a strict subset of beta.   This PR will sit in draft til that's rolled out.  :)

**Review by slevenick — APPROVED** [review]
👍  assuming the tests pass in GA

We may want to exclude `etag` as it is handled internally by the DCL and is not useful for users.

You're adding a couple fields to the beta resource, can you add that to the changelog note?

**Review by slevenick — CHANGES_REQUESTED** [review]
Per discussion in chat: We should block merging this until we can move the beta provider to use the GA endpoints. Currently this resource in the beta provider requires users to be allow-listed. We should move the beta provider to use the GA endpoints to get around this

**Comment by ndmckinley** [comment]
Okay - that _should_ work - we'll see what the tests have to say.  :)

**Comment by slevenick** [comment]
/gcbrun

Looks like it got stuck in the 5:00 runs.

**Review by slevenick — APPROVED** [review]
Looks like it's hitting the v1 endpoints for beta, and tests pass so we should be good to go!

**Pull request merged**
