### PR TITLE
kms: Add support for the MAC key purpose.

### PR DESCRIPTION
**Pull request by bdhess**
Adds support for the [new](https://cloud.google.com/kms/docs/release-notes#August_20_2021) *MAC* key purpose in Cloud KMS.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).

   **Tests failed to run:**
```
 ❯ make testacc TEST=./google TESTARGS='-run=TestAccKmsCryptoKey_hsmMacKey'

==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccKmsCryptoKey_hsmMacKey -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
# github.com/hashicorp/terraform-provider-google/google [github.com/hashicorp/terraform-provider-google/google.test]
google/privateca_operation.go:50:167: undefined: time
google/privateca_operation.go:58:9: undefined: json
google/privateca_operation.go:61:121: undefined: time
google/provider.go:1086:68: undefined: resourcePubsubLiteReservation
FAIL    github.com/hashicorp/terraform-provider-google/google [build failed]
FAIL
make: *** [testacc] Error 2
```
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
kms: Added support for the MAC key purpose
```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Sorry, I missed this!

Looks like the test you added is failing with:
```
Error: Unsupported argument
on terraform_plugin_test.tf line 24, in resource "google_kms_crypto_key" "crypto_key":
24:   version_template = {
An argument named "version_template" is not expected here. Did you mean to
define a block of type "version_template"?
--- FAIL: TestAccKmsCryptoKey_hsmMacKey (3.99s)
```

Looks like a typo in the test config. Were you able to successfully run this test?

**Comment by bdhess** [comment]
Oops, hope this fixes it

**Comment by melinath** [comment]
@bdhess could you rebase this PR?

**Pull request closed without merging**
