### PR TITLE
docs: Update description of google_cloud_run_service

### PR DESCRIPTION
**Pull request by steren**
- Use simpler descrption consistent with GCP product page.
- Remove Warning about Cloud Run for Anthos, which is considered an entirely separated product that should not be surfaced within the context of Cloud Run
- Add a Warning for the availability of the V2 resource
- Update description of a few attributes to remove links to lKnative or Kubernetes documentation (which do not exactly match the Cloud Run attribute).

```release-note:none
N/A
```

### CODE REVIEW

**Review by melinath — APPROVED** [review]
LGTM - this does introduce drift compared to the [API docs](https://cloud.google.com/run/docs/reference/rest/v1/namespaces.services), which include all these links to k8s docs.

**Comment by steren** [comment]
Yes, we have internal issues to track cleaning up the API proto too.

Do you confirm this file is *not* auto generated from the proto? (and I should send this manual PR?)

**Review by melinath — CHANGES_REQUESTED** [review]
This will need to be updated to resolve merge conflicts. terraform.yaml files were all removed and the information was consolidated into the product.yaml file & per-resource files. https://github.com/GoogleCloudPlatform/magic-modules/blob/fd0e701fbce97231421bea0a5508afe2c4dd5ef0/mmv1/products/cloudrun/Service.yaml#L44 is the relevant warning that will need to be updated instead.

**Comment by melinath** [comment]
@steren correct, this is not autogenerated from the proto.

**Comment by steren** [comment]
closed in favor of https://github.com/GoogleCloudPlatform/magic-modules/pull/7532

**Pull request closed without merging**
