### PR TITLE
Sync main feature branch provider functions

### PR DESCRIPTION
**Pull request by SarahFrench**
>1. Checkout a branch from main `sync-main-FEATURE-BRANCH-XXX` and create a PR to merge it into your `FEATURE-BRANCH-XXX`. 
>We sync feature branches via PRs. No direct push is allowed for feature branches, same as main.
>2. Resolve any conflicts, if there are any.
>3. Wait until all tests have finished and passed.
>We need VCR to record cassettes for the branch.
>No new test failures should be introduced.
>4. Get the PR approved and merge it (`commit merge` if it's for major release branch, `squash and merge` regular merge method for other feature branches)

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Force pushed to remove my last merge commit - I had introduced some problems when resolving the merge conflicts 😮‍💨

**Comment by shuyama1** [comment]
@SarahFrench Looks like there's still some build errors. Apologize that this seems a fairly complicated process for syncing at this point. Let's create a PR to merge the feature branch to the main directly and hopefully it will be easier to resolve merge conflicts there.

**Comment by SarahFrench** [comment]
Closing in favour of https://github.com/GoogleCloudPlatform/magic-modules/pull/10288

**Comment by SarahFrench** [comment]
Screenshot 2024-03-26 at 12 18 47


Of the failing checks:
- cla/google - the affected individual in the CLA check had the CLA signed at the time of their contribution : https://github.com/GoogleCloudPlatform/magic-modules/pull/9278
- terraform-provider-breaking-change-test - [the breaking change is OK'd in the original PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10194#issuecomment-1997640171)
- VCR tests - this is a failure due to missing VCR cassettes `Requested interaction not found`

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
