### PR TITLE
fix recording upload failure in nightly vcr run

### PR DESCRIPTION
**Pull request by iyabchen**
https://github.com/hashicorp/terraform-provider-google/issues/18249
Fixing empty folder causing upload failure. Instead of returning the error, just print a warning, since in some cases, recording mode does not generate any cassettes even though tests pass. 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by iyabchen** [comment]
@shuyama1 I created this branch to test the recording
- it disabled fetch recording at replay, to trigger replay failure
- it only runs the service/compute
- it uploads to a temp folder
- include the fix for copy from src + "/*" to destination to see whether that helps. 

Could you help setup the trigger?

**Review by shuyama1 — COMMENTED** [review]
@iyabchen you'll also need to modify .ci/gcb-vcr-nightly.yml to use the golang version in this PR, similar to https://github.com/GoogleCloudPlatform/magic-modules/pull/11148. I'll create a testing trigger after.

**Comment by iyabchen** [comment]
Done! 

> @iyabchen you'll also need to modify .ci/gcb-vcr-nightly.yml to use the golang version in this PR, similar to #11148. I'll create a testing trigger after.

**Comment by shuyama1** [comment]
Trigger the testing trigger

/gcbrun

**Comment by shuyama1** [comment]
@iyabchen Hey, I've set up the trigger. The current run is failing, you'll probably need to resolve the merge conflicts first. Any commits to the branch `nightly-vcr-test-go-record-fix` should trigger the cloud build job automatically. Please let me know if you have any questions.

**Comment by iyabchen** [comment]
@shuyama1 
- Tests showed that it can do the recording. 
- I have reverted the debug code.  
- Main change is to just print warning when upload failed instead of returning an error. 
- Some template change to make it print the error if there is any.

**Comment by iyabchen** [comment]
Just rebased to latest main

**Review by shuyama1 — COMMENTED** [review]
This change makes sense to me, as it aligns with the logic in the current script and the presubmit VCR. Would you mind resolve the conflicts with rebasing your PR? Sorry for the delay on review.

**Comment by iyabchen** [comment]
Sorry for delay, just rebased and force pushed.

**Review by shuyama1 — APPROVED** [review]
LGTM. Thank you! I'll monitor tonight's run.

**Pull request merged**
