### PR TITLE
Add fields to InterconnectAttachment to allow for PARTNER interconnects

### PR DESCRIPTION
**Pull request by cblecker**
This is my first magic-modules PR -- Please let me know if there are additional steps I should take.
ref: https://github.com/terraform-providers/terraform-provider-google/issues/2942
cc: @ndmckinley 

-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by ndmckinley** [comment]
Looks great.  Let me go ahead and get the downstreams generated and we'll take a look!

**Comment by cblecker** [comment]
@ndmckinley I actually found another output status field that's needed. Can I just update this PR?

**Comment by cblecker** [comment]
I reviewed the [API spec](https://www.googleapis.com/discovery/v1/apis/compute/v1/rest) for the enum fields type and spec, and updated with the full list of options.

**Comment by ndmckinley** [comment]
Yep, go ahead and update the PR!  I'll just have to do a quick review of each successive commit - just a quick glance.

**Comment by ndmckinley** [comment]
Ah, you see that failure under `checks` there?  Here's the error message.

```
bundler: failed to load command: compiler (compiler)
Psych::SyntaxError: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 4238 column 7
  /root/.rbenv/versions/2.6.0/lib/ruby/2.6.0/psych.rb:456:in `parse'
  /root/.rbenv/versions/2.6.0/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
  /root/.rbenv/versions/2.6.0/lib/ruby/2.6.0/psych.rb:390:in `parse'
  /root/.rbenv/versions/2.6.0/lib/ruby/2.6.0/psych.rb:349:in `safe_load'
  /tmp/build/fb9bd761/magic-modules-branched/google/yaml_validator.rb:25:in `parse'
  /tmp/build/fb9bd761/magic-modules-branched/api/compiler.rb:35:in `run'
  compiler:117:in `block in <top (required)>'
  compiler:101:in `each'
  compiler:101:in `<top (required)>'
```

You should be able to reproduce locally - do you get the same result?

**Comment by cblecker** [comment]
@ndmckinley Oops! yeah, indentation issue. Fixed and tested locally!

**Comment by ndmckinley** [comment]
On its way through the pipeline!  Watch the status indicators below - should show up under `concourse-ci/*` - if you see any failures, the "details" link should show you the Concourse CI logs.  There's a chance you'll have access issues, but if that happens, let me know.

**Comment by cblecker** [comment]
Everything looks green from here :)

**Comment by ndmckinley** [comment]
These changes look great to me!  I don't have access to an interconnect - could you post the debug logs of creating one of each type of interconnect attachment?  If that looks right, I'll approve and this will be out in the next release.

**Comment by cblecker** [comment]
@ndmckinley I unfortunately don't have a dedicated interconnect either, so I can't set up that type. I have access to a partner interconnect, but can only do the first half of setup for it to go into a pending state, as the second half of setup requires third-party vendor action.

**Comment by ndmckinley** [comment]
Okay, I do have access to someone who's got access to a dedicated interconnect - if you can test the first part of the partner interconnect, by our powers combined (:globe_with_meridians:), we can merge this change.

**Comment by cblecker** [comment]
Okay, so I created these two objects:
```hcl
resource "google_compute_router" "router1" {
  name    = "rooter-1"
  network = "default"

  bgp {
    asn            = 16550
    advertise_mode = "CUSTOM"

    advertised_ip_ranges {
      range = "10.0.0.0/8"
    }
  }
}

resource "google_compute_interconnect_attachment" "vlan1" {
  name                     = "vlan1"
  type                     = "PARTNER"
  router                   = "${google_compute_router.router1.name}"
  edge_availability_domain = "AVAILABILITY_DOMAIN_1"
}
```

I checked out and compiled https://github.com/terraform-providers/terraform-provider-google/commit/75909d79997d4aa5f294e89824bdedd2badfbf76, then used it to `terraform apply` those two objects.

Debug log is here: https://gist.github.com/cblecker/f7bfe8030d47035a401564f0514d57eb

I've modified the log slightly to substitute the GCP project name, and my google account name from the log.

**Comment by ndmckinley** [comment]
Looks great! I'll wait for mine to get back to me and we'll see what we can do.  Thank you!

**Comment by rambleraptor** [comment]
(The Ansible downstream looks good to me!)

**Comment by ndmckinley** [comment]
Okay, almost there!  You just need to set `type` to `Optional` and `Computed`, by adding the `default_from_api: true` flag to `terraform.yaml`.  Then I can merge it.

**Comment by cblecker** [comment]
@ndmckinley Done!

**Comment by cblecker** [comment]
Thanks for the help in getting this in!

One last question: Do you happen to know when the next expected cut of the terraform google provider will be?

**Comment by ndmckinley** [comment]
We're working that out now, but if it's more than 2 weeks from now, I'd be surprised.  :)

**Comment by cblecker** [comment]
Sounds great! Thank you!

**Pull request merged**
