### PR TITLE
Prepared composer-multi-project-monitoring-snippet for inclusion in C…

### PR DESCRIPTION
**Pull request by leahecole**
….G.C. documentation

This PR is to properly migrate [this Composer resource](https://github.com/leahecole/composer_monitoring/tree/main/Cross_Project_Composer_Monitoring), originally created by the Composer PM, to a place where the TF code will be regularly tested. It will be cross-referenced alongside other [Cloud Composer Utilities](https://github.com/GoogleCloudPlatform/composer-utilities)

WRT Testing - I followed the internal guide for "Preparing a sample for GitHub" and tested it manually, and I worked with @msampathkumar on using tftools (which got a cool new upgrade :smile:) for this particular sample. 

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x][Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
Add Composer example using existing Cloud Monitoring resources to be tested here and cross referenced elsewhere

```

### CODE REVIEW

**Comment by leahecole** [comment]
I updated the release note and made it type "none" because I felt like the other types didn't properly encompass what I'm going for here, but please let me know if it should be something else! This is my first time contributing to this repo and I did my best to follow the docs, but I'm sure there could be room for improvement. Please also feel free to ping me if updates are needed.

**Comment by c2thorn** [comment]
Hi @leahecole 
Sorry for the timing here, but MM no longer supports CGC samples. I believe the "terraform-on-cgc" documentation has just been updated with the new workflow, but essentially you'll be making PR's against https://github.com/terraform-google-modules/terraform-docs-samples directly

**Comment by leahecole** [comment]
> Hi @leahecole Sorry for the timing here, but MM no longer supports CGC samples. I believe the "terraform-on-cgc" internal documentation has just been updated with the new workflow, but essentially you'll be making PR's against https://github.com/terraform-google-modules/terraform-docs-samples directly

No worries - I'll make a PR directly against terraform-docs-samples - thanks for letting me know!

**Comment by leahecole** [comment]
Great! replaced with https://github.com/terraform-google-modules/terraform-docs-samples/pull/155

**Pull request closed without merging**
