### PR TITLE
Fix bigtable_gc_policy: the read was not using the right column name

### PR DESCRIPTION
**Pull request by jcanseco**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
bigtable: Fixed broken read logic in `google_bigtable_gc_policy`
```

### CODE REVIEW

**Comment by slevenick** [comment]
So if I'm reading this right the existing logic will only successfully read the gc policy if the family name is the same as the gc policy name?

**Comment by jcanseco** [comment]
> So if I'm reading this right the existing logic will only successfully read the gc policy if the family name is the same as the gc policy name?

The existing logic will only successfully read the GC policy if the GC policy's column name happens to match the table name.

**Comment by rileykarson** [comment]
As I understand it will fail to (re-)set the `id`, so even with the error the resource still generally worked. Or am I misunderstanding it?

**Comment by jcanseco** [comment]
Yep, my understanding is the same. There shouldn't have been issues for Terraform in particular I think. This was just an issue for us since we're reliant on the TF Read correctly setting the ID if the resource exists.

**Comment by kevinsi4508** [comment]
This will fail to detect if a gc policy is updated outside of TF. Can we get this reviewed and committed? Thanks!

**Pull request closed without merging**
