### PR TITLE
ci changes for TFV, generated tests

### PR DESCRIPTION
**Pull request by ScottSuarez**
The is PR in preparation for merging the test generation changes into MM

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — COMMENTED** [review]
Would it at all make sense to store the test files in the same directory as the resource converters? That would better match Golang conventions (& it's what the provider does)

**Comment by ScottSuarez** [comment]
> Would it at all make sense to store the test files in the same directory as the resource converters? That would better match Golang conventions (& it's what the provider does)

So the tests are going to be stored in the `/test` directory alongside the current test code. `read_test` and `cli_test`. All the relevant test code and accessory functions are in the is `/test` package so I consider it to make sense to retain it there.

The `testdata/generatedconvert` is where the generated, plan converted json will live. This will in effect, be present so the developer can see if their change is going to effect tfv.

@melinath

**Review by melinath — APPROVED** [review]
I'm fine with reusing the test dir for now because it makes the shared utils easier but in the long run this should probably go in with the converters.

**Comment by ScottSuarez** [comment]
ack, we can work on transitioning these to the converters and deprecating test directory.

**Pull request merged**
