### PR TITLE
update for support of CMEK for vertex ai resource

### PR DESCRIPTION
**Pull request by googlerjk**
Added support to CMEK to vertexai resource featurestore.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
vertexai: added `encryption_spec` field to `google_vertex_ai_featurestore` resource (beta)
```

### CODE REVIEW

**Comment by c2thorn** [comment]
re-rolling the reviewer, as I need to catch up on other reviews so I won't be able to get to this one in a while.
Couple things I noticed already though @googlerjk 

- Set the PR out of draft mode when you want someone to review
- Add the service to the release note

**Review by shuyama1 — COMMENTED** [review]
Looks like the tests failed due to not having `provider = google-beta` in the configuration, as  this is a beta-only resource.  
Plus, would you mind modifying the release note a bit based on the `enhancements` example [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md#examples)

**Comment by shuyama1** [comment]
@googlerjk I modified the changelog a bit, please let me know if that makes sense:
1. changed service name from `vertex_ai` to `vertexai`
2. added beta label at the end as `google_vertex_ai_featurestore ` is a beta-only resource, so the change only affects beta provider and we only want include this changelog in the beta provider release.

**Review by shuyama1 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
