### PR TITLE
fix enforce_on_key_configs

### PR DESCRIPTION
**Pull request by edwardmedia**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/14905

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed wrongly trigger recreation on changes of `enforce_on_key_configs` on `google_compute_security_policy`
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Note for myself after the acceptance tests complete: rules in this policy resource are updated [through add/delete actions](https://github.com/hashicorp/terraform-provider-google-beta/blob/3cd660523d5fb52f79bed6a67bb0fb7ae260c92e/google-beta/services/compute/resource_compute_security_policy.go#L761-L827) because the resource is handwritten and uses a client library. The underlying API allows patches of the policy, patches of specific rules inside the policy, and imperative methods like [addRule](https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies/addRule) and [removeRule](https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies/removeRule).

Given this info, it definitely doesn't make sense for ForceNew to be there as individual rules can be deleted from the policy without issue and the API doesn't describe special behaviour for this field.

**Comment by SarahFrench** [comment]
Looks like the ForceNew for this field may have been masking an issue in an acceptance test?

The errors above say:
> Error 400: Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs': ''. Only one of enforceOnKey and enforceOnKeyConfigs can be specified., invalid

Here's the [relevant part of API docs](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies#SecurityPolicy.FIELDS.inlinedField_25) that confirms this.

Maybe we should remove these lines from the acceptance tests:
- https://github.com/GoogleCloudPlatform/magic-modules/blob/308e362fb914c212c20ea31f99605fa261011063/mmv1/third_party/terraform/tests/resource_compute_security_policy_test.go.erb#L1329
- https://github.com/GoogleCloudPlatform/magic-modules/blob/308e362fb914c212c20ea31f99605fa261011063/mmv1/third_party/terraform/tests/resource_compute_security_policy_test.go.erb#L1375

**Comment by edwardmedia** [comment]
This PR is put on hold as the api can't be reset between `enforceOnKeyConfigs` and `enforceOnKey`. Although only one is provided for the update, below error is still bing hit

```
Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs': ''. Only one of enforceOnKey and enforceOnKeyConfigs can be specified.
```

**Review by SarahFrench — APPROVED** [review]
Sorry for the wait - looks good to me

**Pull request merged**
