### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by nphilbrook**
Recently while working on my first TPG contribution I discovered a few details that I didn't see covered in the docs. I think these will make future contributors' experiences better. Please give me any feedback!

You can preview these changes at [my fork's root page](https://github.com/nphilbrook/magic-modules/tree/nphilbrook_doc_updates)

I hope this qualifies as a "very small change" that doesn't require an issue 😁 .

If this PR is for Terraform, I acknowledge that I have:

- [n/a] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [n/a] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [n/a] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [n/a] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
Documentation updates only.
```

### CODE REVIEW

**Comment by shuyama1** [comment]
Hey @nphilbrook! Thank you so much for contributing to our documentation! These changes can definitely benefits future contributors. I am currently working on rewriting the Magic Modules ReadMe Page to contain more information and guidance, and I believe it contains some of these changes. 
I'll let you know when the PR is out and you can take a look and let us know if there's more content we should add. Again thank you so much!

**Comment by nphilbrook** [comment]
> Hey @nphilbrook! Thank you so much for contributing to our documentation! These changes can definitely benefits future contributors. I am currently working on rewriting the Magic Modules ReadMe Page to contain more information and guidance, and I believe it contains some of these changes. I'll let you know when the PR is out and you can take a look and let us know if there's more content we should add. Again thank you so much!

Sounds great, have fun with the rewrite.

**Comment by shuyama1** [comment]
Hey @nphilbrook! I've added your change in https://github.com/GoogleCloudPlatform/magic-modules/pull/6547 and also added you as the co-author to the PR. Please let me know if there's more I should add. Thank you so much for helping with the documentation! Feel free to make more changes if you think there's area should be modified or added! Really appreciate it!

**Comment by nphilbrook** [comment]
> Hey @nphilbrook! I've added your change in #6547 and also added you as the co-author to the PR. Please let me know if there's more I should add. Thank you so much for helping with the documentation! Feel free to make more changes if you think there's area should be modified or added! Really appreciate it!

Looks great, thank you for including my changes and giving credit, really appreciate it.

**Pull request closed without merging**
