### PR TITLE
Update storage_bucket.html.markdown public_access_prevention

### PR DESCRIPTION
**Pull request by 880831ian**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
After testing, it was found that when using Google Storage to create a Bucket, the default value of public_access_prevention is enforced, not inherited.
```
截圖 2023-12-22 下午4 44 04

### CODE REVIEW

**Comment by 880831ian** [comment]
@rileykarson Hi, can you check the PR for me? Thanks!

**Review by rileykarson — COMMENTED** [review]
I think this needs to base onto `main` or merge `main` into it, the CI definitions in the base are outdated.

**Review by rileykarson — COMMENTED** [review]
Same comment as https://github.com/GoogleCloudPlatform/magic-modules/pull/9710#pullrequestreview-2111270514, we'll need to rebase/merge main onto this branch!

**Review by rileykarson — COMMENTED** [review]
I looked into this some more- it looks like the Console has applied its own default where it does default to on- which likely means "enforced" here- but a new bucket created through the API without specifying the field is still "inherited":

```
  "iamConfiguration": {
    "bucketPolicyOnly": {
      "enabled": false
    },
    "uniformBucketLevelAccess": {
      "enabled": false
    },
    "publicAccessPrevention": "inherited"
  },
```

And with a minimal Terraform config:

```
public_access_prevention    = "inherited"
```

Based on that I think the current docs are correct and am gonna close this out. Apologies for not checking that sooner- based on your findings I figured they'd changed it, the provider is just not very sensitive to default changes on this field.

**Comment by 880831ian** [comment]
thank you !

**Pull request closed without merging**
