### PR TITLE
Add bigquery connection of type CLOUD_RESOURCE & make other examples GA.

### PR DESCRIPTION
**Pull request by gutschenritter**
Add connection of type cloud_resource to `google_bigquery_connection`. Fixes hashicorp/terraform-provider-google#11671

If this PR is for Terraform, I acknowledge that I have:

- [ X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery connection: Added connection of type cloud_resource for `google_bigquery_connection`
```

```release-note:enhancement
bigquery connection: Made `google_bigquery_connection` part of GA terraform provider.
```

### CODE REVIEW

**Comment by gutschenritter** [comment]
`make lint` failed but none of the products it failed for were bigquery connection. 

Saw errors like these:
```
==> Checking source code against linters...
google/config.go:25:2: `v2` redeclared in this block (typecheck)
	"google.golang.org/api/bigtableadmin/v2"
	^
google/config.go:24:2: other declaration of v2 (typecheck)
	"google.golang.org/api/bigquery/v2"
	^
google/config.go:27:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/cloudbuild/v1"
	^
google/config.go:26:2: other declaration of v1 (typecheck)
	"google.golang.org/api/cloudbilling/v1"
	^
google/config.go:28:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/cloudfunctions/v1"
	^
google/config.go:29:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/cloudidentity/v1"
	^
google/config.go:30:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/cloudiot/v1"
	^
google/config.go:31:2: `v1` redeclared in this block (typecheck)
	"google.golang.org/api/cloudkms/v1"
	^
```

Is this a blocking issue?

**Comment by melinath** [comment]
linting is passing in CI/CD - probably a go version mismatch (or different linter version) on your local machine. Nothing to worry about. The remaining test failure is also unrelated.

**Comment by melinath** [comment]
since this is making a new resource GA I'm doing an explicit run of the new tests in GA as well: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/288989 (the default test run is in beta)

**Comment by gutschenritter** [comment]
> since this is making a new resource GA I'm doing an explicit run of the new tests in GA as well: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/288989 (the default test run is in beta)

Did these tests pass?  (I can't view the link) I ran them locally & they succeeded.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
