### PR TITLE
Update SQL Instance sweeper to check common prefixes

### PR DESCRIPTION
**Pull request by rileykarson**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Ah, the diff is worse than I intended because I split it out to its own file at the same time. Relevant lines are https://github.com/GoogleCloudPlatform/magic-modules/pull/6934/files#diff-43373b6f1f056c3749e781b40acc8a4050b2011489498ce49594d7f4ca576e30R45-R48 & https://github.com/GoogleCloudPlatform/magic-modules/pull/6934/files#diff-6b617b136d6b28b52637ae8ec0430d3680901d2a01158811a70a3c44063b3ae6L98-L109, as well as the init() function and sweep function name (which I changed to match conventions in generated files)

**Comment by roaks3** [comment]
I'm still seeing `tf-lw` and `sqldatabasetest` prefixes in our tests, but not noticing them in the prefix list here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/utils/gcp_sweeper_test.go#L12-L21. Am I misunderstanding part of this change?

**Comment by rileykarson** [comment]
Oh, nope, I just missed that we were still using those prefixes. The leaked resources weren't using them because they were getting cleaned up, and we'd had an effort at one point to move all resources to `tf-test-` a few years ago. I'd assumed we just missed the sweeper, since it wasn't in a standard spot. Added a commit changing 'em over.

**Review by roaks3 — APPROVED** [review]
Ah ok awesome, LGTM!

**Pull request merged**
