### PR TITLE
Added examples for SSL/TLS certs and HA

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Intending to add these here:

https://cloud.google.com/sql/docs/mysql/configure-ssl-instance
https://cloud.google.com/sql/docs/postgres/configure-ssl-instance
https://cloud.google.com/sql/docs/configure-ssl-instance

https://cloud.google.com/sql/docs/sqlserver/configure-ha
https://cloud.google.com/sql/docs/postgres/configure-ha
https://cloud.google.com/sql/docs/mysql/configure-ha

```release-note:none
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Builds failing due to file mismatch. Did you build this locally?

**Comment by betsy-lichtenberg** [comment]
> Builds failing due to file mismatch. Did you build this locally?

What do you mean file mismatch? I'm not sure how to build locally. I did run 'terraform apply' in Cloud Shell.

**Comment by ScottSuarez** [comment]
What environment are you working on? I can collaborate with you in order to get you to a point where you can build the provider locally.

**Comment by betsy-lichtenberg** [comment]
I think I understand what the problem is. I'll try to fix. If my fix doesn't work, I'll redo as two separate PRs.

**Comment by ScottSuarez** [comment]
@betsy-lichtenberg, given the volume of changes you make I think it's pretty important for you to be able to build locally. This would give you higher velocity and reduce the strain on our reviewer pool when things don't go as expected.

**Comment by ScottSuarez** [comment]
I'm happy to help/work with you if you like

**Comment by betsy-lichtenberg** [comment]
OK, great! I'll schedule some time with you.

**Pull request closed without merging**
