### PR TITLE
Showing error details for quota exceeded error for gce operations

### PR DESCRIPTION
**Pull request by upaul9705**
Surfacing error details when compute operation has quota exceeded error while creating a GCE resource.
Quota exceeded error details are provided in quota_info. This change will surface the details in the terraform response.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: surface error details for Compute Operation with quota exceeded errors.
```

### CODE REVIEW

**Comment by upaul9705** [comment]
Hi Sarah, A gentle ping for reviewing the PR. Thanks.

**Review by SarahFrench — COMMENTED** [review]
👋  Thanks for your patience, these changes look fine to me and I'm happy to approve and merge. The merge conflicts are blocking that though - could you please resolve them?

**Comment by SarahFrench** [comment]
Checks are now failing 🤔 

Ah- I think I had missed that this PR included a _unit_ test and there have been changes in our CI that make failing unit tests clearer on PRs.

I can see this in the failing `terraform-provider-google-build-and-unit-tests` check that there are some problems with `QuotaMessageWithDetailsNoDimensions` and `QuotaMessageWithDetailsWithDimensions` test cases :


```
--- FAIL: TestComputeOperationError_Error (0.00s)
    --- FAIL: TestComputeOperationError_Error/QuotaMessageWithDetailsNoDimensions (0.00s)
        compute_operation_test.go:254: expected
            Quota DISKS_TOTAL_GB exceeded.  Limit: 1100.0 in region us-central1.
            
            to contain, "metric name = compute.googleapis.com/disks_total_storage", and did not
        compute_operation_test.go:254: expected
            Quota DISKS_TOTAL_GB exceeded.  Limit: 1100.0 in region us-central1.
            
            to contain, "limit name = DISKS-TOTAL-GB-per-project-region", and did not
    --- FAIL: TestComputeOperationError_Error/QuotaMessageWithDetailsWithDimensions (0.00s)
        compute_operation_test.go:254: expected
            Quota DISKS_TOTAL_GB exceeded.  Limit: 1100.0 in region us-central1.
            
            to contain, "metric name = compute.googleapis.com/disks_total_storage", and did not
        compute_operation_test.go:254: expected
            Quota DISKS_TOTAL_GB exceeded.  Limit: 1100.0 in region us-central1.
            
            to contain, "limit name = DISKS-TOTAL-GB-per-project-region", and did not
        compute_operation_test.go:254: expected
            Quota DISKS_TOTAL_GB exceeded.  Limit: 1100.0 in region us-central1.
            
            to contain, "dimensions = map[region:us-central1]", and did not
```

**Comment by upaul9705** [comment]
The tests are passing now.

**Review by SarahFrench — APPROVED** [review]
LGTM, merging now

**Pull request merged**
