### PR TITLE
Make cluster location a required field

### PR DESCRIPTION
**Pull request by GauravJain21**
Cluster location is marked as optional. It should be marked as required because we might extend the regional API to zonal and therefore can't use the provider default region/environment variable for region.

Solutions considered:

1. Inherit the provider location/region
    - It doesn't work right now because it is not added in [ProviderConfig](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/utils/provider.go.erb#L536)
    - It is undesirable as it restricts us from extending the API from regional to [zonal](https://critique.corp.google.com/cl/512850713/depot/google3/google/cloud/alloydb/v1main/resources.proto?version=s1#26).
2. Get the location from environment variables
    - Same issue as non-extensibility.
3. Mark Location as a required field
    - Ensures extensibility of the APIs in future.

Solution accepted: Mark location as a required field.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
alloydb: changed `location` from `optional` to `required` for `google_alloydb_cluster`. `location` had previously been marked as optional, but operations failed if it was omitted, and there was no way for `location` to be inherited from the provider configuration or from an environment variable. This means there was no way to have a working configuration without `location` specified.
```

```release-note:bug
alloydb: changed `location` from `optional` to `required` for `google_alloydb_cluster`. `location` had previously been marked as optional, but operations failed if it was omitted, and there was no way for `location` to be inherited from the provider configuration or from an environment variable. This means there was no way to have a working configuration without `location` specified.
```

### CODE REVIEW

**Comment by roaks3** [comment]
There is a tiny bit more context at b/277159591. Notably, this line:

> Currently, API calls fail if we don't provide the location in AlloyDB cluster resource

I've verified that this is the case, so I believe this would not be a breaking change (any existing config without the location would be failing).

The one question I have is whether there is any way the location could be implicitly set for existing configurations. This appears to be covered in your "Solutions considered" section, but I'd like to confirm.

**Comment by GauravJain21** [comment]
The location appears in terraform plan if inherited from provider but the same doesn't get used while applying the terraform plan. The location is not passed to the API. So any existing configuration where either location is absent or is being inherently set fails.
I have made it a required field.

**Review by roaks3 — APPROVED** [review]
Hey @GauravJain21 , thanks for your patience here. We've discussed this one and determined that it is reasonable to include in a minor version bump, but we want to make sure the changelog entry is very detailed about why this will not have negative impact. Feel free to take a pass at this if you'd like, but otherwise I will plan to write that up tomorrow morning, and then we can merge this change.

**Comment by GauravJain21** [comment]
Hey @roaks3 I have updated the release-note. Can you please review and edit if required.

**Comment by roaks3** [comment]
👍 I tweaked the message a little bit, and duplicated the message in both a note and bugfix, to match what was done previously here: https://github.com/GoogleCloudPlatform/magic-modules/pull/6936.

**Review by roaks3 — APPROVED** [review]

**Comment by GauravJain21** [comment]
Hey @roaks3 Can you please merge this PR? I don't have the permission to do so.

**Pull request merged**
