### PR TITLE
Updated typos

### PR DESCRIPTION
**Pull request by wyardley**
Can break these up differently if desired. These resolve downstream golangci-lint misspelling warnings.
Almost all the changes are in docs or function naming only. There are one or two actual fixes (I think) of real enum values, in particular the one in `mmv1/products/gkehub2/Feature.yaml` (I added a release note for this one, since that's actually fixing something).

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:bug
gkehub: fixed allowable value `INSTALLATION_UNSPECIFIED` in `template_library.installation`
```

### CODE REVIEW

**Comment by wyardley** [comment]
`TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample` (beta only, I think) seems to work for me locally with or without these changes.

**Comment by wyardley** [comment]
Pushed a potential fix for `TestAccContainerCluster_withFleetConfig` in #12307

**Comment by wyardley** [comment]
@BBBmau would you mind running the tests over again? Hopefully #12307 helps with the fleet one, and maybe the other one is flaky, unless you're seeing anything unusual in the failure log for that one? Seems to work for me locally with these changes in both recording and replaying mode.

**Comment by wyardley** [comment]
@BBBmau can you share the error from the CI run of `TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample`, and do you think it's related?

Tried a few more times locally in recording and replaying mode (with the changes from this PR, including building for all products vs. just `backupdr`) and still can't reproduce the failure.

**Comment by wyardley** [comment]
@BBBmau I rebased it, and also added one more tiny fix (in a separate commit) that I noticed elsewhere.

**Comment by BBBmau** [comment]
can you rebase once more? We look to be getting some conflicts

**Comment by wyardley** [comment]
Rebased. Looks like just `mmv1/third_party/terraform/fwprovider/framework_validators_test.go` being removed upstream.

**Review by BBBmau — APPROVED** [review]
tests can be ignored. Thanks for this!

**Pull request merged**
