### PR TITLE
Graduate support of GKE Queued Provisioning to GA

### PR DESCRIPTION
**Pull request by tosi3k**
Graduate support of GKE Queued Provisioning to GA

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted `google_container_node_pool.queued_provisioning` to GA (ga)
```

### CODE REVIEW

**Comment by tosi3k** [comment]
Nvm, we still need to wait for the necessary Go client to be released.

**Comment by tosi3k** [comment]
Actually, we can progress with it even now, it should be good to go with the current version of `google.golang.org/api` package (`v0.167.0`).

@roaks3 PTAL :)

**Comment by kisieland** [comment]
@roaks3 what seems to be the issue for the build?

**Comment by tosi3k** [comment]
>confirmation that the GA tests pass locally for you (GA tests do not get run in our PR checks)

They pass when I execute them on my machine :).

**Review by roaks3 — APPROVED** [review]

**Pull request merged**
