### PR TITLE
Add support for NEG type PRIVATE_SERVICE_CONNECT in NetworkEndpointGroup

### PR DESCRIPTION
**Pull request by xuchenma**
This PR adds support for NEG type PRIVATE_SERVICE_CONNECT in NetworkEndpointGroup, which solves https://github.com/hashicorp/terraform-provider-google/issues/11631

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added support for NEG type `PRIVATE_SERVICE_CONNECT` in `NetworkEndpointGroup`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Any reason the `exactly one of` blocks are being removed here?

**Comment by xuchenma** [comment]
> Any reason the `exactly one of` blocks are being removed here?

Those parameters are only valid when networkEndpointType is "SERVERLESS". They shouldn't be set when networkEndpointType is "PRIVATE_SERVICE_CONNECT".

**Comment by ScottSuarez** [comment]
Should exactly one of not just be extended to include `networkEndpointType` then?

**Comment by xuchenma** [comment]
> Should exactly one of not just be extended to include `networkEndpointType` then?

I'm not sure I follow this. `networkEndpointType` is an Enum, it used to only have one value `SERVERLESS`. When it is SERVERLESS, there has to be "exactly one of" those blocks specified.
This PR adds `PRIVATE_SERVICE_CONNECT` to the Enum. When that is chosen, none of the previous "exactly one of" blocks should be set.

**Comment by ScottSuarez** [comment]
Sorry perhaps `ConflictsWith` would be more apt for this usecase.

My concern is making sure fields are not set when they are not able.

**Comment by xuchenma** [comment]
That makes sense. Can you link an example that uses `ConflictsWith `?

**Comment by ScottSuarez** [comment]
Sure ! 
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/api.yaml#L3596-L3605

**Comment by ScottSuarez** [comment]
While this is true for `A`, `b` continues to conflict with `c`, `d`, and `e`. Those properties continue to be unable to be set together, correct?

**Comment by xuchenma** [comment]
Oh I see, updated!

**Review by ScottSuarez — APPROVED** [review]
lgtm

**Pull request merged**
