### PR TITLE
Change advertised_ip_ranges fields in google_compute_router_peer and google_compute_router resources to Sets

### PR DESCRIPTION
**Pull request by LucaPrete**
**[breaking change for 6.0.0 major release]**

Change advertised_ip_ranges fields in google_compute_router_peer and google_compute_router resources to Sets.

Fixes [hashicorp/terraform-provider-google/issues/9353](https://github.com/hashicorp/terraform-provider-google/issues/9353)

```release-note:enhancement
compute: changed the `advertised_ip_ranges` fields in both `google_compute_router_peer` and `google_compute_router` resources to be sets. This will reduce diffs due to re-ordering.
```

### CODE REVIEW

**Comment by LucaPrete** [comment]
@SarahFrench I opened this because I wasn't able to work on `https://github.com/GoogleCloudPlatform/magic-modules/pull/10118`. In case the @Maarc-D is able to move forward with the other I'm happy to abandon this one.

I applied the changes you recommended and it's well understood this is a breaking change that can be merged in 6.0.0.

**Comment by SarahFrench** [comment]
I'll leave review to @roaks3.

If this PR addresses ordering diffs on this field by converting it to a Set in 6.0.0 then this PR will also need to remove the ordering logic added in https://github.com/GoogleCloudPlatform/magic-modules/pull/10572/files

**Comment by LucaPrete** [comment]
Ah yes! Good point. I’ll do that.

Il giorno ven 31 mag 2024 alle 16:26 Sarah French ***@***.***>
ha scritto:

**Comment by LucaPrete** [comment]
> I'll leave review to @roaks3.
> 
> If this PR addresses ordering diffs on this field by converting it to a Set in 6.0.0 then this PR will also need to remove the ordering logic added in https://github.com/GoogleCloudPlatform/magic-modules/pull/10572/files

@SarahFrench done! Please, check if it looks good to you. @roaks3 this should be ready (I know you won't be able to merge until the release...)

**Comment by LucaPrete** [comment]
@SarahFrench @roaks3 I see in my local tests that something is failing in the generated router code:

```
make testacc TEST=./google-beta/services/compute TESTARGS='-run=
TestAccComputeRouter_routerBasicExample'
==> Checking that code complies with gofmt requirements...
go vet
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta/services/compute -v -run=TestAccComputeRouter_routerBasicExample -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccComputeRouter_routerBasicExample
=== PAUSE TestAccComputeRouter_routerBasicExample
=== CONT  TestAccComputeRouter_routerBasicExample
panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 307 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute.resourceComputeRouterCustomDiff({0x0?, 0x0?}, 0x0?, {0x0?, 0x0?})
	/Users/lucaprete/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute/resource_compute_router.go:42 +0x1aa
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute.ResourceComputeRouter.All.func1({0x56e9e20, 0xc00104a780}, 0x4de4eda?, {0x4d9f5c0, 0xc00026f000})
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/customdiff/compose.go:52 +0xd2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000981380, {0x56e9e20, 0xc00104a780}, 0xc0011b8d00, 0xc001ba1770, 0xc000480d40, {0x4d9f5c0, 0xc00026f000}, 0x0)
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/schema.go:698 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x56ea088?, {0x56e9e20?, 0xc00104a780?}, 0xc0011b8d00, 0x47711c0?, {0x4d9f5c0?, 0xc00026f000?})
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:962 +0xd5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc000ff6e70, {0x56e9e20?, 0xc00104a6c0?}, 0xc001ba1630)
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:798 +0x9b6
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc00015f570, {0x56e9e20?, 0xc00104a420?}, 0xc001ba1630)
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0004a8dc0, {0x56e9e20?, 0xc001c7fbf0?}, 0xc000e609a0)
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/tf5server/server.go:811 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x4d45080?, 0xc0004a8dc0}, {0x56e9e20, 0xc001c7fbf0}, 0xc002709c80, 0x0)
	/Users/lucaprete/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:500 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001020600, {0x56e9e20, 0xc001c7fb60}, {0x56f5aa8, 0xc00053de00}, 0xc001aea360, 0xc001068840, 0x754c080, 0x0)
	/Users/lucaprete/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc001020600, {0x56f5aa8, 0xc00053de00}, 0xc001aea360)
	/Users/lucaprete/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/Users/lucaprete/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 245
	/Users/lucaprete/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x135
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute	4.509s
FAIL
make: *** [testacc] Error 1
```

Any idea what I am missing, given it's just a one line modification?

**Review by roaks3 — APPROVED** [review]
(Sorry for the delay on this) LGTM, noting that from the issue, it looks like the short-term fix could potentially change, which would mostly likely require changes to this PR.

**Comment by roaks3** [comment]
Follow-up note: this should be changed to point to the feature branch since it is a breaking change (see https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/)

**Comment by LucaPrete** [comment]
> Follow-up note: this should be changed to point to the feature branch since it is a breaking change (see https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/)

Thanks @roaks3 I just rebased, hopefully on the correct branch. Please, let me know if there's anything else I should do.

**Comment by LucaPrete** [comment]
I was also hoping the rebase would have re-triggered the tests but it doesn't seem the case. Can you please help me re-running them? I remember I wasn't able to trigger them on my own...

**Comment by SarahFrench** [comment]
I can see there's a panic affecting the TGC unit tests, FYI @roaks3

**Comment by roaks3** [comment]
Yea, I had missed it before but it looks like the panic has always been present. I'm seeing it occur from a nil pointer on this line https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10845-old..auto-pr-10845#diff-d2eb6a6a2712aaced589de3439e521d9a17895670b7118da797a5e90681285b6R42.

@LucaPrete it's not immediately obvious to me what is wrong, so you may need to step through the code and see where the nil could be coming from with this change. I would suspect there is an edge case that was simply missed, but it could also be related to the set behaving differently in some way.

**Review by roaks3 — COMMENTED** [review]
Quiet review notification

**Comment by roaks3** [comment]
@LucaPrete @c2thorn I'm noticing this a bit late, but this PR was targeting 6.0.0, which I think is about to be closed (if it isn't already). The last message was mentioning a panic that needs to be fixed, so I know the change isn't ready in its current state, but wanted to raise awareness: if we can't get this in now, the long-term solution proposed here might not be available until 7.0.0 next year.

**Comment by c2thorn** [comment]
> @LucaPrete @c2thorn I'm noticing this a bit late, but this PR was targeting 6.0.0, which I think is about to be closed (if it isn't already). The last message was mentioning a panic that needs to be fixed, so I know the change isn't ready in its current state, but wanted to raise awareness: if we can't get this in now, the long-term solution proposed here might not be available until 7.0.0 next year.

The window is closed unfortunately, we need time to sync the branches and test

**Comment by LucaPrete** [comment]
Hello folks,

It seems the panic comes from something deeper into the code. It’s
something I haven’t
time to look into….on the other hand, I want to underline how this change
is crucial for many of our customers. Happy to contribute and make thing
happen in no time, but I’ll definitely need help from somebody from the
core dev team as well.

Please, let me know how you’d like to proceed.

Thanks!

Il giorno mar 20 ago 2024 alle 18:42 Cameron Thornton <
***@***.***> ha scritto:

**Comment by c2thorn** [comment]
> Hello folks, It seems the panic comes from something deeper into the code. It’s something I haven’t time to look into….on the other hand, I want to underline how this change is crucial for many of our customers. Happy to contribute and make thing happen in no time, but I’ll definitely need help from somebody from the core dev team as well. Please, let me know how you’d like to proceed. Thanks!

There is simply no time left, the contribution window for 6.0 closed Friday, and the 6.0 branch is effectively frozen so the major release as a whole can be completed in time and tested thoroughly. I've already declined other changes that missed the window that were in a more ready state than this is.

If there is significant enough prioritization, we can discuss internally _after_ 6.0 is released.

**Pull request closed without merging**
