### PR TITLE
Update privateca_certificate related tests and examples to not use shared CaPool

### PR DESCRIPTION
**Pull request by gfxcc**
Fix https://github.com/hashicorp/terraform-provider-google/issues/13715

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note: none

```

### CODE REVIEW

**Comment by gfxcc** [comment]
As shown in the above 2 comments, there are used to be several tests failed first and later passed in the so called `RECORDING mode`. Could you help me understand what is that? @c2thorn ?

**Comment by c2thorn** [comment]
@gfxcc VCR tests are our way to quickly iterate through tests via caching. `REPLAYING` mode is using cached responses, and `RECORDING` uses actual API calls. Tests that have been directly changed are set to "fail" in `REPLAYING` so that they can be re-recorded with real API calls. That's what happened here.

Secondly, would you mind doing a `git rebase` on the latest commit in `main` ? We very recently downgraded ruby to 3.1 on `main` which is then causing our `run-rake-tests` step to fail because this branch is using 3.2. Just to make sure, I'd like to see the step pass before approving/merging. Sorry for the inconvenience.

**Comment by gfxcc** [comment]
@c2thorn thanks for the detailed explanation. Rebased as requested.

**Review by c2thorn — COMMENTED** [review]
code changes seem good. Just want to confirm if we will hit some sort of quota limit if we start making `google_privateca_ca_pool`'s per test. I'm not familiar with why the bootstrap shared one was needed in the first place. Do you know of any issues we could face by switching over? @gfxcc

**Comment by gfxcc** [comment]
Very good point and that would be fine. CAS's prober test was implemented in the same way.

I believe shared pool was used as CaPool was not able to be deleted in time until late last year. Now, that limitation is removed hence we can use dedicated pool now.

**Review by c2thorn — APPROVED** [review]
That makes sense, thank you.

**Pull request merged**
