### PR TITLE
Sync 5.0.0 with main

### PR DESCRIPTION
**Pull request by shuyama1**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by c2thorn — APPROVED** [review]
pending vcr

**Comment by SarahFrench** [comment]
Do all of these test failures need to be fixed before the sync is merged? Or just some (eg not the tpu ones maybe)?

I've got a 5.0.0 contribution that reverses a big fix that's in this PR (weird, I know!) so I can't start on that PR before this one is merged.

**Comment by shuyama1** [comment]
I believe the failure `TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange` and  `TestAccVertexAIIndexEndpoint_updated` will be fixed after https://github.com/GoogleCloudPlatform/magic-modules/pull/8904 is merged, so they should not be blocker for this PR. Adding @zli82016 to confirm.

tpu tests seem like just flaky and also should be blocker for this PR.

**Comment by shuyama1** [comment]
Thanks @zli82016 for confirming. Will merge the PR now.

**Comment by shuyama1** [comment]
Looks like the tpu tests are new tests added in the main and never got modified in 5.0.0. I'll copy the cassettes over then.

**Pull request merged**
