### PR TITLE
Fixed KeyError due to deletionProtection

### PR DESCRIPTION
**Pull request by sbulage**
Signed-off-by: Satyajit Bulage <sbulage@redhat.com>
Fixed issue https://github.com/ansible/ansible/issues/65291 filed in the Ansible repo.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by sbulage** [comment]
@googlebot I signed it!

**Comment by verasativa** [comment]
¿Why is taking too long to accept so small PR?

**Comment by rambleraptor** [comment]
This currently doesn't have a CLA signed.

**Comment by Akasurde** [comment]
cc @sbulage Can you please take a look? Thanks.

**Comment by sbulage** [comment]
I got a mail to sign CLA, I did that. Not sure I have do it again .?
If anyone can guide me here is really helpful.

**Comment by danawillow** [comment]
@rambleraptor fyi if you click the "googlers" link it brings you to a page where you can force a rescan in case the googlebot messes up.

**Comment by evanscottgray** [comment]
Is anyone able to get this merged in?

**Comment by rambleraptor** [comment]
So sorry for this taking so long. I’ll merge this in before Monday. Can you
rebase this?

**Comment by evanscottgray** [comment]
Thanks, @rambleraptor!

**Pull request merged**
