### PR TITLE
Remove edgecontainer vpnconnection import rule

### PR DESCRIPTION
**Pull request by rayccz2**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
edgecontainer: fixed resource import on `google_edgecontainer_vpn_connection`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Self link should already be included in the downstream. It's by default included.

Notice, no diffs generated
https://github.com/GoogleCloudPlatform/magic-modules/pull/9764#issuecomment-1879250902

Any reason you want to include this more explicitly?

**Comment by rayccz2** [comment]
> Self link should already be included in the downstream. It's by default included.
> 
> Notice, no diffs generated [#9764 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/9764#issuecomment-1879250902)
> 
> Any reason you want to include this more explicitly?

We got a bug b/314144187 complaining the terraform import is incorrect.
And from https://github.com/hashicorp/terraform-provider-google/issues/16598 the error message state `error fetching live state: error importing resource: Import id \"projects/mock-project/locations/us-central1/vpnConnections/edgecontainervpnconnection-j4idl7vcq3lgwjrbhwmq\" doesn't match any of the accepted formats: [^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/vpnConnections$ ^(?P<project>[^/]+)/(?P<location>[^/]+)$ ^(?P<location>[^/]+)$]"`
Which looks like get request failed due to the format error?

Do you have any insight how to resolve this?

**Comment by ScottSuarez** [comment]
This line needs to be deleted
https://github.com/GoogleCloudPlatform/magic-modules/blob/a5036e705278daac790cab6f7127038cf924155a/mmv1/products/edgecontainer/VpnConnection.yaml#L43

**Comment by rayccz2** [comment]
> This line needs to be deleted
> 
> https://github.com/GoogleCloudPlatform/magic-modules/blob/a5036e705278daac790cab6f7127038cf924155a/mmv1/products/edgecontainer/VpnConnection.yaml#L43

Done.

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
