### PR TITLE
Add documentation link to the official documentation for using GCFS (a.k.a. image streaming).

### PR DESCRIPTION
**Pull request by paulbsch**
Add documentation link to the official documentation for using GCFS (a.k.a. image streaming).

If this PR is for Terraform, I acknowledge that I have:

- [ X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
Thanks for contributing!

Right now the new line says to see the official documentation for more information about image streaming - but nothing else in the description references image streaming at all. There would ideally be a brief description here about how to configure it with terraform, followed by the link to the official docs.

Generally we try to mirror the REST API docs as closely as possible; do they have a description of how to configure image streaming that we could use?

Regardless of how this may change, the "Structure is documented below" line needs to come last to match our general docs style.

**Comment by paulbsch** [comment]
Hi @melinath..  I can see how the wording might have been a little confusing.  I just pushed a slight change.  Does that help?

GCFS enablement on node pools, with terraform, is basically documented in the same blurb where I added the line/link.  The link subsequently describes how to configure image streaming for use with GKE.

**Review by melinath — APPROVED** [review]
Yes, that looks a lot better. Thanks!

**Comment by melinath** [comment]
Merging without VCR because this is a docs-only change.

**Pull request merged**
