### PR TITLE
fix: remove retry in read as retry for create/update is already handled in respective methods

### PR DESCRIPTION
**Pull request by gurusai-voleti**
remove retry in read as retry for create/update is already handled in respective methods

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/13464

**Release Note Template for Downstream PRs (will be copied)**

```release-note: bug
storage: removed retry on 404s during refresh for `google_storage_bucket`, preventing hanging when refreshing deleted buckets
```

### CODE REVIEW

**Comment by rileykarson** [comment]
What bug(s) is this addressing / what's the context?

**Comment by gurusai-voleti** [comment]
> What bug(s) is this addressing / what's the context?

http://b/275607155

**Review by rileykarson — APPROVED** [review]
LGTM, I think this makes sense. We added this to several spots in https://github.com/GoogleCloudPlatform/magic-modules/pull/5288 and I'm not confident we needed this one + that PR has no extra context on why we would need it here specifically.

Waiting on approval from @kautikdk to merge

**Review by kautikdk — APPROVED** [review]
Considering public documentation of cloud storage consistency:https://cloud.google.com/storage/docs/consistency#strongly_consistent_operations, Bucket Listing is strongly consistent operation so we don't need retry logic for bucket read operation.

**Pull request merged**
