### PR TITLE
Deleted immutable attributes for initialUser and weeklySchedule so th…

### PR DESCRIPTION
**Pull request by GauravJain21**
…at deleting/adding these properties doesn't force new cluster creation

Creating a cluster with the minimum fields works fine the first time. On re-running the same .tf file, it deletes the existing cluster and creates a new one.

We get the [default values](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/alloydb/Cluster.yaml#L129) for automated backup policy from the API. This includes many fields. One of them is the weekly schedule. This field is marked as [forceNew](https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_alloydb_cluster.go#L73). The first time when we create the cluster without providing any automated backup policy, we get the default from the API. This default value gets persisted in the .tfstate file. On subsequent runs of terraform, Terraform sees that the automated backup policy is present in the state file but not in the .tf file. Since this field is marked as forceNew, the old cluster is deleted and a new one is created. This is highly undesirable.

Similarly, initialUser is marked as immutable while it is a mutable field. Addition/Deletion to this field causes existing cluster deletion and creation of a new one which is highly undesirable.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
     AlloyDB: Deleted immutable flag for initalUser and weeklySchedule 

```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
This looks fairly straightforward and it looks like the downstream code for in-place updates is getting generated. However, it would be good to add additional update tests to make sure that all the fields we think are updatable can actually be updated. There is already an [update test for alloydb](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_alloydb_cluster_test.go), which can be extended to exercise a larger number of fields, for example to ensure that this issue is actually resolved and prevent it from recurring. See https://github.com/GoogleCloudPlatform/magic-modules/blob/bf3305d13d3e14c5374d7c447a811daee94c2f1d/mmv1/third_party/terraform/tests/resource_redis_instance_test.go#L77 for a more mature example of an update test.

**Comment by GauravJain21** [comment]
Hey Stephen,
As the bug is pretty bad (causes DB to be torn down for minor config changes), we're requesting exception to go ahead with the fix. Kindly request your help to make this exception.

Once the current code is stabilised and doesn't have any glaring bugs (max 1-2 weeks), we will switch focus to writing sufficient automated tests to ensure these issues are caught early in development.

**Review by melinath — APPROVED** [review]
LGTM - thanks for adding tests!

**Comment by melinath** [comment]
Failing test seems unrelated.

**Comment by rileykarson** [comment]
@melinath: Please make sure you review the changelog note in the future! I've adjusted this to:

```
IMPROVEMENTS:
* alloydb: added update support for `initial_user` and `automated_backup_policy.weekly_schedule` to `google_alloydb_cluster`
```

**Pull request merged**
