### PR TITLE
Remove qualifier about # of supported projects in billing budget

### PR DESCRIPTION
**Pull request by rileykarson**
For b/178476660

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — APPROVED** [review]
SGTM - though it looks like our docs are the same as the REST API docs; do we have confirmation that the REST API docs are incorrect? https://cloud.google.com/billing/docs/reference/budget/rest/v1/billingAccounts.budgets#filter

**Comment by rileykarson** [comment]
Yeah, see the bug linked in the description.

**Comment by melinath** [comment]
yeah, I read the linked bug and saw that someone was asked to confirm the actual behavior, but it looks like they haven't responded with confirmation yet.

**Comment by juliocc** [comment]
FWIW I just did a test with 4 projects and it worked fine.

**Pull request merged**
