### PR TITLE
Fix the building error in terraform-google-conversion

### PR DESCRIPTION
**Pull request by zli82016**
Add the files to the conversion list to fix the building error in terraform-google-conversion.
third_party/terraform/tpgresource/service_scope.go
third_party/terraform/utils/error_retry_predicates.go

```
tfplan2cai/converters/google/resources/sqladmin_operation.go:140:6: IsSqlInternalError redeclared in this block
	tfplan2cai/converters/google/resources/error_retry_predicates.go:217:6: other declaration of IsSqlInternalError
tfplan2cai/converters/google/resources/cloudscheduler_job.go:62:26: undefined: tpgresource.CanonicalizeServiceScope
tfplan2cai/converters/google/resources/compute_instance_helpers.go:307:40: undefined: tpgresource.StringScopeHashcode
tfplan2cai/converters/google/resources/compute_instance_helpers.go:320:24: undefined: tpgresource.CanonicalizeServiceScopes
tfplan2cai/converters/google/resources/container.go:90:27: undefined: tpgresource.CanonicalizeServiceScope
tfplan2cai/converters/google/resources/service_scope.go:8:21: undefined: tpgresource.CanonicalizeServiceScope
tfplan2cai/converters/google/resources/service_scope.go:12:21: undefined: tpgresource.CanonicalizeServiceScopes
tfplan2cai/converters/google/resources/service_scope.go:16:21: undefined: tpgresource.StringScopeHashcode
```

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by zli82016** [comment]
@melinath, files retry_transport.go is removed from https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/utils, but still exists in https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/main/tfplan2cai/converters/google/resources. Do you know how to remove it from terraform-google-conversion? Thanks.

There are errors in the [build](https://pantheon.corp.google.com/cloud-build/builds/d880e90d-f7ee-4648-a625-afdf14cd8250;step=12?project=graphite-docker-images) for the terraform-google-conversion

# github.com/GoogleCloudPlatform/terraform-google-conversion/v2/tfplan2cai/converters/google/resources
tfplan2cai/converters/google/resources/retry_transport.go:52:20: undefined: defaultErrorRetryPredicates
tfplan2cai/converters/google/resources/retry_transport.go:59:73: undefined: RetryErrorPredicateFunc
tfplan2cai/converters/google/resources/retry_transport.go:68:60: undefined: RetryErrorPredicateFunc
tfplan2cai/converters/google/resources/retry_transport.go:75:20: undefined: RetryErrorPredicateFunc

**Comment by melinath** [comment]
@zli82016 you'll need to make a PR to https://github.com/GoogleCloudPlatform/terraform-google-conversion to remove it. We don't currently clear out that directory on every build (though we probably should) so it needs to happen manually. Review for the PR should be assigned to terraform-validator-reviewers.

**Comment by zli82016** [comment]
> @zli82016 you'll need to make a PR to https://github.com/GoogleCloudPlatform/terraform-google-conversion to remove it. We don't currently clear out that directory on every build (though we probably should) so it needs to happen manually. Review for the PR should be assigned to terraform-validator-reviewers.

Thanks. I created PR to remove the file. We can merge this PR first when it is ready, I think.

**Comment by zli82016** [comment]
We can merge the current PR (7890) first and then merge that PR ([944](https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/944)).

**Review by melinath — APPROVED** [review]

**Comment by melinath** [comment]
LGTM - merge order shouldn't matter as long as they're in close proximity to each other.

**Pull request merged**
