### PR TITLE
Add cmek to spanner database

### PR DESCRIPTION
**Pull request by slevenick**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8822

Also bumps the default request timeout to 2 minutes from 30 seconds. This should fix intermittent request cancelled errors which were showing up fairly frequently on this test

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
spanner: added support for setting a CMEK on `google_spanner_database`
```
```release-note:note
all: changed default HTTP request timeout from 30 seconds to 120 seconds
```

### CODE REVIEW

**Comment by melinath** [comment]
It looks like this is a skip-VCR test; I started a non-VCR test run for the new test here: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/183035

**Review by melinath — APPROVED** [review]
LGTM assuming the test passes

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like this requires google_project_service_identity (beta only)

**Comment by slevenick** [comment]
> It looks like the test currently requires google_project_service_identity (beta only) but the field is currently marked as GA.

Ah yeah, that's correct. I just marked the test as beta to avoid this issue in tests. Spanner only has a v1 API so it wouldn't be correct to mark it as beta. I think the right action here is to mark the test as beta but keep the field as GA

**Comment by melinath** [comment]
non-VCR test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/183261

**Review by melinath — APPROVED** [review]
LGTM assuming test passes

**Pull request merged**
