### PR TITLE
Updated optional component List to possible values

### PR DESCRIPTION
**Pull request by sehgalnamit**
If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
-[X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
-[X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by sehgalnamit** [comment]
@c2thorn 
Many Thanks for getting this request reviewed.
May I know what this check failure is and any actions I need to do ?

TerraformVCRCommunity

**Comment by sehgalnamit** [comment]
@c2thorn  Can you please advise on this?
I am not sure where do I need to commit to make this change work?

Thanks

**Comment by c2thorn** [comment]
@sehgalnamit 
Ah I think I see what's going on here. regarding https://github.com/GoogleCloudPlatform/magic-modules/pull/5129#pullrequestreview-737755508, they were stating that you'll want to make changes in all 3 of those files in the same pull request. You've done 1/3 here by changing the test file

**Comment by sehgalnamit** [comment]
@c2thorn 
Many Thanks for your reply, it is great that you guys reply on community so fast.
If you see all those 3 files, we already have the FLINK component added and the only file which was missing, I added it there.

My goal is to get FLINK component added in the provider:-
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster

optional_components -

**Comment by c2thorn** [comment]
@sehgalnamit I see, that makes sense. I still do not see `FLINK` added as an option to the documentation: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/website/docs/r/dataproc_cluster.html.markdown?plain=1#L487

We could add that in this PR?

**Comment by sehgalnamit** [comment]
@c2thorn 
Yes, please

**Comment by c2thorn** [comment]
Hi @sehgalnamit 
Running the tests and then looking at it manually, there are a few further issues.

`ANACONDA`, `KERBEROS`, and `RANGER` optional components all seem to have additional requirements needed to be valid values, and cause the API to return a 400 error.

Even after removing these, the test check to verify optional components list does not do an un-ordered comparison: https://github.com/GoogleCloudPlatform/magic-modules/blob/174ad27c1078a488af668fa3ee178c7fb63a4225/mmv1/third_party/terraform/tests/resource_dataproc_cluster_test.go.erb#L904

If the list is given in any order not specified in https://github.com/GoogleCloudPlatform/magic-modules/blob/174ad27c1078a488af668fa3ee178c7fb63a4225/mmv1/third_party/terraform/tests/resource_dataproc_cluster_test.go.erb#L575, it will fail the test.

Given these issues, I don't think it is worth actually testing every possible value for optional components. It isn't something we do for other fields, and given the number of possible values it should be fine to just test `DOCKER` and `ZOOKEEPER` (the original values in the test). What do you think? If you agree, we can just keep the HTML change, revert the test changes, and merge the PR.

**Comment by sehgalnamit** [comment]
@c2thorn 
Really appreciate your help on this case.
I am fine to have HTML changes but is it possible for you to test atleast FLINK as component as when I use the provider in my environment, it does not work. 

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_cluster

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.82.0"
    }
  }
}

provider "google" {
  # Configuration options
}

It could be Google API issue with Flink which I can go to Google Product team and ask. If you get similar issue for FLINK as an optional component not working while spinning of dataproc using this provider, I do not think it is worth to update HTML.
There is a feature request I have raised with heshicorp but I think they also depend on open source community. 

My original issue
https://github.com/hashicorp/terraform-provider-google/issues/9766

**Comment by c2thorn** [comment]
Hi @sehgalnamit, this makes sense I agree with at least adding `FLINK` to one of the tested values.

Trying it out myself very quickly, I see success. If you are having problems, can you post your config and Debug log?

**Comment by sehgalnamit** [comment]
@c2thorn 
Thanks for your reply.
I managed to add FLINK as addental component 
dataproc_clusters = {
  "welltuned" : {
    software_config_optional_components = ["ZOOKEEPER", "JUPYTER", "FLINK"]
  }
}

-------------------------------------------------------
So you can just update HTML for the PR.
-------------------------------------------------------
I found further issues with though:-
1. If you get time, please have a look at this 
https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/flink

NOTE: The Flink initialization action has been deprecated. Please use the Flink Component
Even though we have an option to add FLINK as additional component, we do not have a way to start the FLINK session, something we have in gcloud command

flink-start-yarn-session=true
https://cloud.google.com/dataproc/docs/concepts/components/flink


2. If we rerun the code, 
IP of the nodes and master will not preserved

Meaning I get new IPs even though in my plan, I see no change in the resource.

**Comment by c2thorn** [comment]
> So you can just update HTML for the PR.

Do you mind reverting the change to the test file in this PR, then I'll merge

> Even though we have an option to add FLINK as additional component, we do not have a way to start the FLINK session, something we have in gcloud command
> 
> flink-start-yarn-session=true
> [cloud.google.com/dataproc/docs/concepts/components/flink](https://cloud.google.com/dataproc/docs/concepts/components/flink)

We are limited by the API in what we can do, and there is not always parity with gcloud. I cannot find anything here: https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters

> Meaning I get new IPs even though in my plan, I see no change in the resource.
Is this a current bug in the resource? It may be appropriate to open a new issue with the steps involved so we can solve it. I believe this is falling out of the scope of this PR.

**Comment by sehgalnamit** [comment]
@c2thorn 
I have raised an issue for the IPs issue
https://github.com/hashicorp/terraform-provider-google/issues/10074

Also, I have raised a Case with Google for REST API issue

Updated my current PR.

**Comment by sehgalnamit** [comment]
@c2thorn 

You can merge the HTML.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
