### PR TITLE
Format YAML

### PR DESCRIPTION
**Pull request by trodge**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
Even ignoring whitespace, this is too long for me to review manually; could you either split this up into product buckets (a-d, e-h, etc., or similar) or let me know what command I can run to replicate this locally?

**Comment by melinath** [comment]
splitting up into product buckets will also reduce the chance of a merge conflict.

**Comment by trodge** [comment]
> Even ignoring whitespace, this is too long for me to review manually; could you either split this up into product buckets (a-d, e-h, etc., or similar) or let me know what command I can run to replicate this locally?

This was accomplished using the [yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) and [format files](https://marketplace.visualstudio.com/items?itemName=jbockle.jbockle-format-files) vscode extensions.
The formatter adds a newline after `---`, so I used a search replace to put the yaml tags back on the same line with the document seperator.

**Comment by melinath** [comment]
is there a way to replicate this formatting with a command-line tool? we will want to enforce this automatically on PRs so we need something we can do in CI easily.

> The formatter adds a newline after ---, so I used a search replace to put the yaml tags back on the same line with the document seperator.

Just to clarify, do the yaml tags need to be on the same line as the document separator, or was this to reduce noise in the PR?

**Comment by trodge** [comment]
> is there a way to replicate this formatting with a command-line tool? we will want to enforce this automatically on PRs so we need something we can do in CI easily.
> 
> > The formatter adds a newline after ---, so I used a search replace to put the yaml tags back on the same line with the document seperator.
> 
> Just to clarify, do the yaml tags need to be on the same line as the document separator, or was this to reduce noise in the PR?

I'm planning on adding yamllint to the CI, which will report formatting errors but can't fix them automatically.

I'm not sure if the yaml tags need to be on the same line as the document separator, but I've kept them that way to reduce noise.

**Review by ankit-gautam23 — COMMENTED** [review]
I strongly recommend to split the PR

**Review by melinath — CHANGES_REQUESTED** [review]
After thinking this over some more, I won't be able to review a PR like this fast enough to avoid merge conflicts in some part of it, since it modifies the entire product set. Please split it up into buckets as described above and we can aim for merging ~1 bucket per day.

**Comment by trodge** [comment]
> After thinking this over some more, I won't be able to review a PR like this fast enough to avoid merge conflicts in some part of it, since it modifies the entire product set. Please split it up into buckets as described above and we can aim for merging ~1 bucket per day.

I have split this into the following PRs:
https://github.com/GoogleCloudPlatform/magic-modules/pull/7785
https://github.com/GoogleCloudPlatform/magic-modules/pull/7786
https://github.com/GoogleCloudPlatform/magic-modules/pull/7787
https://github.com/GoogleCloudPlatform/magic-modules/pull/7788
https://github.com/GoogleCloudPlatform/magic-modules/pull/7789

**Pull request closed without merging**
