### PR TITLE
Ignore fingerprint during import in TestAccComputeInstanceSettings_update, as it often changes

### PR DESCRIPTION
**Pull request by SarahFrench**
Addresses a [flaky test with ~50% failure rate](https://hashicorp.teamcity.com/test/4946789655298649883?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS&expandTestHistoryChartSection=true)

```
------- Stdout: -------
=== RUN   TestAccComputeInstanceSettings_update
=== PAUSE TestAccComputeInstanceSettings_update
=== CONT  TestAccComputeInstanceSettings_update
    vcr_utils.go:152: Step 2/6 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
          map[string]string{
        -   "fingerprint":          "wQH2_MqU01c=",
        +   "fingerprint":          "TyiC4TGN8NA=",
        -   "metadata.#":           "1",
        -   "metadata.0.%":         "1",
        -   "metadata.0.items.%":   "1",
        -   "metadata.0.items.foo": "baz",
          }
--- FAIL: TestAccComputeInstanceSettings_update (71.24s)
FAIL
```

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
doesn't seem correct - /gcbrun

**Comment by SarahFrench** [comment]
Running this in TeamCity: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_COMPUTE/208785?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true

**Comment by SarahFrench** [comment]
Passed in TeamCity too, opening for review

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks for fixing it.

**Pull request merged**
