### PR TITLE
Promote resource policy to GA

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7872

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: promoted `google_compute_resource_policy` to GA
```

### CODE REVIEW

**Comment by upodroid** [comment]
What is this error?

```
 REDACTED  MCW0CDP3YY  ~  go  …  github.com  hashicorp  terraform-provider-google   master  11⬇  40✎  1  $    make testacc TEST=./google TESTARGS="-run TestAccDataSourceComputeResourcePolicy"
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run TestAccDataSourceComputeResourcePolicy -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceComputeResourcePolicy
=== PAUSE TestAccDataSourceComputeResourcePolicy
=== CONT  TestAccDataSourceComputeResourcePolicy
    TestAccDataSourceComputeResourcePolicy: testing_new_config.go:95: no "id" found in attributes
    TestAccDataSourceComputeResourcePolicy: testing_new.go:48: no "id" found in attributes
--- FAIL: TestAccDataSourceComputeResourcePolicy (41.39s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-google/google   43.722s
FAIL
make: *** [testacc] Error 1
```

Also bundler fails to compile when I change the changed file extensions from .go.erb to .go

**Comment by c2thorn** [comment]
@upodroid there's a known issue with Terraform 0.13+ and data source tests that is probably affecting that test. Our CI is currently running at 0.12.29, and I successfully ran the test with that

**Comment by c2thorn** [comment]
> Also bundle fails to compile when I change the file extensions from .go.erb to .go

Is it because of the `autogen_exception` line? otherwise i'm not too sure. I don't think converting is particularly necessary though. Did you still want to make any more changes?

**Comment by upodroid** [comment]
It works now so merge it. I had issues when I renamed the extension to .go and stripped all the Ruby elements from the file.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
