### PR TITLE
Sync main feature branch 6.0.0 - 7/16

### PR DESCRIPTION
**Pull request by c2thorn**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by c2thorn** [comment]
these tests are already failing on main @shuyama1

**Comment by shuyama1** [comment]
Do we know what breaking change https://github.com/GoogleCloudPlatform/magic-modules/pull/11179#issuecomment-2233847992 is pointing to? We shouldn't be expecting any breaking changes, since these are changes merged into the main. However, it may be due to DCL migrations where changing in project is an known false(?) alert.

**Comment by c2thorn** [comment]
> Do we know what breaking change [#11179 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/11179#issuecomment-2233847992) is pointing to? We shouldn't be expecting any breaking changes, since these are changes merged into the main. However, it may be due to DCL migrations where changing in project is an known false(?) alert.

Yes it is from the DCL change: https://github.com/GoogleCloudPlatform/magic-modules/pull/11052

**Comment by shuyama1** [comment]
> > Do we know what breaking change [#11179 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/11179#issuecomment-2233847992) is pointing to? We shouldn't be expecting any breaking changes, since these are changes merged into the main. However, it may be due to DCL migrations where changing in project is an known false(?) alert.
> 
> Yes it is from the DCL change: #11052

Cool, thanks for confirming!

**Review by shuyama1 — APPROVED** [review]
Thanks for creating the weekly sync PR and resolve merge conflicts!

Don't forget to commit merge :)

**Pull request merged**
