### PR TITLE
Check identity field in FetchBucketIamPolicy before fetching

### PR DESCRIPTION
**Pull request by c2thorn**
Part of https://github.com/GoogleCloudPlatform/terraform-validator/issues/216

Small check that is template friendly for https://github.com/GoogleCloudPlatform/terraform-validator/issues/217

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by c2thorn** [comment]
@melinath I can build and see the change for terraform-google-conversion, but how do I test this modified version with my local copy of Validator? I couldn't figure out how to redirect the go import away from the downloaded copy.

**Comment by melinath** [comment]
@c2thorn you can specify a local version of a module by adding a "replace" statement to the terraform-validator go.mod & rebuilding - here's an example: https://stackoverflow.com/questions/57610669/go-modules-replace-with-a-specific-version-of-a-local-module

**Comment by c2thorn** [comment]
@melinath Thanks I'll send a review request when it is ready then

**Comment by c2thorn** [comment]
Was able to test this, thanks @melinath. Code ended up split between this and https://github.com/GoogleCloudPlatform/terraform-validator/pull/218

**Review by melinath — CHANGES_REQUESTED** [review]
Thinking about this some more, I'm wondering whether there might be a different approach. I think that if the bucket ID isn't known until after apply, that means the bucket is being created, which means that there shouldn't be any policy attached to it yet that we would need to fetch for verification purposes - i.e. I think that we might be able to safely skip fetching but still run validation, like Morgante was talking about.

For example, we could return `nil, nil` from here and then use that to detect not setting existingConverterAsset.

Does that seem like it could be a reasonable approach?

**Comment by c2thorn** [comment]
> Thinking about this some more, I'm wondering whether there might be a different approach. I think that if the bucket ID isn't known until after apply, that means the bucket is being created, which means that there shouldn't be any policy attached to it yet that we would need to fetch for verification purposes - i.e. I think that we might be able to safely skip fetching but still run validation, like Morgante was talking about.
> 
> For example, we could return `nil, nil` from here and then use that to detect not setting existingConverterAsset.
> 
> Does that seem like it could be a reasonable approach?

I believe that's in line with what I was implementing. If you take a look at the Validator part of what I intend to do: https://github.com/GoogleCloudPlatform/terraform-validator/pull/218/files

We'll recognize the type of error and just continue with the rest of the validation instead of erroring out.

**Comment by melinath** [comment]
> I believe that's in line with what I was implementing. If you take a look at the Validator part of what I intend to do: https://github.com/GoogleCloudPlatform/terraform-validator/pull/218/files
> 
> We'll recognize the type of error and just continue with the rest of the validation instead of erroring out.

My reading of that PR is that it will continue the loop, which means that it would skip the rest of the loop and never set `c.assets[key] = augmented`, which means that the resource won't get validated at all. If we instead skip the fetch but still run the rest of the code in the loop, I think we could validate the newly created resource in many cases without much risk of over-validating.

For example, if there's a rule that only emails with X domain are in iam policies (GCPIAMAllowedPolicyMemberDomainsConstraintV2), we would still be able to validate that even for buckets that are just being created. On the other hand, a rule like GCPIAMRequiredBindingsConstraintV1 that expects a particular binding to exist would probably detect incorrect violations since the members/bindings wouldn't get grouped correctly - but that might be preferable in the short term, and we could look into ways to potentially fix the grouping in the longer term even without a real id.

Does that make sense / clarify what I mean? What do you think?

> > For example, we could return `nil, nil` from here and then use that to detect not setting existingConverterAsset.
> 
> Tried returning `nil,<whatever>` and got an error for sending `nil` for type `Asset`

🤦 right, go doesn't do optional values except for pointers. Sorry.

I think you're definitely right to do this by using a specific error, in that case. It looks like the best practice might be to use a [custom error type](https://stackoverflow.com/questions/26881252/returning-an-optional-value-and-an-error) rather than relying on the string value. Does that seem reasonable?

**Review by melinath — APPROVED** [review]
lgtm

**Pull request merged**
