### PR TITLE
Update bigquery dataset documentation

### PR DESCRIPTION
**Pull request by ScottSuarez**
Updating the id description to be inline with the [official rest api documentation ](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets)

Initially noticed in this [PR](https://github.com/hashicorp/terraform-provider-google/pull/7582)

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by danawillow** [comment]
`id` is a special field in Terraform. In our provider we use it as a way to make it easy for users to reference one resource from another (so that they can use id everywhere instead of having to remember what field to reference), so we want to be in control of the format. https://github.com/hashicorp/terraform-provider-google/wiki/Developer-Best-Practices#self-links-names-and-ids has some more info overall. The format that's there now is actually the one that's documented currently: https://github.com/hashicorp/terraform-provider-google/blob/6034ccf8e0b0f096b33c3ea669e47aa6e8427e86/google/resource_big_query_dataset.go#L385-L390

**Comment by ScottSuarez** [comment]
Closing after syncing with @danawillow

**Comment by burnzy** [comment]
Hi @danawillow — some of my dataset resources are still using the old id format of `{{project_id}}:{{dataset_id}}`, these resources are using the newer provider (but were created using an earlier version) — is there anyway to bring these  resource id's up to date with the new format. Wondering if you could point me in the right direction, or link me to some documentation that could help. Your help is appreciated, thanks!

**Comment by danawillow** [comment]
Oh that's an interesting case that I hadn't considered! There isn't a great answer, but here are some options:
1. Modify the state file directly
2. Remove the resource from state and re-import it
3. File an issue against the provider. There's something we can do on our end called a state upgrader that will allow us to do this programmatically for all users.

Option 3 gets a bit tricky because changing values for all users means that we could break some that were relying on the old format, but if you think this is potentially a widespread problem we could look into it. I'd recommend doing 1 or 2 though- our feature request backlog is pretty long right now so it would probably be a while before we got to it.

**Comment by burnzy** [comment]
Thanks for the info and for your quick reply! I'll take a look at option 1 or 2 for now. Thanks again 👍

**Pull request closed without merging**
