### PR TITLE
add port validation

### PR DESCRIPTION
**Pull request by edwardmedia**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/16209

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed an error during the deletion when post was set to 0 on `google_compute_global_network_endpoint`
```

### CODE REVIEW

**Comment by edwardmedia** [comment]
two pieces included

- Fixed the issue mentioned in https://github.com/hashicorp/terraform-provider-google/issues/16209
- Add validation on port as 0 is disallowed by the api.

**Comment by zymotik** [comment]
Hi @edwardmedia, @rileykarson, thank you for your work on this solution. I see the VCR-test step has failed, but I do not have permission to troubleshoot. Can you help?

Thanks in advance for all your hard work.

**Comment by rileykarson** [comment]
Those aren't a problem, they were failing for unrelated reasons.

I'm a little behind on reviews, rerolled @trodge

**Review by trodge — APPROVED** [review]

**Pull request merged**
