### PR TITLE
Fix post-6.0.0 TGC issues

### PR DESCRIPTION
**Pull request by shuyama1**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
@melinath @c2thorn Sorry, this PR is still WIP.  I'm only adding reviewers to prevent it from assigning reviewers from service teams. I'll mark it as ready for review once all TGC tests have passed.

**Comment by shuyama1** [comment]
@melinath It seems that once a service label is added, it remains even if the changes in that service package are reverted. I'm not sure if this is the intended behavior.

**Review by c2thorn — APPROVED** [review]
thank you!

**Comment by melinath** [comment]
> @melinath It seems that once a service label is added, it remains even if the changes in that service package are reverted. I'm not sure if this is the intended behavior, just want to flag.

yes, this is the intended behavior. More specifically, if any service label is present, the CI pipeline will not modify the service labels. This allows us to do things like manual overrides if necessary.

**Pull request merged**
