### PR TITLE
Delete google_project_services in 3.0.0.

### PR DESCRIPTION
**Pull request by ndmckinley**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
Removed `google_project_services`.
```

### CODE REVIEW

**Comment by ndmckinley** [comment]
Definitely.

**Comment by rileykarson** [comment]
Also the sidebar entry on this branch, I believe.

**Comment by ndmckinley** [comment]
That's https://github.com/GoogleCloudPlatform/magic-modules/pull/2411.

**Comment by ndmckinley** [comment]
Great, those diffs look good to me.

**Pull request merged**
