### PR TITLE
making sure swp can be created without scope and certificateUrls

### PR DESCRIPTION
**Pull request by felipegc**
Fixes:
https://github.com/hashicorp/terraform-provider-google/issues/15223

Making sure SWP can be provisioned without scope and certificateUrl fields

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
network_services: removing required flags from `scope` field in `google_network_services_gateway` resource
```

### CODE REVIEW

**Review by NickElliot — COMMENTED** [review]
From reviewing when the update was made to the API (cl/509281977), it seems scope should also have its "immutable" status removed. There is API end validation to prevent users from updating OPEN_MESH gateways, and it is expected users can update Scope for SECURE_WEB_GATEWAYs.

**Review by NickElliot — COMMENTED** [review]
Sorry to ask for another change, but with the immutable status being removed could you uncomment the update test for SECURE_WEB_GATEWAYs that actually already exists [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/b4afc1d0a6780836559dde59997e4616f2e1cb81/mmv1/third_party/terraform/tests/resource_network_services_gateway_test.go#L68), and add a "newGatewayScope" variable to use in the second case. Thanks!

**Comment by felipegc** [comment]
> Sorry to ask for another change, but with the immutable status being removed could you uncomment the update test for SECURE_WEB_GATEWAYs that actually already exists [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/b4afc1d0a6780836559dde59997e4616f2e1cb81/mmv1/third_party/terraform/tests/resource_network_services_gateway_test.go#L68), and add a "newGatewayScope" variable to use in the second case. Thanks!

I have double checked if scope field is updatable and the api returns an error so I put the immutable flag back to it.
I have created the task you mentioned because there is a plan where "certificateUrls" and "policy" will be updatable in the future. This commented test is addressed for testing that.

**Review by NickElliot — APPROVED** [review]
LGTM then!

**Pull request merged**
