### PR TITLE
Fixing advanced_options_config.user_ip_request_headers is set to null when empty list is passed

### PR DESCRIPTION
**Pull request by felipegc**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/15646

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
securitypolicy: fixed a bug where setting `advanced_options_config.user_ip_request_headers` field with empty value was not cleaning the list (beta)
```

### CODE REVIEW

**Comment by slevenick** [comment]
Why is the update mask functionality only being added for beta? Is there a difference between the beta and GA API?

**Comment by felipegc** [comment]
> Why is the update mask functionality only being added for beta? Is there a difference between the beta and GA API?

At the beginning I thought to leave the updateMask for both versions but while generated the code for "ga" I saw there was a compilation error for this call "op, err := client.SecurityPolicies.Patch(project, sp, securityPolicy).UpdateMask(strings.Join(updateMask, ",")).Do()" since the lib versions are different for beta and ga.
Since this field is intended to work only for beta for now, I decided to leave the ga version exactly on the same way it was.

**Comment by slevenick** [comment]
> > Why is the update mask functionality only being added for beta? Is there a difference between the beta and GA API?
> 
> At the beginning I thought to leave the updateMask for both versions but while generating the code for "ga" I saw there was a compilation error for this call "op, err := client.SecurityPolicies.Patch(project, sp, securityPolicy).UpdateMask(strings.Join(updateMask, ",")).Do()" since the lib versions are different for beta and ga. Since this field is intended to work only for beta for now, I decided to leave the ga version exactly on the same way it was.

I'm hoping to get someone from the security policy team to chime in here on how this should work from the API's perspective

**Comment by felipegc** [comment]
> > > Why is the update mask functionality only being added for beta? Is there a difference between the beta and GA API?
> > 
> > 
> > At the beginning I thought to leave the updateMask for both versions but while generating the code for "ga" I saw there was a compilation error for this call "op, err := client.SecurityPolicies.Patch(project, sp, securityPolicy).UpdateMask(strings.Join(updateMask, ",")).Do()" since the lib versions are different for beta and ga. Since this field is intended to work only for beta for now, I decided to leave the ga version exactly on the same way it was.
> 
> I'm hoping to get someone from the security policy team to chime in here on how this should work from the API's perspective

There is this [statement](https://cloud.google.com/compute/docs/reference/rest/beta/securityPolicies/patch?apix_params=%7B%22project%22%3A%22felipegc-test-swg%22%2C%22securityPolicy%22%3A%22tf-userip%22%2C%22updateMask%22%3A%22advancedOptionsConfig.userIpRequestHeaders%22%2C%22resource%22%3A%7B%22name%22%3A%22tf-userip%22%2C%22description%22%3A%22please%202%22%2C%22advancedOptionsConfig%22%3A%7B%22jsonCustomConfig%22%3A%7B%7D%2C%22userIpRequestHeaders%22%3A%5B%5D%2C%22jsonParsing%22%3A%22STANDARD%22%2C%22logLevel%22%3A%22VERBOSE%22%7D%2C%22fingerprint%22%3A%22gNyog2qH1pw%3D%22%2C%22type%22%3A%22CLOUD_ARMOR%22%7D%7D#:~:text=To%20clear%20fields%20in%20the%20policy%2C%20leave%20the%20fields%20empty%20and%20specify%20them%20in%20the%20updateMask) on the api doc and also I created a scenario where I update all fields inside advancedOptionsConfig by changing all values at the same time.

**Comment by felipegc** [comment]
@slevenick I created a chat with someone from the secutity_policy team to try to help us to proceed with the code review. Could you check that? Thanks

**Review by slevenick — APPROVED** [review]

**Pull request merged**
