### PR TITLE
fix beta only flag in compute instance tests

### PR DESCRIPTION
**Pull request by shuyama1**
Fixed the issue introduced in https://github.com/GoogleCloudPlatform/magic-modules/pull/9250. This should bring back 1500+ lines in beta provider

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]

**Review by rileykarson — COMMENTED** [review]
Ah- L1795 is missing a comma on the end

**Review by rileykarson — APPROVED** [review]

**Comment by shuyama1** [comment]
tpgb unit still failed. added the fix and unit tests passed locally

**Review by rileykarson — DISMISSED** [review]

**Comment by shuyama1** [comment]
The failed test `TestAccComputeInstance_confidentialHyperDiskBootDisk ` was added but never got to run in the initial PR https://github.com/GoogleCloudPlatform/magic-modules/pull/9250 due to the flag issue. Should we revert the initial PR and work on a fix there? @rileykarson

**Comment by rileykarson** [comment]
Yeah, was just creating a revert. Sorry for missing that!

**Pull request closed without merging**
