### PR TITLE
feat(vertexai): add the data source for Vertex AI Index

### PR DESCRIPTION
**Pull request by shotarok**
Part of https://github.com/hashicorp/terraform-provider-google/issues/12818
Part of https://github.com/hashicorp/terraform-provider-google/issues/9298

Add the data source for vertex_ai_index.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
google_vertex_ai_index
```

### CODE REVIEW

**Comment by shotarok** [comment]
@shuyama1 Hello, all tests passed. Could you review this PR when you have time? Thanks!

**Comment by shuyama1** [comment]
Sorry, I'll be out this week. Assigning a new reviewer! Thanks @ScottSuarez!

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
Could you add documentation for this datasource? See other datasources like `google_firebase_android_app` for examples.

**Comment by gericdong** [comment]
@shotarok will you be available to add the documentation as suggested above? Please let us know. Thanks.

**Comment by shotarok** [comment]
@gericdong (CC: @ScottSuarez) Thank you for your heads up, and sorry about keeping this PR open for a long time. I added commits to update this PR based on the feedback.

**Review by ScottSuarez — APPROVED** [review]

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
Code is failing to compile
https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/4985343009/jobs/8924828526

**Comment by shotarok** [comment]
It looks like the failed two tests are not related and they often fails in the other open PRs.

**Comment by shotarok** [comment]
It looks like the two failed tests are not related to this PR, and they often fail in the other open PRs.

@ScottSuarez Could you give me your advice? Should we rerun the failed acceptance tests?

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
failures are non-blocking!

**Pull request merged**
