### PR TITLE
Fix GKE not being able to disable Cilium Policies

### PR DESCRIPTION
**Pull request by maxi-cit**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/19360

The issue was caused due to the 'omitempty' flag on the 'DesiredEnableCiliumClusterwideNetworkPolicy' attribute on the struct that builds the request on the library end. So I am forcing it to be sent whenever there is a change.

Other fields suffer of the same issue, but I believe this is something that this issues should be treated on a case basis.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
container: fixed issue which caused to not being able to disable `enable_cilium_clusterwide_network_policy` field on `google_container_cluster`.
```

### CODE REVIEW

**Comment by c2thorn** [comment]
Hi @maxi-cit 

The Magic Modules repository has recently migrated from Ruby to Go. You can view more details about this in our announcement here: https://github.com/hashicorp/terraform-provider-google/issues/19583 (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)

This open pull request has likely become incompatible due to most YAML and .erb files converting to Go-compatible files.

Our team (Magic Modules repository maintainers) has tooling to automatically convert changes to the new language, and we can prepare a new commit for this pull request that is compatible with the migration.

In order to push the new changes to your pull request, we would need to <ins>force push the commit to your fork's branch</ins>. Our tooling saves a backup branch before converting, so we could rollback or open a new pull request if needed. We would also work with you and the PR reviewer in the event additional changes are needed.

You also have the option to update the pull request yourself. You can view [updated documentation](https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/) related to the migration changes.

We will take no action until we have your explicit permission to push changes to your fork's branch used for this pull request. Let me or your reviewer know if you have any further questions!

**Comment by maxi-cit** [comment]
Thanks @c2thorn, I will update accordingly

**Review by melinath — CHANGES_REQUESTED** [review]
removing from queue pending updates for go rewrite

**Comment by maxi-cit** [comment]
Hello @c2thorn could you run the tests please? I check it locally and removing the .erb files should be enough to solve conflicts.

**Review by melinath — APPROVED** [review]

**Pull request merged**
