### PR TITLE
Make `google_compute_security_policy`'s `rule_visibility` optional + computed and remove default value

### PR DESCRIPTION
**Pull request by SarahFrench**
Supersedes https://github.com/GoogleCloudPlatform/magic-modules/pull/8060
Might fix https://github.com/hashicorp/terraform-provider-google/issues/12743 ?

I find that issue above confusing as it includes 2 issues:
1. Being unable to create a google_compute_security_policy resource when this is in the config:
```
adaptive_protection_config {
      layer_7_ddos_defense_config {
          enable = false
      }
}
```
2. Issues/expected behaviour when the adaptive_protection_config block is removed:
```diff
- adaptive_protection_config {
-      layer_7_ddos_defense_config {
-          enable = false
-      }
-}
```

This PR addresses issue 1.
[I explored issue 2](https://github.com/GoogleCloudPlatform/magic-modules/pull/10823#issuecomment-2142542094) but [decided that it'd be best to address that separately to 1.](https://github.com/GoogleCloudPlatform/magic-modules/pull/10823#issuecomment-2142696373)

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed issue where users could not create `google_compute_security_policy` resources with `layer_7_ddos_defense_config` explicitly disabled
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Test failures are due to a quota limit in the VCR project:

```
        Error: Error waiting for Creating Target Pool: Quota 'TARGET_POOLS' exceeded.  Limit: 150.0 globally.
```

I'll run a sweeper from TeamCity

**Comment by SarahFrench** [comment]
There isn't a sweeper for google_compute_target_instance

**Comment by SarahFrench** [comment]
The failures in `TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy` and `TestAccComputeInstance_guestAccelerator ` are unrelated to this PR.

The failure in `TestAccComputeSecurityPolicy_withoutAdaptiveProtection` is due to the final step:

```
			{
				// Can remove adaptive protection block
				Config: testAccComputeSecurityPolicy_withoutAdaptiveProtection(spName),
			},
```

In this step we make this change to the config from the previous step:

```diff
resource "google_compute_security_policy" "policy" {
  name        = "%s"
  description = "updated description"
-  adaptive_protection_config {
-    layer_7_ddos_defense_config {
-      enable = false
-    }
-  }
}
```

And the PATCH request from that update looks like:

```
---[ REQUEST ]---------------------------------------
PATCH /compute/beta/projects/PROJECT_ID/global/securityPolicies/tf-test-aaoujjl9qe?alt=json&prettyPrint=false&updateMask= HTTP/1.1
Host: compute.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/1.8.3 (+https://www.terraform.io) Terraform-Plugin-SDK/2.33.0 terraform-provider-google-beta/acc
Content-Length: 31
Content-Type: application/json
X-Goog-Api-Client: gl-go/1.21.10 gdcl/0.177.0
Accept-Encoding: gzip

{
 "fingerprint": "UQV3Yc2hZ-g="
}
```

**Comment by SarahFrench** [comment]
After the resource has DDOS defence enabled, disabled, and then deleting the adaption_protection_config block when we read the resource's data from the API it will still contain this:

```
 "adaptiveProtectionConfig": {
  "layer7DdosDefenseConfig": {
   "enable": false,
   "ruleVisibility": "STANDARD"
  }
 },
```

Making the test step mentioned in this step pass will require a change to the flatten functions so that fields are selectively read from the API response based on the user's config. If that's a path we'd want to pursue that's ok but I'd like it to be in a PR separate to this one; this PR should only be about removing the default value that makes it impossible to create a resource where `enabled=false` is in the config

**Review by slevenick — COMMENTED** [review]
Looks like the test is failing due to the security policy?

**Comment by SarahFrench** [comment]
Oh yes it is, though it doesn't look immediately related to the change in this PR.

Here are the failing tests:

- TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy/[two_nics_two_access_configs_update_remove_access_config](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L2986)
  - Uses only [this config](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L8482) that includes `google_compute_region_security_policy` but not `google_compute_security_policy`
 - TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy/[access_config_update_access_config](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L2988)
    - Uses a bunch of config ([1](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L8303),[ 2](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L8892), [3](https://github.com/hashicorp/terraform-provider-google-beta/blob/132488240c845e929b78570944b13051988bc03c/google-beta/services/compute/resource_compute_instance_test.go#L9000))  but all use `google_compute_region_security_policy` only


google_compute_region_security_policy is MMv1 generated while google_compute_security_policy is handwritten, so I don't think there's any schema re-used between them.

**Comment by SarahFrench** [comment]
I'll re-run the tests and hopefully the test will pass in RECORDING mode : /gcbrun

**Comment by SarahFrench** [comment]
TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy has been failing in nightly tests: https://github.com/hashicorp/terraform-provider-google/issues/17838

TestAccComputeInstance_guestAccelerator has been failing in nightly tests: 
https://hashicorp.teamcity.com/test/-2086049782442135804?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true

**Comment by SarahFrench** [comment]
> Are we okay with merging a PR that is failing VCR for valid reasons? I believe we make sure that these always pass

I think so - if a test is failing on main then there should be a test failure ticket open and a PR opened to address the test failure

**Comment by SarahFrench** [comment]
I realised that in https://github.com/GoogleCloudPlatform/magic-modules/pull/10823/commits/ce34db40878383e105734450194fb731a56ed7a6 I intended to remove a step but I removed the whole test.

I intended to remove only:

```
{
	// Can remove adaptive protection block
	Config: testAccComputeSecurityPolicy_withoutAdaptiveProtection(spName),
},
```

I'm going to push a commit to re-add that test

**Comment by SarahFrench** [comment]
The test I returned, TestAccComputeSecurityPolicy_withoutAdaptiveProtection, passed.

The failing test in VCR is failing on main: https://github.com/hashicorp/terraform-provider-google/issues/17838

I'll merge this later after the nightly tests finish

**Pull request merged**
