### PR TITLE
Add Pub/Sub Lite reservation support to terraform.

### PR DESCRIPTION
**Pull request by dpcollins-google**
Also fix doc links for Pub/Sub Lite.

fixes https://github.com/hashicorp/terraform-provider-google/issues/10257

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-resource
`google_pubsub_lite_reservation`
```
```release-note:enhancement
pubsub:  Added support for references to `google_pubsub_lite_reservation` to `google_pubsub_lite_topic`.
```

### CODE REVIEW

**Comment by dpcollins-google** [comment]
I've added the examples- building now, unfortunately it takes a while.

**Comment by ndmckinley** [comment]
Okay - running the tests now.  /gcbrun

**Comment by ndmckinley** [comment]
Great - as long as that last test passes, this can go in today and be released next week Monday.

**Comment by ndmckinley** [comment]
Ah, unfortunately not:

```
------- Stdout: -------
=== RUN   TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample
=== PAUSE TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample
=== CONT  TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample
provider_test.go:278: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# google_pubsub_lite_reservation.example will be updated in-place
~ resource "google_pubsub_lite_reservation" "example" {
id                  = "projects/1067888929963/locations/us-central1/reservations/tf-test-example-reservationmbdz2vv2gl"
name                = "tf-test-example-reservationmbdz2vv2gl"
~ throughput_capacity = 0 -> 2
# (1 unchanged attribute hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample (7.51s)
FAIL
```

**Comment by ndmckinley** [comment]
It just needed a minor change - it needed to use `locations` instead of `regions` for the reference.  :)

Tests pass on my machine but I'll wait for the diffs to generate to be sure.

**Pull request merged**
