### PR TITLE
add support for 'apikeys.googleapis.com/Key' to TGC

### PR DESCRIPTION
**Pull request by dvfons**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Failing tests

**Comment by dvfons** [comment]
@slevenick can you take a look now please sorry but i'd got a eviromment problem

**Comment by slevenick** [comment]
Still failing on ... // 2 identical fields

**Review by slevenick — COMMENTED** [review]
Failing to compile

**Comment by dvfons** [comment]
i beleve thats broken cause this:
image

**Comment by dvfons** [comment]
this pr must reverted https://github.com/GoogleCloudPlatform/magic-modules/pull/10773

**Comment by slevenick** [comment]
Made https://github.com/GoogleCloudPlatform/magic-modules/pull/10928 to fix this

**Review by slevenick — CHANGES_REQUESTED** [review]
Looks like it's failing with errors relevant to this PR now

**Comment by dvfons** [comment]
> Looks like it's failing with errors relevant to this PR now

i fixed thanks

**Review by slevenick — APPROVED** [review]

**Pull request merged**
