### PR TITLE
Mark GKE Workload Identity config as GA

### PR DESCRIPTION
**Pull request by ewolak-sq**
Per https://cloud.google.com/kubernetes-engine/docs/release-notes#march_16_2020, Workload Identity is now generally available in some GKE versions. Therefore it should be available in the "google" provider, not just the "google-beta" provider.

I'm not 100% sure I got every 'ga' guard here, as workload identity is mixed-up with a bunch of other beta features.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
container: `google_container_cluster`'s `workload_identity_config` is now GA.
```

### CODE REVIEW

**Comment by ewolak-sq** [comment]
Whoops! This needs some work. I'll fix the 'ga' guards.

**Comment by ndmckinley** [comment]
Hi there - happy to review when you're ready!  The ga guards still need some work:
```
google/resource_container_cluster.go:989:36: undefined: expandWorkloadIdentityConfig
google/resource_container_cluster.go:1192:46: undefined: flattenWorkloadIdentityConfig
google/resource_container_cluster.go:1668:36: undefined: expandWorkloadIdentityConfig
```

**Comment by ndmckinley** [comment]
Only one left:
```
google/resource_container_node_pool_test.go:178:13: undefined: testAccContainerNodePool_withWorkloadMetadataConfig_gkeMetadataServer
```

**Comment by ewolak-sq** [comment]
You beat me to it! Was just getting a local env set up so I could find these mess-ups myself.

**Comment by ndmckinley** [comment]
Helps to have access to the CI project - getting a local env set up is a bear sometimes.  You might consider trying the cloud-shell tool in the README if you're having trouble with it.

I'll review when you're ready!  Thanks for your contribution.  :)

**Comment by ndmckinley** [comment]
```
google/resource_container_cluster_test.go:2710:6: `testAccContainerCluster_withWorkloadIdentityConfigEnabled` is unused (deadcode)
func testAccContainerCluster_withWorkloadIdentityConfigEnabled(projectID string, clusterName string) string {
     ^
google/resource_container_cluster_test.go:2728:6: `testAccContainerCluster_updateWorkloadIdentityConfig` is unused (deadcode)
func testAccContainerCluster_updateWorkloadIdentityConfig(projectID string, clusterName string, enable bool) string {
     ^
make: *** [lint] Error 1
```

**Comment by ewolak-sq** [comment]
I figured out how to run the acceptance tests myself! They're executing now...

**Comment by ewolak-sq** [comment]
Hmmmm
```
$ make testacc TEST=./google TESTARGS='-run=TestAccContainerCluster_withWorkloadIdentityConfig'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccContainerCluster_withWorkloadIdentityConfig -timeout 240m -ldflags="-X=github.com/terraform-providers/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccContainerCluster_withWorkloadIdentityConfig
=== PAUSE TestAccContainerCluster_withWorkloadIdentityConfig
=== CONT  TestAccContainerCluster_withWorkloadIdentityConfig
--- FAIL: TestAccContainerCluster_withWorkloadIdentityConfig (416.11s)
    testing.go:674: Step 2 error: errors during apply:

        Error: googleapi: Error 400: WorkloadIdentity must be disabled on all nodepools before it can be disabled at the cluster level., badRequest

          on /var/folders/9y/v6hy9gbn2k7_gl85nxkqjxf00000gn/T/tf-test432643491/main.tf line 6:
          (source code not available)


FAIL
FAIL	github.com/terraform-providers/terraform-provider-google/google	416.140s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewolak-sq** [comment]
I'm so sorry, but I don't understand Magic Modules well enough to untangle `workload_metadata_config` (which might still be Beta?) from `workload_identity_config` here. @ndmckinley can someone from Cloud Graphite take over and see this through?

**Comment by ndmckinley** [comment]
No problem - we'll put that on our triage list and assign it next week.  :)

**Comment by ndmckinley** [comment]
I've replaced this with https://github.com/GoogleCloudPlatform/magic-modules/pull/3580 to make sure we comply with the two-approvals policy.  :)

**Comment by ndmckinley** [comment]
Hi,

It seems there's been a github bug and your identity got confused with our CI robot.  Odd!

In any event, yes, it seems to be GA as of May of this year.

**Pull request closed without merging**
