### PR TITLE
Update node pool tests to use bootstrapped network

### PR DESCRIPTION
**Pull request by shuyama1**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
Our network is located in `us-central1` while `TestAccContainerNodePool_withConfidentialNodes` and `TestAccContainerNodePool_withHostMaintenancePolicy` set locations to others. I went through the original PRs and didn't see particular reasons that we couldn't create them in `us-central1`. So I just modified them.

Some other tests failed with `max secondary ranges reached` issue, a rerun should make them work.

**Comment by shuyama1** [comment]
Run VCR skipped tests on TC: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleBeta_MmUpstreamTesting_GOOGLEBETA_PACKAGE_CONTAINER/47970?hideTestsFromDependencies=false&hideProblemsFromDependencies=false

**Comment by shuyama1** [comment]
I can get `TestAccContainerNodePool_withHostMaintenancePolicy` passed locally but not in VCR project. I'll revert the change in that test for now and will look into the issue and add the bootstrapped network to it in a later PR

**Review by rileykarson — APPROVED** [review]
LGTM- I haven't verified all the argument positions within the config or anything, but scanned through and no surprises + all the ones I did check were correct.

**Pull request merged**
