### PR TITLE
fix vcr message format

### PR DESCRIPTION
**Pull request by shuyama1**
fix vcr message format issue. example: https://github.com/GoogleCloudPlatform/magic-modules/pull/10650#issuecomment-2105305924

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by melinath** [comment]
Could we fix it like this instead: https://github.com/GoogleCloudPlatform/magic-modules/pull/10681

**Comment by melinath** [comment]
sorry, didn't see this until after making that

**Comment by melinath** [comment]
let me know what you think!

**Comment by shuyama1** [comment]
This will be fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/10681

**Pull request closed without merging**
