### PR TITLE
Fix Datastream kms test failure

### PR DESCRIPTION
**Pull request by iperetz-goo**
Fix https://github.com/hashicorp/terraform-provider-google/issues/13709, by moving the cmek key name override to the correct example

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by hao-nan-li** [comment]
I didn't see this test failing during recording mode so I tested it locally.
I'm currently getting some     **"message": "Resource name 'projects//locations/us-central1/keyRings/tftest-shared-keyring-1' does not match pattern 'projects/([^/]{1,100})/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})'.",**
Could you confirm the test passed on your environment?

**Review by hao-nan-li — CHANGES_REQUESTED** [review]
I didn't see TestAccDatastreamStream_datastreamStreamFullExample failing during recording mode so I tested it locally.

I'm currently getting some "message": "Resource name 'projects//locations/us-central1/keyRings/tftest-shared-keyring-1' does not match pattern 'projects/([^/]{1,100})/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})'.",
Could you confirm the test passed on your environment?

**Review by roaks3 — APPROVED** [review]
Cool, LGTM. I'm going to just update the release note manually, since I think Ido is in a different timezone.

**Review by hao-nan-li — APPROVED** [review]
Sound good!

**Pull request merged**
