### PR TITLE
Ansible: better documentation for how a resourceref works

### PR DESCRIPTION
**Pull request by rambleraptor**
We had an issue on Ansible that ResourceRefs are a little difficult to understand.
This is meant to help people better understand how resourcerefs work and what a ResourceRef field can/cannot take in.

-----------------------------------------------------------------
# [all]
Ansible: better documentation for how a resourceref works
## [ansible]
Better documentation for how a resourceref works

### CODE REVIEW

**Comment by rambleraptor** [comment]
Let me know your thoughts on the documentation text. I'm trying to say that there's multiple ways of expressing ResourceRefs.

Method 1:
```yaml
  gcp_compute_address:
    name: my-address
    ...
  register: address

  gcp_compute_instance:
     address: "{{ address }}"
```

Method 2:

```yaml
  gcp_compute_instance:
    address:
      name: my-address
```

**Comment by danawillow** [comment]
I'm a bit confused by your example. Can you try to make a new one that aligns a bit better with the API itself? Should one of those fields be `nat_ip`? I'm not totally sure which things are address because that's the name of the resource it's referencing vs address because a field name might be address.

**Comment by rambleraptor** [comment]
Yeah, check out my example (and better explanation)

**Comment by danawillow** [comment]
That helps, thanks! So I think this is one of those things that might be a bit better to explain explicitly. Here's a thought, let me know if you think this reads better / whether it's actually accurate.

This field represents a link to a ___ resource in GCP, and can be specified in two ways:
1. Add a `register: name-of-resource` field to the ___ resource, and reference it using `"{{ name-of-resource }}"`
2. Use a dictionary with a `name` field that points to the name of the __ resource.

Or just like, what if you put those two examples straight into the docs there?

(while I'm here, question about approach 2- what would happen if you had two addresses with the same name but different regions?)

**Comment by rambleraptor** [comment]
I sadly don't think I can just place the examples into the description because it's just a blob of text. Formatting will be messed up when it goes into docs.ansible.

I like the idea of being explicit like that. Let me take another swing at it.

**Comment by rambleraptor** [comment]
@danawillow mind taking another look?

**Comment by rambleraptor** [comment]
> That helps, thanks! So I think this is one of those things that might be a bit better to explain explicitly. Here's a thought, let me know if you think this reads better / whether it's actually accurate.
> 
> This field represents a link to a ___ resource in GCP, and can be specified in two ways:
> 
> 1. Add a `register: name-of-resource` field to the ___ resource, and reference it using `"{{ name-of-resource }}"`
> 2. Use a dictionary with a `name` field that points to the name of the __ resource.
> 
> Or just like, what if you put those two examples straight into the docs there?
> 
> (while I'm here, question about approach 2- what would happen if you had two addresses with the same name but different regions?)

Intended behavior!

**Pull request merged**
