### PR TITLE
Fix compute test failure

### PR DESCRIPTION
**Pull request by SarahFrench**
Stacked PR on top of https://github.com/GoogleCloudPlatform/magic-modules/pull/10883

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Current issues:

```
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating NetworkEdgeSecurityService: googleapi: Error 400: Invalid value for field 'resource.region': ''. Region europe-west1 already has a Network Edge Security Service., invalid
        
          with google_compute_network_edge_security_service.edge_sec_service,
          on terraform_plugin_test.tf line 18, in resource "google_compute_network_edge_security_service" "edge_sec_service":
          18: resource "google_compute_network_edge_security_service" "edge_sec_service" {
```

```
    vcr_utils.go:152: Step 1/6 error: Check failed: Check 2/2 error: Security Policy with name google_compute_region_security_policy.policyforinstance.self_link not present
```

**Comment by SarahFrench** [comment]
The failure here seems to be only due to quotas - I'll run a sweeper and re-run the test

**Comment by rileykarson** [comment]
Hey! I'm closing this PR as a part of a cleanup of older inactive PRs, using a threshold of PRs in "Draft" last updated over a month ago. This doesn't represent rejection of the change, and feel free to comment for me to reopen it if you plan to pick it back up, or feel free to start a new PR with the same changes in the future.

**Pull request closed without merging**
