### PR TITLE
Add TD example to docs

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8366

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by upodroid** [comment]
I don't think this should be implemented in terraform. There is a precedent for that because the provider doesn't configure this either https://cloud.google.com/compute/docs/containers/deploying-containers https://github.com/terraform-google-modules/terraform-google-container-vm

In both cases, it is the job of the endusers to identify valid metadata values and supply it in terraform.

**Comment by upodroid** [comment]
Looking at the SDK code, not a great idea.

https://github.com/twistedpair/google-cloud-sdk/blob/master/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/instance_templates/service_proxy_aux_data.py

https://github.com/twistedpair/google-cloud-sdk/blob/master/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/instance_templates/flags.py

**Review by melinath — COMMENTED** [review]
Hi Upodroid - sorry for the delayed review on this. It looks like the ticket this is linked to is proposing some code changes rather than a documentation update, so I am pretty sure this PR would not resolve that issue.

Do you want to have this reviewed even if the other work will still happen, or are you proposing this as an alternative to that work?

**Comment by upodroid** [comment]
The code change isn't appropriate in my opinion given that it involves setting metadata entries which we can already do unless google is introducing instance api fields.

**Review by melinath — APPROVED** [review]
I hear what you're saying regarding hashicorp/terraform-provider-google#8366; however, we may end up doing that work in order to provide a better user experience, so we will need to keep the ticket open to track it. That being said, I'm happy to merge this documentation improvement once the merge conflicts are resolved. :-)

**Comment by upodroid** [comment]
Conflicts are fixed.

**Comment by melinath** [comment]
Unfortunately, after some more discussion it seems like we're not going to merge this change after all, since documenting this way of handling the issue would make the other potential solutions breaking changes.

I'm sorry to be backtracking; I thought we could safely release the documentation in addition to making other changes but that does not seem to be the case.

**Comment by upodroid** [comment]
Hmm, that is fine. I'm curios about those breaking changes

**Comment by rileykarson** [comment]
We'd consider promoting certain values that are configured through labels into properties on the resource. We have precedent, particularly in Stackdriver, and call the pattern "load-bearing labels". The way that gets accomplished would probably lead to a diff for users who've configured the settings through labels, so we'd like to avoid promoting an alternative configuration until we've made a decision about whether to do so or not.

**Pull request closed without merging**
