### PR TITLE
Rename TF Samples files

### PR DESCRIPTION
**Pull request by msampathkumar**
No changes in the file content. Only update in the filenames of two terraform samples.

- Removed "custom_header" suffix as its not required.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by betsy-lichtenberg** [comment]
I think the strings in terraform.yaml will need to be updated as well.

https://github.com/GoogleCloudPlatform/magic-modules/blob/08f676cfeddd5fefc72e3973226f5e8ac61329ca/mmv1/products/compute/terraform.yaml#L940

https://github.com/GoogleCloudPlatform/magic-modules/blob/08f676cfeddd5fefc72e3973226f5e8ac61329ca/mmv1/products/compute/terraform.yaml#L960

**Comment by shuyama1** [comment]
I've update the changelog and let's wait the tests to pass to make sure we covered everything!

**Review by shuyama1 — APPROVED** [review]

**Comment by shuyama1** [comment]
@msampathkumar @betsy-lichtenberg Thanks for your contribution!

**Pull request merged**
