### PR TITLE
Update Instance.yaml to remove LOOKER_MODELER edition

### PR DESCRIPTION
**Pull request by efeelaiho**
remove LOOKER_MODELER edition as we will not be GA'ing that offering

**Release Note Template for Downstream PRs (will be copied)**

```release-note:remove LOOKER_MODELER edition

```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
It is a breaking change to remove an enum value as it could break a user's config who has specified this value. 

You could make this against the 5.0.0 branch instead, and it should be accepted, but it cannot be made against main

**Comment by efeelaiho** [comment]
@slevenick is this considered a breaking change if the edition never GA'd to the public? In other words the enum value should not have been added to begin with as it was in development internally.

**Comment by slevenick** [comment]
> @slevenick is this considered a breaking change if the edition never GA'd to the public?

Yep, but you can make this against the 5.0.0 branch and it should go out soon! Just make sure it happens quickly because we are cutting off merges at the end of the week

**Comment by efeelaiho** [comment]
@slevenick Okay thanks! Created a new PR here: https://github.com/GoogleCloudPlatform/magic-modules/pull/9032

**Pull request closed without merging**
