### PR TITLE
Revert "Support generating code for terraform-google-conversion"

### PR DESCRIPTION
**Pull request by ScottSuarez**
Reverts GoogleCloudPlatform/magic-modules#7395

Causing build failure in our pipeline
https://pantheon.corp.google.com/cloud-build/builds/2ff410c3-1e29-4829-89f1-b3b8731e37a4?project=673497134629&utm_campaign=google-cloud-build-notifiers&utm_medium=chat&utm_source=google-cloud-build&jsmode=O&mods=logs_tg_staging

notice @melinath @iyabchen

```release-note:none
```

### CODE REVIEW

**Comment by iyabchen** [comment]
I checked the ci, it is not using the latest image to run, could you trigger another run, and if it still fails, let me know the build log? @ScottSuarez

**Comment by melinath** [comment]
It looks like this was an issue with the downstream builder image getting rebuilt; currently retrying.

**Comment by melinath** [comment]
looks like re-running did the trick!

**Pull request closed without merging**
