### PR TITLE
Update default value for node pool config

### PR DESCRIPTION
**Pull request by naitianliu-google**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
google_gkeonprem_vmware_node_pool: set default values of node pool config fields `boot_disk_size_db` and `image_type`
google_gkeonprem_vmware_node_pool: update default value of node pool config field `replicas` from 1 to 3
google_gkeonprem_vmware_cluster: update `hostname` of `ip_block` from required to default_from_api
```

### CODE REVIEW

**Review by akulkapoor90 — APPROVED** [review]

**Comment by naitianliu-google** [comment]
> @naitianliu-google As mentioned in the automated message, these would be breaking changes. Is the intention for these to be included in the next major release (multiple months from now)?

@roaks3 Thanks for confirming this. The changes are intended to be included in the next minor release (next week). These are the fixes for the initial resource schema released last week. As we haven't officially released the resources to end customers, the breaking changes won't affect existing customers. 

Please let me know if further clarification is needed. Thanks!

**Comment by roaks3** [comment]
It looks like these resources have been released in https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.64.0. Can you please confirm that these resources could be in use already?

**Comment by naitianliu-google** [comment]
> It looks like these resources have been released in https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.64.0. Can you please confirm that these resources could be in use already?

These resources are not in use currently. We wanted to patch the fixes in this PR and get released ASAP.

**Comment by roaks3** [comment]
Hey @naitianliu-google , I checked in with the team, and unfortunately we can't include breaking changes like this in a minor release. The problem is not only if users are currently using the resource, but also if a user were to upgrade directly to v4.64.0 in the future and begin using the resource.

The options would be to include this in the next major release, or work on a way to solve the problem without a breaking change. Let me know how you'd like to move forward and if you have any questions.

**Comment by roaks3** [comment]
@c2thorn it looks like there isn't an associated issue, but it might make sense to include this in 6.0.0. Would that fit in with our plan?

**Comment by c2thorn** [comment]
> @c2thorn it looks like there isn't an associated issue, but it might make sense to include this in 6.0.0. Would that fit in with our plan?

That would be fine as long as @naitianliu-google or someone else from the service would carry it forward. Given this missed last year's major release window, I'm not sure how relevant it still is?

**Comment by roaks3** [comment]
I checked with them internally and received no response, so closing the PR as having no owner (we can of course re-open if that changes)

**Pull request closed without merging**
