### PR TITLE
Support FOR_MIGRATION InternalRange objects

### PR DESCRIPTION
**Pull request by sebkalis**
Support for for-migration InternalRange resources. 

A new value of usage enum is introduced: FOR_MIGRATION. Such ranges must also contain a nested object consisting of 2 strings: source - an URI/path to the migration source (a subnet resource being migrated, in its original location) and a target - an URI/path for the planned future resource (a subnet) to be recreated in the new location.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/19636

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
networkconnectivity: added field `migration` to resource `google_network_connectivity_internal_range`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Could you add a test for this field and pull the latest changes from main?

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
waiting for addition of test

**Comment by sebkalis** [comment]
Test has been added

**Review by ScottSuarez — APPROVED** [review]
Thanks for the work ! 😄

**Pull request merged**
