### PR TITLE
Docs: Fix a broken-link in getting-started/provider-documentation

### PR DESCRIPTION
**Pull request by sahya**
Update a document for fixing a broken link in getting-started/provider-documentation
Info: This Pull request only fixed a tiny change about  a broken link

If this PR is for Terraform, I acknowledge that I have:

- [-] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [-] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [-] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [-] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [-] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

<!-- AUTOCHANGELOG for Downstream PRs.

```release-note:none
```

### CODE REVIEW

**Comment by melinath** [comment]
LGTM - could you sign the CLA? https://github.com/GoogleCloudPlatform/magic-modules/pull/7759/checks?check_run_id=12837584245

**Review by melinath — CHANGES_REQUESTED** [review]
Marking as change requested to remove from my review queue pending CLA - please re-request review or ping me once that's done!

**Comment by sahya** [comment]
Sorry, I don't have a Google account for my GitHub account and I'm closing the PR with sincere disappointment. I wasn't motivated enough to create an account to make this small change and other documentation changes.

**Comment by sahya** [comment]
This issue fixed by #7998

**Pull request closed without merging**
