### PR TITLE
Remove unused front-matter from provider documentation

### PR DESCRIPTION
**Pull request by SarahFrench**
# Description

This PR:
- removes the `layout` front-matter from documentation markdown files and template files
- removes the .erb template files that the `layout` value refers to
- removes the `sidebar_current` front-matter and template files linked to the sidebar navigation in the documentation.
- removes the .erb template file for the sidebar in the docs

The accepted front-matter values in [the Registry documentation](https://www.terraform.io/registry/providers/docs#yaml-frontmatter) are `page_title` and `subcategory`. The `description` field is less clear - I've been told that it _should_ be being used to set meta tags for SEO even though the documentation doesn't mention this, so best to leave them alone!

Other fields like `layout` and `sidebar_current` are not supported anymore - e.g. here's an [issue in the aws provider that describes `sidebar_current` needing to be removed](https://github.com/hashicorp/terraform-provider-aws/issues/14712). By removing them it'll make it easier to debug documentation issues etc

## Impact

Lots of markdown files have the 2 fields deleted from them in this PR

Templates and non-markdown files affected:
- [mmv1/templates/terraform/resource.html.markdown.erb](https://github.com/GoogleCloudPlatform/magic-modules/pull/6238/files#diff-70ccc3b4cef5102361666e473513c0d7b00366088377032724c4aaf9f384e3de) - stop it adding the 2 frontmatter fields
- [mmv1/templates/terraform/resource_iam.html.markdown.erb](https://github.com/GoogleCloudPlatform/magic-modules/pull/6238/files#diff-7970d5a719f2e0cb081db5faf7b874867acfca53590b2d3fe3464756a323332e) - stop it adding the 2 frontmatter fields
- [mmv1/third_party/terraform/website/google.erb.tmpl](https://github.com/GoogleCloudPlatform/magic-modules/pull/6238/files#diff-ac901b575bb22b967cb25b9e7b93b069dc7e74a7b4f305e492cc2edbb7de6282) - delete it as it's unneeded
- [mmv1/third_party/terraform/scripts/sidebar/sidebar.go](https://github.com/GoogleCloudPlatform/magic-modules/pull/6238/files#diff-db33af93ae5c09fe3bb4ad76bc3ad462d0dfd96f32d49d980d9c5782bf891271) - delete it as it's unneeded
- **tpgtools** -  [tpgtools/templates/resource.html.markdown.tmpl](https://github.com/GoogleCloudPlatform/magic-modules/pull/6238/files#diff-9e6a5d98220b5e41879583fe29fb7082fb538ec5b853954b44eed7040aa406ea)

**This PR should not affect the appearance of documentation in the Registry providing that:**
- All MD files for resources and datasources have `subcategory` still set
- All MD files in the [guides folder](https://github.com/hashicorp/terraform-provider-google/tree/main/website/docs/guides) have `page_title` still set

## Open questions & stuff

- During this work I found [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5890) updating generation of `sidebar_current` in tpgtools - I believe that this could be removed, unless I've misunderstood something! 

- Also I'm aware this change cannot be tested other than by making a release - sorry about that 😬 

-  Depending on how modular-magician works, I think this layout file in the downstream repo might need to be deleted via a PR directly against the downstream?:
    - [website/google.erb](https://github.com/hashicorp/terraform-provider-google/blob/main/website/google.erb) 

# References

- Supported YAML frontmatter -  https://www.terraform.io/registry/providers/docs#yaml-frontmatter
- [PR in the aws provider where `sidebar_current` is removed](https://github.com/hashicorp/terraform-provider-aws/pull/8224).

# Checklist

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
Looks like the build failed. Are you able to build this locally?

**Comment by SarahFrench** [comment]
Hi @shuyama1 - yes I can build this locally using `make terraform`, though I've only built the ga version

**Comment by SarahFrench** [comment]
☝️ Latest commit is an extra file @megan07 identified - going to see if deleting that resolves the build issues

**Comment by miguelhrocha** [comment]
Hi @shuyama1!

I am Miguel and I work at the Registry team. @SarahFrench asked me to have a look and I can confirm that removing the `layout` and the `sidebar_current` front matter makes sense as we currently do not support it in any way or form.

**Comment by shuyama1** [comment]
> Thanks @miguelhrocha !
> 
> @shuyama1 - Thanks for bearing with me on this PR!
> 
> The remaining thing I don't know is whether [this template file](https://github.com/hashicorp/terraform-provider-google/blob/main/website/google.erb?rgh-link-date=2022-07-18T18%3A20%3A50Z) need to be removed by a PR directly to the hashicorp/terraform-provider-google repo. It also isn't needed but I can't track its origin from this repo.

I don't think we need a PR against hashicorp/terraform-provider-google repo to remove the template file. It should be automatically removed, as it can be seen in the generated downstream diff result in this PR at https://github.com/GoogleCloudPlatform/magic-modules/pull/6238#issuecomment-1183250590

> Also, there is [code from this PR that can be removed](https://github.com/GoogleCloudPlatform/magic-modules/pull/5890/files) as a result of this PR. Should removing this unused code be kept as a separate PR, or should everything related to removing deprecated front matter be in this PR?

Sorry, got a question about this. Looks like the code added in https://github.com/GoogleCloudPlatform/magic-modules/pull/5890 is introduced to solve https://github.com/hashicorp/terraform-provider-google/issues/10937 where the documentation of some resources are not generated in the correct position in the sidebar. So after merging this PR (removing all unused front-matter and related files), is the appearance of the website sidebar going to remain the same? My understanding is that nothing is going to change on the website and I just want to make sure I understand correctly. Thanks :)

**Comment by SarahFrench** [comment]
Ah yes of course I should have checked the downstream diffs! I overlooked that and was only checking what happened locally on my laptop. Thanks! 😁 

As for the expected outcomes of this PR, yes, it should leave the documentation and the sidebar navigation in the Registry unchanged. The stuff I'm removing was used at one point but was deprecated around the time when Terraform provider documentation was migrated from terraform.io to registry.terraform.io (long before my time at HashiCorp).

<details>
  <summary>Here's some explanation about how the frontmatter is used, if it helps give context about my next paragraph</summary>
  <br>

## Docs in the Guides subcategory

Documentation in the **_Guides_** subcategory is sourced from the `website/docs/guides` directory (so `subcategory` frontmatter is unnecessary and can be left unset in those files) and the value of `page_title` sets what text is shown in the sidebar navigation. E.g. this [getting started guide](https://github.com/hashicorp/terraform-provider-google/blob/main/website/docs/guides/getting_started.html.markdown) doesn't have `subcategory` set and `page_title` matches the first link in this screenshot:

Screenshot 2022-07-19 at 11 15 45

## Docs in custom subcategories about resources & data sources

Docs about resources and data sources are all stored in a flat structure in `website/docs/r` & `website/docs/d`. They are arranged into subcategories in the Registry sidebar navigation using the value of `subcategory` in their frontmatter. The value of `page_title` is not used here - but I think it's fine to leave in those files as the fact they are not used is easier to understand by looking at the [Registry's documentation about publishing providers](https://www.terraform.io/registry/providers/docs#yaml-frontmatter).

E.g. the [google_privateca_certificate_template resource](https://github.com/hashicorp/terraform-provider-google/blob/main/website/docs/r/privateca_certificate_template.html.markdown) has "Certificate Authority Service " as the `subcategory` value and is shown below in the Registry navigation bar. The `page_title` value is ignored.

Screenshot 2022-07-19 at 11 46 07

</details>

I think my PR will hopefully avoid similar confusion with https://github.com/GoogleCloudPlatform/magic-modules/pull/5890 , here's the timeline of events showing why it wan't clear at the time that #5890 didn't affect the documentation sidebar as expected:

1. Jan 20th - [the issue you mentioned](https://github.com/hashicorp/terraform-provider-google/issues/10937) was created. [In v4.7.0 the google_privateca_certificate_template documentation](https://github.com/hashicorp/terraform-provider-google/blob/v4.7.0/website/docs/r/privateca_certificate_template.html.markdown) had an incorrect `subcategory` value "Privateca"
2. April 4th - the PR https://github.com/GoogleCloudPlatform/magic-modules/pull/5890 that intended to fix the sidebar issue  by altering `sidebar_current` was merged. Totally understandable to expect that to be the fix!
3. April 13th - this PR https://github.com/GoogleCloudPlatform/magic-modules/pull/5937 corrected the value of `subcategory` (was changed "Privateca" => "Certificate Authority Service")
4.  April 18th - Both of those PRs were included in the v4.18.0 release, where the [correct `subcategory` value](https://github.com/hashicorp/terraform-provider-google/blob/v4.18.0/website/docs/r/privateca_certificate_template.html.markdown) was present in the release due to the 2nd PR. This would have changed the appearance in the Registry documentation but it would have been unclear at the time which PR caused the change

**Comment by shuyama1** [comment]
@SarahFrench Thank you so much for the detailed explanation! It's super clear now. Then I think this PR is good to go. Thanks for making the changes!

**Review by shuyama1 — APPROVED** [review]

**Comment by shuyama1** [comment]
Thanks @miguelhrocha for taking a look!

**Pull request merged**
