### PR TITLE
Fix missing fields on Certificate

### PR DESCRIPTION
**Pull request by gfxcc**
fixes https://github.com/hashicorp/terraform-provider-google/issues/10966

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
privateca: added new output fields on `google_privateca_certificate` including `issuer_certificate_authority`, `pem_certificate_chain` and `certificate_description.x509_description`
```

### CODE REVIEW

**Review by slevenick — APPROVED** [review]
LGTM

These were left over from the beta implementation that was scrapped when the API went to v1

**Comment by slevenick** [comment]
Unfortunately after consultation with another team member I don't think we can go forward with this. Removing fields even if they are incorrect, output-only and empty is considered a breaking change that can't be done in a minor version.

Can you change this to be purely additive, and mark the incorrect fields with a deprecation: message? We are able to add fields as needed for this use case, but we can't remove the old ones

**Comment by gfxcc** [comment]
Change the PR to be additive only. 
@slevenick , it seems the documentation is not updated for those fields updated with a `deprecation_message`. Is there anything missing?

**Review by slevenick — APPROVED** [review]
Seems reasonable

**Pull request merged**
