### PR TITLE
[WIP] Enable composer private networking options.

### PR DESCRIPTION
**Pull request by jmcarp**
Support composer options related to [private networking](https://cloud.google.com/composer/docs/concepts/private-ip). I'm submitting this as a draft for feedback on the interface. If that makes sense, I'll work on integration testing.

cc @danawillow

### CODE REVIEW

**Comment by danawillow** [comment]
cc @tysen who's also been working on this. Ty, up to you how you want to handle.

@jmcarp, thanks so much for the contribution! In the future, would you mind commenting on the related GH issue (in this case, https://github.com/terraform-providers/terraform-provider-google/issues/3526) to let us know you're working on it so we don't accidentally end up duplicating work?

**Comment by jmcarp** [comment]
Sorry about that, I looked through the tickets but didn't realize the ticket you linked was about this feature. If you all already have this in progress and/or would rather do it yourselves, I'll close this.

**Comment by jmcarp** [comment]
@danawillow and @tysen: did you pick this up? Happy to finish writing tests or close this PR, depending on your plans.

**Comment by tysen** [comment]
@jmcarp I am working on this, sorry about the delayed response.

**Comment by jmcarp** [comment]
Thanks @tysen!

**Comment by jmcarp** [comment]
Any updates @tysen? Looking forward to this being available via tf.

**Comment by tysen** [comment]
@jmcarp Working on it here: https://github.com/GoogleCloudPlatform/magic-modules/pull/1999, sorry for the delay.

**Pull request closed without merging**
