### PR TITLE
Update Instance.yaml to remove LOOKER_MODELER edition

### PR DESCRIPTION
**Pull request by efeelaiho**
fixes https://github.com/hashicorp/terraform-provider-google/issues/15923

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
looker: removed `LOOKER_MODELER` as a possible value in `google_looker_instance. platform_edition`
```

### CODE REVIEW

**Comment by c2thorn** [comment]
Is there a GH issue and upgrade guide associated with this PR?

**Comment by efeelaiho** [comment]
@c2thorn No, this is an internal issue to remove LOOKER_MODELER edition as we will not be GA'ing that offering. b/301270835
b/298254910

**Comment by c2thorn** [comment]
created https://github.com/hashicorp/terraform-provider-google/issues/15923 to track and updated the changelog. We require an upgrade guide entry for breaking changes to explain what users should use instead. This will need to be in a separate pull request to the `main` branch. Instructions are at https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#add-upgrade-guide-entries-to-the-main-branch-of-magic-modules

**Comment by c2thorn** [comment]
> created [hashicorp/terraform-provider-google#15923](https://github.com/hashicorp/terraform-provider-google/issues/15923) to track and updated the changelog. We require an upgrade guide entry for breaking changes to explain what users should use instead. This will need to be in a separate pull request to the `main` branch. Instructions are at [googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#add-upgrade-guide-entries-to-the-main-branch-of-magic-modules](https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#add-upgrade-guide-entries-to-the-main-branch-of-magic-modules)

@efeelaiho have you seen this?

**Comment by efeelaiho** [comment]
@c2thorn Thanks! Have created this PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/9052
for the upgrade guide

**Review by c2thorn — APPROVED** [review]

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
