### PR TITLE
adding user_ip_request_headers support to compute_security_policy

### PR DESCRIPTION
**Pull request by felipegc**
fixes:
https://github.com/hashicorp/terraform-provider-google/issues/15048

Adding user_ip_request_headers support to compute_security_policy

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `user_ip_request_headers` field to `google_compute_security_policy` resource(beta)
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
👋 Thanks for your PR! The test that ran above uses the GA version of the provider, not Beta, but when I ran the acceptance test manually I can see that the new field behaves well. I'm just checking internally about any gotchas around the schema.Set field type, and will resume reviewing once I've got some feedback.

**Comment by felipegc** [comment]
Hi @SarahFrench is there anything else from my side? Thanks

**Comment by SarahFrench** [comment]
Nope - I got the feedback I mentioned and I'm going to approve this in a bit. Thanks for your patience!

**Review by SarahFrench — APPROVED** [review]
When I run the Beta version of the acceptance test including the new field everything passes. I can see that ordering of the field isn't important, and there isn't any trouble when re-ordering. I remembered there was an issue with Sets but not what - it's that schema.Set has trouble with Computed values. As that's not relevant here I'm happy to approve.

**Comment by SarahFrench** [comment]
@felipegc Sorry, my delay allowed the merge conflict above to happen. I'll keep an eye on this PR and will merge it once I see  it's resolved.

**Comment by felipegc** [comment]
> @felipegc Sorry, my delay allowed the merge conflict above to happen. I'll keep an eye on this PR and will merge it once I see it's resolved.

I updated my branch with the upstream/main and got no conflict to solve manually. But when I ran the provider beta with my test and other test from the same file I got a message saying: “no tests to run”. Is there anything changed recently to run the acc tests locally? Thanks

**Comment by SarahFrench** [comment]
> Is there anything changed recently to run the acc tests locally? 

Yes - that file has been migrated into a new package by [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/8572). The file was previously in ./google-beta but now it's in ./google-beta/services/compute. Are you using the Makefile to run acceptance tests, or using `go test` ?

**Comment by zli82016** [comment]
If the tests are moved to the specific service packages, the command to run the tests needs to change. For example:  `make testacc TEST=./google-beta/services/compute  TESTARGS='-run=TestAccComputeAddress_withProviderDefaultLabels'`

**Comment by felipegc** [comment]
Thanks @SarahFrench and @zli82016. I managed to successfully run locally with the explanation.

**Review by SarahFrench — APPROVED** [review]
Re-approving after merge conflict resolved - sorry for the confusion!

**Pull request merged**
