### PR TITLE
Run MM tests in parallel to create-prs

### PR DESCRIPTION
**Pull request by rileykarson**
Not too familiar with editing this part of the Magician; does that look like all it takes to run the tests in parallel & are https://github.com/GoogleCloudPlatform/magic-modules/tree/master/.ci#deploying-the-pipeline the instructions to deploy this?

-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by slevenick** [comment]
Looks right to me! I think there will be race conditions though, as the tests put a failure status on the github PR and create-prs puts a success status. I imagine whichever finishes last will win out, which will likely be create-prs.

I'm sure there is a way to fix this, maybe move the success update to a separate job and make it depend on both test steps?

**Comment by rileykarson** [comment]
Yeah I was wondering about the race conditions as well; I was thinking I want to test to see whether they occur or not by pushing the pipeline and intentionally breaking `terraform-tests` to see if it behaves like that, or if an error trumps a success.

**Comment by rambleraptor** [comment]
Yeah, I've got the same concerns Sam does. I'm not entirely sure how Concourse reports GH status. It would be great if you could do some kind of test (which wouldn't involve needing to merge this PR because it's just a pipeline change)

**Comment by rambleraptor** [comment]
What's the status on this?

**Comment by rileykarson** [comment]
I need to actually run the `fly` commands to test this, I haven't blocked off time to do that yet though.

**Comment by rileykarson** [comment]
This change is applied to our pipelines; here's what a failure looks like: https://github.com/GoogleCloudPlatform/magic-modules/pull/1768

Concourse reports a separate failure status when a test fails.

Looking for review for 👍 now @rambleraptor

**Pull request merged**
