### PR TITLE
Add support for domainNames to Service Attachment

### PR DESCRIPTION
**Pull request by falfaro**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/11612

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:enhancement
compute: added support for `domain_names` attribute in `google_compute_service_attachment`
```

For the record, I _did_ run `make lint` which failed with many errors which I believe to be unrelated to mu change.

### CODE REVIEW

**Review by shuyama1 — CHANGES_REQUESTED** [review]

**Comment by falfaro** [comment]
@shuyama1 PTAL

**Comment by falfaro** [comment]
Any chance I could get permissions to look at the build and debug logs to troubleshoot why two tests failed?

**Comment by falfaro** [comment]
For the record, the `TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample` test is unrelated to my change.

**Comment by shuyama1** [comment]
```
=== CONT  TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating ServiceAttachment: googleapi: Error 400: Invalid value for field 'resource.domainNames': ''. Please verify ownership of the PTR domain at https://www.google.com/webmasters/verification/verification?domain=hashicorptest.com., invalid
        
          on terraform_plugin_test.tf line 2, in resource "google_compute_service_attachment" "psc_ilb_service_attachment":
           2: resource "google_compute_service_attachment" "psc_ilb_service_attachment" {
        
        
--- FAIL: TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample (97.94s)
=== CONT  TestAccComputeServiceAttachment_serviceAttachmentBasicExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating ServiceAttachment: googleapi: Error 400: Invalid value for field 'resource.domainNames': ''. Please verify ownership of the PTR domain at https://www.google.com/webmasters/verification/verification?domain=hashicorptest.com., invalid
        
          on terraform_plugin_test.tf line 2, in resource "google_compute_service_attachment" "psc_ilb_service_attachment":
           2: resource "google_compute_service_attachment" "psc_ilb_service_attachment" {
        
        
--- FAIL: TestAccComputeServiceAttachment_serviceAttachmentBasicExample (98.02s)
```

@falfaro Sorry that I can't grant your access to the logs. I just copied the errors above. Looks like the error is still related to the ownership of the domains. Let me look into it. Sorry about it!

**Comment by falfaro** [comment]
For the record,

```
$ nslookup -query=ptr hashicorptest.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
*** Can't find hashicorptest.com: No answer

Authoritative answers can be found from:
hashicorptest.com
	origin = kara.ns.cloudflare.com
	mail addr = dns.cloudflare.com
	serial = 2275801625
	refresh = 10000
	retry = 2400
	expire = 604800
	minimum = 3600
```

**Comment by falfaro** [comment]
And for the record, I've changed the DNS domain to be `gcp.tfacc.hashicorptest.com`, which seems to be a Cloud DNS domain:

```
$ nslookup -query=ptr gcp.tfacc.hashicorptest.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
*** Can't find gcp.tfacc.hashicorptest.com: No answer

Authoritative answers can be found from:
gcp.tfacc.hashicorptest.com
	origin = ns-cloud-e1.googledomains.com
	mail addr = cloud-dns-hostmaster.google.com
	serial = 1
	refresh = 21600
	retry = 3600
	expire = 259200
	minimum = 300
```

**Comment by falfaro** [comment]
@shuyama1 I tried to change the DNS domain to `gcp.tfacc.hashicorptest.com` that I found in other tests, to no avail. VCR tests keep failing :-(

**Comment by shuyama1** [comment]
@falfaro Thanks for investigating the failing tests and making the changes! Looks like `gcp.tfacc.hashicorptest.com.` is the one we used in other test. I must have found `hashicorptest.com.` in an outdated PR and really sorry about it! It seems the tests passed in the most recent run and the failing test `TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample` seems unrelated to your change.

**Review by shuyama1 — APPROVED** [review]
Tests passed! LGTM! Thank you so much!

**Pull request merged**
