### PR TITLE
add Large Volumes support for netapp volumes

### PR DESCRIPTION
**Pull request by Mehul3217**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
netapp: added `large_capacity` and `multiple_endpoints` to `google_netapp_volume` resource
```

### CODE REVIEW

**Review by zli82016 — CHANGES_REQUESTED** [review]
Do you mind adding adding a create test and a update test for the new fields?

Doc: https://googlecloudplatform.github.io/magic-modules/develop/test/test/#before-you-begin

**Comment by zli82016** [comment]
Also, the conflicts need to be resolved.

**Comment by Mehul3217** [comment]
> Do you mind adding adding a create test and a update test for the new fields?
> 
> Doc: https://googlecloudplatform.github.io/magic-modules/develop/test/test/#before-you-begin

Creating Large Volume is a high resource intensive process and by nature of design of this feature it limits the total number of large volumes for a particular region which will restrict the user if we add tests for this.

We already have this feature in Terraform EAP provider which is shared with customers and working fine.

**Comment by Mehul3217** [comment]
> Also, the conflicts need to be resolved.

Done

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks for working on this.

**Pull request merged**
