### PR TITLE
promoting `google_parallelstore_instance` to ga

### PR DESCRIPTION
**Pull request by unnatinadupalli**
**Promoting Parallelstore to GA.**

```release-note: enhancement
parallelstore: promoted `google_parallelstore_instance` to GA
```

### CODE REVIEW

**Review by SarahFrench — CHANGES_REQUESTED** [review]
Hi, thanks for your PR! Could you please address the open merge conflicts, as this will interfere with the usual automation to run tests on your PR

**Comment by unnatinadupalli** [comment]
Hello Sarah i am not able to resolve the conflicts as that option is disable for me 
image

**Comment by SarahFrench** [comment]
That means that the conflict isn't simple enough to resolve through the GitHub UI and instead you'd need to resolve them locally. GitHub has some documentation about this here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

Let me know if you'd like to address the merge conflicts using that guidance or whether it's ok for me to resolve them and make a to push to your branch.

**Comment by unnatinadupalli** [comment]
> That means that the conflict isn't simple enough to resolve through the GitHub UI and instead you'd need to resolve them locally. GitHub has some documentation about this here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line
> 
> Let me know if you'd like to address the merge conflicts using that guidance or whether it's ok for me to resolve them and make a to push to your branch.

Hello Sarah! i tried to address this but I am not able to do so. would it be possible for you to resolve the conflicts?

**Comment by SarahFrench** [comment]
I just rebased your branch so that it's based on the latest commit on `main`, addressed conflicts, and force-pushed. Your branch originally predated a recent rewrite of our code generator from Ruby to Go (https://github.com/GoogleCloudPlatform/magic-modules/pull/11814) so there were some diffs in `mmv1/products/parallelstore/Instance.yaml` that I had to drop. Here's a screenshot of what they were (only 2 lines had diffs):

Screenshot 2024-11-12 at 19 46 51

**Review by SarahFrench — CHANGES_REQUESTED** [review]
Please update `mmv1/products/parallelstore/Instance.yaml` following https://googlecloudplatform.github.io/magic-modules/develop/promote-to-ga/#promote-fields-and-resources, following my rebase to address merge conflicts

**Comment by unnatinadupalli** [comment]
Thanks Sarah! i have added the changes to instance.yaml

**Review by SarahFrench — COMMENTED** [review]
The most recent test failure is in a test generated from this example file: mmv1/templates/terraform/examples/parallelstore_instance_basic.tf.tmpl

That file currently still includes `provider = google-beta` lines that need to be removed

**Comment by unnatinadupalli** [comment]
@SarahFrench Thanks! I removed them.

**Review by SarahFrench — APPROVED** [review]
Thanks, everything looks good and the tests pass when they're run with the GA version of the provider. Merging!

**Pull request merged**
