### PR TITLE
Promoting Managed Kafka Cluster and Topic resources to GA

### PR DESCRIPTION
**Pull request by jessdejong**
https://b.corp.google.com/issues/371049718

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-resource
`google_managed_kafka_cluster` and `google_managed_kafka_topic` (ga)
```

### CODE REVIEW

**Comment by jessdejong** [comment]
Hi! Our GA is technically November 12th. Is it possible to submit this before that date? Our beta and GA endpoints are the same.

**Comment by SarahFrench** [comment]
Review note: [GA testing here](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_MANAGEDKAFKA/262351?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true)

---

>Hi! Our GA is technically November 12th. Is it possible to submit this before that date? Our beta and GA endpoints are the same.

Hi @jessdejong - we can get this merged today, assuming the tests pass etc, but it's too late to be included in the release scheduled for Monday 11th Nov. [The only changes that we would cherry-pick into a prepared release](https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process#when-to-cherry-pick) are bug fixes. I'm afraid this PR's changes would need to go out in the release on November 18th.

**Review by SarahFrench — CHANGES_REQUESTED** [review]
I'm seeing a problem running the test `TestAccManagedKafkaCluster_managedkafkaClusterCmekExample` with the GA provider:

```
------- Stdout: -------
=== RUN   TestAccManagedKafkaCluster_managedkafkaClusterCmekExample
=== PAUSE TestAccManagedKafkaCluster_managedkafkaClusterCmekExample
=== CONT  TestAccManagedKafkaCluster_managedkafkaClusterCmekExample
    resource_managed_kafka_cluster_generated_test.go:94: Step 1/2 error: Error running pre-apply refresh: exit status 1
        Error: Invalid resource type
          on terraform_plugin_test.tf line 20, in resource "google_project_service_identity" "kafka_service_identity":
          20: resource "google_project_service_identity" "kafka_service_identity" {
        The provider hashicorp/google does not support resource type
        "google_project_service_identity".
--- FAIL: TestAccManagedKafkaCluster_managedkafkaClusterCmekExample (1.68s)
FAIL
```

The `google_project_service_identity` resource is only in the Beta provider, so that test will need to use google-beta still. I believe that to solve this you just need to re-add `min_version: 'beta'` to the example named `managedkafka_cluster_cmek` in mmv1/products/managedkafka/Cluster.yaml.

**Comment by jessdejong** [comment]
Hi @SarahFrench, thanks for letting me know about the releases. Given that we can not make it into the Monday release, I would like to still get this in ASAP so that we can be a part of the following release. Thanks!

Also -- I'm curious where you're seeing that the CMEK test is failing. Based on [this issue cmoment](https://github.com/GoogleCloudPlatform/magic-modules/pull/12264#issuecomment-2460646174), it looks like all of the GA tests are passing.

But anyway, I took your advice and added the `beta` min_version to the Cluster.yaml file and I'll wait to see if the tests pass. Would I also have to add the `provider = google-beta` line back into the `mmv1/templates/terraform/examples/managedkafka_cluster_cmek.tf.tmpl` file?

**Comment by jessdejong** [comment]
Ok, looks like we have a new error on the CMEK test:

```
Error: Inconsistent dependency lock file
  | 
  | The following dependency selections recorded in the lock file are
  | inconsistent with the current configuration:
  |   - provider registry.terraform.io/hashicorp/google: required by this configuration but no version is selected
```

I'm going to try and add `provider = google-beta` back into the cmek test example to try and address this issue.

**Comment by SarahFrench** [comment]
>Hi @SarahFrench, thanks for letting me know about the releases. Given that we can not make it into the Monday release, I would like to still get this in ASAP so that we can be a part of the following release. Thanks!
>
>Also -- I'm curious where you're seeing that the CMEK test is failing. Based on https://github.com/GoogleCloudPlatform/magic-modules/pull/12264#issuecomment-2460646174, it looks like all of the GA tests are passing.
>
>But anyway, I took your advice and added the beta min_version to the Cluster.yaml file and I'll wait to see if the tests pass. Would I also have to add the provider = google-beta line back into the mmv1/templates/terraform/examples/managedkafka_cluster_cmek.tf.tmpl file?

Hi! On our PRs we run all the automated tests with the Beta version of the provider. I believe that comment is highlighting to the reviewer that those tests have newly been added to the GA provider code but require manual testing as while they pass for the Beta provider the aren't guaranteed to also pass for the GA provider. You won't be able to access this, but [I ran the tests here using the GA provider code ](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_MANAGEDKAFKA/262351?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildChangesSection=true)and saw the error.

I'll double check your latest changes

**Comment by jessdejong** [comment]
I'm unfortunately not able to access the team city link. Can you let me know when/if the tests complete?

**Comment by jessdejong** [comment]
Hi @SarahFrench, were there any failures on the manual tests?

**Comment by SarahFrench** [comment]
The tests all passed, and the TestAccManagedKafkaCluster_managedkafkaClusterCmekExample test is still Beta-only as needed

**Review by SarahFrench — APPROVED** [review]

**Pull request merged**
