### PR TITLE
TF Add Resource Settings - google_organization_resource_setting

### PR DESCRIPTION
**Pull request by nstogner**
Add terraform support for the resource settings API.

Adding a single `google_organization_resource_setting` resource at this time. This is the only level at which resource settings can be set currently. This is due to a restriction in the `roles/resourcesettings.admin` role: "Lowest-level resources where you can grant this role: - Organization". (https://cloud.google.com/iam/docs/understanding-roles#resource-settings-roles).

Once the `folder` and `project` levels are supported I think it makes sense to add and test the corresponding `google_<level>_resource_setting` resources.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/11016

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_organization_resource_setting`
```

### CODE REVIEW

**Comment by nstogner** [comment]
Looking for a thorough review of this PR. This is the first new resource I have added. Open to feedback, especially around bolstering test coverage.

Note: Supporting multiple resource parent types as different tf resource types (as discussed in tf issue) got kind of awkward (`switch parentType ...`).

**Comment by melinath** [comment]
gotcha - it might be possible to instead use a `custom_delete` to only have the deletion portion be custom. if you search for that string in the `products` folder there are a number of examples - it involves setting up a terraform.yaml file in addition to an api.yaml file. Could you take a look and see if that might work for your case?

**Comment by rileykarson** [comment]
I can't recall, sorry! If this fits in the generator that would be preferred, although handwritten is acceptable if it won't.

Skipping deletion with `skip_delete` is also an acceptable behaviour fwiw (different settings resources do different things- some set to zero, others skip)

**Comment by rileykarson** [comment]
Revisiting the original discussion about targeting third_party: I may have misspoke, and commented on DCL vs MMv1 rather than on `third_party` over the MMv1 generator. The original thread was about an MMv1 config generator that never worked.

Original message:

```
Got it - so noting that this set of resources (Cloud Resource Manager Settings) aren't covered in the DCL repo yet, is the way forward to simply write out the resources fully in mmv1/third_party/terraform/resources?
```

```
Yep!
```

**Comment by melinath** [comment]
Okay, thanks @rileykarson for clarifying. @nstogner sorry for the rework, but it would definitely be better to put this in yaml and either use custom_delete (or skip_delete) to add the custom delete behavior.

If it turns out that there's some other requirement, it's much easier to go the other direction (since you can copy the generated code to Magic Modules).

**Comment by nstogner** [comment]
Do you have a guide of how to add a new API into mmv1?

**Comment by melinath** [comment]
if you have access, go/terraform-contribution-guide might be what you're looking for; otherwise, there's somewhat of a guide at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/README.md

**Comment by nstogner** [comment]
In short, do we look at the REST documentation, and manually construct the `api.yaml` file off of that? @melinath

**Comment by melinath** [comment]
@nstogner in short - yes

**Comment by nstogner** [comment]
Opened a new PR with code generation: https://github.com/GoogleCloudPlatform/magic-modules/pull/5861

**Pull request closed without merging**
