### PR TITLE
Compute instance reservation affinity

### PR DESCRIPTION
**Pull request by edwardsamuel**
Add `reservationAffinity` field into [Instances](https://cloud.google.com/compute/docs/reference/rest/v1/instances) and [InstanceTemplates](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates).

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `reservation_affinity` field to `google_compute_instance` resource
compute: added `reservation_affinity` field to `google_compute_instance_template` resource
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
Unfortunately, Instance and ComputeInstance are both handwritten resources for terraform (and we don't generate any other tools from Magic Modules) so you would need to make changes to the handwritten resources, tests, and docs.

For example, here's the compute instance resource: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/resources/resource_compute_instance.go.erb

**Comment by edwardsamuel** [comment]
Hi @melinath, it looks like the `reservation_affinity` for `google_compute_instance ` and `google_compute_instance_template` is available for Terraform as in #4335. My initial intention is to make it available to Ansible as well.
Do we need to have a manual edit on resources/tests/docs for Ansible?

**Comment by melinath** [comment]
Ah, gotcha. We're no longer using Magic Modules to generate the ansible provider. If you want to contribute ansible code I think you need to contribute that directly. I'm not sure where that code lives but I can find out if you don't know

**Comment by melinath** [comment]
@rambleraptor you might know what to do here.

**Comment by edwardsamuel** [comment]
Would be appreciated if someone can give some directions on how to update the Ansible module.

As per my understanding, https://github.com/ansible-collections/google.cloud committers is [modular-magician](https://github.com/ansible-collections/google.cloud/commits?author=modular-magician) only. We can backtrack the changes/PRs to this repo.

**Comment by melinath** [comment]
Up until recently, the ansible collection _was_ generated from magic-modules; however, we have not actually actively worked on ansible support for a long time, so we have stopped doing that generation. I think the alternative would be to make PRs against that repository directly. @rambleraptor may know more.

**Comment by melinath** [comment]
@rambleraptor do you have any insight on this?

**Review by kutysam — APPROVED** [review]

**Comment by edwardsamuel** [comment]
Any idea how to move forward the changes?

**Comment by edwardsamuel** [comment]
I saw there was a manual update: adding `private_network` to `gcp_sql_instance` (https://github.com/ansible-collections/google.cloud/pull/451) and merged by @rambleraptor.

Is my assumption correct: we don't maintain Ansible via this magic-module anymore, but we can submit a PR directly to the https://github.com/ansible-collections/google.cloud/?
cc @melinath

**Comment by rambleraptor** [comment]
I think that would be the best course of action.

**Comment by melinath** [comment]
Closing this as the question is resolved

**Pull request closed without merging**
