### PR TITLE
Promoting Memorystore to GA

### PR DESCRIPTION
**Pull request by himanikh**
**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-resource
`google_memorystore_instance` (ga)
```

### CODE REVIEW

**Comment by SirGitsalot** [comment]
I ran the GA tests manually and they passed with flying colors. LGTM, but with a nit I'd like to resolve first: please revert the single to double quote line changes in `Instance.yaml` (it's not that we particularly care about quote formatting, but it screws up the change history and makes future bug discovery harder).

**Comment by himanikh** [comment]
> I ran the GA tests manually and they passed with flying colors. LGTM, but with a nit I'd like to resolve first: please revert the single to double quote line changes in `Instance.yaml` (it's not that we particularly care about quote formatting, but it screws up the change history and makes future bug discovery harder).

Yeah, this was all auto formatter's doing. Reverted the Instance.yaml to single quotes.

**Review by SirGitsalot — APPROVED** [review]
Re-ran the tests manually, they again passed. LGTM!

**Pull request merged**
