### PR TITLE
Added end-to-end external HTTP LB example with custom headers

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Intending to add this example to this page:

https://cloud.google.com/load-balancing/docs/https/ext-http-lb-tf-module-examples
Will also include on a new TF page in https://cloud.google.com/cdn/docs/.

```release-note:none
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
hi @betsy-lichtenberg , if you want to get on a call to understand how to run these locally or any help let me know.

**Comment by betsy-lichtenberg** [comment]
> hi @betsy-lichtenberg , if you want to get on a call to understand how to run these locally or any help let me know.

Great, thanks.. I sent you an invite.

**Comment by ScottSuarez** [comment]
hmm this failure is strange /gcbrun - lets try again

**Comment by ScottSuarez** [comment]
pushed a change that should finally resolve this

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
