### PR TITLE
Network queue count support

### PR DESCRIPTION
**Pull request by slevenick**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/9847

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added support for `queue_count` to `google_compute_instance.network_interface` and `google_compute_instance_template.network_interface`
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
This seems reasonable. The failing tests in VCR seem unrelated. It looks like it breaks the TFV downstream; it's possible that updating the downstream tests to include this field new field in their test data might be sufficient but it may be that we need to update the TPG dependency downstream (in which case we would have to merge this first and update afterward.

It would be great if you could try to get the downstream working prior to merge.

**Comment by slevenick** [comment]
> This seems reasonable. The failing tests in VCR seem unrelated. It looks like it breaks the TFV downstream; it's possible that updating the downstream tests to include this field new field in their test data might be sufficient but it may be that we need to update the TPG dependency downstream (in which case we would have to merge this first and update afterward).
> 
> It would be great if you could try to get the downstream working prior to merge.

Upgrading the version of TPG seems to fix it:
```--- FAIL: TestReadPlannedAssetsCoverage (0.00s)
    --- PASS: TestReadPlannedAssetsCoverage/example_storage_bucket (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/full_spanner_instance (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_access_context_manager_service_perimeter (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_pubsub_topic (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_filestore_instance (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/full_container_node_pool (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/full_sql_database_instance (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/full_storage_bucket (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_storage_bucket_iam_policy (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_storage_bucket_iam_member_random_suffix (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_iam (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_storage_bucket_iam_binding (0.04s)
    --- FAIL: TestReadPlannedAssetsCoverage/full_container_cluster (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/full_compute_firewall (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/example_storage_bucket_iam_member (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/full_compute_instance (0.06s)
    --- PASS: TestReadPlannedAssetsCoverage/example_sql_database_instance (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_iam_member (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_key_ring_iam_member (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_organization_iam_binding (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_key_ring_iam_policy (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_service (0.06s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_iam_policy (0.06s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_iam_binding (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_key_ring_iam_binding (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_key_ring (0.02s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_in_org (0.02s)
    --- PASS: TestReadPlannedAssetsCoverage/example_organization_iam_policy (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_organization_iam_member (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_crypto_key_iam_member (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_crypto_key_iam_policy (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_disk_empty_image (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/example_container_cluster (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_global_forwarding_rule (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_network (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_subnetwork (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_firewall (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_in_folder (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_pubsub_subscription (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_compute_disk (0.02s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_crypto_key (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_kms_crypto_key_iam_binding (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_bigquery_dataset_iam_policy (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_update (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_bigquery_dataset_iam_binding (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_bigtable_instance (0.04s)
    --- PASS: TestReadPlannedAssetsCoverage/example_bigquery_dataset (0.03s)
    --- PASS: TestReadPlannedAssetsCoverage/example_bigquery_dataset_iam_member (0.05s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_create (0.02s)
    --- PASS: TestReadPlannedAssetsCoverage/example_project_organization_policy (0.03s)```

Container cluster test seems to fail, but that has to be unrelated to this PR.

**Comment by melinath** [comment]
@slevenick great! 👍 would you like to make the downstream PR to do the upgrade? It basically requires adding a commit like https://github.com/hashicorp/terraform-provider-google/commit/61e7a7931bce5c44d3b423ea18e3b4825fc5f773 to a fork of the release branch you want to upgrade to, then using `go get` to install that forked branch in TFV

**Comment by slevenick** [comment]
> @slevenick great! 👍 would you like to make the downstream PR to do the upgrade? It basically requires adding a commit like [hashicorp/terraform-provider-google@61e7a79](https://github.com/hashicorp/terraform-provider-google/commit/61e7a7931bce5c44d3b423ea18e3b4825fc5f773) to a fork of the release branch you want to upgrade to, then using `go get` to install that forked branch in TFV

Yeah, I can do that. It requires merging this PR first and then making the release & upgrading TFV right?

**Review by melinath — APPROVED** [review]
yes, you'd have to fix the downstream after the next release (or at least after the next release is cut) so this would need to be merged first.

**Pull request merged**
