### PR TITLE
Remove old tools (Ansible, InSpec) from the Magician

### PR DESCRIPTION
**Pull request by rileykarson**
Part of https://github.com/hashicorp/terraform-provider-google/issues/9588

I believe I can roll forward this change without updating the `downstream-builder` image as the behaviour is opt-in, although I've cleaned it up for the next rebuild. I will update `github-differ` prior to merging, but haven't yet. That will mean:

* Old PRs will continue to work, generating downstreams, but those changes will never get synced or commented about
* New PRs, or PRs that rebase will no longer generate downstreams

When we next rebuild `downstream-builder`, old PRs that have not rebased will report an unrecognized repo error, but there will be less of them. We could also rebuild now, but that'll cause a lot more noise.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Review by ndmckinley — APPROVED** [review]
Yeah, I basically believe in this!  LGTM, give it a whirl.

**Comment by rileykarson** [comment]
(TIL `generate-diffs` doesn't do anything if you only change `.ci/`!)

**Comment by rileykarson** [comment]
Made it to VCR, good enough for me!

**Pull request merged**
