### PR TITLE
Reduce logging output to a reasonable level for tfv

### PR DESCRIPTION
**Pull request by ScottSuarez**
Reducing volume of logs for tfv

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]
Does this capture one or both debug logs and error logs? Are they output to stdin?

Also, with this approach it is fairly unlikely that folks will retrieve the logs- is it much different than piping them to `/dev/null`? I'd be a little more inclined to take an approach that reduces the log volume, like omitting debug logs and only including error ones. Deferring to @melinath's judgement on what path is preferred for TFV, either approach is fine to get back error logs for TPG/TPGB.

**Comment by ScottSuarez** [comment]
hmm maybe we could complete this to unblock right away and create a new task for Iris on reducing log volume or only emitting failed instances? Then this would be a stopgap for now.

**Comment by ScottSuarez** [comment]
Looking into it... Seems like the tests /were/ designed in this way... **ie only emit when failing**.. I'm guessing component functions called behaving erroneously.

**Comment by ScottSuarez** [comment]
@melinath 

Sure, I'll take a look today. It should be easy if we switch the logging to be an interface that we initialize per test.

**Comment by ScottSuarez** [comment]
I've updated the pr with a new strategy.

This in combination with https://github.com/GoogleCloudPlatform/terraform-validator/pull/453 will greatly reduce the volume of logs written to stdout.

**Comment by ScottSuarez** [comment]
Thanks for your patience on this ^-^

**Review by melinath — APPROVED** [review]
LGTM - this is a great improvement for reducing log verbosity!

**Pull request merged**
