### PR TITLE
Run rubocop and MM rspec test on every PR using travis

### PR DESCRIPTION
**Pull request by rosbo**
-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by rosbo** [comment]
Rubocop and the rspec tests are failing as expected. We should fix them (Alex PR should fix the Ansible failures) and aim to keep it green.

**Comment by rosbo** [comment]
It is very easy to do in travis. It keeps our concourse pipeline simpler. We also get this "Details" button that allows us to see quickly why it is failing.

**Comment by ndmckinley** [comment]
I would like to migrate it to concourse eventually but this is super easy and we're all pretty busy.

**Comment by rosbo** [comment]
I think I prefer to keep it in TravisCI. This allow external contributor access to the logs on why the tests failed.

**Comment by ndmckinley** [comment]
That's a good point I hadn't considered.

**Comment by rambleraptor** [comment]
Nice thinking Vincent. Agree 100%

**Pull request merged**
