### PR TITLE
Add annotations for cloudrunV2_service

### PR DESCRIPTION
**Pull request by hao-nan-li**
Add annotations for cloudrunV2_service
https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services#RevisionTemplate

* Add traffic percent=100 in the test to fit API required fields
* Change traffic tag to a shorter string because the length of it + length of service account name can't exceed 46 chars.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrunV2: added `annotations` to `CloudRunV2_service` resource
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Code looks good! I've got two comments:
1. Would you mind adding update step to test the update functionality of this field? Plus, I'd recommend we modify the existing test `TestAccCloudRunV2Service_cloudrunv2ServiceFullUpdate` instead of adding a new acceptance test `TestAccCloudRunV2Service_cloudrunv2ServiceFullBasic`, since it should be a simple test.
2. The error you ran into earlier
```
error=
  | After applying this test step, the plan was not empty.
  | stdout:
  | 
  | 
  | Terraform used the selected providers to generate the following execution
  | plan. Resource actions are indicated with the following symbols:
  |   ~ update in-place
  | 
  | Terraform will perform the following actions:
  | 
  |   # google_cloud_run_v2_service.default will be updated in-place
  |   ~ resource "google_cloud_run_v2_service" "default" {
  |         id                      = "projects/terraform-test-project-361017/locations/us-central1/services/tf-test-cloudrun-serviceaemnh7go3v"
  |         name                    = "tf-test-cloudrun-serviceaemnh7go3v"
  |         # (16 unchanged attributes hidden)
  | 
  |       ~ template {
  |           ~ annotations                      = {
  |               + "run.googleapis.com/startup-cpu-boost" = "true"
  |             }
```
happens when you try to add a v1 system annotations (annotations starting with `run.googleapis.com/`), as v2 API currently swallows these annotations, then it causes perma-diff in Terraform. Therefore, the annotations field is omitted from the initial implementation of this resource.
There’s an internal ticket (b/244872932) tracking the fix of this bug. Looks like it’s marked as fixed, however, I wonder if the fix is already released (doesn’t look like it is, otherwise it should error out for any v1 annotations). Would you mind confirming with the service team if the validation is released?

**Comment by hao-nan-li** [comment]
Thanks @shuyama1 for the review. 

1. Sure will do.
2. Sure I will leave a comment on the ticket to track for update. If for any reason the bug is not 100% fixed, do we temporarily don't support v1 system annotations?

**Review by shuyama1 — COMMENTED** [review]
I tested it locally with v1 system annotations and still got the same permadiff as before. If the validation is fully released, my understanding is it should error out instead of secretly drop the annotations. Were you able to get it work locally?

**Comment by hao-nan-li** [comment]
> I tested it locally with v1 system annotations and still got the same permadiff as before. If the validation is fully released, my understanding is it should error out instead of secretly drop the annotations. Were you able to get it work locally?

I was not able to get it work locally, I got the error you've listed in the previous comment.

**Review by shuyama1 — APPROVED** [review]
LGTM assuming it's tested locally and confirmed that v1 system annotation is rejected!

**Pull request merged**
