### PR TITLE
Composer 3 GA: Reintroduce changes

### PR DESCRIPTION
**Pull request by spapi17**
**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-datasource
`google_composer_user_workloads_config_map` (GA)
```
```release-note:new-datasource
`google_composer_user_workloads_secret` (GA)
```
```release-note:new-resource
`google_composer_user_workloads_config_map` (GA)
```
```release-note:new-resource
`google_composer_user_workloads_secret` (GA)
```
```release-note:enhancement
composer: added multiple composer 3 related fields to `google_composer_environment` (GA)
```

This PR reintroduces changes that were previously approved, but merged too early and subsequently reverted: https://github.com/GoogleCloudPlatform/magic-modules/pull/12234.

***Please do not merge yet.*** We'd like to have it approved and ready but align the release of this with composer 3 GA rollout scheduled for first half of December.

### CODE REVIEW

**Comment by shuyama1** [comment]
Running GA tests on [TeamCity](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_COMPOSER/270255?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true)

**Review by shuyama1 — COMMENTED** [review]
@spapi17 The change looks good to me. I'll hold off on merging the PR for now. Please let me know when I should merge the PR. Thanks!

**Comment by spapi17** [comment]
Thank you!

**Review by shuyama1 — APPROVED** [review]
Please ping me when it's ready to be merged. Thanks!

**Pull request merged**
