### PR TITLE
gke_backup_agent_config: support from beta to ga

### PR DESCRIPTION
**Pull request by kkram01**
This PR is support the documentation for gke_backup_agent_config. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1450

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written  "part of {[gke backup agent config](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1450)}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**
```release-note:enhancement
container: promoted `gke_backup_agent_config` in `google_container_cluster` to GA
```

### CODE REVIEW

**Review by roaks3 — CHANGES_REQUESTED** [review]
Overall looks good, I just noticed two things that should be changed:

1. I think your release notes are a bit more verbose than we need for this change (see https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md#release-note-style-guide-terraform-specific). I would reduce it to just `container: support the gke_backup_agent_config in ga from beta in 'google_container_cluster'`
2. I think there are tests that need to be updated too, so that this field is tested in the GA version of the provider. Namely, `mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb`.

**Comment by kkram01** [comment]
@roaks3 Thanks for pointing that out. Updated the tests and release notes

**Comment by roaks3** [comment]
@kkram01 I tweak the format of the release note to closer match other GA promotions in the changelog

**Review by roaks3 — APPROVED** [review]

**Comment by rileykarson** [comment]
Linked a related issue in the parent- the issue didn't exist @ PR creation time. It doesn't completely close the issue, so I didn't apply `Fixes: `.

**Pull request merged**
