### PR TITLE
remove compute API usage in third_party/validator/compute_instance.go

### PR DESCRIPTION
**Pull request by yukinying**
# Release Note for Downstream PRs (will be copied)
```releasenote

```

### CODE REVIEW

**Comment by danawillow** [comment]
Thanks @yukinying! Could you also make these changes in third_party/terraform/resources/resource_compute_instance.go? From what I understand, the expanders in the two files should be identical.

**Comment by yukinying** [comment]
I don't have a ruby dev environment handy so the changes on 3301427 are not tested. The previous one I have is already teared down. I planned to setup one again and test it. If the travis-ci test is reliable then I may skip the integration test in my local env.

**Comment by danawillow** [comment]
Ok! I'm starting off a magician run, which will generate the downstreams. That'll also tell us whether the code builds. From there, I can run one of the existing tests to confirm that this works (I don't think it merits any new ones).

**Comment by danawillow** [comment]
Looks like the generated code doesn't build: https://travis-ci.org/terraform-providers/terraform-provider-google-beta/builds/571997297?utm_source=github_status&utm_medium=notification

**Comment by yukinying** [comment]
I have update the code last night. PTAL. Thanks!

**Pull request merged**
