### PR TITLE
[terraform-conversions] Manually add storage_bucket to conversions library

### PR DESCRIPTION
**Pull request by nstogner**
Add `storage_bucket` to conversion library by manually adding `storage_bucket.go` to `third_party/validator/`. The code to build up the resource was pieced together from the provider `Create` function.

### CODE REVIEW

**Comment by nstogner** [comment]
@chrisst

**Comment by chrisst** [comment]
Ping me when you've resolved the conflicts and I'll rerun the build.

**Comment by nstogner** [comment]
Can we merge this one? Looks like its already merged downstream.

**Comment by chrisst** [comment]
Looks like when I tried to merge Friday the job failed :( Failure looks transient though so fingers crossed

**Pull request merged**
