### PR TITLE
♻️ Make Logging Sink resources work with auto-created sinks

### PR DESCRIPTION
**Pull request by estliberitas**
♻️ Make Logging Sink resources work with auto-created sinks

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement

```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Hi @estliberitas 

This pull request is difficult to review. Is there any way you can split this up into smaller more deliberate incrementations so the scope of the change is easier to understand?

**Comment by estliberitas** [comment]
@ScottSuarez maybe I will first explain the context and scope of work that was done here.

First of all, here is an original issue:
https://github.com/hashicorp/terraform-provider-google/issues/7811.

I looked at how the same issue is solved for Log Bucket resources: [here](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_logging_bucket_config.go#L123-L139). Also I noted the way parent-specific Log Bucket resources are organized: [here](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_logging_bucket_config.go#L51-L65) and, for example, [here](https://github.com/hashicorp/terraform-provider-google/blob/25e1e8a570743076acf2cf3f0e3f0a2148db7443/google/resource_logging_billing_account_bucket_config.go#L32-L35). Basically, we can see a function which generates a Terraform resource and accepts some params in order to modify the behaviour of a result Terraform resource. This way we keep parent-specific resources slim, because all the mechanics exists in [`resource_logging_bucket_config.go`](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_logging_bucket_config.go).

I thought about the same option for Logging Sink resources. But in case of those, there are more moving parts, which differ between parent-specific resources. Hence, I provided a bunch of APIs, which account for CRUD operations and serialization / deserialization of objects, which can be re-used and extended/wrapped for the parent-specific resources.

Now, thinking about this, I realize that maybe we can simplify a lot of this stuff by just updating Create functions for each parent-specific resource... 🤔

**Comment by ScottSuarez** [comment]
Let me know if you would like to make changes to simplify, if you feel that is the right way to go. Otherwise I'll try to give this some attention tomorrow

**Comment by estliberitas** [comment]
@ScottSuarez I now think it makes sense to have it simplified. So yeah, gimme some time, I will refine this PR into something nicer. And we can close this one for now.

**Comment by ScottSuarez** [comment]
sure, feel free to ping me on the new pr when it is ready

**Pull request closed without merging**
