### PR TITLE
Adding route policies support to Router

### PR DESCRIPTION
**Pull request by harshithpatte-g**
This PR adds support for export_policies and import_policies on BGP peer in Router resource.
API to create a route policy: https://cloud.google.com/compute/docs/reference/rest/beta/routers/updateRoutePolicy
API to add import and export policies to BGP peer: https://cloud.google.com/compute/docs/reference/rest/beta/routers/update

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_compute_router_route_policy`
```

```release-note:enhancement
compute: added `export_policies` and `import_policies` fields  to `google_compute_router_peer` resource
```

### CODE REVIEW

**Review by hao-nan-li — CHANGES_REQUESTED** [review]
Could you add the missing test based on the comments in the PR?

Also for the build error, I don't think `provider = google-beta` is necessary in the TF config under the resource block

**Comment by harshithpatte-g** [comment]
> Could you add the missing test based on the comments in the PR?
> 
> Also for the build error, I don't think `provider = google-beta` is necessary in the TF config under the resource block

The new resource and fields are only available in beta apis. 
Would that not be a problem if I remove it?

**Comment by hao-nan-li** [comment]
> > Could you add the missing test based on the comments in the PR?
> > Also for the build error, I don't think `provider = google-beta` is necessary in the TF config under the resource block
> 
> The new resource and fields are only available in beta apis. Would that not be a problem if I remove it?

That would not be a problem, you are using a test framework that handles it already.

**Comment by harshithpatte-g** [comment]
> Tests failed during RECORDING mode: `TestAccComputeRouterPeer_addImportAndExportPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/build-log/recording_build/TestAccComputeRouterPeer_addImportAndExportPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/recording/TestAccComputeRouterPeer_addImportAndExportPolicy.log)] `TestAccComputeRouterRoutePolicy_routerRoutePolicyExportExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/build-log/recording_build/TestAccComputeRouterRoutePolicy_routerRoutePolicyExportExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/recording/TestAccComputeRouterRoutePolicy_routerRoutePolicyExportExample.log)] `TestAccComputeRouterRoutePolicy_routerRoutePolicyImportExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/build-log/recording_build/TestAccComputeRouterRoutePolicy_routerRoutePolicyImportExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/recording/TestAccComputeRouterRoutePolicy_routerRoutePolicyImportExample.log)]
> 
> Errors occurred during RECORDING mode. Please fix them to complete your PR.
> 
> View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11158/artifacts/12efab98-6d5d-47d4-a105-0d13d53dac33/recording) for each test

@hao-nan-li I was facing the same error locally when provider = google-beta was not added. 
Let me know if I need to add it back. 

Because we are using beta provider factories in the test, I suppose we need to mention the resource to use beta provider.

**Comment by hao-nan-li** [comment]
Here's the error mesage: `--- FAIL: TestAccComputeRouterPeer_addImportAndExportPolicy (0.00s)
    vcr_utils.go:152: Test validation error: TestStep 1/1 validation error: Providers must be specified at the TestCase level or in all TestStep
FAIL`

Could you double-check for that test cases, provider is mentioned in all steps?

**Comment by harshithpatte-g** [comment]
> Here's the error mesage: `--- FAIL: TestAccComputeRouterPeer_addImportAndExportPolicy (0.00s) vcr_utils.go:152: Test validation error: TestStep 1/1 validation error: Providers must be specified at the TestCase level or in all TestStep FAIL`
> 
> Could you double-check for that test cases, provider is mentioned in all steps?

I guess it is because the beta provider test was generated for GA repo as well and failed. 
I have added conditions to the test, it should not run against the GA repo.

**Review by hao-nan-li — APPROVED** [review]
LGTM.

Next time it would be great to split this into 2 different PRs, one for adding the new resource, the other for the new fields.

**Pull request merged**
