### PR TITLE
Add session affinity v2

### PR DESCRIPTION
**Pull request by kminsu-google**
Cloud Run V2 API just added a support for session affinity by adding a boolean field to control it.
Adding the same field to be supported in Terraform for Cloud Run V2
Part of https://github.com/hashicorp/terraform-provider-google/issues/13748

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrunv2: added support for `session_affinity` to `google_cloud_run_v2_service`
```

### CODE REVIEW

**Comment by kminsu-google** [comment]
Note on failing tests:
TestAccCloudRunV2Service_cloudrunv2ServiceFullUpdate -> I totally thought our rollout (for Cloud Run) for this week has completed, just checked and us-central1 only has part of the cells with new binary (that has this field change). Sorry about this. I believe the test should pass if re-run after the rollout is done.

TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey -> Not quite sure of this test. There's not point any error occured, and it says "resource_container_cluster_test.go:3065: Stopping the test because a role was added to the policy." and it's marked failure. I can check with my teammates if they are aware of this issue, but also please let me know if you have an idea why this test fails in this manner.

Once the rollout completes, I will try to run the command above `/gcbrun` to re-evaluate this PR.

**Comment by c2thorn** [comment]
> Note on failing tests: TestAccCloudRunV2Service_cloudrunv2ServiceFullUpdate -> I totally thought our rollout (for Cloud Run) for this week has completed, just checked and us-central1 only has part of the cells with new binary (that has this field change). Sorry about this. I believe the test should pass if re-run after the rollout is done.

No problem, please ping me here or internally whenever you want me to re-run.

> TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey -> Not quite sure of this test. There's no point any error occured, and it says "resource_container_cluster_test.go:3065: Stopping the test because a role was added to the policy." and it's marked failure. I can check with my teammates if they are aware of this issue, but also please let me know if you have an idea why this test fails in this manner.

I'm very certain this test in failing unrelated to your change. Don't worry about it.

> Once the rollout completes, I will try to run the command above `/gcbrun` to re-evaluate this PR.

I don't believe you'll have permission, since it didn't autorun when you pushed your commit.

**Comment by kminsu-google** [comment]
Happy Monday @c2thorn, I just double checked that the new binary has been rolled out to all us-central1(also to all prod regions). Could we run the check one more time?

**Comment by kminsu-google** [comment]
@c2thorn Hi Cameron, I believe the change needed to be made actually got rolled out to prod last week.
Could we run the check once again?

Thank you so much!

**Comment by kminsu-google** [comment]
Might be a visibility label issue. Retrying after updating the LABELs for the test project.

**Comment by kminsu-google** [comment]
Failed test does not seem to be related to the change made in this PR. Waiting for reviewer to confirm.

**Review by rileykarson — APPROVED** [review]

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
