### PR TITLE
Upgrade to Go 1.19 for TPG/TPGB

### PR DESCRIPTION
**Pull request by zli82016**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/14102
Upgrade to Go 1.19 for TPG/TPGB

Command:
go mod edit -go 1.19
go mod tidy

Ran acceptance tests locally
  * mmv1: make testacc TEST=./google TESTARGS='-run=TestAccStorageTransferAgentPool_agentPoolUpdate'
  * DCL: make testacc TEST=./google TESTARGS='-run=TestAccRecaptchaEnterpriseKey_AndroidKey'

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
I suspect we'll need to upgrade the Magician containers (such as https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/containers/downstream-builder/Dockerfile#L1) and the .go-version files in TPG and TPGB (such as https://github.com/hashicorp/terraform-provider-google/blob/main/.go-version) as well!

I think .go-version updates TeamCity as well, since the GO_VERSION variable there is 1.12.5 which is definitely too old to still work. (@megan07 or @SarahFrench should we clean that variable up?)

**Comment by SarahFrench** [comment]
@rileykarson I just double checked how that variable is used as I'm unfamiliar with it. The `Step 1/7: Setup GOENV (Command Line)` build step overrides the GO_VERSION environment variable using the local `.go-version` file in the downstream. Currently the build logs show `GO_VERSION overridden by local (1.18.1)` and this corresponds to a step in a bash script that uses `.go-version`.

I can update the value to match 1.19, in case a local version isn't present, but 99% of the time that variable does nothing.

**Comment by zli82016** [comment]
I see the version is already 1.18.1 in https://github.com/hashicorp/terraform-provider-google/blob/main/.go-version. 
Where do you see 1.12.5, @rileykarson ?

Also, does the order of merging PRs for this work and update .go-version matter? It seems that this PR should be merged first?

**Comment by rileykarson** [comment]
@zli82016: GO_VERSION is 1.12.5 in TeamCity, nowhere else! As mentioned, `.go-version` overrides it.

**Review by rileykarson — APPROVED** [review]
This change works to change our module version! We'll also want to update our images & `.go-version` numbers.

**Comment by zli82016** [comment]
Will update the images in a separate PR.

**Pull request merged**
