### PR TITLE
Set Bucket Id as context variable in TestAccLoggingBucketConfigProject_*

### PR DESCRIPTION
**Pull request by BBBmau**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/16695

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
logging: updated the `google_logging_project_bucket_config` resource to be created using the asynchronous create method
```

### CODE REVIEW

**Comment by BBBmau** [comment]
@SarahFrench made you a reviewer to get it merged quickly

**Comment by SarahFrench** [comment]
Check out the `terraform-provider-google-build-and-unit-tests` check for what's causing the test failure above

**Comment by BBBmau** [comment]
is this from recent changes to VCR? @SarahFrench

**Comment by SarahFrench** [comment]
I don't know, I wouldn't expect it to be related though. Let's re run the tests : /gcbrun

**Comment by SarahFrench** [comment]
Here's a list of requirements for enabling Log Analytics on a bucket : https://cloud.google.com/logging/docs/log-analytics#restrictions . I don't think your acceptance test is missing any of the requirements, but it's worth checking!

It may be that the service account we use for acceptance tests is just missing a permission, but I don't think that's likely. The acceptance test creates a new project and that means the identity Terraform uses will be the [Owner](https://cloud.google.com/iam/docs/understanding-roles#owner) of the overall project, plus the test passed ok in the past. Unless required permissions have changed in GCP following an update.

**Comment by SarahFrench** [comment]
It might be worth rebasing your PR to pull in this change - https://github.com/GoogleCloudPlatform/magic-modules/pull/9753
I don't think this will fix the test failure but it'll help us remove a 'what if?' from the problem.

**Comment by SarahFrench** [comment]
Oh wait - I didn't spot that there's a 500 error in the logs prior to the 403:

```
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

**Comment by BBBmau** [comment]
The latest build contained logic that would make the `POST` request async however it still produces the same error.

I noticed however that in the `POST` request it doesn't have the expect url set in the `Create` function

```
---[ REQUEST ]---------------------------------------
POST /v2/projects/tf-test-nrdqyqf4n1/locations/global/buckets?alt=json&bucketId=tf-test-bucket-jy23sskxh6 HTTP/1.1
Host: logging.googleapis.com
```

The expected url that should be used from the `Create` function is referenced below:

https://github.com/GoogleCloudPlatform/magic-modules/blob/d466e31c94a532c673ffee3d4481f9b9099122c9/mmv1/third_party/terraform/services/logging/resource_logging_bucket_config.go#L234C1-L237C3

I expected the url to change but im guessing there's something else that I need to change in order for the url to include the needed `createAsync` in the `POST` url request

**Comment by BBBmau** [comment]
From reading the [docs](https://cloud.google.com/logging/docs/buckets?&_ga=2.131456969.751422881.1704737111-1095956490.1702313106&_gac=1.60207839.1705008405.Cj0KCQiAwP6sBhDAARIsAPfK_wa0VzpwbLyE5rQcRW5lpKqMrgVx2LiOpNeKj5YgPgDw98LC-sJa5TkaAhOvEALw_wcB#upgrade-bucket) for upgrading a bucket to have analytics, the API section states that an `updateAsync` is required for enabling analytics on an existing bucket. This may be the reason for errors occuring, changed it to use `updateAsync` instead of `createAsync` to see what it outputs in the next build run.

**Comment by BBBmau** [comment]
reverted previous commit, this would still be required since the update function doesn't have this yet but creating the bucket with analytics should be fixed first.

when dealing with operations from adding `createAsync`, i also stumbled upon the fact that sending a GET request to the [operation.get](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.operations/get) endpoint is required to be able to get a finished response once done. I first wanted to make sure that it wasn't anything else that could be causing this error since the resource could just not be created at all. But the debug logs show that it is successful when destroyed.

Next step would be to allow `logging.operations.get` permissions to be able to send a GET request to the operation.get endpoint

**Comment by BBBmau** [comment]
Tests are passing, however it would be good to include `updateSync` also since it's included in the API docs

https://cloud.google.com/logging/docs/buckets?&_ga=2.131456969.751422881.1704737111-1095956490.1702313106&_gac=1.60207839.1705008405.Cj0KCQiAwP6sBhDAARIsAPfK_wa0VzpwbLyE5rQcRW5lpKqMrgVx2LiOpNeKj5YgPgDw98LC-sJa5TkaAhOvEALw_wcB#upgrade-bucket

**Comment by BBBmau** [comment]
recent commit will determine whether `updateSync` is required. 

added first step in `analyticsEnabled` to be a basic configuration in order to test the case where updating a log bucket to enable analytics is tested.

we may want to have a separate TestAcc for this specific case. It's expected to fail since currently there is no use of `:updateSync`

**Comment by BBBmau** [comment]
tests are passing despite no use of `:updateSync`, a bit surprising since based off the docs it does say to use it for updating an existing bucket to have analytics enabled. The test already had the requirement of adding an `update_mask` which is also another requirement. Could be that just having the `update_mask` is the only thing necessary?

**Comment by BBBmau** [comment]
looked into the patch time and although it's passing it only passes due to sending a second patch after the first attempt times out, it would be best to add `:updateSync` to prevent future failures due to this.

```
2024/01/17 15:13:26 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
PATCH /v2/projects/tf-test-n4o0sxostl/locations/global/buckets/tf-test-bucket-3ni9wgm8c4?alt=json&updateMask=analyticsEnabled HTTP/1.1
Host: logging.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/acc
Content-Length: 26
Content-Type: application/json
Accept-Encoding: gzip

{
 "analyticsEnabled": true
}

-----------------------------------------------------
2024-01-17T15:13:30.949Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:31.144Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:13:35.949Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:36.145Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:13:40.950Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:41.146Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:13:45.951Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:46.146Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:13:50.952Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:51.147Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:13:55.953Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:13:56.148Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:00.953Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:01.149Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:05.954Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:06.150Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:10.955Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:11.150Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:15.956Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:16.151Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:20.957Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:21.152Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:25.957Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:26.152Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:30.957Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:31.153Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:35.958Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:36.154Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:40.959Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:41.155Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:45.959Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:46.156Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:50.960Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:51.157Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:14:55.961Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:14:56.157Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:00.962Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:15:01.158Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:05.963Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:15:06.158Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:10.965Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:15:11.159Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:15.965Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:15:16.159Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:20.966Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024-01-17T15:15:21.160Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024-01-17T15:15:25.966Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/google\"] (close)" is waiting for "google_logging_project_bucket_config.basic"
2024/01/17 15:15:26 [DEBUG] Retry Transport: Stopping retries, last request failed with non-retryable error: net/http: request canceled
2024/01/17 15:15:26 [DEBUG] Retry Transport: Returning after 1 attempts
2024/01/17 15:15:26 [DEBUG] Dismissed an error as retryable. marked as timeout - Patch "https://logging.googleapis.com/v2/projects/tf-test-n4o0sxostl/locations/global/buckets/tf-test-bucket-3ni9wgm8c4?alt=json&updateMask=analyticsEnabled": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2024-01-17T15:15:26.161Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/google\"] (close)"
2024/01/17 15:15:26 [DEBUG] Retry Transport: starting RoundTrip retry loop
2024/01/17 15:15:26 [DEBUG] Retry Transport: request attempt 0
2024/01/17 15:15:26 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
PATCH /v2/projects/tf-test-n4o0sxostl/locations/global/buckets/tf-test-bucket-3ni9wgm8c4?alt=json&updateMask=analyticsEnabled HTTP/1.1
Host: logging.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/acc
Content-Length: 26
Content-Type: application/json
Accept-Encoding: gzip
```

**Comment by BBBmau** [comment]
All good now

**Comment by SarahFrench** [comment]
Note: I've updated the release notes to include the change in the resource.

**Comment by SarahFrench** [comment]
I'm just running the acceptance tests against the google-beta generated from this PR ([here](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleBeta_MmUpstreamTesting_GOOGLEBETA_PACKAGE_LOGGING/90282?mode=builds&buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false)), assuming they pass ok I'm happy to merge

**Review by SarahFrench — APPROVED** [review]
Approving as the tests pass via VCR and in TeamCity. Good lob seeing this through!

**Pull request merged**
