### PR TITLE
Add Vertex ML Metadata Store

### PR DESCRIPTION
**Pull request by upodroid**
Part of: https://github.com/hashicorp/terraform-provider-google/issues/9298

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_vertex_ai_metadata_store`
```

### CODE REVIEW

**Comment by upodroid** [comment]
There is a bug in the API. It doesn't return encryption_spec fields.

The whole reason for using this resource is to support CMEK and the API doesn't even return those fields  😕 

```
021/07/05 19:04:19 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /v1beta1/projects/REDACTED/locations/us-central1/metadataStores?alt=json&metadataStoreId=tf-test-2weojyw8lj HTTP/1.1
Host: us-central1-aiplatform.googleapis.com
User-Agent: Terraform/0.14.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/acc
Content-Length: 169
Content-Type: application/json
Accept-Encoding: gzip

{
 "description": "Magic",
 "encryptionSpec": {
  "kmsKeyName": "projects/REDACTED/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1"
 }
}

-----------------------------------------------------
2021/07/05 19:04:20 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Jul 2021 18:04:20 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/550924169191/locations/us-central1/operations/616599798664921088",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.aiplatform.v1beta1.CreateMetadataStoreOperationMetadata",
    "genericMetadata": {
      "createTime": "2021-07-05T18:04:20.582962Z",
      "updateTime": "2021-07-05T18:04:20.582962Z"
    }
  }
}

-----------------------------------------------------
2021/07/05 19:04:20 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/07/05 19:04:20 [DEBUG] Retry Transport: Returning after 1 attempts
2021/07/05 19:04:20 [DEBUG] Waiting for state to become: [done: true]
2021/07/05 19:04:20 [DEBUG] Waiting for state to become: [success]
2021/07/05 19:04:20 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/07/05 19:04:20 [DEBUG] Retry Transport: request attempt 0
2021/07/05 19:04:20 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /v1beta1/projects/550924169191/locations/us-central1/operations/616599798664921088?alt=json HTTP/1.1
Host: us-central1-aiplatform.googleapis.com
User-Agent: Terraform/0.14.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2021/07/05 19:04:21 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Jul 2021 18:04:21 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/550924169191/locations/us-central1/operations/616599798664921088",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.aiplatform.v1beta1.CreateMetadataStoreOperationMetadata",
    "genericMetadata": {
      "createTime": "2021-07-05T18:04:20.582962Z",
      "updateTime": "2021-07-05T18:04:20.582962Z"
    }
  }
}

-----------------------------------------------------
2021/07/05 19:04:21 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/07/05 19:04:21 [DEBUG] Retry Transport: Returning after 1 attempts
2021/07/05 19:04:21 [DEBUG] Got done: false while polling for operation projects/550924169191/locations/us-central1/operations/616599798664921088's status
2021/07/05 19:04:31 [DEBUG] Waiting for state to become: [success]
2021/07/05 19:04:31 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/07/05 19:04:31 [DEBUG] Retry Transport: request attempt 0
2021/07/05 19:04:31 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /v1beta1/projects/550924169191/locations/us-central1/operations/616599798664921088?alt=json HTTP/1.1
Host: us-central1-aiplatform.googleapis.com
User-Agent: Terraform/0.14.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2021/07/05 19:04:31 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Jul 2021 18:04:31 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/550924169191/locations/us-central1/operations/616599798664921088",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.aiplatform.v1beta1.CreateMetadataStoreOperationMetadata",
    "genericMetadata": {
      "createTime": "2021-07-05T18:04:20.582962Z",
      "updateTime": "2021-07-05T18:04:21.980978Z"
    }
  },
  "done": true,
  "response": {
    "@type": "type.googleapis.com/google.cloud.aiplatform.v1beta1.MetadataStore",
    "name": "projects/550924169191/locations/us-central1/metadataStores/tf-test-2weojyw8lj"
  }
}

-----------------------------------------------------
2021/07/05 19:04:31 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/07/05 19:04:31 [DEBUG] Retry Transport: Returning after 1 attempts
2021/07/05 19:04:31 [DEBUG] Got done: true while polling for operation projects/550924169191/locations/us-central1/operations/616599798664921088's status
2021/07/05 19:04:31 [DEBUG] Finished creating MetadataStore "tf-test-2weojyw8lj": map[string]interface {}{"metadata":map[string]interface {}{"@type":"type.googleapis.com/google.cloud.aiplatform.v1beta1.CreateMetadataStoreOperationMetadata", "genericMetadata":map[string]interface {}{"createTime":"2021-07-05T18:04:20.582962Z", "updateTime":"2021-07-05T18:04:20.582962Z"}}, "name":"projects/550924169191/locations/us-central1/operations/616599798664921088"}
2021/07/05 19:04:31 [DEBUG] Waiting for state to become: [success]
2021/07/05 19:04:31 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/07/05 19:04:31 [DEBUG] Retry Transport: request attempt 0
2021/07/05 19:04:31 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /v1beta1/projects/REDACTED/locations/us-central1/metadataStores/tf-test-2weojyw8lj?alt=json HTTP/1.1
Host: us-central1-aiplatform.googleapis.com
User-Agent: Terraform/0.14.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2021/07/05 19:04:32 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Jul 2021 18:04:32 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/550924169191/locations/us-central1/metadataStores/tf-test-2weojyw8lj",
  "createTime": "2021-07-05T18:04:20.582962Z",
  "updateTime": "2021-07-05T18:04:22.015587Z",
  "state": {
    "diskUtilizationBytes": "851968"
  }
}

-----------------------------------------------------
2021/07/05 19:04:32 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/07/05 19:04:32 [DEBUG] Retry Transport: Returning after 1 attempts
2021/07/05 19:04:37 [INFO] Authenticating using DefaultClient...
2021/07/05 19:04:37 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/07/05 19:04:37 [INFO] Authenticating using DefaultClient...
2021/07/05 19:04:37 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/07/05 19:04:37 [DEBUG] Waiting for state to become: [success]
2021/07/05 19:04:37 [INFO] Terraform is using this identity: REDACTED
    provider_test.go:276: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # google_vertex_ai_metadata_store.store must be replaced
        -/+ resource "google_vertex_ai_metadata_store" "store" {
              ~ create_time = "2021-07-05T18:04:20.582962Z" -> (known after apply)
              + description = "Magic"
              ~ id          = "tf-test-2weojyw8lj" -> (known after apply)
                name        = "tf-test-2weojyw8lj"
              ~ project     = "REDACTED" -> (known after apply)
              ~ state       = [
                  - {
                      - disk_utilization_bytes = "851968"
                    },
                ] -> (known after apply)
              ~ update_time = "2021-07-05T18:04:22.015587Z" -> (known after apply)
                # (1 unchanged attribute hidden)
        
              + encryption_spec {
                  + kms_key_name = "projects/REDACTED/locations/us-central1/keyRings/tftest-shared-keyring-1/cryptoKeys/tftest-shared-key-1"
                }
            }
        
        Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by upodroid** [comment]
Filed b/192870434

**Comment by c2thorn** [comment]
> Filed b/192870434

Thanks @upodroid. Following up on an internal tracker that points to yours.

**Comment by upodroid** [comment]
Google have said this fixed but it is still active. I fixed the conflicts in the meanwhile.

b/193651954

**Comment by jialuzh** [comment]
@upodroid I am from Vertex ML Metadata team. b/193651954 should be fixed now, could you help retry it and let us know whether you still saw the issue?

**Comment by c2thorn** [comment]
Tested locally - merging ahead of VCR tests to ensure the change is included in the next release.

**Review by c2thorn — APPROVED** [review]

**Comment by upodroid** [comment]
Thank you for getting this over the line.

**Pull request merged**
