### PR TITLE
Global forwarding rule and forwarding rule DCL conversion.

### PR DESCRIPTION
**Pull request by ndmckinley**
Converts the Global forwarding rule and Forwarding Rule resources to the DCL.  (Before reviewing, wait for tests to finish - they passed locally, but this is a brownfield resource and I'm opening this PR as a next-step, not as an indicator that this is certainly ready to go in).

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

(question - I put in no release note because this doesn't matter to end users.  Does that seem right to you?)

### CODE REVIEW

**Comment by ndmckinley** [comment]
```
go run scripts/diff.go --resource=google_compute_global_forwarding_rule --verbose                                                                                    
------------Diffing resource google_compute_global_forwarding_rule------------
DiffSuppressFunc for path project, was:  is now compareSelfLinkOrResourceName
------------Done------------
```

aaaand

```
go run scripts/diff.go --resource=google_compute_forwarding_rule --verbose       
------------Diffing resource google_compute_forwarding_rule------------
DiffSuppressFunc for path project, was:  is now compareSelfLinkOrResourceName
------------Done------------
```

(I assume this diff suppress is okay - it would take a fourth new override to remove it and it's pretty clearly harmless - but let me know if that's not all right).

**Comment by ndmckinley** [comment]
Ah, bummer - /gcbrun

**Comment by ndmckinley** [comment]
(in case anyone's wondering, it was the RAM issue in TeamCity again)

**Comment by ndmckinley** [comment]
Oh interesting, the way that the test fails in VCR is funny - it fails with "cannot create, already exists", because the existing VCR cassette contains responses that tickle the DCL.

| request | response | DCL | MM |
|--------|----|----|----|
| 1st GET |  404 | issued to check if resource exists | issued to check if resource exists
| 2nd GET | 200 | issued at start of Create apply for canonicalization | issued after Create is done

**Comment by ndmckinley** [comment]
Cool - two minor issues, will fix.

**Comment by ndmckinley** [comment]
Okay - those tests both pass locally now and this PR is (I believe) ready for review.

**Comment by ndmckinley** [comment]
Yep: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr/203498

**Review by slevenick — COMMENTED** [review]
It looks like the VCR test failures although they are on resources that look unrelated (private service connect) are caused by this swap:

```
Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.allPorts': 'false'. Invalid field set in Private Service Connect Forwarding Rule. This field should not be set., invalid
```

**Comment by ndmckinley** [comment]
> It looks like the VCR test failures although they are on resources that look unrelated (service attachement) are caused by this swap:

Ah!  Of course!  Thanks, I will make those tests pass ASAP.

**Comment by ndmckinley** [comment]
Those tests pass on this new change!
```
--- PASS: TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample (144.2s)
```

**Comment by ndmckinley** [comment]
Currently running all the regular forwarding rule tests.

**Comment by ndmckinley** [comment]
Yep, all `TestAccComputeGlobalForwardingRule` and `TestAccComputeForwardingRule` passing.

```
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta 312.961s
```

**Review by slevenick — APPROVED** [review]
Looks good assuming everything passes in CI!

I agree that this shouldn't impact users, so no release note

**Comment by ndmckinley** [comment]
Well, that's a lot, but I spot tested them and it looks okay... guess we'll see when the VCR test finishes.

**Comment by slevenick** [comment]
> Well, that's a lot, but I spot tested them and it looks okay... guess we'll see when the VCR test finishes.

Lots of failures on long names & port comparisons.. Did anything in the DCL change around this with the new version?

**Comment by ndmckinley** [comment]
Bummer - yes, the DCL can canonicalize those strings just fine, but import tests don't provide us with the customer's value, so we return whatever the API returns.

Okay, I'll have to come back to this when I'm back from vacation.

**Comment by ndmckinley** [comment]
Okay - seems to have been a simple git history mistake on my part, covered up by the fact that I was only running `make tpgtools` on my machine, so my local testing was using the pre-mistake version of mmv1.

**Comment by ndmckinley** [comment]
/gcbrun - failure in cloud build to cancel the ongoing run since it was already done.

**Comment by ndmckinley** [comment]
Okay - that is all the tests passing.  The two that failed are unrelated and are failing at head.  I'm going to merge this.

**Pull request merged**
