### PR TITLE
docs: Improve Terraform example for google_vpc_access_connector

### PR DESCRIPTION
**Pull request by ppuschmann**
Improve the Terraform example for `google_vpc_access_connector` with Shared-VPC. The current example does not work properly, because the lookup of the subnet is not working perfectly.

Since the network management in the context of Shared-VPC is mostly done centrally, the new example uses a data source for the serverless subnetwork `google_compute_subnetwork`.

```release-note:none

```

### CODE REVIEW

**Comment by ppuschmann** [comment]
This is my first PR in this project and hopefully I get everything right.

**Comment by ppuschmann** [comment]
Okay, then I'll investigate locally first.

By the way: this helped me a lot: https://github.com/rbenv/ruby-build/discussions/1933#discussioncomment-2131144

**Comment by ppuschmann** [comment]
Hi @trodge , I tried to run the test and all locally, but cannot find the issue.
I can't access the error-log and debug-log from above.

**Comment by trodge** [comment]
This is the error the test is failing with:

```
2024-02-23T22:33:54.669Z [WARN]  sdk.helper_resource: Error running Terraform CLI command: test_terraform_path=/bin/terraform test_step_number=1
  error=
  | exit status 1
  | 
  | Error: Reference to undeclared resource
  | 
  |   on terraform_plugin_test.tf line 5, in resource "google_vpc_access_connector" "connector":
  |    5:     name       = google_compute_subnetwork.custom_test.name
  | 
  | A managed resource "google_compute_subnetwork" "custom_test" has not been
  | declared in the root module.
  | 
  | Did you mean the data resource data.google_compute_subnetwork.custom_test?
  | 
  | Error: Reference to undeclared input variable
  | 
  |   on terraform_plugin_test.tf line 14, in data "google_compute_subnetwork" "custom_test":
  |   14:   region  = var.region
  | 
  | An input variable with the name "region" has not been declared. This variable
  | can be declared with a variable "region" {} block.
   test_working_directory=/tmp/plugintest1475029740 test_name=TestAccVPCAccessConnector_vpcAccessConnectorSharedVpcExample
```

**Comment by trodge** [comment]
A rebase may help with the CI failure happening in this PR.

**Comment by rileykarson** [comment]
Hey! I'm closing this PR as a part of a cleanup of older inactive PRs, using a threshold of PRs last updated over 3 months ago. This doesn't represent rejection of the change, and feel free to comment for me to reopen it if you plan to pick it back up, or feel free to start a new PR with the same changes in the future.

**Pull request closed without merging**
