### PR TITLE
Adding Proxy destination and DeadLetter config for Eventing config.

### PR DESCRIPTION
**Pull request by balanaguharsha**
Adding Proxy destination and DeadLetter config for Eventing config.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Adding support of Proxy and DeadLetter Configuration for Eventing in Connections resource

```

### CODE REVIEW

**Comment by balanaguharsha** [comment]
I don't see an error in the logs, please suggest, @melinath

**Review by melinath — CHANGES_REQUESTED** [review]
The API doesn't seem to return values for these fields - is that intentional? If so, you'll need to add a `custom_flatten` function to ignore the value from the API: https://googlecloudplatform.github.io/magic-modules/develop/custom-code/#custom_flatten

Similar to https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/custom_flatten/datastream_connection_profile_mysql_profile_ssl_config_ca_certificate.go.erb

**Review by melinath — CHANGES_REQUESTED** [review]
previous review was not addressed - re-requesting changes.

**Review by melinath — CHANGES_REQUESTED** [review]
It doesn't look like the previous change requests have been addressed, so I'm removing this from my review queue again - please let me know if I'm missing anything :-)

**Review by melinath — CHANGES_REQUESTED** [review]
re-requesting changes since they have not been addressed

**Review by melinath — CHANGES_REQUESTED** [review]
same

**Review by melinath — CHANGES_REQUESTED** [review]
still waiting for previous comments to be resolved

**Review by melinath — CHANGES_REQUESTED** [review]
still waiting

**Comment by melinath** [comment]
@balanaguharsha did you mean to close this? I see you pushed commits _after_ closing so just wanted to make sure it was intentional.

**Pull request closed without merging**
