### PR TITLE
feat: add cross-region replication support to AlloyDB

### PR DESCRIPTION
**Pull request by bschaatsbergen**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
google_alloydb_cluster: add primary_config output-only attribute
```

```release-note:new-resource
`google_alloydb_cluster_secondary`
```

```release-note:new-resource
`google_alloydb_instance_secondary`
```

Closes https://github.com/hashicorp/terraform-provider-google/issues/13251

### CODE REVIEW

**Review by thomas-vl — APPROVED** [review]
LGTM 🚀 !

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
See https://github.com/hashicorp/terraform-provider-google/issues/13251#issuecomment-1648494116

**Comment by bschaatsbergen** [comment]
Heya @ScottSuarez, could you give me a hand with the `post_create` ? I've added an empty file for now: `alloydb_secondary_cluster_create.go.erb` but I honestly have no idea how to implement it, even after some digging around - these post_creates seem very custom.

**Comment by ScottSuarez** [comment]
Check out the following 
https://github.com/GoogleCloudPlatform/magic-modules/blob/e0598af7c9ebbc8c43b976b9c4f201bbb2555364/mmv1/templates/terraform/resource.erb#L402

We essentially inject the post_create contents from the file into the resource function. You should be able to make the changes in tpg(b) downstream then copy that extra functionality up to your create method. Note that it the scope of the rest of the create function so you should be able to reuse the url and whatnot.

**Comment by bschaatsbergen** [comment]
Hey @ScottSuarez, scuzi - I haven't touched the post_create at all so far, what do you exactly mean with; 

> You should be able to make the changes in tpg(b) downstream then copy that extra functionality up to your create method

Does this mean I have to make a PR to https://github.com/hashicorp/terraform-provider-google-beta ?

If you could give me a hand, that would be appreciated

**Comment by ScottSuarez** [comment]
So magic-modules runs as a templating engine. We basically format and template a bunch of files that we then merge with the providers downstream. What I'm suggesting is to checkout the provider locally and add that functionality inline to the file.


Therefore if you look at the template I linked.
https://github.com/GoogleCloudPlatform/magic-modules/blob/e0598af7c9ebbc8c43b976b9c4f201bbb2555364/mmv1/templates/terraform/resource.erb#L402

This line is where the post_create function is injected.

If you are to work in tpgb and alter the file downstream where this function gets injected.
https://github.com/modular-magician/terraform-provider-google-beta/blob/0757f416a76f6f38582e84ac9986c809f3736c02/google-beta/services/alloydb/resource_alloydb_cluster.go#L634-L649

You would be able to see the scope that available here prior to injection and even tinker with it. I can certainly try tomorrow to help if you can't get anywhere or you still don't know how to proceed.

**Comment by bschaatsbergen** [comment]
Heya @ScottSuarez could you give me a little kickstart. I'm a bit jam packed with day to day work at the moment, and would like to see how you're tackling this post_create.

**Comment by bschaatsbergen** [comment]
I'm going to check this out today together with a colleague @ScottSuarez, if we bump into anything I'll let you know.

**Comment by DanielRieske** [comment]
@ScottSuarez Apologies for the extra commit noise, I had some issues with rebasing.
We will continue working on this tomorrow.

**Comment by ScottSuarez** [comment]
No worries, let me know when this is ready for review

**Comment by DanielRieske** [comment]
We have been working for the past few days on the solution suggested by @ScottSuarez and I have a question and an observation.

Because the secondary cluster and instance resources are heavily tied to the primary ones, the suggestion was to reuse these resource schemas and implement the `post-create` to change the URL parameters based on a bool.

This is what we have done and is working as intended but we did ran into certain edge-cases that I'd ask your opinion on.

_**1 -Deleting secondary instance/cluster**_

During testing we noticed that you cannot delete the secondary instance itself but rather have to delete the entire secondary cluster to delete it. Because the secondary instance is technically a child-resource of the cluster I am unsure on how to manage the deletion of this resource within Terraform.

There is currently no-way of deleting this resource through the API as I need to delete the parent-resource to make this happen.

It's an odd dependancy to begin with as I can create primary and secondary cluster without instances through the API but when I create instances in the secondary cluster I can't delete them.

Any advice on how to manage this?

We got the following response from the API when we tried deleting the secondary instance.


```
---[ REQUEST ]---------------------------------------
DELETE /v1/projects/project-x/locations/us-east1/clusters/tf-test-alloydb-cluster-secondaryuvgdhsrnwm/instances/tf-test-alloydb-instanceuvgdhsrnwm?alt=json HTTP/1.1
Host: alloydb.googleapis.com
User-Agent: Terraform/1.5.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2023/08/03 02:49:32 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Thu, 03 Aug 2023 00:49:32 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "error": {
    "code": 400,
    "message": "Invalid resource state for \"projects/project-x/locations/us-east1/clusters/tf-test-alloydb-cluster-secondaryuvgdhsrnwm/instances/tf-test-alloydb-instanceuvgdhsrnwm\": Cannot delete SECONDARY instance without deleting the SECONDARY cluster. Delete the SECONDARY cluster in force mode to delete the entire cluster and the instances",
    "status": "FAILED_PRECONDITION",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "SECONDARY_INSTANCE_NOT_DELETABLE",
            "subject": "projects/project-x/locations/us-east1/clusters/tf-test-alloydb-cluster-secondaryuvgdhsrnwm/instances/tf-test-alloydb-instanceuvgdhsrnwm",
            "description": "Cannot delete SECONDARY instance without deleting the SECONDARY cluster. Delete the SECONDARY cluster in force mode to delete the entire cluster and the instances"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "c9a083f0f760c1a5"
      }
    ]
  }
}

```


_**2 -Assigning a secondary instance to a primary instance**_

Purely to test certain edge-cases I tried assigning a secondary instance to a primary cluster, which for obvious reasons shouldn't work and I expected an error message from the API explaining this.

Instead I got an "Internal Server Error - 500" and from a consumer stand-point this message won't tell them anything.

```
---[ REQUEST ]---------------------------------------
POST /v1/projects/project-x/locations/us-central1/clusters/tf-test-alloydb-clusterghb167bvdx/instances:createsecondary?alt=json&instanceId=tf-test-alloydb-instanceghb167bvdx HTTP/1.1
Host: alloydb.googleapis.com
User-Agent: Terraform/1.5.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google/acc
Content-Length: 60
Content-Type: application/json
Accept-Encoding: gzip

{
 "instanceType": "SECONDARY",
 "machineConfig": {
  "cpuCount": 2
 }
}

-----------------------------------------------------
2023/08/03 01:45:30 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 500 Internal Server Error
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Wed, 02 Aug 2023 23:45:30 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "error": {
    "code": 500,
    "message": "An internal error has occurred (5d87ef19-275a-4c66-8897-e23a24974014)",
    "status": "INTERNAL"
  }
}
```

**Comment by ScottSuarez** [comment]
This is issue is directly tied to the `google_alloydb_instance` resource correct? Could you schedule an office hour visit go/terraform-help . This is a pretty esoteric issue and would require closer collaboration.

**Comment by DanielRieske** [comment]
Yes it is directly tied to `google_alloydb_instance`, the tests that are currently running will most likely fail for that reason too.

> Could you schedule an office hour visit go/terraform-help . This is a pretty esoteric issue and would require closer collaboration.

I'd love to but I am unsure how.

**Comment by ScottSuarez** [comment]
Ah apologies, I assumed you were apart of the service team at google. Since you're not internal its tricky to discuss. Since we have no process for these kind of nuanced discussions with external contributors. Ultimately we may need to have consultation with the api team directly.

Can I ask some questions?

Cluster resource spins up the instances correct.
Then instance resources are used to manage the ones that get spun up.

Isn't the current UX for removing the primary instance from the configuration a NOOP. I would assume both the secondary and primary clusters being deleted to result in no action or an unsetting of the customization of the instance. Since the cluster itself is the one that declares and spins them up. It feel appropriate to me for the cluster deletion to also be the resource that spins them down. It appears this is not the behavior.

What is the current relationship between the cluster and the instance resources?

**Comment by DanielRieske** [comment]
Ah that explains it and absolutely I'll try to answer them as much as I can but I agree that this needs consultation with the API team.

> Cluster resource spins up the instances correct. Then instance resources are used to manage the ones that get spun up.

Cluster resources `google_alloydb_cluster` spin up an AlloyDB cluster and how it's implemented right now we check a boolean called `create_secondary` on whether this wil a primary or a secondary that has a dependency to the primary.

The instance resource `google_alloydb_instance` is an instance created within the cluster and needs to have a reference to the cluster that it's created within.
This causes an inherit dependency on the cluster within our Terraform configuration.

> Isn't the current UX for removing the primary instance from the configuration a NOOP. I would assume both the secondary and primary clusters being deleted to result in no action or an unsetting of the customization of the instance. Since the cluster itself is the one that declares and spins them up. It feel appropriate to me for the cluster deletion to also be the resource that spins them down. It appears this is not the behavior.

Semantically speaking, yes I agree that the cluster is the one spinning up the instance resources but because the instance is a resource that we create within the cluster and thus a child-resource of the cluster there should be a way to delete the instance first and then delete the cluster.

In the Google Cloud Console for example you cannot create a stand-alone cluster, you need to create the cluster + instance in one go. This implies that one cannot live without the other while the API does support this action.

So through the API it is possible to create a stand-alone cluster and then create an instance in it but you cannot delete the instance and revert back to a stand-alone cluster. This is consistent with how the Google Cloud Console behaves just not the API.

> What is the current relationship between the cluster and the instance resources?

As it stands right now, instances are child-resources of the cluster.

**Comment by bschaatsbergen** [comment]
@ScottSuarez any update on this?

**Comment by ScottSuarez** [comment]
The team responded that they won't be accepting external contributions for this change but they are assigning an engineer to work on this issue. Apologies, but thats for the work. I'll be closing this ticket out. It's likely the team member may use some of the existing philosophy to accomplish the same task.

**Comment by bschaatsbergen** [comment]
All good @ScottSuarez

**Pull request closed without merging**
