### PR TITLE
Make google_container_cluster work for both routes-based and autopilot clusters

### PR DESCRIPTION
**Pull request by xiaobaitusi**
For autopilot clusters, the networking is pre-configured. With container
gen-client, we want to send `IPAllocationPolicy.UseIpAliases` and `IPAllocationPolicy.UseRoutes` as false,
so that the service can pick the default IP allocation mode [1].

Only when the `networkingMode` is specifically set to "ROUTES",
`IPAllocationPolicy.UseRoutes` is passed with true.

[1] https://github.com/googleapis/google-api-go-client/blob/main/container/v1/container-gen.go#L2238:L2241

This change fixes the following error when applying an autopilot cluster

```
resource "google_container_cluster" "tf-cluster" {
  name     = "tf-cluster"
  location = "europe-west1"
  project = "my-project"

  enable_autopilot = "true"
  release_channel {
    channel = "REGULAR"
  }
  min_master_version = "1.21.5-gke.1302"
}
```

```
google_container_cluster.tf-cluster: Creating...

Error: googleapi: Error 400: Max pods constraint on node pools for Autopilot clusters should be 32., badRequest

  on container_cluster.tf line 1, in resource "google_container_cluster" "tf-cluster":
   1: resource "google_container_cluster" "tf-cluster" {

```

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by xiaobaitusi** [comment]
For transparency, I didn't have the ruby setup for my local MM repo. So this CL didn't go through steps to generate terraform code, and run related tests.

**Review by rileykarson — COMMENTED** [review]
This change effectively undoes https://github.com/GoogleCloudPlatform/magic-modules/pull/5504 and makes it so that clusters default to VPC-native mode. That's probably a better default, honestly, but https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#networking_mode states that they default to ROUTES-based so I'd prefer waiting for a major version to change that.

There's a preexisting customizediff function that rewrites a field's planned value based on autopilot being enabled. I believe we can use that instead, in order to maintain backwards compatibility for both autopilot and non-autopilot clusters, by setting `networking_mode` to `VPC_NATIVE`: https://github.com/hashicorp/terraform-provider-google-beta/blob/4ea6fb2acfcdd87d6756cab0b4577315c8e19d20/google-beta/resource_container_cluster.go#L4086-L4095

**Comment by ScottSuarez** [comment]
related to 
https://github.com/hashicorp/terraform-provider-google/issues/10782

**Comment by ScottSuarez** [comment]
any update on this change? 

continues to be an issue for https://github.com/hashicorp/terraform-provider-google/issues/10782#issuecomment-1023601603

**Comment by ScottSuarez** [comment]
I think autopilot is effectively broken without this fix

**Comment by ScottSuarez** [comment]
or I'm unsure what the failure scenario is here

**Comment by rileykarson** [comment]
Can't autopilot users specify the mode explicitly?

**Comment by hessjcg** [comment]
This is a big point of friction for people using Terraform and GKE. Can you please prioritize it?

**Comment by ScottSuarez** [comment]
closing in favor of https://github.com/GoogleCloudPlatform/magic-modules/pull/6696

**Pull request closed without merging**
