### PR TITLE
feat: add `pubsub_wrapper` to `google_pubsub_subscription`

### PR DESCRIPTION
**Pull request by bschaatsbergen**
Adds the `pubsub_wrapper` argument to the `google_pubsub_subscription` resource.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
pubsub: added `pubsub_wrapper` field to `google_pubsub_subscription` resource
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Heya @slevenick could you check out this PR :)?

**Comment by slevenick** [comment]
Huh... I thought I approved it and was waiting for the follow-up generation comment to ping me. Was there a build error?

**Comment by slevenick** [comment]
It looks like the API does not recognize the fields:
                "description": "Invalid JSON payload received. Unknown name \"writeMetadata\" at 'push_config.pubsub_wrapper': Cannot find field.",


Is this feature released? Are you able to run the tests locally?

**Comment by bschaatsbergen** [comment]
> Oh, it looks like it should be on a sibling object to pubsub_wrapper called no_wrapper: https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#nowrapper

Hey @slevenick ! :) 

What do you mean exactly? Aren't they defined on the same level?
image

**Comment by slevenick** [comment]
It looks like the pubsubWrapper object has no subfields, which generally means that the presence of the object itself in the request `{"pubsubWrapper": {}}` means something, typically that the feature should be enabled.

We have some cases of this happening before, and have used the `bool_to_object` custom expand and object_to_bool custom flattener to make it seem like a boolean flag in the Terraform config. The problem is that this ends up being a major headache if the API adds sub fields at a later date. It may make sense to just implement it as an empty object in Terraform, meaning a user would have to specify `pubsub_wrapper {}` in their config

**Comment by slevenick** [comment]
allow_empty_object may be the right answer here to allow enabling of this feature and keep us flexible in the case where subfields are added in the future.

See https://github.com/hashicorp/terraform-provider-google/issues/12651

**Comment by bschaatsbergen** [comment]
Hey @slevenick I'll pick this up soon again!

**Pull request closed without merging**
