### PR TITLE
Add Dataplex Zone resource

### PR DESCRIPTION
**Pull request by saurabhmaurya06**
part of https://github.com/hashicorp/terraform-provider-google/issues/11648

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-resource
`google_dataplex_zone`
```

### CODE REVIEW

**Comment by melinath** [comment]
Reassigning to someone who knows more about the DCL than I do since it's doing weird things.

A couple things to note:

Error:

```
provider_test.go:301: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=4) {
         (string) (len=16) "discovery_spec.#": (string) (len=1) "1",
         (string) (len=18) "discovery_spec.0.%": (string) (len=1) "6",
         (string) (len=24) "discovery_spec.0.enabled": (string) (len=5) "false",
         (string) (len=25) "discovery_spec.0.schedule": (string) ""
        }

```

HTTP request to create the resource contains:

```json
 "discoverySpec": {
  "enabled": false,
  "excludePatterns": [],
  "includePatterns": []
 }
```

Response with the created resource contains:

```json
    "discoverySpec": {
      "csvOptions": {},
      "jsonOptions": {},
      "schedule": ""
    }
```

So it looks like the API isn't returning a value for enabled (which was sent) and _is_ returning a value for schedule (which wasn't sent). This feels like it could cause issues? I think there may also be issues telling the difference between a struct that has all its values set to the "unset" value and a struct that is not set at all - but I'm not sure?

**Review by slevenick — CHANGES_REQUESTED** [review]
You'll need to rebase and remove serialization.go, it shouldn't be needed anymore due to a recent change

**Comment by slevenick** [comment]
Looks pretty good! Just a couple of notes:

resource_spec should be marked as immutable in the DCL YAML file that describes it, otherwise we don't correctly mark the field as requiring recreate to change.
discovery_spec description should match the new required behavior. Currently the description says the field is optional

**Review by slevenick — CHANGES_REQUESTED** [review]
See my above comment

**Review by slevenick — CHANGES_REQUESTED** [review]
Looks like you've got some conflicts, can you rebase from master and resolve them?

**Review by slevenick — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
