### PR TITLE
New range types supported on google_netblock_ip_ranges

### PR DESCRIPTION
**Pull request by drebes**
# Release Note for Downstream PRs (will be copied)
```releasenote
This extends `google_netblock_ip_ranges` to supportmultiple useful IP address ranges that have a special meaning on GCP.
```

### CODE REVIEW

**Comment by drebes** [comment]
Are we good with this or do you have any additional feedback?

**Comment by paddycarver** [comment]
I think my approval stands? If that question was for me.

**Comment by drebes** [comment]
More for @chrisst as the assigned reviewer, since as an "unofficial official member" I so far do not merge my PRs.

**Comment by drebes** [comment]
But I see now that he's out of office due to a very good reason. @rileykarson can you help here?

**Comment by paddycarver** [comment]
Oh, sorry, I missed that @chrisst is the assigned reviewer. I think he's out on leave and won't be back for a bit. Either someone else on the team or I can help with the merging, if you like?

**Comment by rileykarson** [comment]
@paddycarver reviewed and can merge 👍

**Pull request merged**
