### PR TITLE
fix: Make key handle sweepable

### PR DESCRIPTION
**Pull request by romanini-ciandt**
Make key handle and resource project name sweepable too.

Go template version of https://github.com/GoogleCloudPlatform/magic-modules/pull/11693 PR

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by romanini-ciandt** [comment]
Just realized I need to make a couple more tests on that. I'll re-open soon, sorry!

**Comment by romanini-ciandt** [comment]
FYI this PR should fix an opened provider issue: https://github.com/hashicorp/terraform-provider-google/issues/18934

**Comment by zli82016** [comment]
I run the tests. `TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` passed.

But `TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` still fails with the error message
```
=== RUN   TestAccKMSKeyHandle_kmsKeyHandleBasicExample
=== PAUSE TestAccKMSKeyHandle_kmsKeyHandleBasicExample
=== CONT  TestAccKMSKeyHandle_kmsKeyHandleBasicExample
    resource_kms_key_handle_generated_test.go:39: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # google_kms_autokey_config.autokey_config will be updated in-place
          ~ resource "google_kms_autokey_config" "autokey_config" {
                id          = "folders/296033849616/autokeyConfig"
              + key_project = "projects/tf-test-key-proj0l4x6pzrzw"
                # (1 unchanged attribute hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccKMSKeyHandle_kmsKeyHandleBasicExample (162.33s)
```

**Comment by romanini-ciandt** [comment]
@zli82016 this error you posted is being discussed/investigated in https://github.com/hashicorp/terraform-provider-google/issues/18935. We suspect that is an infrastructure error. Looks like it was a flaky and after 8/4/24 it started to fail 100% of the times (for both `testAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` and `testAccKMSKeyHandle_kmsKeyHandleBasicExample`).

The goal of this current opened PR is to make the folder name sweepable and fix the hard-coded static folder name error. Do you think we can merge this now and deal with the other error in a future PR, if it's needed? ("if it's needed" because if it's due to some infra issue, maybe no PR here will be required)

PS: In your comment you mentioned that "`TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` passed" and But "`TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` still fails", but both are the same name. Which one passed? Key Handle or Autokey Config?

Thanks!

**Comment by zli82016** [comment]
> @zli82016 this error you posted is being discussed/investigated in [hashicorp/terraform-provider-google#18935](https://github.com/hashicorp/terraform-provider-google/issues/18935). We suspect that is an infrastructure error (more details are in the issue thread). Looks like it was a flaky and after 8/4/24 it started to fail 100% of the times (for both `testAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` and `testAccKMSKeyHandle_kmsKeyHandleBasicExample`).
> 
> The goal of this current opened PR is to make the folder name sweepable and fix the hard-coded static folder name error. Do you think we can merge this now and deal with the other error in a future PR, if it's needed? ("if it's needed" because if it's due to some infra issue, maybe no PR here will be required)
> 
> PS: In your comment you mentioned that "`TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` passed" and "`TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` still fails", but both are the same name. Which one passed? Key Handle or Autokey Config?
> 
> Thanks!

oh. Sorry for the copy paste issue.
`TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample` passed.

`TestAccKMSKeyHandle_kmsKeyHandleBasicExample` failed. 


This PR can be merged and then fix the test `TestAccKMSKeyHandle_kmsKeyHandleBasicExample` in the future.

**Comment by zli82016** [comment]
But I don't think this PR's change is related to `TestAccKMSAutokeyConfig_kmsAutokeyConfigAllExample`.

**Review by zli82016 — APPROVED** [review]
LGTM.

**Pull request merged**
