### PR TITLE
Dataproc job  - add presto config

### PR DESCRIPTION
**Pull request by DrFaust92**
Closes https://github.com/hashicorp/terraform-provider-google/issues/11159

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dataproc: adds `presto_config` to `dataproc_job`
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
fixed failing acctest @slevenick

**Comment by DrFaust92** [comment]
I double checked with rebasing latest code base that tests pass:

```
--- PASS: TestAccDataprocJob_PySpark (208.71s)
--- PASS: TestAccDataprocJob_updatable (225.55s)
--- PASS: TestAccDataprocJob_Hive (229.52s)
--- PASS: TestAccDataprocJob_Pig (230.64s)
--- PASS: TestAccDataprocJob_SparkSql (231.17s)
--- PASS: TestAccDataprocJob_Hadoop (250.78s)
--- PASS: TestAccDataprocJob_Presto (258.64s)
--- PASS: TestAccDataprocJob_Spark (271.79s)
```

[slevenick](https://github.com/slevenick)

**Comment by DrFaust92** [comment]
cant login to the above
Screen Shot 2022-03-23 at 10 08 51

the only related fail is `TestAccDataprocJob_Presto` ill check again as its does pass for me

**Comment by DrFaust92** [comment]
Rebasing Again, 

run the following:
```
make terraform VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" PRODUCT=dataproc
```

and then test using:
```
make testacc TEST=./google TESTARGS='-run=TestAccDataprocJob_Presto'
```

with results being:
```
--- PASS: TestAccDataprocJob_Presto (320.78s)
```

Cant repro any error and as stated can see the tests runs above /:

**Comment by DrFaust92** [comment]
Rebasing Again, 

run the following:
```
make terraform VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" PRODUCT=dataproc
```

and then test using:
```
make testacc TEST=./google TESTARGS='-run=TestAccDataprocJob_Presto'
```

with results being:
```
--- PASS: TestAccDataprocJob_Presto (320.78s)
```

Cant repro any error and as stated can see the tests runs above /:

**Review by slevenick — APPROVED** [review]

**Pull request merged**
