### PR TITLE
encode storage object in url

### PR DESCRIPTION
**Pull request by odedniv**
Moving from #1717 
Fixes terraform-providers/terraform-provider-google#2895

According to https://cloud.google.com/storage/docs/json_api/#encoding URI path parts need to be encoded.

For example in [`google_storage_object_access_control`](https://www.terraform.io/docs/providers/google/r/storage_object_access_control.html) if the object name contains a `/`, the request will fail with:

```
* google_storage_object_access_control.public_rule: Error creating ObjectAccessControl: googleapi: got HTTP response code 404 with body: Not Found
```

**Note:** I'm not sure how to test this, and if unit tests should be added somewhere because I can't get my baring of what tests this YAML configuration may affect. Please point me and the right direction and I'll be happy to add/test.

### CODE REVIEW

**Comment by rileykarson** [comment]
You can modify the test in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_storage_object_access_control_test.go to use a `/` in the object name; this test is already redundant with a test generated from https://github.com/GoogleCloudPlatform/magic-modules/blob/master/templates/terraform/examples/storage_object_access_control_public_object.tf.erb, so testing novel functionality is a 👍

**Comment by odedniv** [comment]
@rileykarson not sure I understand, do you think I should or should not add a test?

**Comment by rileykarson** [comment]
Ah! Sorry for the confusion, I'd suggest modifying the test in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_storage_object_access_control_test.go

**Comment by odedniv** [comment]
@rileykarson added, I think

**Comment by rileykarson** [comment]
Yep, that's it to add it. Thanks!
Running this through the code generator again so I can test the downstream PRs.

**Comment by odedniv** [comment]
@rileykarson, can this be merged?

**Comment by rileykarson** [comment]
These changes look good, it looks like we can't actually read `google_storage_object` resources that need URL encoding though. They're a handwritten resource, so we'll need to fix that manually. You can repro using the `TestAccStorageObjectAccessControl_update` test.

If you'd like to patch this yourself, let me know! Otherwise, I can get that done and then merge this PR.

**Comment by odedniv** [comment]
@rileykarson I can't find the hand-written problem... would you like to give it a go?

**Comment by rileykarson** [comment]
I sent a PR that fixes an issue during import where we only match part of the value in these cases. Do you mind also adding a `%` to this value as well? https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/storage/terraform.yaml#L29

**Comment by odedniv** [comment]
Sure @rileykarson, but what about the other lines and the `id_format`?

**Comment by rileykarson** [comment]
Afaik `id_format` doesn't need to changed, while testing locally https://github.com/GoogleCloudPlatform/magic-modules/pull/1866 + adding the symbol to `import_format` was sufficient.

**Comment by rileykarson** [comment]
Alright, merged #1866. Do you mind rebasing off `master` again?

**Comment by odedniv** [comment]
@rileykarson merged master (we can squash-rebase during merging the PR)

**Comment by rileykarson** [comment]
Hmm- the results in the downstream were a little different than I expected. I'm not sure why that's happening, so I'll take a look.

**Comment by odedniv** [comment]
@rileykarson any news?

**Comment by rileykarson** [comment]
Sorry! I didn't have the time to dig in immediately and this fell off my radar a little. I'll try to get to this today.

**Comment by rileykarson** [comment]
Looking into this more, my understanding of how we collapsed import formats was wrong. I'm working through supporting this by updating the code that does this, starting with https://github.com/GoogleCloudPlatform/magic-modules/pull/2054. I'll return to this PR when I have an update, sorry for the delay.

**Comment by lawliet89** [comment]
@rileykarson do you have an update on this?

**Comment by rileykarson** [comment]
My ideas to try and fix our generator didn't end up panning out, even after revisiting it a few times. I'm going to close this PR- it's probably better that whoever fixes https://github.com/terraform-providers/terraform-provider-google/issues/2895 starts from a fresh slate, since the current URL-encoding support in MM was insufficient. 

For the issue itself, we have a few team members working through old bugs. It  should get picked up by them.

**Pull request closed without merging**
