### PR TITLE
datasource google_compute_disk

### PR DESCRIPTION
**Pull request by AliAllomani**
Data Source for `google_compute_disk`

Fixes  https://github.com/hashicorp/terraform-provider-google/issues/8068

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
google_compute_disk
```

### CODE REVIEW

**Comment by AliAllomani** [comment]
@googlebot I signed it!

**Comment by AliAllomani** [comment]
```bash
# git remote -v
origin	git@github.com:modular-magician/terraform-provider-google.git (fetch)
origin	git@github.com:modular-magician/terraform-provider-google.git (push)

# git show --oneline  -s
b82501ab (HEAD) New generated code for MM PR 4355.

# make testacc TEST=./google TESTARGS='-run=TestAccDataSourceGoogleComputeDisk_basic'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccDataSourceGoogleComputeDisk_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceGoogleComputeDisk_basic
=== PAUSE TestAccDataSourceGoogleComputeDisk_basic
=== CONT  TestAccDataSourceGoogleComputeDisk_basic
--- PASS: TestAccDataSourceGoogleComputeDisk_basic (18.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-google/v3/google	19.457s
```

**Comment by jmeekhof** [comment]
Bump.

This would be really nice functionality to have.

**Comment by slevenick** [comment]
Ah sorry I lost track of this. @AliAllomani can you fix the merge conflict in this PR?

**Comment by AliAllomani** [comment]
replaced by #5978

**Pull request closed without merging**
