### PR TITLE
Added examples for Cloud SQL backup retention

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Planning to add these samples to this section:

https://cloud.google.com/sql/docs/sqlserver/backup-recovery/backing-up#locationbackups#set-retention
https://cloud.google.com/sql/docs/mysql/backup-recovery/backing-up#locationbackups#set-retention
https://cloud.google.com/sql/docs/postgres/backup-recovery/backing-up#locationbackups#set-retention

```release-note:none
```

### CODE REVIEW

**Review by ScottSuarez — APPROVED** [review]
looks good to me pending tests ~!

**Comment by betsy-lichtenberg** [comment]
Figured out why I was getting merge conflicts: Merging my branches with "master" instead of "main"

**Comment by ScottSuarez** [comment]
You've closed the PR. Is that intentional @betsy-lichtenberg ?

**Comment by betsy-lichtenberg** [comment]
Yes. I created a new PR.
https://github.com/GoogleCloudPlatform/magic-modules/pull/5798

**Pull request closed without merging**
