### PR TITLE
Added support for `auto` and deprecated `automatic` field in `google_secret_manager_secret` resource

### PR DESCRIPTION
**Pull request by abheda-crest**
Added support for the `auto` field and deprecated `automatic` field in the `google_secret_manager_secret` resource
fixes https://github.com/hashicorp/terraform-provider-google/issues/10679
fixes https://github.com/hashicorp/terraform-provider-google/issues/9272
fixes https://github.com/hashicorp/terraform-provider-google/issues/14282

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
secretmanager: added `auto` field to `google_secret_manager_secret` resource
```
```release-note:deprecation
secretmanager: deprecated `automatic` field on `google_secret_manager_secret`. Use `auto` instead.
```

### CODE REVIEW

**Comment by abheda-crest** [comment]
This PR follows the approach suggested by @slevenick in his [comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/8662#pullrequestreview-1587714959).

**Comment by abheda-crest** [comment]
@SarahFrench Could you please start the tests as it is awaiting your approval and review this PR?

**Comment by abheda-crest** [comment]
@SarahFrench Could you please review this PR?

**Review by SarahFrench — COMMENTED** [review]
👋 I've caught up on context needed to review this PR. As this PR is trying to avoid breaking changes, could you please [update this handwritten acceptance test](https://github.com/GoogleCloudPlatform/magic-modules/pull/8859/files#diff-0d9f3a58beb28b76e0fe278896045e0ba169a10239dfa2664b6a98a6bbbf8a99) to show that an old config that still uses `automatic = true` still works as expected?

**Comment by abheda-crest** [comment]
> 👋 I've caught up on context needed to review this PR. As this PR is trying to avoid breaking changes, could you please [update this handwritten acceptance test](https://github.com/GoogleCloudPlatform/magic-modules/pull/8859/files#diff-0d9f3a58beb28b76e0fe278896045e0ba169a10239dfa2664b6a98a6bbbf8a99) to show that an old config that still uses `automatic = true` still works as expected?

I've added a test case that covers the `automatic = true`. Just to clarify, while importing the `secret` resources having the old field `automatic = true`, the imported resource will have the new field `auto` as an empty object instead and the `automatic` field will be false.

**Comment by abheda-crest** [comment]
@SarahFrench Could you please start the tests and review the changes?

**Review by SarahFrench — APPROVED** [review]

**Pull request merged**
