### PR TITLE
Change google_network_security_tls_inspection_policy to ga

### PR DESCRIPTION
**Pull request by paulomarquescit**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/17247
This PR sends the 'google_network_security_tls_inspection_policy'  resource  from beta version to GA
 
If this PR is for Terraform, I acknowledge that I have:

- Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- Ensured that the resource and his fields wich I added that can be set by a user appear in at least one example (for generated resources) or third_party test (for handwritten resources or update tests).
- [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [make test and make lint](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_network_security_tls_inspection_policy` (GA)
```

```release-note:new-resource
networksecurity: promoted `tls_inspection_policy` field in `google_network_security_gateway_security_policy` to GA
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
The test failed due to:
```
    vcr_utils.go:152: Step 1/2 error: Error running pre-apply refresh: 
        Error: Inconsistent dependency lock file
        
        The following dependency selections recorded in the lock file are
        inconsistent with the current configuration:
          - provider registry.terraform.io/hashicorp/google-beta: required by this configuration but no version is selected
        
        To make the initial dependency selections that will initialize the dependency
        lock file, run:
          terraform init
--- FAIL: TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample (0.28s)
```

You'll likely want to remove the `provider = google-beta` in the configs of that tests.

For the linting errors, you can see details at https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/7872741133/job/21478600913?pr=9966

**Comment by LucaPrete** [comment]
@paulomarquescit @shuyama1 actually, this should be already included in [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10583)

**Comment by shuyama1** [comment]
> @paulomarquescit @shuyama1 actually, this should be already included in [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10583).
> 
> Also, I think the depending resources of this test are still beta, so I preferred to move the resource only to GA, but tests are still full beta for now. We can always double check later if also the dependent resources should be upgraded. @shuyama1 what do you think?

Thanks for the update. Do we have other GA tests that cover the resource, or if resource is proven to work fine locally with existing dependent resources in GA provider? Basically, we'll just need to make sure we can confirm the resource behaves as expected with the GA endpoint before promoting it to GA and upgrading the dependent resources could happen in a separate PR.

**Comment by LucaPrete** [comment]
@shuyama1 sorry...I noticed those other resources went to GA as well. Now in my PR everything is GA. I think we can abandon this one.

**Comment by shuyama1** [comment]
> @shuyama1 sorry...I noticed those other resources went to GA as well. Now in my PR everything is GA. I think we can abandon this one.

Sounds good! Thank you @LucaPrete!

@paulomarquescit Feel free to close this PR as the change will be in https://github.com/GoogleCloudPlatform/magic-modules/pull/10583. Thanks for working on it!

**Pull request closed without merging**
