### PR TITLE
Add validators cis 1.1 phase 1

### PR DESCRIPTION
**Pull request by palani-ram-google-partner**
Add Terraform Validator support for the following resources
kms keyring iam 
kms crypto key iam
bug fixes on big query dataset, , DNS managed zone and compute disk validator support

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note: enhancement
Add Terraform Validator support for Cloud KMS KeyRing and Cloud KMS Crypto Key IAM resources. 
Bug fixes on Bigquery data set, DNS managed zone and Compute Disk validators.

```

### CODE REVIEW

**Comment by palani-ram-google-partner** [comment]
@melinath Please review and let me know

**Review by melinath — CHANGES_REQUESTED** [review]
There are a few major things to address with this PR:

1. There are a lot of extraneous changes to files that are unrelated to the changes you're making. This makes it hard to review & also it's better for PRs to be focused on a single change. Please remove the changes to the following files & any other files that have changes that are not relevant to the current work:
   - mmv1/.ruby-version
   - mmv1/Gemfile.lock
   - various ansible_version_added.yaml files
2. There are changes to multiple unrelated resources in a single PR. Having all the KMS key ring IAM resources in a single PR is fine, since they're closely related; however, changes related to KMS key ring IAM, KMS crypto key IAM, compute disk, and bigquery dataset IAM should be in four separate PRs. This will allow us to review & merge resources that are ready while continuing to work on resources that need more changes. (It also makes review easier.)
3. Please put the fixes for the `for for` typo in a separate PR - that is easy to merge & doesn't need to wait on a resource getting ready.

**Comment by melinath** [comment]
It might be easiest to close this PR and open separate PRs with each set of changes, rather than modifying this PR to have just one set of changes & then opening additional PRs - but whatever you prefer is fine.

**Comment by palani-ram-google-partner** [comment]
ok sounds good, thanks Stephen.
I am going to cancel the next meeting. I would have that meeting once all
this is done and do the same with the policy library.

Thanks & Regards,
Palani.
Cloud Security Engineer, Google PSO

**Comment by melinath** [comment]
Closing this PR; this work will happen in separate PRs like https://github.com/GoogleCloudPlatform/terraform-validator/pull/277

**Pull request closed without merging**
