### PR TITLE
Add billingType attribute to Apigee Organization resource

### PR DESCRIPTION
**Pull request by xuchenma**
This PR fixes https://github.com/hashicorp/terraform-provider-google/issues/11226 by adding a billingType attribute to ApigeeOrganization resource.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
Add billingType attribute to Apigee Organization resource.
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Did you tests these changes locally. Looks like a lot of the corresponding tests are failing and its not immediately clear why

**Comment by xuchenma** [comment]
Yes, I tested it locally and it has passed. The failures in the above comment don't seem to be related though, because this PR doesn't modify those resources.

**Comment by ScottSuarez** [comment]
it looks like the apigee tests are failing because it's unable to update the billing type to null

```
          # google_apigee_organization.apigee_org must be replaced
        -/+ resource "google_apigee_organization" "apigee_org" {
              - billing_type       = "EVALUATION" -> null
              ~ ca_certificate     = "" -> (known after apply)
              ~ id                 = "organizations/tf-testnz49of6h07" -> (known after apply)
              ~ name               = "tf-testnz49of6h07" -> (known after apply)
              ~ subscription_type  = "TRIAL" -> (known after apply)
                # (4 unchanged attributes hidden)
            }
```

**Comment by ScottSuarez** [comment]
You should be able to fix this by using `default_from_api` in the terraform.yaml

https://github.com/GoogleCloudPlatform/magic-modules/blob/5268d03a79ba5644c9b8252175f642245881c8b7/mmv1/products/compute/terraform.yaml#L177-L179

**Comment by xuchenma** [comment]
Thanks, I added that. When testing locally I got errors like
`google/resource_apikeys_key.go:251:12: undefined: NewDCLApikeysClient`
that seems unrelated. I wonder if this will just pass in the CI system.

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
