### PR TITLE
Add Suport for `google_cloud_run_Job` to TGC

### PR DESCRIPTION
**Pull request by dvfons**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Thanks for the work!

Review pending internal discussion

**Comment by sushant00** [comment]
@dvfons Since this is a TGC-only change it should use release note type none and the content of the release note should be empty.

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
