### PR TITLE
use patch instead of put to update router

### PR DESCRIPTION
**Pull request by danawillow**
-----------------------------------------------------------------
# [all]
use patch instead of put to update router
## [terraform]
use patch instead of put to update router. Fixes #1778.

### CODE REVIEW

**Comment by danawillow** [comment]
huh, any idea why this didn't generate anything for chef?

**Comment by ndmckinley** [comment]
Is router already available in Chef?  I didn't know that it was.  I'll check on that.

**Comment by ndmckinley** [comment]
Hm, it is, but I wonder if Chef knows about patch requests.  Checking on that.

**Comment by ndmckinley** [comment]
Got it, yeah, chef doesn't support `update_verb`.

**Pull request merged**
