### PR TITLE
Add deletion_protection to container cluster

### PR DESCRIPTION
**Pull request by c2thorn**
fixes https://github.com/hashicorp/terraform-provider-google/issues/10168
upgrade guide:  https://github.com/GoogleCloudPlatform/magic-modules/pull/9087

Creates `deletion_protection` which is enabled by default.
Commits are separated out for review convenience (except for test fixes)

Essentially used the same approach for `deletion_protection` and the state upgrader as in https://github.com/GoogleCloudPlatform/magic-modules/pull/3450/files

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
container: `google_container_cluster` now has `deletion_protection` enabled to `true` by default. When enabled, this field prevents Terraform from deleting the resource.
```

### CODE REVIEW

**Comment by c2thorn** [comment]
`TestAccContainerCluster_withAddons` is flaky with the same error in nightly

**Review by melinath — COMMENTED** [review]
LGTM - have you been able to manually confirm that the state upgrader works as expected?

**Comment by c2thorn** [comment]
> LGTM - have you been able to manually confirm that the state upgrader works as expected?

Yes, I've started with a minimally configured cluster on 4.83, tried to upgrade with the state upgrader and got a diff. Upgraded _with_ the state upgrader and there was no diff.

**Review by melinath — APPROVED** [review]

**Pull request merged**
