### PR TITLE
Add new resource for creating Whistle Mapping, Reconciliation and Backfill Pipeline Jobs for Healthcare Data Engine 

### PR DESCRIPTION
**Pull request by ashwinsshetty**
Add support for creating Whistle Mapping, Reconciliation and Backfill Pipeline for Healthcare Data Engine 

Link: https://cloud.google.com/healthcare-api/healthcare-data-engine/docs/reference/rest/v1/projects.locations.datasets.pipelineJobs/create

Fixes https://github.com/hashicorp/terraform-provider-google/issues/19412

```release-note: new-resource
`google_healthcare_pipeline_job`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
@trodge can you pick up review? I got preempted by some other work.

**Comment by trodge** [comment]
Would it be possible to add the fields from the missing test report to an example or else add a test that includes them?

**Review by trodge — CHANGES_REQUESTED** [review]
Overall LGTM, but would like to see more complete test coverage if possible.

**Review by trodge — APPROVED** [review]

**Comment by ashwinsshetty** [comment]
Thanks @trodge for the review and approval. Do we need anything else to MERGE this.

**Pull request merged**
