### PR TITLE
add minItems for the required field scopes

### PR DESCRIPTION
**Pull request by edwardmedia**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/8792

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: added minimum for `scopes` field to `google_compute_instance` resource
```

### CODE REVIEW

**Comment by melinath** [comment]
@edwardmedia Could you elaborate on this fix? I can see how requiring at least one scope would prevent a user from encountering the described behavior, and I don't think we necessarily need to support empty scopes to provide a good user experience.

Does the API support empty scopes? Is the user correct that sending an empty scopes field + no email should give us the default service account but without any scopes?

**Comment by edwardmedia** [comment]
@melinath api does accept empty list of `scopes` but appears it does nothing. But it causes diff on tf side

```
{
 "scopes": [
 ]
}
```

**Review by melinath — APPROVED** [review]
Given that the API accepts no email + empty scopes but doesn't actually return any created objects - I'm fine with us requiring this input on the client side. A stricter interpretation could be to require either email or scopes, but I think that we can just say we don't support an empty scopes placeholder.

The test failure is unrelated.

**Comment by alsyia** [comment]
My thoughts on the default behaviour (no email + empty scopes results in default SA without scopes) came from the provider doc, here: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#email

Thanks for the quick fix, I will just add a scope to my instances :)

**Pull request merged**
