### PR TITLE
Add product backupdr with managementServer resource 

### PR DESCRIPTION
**Pull request by umeshkumhar**
This PR introduces a new gcp product backupdr and have resource to manage managementServer 

This is the raised issue [11319](https://github.com/hashicorp/terraform-provider-google/issues/13319), though it's not directly connected, but part of provisioning the backupdr management console.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_backup_dr_management_server`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_backup_dr_management_server` (0 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```terraform
> resource "google_backup_dr_management_server" "primary" {
>   location = # value needed
>   name     = # value needed
>   networks {
>     network      = # value needed
>     peering_mode = # value needed
>   }
>   type = # value needed
> }
> ```

@trodge Looks like the missing test detector has a false positive here. Any idea whats going on?

**Comment by trodge** [comment]
> > ## Missing test report
> > Your PR includes resource fields which are not covered by any test.
> > Resource: `google_backup_dr_management_server` (0 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> > ```terraform
> > resource "google_backup_dr_management_server" "primary" {
> >   location = # value needed
> >   name     = # value needed
> >   networks {
> >     network      = # value needed
> >     peering_mode = # value needed
> >   }
> >   type = # value needed
> > }
> > ```
> 
> @trodge Looks like the missing test detector has a false positive here. Any idea whats going on?

Looks like the resource name was wrong in the test and has since been fixed.

**Comment by ScottSuarez** [comment]
> > > ## Missing test report
> > > Your PR includes resource fields which are not covered by any test.
> > > Resource: `google_backup_dr_management_server` (0 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> > > ```terraform
> > > resource "google_backup_dr_management_server" "primary" {
> > >   location = # value needed
> > >   name     = # value needed
> > >   networks {
> > >     network      = # value needed
> > >     peering_mode = # value needed
> > >   }
> > >   type = # value needed
> > > }
> > > ```
> > 
> > 
> > @trodge Looks like the missing test detector has a false positive here. Any idea whats going on?
> 
> Looks like the resource name was wrong in the test and has since been fixed.

Ahh ! gotcha !! thanks for taking a look :) 

Sorry for the noise

**Comment by ScottSuarez** [comment]
> Error message

```
        Error: Error creating ManagementServer: googleapi: Error 400: The request was invalid: the network "projects/-------/global/networks/-----" has not been peered with Google managed services
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "field": "networks"
              }
            ]
          },
          {
            "@type": "type.googleapis.com/google.rpc.RequestInfo",
            "requestId": "44fce9726c306f50"
          }
        ]
        
          with google_backup_dr_management_server.ms-console,
          on terraform_plugin_test.tf line 6, in resource "google_backup_dr_management_server" "ms-console":
           6: resource "google_backup_dr_management_server" "ms-console" {

```

**Comment by umeshkumhar** [comment]
Please review https://github.com/GoogleCloudPlatform/magic-modules/pull/8568

Closed this by mistake

**Pull request closed without merging**
