### PR TITLE
Terraform Support for Secret Manager CSI addon GA Version

### PR DESCRIPTION
**Pull request by riddhi-google**
Changed condition in  ```secret_manager_config``` in ```google_container_cluster``` to work for Secret Manager CSI addon GA version.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:
container: changed `secret_manager_config` field in `google_container_cluster` resource to work for GA version.

```

### CODE REVIEW

**Review by NickElliot — CHANGES_REQUESTED** [review]
Hi, the build is failing due to some likely improper handling of version guards over these and potentially other files. Could you resolve the build issues then send it back up for review? Thanks!
```
Error: google/services/container/resource_container_cluster.go:2074:3: unknown field SecretManagerConfig in struct literal of type "google.golang.org/api/container/v1".Cluster
Error: google/services/container/resource_container_cluster.go:2678:78: cluster.SecretManagerConfig undefined (type *"google.golang.org/api/container/v1".Cluster has no field or method SecretManagerConfig)
Error: google/services/container/resource_container_cluster.go:36[11](https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/9751023302/job/26911721694#step:9:12):5: unknown field DesiredSecretManagerConfig in struct literal of type "google.golang.org/api/container/v1".ClusterUpdate
Error: google/services/container/resource_container_cluster.go:4820:67: undefined: container.SecretManagerConfig
Error: google/services/container/resource_container_cluster.go:4827:20: undefined: container.SecretManagerConfig
Error: google/services/container/resource_container_cluster.go:5615:46: undefined: container.SecretManagerConfig
```

**Comment by riddhi-google** [comment]
Hi, The GA version is not out yet, which is probably causing an issue in the BUILD. I will mark this as a draft for the time being.

**Review by NickElliot — CHANGES_REQUESTED** [review]
the build failing is unrelated to the actual API atm, just the template syntax. let me know when its ready for review!

**Pull request closed without merging**
