### PR TITLE
Made exclude_resource not exclude tests

### PR DESCRIPTION
**Pull request by melinath**
There are cases where the test may be handwritten but there are tests that are intended to be generated. This previously wasn't happening because excluding resource generation also excluded test generation.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by slevenick** [comment]
I'm curious what the goal is here with exclude_resource. My understanding (and why I implemented it) is that it is for generated IAM resources that don't map to a real resource (or the resource is implemented via other means like handwritten or DCL).

Is that still the case?

**Comment by slevenick** [comment]
For example, https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6848-old..auto-pr-6848#diff-95399c161a4a569088a4425aa1282083b3ff9f8f040b8b1920f5495acd8f966fR26 shouldn't exist

**Comment by melinath** [comment]
@slevenick the goal here is to allow generating tests for handwritten resources. For example, `TestAccDialogflowCXEnvironment_dialogflowcxEnvironmentFullExample` can be generated but was previously forced to be handwritten.

Makes sense that if there isn't a root resource (but is an IAM resource) we would want to skip....... non-IAM tests. Hmm, I'm not sure there's a good way to do that. I don't really want to add a `skip_iam_tests` property. I'll have to think about it.

**Comment by melinath** [comment]
Closing this PR as I won't have time to complete it.

**Pull request closed without merging**
