### PR TITLE
Adding enableConfidentialCompute field for Hyperdisk

### PR DESCRIPTION
**Pull request by NA2047**
Adding in ablity to enable Confidential Compute for Hyper disk on beta

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added field `enableConfidentialCompute` for `google_compute_disk` resource
```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
Could you add a test for this field? Or add this field in an existing test.

**Comment by hao-nan-li** [comment]
Looks like the added test did not run in the VCR-test. Could you confirm it passed locally?

**Comment by NA2047** [comment]
> Looks like the added test did not run in the VCR-test. Could you confirm it passed locally?

This may have something to do with `<% unless version = 'ga' -%>...<% end -%>` that I wrapped the test in due to this only being a beta feature. But worked when I ran make test

**Comment by hao-nan-li** [comment]
> > Looks like the added test did not run in the VCR-test. Could you confirm it passed locally?
> 
> This may have something to do with `<% unless version = 'ga' -%>...<% end -%>` that I wrapped the test in due to this only being a beta feature. But worked when I ran make test without this as well

Thanks for the confirmation.

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
