### PR TITLE
Add google_composer_environment data source

### PR DESCRIPTION
**Pull request by FromZeus**
Resolved hashicorp/terraform-provider-google#7826

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
composer: added datasource for `google_composer_environment`
```

### CODE REVIEW

**Comment by FromZeus** [comment]
@googlebot I signed it!

**Comment by ndmckinley** [comment]
Looks great, let me get the tests run.  /gcbrun.

**Comment by FromZeus** [comment]
@ndmckinley please take a look at the PR if you have spare time :)

**Comment by ndmckinley** [comment]
Were you able to get the new test to pass on your machine?

```
------- Stdout: -------
=== RUN   TestAccDataSourceComposerEnvironment_basic
=== PAUSE TestAccDataSourceComposerEnvironment_basic
=== CONT  TestAccDataSourceComposerEnvironment_basic
TestAccDataSourceComposerEnvironment_basic: provider_test.go:266: Step 1/1 error: Error running pre-apply refresh: 2020/11/16 23:15:31 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: "name" ("data_google_composer_environment_test") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
on config710596132/terraform_plugin_test.tf line 3, in data "google_composer_environment" "composer_env":
3:   name = "data_google_composer_environment_test"
--- FAIL: TestAccDataSourceComposerEnvironment_basic (3.56s)
FAIL
```

**Comment by FromZeus** [comment]
> Were you able to get the new test to pass on your machine?
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccDataSourceComposerEnvironment_basic
> === PAUSE TestAccDataSourceComposerEnvironment_basic
> === CONT  TestAccDataSourceComposerEnvironment_basic
> TestAccDataSourceComposerEnvironment_basic: provider_test.go:266: Step 1/1 error: Error running pre-apply refresh: 2020/11/16 23:15:31 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
> Error: "name" ("data_google_composer_environment_test") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
> on config710596132/terraform_plugin_test.tf line 3, in data "google_composer_environment" "composer_env":
> 3:   name = "data_google_composer_environment_test"
> --- FAIL: TestAccDataSourceComposerEnvironment_basic (3.56s)
> FAIL
> ```

Oops, sorry, I've changed the name of the test environment after I did tests on my own environment :)

**Comment by FromZeus** [comment]
@ndmckinley hey! Could you please take a look when you've got some time?

**Comment by ndmckinley** [comment]
Ah, thanks for the ping!  Let me rerun those.  /gcbrun

**Comment by ndmckinley** [comment]
> @ndmckinley hey! Could you please take a look when you've got some time?

Hey, sorry:
```
------- Stdout: -------
=== RUN   TestAccDataSourceComposerEnvironment_basic
=== PAUSE TestAccDataSourceComposerEnvironment_basic
=== CONT  TestAccDataSourceComposerEnvironment_basic
TestAccDataSourceComposerEnvironment_basic: testing_new_config.go:71: no "id" found in attributes
TestAccDataSourceComposerEnvironment_basic: testing_new.go:48: no "id" found in attributes
--- FAIL: TestAccDataSourceComposerEnvironment_basic (7.41s)
FAIL
```

**Comment by FromZeus** [comment]
@ndmckinley hm, that's weird, locally the tests are passed
```
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccDataSourceComposerEnvironment_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceComposerEnvironment_basic
=== PAUSE TestAccDataSourceComposerEnvironment_basic
=== CONT  TestAccDataSourceComposerEnvironment_basic
--- PASS: TestAccDataSourceComposerEnvironment_basic (6.62s)
PASS
ok  	github.com/hashicorp/terraform-provider-google/google	6.638s
```
Also I found some weird issue with composer environment creation when I was trying to use `data-google-composer-environment-test` name for the environment, so I've changed the name of test env once again.
```
Use of this bucket name is restricted: 'us-central1-data-google-com-cb1e6a07-bucket'
```

**Comment by ndmckinley** [comment]
Let's try one more time.  If it fails again I'll go ahead and run it locally and try to debug.  /gcbrun

**Comment by ndmckinley** [comment]
Same problem unfortunately!  I'll clone it locally and see what I can see.

**Comment by ndmckinley** [comment]
Same thing happens on my machine, exact same.  Never seen this error before, but it only happens on your PR.  The tests are passing for you?

**Comment by ndmckinley** [comment]
Okay, our theory is that the issue is that the config does not create the resource that the data source reads.  Take a look at https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/data_source_cloud_run_service_test.go#L53, for example, where the data source reads from a resource that is also created.  We think it's passing for you since that resource exists in your environment (but not in ours), and we think the error message is just confusing and if that resolves your problem we'll ask HashiCorp to edit it to make it clearer.

**Comment by FromZeus** [comment]
@ndmckinley Gotcha, didn't know how they are hooked up, thank you! Updated the PR.

**Comment by FromZeus** [comment]
@ndmckinley hey) Could you please take a look and run /gcbrun if you've got a time?

**Comment by ndmckinley** [comment]
Hi there - /gcbrun - thanks, we were off for the thanksgiving holiday.  :)

**Comment by FromZeus** [comment]
Ah, right, happy belated thanksgiving! :)

**Comment by ndmckinley** [comment]
Looks good to me!

**Review by ndmckinley — APPROVED** [review]

**Pull request merged**
