### PR TITLE
Promote fleet observability feature in GKE Hub to GA

### PR DESCRIPTION
**Pull request by JeffLuoo**
Promote `fleetobservability` feature to GA

fixes https://github.com/hashicorp/terraform-provider-google/issues/15045.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
gkehub: promoted the `google_gke_hub_feature` resource's `fleetobservability` block to GA.
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Hi @JeffLuoo , thanks for this PR! Currently the Beta provider is experiencing this error when the tests run:

> Error: google-beta/resource_gke_hub_feature_membership_test.go:91:9: undefined: gkeHubFeatureProjectSetup

It looks like this function was [deleted in this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/8268/files#diff-0c34114cf41d722c346d40611e301fe395813645c22aed2cbb46555154760adfL147), so the fix should be to re-introduce that code

**Comment by JeffLuoo** [comment]
> 

Updated. Thanks for the instruction!

**Comment by JeffLuoo** [comment]
I tested it locally in my own gcp projects and it passed.

```
--- PASS: TestAccGKEHubFeature_gkehubFeatureFleetObservability (245.40s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   245.723s
```

Can you please take another look? @SarahFrench

Thanks!

**Review by trodge — APPROVED** [review]

**Pull request merged**
