### PR TITLE
update dcl to 1.70

### PR DESCRIPTION
**Pull request by c2thorn**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
gkehub: added `config_management.management` and `config_management.config_sync.enabled` fields to `google_gkehub_feature_membership`
```
```release-note:enhancement
clouddeploy: added `gke.proxy_url` field to `google_clouddeploy_target`
```

### CODE REVIEW

**Review by c2thorn — COMMENTED** [review]
current failing tests are already failing on main

**Comment by c2thorn** [comment]
@zli82016 all currently running tests are already failing on main

**Review by zli82016 — APPROVED** [review]
LGTM

**Comment by henrybell** [comment]
Hi, was this intended to be a breaking change? I am finding that unless I include `enabled = true` in the `config_sync` stanza within the `google_gke_hub_feature_membership` resource, the Config Sync components do not get installed in my clusters, which is different behaviour from provider versions prior to v5.41.0. I was also able to find [this documentation update](https://github.com/hashicorp/terraform-provider-google/pull/19329) which also [suggests](https://github.com/hashicorp/terraform-provider-google/pull/19329/files#diff-52b90c89e6a3904f63f4c2ab4016913bf854d4406a6ca681146e83070f526f6bR356) that it is now mandatory to include `enabled = true` for the Config Sync components to be installed. If this is a breaking change, I wonder if perhaps it could be made (even) clearer in the documentation/changelog/etc -- thanks!

**Comment by zli82016** [comment]
Hello, @henrybell , the breaking change was not intended. The contributor is working on the fix.

**Comment by henrybell** [comment]
Thanks @zli82016 for the update, greatly appreciated.

**Pull request merged**
