### PR TITLE
Added merging logic for organization policy

### PR DESCRIPTION
**Pull request by rdayama-eng**

### CODE REVIEW

**Comment by rdayama-eng** [comment]
@rileykarson @morgante Please take a look

**Comment by rileykarson** [comment]
Reassigning from @c2thorn as they're out. @melinath: mind taking a look?

**Comment by morgante** [comment]
This looks fine to me.

**Comment by melinath** [comment]
/gcbrun

@rdayama-eng could you add a [release note comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/4250#issuecomment-729919789) and give a brief summary (1-3 paragraphs, ideally in the PR description) of what the purpose of this change is, and how this PR accomplishes that purpose? I see that you're adding a function but I don't understand what it's for; also, it doesn't seem to be referenced by anything.

**Comment by rdayama-eng** [comment]
> /gcbrun
> 
> @rdayama-eng could you add a [release note comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/4250#issuecomment-729919789) and give a brief summary (1-3 paragraphs, ideally in the PR description) of what the purpose of this change is, and how this PR accomplishes that purpose? I see that you're adding a function but I don't understand what it's for; also, it doesn't seem to be referenced by anything.

As org policy is a list inside Asset. This function is added to merge multiple org policy related to same asset into one list. I have raised a corresponding PR in terraform validator
https://github.com/GoogleCloudPlatform/terraform-validator/pull/157

**Review by melinath — APPROVED** [review]
From examining the code in the linked PR, it looks like this code is used inside of [terraform-validator/converters/google/mappers.go](https://github.com/GoogleCloudPlatform/terraform-validator/pull/157/files#diff-b2f0f747f0ffe0f5e010cf35b406dab9b2624e74cc0775764b1740c8b41c5359R78), which fits the format of `N:1 = [mapper{convert: convertAbc, merge: mergeAbc}] (len=1)`.

I am approving this because it seems like it is probably fine and in line with the way other surrounding IAM policies are handled. The other Merge functions are also defined in `magic-modules/third_party` and are also untested. Additionally, if there is any issue with terraform-validator, that seems like it should be picked up before the PR merge on their side (and this won't impact any other code generated by magic-modules.)

In the interests of not repeating code, I just wanted to double-check that neither of the existing helper functions (mergeAuthoritativeBindings and mergeAdditiveBindings) would work for your use case?

**Comment by rdayama-eng** [comment]
> From examining the code in the linked PR, it looks like this code is used inside of [terraform-validator/converters/google/mappers.go](https://github.com/GoogleCloudPlatform/terraform-validator/pull/157/files#diff-b2f0f747f0ffe0f5e010cf35b406dab9b2624e74cc0775764b1740c8b41c5359R78), which fits the format of `N:1 = [mapper{convert: convertAbc, merge: mergeAbc}] (len=1)`.
> 
> I am approving this because it seems like it is probably fine and in line with the way other surrounding IAM policies are handled. The other Merge functions are also defined in `magic-modules/third_party` and are also untested. Additionally, if there is any issue with terraform-validator, that seems like it should be picked up before the PR merge on their side (and this won't impact any other code generated by magic-modules.)
> 
> In the interests of not repeating code, I just wanted to double-check that neither of the existing helper functions (mergeAuthoritativeBindings and mergeAdditiveBindings) would work for your use case?

mergeAuthoritativeBindings and mergeAdditiveBindings won't work, as this a different use case

**Comment by melinath** [comment]
Sorry for the delayed merge; I forgot that the procedure is that my team does merges on this repo. :-) Here you go!

**Pull request merged**
