### PR TITLE
Fix spacing of resource template

### PR DESCRIPTION
**Pull request by trodge**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
No issues with the concept. Thumbs up form me. Assigning Riley for approval

**Review by rileykarson — COMMENTED** [review]
We have `custom_create` already so adding this as an entrypoint feels fine. What I do want to make sure we do is avoid using it unless _absolutely_ necessary- it's very easy to miss that a resource has a custom method and leave out new fields, for example. Let's upgrade the warning not to use both this + `custom_create` unless there are zero other options.

Additionally, could you minimise the spacing changes and keep the file consistently using spaces instead of tabs?

**Comment by trodge** [comment]
> We have `custom_create` already so adding this as an entrypoint feels fine. What I do want to make sure we do is avoid using it unless _absolutely_ necessary- it's very easy to miss that a resource has a custom method and leave out new fields, for example. Let's upgrade the warning not to use both this + `custom_create` unless there are zero other options.
> 
> Additionally, could you minimise the spacing changes and keep the file consistently using spaces instead of tabs?

Which warning are you referring to?

**Comment by rileykarson** [comment]
Sorry- I mean let's add an explicit warning not to use 'em.

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
