### PR TITLE
Add Region Instance Template resource and datasource into beta provider

### PR DESCRIPTION
**Pull request by jingcongw**
Note: Resubmit the changes for RIT resource and ds, the original changes are reverted in [PR](https://github.com/GoogleCloudPlatform/magic-modules/commit/11f9ba6c6165242c92b77d79e52b66d51b70298d) due to breaking changes in API. This PR wraps previous changes in the beta guard and this time we are going to release to beta provider.

Background

Regional Instance Template (later: RIT) is a new regional resource, implementing the functionality of [Instance Templates](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates) existing before only in the global scope. More details can be found: [go/rit-support-in-terraform](https://goto.google.com/rit-support-in-terraform).

There is already a handwritten global scope [google_compute_instance_template](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template) Terraform resource and as we implement the new RIT resource, we want to give customers a smooth migration experience from GIT to RIT, the decision is to hand write RIT as GIT to keep the resource representation consistent. More info can be found: [go/rit-resource-inconsistency](https://goto.google.com/rit-resource-inconsistency)

Changes include:

1. Add Region Instance Template datasource, acceptance tests and document.
2. Add Region Instance Template resource, acceptance tests and document.
3. Modify existing google_compute_instance_from_template resource to consume RIT as source instance template.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_compute_region_instance_template`
```
```release-note:new-datasource
`google_compute_region_instance_template`
```
```release-note:enhancement
compute: supported region instance template in`source_instance_template` field of `google_compute_instance_from_template` resource
```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
Looks like not all fields are covered by the tests. The current test detector could mistakenly identify tested fields as untested, but there are couple fields such as `source_snapshot_encryption_key` that need to be added in.

**Comment by hao-nan-li** [comment]
Quick notes: network_performance_config is tested https://github.com/GoogleCloudPlatform/magic-modules/blob/7f6027737020143dc5c2f2b45694f84d586d41af/mmv1/third_party/terraform/tests/resource_compute_instance_test.go.erb#L5265

**Comment by hao-nan-li** [comment]
Could you change the release note following https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md?

**Comment by jingcongw** [comment]
```release-note:new-resource
`google_compute_region_instance_template`
```
```release-note:new-datasource
`google_compute_region_instance_template`
```
```release-note:enhancement
compute: supported region instance template in`source_instance_template` field of `google_compute_instance_from_template` resource
```

These notes I put in PR description are following the sample notes in guide. Did I miss anything?

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
