### PR TITLE
Remove gke_hub as part of the DCL endpoints

### PR DESCRIPTION
**Pull request by hao-nan-li**
part of https://github.com/hashicorp/terraform-provider-google/issues/20246

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:none

```

### CODE REVIEW

**Comment by hao-nan-li** [comment]
@roaks3 Looks like this change didn't really affect any of the existing test for gkehub, maybe this is not the root cause. Can we still merge it since this line is no longer being used and could potentially cause confusion?

**Review by roaks3 — APPROVED** [review]
Sounds good, but might want to remove the `fixes: ` from the description if this doesn't fully resolve that issue.

**Comment by hao-nan-li** [comment]
> Sounds good, but might want to remove the `fixes: ` from the description if this doesn't fully resolve that issue.

Good point, will take that part off.

**Comment by hao-nan-li** [comment]
> > Sounds good, but might want to remove the `fixes: ` from the description if this doesn't fully resolve that issue.
> 
> Good point, will take that part off.

On a second thought, this might be the right fix, since the VCR runs on beta and removing this line doesn't affect anything because everything was already running in beta. I'll check in the nightly runs and see if this fixed the issue.

**Pull request merged**
