### PR TITLE
Promote Memcached to GA

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8901

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new_resource
`google_memcache_instance`
```

### CODE REVIEW

**Comment by upodroid** [comment]
I'm hoping this promotion doesn't become `google_billing_budget` 2.0. That resource was bug ridden after it went GA.

```
 REDACTED  MCW0CDP3YY  ~  go  …  github.com  hashicorp  terraform-provider-google   master  13⬇  3✎  4+  $    make testacc TEST=./google TESTARGS='-run=TestAccMemcacheInstance_memcacheInstanceBasicExample'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccMemcacheInstance_memcacheInstanceBasicExample -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccMemcacheInstance_memcacheInstanceBasicExample
=== PAUSE TestAccMemcacheInstance_memcacheInstanceBasicExample
=== CONT  TestAccMemcacheInstance_memcacheInstanceBasicExample
2021/04/17 00:16:13 [INFO] Authenticating using DefaultClient...
2021/04/17 00:16:13 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/04/17 00:16:13 [DEBUG] Getting shared test network "tf-bootstrap-net-memcache-private"
2021/04/17 00:16:13 [INFO] Instantiating GCE client for path https://compute.googleapis.com/compute/v1/projects/
2021/04/17 00:16:13 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/04/17 00:16:13 [DEBUG] Retry Transport: request attempt 0
2021/04/17 00:16:14 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/04/17 00:16:14 [DEBUG] Retry Transport: Returning after 1 attempts
2021/04/17 00:16:14 [INFO] Instantiating GCE client for path https://compute.googleapis.com/compute/v1/projects/
2021/04/17 00:16:14 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/04/17 00:16:14 [DEBUG] Retry Transport: request attempt 0
2021/04/17 00:16:14 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/04/17 00:16:14 [DEBUG] Retry Transport: Returning after 1 attempts
--- PASS: TestAccMemcacheInstance_memcacheInstanceBasicExample (536.97s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   538.004s
```

**Review by slevenick — CHANGES_REQUESTED** [review]
We will also want to GA this file: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/tests/resource_memcache_instance_test.go.erb

**Comment by upodroid** [comment]
It is fixed now.

**Review by slevenick — CHANGES_REQUESTED** [review]
Looks like the build fails now because the test file isn't formatted correctly and `gofmt` doesn't get run on non-erb files.

```
gofmt needs running on the following files:
./google-beta/resource_memcache_instance_test.go
You can use the command: `make fmt` to reformat code.
```

You can either format the file correctly or just convert it back to an erb so it will happen automatically

**Comment by upodroid** [comment]
Fixed

**Review by slevenick — APPROVED** [review]
Thanks!

**Pull request merged**
