### PR TITLE
products/container: Add datapath provider field

### PR DESCRIPTION
**Pull request by brancz**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests. (I think I might have not done all the changes required though as I couldn't see changes in the generated terraform)
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests). (I can't see any GKE examples in this directory, are they maybe somewhere else?)
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Add support for `datapath_provider` to `google_container_cluster`
```

Fixes https://github.com/hashicorp/terraform-provider-google/issues/7207

My apologies in advance as I feel I haven't found where to do all the changes necessary. I would appreciate a hint where else changes might be necessary.

### CODE REVIEW

**Comment by brancz** [comment]
Fixed the changelog entry to be `enhancement`.

**Review by ndmckinley — CHANGES_REQUESTED** [review]
Hi there - you might want to make these changes in third_party/terraform/resources/resource_container_cluster, unfortunately this resource is not autogenerated in the same way as others.

**Comment by brancz** [comment]
I can't view the google cloud builds. Can someone help me figure out why they are failing?

**Comment by brancz** [comment]
I created a cluster with this patch and it appears to work! :)

**Comment by ndmckinley** [comment]
Awesome!  Looks great, the tests are failing because of a mismatch in the test file:

```
# github.com/hashicorp/terraform-provider-google-beta/google-beta [github.com/hashicorp/terraform-provider-google-beta/google-beta.test]
google-beta/resource_container_cluster_test.go:1803:13: undefined: testAccContainerCluster_withDatapath
```

Looks like the function is called `testAccContainerCluster_withDatapathProvider` - just a typo.  :)

**Comment by ndmckinley** [comment]
That'll fix one of them, the other one is going to require me to authorize it, which I will do as soon as the first one passes.  :)

**Comment by brancz** [comment]
My bad, should be fixed now! :)

**Comment by brancz** [comment]
If I understand correctly I need a maintainer to run a command to trigger the google cloud build.

**Comment by slevenick** [comment]
Ack, ignore that. It requires a file to exist that hasn't been merged yet, my bad

**Comment by slevenick** [comment]
If you rebase off of current master it should add the required files to make the trigger work

**Comment by brancz** [comment]
Done :)

**Comment by slevenick** [comment]
Huh... it got stuck.

/gcbrun

**Comment by slevenick** [comment]
Looks like that new test is failing with the following error:
```
TestAccContainerCluster_withAdvancedDatapath: testing.go:674: Step 0 error: errors during apply:
Error: googleapi: Error 400: GKE Dataplane v2 is only available in cluster versions 1.17.9 and up., badRequest
```

Are you able to successfully run this test locally?

**Comment by brancz** [comment]
My apologies I tried it in my own setup which uses the "RAPID" release channel, where this is the version. I updated the test to also do this, hopefully, that works now.

**Review by ndmckinley — APPROVED** [review]

**Comment by cagataygurturk** [comment]
I tried changing one of my clusters which is running on 1.19 to ADVANCED_DATAPATH. My expectation was to get an error because first data plane v2 is not supported on this version and second that setting is immutable but the modification was complete. Of course the changes are not persisted on the cluster configuration.

**Pull request merged**
