### PR TITLE
Make the `destination.cloud_function` field on google_eventarc_trigger output only, update field description in docs

### PR DESCRIPTION
**Pull request by SarahFrench**
The [API docs describe this field](https://cloud.google.com/eventarc/docs/reference/rest/v1/projects.locations.triggers#destination) as output only:

>The Cloud Function resource name. Only Cloud Functions V2 is supported. Format: projects/{project}/locations/{location}/functions/{function}This is a read-only field. Creating Cloud Functions V2 triggers is only supported via the Cloud Functions product. An error will be returned if the user sets this value.

In this PR I'm updating the schema for this field so it's Computed and not Optional, and also updating [the provider documentation for this field](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger#cloud_function) to match the API docs.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
eventarc: made the `destination.cloud_function` field on `google_eventarc_trigger` an output. Previously when users attempted to set this in their configuration it caused an API error.
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Re: [the breaking change detector](https://github.com/GoogleCloudPlatform/magic-modules/pull/9820#issuecomment-1892584649), I believe this isn't a breaking change because if a user tried to set this value in a Terraform configuration it would cause an API error (the TF config wouldn't be valid so cannot become broken).

**Comment by SarahFrench** [comment]
Does the breaking change detector block running acceptance tests?

**Comment by SarahFrench** [comment]
I've triggered eventarc tests to run on this PR's upstream GA branch here: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_MmUpstreamTesting_GOOGLE_PACKAGE_EVENTARC/87866?branch=%3Cdefault%3E&buildTypeTab=overview&buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false

**Comment by rileykarson** [comment]
@NickElliot and I took a look here- VCR didn't run because there was no diff in beta. You'll want to apply the same changes to https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/overrides/eventarc/beta/trigger.yaml probably?

**Comment by SarahFrench** [comment]
Ah, sorry I overlooked that I'd need to implement this separately for Beta - I'll do that now

**Comment by SarahFrench** [comment]
No Diff Report? /gcbrun

**Comment by SarahFrench** [comment]
The last run failed with:

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'll retry - /gcbrun

**Review by NickElliot — APPROVED** [review]
LGTM

**Comment by SarahFrench** [comment]
Thanks!

**Pull request merged**
