### PR TITLE
Add new data source google_compute_instance_template

### PR DESCRIPTION
**Pull request by mweibel**
Fixes hashicorp/terraform-provider-google#365.

Adds a new data source for instance templates. Allows to retrieve instance templates either by name or using a filter (allowing for name regex using e.g. `filter = "name eq .*-${var.name}-tpl-.*"`). `most_recent` orders (client side, as not supported by API) retrieved instances by creation timestamp and retrieves the latest one. 

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_compute_instance_template`
```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
Generally LGTM. One last thing, are you able to add a documentation page to https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/website/docs/d? Thanks!

**Comment by mweibel** [comment]
I added a doc page and currently trying to locally render the website - doesn't yet work though. So I couldn't yet see how it will look like.

**Comment by mweibel** [comment]
Ok I can't get the website `make` target to run properly. When I run it, the provider docs aren't found and it seems that's an issue with the terraform-website repo, but I'm not sure - didn't want to invest more time.

**Review by rileykarson — APPROVED** [review]
Ah, `make website` broke out of the blue a few weeks ago and hasn't been fixed since. Weirdly enough it works for me, but nobody else on the provider team.

LGTM. Thanks for your contribution!

**Comment by mweibel** [comment]
I see ;) 

Thanks for merging! Do you happen to know any release date for this change? :)

**Comment by rileykarson** [comment]
I believe Jan 18th (`3.53.0`), this was merged ~a day after the Jan 11th (`3.52.0`) branch cut!

**Pull request merged**
