### PR TITLE
Add Pub/Sub Lite Resources

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7924

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_pubsub_lite_topic`
```
```release-note:new-resource
`google_pubsub_lite_subscription`
```

### CODE REVIEW

**Comment by upodroid** [comment]
Tests are passing but MM is creating weird duplicate code.

Again this is another dodgy API that wants project number instead of project id. 

I opened b/175033264 to get it fixed and earlier TPU was doing it (b/167838005) which was fixed later too. Handling this transformation isn't fun and Google should be writing consistent API interfaces.

**Comment by upodroid** [comment]
```
 REDACTED  MCW0CDP3YY  ~  go  …  github.com  hashicorp  terraform-provider-google-beta   master  37⬇  5✎  16+  $    make testacc TEST=./google-beta TESTARGS="-run TestAccPubsubLite"
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run TestAccPubsubLite -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample
=== PAUSE TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample
=== RUN   TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample
=== PAUSE TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample
=== CONT  TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample
=== CONT  TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample
--- PASS: TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample (42.20s)
--- PASS: TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample (45.48s)
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta 46.463s
```

**Comment by ndmckinley** [comment]
All right!  Let me see if those tests pass - /gcbrun - but if they do, this looks great to me.  Let me look into that duplicate code situation.

**Comment by upodroid** [comment]
I was pointed to an interesting AIP. The cloud apis can accept project ids or numbers when receiving requests but will always return the project number. Looks like we need to write a diff suppression for that behaviour

**Comment by ndmckinley** [comment]
Yeah, we've seen that once or twice before.  Storage bucket, I believe, is our most annoying case of it.  It's very annoying because mapping a project name to a project number is not easy and is usually done with a call to the compute api, and some people don't like to have the compute api enabled on projects that don't otherwise use it.

**Comment by ndmckinley** [comment]
Looks great - the duplicate code is intended, as far as I can tell, the tests all pass. :)

**Review by ndmckinley — APPROVED** [review]

**Pull request merged**
