### PR TITLE
Add support for `advanced_datapath_observability_config` to `google_container_cluster`

### PR DESCRIPTION
**Pull request by epk**
Opened in place of https://github.com/GoogleCloudPlatform/magic-modules/pull/8372

Adds support for https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability#configure-gke-dataplane-v2-metrics

---

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added support for `advanced_datapath_observability_config` to `google_container_cluster`
```

cc @rileykarson

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
Sorry, I lost track of the original! @NickElliot do you mind picking this up? I've been behind on reviews.

**Review by NickElliot — CHANGES_REQUESTED** [review]
Looks like the test is failing with the following: 
```Error: googleapi: Error 400: Clusters with DatapathProvider=ADVANCED_DATAPATH must set IPAllocationPolicy.UseIPAliases to true.```

Unfortunately, it looks like that conflicting field is not currently in our resource, and will also need to be added for support of this feature to be added (along with corresponding test case updates). Sorry for the expanded scope of this update!

**Comment by rileykarson** [comment]
UseIPAliases is also known as VPC native clusters, see https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#vpc-native-clusters for how to configure.

**Comment by epk** [comment]
Updated the test tf files to create a VPC native cluster

**Review by NickElliot — COMMENTED** [review]
The test is now failing on the 2nd version with `AdvancedDatapathObservability relay_mode EXTERNAL_LB is not supported in current cluster version.`, which would be because the current stable GKE release does not support it yet (even the [user guide](https://cloud.google.com/kubernetes-engine/docs/how-to/observe-your-traffic#inspect-network-traffic-in-single-namespace) does not reference it yet despite it being listed in the REST API reference). The test case could be updated to specify a `min_master_version` that supports the value, or really it would be fine to remove the test case entirely -- we don't need to test every individual ENUM value in Terraform, the goal of an update test is to demonstrate its ability to be updated in place and the swap between disabled and enabled already proves that functionality is stable.

**Comment by epk** [comment]
Dropped the second test case (`testAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfigUpdated`)

**Review by NickElliot — APPROVED** [review]
LGTM!

**Pull request merged**
