### PR TITLE
Add support for Context Aware Access UserAccessBinding resource

### PR DESCRIPTION
**Pull request by melinath**
Resolved https://github.com/hashicorp/terraform-provider-google/issues/7501

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
      ^ --- I'm not able to run acceptance tests (TestAccAccessContextManager) locally because they require a CUST_ID. However, you can see the results in the teamcity tests.
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
accesscontextmanager: Added support for `google_access_context_manager_gcp_user_access_binding`
```

### CODE REVIEW

**Comment by melinath** [comment]
Ran into some issues with this prior to break.

- `opRes` is not getting set correctly because the operation is coming back `done` right away
- Riley:
  > (as written now) the value that ultimately becomes opres needs to happen after the done check to handle operations that are not immediately done. I took a quick look at common_operation and can't see what's going wrong
  > Probably the most suspicious place to me is https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/common_operation.go#L139. Are we entering that if block? We should be, I think.

So, looking at the test output now, it turns out that a lot of the operations (Group, AccessPolicy, AccessLevel) come back `done` right away, and have similar structures to the GcpUserAccessBinding response. The difference is that they all have custom code for extracting the actual id from the response and setting it locally prior to read. I think that's what I probably need to do as well, rather than trying to find a bug in the core functionality.

**Comment by melinath** [comment]
Looking at this more, yes, I could handle it with custom code. But I think there is a bug in [createAccessContextManagerWaiter](https://github.com/hashicorp/terraform-provider-google-beta/blob/ab5caa4/google-beta/access_context_manager_operation.go#L38) - the operation returned apparently doesn't need to have a name.

**Comment by melinath** [comment]
It looks like the change to detect operations via metadata did the trick - [name is now properly extracted](https://ci-oss.hashicorp.engineering/repository/download/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr/165640:id/debug-google-beta-0eefbb3-TestAccAccessContextManager__gcp_user_access_binding.log)

**Comment by melinath** [comment]
At long last, the new tests are passing :-)

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
