### PR TITLE
Promote healthcare consent API to GA support

### PR DESCRIPTION
**Pull request by chaopeng**
Change healthcare consent API to GA support

Fix: https://github.com/hashicorp/terraform-provider-google/issues/8179

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Promote `google_healthcare_consent_store*` to GA support
```

### CODE REVIEW

**Comment by chaopeng** [comment]
cc @nmousavi

**Comment by ScottSuarez** [comment]
Hi @chaopeng, I notice the header says [not ready] .. that's no problem, but just @ me whenever it is :)

**Comment by chaopeng** [comment]
@ScottSuarez ready to review.

**Comment by chaopeng** [comment]
Hi @ScottSuarez, I am not able to see the `generate-diffs` failure log. Can you check what is the issue? Thank you

**Comment by ScottSuarez** [comment]
```
google/iam_healthcare_consent_store_generated_test.go:41:24: Sprintf format %d reads arg #1, but call has 0 args
google/iam_healthcare_consent_store_generated_test.go:51:24: Sprintf format %d reads arg #1, but call has 0 args
google/iam_healthcare_consent_store_generated_test.go:77:24: Sprintf format %d reads arg #1, but call has 0 args
google/iam_healthcare_consent_store_generated_test.go:102:24: Sprintf format %d reads arg #1, but call has 0 args
google/iam_healthcare_consent_store_generated_test.go:111:24: Sprintf format %d reads arg #1, but call has 0 args
```

**Comment by ScottSuarez** [comment]
curious... trying this locally :)

**Comment by ScottSuarez** [comment]
import format was incorrect. Since we don't run import tests on non-ga products it flew under the radar

**Comment by chaopeng** [comment]
@ScottSuarez sorry, it still fails

**Comment by chaopeng** [comment]
@ScottSuarez sorry, it still fails

**Comment by ScottSuarez** [comment]
@chaopeng failed due to an unrelated flakey test. This is good to go. Just going to wait for Sam to sign off

**Review by slevenick — APPROVED** [review]
Looks good to me! The escaped interpolated string is a little gross, but the whole system gets a little weird when a field can include `/` characters

**Pull request merged**
