### PR TITLE
Fixed review requests on issue comment from author

### PR DESCRIPTION
**Pull request by melinath**
According to https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment the data for comment creation should be in issue, not pull_request

Note that pull request comments (on specific lines of files) are separate and are currently intentionally not included here.

~This should be possible to test by having the reviewer leave a review, then having me leave a comment - I believe the issue comment portion of the logic should run based off of what is in this PR.~ This all runs off the main branch so it won't be possible to test before merge. However, I think the logic should be more clear now so I am more confident in it.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by melinath** [comment]
leaving a comment

**Comment by melinath** [comment]
leaving comment

**Comment by melinath** [comment]
another comment

**Comment by melinath** [comment]
🤦  nope, this also runs off the default branch.

**Comment by melinath** [comment]
Based on https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow it looks like the `created` event will not set `pull_request` at all. Which does technically match the [documented payload](https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment); I think I just thought they might do something clever. (But this is probably for the best!)

**Review by roaks3 — APPROVED** [review]
LGTM

**Pull request merged**
