### PR TITLE
Update `privateNetworkLinkRegex` to protect against values starting with `/projects...`

### PR DESCRIPTION
**Pull request by SarahFrench**
I've been triaging some old HashiCorp support tickets and there's an issue that was due to a resource being references using `/projects/{{project}}/....` instead of `projects/{{project}}/....`. This PR aims to improve provider-side validation to discourage this type of error.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] ~~Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).~~ N/A
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
Updated regex validation of resource ids to prevent leading slashes
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
I have suspicions that this may be a breaking change. There may be resources that are already using the existing syntax

**Comment by ScottSuarez** [comment]
I would agree unless we can reproduce the error. Then I would switch to fixing the instance of the reproduction to allow to work.

**Comment by SarahFrench** [comment]
I've scaled back this PR to be about the issue from the original customer issue I saw, which was hardcoding the `private_network` argument in a `google_sql_database_instance` resource with a value starting `/projects/...`. 

I reproduced the customer issue by using the [private IP example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#private-ip-instance) to create everything except the database instance in apply #.1, and then creating the instance with a hardcoded network in apply #.2

This is the error returned from the API which doesn't make it clear to the user how their input is invalid:



Because users might use custom endpoints, the regex needs to either be permissive (i.e. using `.+`) or somehow access the provider config.

**Comment by ScottSuarez** [comment]
sounds good, I notice this is in draft. Let me know when it's ready for review

**Review by ScottSuarez — APPROVED** [review]
lgtm

**Comment by SarahFrench** [comment]
Thanks!

**Pull request merged**
