### PR TITLE
Fixed SecurityPolicyRule and RegionSecurityPolicyRule resources being unable to manage the policy default rule

### PR DESCRIPTION
**Pull request by matheusaleixo-cit**
Adds custom code to allow the `google_compute_region_security_policy_rule` and `google_compute_security_policy_rule` resources to override the default rule of their respective security policy without the need of a multi-apply import process.

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/15687

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed unable to create default rule when using `google_compute_region_security_policy_rule` resource (beta)
```
```release-note:bug
compute: fixed unable to create default rule when using `google_compute_security_policy_rule` resource
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Sorry, been behind on reviews. Rolled a new reviewer.

**Comment by zli82016** [comment]
@melinath , it looks like both PR, https://github.com/GoogleCloudPlatform/magic-modules/pull/12054 and  https://github.com/GoogleCloudPlatform/magic-modules/pull/11894 are trying to fix the same Github issue with different ways. They both look reasonable to me. What is your thought? Thanks.

**Comment by melinath** [comment]
FWIW to me this feels like a reasonable situation for acquire-on-create behavior. That said, I don't think these PRs necessarily conflict & having both seems like it's probably good for users.

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
