### PR TITLE
switch sql_database_instance from update to patch so we don't overwrite undocumented fields

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/8675

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
sql: switched api call to patch from update for `sql_database_instance` as to not overwrite existing fields managed outside terraform
```

### CODE REVIEW

**Comment by c2thorn** [comment]
We don't actually use the instance resource as defined in the api.yaml, as it is excluded in Terraform: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/sql/terraform.yaml#L76

You'll have to update the resource written in `third_party`

**Comment by ScottSuarez** [comment]
ooops 😛

**Comment by ScottSuarez** [comment]
@c2thorn should be g2g

**Comment by c2thorn** [comment]
Do SQL updates pass locally? I tried a run in TC for all tests but getting seemingly unrelated failures. Except for this test that updates: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/177554?buildTab=tests&expandedTest=-1725348352079025635

**Comment by ScottSuarez** [comment]
When I ran it locally previously it passed. I can give another run and post the results here.

**Comment by ScottSuarez** [comment]
Also running them on team city here in recording mode
https://ci-oss.hashicorp.engineering/viewLog.html?buildId=177711&

**Review by c2thorn — APPROVED** [review]
LGTM, maybe another gcbrun to get the cancelled tests recorded?

**Comment by ScottSuarez** [comment]
/gcbrun

Sure ! :)

**Pull request closed without merging**
