### PR TITLE
Filestore Operation autogeneration

### PR DESCRIPTION
**Pull request by rambleraptor**
Filestore Operation autogeneration

-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by rambleraptor** [comment]
The TPG downstream just deletes a stray Filestore operation which seems like correct behavior.

**Comment by rambleraptor** [comment]
Going to retest this because now I'm paranoid.

**Comment by rileykarson** [comment]
Ehh, these ones pass in CI. Want me to hold merging for you, or go ahead?

**Comment by rambleraptor** [comment]
go ahead and merge in then!

**Pull request merged**
