### PR TITLE
Upgrade DCL to v1.51.0

### PR DESCRIPTION
**Pull request by NickElliot**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
containeraws: added support for `auto_repair` in `container_aws_node_pool`
```

```release-note:enhancement
containerazure: added support for `auto_repair` in `container_azure_node_pool`
```

```release-note:enhancement
networkconnectivity: added support for `linked_vpc_network` in `network_connectivity_spoke`
```

```release-note:bug
eventarc: field `event_data_content_type` in `eventarc_trigger` now marked as computed
```

### CODE REVIEW

**Review by hao-nan-li — APPROVED** [review]

**Comment by rileykarson** [comment]
@NickElliot we made config.instance_type updatable too, I think, looking at the generated diffs! Someone pinged me about their change so I was looking at this. Can you write an upgrade entry for that, and work with the next release shepherd (@trodge I think) to include it in the release?

**Comment by NickElliot** [comment]
Do I need to just edit it into the original post here, or send it over to @trodge for manually updating the release notes?

```release-note:enhancement
containeraws: added update support for `config.instance_type` in  `container_aws_node_pool`
```

**Comment by melinath** [comment]
you'll need to send it over to @trodge - release notes don't pick up changes after merge. You may also want to modify the eventarc line to focus more on customer impact of the switch to O+C. Something like:

```
eventarc: resolved permadiff on `google_eventarc_trigger.event_data_content_type` by defaulting to the value returned by the API if not set in the configuration.
```

**Comment by rileykarson** [comment]
You could theoretically edit the PR's changelog file in both repos to update the changelog generator (https://github.com/hashicorp/terraform-provider-google/blob/main/.changelog/8876.txt / https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.changelog/8876.txt). But since we haven't done this before you'll still want to manually verify the changes worked (I'm also not sure if edits made after the cut date but before the cut is made would work- not an issue in this case, but possibly in others)

**Pull request merged**
