### PR TITLE
Disable delete for bare metal admin cluster resource

### PR DESCRIPTION
**Pull request by naitianliu-google**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/15766

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
baremetal: make delete a noop for the resource `google_bare_metal_admin_cluster` to better align with actual behavior
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Is there context or an existing bug for this change ?

**Review by ScottSuarez — APPROVED** [review]

**Review by ScottSuarez — COMMENTED** [review]
Actually, upon examination. Could you further explain the changes here. What does unenroll do? What is the existing behavior. This could be quite problematic for out testing environment if we have a lot of resources that don't get cleaned up

**Comment by ScottSuarez** [comment]
After talking with my team this is a breaking change per 
https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/#resource-level-breaking-changes

And will need to be make in MAJOR release

**Comment by naitianliu-google** [comment]
> Actually, upon examination. Could you further explain the changes here. What does unenroll do? What is the existing behavior. This could be quite problematic for out testing environment if we have a lot of resources that don't get cleaned up

Unenroll only removes the resource from cloud storage and leave it locally while it is expected to remove resource from both storage and local environments. This is why we decide to skip delete in TF and guide users to manually delete the resource. 

Agree it may causes test issues without delete method. Could you please help guide if it is feasible to resolve this, e.g. custom tests?

**Comment by naitianliu-google** [comment]
> After talking with my team this is a breaking change per https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/#resource-level-breaking-changes
> 
> And will need to be make in MAJOR release

Thanks for the guidance. Could you please help estimate the date of next MAJOR release?

**Comment by ScottSuarez** [comment]
We are in the process of 5.0.0 release. You can make this change against the 5.0.0 branch provided you write an upgrade guide.

**Comment by naitianliu-google** [comment]
> We are in the process of 5.0.0 release. You can make this change against the 5.0.0 branch provided you write an upgrade guide.

Thanks for the guidance!

**Comment by c2thorn** [comment]
@naitianliu-google Can you also add a Github Issue describing the problem that this solves? For 5.0.0 tracking purposes

**Comment by naitianliu-google** [comment]
> @naitianliu-google Can you also add a Github Issue describing the problem that this solves? For 5.0.0 tracking purposes

Thanks for the guidance! Added this issue for tracking: https://github.com/hashicorp/terraform-provider-google/issues/15766

**Comment by ScottSuarez** [comment]
Wanted to check on the upgrade guide. Apologies if you're already aware/working on this. I see no issue with the PR though since we are merging into the FEATURE branch.

**Comment by naitianliu-google** [comment]
> Wanted to check on the upgrade guide. Apologies if you're already aware/working on this. I see no issue with the PR though since we are merging into the FEATURE branch.

Thanks for the guide. Updated the upgrade guide in this PR. Please help take a look. Thanks!

**Comment by c2thorn** [comment]
hi @naitianliu-google can you remove the upgrade guide in this PR and move it to a PR going into `main`?

**Comment by naitianliu-google** [comment]
> hi @naitianliu-google can you remove the upgrade guide in this PR and move it to a PR going into `main`?

Thanks for the guidance. Split the change to the PR https://github.com/GoogleCloudPlatform/magic-modules/pull/9090

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
