### PR TITLE
Support specifying project explicitly on the sql ssl resource

### PR DESCRIPTION
**Pull request by chrisst**
fixes https://github.com/terraform-providers/terraform-provider-google/issues/2988

-----------------------------------------------------------------
# [all]
Support specifying project explicitly on the sql ssl resource

### CODE REVIEW

**Comment by chrisst** [comment]
@emilymye good point, looks like we don't set it during getProject though I thought we did.

**Comment by emilymye** [comment]
@chrisst I'm a little concerned still about not setting project in state - this would probably cause a diff if someone explicitly sets `project` after using the same provider project to create it. I think usually we end up setting it to the getProject value? I think my previous comment was less "remove Computed", more "add d.Set("project", project)", my bad.

**Comment by chrisst** [comment]
Makes sense, thanks!

**Comment by rileykarson** [comment]
Were there existing docs for this field, or do we need docs + a changelog entry?

**Comment by chrisst** [comment]
Doc updates https://github.com/GoogleCloudPlatform/magic-modules/pull/1508

**Pull request merged**
