### PR TITLE
Add Dataplex Asset resource

### PR DESCRIPTION
**Pull request by saurabhmaurya06**
part of https://github.com/hashicorp/terraform-provider-google/issues/11648

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-resource
`google_dataplex_asset`
```

### CODE REVIEW

**Comment by saurabhmaurya06** [comment]
It looks like I'll have to manually create a GCS bucket for the Dataplex asset to attach to. I'll mark this review in draft until I complete that step.

**Comment by saurabhmaurya06** [comment]
I've added an ignore_read for Asset.resource_spec.name. 

This is an immutable field, and the Dataplex API accepts input in the format "projects/{projectID}/buckets/{bucketID}", however it returns it as "{bucketID}". 

The API behavior is because of the need to maintain backwards compatibility but return results in line with other GCP APIs. 

Since it's an immutable field, it's safe to skip the verify import-state-step for this field. I've discussed the above with @trodge, and all the tests are passing now.

**Review by slevenick — CHANGES_REQUESTED** [review]
Looks like the ID format of the asset and zone resources are malformed.

Mine looks like this:
`projects/my-project/locations/us-central1/lakes/tf-test-lakeasd/zones/tf-test-zoneasd/assets/tf-test-asset`

**Comment by slevenick** [comment]
Couple notes:

resource_type should not document that it allows TYPE_UNSPECIFIED, as it is not a valid value to send to the API.

The discovery_spec.enabled field's documentation does not match its behavior

`zone` is a bit weird, as zone is a magic field in the provider where we set it as Optional and inherit from the provider's default zone. Is it possible to rename this field?

**Review by slevenick — APPROVED** [review]
Looks good!

One note but not urgent, you can fix as you have time:

This line mentions what happens when discovery_spec is unset, but the field has been marked required so it can never be unset: https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6310-old..auto-pr-6310#diff-5d6d84399bf306af362c41c7ee924744379a41d52bb6d4754206961bd89c681aR100

**Pull request merged**
