### PR TITLE
Promote `user_ip_request_headers` field on `google_compute_security_policy` resource to GA

### PR DESCRIPTION
**Pull request by SarahFrench**
This PR promotes the `user_ip_request_headers` field on `google_compute_security_policy` resource to GA.
The API docs show [userIpRequestHeaders as present in the GA version of the API](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies#SecurityPolicy.FIELDS.inlinedField_89:~:text=advancedOptionsConfig.userIpRequestHeaders%5B%5D).

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: promoted `user_ip_request_headers` field on `google_compute_security_policy` resource to GA
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
Confusing problem with the checks - I'll retry - /gcbrun

**Comment by SarahFrench** [comment]
I've run the `TestAccComputeSecurityPolicy_withAdvancedOptionsConfig` test using the GA provider in TeamCity here: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_MmUpstreamTesting_GOOGLE_PACKAGE_COMPUTE/91177?buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=false

**Comment by SarahFrench** [comment]
@BBBmau requesting you as reviewer for some practice as part of onboarding! 😁

**Review by BBBmau — APPROVED** [review]
PR matches the steps to follow when [promoting a field to GA](https://googlecloudplatform.github.io/magic-modules/develop/promote-to-ga/#promote-fields-and-resources)

LGTM!

**Comment by SarahFrench** [comment]
/gcbrun

Just re-testing this as I forgot to merge!

**Pull request merged**
