### PR TITLE
Update bq connection types from v1 api

### PR DESCRIPTION
**Pull request by maduris**
Update connection types of google_bigquery_connection from v1 api. Fixes https://github.com/hashicorp/terraform-provider-google/issues/11053 and https://github.com/hashicorp/terraform-provider-google/issues/11459

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigqueryconnection: Update connection types to support v1 ga
```

### CODE REVIEW

**Comment by maduris** [comment]
hi @ScottSuarez @rileykarson , regarding those failing tests, should I add exceptions similar as https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_bigquery_connection_test.go.erb?

**Comment by rileykarson** [comment]
Given we're introducing a GA version here we can likely just remove the version tags (the `<%` lines) in that file as a whole! @ScottSuarez can help make the appropriate change.

The failure messages look like a difference in supported regions between beta/GA at first glance, which is concerning- that may block making this change since it would be breaking for existing users:

```
=== RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
=== PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
=== RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
=== PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
=== RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
=== PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
=== RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
=== PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
=== RUN   TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
=== PAUSE TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
=== CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating Connection: googleapi: Error 400: Unable to recognize type of the connection properties.
        
          on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
           2: resource "google_bigquery_connection" "connection" {
        
        
--- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample (3.33s)
=== CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating Connection: googleapi: Error 400: Cloud Spanner database id must be of the form projects/{project=*}/instances/{instance=*}/databases/{database=*}
        
          on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
           2: resource "google_bigquery_connection" "connection" {
        
        
--- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample (3.25s)
=== CONT  TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating FolderFeed: googleapi: Error 400: Fail to use projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi as feed output destination. Error: PERMISSION_DENIED: User not authorized to perform this action. [type.googleapis.com/util.MessageSetPayload='[google.rpc.error_details_ext] { message: "User not authorized to perform this action." details { [type.googleapis.com/google.rpc.DebugInfo] { detail: "PermissionResponse.success = false for resource \'projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi\': " } } }']
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "description": "Fail to use projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi as feed output destination. Error: PERMISSION_DENIED: User not authorized to perform this action. [type.googleapis.com/util.MessageSetPayload='[google.rpc.error_details_ext] { message: \"User not authorized to perform this action.\" details { [type.googleapis.com/google.rpc.DebugInfo] { detail: \"PermissionResponse.success = false for resource \\'projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi\\': \" } } }']",
                "field": "feed.feed_output_config.pubsub_destination.topic"
              }
            ]
          }
        ]
        
          on terraform_plugin_test.tf line 4, in resource "google_cloud_asset_folder_feed" "folder_feed":
           4: resource "google_cloud_asset_folder_feed" "folder_feed" {
        
        
--- FAIL: TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample (14.82s)
=== CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating Connection: googleapi: Error 400: Azure connection is not supported in this region.
        
          on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
           2: resource "google_bigquery_connection" "connection" {
        
        
--- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample (3.28s)
=== CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating Connection: googleapi: Error 400: AWS connection is not supported in this region.
        
          on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
           2: resource "google_bigquery_connection" "connection" {
        
        
--- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample (3.28s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta	28.006s
FAIL
```

**Comment by ScottSuarez** [comment]
The new tests seem to be failing as `US` isn't a valid location for a bigquery connection.
https://cloud.google.com/bigquery/docs/locations#supported_regions

**Comment by maduris** [comment]
> Given we're introducing a GA version here we can likely just remove the version tags (the `<%` lines) in that file as a whole! @ScottSuarez can help make the appropriate change.
> 
> The failure messages look like a difference in supported regions between beta/GA at first glance, which is concerning- that may block making this change since it would be breaking for existing users:
> 
> ```
> === RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
> === PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
> === RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
> === PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
> === RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
> === PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
> === RUN   TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
> === PAUSE TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
> === RUN   TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
> === PAUSE TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
> === CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample
>     provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: Error creating Connection: googleapi: Error 400: Unable to recognize type of the connection properties.
>         
>           on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
>            2: resource "google_bigquery_connection" "connection" {
>         
>         
> --- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample (3.33s)
> === CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample
>     provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: Error creating Connection: googleapi: Error 400: Cloud Spanner database id must be of the form projects/{project=*}/instances/{instance=*}/databases/{database=*}
>         
>           on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
>            2: resource "google_bigquery_connection" "connection" {
>         
>         
> --- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionCloudspannerExample (3.25s)
> === CONT  TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample
>     provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: Error creating FolderFeed: googleapi: Error 400: Fail to use projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi as feed output destination. Error: PERMISSION_DENIED: User not authorized to perform this action. [type.googleapis.com/util.MessageSetPayload='[google.rpc.error_details_ext] { message: "User not authorized to perform this action." details { [type.googleapis.com/google.rpc.DebugInfo] { detail: "PermissionResponse.success = false for resource \'projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi\': " } } }']
>         Details:
>         [
>           {
>             "@type": "type.googleapis.com/google.rpc.BadRequest",
>             "fieldViolations": [
>               {
>                 "description": "Fail to use projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi as feed output destination. Error: PERMISSION_DENIED: User not authorized to perform this action. [type.googleapis.com/util.MessageSetPayload='[google.rpc.error_details_ext] { message: \"User not authorized to perform this action.\" details { [type.googleapis.com/google.rpc.DebugInfo] { detail: \"PermissionResponse.success = false for resource \\'projects/ci-test-project-188019/topics/tf-test-network-updatespbt0a7dszi\\': \" } } }']",
>                 "field": "feed.feed_output_config.pubsub_destination.topic"
>               }
>             ]
>           }
>         ]
>         
>           on terraform_plugin_test.tf line 4, in resource "google_cloud_asset_folder_feed" "folder_feed":
>            4: resource "google_cloud_asset_folder_feed" "folder_feed" {
>         
>         
> --- FAIL: TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample (14.82s)
> === CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample
>     provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: Error creating Connection: googleapi: Error 400: Azure connection is not supported in this region.
>         
>           on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
>            2: resource "google_bigquery_connection" "connection" {
>         
>         
> --- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionAzureExample (3.28s)
> === CONT  TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample
>     provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: Error creating Connection: googleapi: Error 400: AWS connection is not supported in this region.
>         
>           on terraform_plugin_test.tf line 2, in resource "google_bigquery_connection" "connection":
>            2: resource "google_bigquery_connection" "connection" {
>         
>         
> --- FAIL: TestAccBigqueryConnectionConnection_bigqueryConnectionAwsExample (3.28s)
> FAIL
> FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta	28.006s
> FAIL
> ```

I removed the default region, and update the regions for both aws and azure too, how do we run this vcr tests in local?

**Comment by maduris** [comment]
hi @ScottSuarez, the tests for cloudspanner, aws, azure are passing, but TestAccBigqueryConnectionConnection_bigqueryConnectionCloudResourceExample is not passing, however it passes when I tested manually building the provider, And I noticed this change has already been merged to main branch from another PR, could we merge this pr now?

**Comment by ScottSuarez** [comment]
> And I noticed this change has already been merged to main branch from another PR, could we merge this pr now?

Do you have a reference for this? Could you rebase this PR. 
These tests are still failing for seemingly valid reasons. I suspect this is because we aren't sending cloudresource field if it's empty anymore.

**Comment by maduris** [comment]
hi @ScottSuarez, found the issue, fixed the test for cloudResource, could you please review and let me know?

**Review by ScottSuarez — APPROVED** [review]
lgtm

**Pull request merged**
