### PR TITLE
Add nil check to disk_autoresize_limit

### PR DESCRIPTION
**Pull request by c2thorn**
Addressing panic seen in https://github.com/GoogleCloudPlatform/terraform-validator/pull/218 tests

I'm not sure why the value isn't being set to the zero default, but I figured a nil check wouldn't hurt either way.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — APPROVED** [review]
Seems reasonable. I feel like we've had issues like this that where it turned out the provider dependency was out of date, which was causing the issue. Not sure if that's a factor here though.

**Comment by c2thorn** [comment]
> Seems reasonable. I feel like we've had issues like this that where it turned out the provider dependency was out of date, which was causing the issue. Not sure if that's a factor here though.

Ahh I bet that would be the case. I was thinking that this was a google-conversion issue, but you mean updating the provider dependency in Validator right? Do we have to do anything weird with the whole `/v3` thing?

**Comment by melinath** [comment]
> Ahh I bet that would be the case. I was thinking that this was a google-conversion issue, but you mean updating the provider dependency in Validator right? Do we have to do anything weird with the whole `/v3` thing?

yyyup. Basically you have to make a special "v3" release branch like this: https://github.com/hashicorp/terraform-provider-google/tree/release-3.60.0-v3 - it just has an extra commit that makes it v3.

**Comment by c2thorn** [comment]
> > Ahh I bet that would be the case. I was thinking that this was a google-conversion issue, but you mean updating the provider dependency in Validator right? Do we have to do anything weird with the whole `/v3` thing?
> 
> yyyup. Basically you have to make a special "v3" release branch like this: [https://github.com/hashicorp/terraform-provider-google/tree/release-3.60.0-v3](https://github.com/hashicorp/terraform-provider-google/tree/release-3.60.0-v3?rgh-link-date=2021-06-03T15%3A18%3A28Z) - it just has an extra commit that makes it v3.

That totally fixed it. Closing this as it is unnecessary!

**Pull request closed without merging**
