### PR TITLE
Upgrade Go 1.19

### PR DESCRIPTION
**Pull request by zli82016**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/14102

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by rileykarson** [comment]
Since you're editing .ci generate-diffs won't run! You'll need to allowlist the PR # if you want it to. I don't know how myself- Thomas knew how to, last I checked, so you can ping them!

**Comment by zli82016** [comment]
> Since you're editing .ci generate-diffs won't run! You'll need to allowlist the PR # if you want it to. I don't know how myself- Thomas knew how to, last I checked, so you can ping them!

Thanks. I will ping Thomas.

**Review by rileykarson — COMMENTED** [review]
LGTM.

One thing to keep in mind is the mechanics of how this merge will go- the sync job immediately after you merge the PR will still use the old images, and they'll be updated out-of-band by the rebuild job. So we'll see a failure downstream initially, and it'll be corrected by the next merged commit after a half hour or so has passed

You'd be able to PR manually with the reformatted files or build and push the images in advance to fix things sooner.

**Review by rileykarson — APPROVED** [review]

**Comment by rileykarson** [comment]
We may need to update goimports as well (and may want to do that out of band first). See https://github.com/GoogleCloudPlatform/magic-modules/blob/a7e2915c87e7018bd0020c4bf0bc350bc933f872/.ci/containers/downstream-builder/Dockerfile#LL5C61-L5C61, we pin a specific version to avoid image rebuilds unintentionally reformatting files en-masse.

**Pull request merged**
