### PR TITLE
Add version field to API (WIP)

### PR DESCRIPTION
**Pull request by sreevatsanraman**
**Release Note Template for Downstream PRs (will be copied)**

`google_data_fusion_instance`: Added `version` field

### CODE REVIEW

**Comment by c2thorn** [comment]
Hi @sreevatsanraman, I believe https://github.com/GoogleCloudPlatform/magic-modules/pull/3734#event-3540564856

Was doing what you wanted, it just got merged!

**Comment by sreevatsanraman** [comment]
Thanks @c2thorn, any time lines on when this will be made available? I will close this PR

**Comment by c2thorn** [comment]
@sreevatsanraman  Since it was merged today, it should be available for v3.31 which is scheduled for release on Monday.

**Comment by sreevatsanraman** [comment]
thanks for you quick response.

**Pull request closed without merging**
