### PR TITLE
Update labels.go to also check for user_labels

### PR DESCRIPTION
**Pull request by mikaelm12**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by NickElliot** [comment]
to @zli82016 as it pertains to the labels update

**Comment by zli82016** [comment]
@mikaelm12 , I wonder what is the reason to check for `user_labels`. 

 The function `SetLabelsDiff` is only added as the `CustomizeDiff` to the resource with `labels` field and not added to the resource with `user_labels` field.

**Comment by zli82016** [comment]
@mikaelm12 , do you have any questions before I closing this PR? Which resources do you expect to apply the  function `SetLabelsDiff`?

**Comment by rileykarson** [comment]
Hey! I'm closing this PR as a part of a cleanup of older inactive PRs, using a threshold of PRs in "Draft" last updated over a month ago. This doesn't represent rejection of the change, and feel free to comment for me to reopen it if you plan to pick it back up, or feel free to start a new PR with the same changes in the future.

**Pull request closed without merging**
