### PR TITLE
Error abort predicates

### PR DESCRIPTION
**Pull request by trodge**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by zli82016 — APPROVED** [review]
LGTM

**Review by rileykarson — CHANGES_REQUESTED** [review]
Blocking this temporarily, sorry for the disruption! https://github.com/hashicorp/terraform-provider-google/issues/14691 needs some retry changes and I may try to get it cherrypicked into the next release. Will dismiss once a decision is made on that.

**Comment by rileykarson** [comment]
Unblocked- sorry again for the disruption!

**Review by zli82016 — APPROVED** [review]
LGTM

**Comment by sachitjaggi156** [comment]
`
sachitjaggi@sachit6:~/Desktop/trf9/magic-modules$ cd $GOPATH/src/github.com/hashicorp/terraform-provider-google
sachitjaggi@sachit6:~/go/src/github.com/hashicorp/terraform-provider-google$ make test
make lint
sh -c "'/usr/local/google/home/sachitjaggi/go/src/github.com/hashicorp/terraform-provider-google/scripts/gofmtcheck.sh'"
==> Checking that code complies with gofmt requirements...
go vet
# github.com/hashicorp/terraform-provider-google/google
google/iam_batching.go:18:69: undefined: iamPolicyModifyFunc
google/iam_batching.go:23:19: undefined: iamPolicyModifyFunc
google/iam_batching.go:34:32: undefined: iamPolicyModifyFunc
google/iam_batching.go:39:32: undefined: iamPolicyModifyFunc
google/iam_batching.go:49:28: undefined: iamPolicyModifyFunc
google/iam_batching.go:53:15: undefined: iamPolicyReadModifyWrite
google/provider.go:765:97: undefined: ContainerAnalysisNoteIamSchema
google/provider.go:765:129: undefined: ContainerAnalysisNoteIamUpdaterProducer
google/provider.go:926:68: undefined: ResourceCertificateManagerCertificateIssuanceConfig
google/provider.go:1053:102: undefined: ContainerAnalysisNoteIamSchema
google/provider.go:1053:102: too many errors
make: *** [GNUmakefile:26: vet] Error 1
sh -c "'/usr/local/google/home/sachitjaggi/go/src/github.com/hashicorp/terraform-provider-google/scripts/gofmtcheck.sh'"
==> Checking that code complies with gofmt requirements...
go vet
# github.com/hashicorp/terraform-provider-google/google
google/iam_batching.go:18:69: undefined: iamPolicyModifyFunc
google/iam_batching.go:23:19: undefined: iamPolicyModifyFunc
google/iam_batching.go:34:32: undefined: iamPolicyModifyFunc
google/iam_batching.go:39:32: undefined: iamPolicyModifyFunc
google/iam_batching.go:49:28: undefined: iamPolicyModifyFunc
google/iam_batching.go:53:15: undefined: iamPolicyReadModifyWrite
google/provider.go:765:97: undefined: ContainerAnalysisNoteIamSchema
google/provider.go:765:129: undefined: ContainerAnalysisNoteIamUpdaterProducer
google/provider.go:926:68: undefined: ResourceCertificateManagerCertificateIssuanceConfig
google/provider.go:1053:102: undefined: ContainerAnalysisNoteIamSchema
google/provider.go:1053:102: too many errors
make: *** [GNUmakefile:26: vet] Error 1
sachitjaggi@sachit6:~/go/src/github.com/hashicorp/terraform-provider-google$ 
`

Main branch is failing the lint test not able to run tests.

**Pull request merged**
