### PR TITLE
bump go api client version to 0.156.0

### PR DESCRIPTION
**Pull request by siwiutki**
v0.155.0 version adds EnableRelay field to AdvancedDatapathObservabilityConfig struct in v1beta1: https://pkg.go.dev/google.golang.org/api@v0.155.0/container/v1beta1#AdvancedDatapathObservabilityConfig

This is required to unblock https://github.com/GoogleCloudPlatform/magic-modules/pull/9633. Although for this PR version v0.155.0 or higher is required, updating to v0.156.0 since it's the newest version available at the moment.

Fixes b/319236259

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
provider: updated google.golang.org/api from v0.154.0 to v0.156.0
```

### CODE REVIEW

**Comment by siwiutki** [comment]
Pinging @SarahFrench after 2 days - would be lovely if you had a look at this.

**Comment by siwiutki** [comment]
Keep in mind that updating packages will yield different results depending on the point of time when you update them, even if you do the process on the exact same version of magic-modules repo as I do. Newer package versions might have been released between the time I created this PR and the time you tested this change. As I'm coming back to answer your comment, v0.156.0 version of `google.golang.org/api` is already available. IMO if tests are passing, there should be no harm with merging this PR.

About the steps:

1. Generate provider code:

    ```shell
    $ make provider VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google"
    $ make provider VERSION=beta OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta"
    ```
1. Check diffs between generated go.mod, go.sum files and templated ones, note the diffs for later. Note that go.sum is the same for beta and ga and go.mod has some slight differences in the first lines only, otherwise it has the same package versions:

    ```shell
    # no diff
    $ diff $GOPATH/src/github.com/hashicorp/terraform-provider-google-beta/go.sum $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.sum
    $ diff $GOPATH/src/github.com/hashicorp/terraform-provider-google/go.sum $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.sum
    
    # diff:
    # 1c1,2
    # < module github.com/hashicorp/terraform-provider-google-beta
    # ---
    # > <% autogen_exception -%>
    # > module github.com/hashicorp/terraform-provider-google
    $ diff $GOPATH/src/github.com/hashicorp/terraform-provider-google-beta/go.mod $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.mod.erb
    
    # diff:
    # 0a1
    # > <% autogen_exception -%>
    diff $GOPATH/src/github.com/hashicorp/terraform-provider-google/go.mod $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.mod.erb
    ```

1. Update `google.golang.org/api` package to the newest version:

    ```
    $ go get -u google.golang.org/api/composer/v1
    $ go mod tidy
    ```

1. Copy ga versions of go.mod and go.sum files back to magic-modules:

    ```
    $ cat $GOPATH/src/github.com/hashicorp/terraform-provider-google/go.mod > $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.mod.erb
    $ cat $GOPATH/src/github.com/hashicorp/terraform-provider-google/go.sum > $GOPATH/src/github.com/GoogleCloudPlatform/magic-modules/mmv1/third_party/terraform/go.sum
    ```

I did additional sanity checks by running `make provider (...)` again and updating `google.golang.org/api` again. Expectation is that updating will be a noop operation since magic-modules should already have all package version updates included.

**Comment by siwiutki** [comment]
Around the time of writing this comment (for reference, if you want to compare diffs later), I updated this PR to bump api client version to v0.156.0 since it's the newest available at the moment. When updating, I followed the process described above.

**Review by SarahFrench — APPROVED** [review]
Thank you for the notes about the process you followed! Like you said, given the tests are passing I'm happy to merge this

**Pull request merged**
