### PR TITLE
feat: add vpc_connector to cloud function on update

### PR DESCRIPTION
**Pull request by Priyam-tricon**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
     fix: update vpc_connector on cloud function update
```

### CODE REVIEW

**Comment by Priyam-tricon** [comment]
@googlebot I signed it!

**Comment by rileykarson** [comment]
Hey @Priyam-tricon! Sorry for the delay in getting to this. Did you end up finding that this didn't work as expected, or did you close it due to lack of response?

**Comment by rileykarson** [comment]
Oh nevermind, just saw https://github.com/GoogleCloudPlatform/magic-modules/pull/3201 superseding this.

**Comment by Priyam-tricon** [comment]
@rileykarson  Sorry for the confusion.
Too many chrome tabs opened, and I accidentally closed the wrong PR.😅

**Comment by rileykarson** [comment]
All good!

**Pull request closed without merging**
