### PR TITLE
Unrevert low touch

### PR DESCRIPTION
**Pull request by trodge**
Fixed the issue with GKEHub base paths by removing the `skip` override.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
GKE hub feature tests skipped in VCR. Triggered an independent run in TC and tests passed: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/301512?buildTab=tests&status=passed

**Comment by ScottSuarez** [comment]
Thanks Shuya for running the GKE tests !

**Review by ScottSuarez — APPROVED** [review]

**Review by slevenick — DISMISSED** [review]
Looks like this changes the key from GOOGLE_GKEHUB_FEATURE_CUSTOM_ENDPOINT -> GOOGLE_GKE_HUB_FEATURE_CUSTOM_ENDPOINT which I'd like to avoid. Can we keep this key backwards compatible as I believe that key is how a user sets this value

**Comment by ScottSuarez** [comment]
@rileykarson could you bypass merge this. 

It won't let me merge due to Sam's requested change comment (which has been addressed)

**Comment by ScottSuarez** [comment]
thanks !

**Pull request merged**
