### PR TITLE
Added Cloud SQL SSL/TLS example

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Intending to add these here:

https://cloud.google.com/sql/docs/sqlserver/configure-ssl-instance
https://cloud.google.com/sql/docs/postgres/configure-ssl-instance
https://cloud.google.com/sql/docs/mysql/configure-ssl-instance

```release-note:none
```

### CODE REVIEW

**Comment by slevenick** [comment]
Can we mark this as CGC-only? Adding additional tests for SQL especially when we have multiple instances is significantly adding to our test run time

**Comment by betsy-lichtenberg** [comment]
> Can we mark this as CGC-only? Adding additional tests for SQL especially when we have multiple instances is significantly adding to our test run time

I thought that everything in products/cgc/terraform.yaml was already cgc-only.

Does this line apply to everything in the file?

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/cgc/terraform.yaml#L17

**Comment by betsy-lichtenberg** [comment]
> Can we mark this as CGC-only? Adding additional tests for SQL especially when we have multiple instances is significantly adding to our test run time

I thought that everything in products/cgc/terraform.yaml was already cgc-only.

Does this line apply to everything in the file?

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/cgc/terraform.yaml#L17

**Comment by betsy-lichtenberg** [comment]
I added skip test true to this an several others.

**Review by slevenick — APPROVED** [review]
Great, thanks!

**Pull request merged**
