### PR TITLE
Add "consumerAcceptList" and "serviceAttachment" to ApigeeInstance.

### PR DESCRIPTION
**Pull request by xuchenma**
This PR add "consumerAcceptList" and "serviceAttachment" to ApigeeInstance. It solves https://github.com/hashicorp/terraform-provider-google/issues/11331.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Add "consumerAcceptList" and "serviceAttachment" to ApigeeInstance.
```

### CODE REVIEW

**Comment by xuchenma** [comment]
I got the following error when running locally, could you advise?
```
$ make testacc TEST=./google TESTARGS='-run=TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample
=== PAUSE TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample
=== CONT  TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample
    provider_test.go:301: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # google_apigee_instance.apigee_instance must be replaced
        -/+ resource "google_apigee_instance" "apigee_instance" {
              ~ consumer_accept_list = [
                  - "896209796641",
                ] -> (known after apply)
              ~ host                 = "172.18.0.2" -> (known after apply)
              ~ id                   = "organizations/tf-testl7lelq43yp/instances/tf-testl7lelq43yp" -> (known after apply)
              ~ location             = "us-central1" -> "us-central1-b"
                name                 = "tf-testl7lelq43yp"
                org_id               = "organizations/tf-testl7lelq43yp"
              ~ peering_cidr_range   = "SLASH_22" -> (known after apply)
              ~ port                 = "443" -> (known after apply)
              ~ service_attachment   = "projects/n4702e404a31ae85dp-tp/regions/us-central1/serviceAttachments/apigee-us-central1-kq7t" -> (known after apply)
            }
        
        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccApigeeInstance_apigeeInstanceServiceAttachmentBasicTestExample (2573.45s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google/google	2573.733s
FAIL
make: *** [GNUmakefile:14: testacc] Error 1
```

**Comment by melinath** [comment]
This failure is due to the permadiff described here: https://github.com/hashicorp/terraform-provider-google/issues/9988 The root cause seems to be https://github.com/hashicorp/terraform-provider-google/issues/10849. It would be great to resolve that permadiff prior to merging this PR - potentially in a separate PR.

**Comment by xuchenma** [comment]
Thanks, I fixed the newly added test and it now passes! I'll make another PR to fix other tests too.

**Comment by xuchenma** [comment]
Made https://github.com/GoogleCloudPlatform/magic-modules/pull/5872 to fix the test issue for other test cases.

**Comment by melinath** [comment]
It looks like TestAccContainerCluster_withAuthenticatorGroupsConfig failed in CI but it's unrelated. I started up https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/274884 as a CI run specifically for the new test since it skips VCR.

**Review by melinath — CHANGES_REQUESTED** [review]
Could you add consumerAcceptList usage to the test?

**Comment by xuchenma** [comment]
Yes. The product fix to support consumer_accept_list has just rolled out today.
I added a usage to the test:
consumer_accept_list = [123456, google_project.project.number]

**Comment by melinath** [comment]
Specific test run for the new test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/283988

**Review by melinath — APPROVED** [review]
lgtm and tests are passing - thanks for adding consumer_accept_list to the tests!

**Pull request merged**
