### PR TITLE
Fix compute_service_attachment  consumer_accept diff

### PR DESCRIPTION
**Pull request by horjulf**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/12409

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Fixed permadiff for `consumer_accept_lists` in `google_compute_service_attachment`
```

### CODE REVIEW

**Comment by horjulf** [comment]
@slevenick its kinda broken as is, it diffs on every run, only solution currently is to ignore the field which isn't great. 😞 

Is a new major release in the plans for the near future ?

**Comment by slevenick** [comment]
Next major release is 5.0.0 but it hasn't been scheduled as far as I know.

A potential workaround could be something like `resourceBigtableInstanceClusterReorderTypeList` in the bigtable_instance resource, which handles the list -> set conversion within a CustomizeDiff rather than actually changing the schema types. We'll probably want to evaluate this before implementation, as implementation could be tricky.

@ScottSuarez you were tagged on the underlying bug to do additional investigation, did that happen?

**Comment by ScottSuarez** [comment]
It's as you say. List to Set is going to be a breaking change. If we could do a customizediff that would resolve the issue.

We could also ignore read of the resource. Which would cause other problems, but allow the stability on the configuration state.

**Comment by ScottSuarez** [comment]
Adding comment from other thread here.
There are a couple options to resolve this.

* List -> Set: This is a breaking change, would need to wait for a major release
* Ignore read of the resource. This would make it so terraform state is the only reality terraform is aware of. Updating out of band won't make any difference. Not ideal but this scenario is already broken as is.
* CustomizeDiff to ignore a difference and treat the list as a Set. Similar to `resourceBigtableInstanceClusterReorderTypeList`
* Custom flatten for this array where the setting of the field in state does not set anything if it already equivalent by writing a custom compare method.

**Comment by c2thorn** [comment]
moved this to https://github.com/GoogleCloudPlatform/magic-modules/pull/9058

**Pull request closed without merging**
