### PR TITLE
Fix hashicorp/terraform-provider-google#17388 (only run tests in beta)

### PR DESCRIPTION
**Pull request by rainshen49**
Roll-forward https://github.com/GoogleCloudPlatform/magic-modules/pull/10111 with handwritten update tests also limited to beta.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
test only
```

### CODE REVIEW

**Comment by rainshen49** [comment]
Please assign to @ScottSuarez per https://github.com/GoogleCloudPlatform/magic-modules/pull/10111

**Comment by ScottSuarez** [comment]
@rainshen49 is there more context for this change. Why are we moving these tests to beta only. I presumed they were in GA by mistake but am interested in more context.

**Comment by rainshen49** [comment]
Right, I should've explained. The API for `google_firebase_app_check_*` has a GA version and a beta version https://firebase.google.com/docs/reference/appcheck/rest, but `google_firebase_*_app` only has a beta API https://firebase.google.com/docs/reference/firebase-management/rest.

1. If the user wants to use the complete flow to create an app and use App Check, they have to use the google-beta provider at least for the google_firebase_*_app.
2. If the user creates their app elsewhere (e.g. console, CLI), they can absolutely use App Check with the GA provider
3. In the examples, we want to show the complete picture, so it can only be run in the beta provider.

**Comment by rainshen49** [comment]
Friendly ping @ScottSuarez

**Comment by ScottSuarez** [comment]
> Friendly ping @ScottSuarez

Sorry for sleeping on this PR. I've been so busy. Let me do a pass.

**Comment by ScottSuarez** [comment]
Could you message me on google chat. Lets have a short call on this topic. I think we need to talk this out a bit.

**Comment by rainshen49** [comment]
The failure `TestAccFirebaseAppCheckServiceConfig_firebaseAppCheckServiceConfigUpdate` is unrelated to this PR. It looks like https://github.com/GoogleCloudPlatform/magic-modules/pull/10206 is flakey. I'll investigate separately.

**Comment by ScottSuarez** [comment]
Could we investigate or disable this testcase before checkin. Unfortunately if we check in a PR with a failing test that recording will be brought into our CI database.

**Comment by rainshen49** [comment]
Ack. I will wait for https://github.com/GoogleCloudPlatform/magic-modules/pull/10281 then.

**Comment by rainshen49** [comment]
Looks like it's fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/10258

**Pull request merged**
