### PR TITLE
switch disk timeout test to debian 10

### PR DESCRIPTION
**Pull request by megan07**
switching test to use debian 10 as debian 11 seems to beat the timeout
https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/322322?buildTab=tests&status=failed&expandedTest=6330899725422803853

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — COMMENTED** [review]
Since debian-10 will probably reach EOL at some point, could this be handled in some other way? Any chance the timeout could be reduced lower than 1s?

**Comment by megan07** [comment]
switched to `.5s` timeout! thanks for asking, i just assumed 1 was the lowest we could go :)

**Comment by melinath** [comment]
cool, I wasn't sure if it would work either; the online docs aren't clear on it 😓

**Review by melinath — APPROVED** [review]
LGTM

**Comment by melinath** [comment]
it looks like this skips vcr; might require a manual run in TeamCity to test?

**Comment by megan07** [comment]
@melinath sorry, i think i skimmed over your message when i merged (i had tested it locally), but it seems to have passed in the tests over the weekend, so i think we're good to go. thanks!

**Comment by melinath** [comment]
yay!

**Pull request merged**
