### PR TITLE
Add external dataset reference to bigquery dataset

### PR DESCRIPTION
**Pull request by obada-ab**
Add external dataset reference to bigquery dataset. This feature is currently in public preview, the field is added to `google_beta`.

API references: https://cloud.google.com/bigquery/docs/glue-federated-datasets
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#ExternalDatasetReference

Fixes https://github.com/hashicorp/terraform-provider-google/issues/16529

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery: added `external_dataset_reference` field to `google_bigquery_dataset` resource (beta)
```

b/307590851

### CODE REVIEW

**Comment by obada-ab** [comment]
@trodge this is a feature currently in public preview, running an acceptance test would require having a `google_bigquery_connection` resource with iam permissions to access an AWS glue resource.

For now I marked the example with `skip_test: true`, I wonder if there's any other resources that require similar external connections that have acceptance tests, If not what do you recommend in this situation? would manual testing be enough?

**Review by wj-chen — COMMENTED** [review]
Do we need a `min_version` here too?

**Comment by trodge** [comment]
> @trodge this is a feature currently in public preview, running an acceptance test would require having a `google_bigquery_connection` resource with iam permissions to access an AWS glue resource.
> 
> For now I marked the example with `skip_test: true`, I wonder if there's any other resources that require similar external connections that have acceptance tests, If not what do you recommend in this situation? would manual testing be enough?

We generally do not want to include fields in the provider if they require special permissions to use. However, we do make some exceptions if the IAM permissions can be set up in [our infra terraform file](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/infra/terraform/main.tf).

I think this [bigquery dataset IAM](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam) doc would be helpful in setting it up. If you can post the necessary resource in a comment I can make a PR to add it to our infra and apply it to our test projects.

**Comment by obada-ab** [comment]
> Do we need a `min_version` here too?

Yes, I need to add this to the field, thanks for catching this. Will fix it

**Comment by obada-ab** [comment]
> We generally do not want to include fields in the provider if they require special permissions to use. However, we do make some exceptions if the IAM permissions can be set up in [our infra terraform file](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/infra/terraform/main.tf).
> 
> I think this [bigquery dataset IAM](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_dataset_iam) doc would be helpful in setting it up. If you can post the necessary resource in a comment I can make a PR to add it to our infra and apply it to our test projects.

@trodge Just to clarify, the IAM policy that would be required for testing is an AWS IAM policy to enable BigQuery to access an S3/AWS glue resource. For reference, BQ Omni has instructions on setting up IAM policy/role and BQ connection resource in terraform: https://cloud.google.com/bigquery/docs/omni-aws-create-connection#terraform

**Comment by rileykarson** [comment]
> We generally do not want to include fields in the provider if they require special permissions to use.

Do you have any precedent(s) you're pulling from here? We haven't written this as policy & I don't agree w/ it. From my POV 
 we do want to make testing as easy as possible in the case of external dependencies, but would only consider disqualification if we thought that we'd actively harm customers by releasing something.

**Comment by obada-ab** [comment]
@trodge PTAL, the failing test isn't related to the `google_bigquery_dataset` resource

**Comment by obada-ab** [comment]
@trodge friendly ping

**Review by trodge — APPROVED** [review]

**Pull request merged**
