### PR TITLE
Made resource_bigquery_reservation_test be included in GA

### PR DESCRIPTION
**Pull request by melinath**
This resource was moved to GA in https://github.com/GoogleCloudPlatform/magic-modules/pull/4342

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by c2thorn — APPROVED** [review]
This file could be converted to just a .go file right?

**Comment by melinath** [comment]
yeah, it could be. I go back and forth on doing that because I've converted files to .go and then had to convert the same file back to a .erb shortly after when a new beta feature was added. But OTOH the syntax highlighting is nicer when it's a simple go file... I don't have a strong opinion either way, how about you?

**Comment by melinath** [comment]
since this is a GA-only build, here's a manual test run: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/197604

**Comment by melinath** [comment]
went ahead & converted to a `.go` file and also added a tf-test prefix

**Comment by c2thorn** [comment]
> yeah, it could be. I go back and forth on doing that because I've converted files to .go and then had to convert the same file back to a .erb shortly after when a new beta feature was added.

I see, reasonably annoying.

> But OTOH the syntax highlighting is nicer when it's a simple go file... I don't have a strong opinion either way, how about you?

That's my main argument. Not a big deal at all. Thanks for going ahead and converting it!

**Review by slevenick — APPROVED** [review]

**Comment by melinath** [comment]
It turns out this fully duplicates an existing generated test - I'll open a separate PR to instead delete this test.

**Pull request closed without merging**
