### PR TITLE
Upgrade the dcl version to v1.26.0

### PR DESCRIPTION
**Pull request by alphanota**
Upgrade the dcl version to v1.26.0
The reason for this upgrade is to add new fields to the DeliveryPipeline and Target resources.
A fix for #12714 is also included.

If this PR is for Terraform, I acknowledge that I have:

- [ x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
clouddeploy: Added support for Cloud Run Targets (beta)
```

```release-note:enhancement
clouddeploy: Added support for Deployment Verification standard strategy (beta)
```

```release-note:enhancement
clouddeploy: Added execution_configs.execution_timeout in target resource. (beta)
```

```release-note:enhancement
compute: machine_type field in compute instance resource now accepts short name.
```
```release-note:enhancement
orgpolicy: Changed spec.rules type from Array to Set in policy resource.
https://github.com/hashicorp/terraform-provider-google/issues/12363
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Note that https://github.com/GoogleCloudPlatform/magic-modules/pull/6614 is ongoing to reach `1.22.0`

**Comment by rileykarson** [comment]
@avinash84 fyi

**Comment by alphanota** [comment]
@rileykarson  Hi yes, we would like to push v.1.23 instead of v.1.22 since we want to release these new features in the beta version.

**Review by melinath — CHANGES_REQUESTED** [review]
Please fix the failing tests related to this PR. Also, if this replaces the other DCL PR, please be sure to include the changes from it.

**Comment by alphanota** [comment]
Hi @melinath we made the requested fixes. Would you be able to review again and verify if the new VCR failures are of concern? Thank you!

**Review by melinath — CHANGES_REQUESTED** [review]
@alphanota great. This is looking good. The one thing that seems a bit odd to me is that GkeHubFeatureMembershipMeshSchema sets a default to `MANAGEMENT_UNSPECIFIED`. Changing the default later will be a breaking change, and UNSPECIFIED values generally don't have a useful meaning. Sometimes they even cause API requests to fail. Does this need to be sent, or would it be enough to just leave the field empty?

Also, could you please verify that the release notes look correct?

**Comment by alphanota** [comment]
> @alphanota great. This is looking good. The one thing that seems a bit odd to me is that GkeHubFeatureMembershipMeshSchema sets a default to `MANAGEMENT_UNSPECIFIED`. Changing the default later will be a breaking change, and UNSPECIFIED values generally don't have a useful meaning. Sometimes they even cause API requests to fail. Does this need to be sent, or would it be enough to just leave the field empty?
> 
> Also, could you please verify that the release notes look correct?

I will loop in @avinash84 here who might be better able to answer that question.

**Comment by avinash84** [comment]
> > @alphanota great. This is looking good. The one thing that seems a bit odd to me is that GkeHubFeatureMembershipMeshSchema sets a default to `MANAGEMENT_UNSPECIFIED`. Changing the default later will be a breaking change, and UNSPECIFIED values generally don't have a useful meaning. Sometimes they even cause API requests to fail. Does this need to be sent, or would it be enough to just leave the field empty?
> > Also, could you please verify that the release notes look correct?
> 
> I will loop in @avinash84 here who might be better able to answer that question.

The [fix](https://critique.corp.google.com/cl/482034404) has been merged in [v1.26.0](https://github.com/GoogleCloudPlatform/declarative-resource-client-library/releases/tag/v1.26.0)

**Comment by alphanota** [comment]
@melinath We made requested changes. Can you please take another look? cc @avinash84

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like a few fields have been added that need to be added to tests:

Both:
- clouddeploy_target: execution_timeout
- eventarc_trigger: channel
- container_aws_cluster: tags was changed to not be ForceNew - it would be great to add it to the existing update test if possible (or add an update test if there isn't one yet.)

Beta-only:
- container_aws_cluster: monitoring_config
- container_azure_cluster: monitoring_config
- gkehub_feature_membership: mesh

Please update the release notes to ensure all those fields are represented, as well as:

Beta-only
- clouddeploy_delivery_pipeline: strategy - has tests 👍 
- clouddeploy_target: run - has tests 👍 

And ensure that all release notes are formatted according to the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md)

**Comment by SirGitsalot** [comment]
Hi Angel,

Avinash just left for vacation so I took a gander at the PR. To address Stephen's most recent comment:

- clouddeploy_target: execution_timeout

That can be fixed by adding the field to the `tpgtools/api/clouddeploy/samples/run.target.json` sample that's already part of this PR (also, `tpgtools/api/clouddeploy/samples/samples/run.target.json` and `tpgtools/api/clouddeploy/samples/samples/run_target.yaml` are dupes of other files in this PR - note the `samples/samples`).

- eventarc_trigger: channel

Not sure if this one is addressable; `channel` is a reference to a resource that doesn't (yet?) exist in TPG.

- container_aws_cluster: tags

Can be fixed to match the DCL test by updating [this line](https://github.com/GoogleCloudPlatform/magic-modules/blob/4cb34a727b3d153e427e4f7ee32fb0d19a93f09e/tpgtools/overrides/containeraws/samples/cluster/beta_basic_update.tf.tmpl#L62) to:

```
    owner = "updated-{{test_service_account}}"
```

- container_aws_cluster: monitoring_config
- container_azure_cluster: monitoring_config

To match the DCL tests, you can add:

```
  monitoring_config {
    managed_prometheus_config {
      enabled = false
    }
  }
```

adjacent to `logging_config` in:

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/overrides/containeraws/samples/cluster/beta_basic.tf.tmpl, 
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/overrides/containeraws/samples/cluster/beta_basic_update.tf.tmpl, 
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/overrides/containerazure/samples/cluster/beta_basic.tf.tmpl, and 
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/overrides/containerazure/samples/cluster/beta_basic_update.tf.tmpl

- gkehub_feature_membership: mesh

Doesn't seem to have a [test to add to](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/tpgtools/overrides/gkehub/samples/feature_membership) (or am I misreading this)?

@melinath - what's the correct path for eventarc_trigger and gkehub_feature_membership?

**Comment by melinath** [comment]
@SirGitsalot could you clarify what you mean by `path` in this case?

**Comment by SirGitsalot** [comment]
> @SirGitsalot could you clarify what you mean by `path` in this case?

How does Angel resolve these test issues:

- eventarc_trigger: channel

To configure this field, the channel that's referenced must exist AIUI. TPG doesn't have support for Eventarc Channel resources, so any TPG test that uses this field must have some non-TPG way of creating Channels.

- gkehub_feature_membership: mesh

gkehub_feature_membership doesn't seem to have any tests to add the `mesh` field to (although it's entirely possible I'm looking in the wrong place)

**Comment by daveavi** [comment]
> It looks like a few fields have been added that need to be added to tests:
> 
> Both:
> 
> * clouddeploy_target: execution_timeout
> * eventarc_trigger: channel
> * container_aws_cluster: tags was changed to not be ForceNew - it would be great to add it to the existing update test if possible (or add an update test if there isn't one yet.)
> 
> Beta-only:
> 
> * container_aws_cluster: monitoring_config
> * container_azure_cluster: monitoring_config
> * gkehub_feature_membership: mesh
> 
> Please update the release notes to ensure all those fields are represented, as well as:
> 
> Beta-only
> 
> * clouddeploy_delivery_pipeline: strategy - has tests 👍
> * clouddeploy_target: run - has tests 👍
> 
> And ensure that all release notes are formatted according to the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md)


Currently I am have a PR open for adding eventarc channel:https://github.com/GoogleCloudPlatform/magic-modules/pull/6529  however I am waiting for these changes to be merged so I can update the version of the dcl on my PR

**Comment by alphanota** [comment]
@SirGitsalot made requested changes. Thanks!

**Review by melinath — CHANGES_REQUESTED** [review]
> > @SirGitsalot could you clarify what you mean by `path` in this case?
> 
> How does Angel resolve these test issues:
> 
> * eventarc_trigger: channel
> 
> To configure this field, the channel that's referenced must exist AIUI. TPG doesn't have support for Eventarc Channel resources, so any TPG test that uses this field must have some non-TPG way of creating Channels.

We should remove the field and add it back after the Eventarc Channel resource exists. (or as part of the PR adding that resource.)


> * gkehub_feature_membership: mesh
> 
> gkehub_feature_membership doesn't seem to have any tests to add the `mesh` field to (although it's entirely possible I'm looking in the wrong place)

it looks like all tests for this resource are currently [handwritten](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/README.md#testing) in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb

**Comment by SirGitsalot** [comment]
@alphanota See #6731 to copy over a test for gkehub_feature_membership mesh and exclusions for the channel field for eventarc trigger

@daveavi for vis since you'll need to delete the exclusions (assuming they end up merged) once you're ready to merge your own PR

**Comment by alphanota** [comment]
@SirGitsalot merged your branch into this one.

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like there are two permadiffs causing the following tests to fail:

- TestAccContainerAzureCluster_BetaBasicHandWritten
- TestAccContainerAwsCluster_BetaBasicHandWritten

Since the monitoring_config fields are new in this PR, you could either fix the tests or exclude the field additions for now & fix them later.

`TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample` seems unrelated.

**Comment by ghabian** [comment]
> TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample seems unrelated.

merged PR #6726 should fix this test going forward

**Comment by daveavi** [comment]
> @alphanota See #6731 to copy over a test for gkehub_feature_membership mesh and exclusions for the channel field for eventarc trigger
> 
> @daveavi for vis since you'll need to delete the exclusions (assuming they end up merged) once you're ready to merge your own PR

Sounds good Chris!

**Review by melinath — CHANGES_REQUESTED** [review]
please resolve test failures as described above

**Comment by ghabian** [comment]
@melinath Looks like we're all set now?

**Review by melinath — APPROVED** [review]
LGTM

**Comment by melinath** [comment]
@rileykarson looks like you have to approve this as codeowner.

**Comment by ghabian** [comment]
Thank you so much! @rileykarson if we could hold on cutting a release until my other PR (#6693) is merged as well (currently held up because of this one)

**Review by rileykarson — APPROVED** [review]
Ah, I should take off the CODEOWNERS bit. That was to make sure we didn't inadvertently release some stuff & that window's passed.

**Pull request merged**
