### PR TITLE
Update documentation for google_compute_region_per_instance_config

### PR DESCRIPTION
**Pull request by steveazz**
## docs: fix region defention for region stateful mig

`google_compute_instance_group_manager` is not defined anywhere in the
example and here we are talking about region instance groups and not
zonal.

## docs: add required update_policy for stateful migs 

When you don't specify an `update_policy` and run `terraform apply` you
end up getting the following error:

```
Error waiting to create RegionPerInstanceConfig: Error waiting for Creating RegionPerInstanceConfig: CreateInstances can be used only when instance redistribution is disabled (set to NONE).
```

Also specify [`minimal_action`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager#minimal_action) and [`type`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager#type) since they are both required for `update_policy`

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by steveazz** [comment]
Do I open the PR to update https://github.com/hashicorp/terraform-provider-google now or after this is merged/approved?

**Review by melinath — APPROVED** [review]
LGTM

**Comment by melinath** [comment]
@steveazz after I merge this PR, the changes will be automatically merged into the providers. Thanks for contributing!

**Pull request merged**
