### PR TITLE
Promote Cloud SQL CMEK feature to ga

### PR DESCRIPTION
**Pull request by rkmoorthy-github**
Cloud SQL supports CMEK feature and it has been in GA (https://cloud.google.com/sql/docs/mysql/configure-cmek). So promoting the terraform attribute to ga.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
sql: promoted attribute "encryption_key_name" to GA in `google_sql_database_instance` resource.
```

### CODE REVIEW

**Comment by rkmoorthy-github** [comment]
Below is my test log.

$ make testacc TEST=./google-beta TESTARGS='-run=TestAccSqlDatabaseInstance_encryption'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=TestAccSqlDatabaseInstance_encryption -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccSqlDatabaseInstance_encryptionKey
=== PAUSE TestAccSqlDatabaseInstance_encryptionKey
=== RUN   TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
=== PAUSE TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
=== CONT  TestAccSqlDatabaseInstance_encryptionKey
=== CONT  TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
--- PASS: TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion (568.43s)
--- PASS: TestAccSqlDatabaseInstance_encryptionKey (586.75s)
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta 586.852s

**Comment by rkmoorthy-github** [comment]
make testacc TEST=./google TESTARGS='-run=TestAccSqlDatabaseInstance_encryption'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccSqlDatabaseInstance_encryption -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
        === RUN   TestAccSqlDatabaseInstance_encryptionKey
=== PAUSE TestAccSqlDatabaseInstance_encryptionKey
=== RUN   TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
=== PAUSE TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
=== CONT  TestAccSqlDatabaseInstance_encryptionKey
=== CONT  TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion
--- PASS: TestAccSqlDatabaseInstance_encryptionKey (539.95s)
--- PASS: TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion (597.41s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   597.504s

**Comment by shuyama1** [comment]
Triggered GA test on TC: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/309823

**Review by shuyama1 — APPROVED** [review]
Tests passed! LGTM! Thank you for your contribution!

**Pull request merged**
