### PR TITLE
Add Dataplex Lake to tpg built from their DCL resources

### PR DESCRIPTION
**Pull request by saurabhmaurya06**
part of https://github.com/hashicorp/terraform-provider-google/issues/11648

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-resource
`google_dataplex_lake`
```

### CODE REVIEW

**Comment by saurabhmaurya06** [comment]
@slevenick, I've closed an existing pull request (https://github.com/GoogleCloudPlatform/magic-modules/pull/6049) and am splitting that one into 3 separate pull requests.

**Comment by saurabhmaurya06** [comment]
I believe the failing tests are unrelated to this pull request.

**Comment by slevenick** [comment]
I'm not seeing any tests generated by this. I believe the samples should go under `tpgtools/overrides/datalake/samples` rather than `tpgtools/api` which should trigger test generation

**Comment by saurabhmaurya06** [comment]
I think the tests are supposed to be under tpgtools/api but under a samples directory. I'm using https://github.com/GoogleCloudPlatform/magic-modules/pull/5999/files# as a reference.

I've changed my samples to be in line with this pull request. Let me know if it looks fine now.

**Comment by slevenick** [comment]
Looks mostly good. The `name` field description coming from the DCL is incorrect, so we should fix that prior to release.

https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6055-old..auto-pr-6055#diff-28f548553b92b83fa060dea95c0a470d0cbdfd311d90d1d3291fdcc237f5ea03R57

It shouldn't say Output only (because it isn't) and shouldn't claim to require the long-form name

**Comment by saurabhmaurya06** [comment]
I've made the changes to DCL. I'll test the changes here again after DCL cuts a new version to 1.7.1. 
I'm not sure what triggers new versions, but I hope we can do that before Monday afternoon.

**Comment by slevenick** [comment]
Unfortunately DCL version 1.8.0 contains a regression and I don't believe we can upgrade to it at this time, we may need to wait for a fix

**Review by slevenick — APPROVED** [review]
Looks good, only test failure is unrelated and will be fixed with https://github.com/GoogleCloudPlatform/magic-modules/pull/6066

**Pull request merged**
