### PR TITLE
Add Google HC Datasource

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8429

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_compute_health_check`
```

### CODE REVIEW

**Comment by upodroid** [comment]
I'm getting a weird error in the test.

The error is present in both `TestAccComputeHealthCheckDatasource_basic` and `TestAccDataSourceComputeBackendService_basic`
```
2021/02/19 21:49:45 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/02/19 21:49:45 [DEBUG] Retry Transport: Returning after 1 attempts
    testing_new_config.go:96: no "id" found in attributes
    testing_new.go:49: no "id" found in attributes
--- FAIL: TestAccDataSourceComputeBackendService_basic (41.08s)
```

**Comment by slevenick** [comment]
> I'm getting a weird error in the test.
> 
> The error is present in both `TestAccComputeHealthCheckDatasource_basic` and `TestAccDataSourceComputeBackendService_basic`
> 
> ```
> -----------------------------------------------------
> 2021/02/19 21:57:05 [DEBUG] Retry Transport: Stopping retries, last request was successful
> 2021/02/19 21:57:05 [DEBUG] Retry Transport: Returning after 1 attempts
>     testing_new_config.go:96: no "id" found in attributes
>     testing_new.go:49: no "id" found in attributes
> --- FAIL: TestAccComputeHealthCheckDatasource_basic (29.44s)
> FAIL
> FAIL	github.com/hashicorp/terraform-provider-google-beta/v3/google-beta	31.702s
> FAIL
> ```
> 
> ```
> 2021/02/19 21:49:45 [DEBUG] Retry Transport: Stopping retries, last request was successful
> 2021/02/19 21:49:45 [DEBUG] Retry Transport: Returning after 1 attempts
>     testing_new_config.go:96: no "id" found in attributes
>     testing_new.go:49: no "id" found in attributes
> --- FAIL: TestAccDataSourceComputeBackendService_basic (41.08s)
> ```
/gcbrun

Are you running the tests with a new version of Terraform core? I believe that 0.14.x causes some issues in datasource tests specifically, so we still run the CI tests on 0.13 or 0.12. I'd recommend having an alternate version of TF core to be able to run these sorts of tests

**Comment by upodroid** [comment]
Ah, Cameron mentioned something about this. I forgot

**Comment by upodroid** [comment]
Bump

**Comment by slevenick** [comment]
/gcbrun

Sorry I've taken so long to review!

**Comment by slevenick** [comment]
This seems good to me. Assuming tests pass I'll merge

**Review by slevenick — APPROVED** [review]
Test passes, thanks for the addition!

**Pull request merged**
