### PR TITLE
Make the sed command work on OSX.

### PR DESCRIPTION
**Pull request by ndmckinley**
Just a DCL upgrade that runs on OSX - the `-i` works differently on OSX than linux.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
I get the following diff on `go.sum`, does that look right? Specifically the `-e` prepended on one of the lines

```
diff --git a/mmv1/third_party/terraform/go.sum b/mmv1/third_party/terraform/go.sum
index bdcabbe12..89d5b4bfc 100644
--- a/mmv1/third_party/terraform/go.sum
+++ b/mmv1/third_party/terraform/go.sum
@@ -1413,3 +1413,5 @@ github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-202109
 github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-20210918014849-ef8e2b337288/go.mod h1:oEeBHikdF/NrnUy0ornVaY1OT+jGvTqm+LQS0+ZDKzU=
 github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-20210921224745-48b8ffa00a5a h1:5G/+2v/atxzGvjxAZloMbAoad19hYRCbmGyW60SyCcE=
 github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-20210921224745-48b8ffa00a5a/go.mod h1:oEeBHikdF/NrnUy0ornVaY1OT+jGvTqm+LQS0+ZDKzU=
+-e github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-20210923164710-b8734d273ffb h1:by1flCMHI4mpQYSUN5RIGUVv8FhVS+vgpzOqP/jgIVY=
+github.com/GoogleCloudPlatform/declarative-resource-client-library v0.0.0-20210923164710-b8734d273ffb/go.mod h1:oEeBHikdF/NrnUy0ornVaY1OT+jGvTqm+LQS0+ZDKzU=
```

**Comment by ndmckinley** [comment]
Hmmm ... no, clearly wrong, dang.  Okay, maybe that's easy to fix...

**Comment by ndmckinley** [comment]
Oh dang, "echo" is different on mac, too.  Oh, man, come _on_.

**Review by rileykarson — APPROVED** [review]
LGTM!

Not needed for this one, but should we consider using Go or Python for similar scripts in the future? They're definitely more heavyweight, but they should be easier for folks to understand (bash feels write-only sometimes) and won't have the same kinds of cross-OS compatibility problems.

**Comment by ndmckinley** [comment]
> LGTM!
> 
> Not needed for this one, but should we consider using Go or Python for similar scripts in the future? They're definitely more heavyweight, but they should be easier for folks to understand (bash feels write-only sometimes) and won't have the same kinds of cross-OS compatibility problems.

Hmm... I tend to think if it can be a short shell script, it should be - go / python are great, readable, cross-platform - but they're annoying when you're dealing with moving files around, changing contents, etc.  And they have a much higher bar for error handling and reporting.

**Comment by rileykarson** [comment]
> Hmm... I tend to think if it can be a short shell script, it should be - go / python are great, readable, cross-platform - but they're annoying when you're dealing with moving files around, changing contents, etc. And they have a much higher bar for error handling and reporting.

Definitely! I think if we expect those scripts to have to switch modes between MacOS and Linux tools, though, we're getting past the "short shell script" territory. There's obviously ways to, say, install the Linux versions on MacOS- but we've also got community contributors or occasional contributors, and I don't think we can expect them to do the same.

**Comment by ndmckinley** [comment]
+1, I think we agree, except as usual we draw the lines in slightly different places.  

for instance, `generate_downstreams.sh`, which I consider a magnus opus of questionable shell scripts, is probably a smidge past your line of acceptable shell.  :p

**Comment by rileykarson** [comment]
Yeah, that's one that if it were being newly written I'd push for go/python 🙂 

Anyways, not a blocker here regardless!

**Pull request merged**
