### PR TITLE
Add new terraform sample - CDN XLB with Backend Bucket

### PR DESCRIPTION
**Pull request by msampathkumar**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by slevenick** [comment]
Whats the reason for adding this example? I'm worried because it's a fairly large example with a lot of config and it will be added to our docs page here: https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5869-old..auto-pr-5869#diff-0bd72faa5634a22f080fa06fe8346998911d494e1f50499d29d1bb67586aaa7eR40

Can we restrict this to only the cloud docs if that is the intended target?

**Review by slevenick — APPROVED** [review]

**Comment by shuyama1** [comment]
Looks like `TestAccComputeGlobalForwardingRule_externalCdnLbWithBackendBucketExample` is constantly failing in VCR and also failed in CI last night https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/278011?buildTab=tests&status=failed&name=TestAccComputeGlobalForwardingRule_externalCdnLbWithBackendBucketExample&pager.currentPage=1&expandedTest=-5379752785185941961

**Comment by slevenick** [comment]
Huh, then why did it pass in VCR?

I guess I'll revert again!

**Comment by shuyama1** [comment]
I think VCR got timeout and did not run this test https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr/274382?buildTab=tests&status=all&pager.currentPage=1

**Comment by shuyama1** [comment]
If a beta-only test does not have `provider = google-beta` on the resources, it will fail in our nightly test but pass in VCR (https://github.com/GoogleCloudPlatform/magic-modules/pull/5852). I will look into the problem and try to get it fixed next week.
While this PR is more than that I guess. It seems lack of `provider = google-beta` on some resources but after adding it I still got errors
```
    provider_test.go:309: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: Invalid resource type
        
          on terraform_plugin_test.tf line 118, in resource "local_file" "index_page":
         118: resource "local_file" "index_page" {
        
        The provider hashicorp/google-beta does not support resource type
        "local_file".
        
        Error: Invalid resource type
        
          on terraform_plugin_test.tf line 129, in resource "local_file" "error_page":
         129: resource "local_file" "error_page" {
        
        The provider hashicorp/google-beta does not support resource type
        "local_file".
        
        Error: Invalid resource type
        
          on terraform_plugin_test.tf line 140, in resource "null_resource" "test_image":
         140: resource "null_resource" "test_image" {
        
        The provider hashicorp/google-beta does not support resource type
        "null_resource".
```

**Pull request merged**
