### PR TITLE
Handle case where policy_data is empty in terraform validator

### PR DESCRIPTION
**Pull request by iyabchen**
b/225382823
Handle the case when policy_data is empty, it should not throw unmarshal error. 
- added a case to make policy_data contain a var, then in terraform plan it will show as (known as apply), in terraform json data, it will be empty string. 

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
VCR recording mode did not run correctly. Fixed the error in new VCR script and testing it in this PR now.
/gcbrun

**Comment by melinath** [comment]
@shuyama1 I don't know if this is something you want to change but this PR doesn't impact the providers, so it shouldn't need to run VCR tests at all

**Comment by shuyama1** [comment]
@melinath I think you are right. But the failing test `TestAccAccessContextManager` seems only happen in this PR and that's weird.

**Comment by shuyama1** [comment]
@melinath  Sorry. Looks like I was wrong. Also see `TestAccAccessContextManager` failed in other PRs!

**Comment by melinath** [comment]
/gcbrun since the pipeline should be more stable now.

**Review by melinath — APPROVED** [review]
LGTM. I'll merge assuming tests pass - ping me if I don't get to it in a day.

**Pull request merged**
