### PR TITLE
dataform_repository - add missing args

### PR DESCRIPTION
**Pull request by DrFaust92**
Closes https://github.com/hashicorp/terraform-provider-google/issues/15975

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dataform: added `display_name`, `labels` and `npmrc_environment_variables_secret_version` fields to `google_dataform_repository` resource 
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Sorry I somehow missed this from my review list.

This test failed with error:
```
 Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # google_dataform_repository.dataform_respository must be replaced
        -/+ resource "google_dataform_repository" "dataform_respository" {
              ~ id                                         = "projects/ci-test-project-188019/locations/us-central1/repositories/tf_test_dataform_repository76o4gxbo8z" -> (known after apply)
                name                                       = "tf_test_dataform_repository76o4gxbo8z"
              ~ set_authenticated_user_admin               = false -> true # forces replacement
                # (6 unchanged attributes hidden)
        
              ~ git_remote_settings {
                  + token_status                        = (known after apply)
                    # (3 unchanged attributes hidden)
                }
        
                # (1 unchanged block hidden)
            }
```

Are you able to get the test passed locally? It could be that the API does not return this field at all

**Comment by DrFaust92** [comment]
Thanks, will check there was a big rebase after initial test

**Review by shuyama1 — COMMENTED** [review]
LGTM! Only one small comment. Thanks!

**Review by shuyama1 — APPROVED** [review]
Thank you!

**Pull request merged**
