### PR TITLE
Add Cloud Composer Ip Masq Agent and Privately Used Public Ips to GA.

### PR DESCRIPTION
**Pull request by mhenc**
If this PR is for Terraform, I acknowledge that I have:

- [ x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
composer: promoted `config.privately_used_public_ips` and `config.ip_masq_agent` in `google_composer_environment` resource to GA.
```

### CODE REVIEW

**Comment by megan07** [comment]
Running tests in GA: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/298475

**Comment by mhenc** [comment]
I don't have access to TeamCity, can you please provide some log output?

**Comment by megan07** [comment]
Hi @mhenc , yea, sorry - I have one failing test, but I don't think it's related - I think it's just flaky, so I'm re-running it and will let you know!

**Review by megan07 — APPROVED** [review]
Test failure was unrelated! Looks good to me! Thanks!

**Pull request merged**
