### PR TITLE
Add support for max pods per node configuration to Composer (beta)

### PR DESCRIPTION
**Pull request by gor-obr**
Add `max_pods_per_node` to `google_composer_environment` (beta)

fixes hashicorp/terraform-provider-google#9346

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
composer: added field `max_pods_per_node` to resource `google_composer_environment` (beta)
```

### CODE REVIEW

**Comment by rileykarson** [comment]
@gor-obr: We spoke offline about making a change to set the field as `Computed: true`. Have you had a chance to make the change yet?

**Comment by gor-obr** [comment]
> @gor-obr: We spoke offline about making a change to set the field as `Computed: true`. Have you had a chance to make the change yet?



> @gor-obr: We spoke offline about making a change to set the field as `Computed: true`. Have you had a chance to make the change yet?

Not yet. Quick question, do I need to squash the new commit with the original one, or I can just add a commit to the pull request?

**Comment by rileykarson** [comment]
Either is fine, we squash as part of the merge.

**Comment by gor-obr** [comment]
> > @gor-obr: We spoke offline about making a change to set the field as `Computed: true`. Have you had a chance to make the change yet?
> 
> Not yet. Quick question, do I need to squash the new commit with the original one, or I can just add a commit to the pull request?

@rileykarson I have pushed the fix yesterday, and last comment I see here is that VCR tests have been triggered. I don't know if they passed (no info that they failed as in previous cases). Have the tests passed now?

**Review by rileykarson — APPROVED** [review]
Yes, they passed! Sorry about the delay in getting back. LGTM.

**Pull request merged**
