### PR TITLE
Add datasource for google_compute_instance_group_manager

### PR DESCRIPTION
**Pull request by kutysam**
Google compute instance group manager and region instance group manager datasources seem to be missing in google's terraform provider.

We need datasource to extract things like instance_template from the instance group manager.
There are two versions, region and zone. Both are very similar. 

The APIs that these 2 PRs are related to are
1. `google_compute_instance_group_manager` - https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers/get
2. `google_compute_region_instance_group_manager` - 
https://cloud.google.com/compute/docs/reference/rest/v1/instanceRegionGroupManagers/get

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
data_source_google_compute_instance_group_manager: Add datasource for google compute instance group manager
data_source_google_compute_region_instance_group_manager: Add datasource for google compute region instance group manager
```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
Rather than handwriting the datasource, can you use the DS utility functions? That will keep the schema in sync. This an an example: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/data_sources/data_source_google_compute_disk.go

**Review by rileykarson — COMMENTED** [review]
Rather than handwriting the datasource, can you use the DS utility functions? That will keep the schema in sync. This an an example: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/data_sources/data_source_google_compute_disk.go

**Comment by kutysam** [comment]
> Rather than handwriting the datasource, can you use the DS utility functions? That will keep the schema in sync. This an an example: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/data_sources/data_source_google_compute_disk.go

Thanks for this! I'll work on this format in coming days.

**Comment by kutysam** [comment]
Closing this PR

**Pull request closed without merging**
