### PR TITLE
upgrade DCL

### PR DESCRIPTION
**Pull request by shuyama1**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by slevenick — APPROVED** [review]
Looks good! There were some changes around how the DCL handles empty arrays which is why some tests needed re-recording, but they all pass!

**Comment by shuyama1** [comment]
Looks like validator-test-integration-0.12.31 failed. @melinath @ScottSuarez Could you help take a look at this? Thanks!

**Comment by ScottSuarez** [comment]
Could you rebase?

it's not immediately clear whats going on here

**Comment by shuyama1** [comment]
> Could you rebase?
> 
> it's not immediately clear whats going on here

Done!

**Comment by ScottSuarez** [comment]
looks like it passed

**Comment by shuyama1** [comment]
Interesting. My branch should be on the top yesterday, but it still failed. No ideas why that happened. 
@ScottSuarez Thanks so much for the help!

**Pull request merged**
