### PR TITLE
new datasource: sql databases

### PR DESCRIPTION
**Pull request by ravisiddhu**
This PR is in reference to https://github.com/hashicorp/terraform-provider-google/issues/11587

Buganizer ticket : http://b/263687902

I have created a new data source for listing databases in a cloud sql instance with different filter options and have also created test functions and documentation for the same.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-datasource
google_sql_databases
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
I'm a little hesitant about the filtering functionality provided in this PR. We don't have a lot of plural datasources like this, and of the ones we have, the only filtering is server-side.

It looks like the filtering implemented here matches filtering implementation on a somewhat similar AWS resource - however, that is using a filter schema that is [standard to AWS](https://github.com/hashicorp/terraform-provider-aws/blob/0c7234baac289e44cf00646f16e8d13425ec10fc/internal/service/ec2/ec2_ami_data_source.go#L93) and which may not make sense to google provider users.

In the google provider the "standard" filtering mechanism (as much as we have one) is generally a `filter` field that is server-side, which can allow for [complex queries](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/projects#example-usage---searching-for-projects-about-to-be-deleted-in-an-org). Unfortunately, filtering on the List endpoint is not (yet?) available for this resource.

Since the client-side filtering is listed as "also useful" in https://github.com/hashicorp/terraform-provider-google/issues/11587, I would prefer to leave filtering off of this altogether. We can have a discussion about adding filtering and what the UX would be separately. What do you think?

**Comment by ravisiddhu** [comment]
I agree with you. We can start with a standard datasource which would list all databases and we can think of client side filtering later. I will make the necessary changes.

**Comment by ravisiddhu** [comment]
I have removed the client side filtering, and now this datasource would simply lists all the databases present in the instance.

**Comment by melinath** [comment]
@ravisiddhu thanks! By the way, one thing that can come up for plural datasources like this is that the order returned from the API is non-deterministic, which can cause diffs for users; do you happen to know what the case is here?

**Comment by ravisiddhu** [comment]
> @ravisiddhu thanks! By the way, one thing that can come up for plural datasources like this is that the order returned from the API is non-deterministic, which can cause diffs for users; do you happen to know what the case is here?

For datasources diff would be generated only for the input fields, which in this case are the `project` and the `instance` fields, rest all are `computed` = `true` fields, hence there would not be any terraform diff generated for non-deterministic orders.

**Comment by melinath** [comment]
> For datasources diff would be generated only for the input fields, which in this case are the `project` and the `instance` fields, rest all are `computed` = `true` fields, hence there would not be any terraform diff generated for non-deterministic orders.

Correct, the diff would be in the resource _referencing_ the datasource. So for example, if a user does something like:

```
data "google_sql_databases" "qa" {
    instance = google_sql_database_instance.main.name
}

resource "google_some_resource" "my-resource" {
    database = data.google_sql_databases.qa.databases[0]
}
```

Then they might see a diff on `google_some_resource.my-resource` on subsequent applies if there is more than one database returned by the datasource and the order is non-deterministic.

**Comment by ravisiddhu** [comment]
> > For datasources diff would be generated only for the input fields, which in this case are the `project` and the `instance` fields, rest all are `computed` = `true` fields, hence there would not be any terraform diff generated for non-deterministic orders.
> 
> Correct, the diff would be in the resource _referencing_ the datasource. So for example, if a user does something like:
> 
> ```
> data "google_sql_databases" "qa" {
>     instance = google_sql_database_instance.main.name
> }
> 
> resource "google_some_resource" "my-resource" {
>     database = data.google_sql_databases.qa.databases[0]
> }
> ```
> 
> Then they might see a diff on `google_some_resource.my-resource` on subsequent applies if there is more than one database returned by the datasource and the order is non-deterministic.

Wouldn't the list returned by the databases.list admin API deterministic since in MySQL the API is reading from the `information_schema.SCHEMATA` table in order and in Postgres the API is reading from `pg_catalog.pg_database` table in order?

Since there already exists databases.list(https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/databases/list) Admin API, wouldn't it just make sense to provide this support for terraform customers also?

**Comment by melinath** [comment]
@ravisiddhu Some list APIs are non-deterministic, hence my question :-) If you believe that this one is deterministic, then that's great! I think you likely know better than I do.

If this API is non-deterministic, that's not a blocker either - we could add client-side sorting as part of this PR.

Let me know what you think.

**Comment by ravisiddhu** [comment]
I think we can consider client-side filtering as a separate PR after discussion with other teams also.

**Comment by melinath** [comment]
@ravisiddhu yes, I agree that client-side filtering should be a separate PR.

Do you know whether the API response is in a deterministic order? If not, it would be best to add client-side sorting in this PR; otherwise it will be confusing for users.

**Comment by ravisiddhu** [comment]
I checked the code and from the sql query it seems to be determinstic but want to confirm with database teams to be completely sure, and hence not adding the client side logic along with this PR.

**Review by melinath — CHANGES_REQUESTED** [review]
It seems like the order is not deterministic, so we should add client-side sorting to make sure the behavior is consistent. Specifically, it seems like ordering by the `name` field would likely work?

**Comment by ravisiddhu** [comment]
Agreed. I have added client-side sorting based on the database names to provide consistent ordering of the databases.

**Review by melinath — APPROVED** [review]

**Pull request merged**
