### PR TITLE
Added support for adaptive protection to google_compute_security_policy

### PR DESCRIPTION
**Pull request by matty-rose**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/8984

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added field `adaptive_protection_config` to `google_compute_security_policy` (beta)
```

### CODE REVIEW

**Review by c2thorn — CHANGES_REQUESTED** [review]
Hey @matty-rose,

Recently we've been wanting to restrict the use of beta APIs in the GA provider. Can we change this to use the appropriate client based on the version? We could use a variable to hold `config.NewComputeClient(userAgent)` vs `config.NewComputeClient(userAgent)` or something to that extent.

**Comment by matty-rose** [comment]
@c2thorn that makes a lot of sense, do you have any suggestions/preferences on how to handle all the `flatten`/`expand` methods? i.e. just duplicate all methods with both `compute` and `computeBeta` type signatures, and generate in a large `if/else` block?

**Comment by c2thorn** [comment]
> @c2thorn that makes a lot of sense, do you have any suggestions/preferences on how to handle all the `flatten`/`expand` methods? i.e. just duplicate all methods with both `compute` and `computeBeta` type signatures, and generate in a large `if/else` block?

Using https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/resources/resource_dataproc_cluster.go.erb as a reference, I believe we may be able to remove the `computeBeta` part of the import and refer to both clients as `compute._` in the flatteners and expanders.

**Comment by matty-rose** [comment]
thanks for that example @c2thorn, have pushed changes and tests are passing locally for both ga and beta providers so hopefully the magician agrees 🤞

**Review by c2thorn — APPROVED** [review]
Seems good from my end, thanks for bearing with us on this tricky change!

**Pull request merged**
