### PR TITLE
fix: do not store the ssl_mode field locally if it has never been used.

### PR DESCRIPTION
**Pull request by feng-zhe**
This is to make sure the irrelevant workflows doesn't need to set this ssl_mode field. See
[PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/9396) for details.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
Do not store the ssl_mode field locally if it has never been used.
```

### CODE REVIEW

**Review by SarahFrench — COMMENTED** [review]
👋 Hi there - there's currently a lint check failing on this PR, could you please fix it?

```
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
make: *** [GNUmakefile:26: fmtcheck] Error 1
./google-beta/services/sql/resource_sql_database_instance_test.go
You can use the command: `make fmt` to reformat code.
```

Meanwhile, I'm going to trigger a non-VCR version of the acceptance test [mentioned in this issue](https://github.com/hashicorp/terraform-provider-google/issues/16435) to run against this PR.

**Comment by feng-zhe** [comment]
> 👋 Hi there - there's currently a lint check failing on this PR, could you please fix it?
> 
> ```
> ==> Checking that code complies with gofmt requirements...
> gofmt needs running on the following files:
> make: *** [GNUmakefile:26: fmtcheck] Error 1
> ./google-beta/services/sql/resource_sql_database_instance_test.go
> You can use the command: `make fmt` to reformat code.
> ```
> 
> i.e. (`mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go`)
> 
> Meanwhile, I'm going to trigger a non-VCR version of the acceptance test [mentioned in this issue](https://github.com/hashicorp/terraform-provider-google/issues/16435) to run against this PR.
> 
> Edit: [results here](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_MmUpstreamTesting_GOOGLE_PACKAGE_SQL/54886?buildTab=tests)

Thanks, I have fixed the lint error and the failed tests passed.

**Comment by feng-zhe** [comment]
Hi @SarahFrench, thanks for reviewing this PR. I see all presubmit tests passed. Unfortunately I cannot login to the team city and see the test result you mentioned before. I see `Authenticated successfully, but failed to create a new user since creating new users by "GitHub.com" login is not allowed`.

Are the tests passing? Thanks.

**Comment by SarahFrench** [comment]
Sorry for the delay, and that link to tests that I posted was for me/other reviewers to look at one the build had completed, so no worries about being unable to access it.

All of the sql acceptance tests except `TestAccSqlUser_postgresIAM` passed for this PR, and that test's failure isn't related to this PR. I can see that the `TestAccSqlDatabaseInstance_basicMSSQL test` ([mentioned here](https://github.com/hashicorp/terraform-provider-google/issues/16435)) fails with the latest release of the provider but passes with the changes in this PR, so LGTM

**Review by SarahFrench — APPROVED** [review]

**Comment by feng-zhe** [comment]
Thank you, SarahFrench!

**Pull request merged**
