### PR TITLE
Upstream docs change about source for instance template

### PR DESCRIPTION
**Pull request by emilymye**
Upstream https://github.com/terraform-providers/terraform-provider-google/pull/6064

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by emilymye** [comment]
Overriding CLA for third_party (@ArseniiPetrovich feel free to sign CLA but we don't require it for third_party)

**Comment by ArseniiPetrovich** [comment]
I'm not sure how to sign CLA in the right way, but I would like to sign :)

**Comment by emilymye** [comment]
@ArseniiPetrovich I believe you can sign the CLA from the "login here" link above

**Comment by ArseniiPetrovich** [comment]
> @ArseniiPetrovich I believe you can sign the CLA from the "login here" link above

Unfortunately, I can't. I get "We don't have any individual agreements on file for you." ¯\_(ツ)_/¯

**Pull request merged**
