### PR TITLE
TeamCity: Add ability to save test log artifacts to all build configurations

### PR DESCRIPTION
**Pull request by SarahFrench**
This PR adds the ability to make log artefacts (see here for [example in old projects](https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/425950?buildTab=artifacts)) to the new TC projects.

Here's a place I manually tested the code changes in this PR and got log artifacts created per test : https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_SarahManualTestingProject_GOOGLE_PACKAGE_BILLING/17306?buildTab=artifacts

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
TODO:
- Add `TF_LOG_PATH_MASK` ENV variable
- Ensure that the TF_LOG_PATH_MASK value, and value I included in the first commit on this PR are still correct for the new projects

**Comment by SarahFrench** [comment]
This build reflects the latest commit that changes the file's extension to .txt, allowing us to open the file in our browsers instead of it downloading automatically: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_SarahManualTestingProject_GOOGLE_PACKAGE_BILLING/17701?buildTab=artifacts

**Review by shuyama1 — APPROVED** [review]
LGTM. Not sure if saving the debug log as a text file will have limitation on log length, but I think it's good for now

**Comment by SarahFrench** [comment]
> Not sure if saving the debug log as a text file will have limitation on log length

Me neither, but I don't think I have the ability to influence if TeamCity opens the file in-browser or makes it download by any other means. If problems do occur I'll revert the files to saving as .log files and they'll need to be downloaded.

**Pull request merged**
