### PR TITLE
Documentai Processor

### PR DESCRIPTION
**Pull request by slevenick**
Adds DocumentAI Processor resource and processor default version FGR

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_documentai_processor
```
```release-note:new-resource
google_documentai_processor_default_version
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like `mmv1/templates/terraform/post_create/documentai_processor.go.erb` was added but is no longer used - could it be removed?

Relatedly - why does being able to directly set the field on the resource end up not working?

**Comment by slevenick** [comment]
> It looks like `mmv1/templates/terraform/post_create/documentai_processor.go.erb` was added but is no longer used - could it be removed?
> 
> Relatedly - why does being able to directly set the field on the resource end up not working?

Ah good call, that's from a previous impementation.

Setting the field during create isn't allowed by the API, but the bigger deal is that I would expect in the future for this to be able to reference user-created processor versions, which are sub-resources of this processor resource. So it will create a circular dependency between processor -> processorVersion -> defaultProcessorVersion

**Review by melinath — APPROVED** [review]
b/209050020

Gotcha - so the issue is that if a user tries to create a processor and a version and also use that version as the default version all in a single apply, Terraform wouldn't be able to process the dependency chain - but if the default version is set by a separate resource, that breaks the circular dependency and makes it work intuitively.

LGTM. Is there a precedent for this setup?

**Comment by slevenick** [comment]
> 

Heres an example of a similar issue and the fix was adding a new FGR: https://github.com/hashicorp/terraform-provider-google/issues/2686

Yeah, the issue is that we need to split out the defaultVersion to allow Terraform to build the dependency graph successfully

**Pull request merged**
