### PR TITLE
remove computed keys from json

### PR DESCRIPTION
**Pull request by megan07**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/9976
Fixes https://github.com/hashicorp/terraform-provider-google/issues/7242 as well, I think

I chose this approach because that second issue seemed to show there were more fields than just the one showing up in the test that were computed, and I think this should cover them all, but it's also possible I'm overlooking a potential issue.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
monitoring: fixed perma-diff in `google_monitoring_dashboard` by not comparing computed keys returned by API that aren't defined in the config.
```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
This changes the resource behaviour, given that fields not in config won't appear anymore so drift detection on them won't work. Do you feel this could be a breaking change?  Should we document it in a warning on the resource?

**Comment by IchordeDionysos** [comment]
@rileykarson @megan07 what is the status of this PR?
Will be merged for the upcoming 5.0.0 release?

**Comment by rileykarson** [comment]
Ah, we'd lost track of this- @c2thorn can you take a look?

**Comment by c2thorn** [comment]
This is targeted for 5.0.0 release, but will need someone to take it over. I'll tentatively take it.

**Comment by c2thorn** [comment]
closing in favor of https://github.com/GoogleCloudPlatform/magic-modules/pull/9065

**Pull request closed without merging**
