### PR TITLE
Change zone of TPU node to get less OOM* messages

### PR DESCRIPTION
**Pull request by ScottSuarez**
Trying to fix consistent failures on `TestAccTPUNode_*` tests. 

While there is nothing /wrong/ with the test per-say this zone consistently runes out of units. Swapping to another zone to see if it alleviates the problem.

```
Error: Error waiting to create Node: Error waiting for Creating Node: Error code 8, message: There is no more capacity in the zone "us-central1-b"; you can try in another zone where Cloud TPU Nodes are offered (see https://cloud.google.com/tpu/docs/regions)
```

closes https://github.com/hashicorp/terraform-provider-google/issues/10222

*oom: https://www.urbandictionary.com/define.php?term=oom
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by roaks3** [comment]
This makes sense. My understanding is that there is a hard limit of TPUs per zone, so this seems like the best way to get around that.

I'm not sure why these tests are suddenly failing on the AcceleratorType though (they seem to have passed in CI ~1 week ago), but maybe we need to update those fields as well?

**Comment by roaks3** [comment]
This one looks like it's still having diff issues with the version, no clue what's going on there

**Comment by ScottSuarez** [comment]
> This one looks like it's still having diff issues with the version, no clue what's going on there

Yeah, I've reached out to the team.. Hoping they can reserve some small quota for us

**Comment by roaks3** [comment]
@ScottSuarez could you possibly share a ticket if we have one for the quota increase, or mention if there are blockers at this point?

**Comment by ScottSuarez** [comment]
> @ScottSuarez could you possibly share a ticket if we have one for the quota increase, or mention if there are blockers at this point?

Added you to the email chain

**Pull request closed without merging**
