### PR TITLE
StorageTransfer Service: Support FederatedIdentifyConfig for Azure Blob Storage

### PR DESCRIPTION
**Pull request by venky999**
Release Note Template for Downstream PRs (will be copied)

Support FederatedIdentifyConfig in StorageTransfer Service for Azure Blob Storage 
Fixes https://github.com/hashicorp/terraform-provider-google/issues/19526

Note: Will work after merging https://github.com/googleapis/google-api-go-client/pull/2810

### CODE REVIEW

**Review by slevenick — COMMENTED** [review]
Can you add a test that specifies this?

**Comment by venky999** [comment]
> Can you add a test that specifies this?

I dont see any tests for azure blob storage  for other usecases, so I have not added thinking that the test might fail ..

**Review by slevenick — COMMENTED** [review]
I'm unable to test this as well. Asking someone with credentials to follow-up here

**Comment by slevenick** [comment]
Ah, it looks like we need to wait on the go client to be merged to be able to test

**Comment by venky999** [comment]
> Ah, it looks like we need to wait on the go client to be merged to be able to test

Yes I raised a PR but its closed as its a copy. looks like it needs to be done from google side

**Pull request closed without merging**
