### PR TITLE
add encryption_configuration to google_bigquery_table resource

### PR DESCRIPTION
**Pull request by MartinNowak**
- fixes terraform-providers/terraform-provider-google#2014

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by MartinNowak** [comment]
Any chance you could find a bit of time to review this @slevenick?

**Comment by slevenick** [comment]
Sorry I spaced this!

I believe this was added via https://github.com/GoogleCloudPlatform/magic-modules/pull/2784 ?

Is there something that this PR adds that is still missing?

**Comment by MartinNowak** [comment]
@slevenick Ah cool.

> Is there something that this PR adds that is still missing?

The ForceNew handling is missing in #2784 when a KMS key is added our exchanged. Let me comment this there.

**Comment by slevenick** [comment]
Why should there be a ForceNew on that field? I'm able to update the kms key referenced, so I don't think it needs to be ForceNew

**Comment by MartinNowak** [comment]
Right @slevenick, it needs to be set on the encryption configuration, not on the kms_key_name, like done in *this* PR (see below).

https://github.com/GoogleCloudPlatform/magic-modules/blob/8122abe2061c165f250b4c3fe7f71e9c1711321c/third_party/terraform/resources/resource_bigquery_table.go.erb#L315-L321

You can update a KMS key on an already encrypted table in place, but encrypting and decrypting tables require copies, hence the force new.
https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_to_kms
https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_key

**Comment by slevenick** [comment]
Ah, gotcha. Trying to remove encryption_configuration got this error: 
```Error: googleapi: Error 400: Changing from Default to Cloud KMS encryption key and back must be done via table.copy job. https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_to_kms, invalid```

I'll do a little more testing and then make a PR for this

**Comment by slevenick** [comment]
Ehhhh, it may be a bit more difficult. Seems like the API can handle adding encryption specifically, but decrypting the table requires copying it.

**Comment by slevenick** [comment]
Created https://github.com/terraform-providers/terraform-provider-google/issues/5241 to track this in the terraform repo

**Comment by MartinNowak** [comment]
> Ehhhh, it may be a bit more difficult. Seems like the API can handle adding encryption specifically, but decrypting the table requires copying it.

Seems the API simply doesn't validate this, at least it silenty accepts a key on update, but that doesn't appear to actually encrypt the table (according to the UI/CLI).

**Pull request closed without merging**
