### PR TITLE
remove google_identity_platform_project_default_config resource.

### PR DESCRIPTION
**Pull request by mraouffouad**
Remove google_identity_platform_project_default_config. The resource was deprecated in pr/8559.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
Removeing `google_identity_platform_project_default_config`.
```

### CODE REVIEW

**Comment by mraouffouad** [comment]
@ScottSuarez I'm not sure why the linter is applied to ProjectDefaultConfig.yaml, which is being deleted in this PR.

It'd be great if we can get this change into 5.0.0.

**Comment by ScottSuarez** [comment]
Hey @mraouffouad, Have you contacted our leads about this? We only accept resource removals in rare cases and only if discussed with our team prior to merge.

**Comment by mraouffouad** [comment]
> Hey @mraouffouad, Have you contacted our leads about this? We only accept resource removals in rare cases and only if discussed with our team prior to merge.

Yes, @shuyama1 and @c2thorn are aware of this change as a follow-up of pr/8559.

**Comment by c2thorn** [comment]
Discussed offline with the service team and @mraouffouad 
We will not remove this resource for now. 
Created https://github.com/GoogleCloudPlatform/magic-modules/pull/9057 to update the upgrade guide
Created https://github.com/hashicorp/terraform-provider-google/issues/15963 to track the future removal.

**Pull request closed without merging**
