### PR TITLE
revert plugin framework code

### PR DESCRIPTION
**Pull request by megan07**
reverts plugin-framework code

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
provider: fixed crash when trying to configure the provider with invalid credentials
```

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]

**Comment by rosmo** [comment]
Apparently the new plugin framework code also broke data source `google_dns_keys` (returned an empty list of object), so I believe there is more than just the crash issue at hand here.

**Comment by melinath** [comment]
@rosmo Is that issue already fixed in 4.53.1? If not, could you [open an issue](https://github.com/hashicorp/terraform-provider-google/issues) for it?

**Comment by rosmo** [comment]
It's fixed in 4.53.1. But it broken in 4.53.0.

**Comment by megan07** [comment]
Hi @rosmo, are you able to create a new issue with what you experienced in `4.53.0`? I'm making updates to that area of the code and would like to make sure your case is covered. Specifically I'd be interested in what your config looks like and what you're expecting (it returned an empty set of objects, should it have errored? or were there keys that it should have returned, etc). Thanks!

**Pull request merged**
