### PR TITLE
Remove release channel UNSPECIFIED diff suppress

### PR DESCRIPTION
**Pull request by c2thorn**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/8543

The diff suppress made setting `channel = "UNSPECIFIED"` not set a channel at all, which now causes a diff due to an API change setting a default.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
container: fixed an issue where release channel UNSPECIFIED could not be set
```

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]
LGTM, as we'll know this works when the tests pass, right?

**Comment by c2thorn** [comment]
@rileykarson ATM there isn't a test that captures the failing scenario. 

https://github.com/GoogleCloudPlatform/magic-modules/blob/5b6b9cb95dd4d940a6505092f2c6e31be718ad2f/mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb#L444 is close but actually passes right now because UNSPECIFIED is set during update.

https://github.com/GoogleCloudPlatform/magic-modules/blob/5d930d4daab86ed69c600e746f383a59b33fce45/mmv1/third_party/terraform/tests/resource_container_node_pool_test.go.erb#L1180 is failing because the API changed the default release channel, which my PR doesn't override (and we shouldn't do right?). If we explicitly set the channel to UNSPECIFIED here, that will both fix the test and also capture the failing scenario going forward.

**Comment by rileykarson** [comment]
Good point about `TestAccContainerNodePool_withManagement`! I was going to suggest adding the UNSPECIFIED channel, which it looks like you've already done. Once that's passing I'm :+1:

**Comment by c2thorn** [comment]
Test has passed: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/175190?buildTab=tests

Going to merge now so the fix goes into next release.

**Pull request merged**
