### PR TITLE
Move MMV1 and handwritten acc tests to service packages

### PR DESCRIPTION
**Pull request by zli82016**
1. Generate Mmv1 tests to the specific service packages
2. Move handwritten tests to the specific service packages
3. Copy test-fixtures to the specific service packages
4. Move function `createZIPArchiveForCloudFunctionSource` to the `acctest` package
5. Move function `testBucketName` to the `acctest` package
6. Move function `ServiceAccountCanonicalEmail` to the `envvar` package
7. Move function `GetResourceAttributes` to the `tpgresource` package

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by slevenick** [comment]
Looks like there's conflicts

**Comment by zli82016** [comment]
> Looks like there's conflicts

Thanks. I will resolve the conflicts.

**Review by slevenick — APPROVED** [review]
I'm assuming this is essentially a no-op, just moving around packages and stuff. No tests are failing so that's good!

**Comment by zli82016** [comment]
Rebased the main branch and resolved the conflicts.

This PR is planed to be merged after the release cut on Thursday.

**Pull request closed without merging**
