### PR TITLE
Add MTU to interconnect

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8227

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `mtu` field to `google_compute_interconnect_attachment`
```

### CODE REVIEW

**Comment by upodroid** [comment]
This has no test but the MTU field is updatable. I created a partner interconnect with 1500 and set it to 1440 by patching it using the API Explorer :(

**Review by melinath — COMMENTED** [review]
It sounds like this field should be marked as `default_from_api: true` - what do you think?

it looks like there are not currently _any_ tests for this resource. Do you happen to know if there's a particular reason this resource is hard to write tests for?

**Comment by upodroid** [comment]
I'm not sure.

https://github.com/hashicorp/terraform-provider-google/issues/7972 @rileykarson may know the full details.

**Comment by rileykarson** [comment]
It was previously impossible for us to provision one, but it should actually work now since our CI project has been added to a list of projects that provision fake interconnects.

**Review by melinath — CHANGES_REQUESTED** [review]
I'll open a new issue for us to add MTU interconnect tests. However, this seems like it should use default_from_api - @upodroid please let me know if that seems incorrect.

**Comment by upodroid** [comment]
Ok, i'll push a change

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
