### PR TITLE
fix import for bigquery-data-transfer resource

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/12011

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
bigquery: fixed import for `google_bigquery_data_transfer_config`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
@shuyama1 , any idea why the logs for `TestAccBigqueryDataTransferConfig` failed to upload?

**Comment by shuyama1** [comment]
I think it's the test set that contains tests running serially. Click the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6227/artifacts/8867e193-31fe-40ad-8276-472ee62bfa38/recording), you should be able to see the test logs I think.

**Comment by kanata2** [comment]
@ScottSuarez 
Hi, thanks for your great work. What is the current status of this PR?

**Comment by lodotek** [comment]
Bump. Can we please get this merged in?

Thank you...

**Comment by ScottSuarez** [comment]
There are outstanding issues with this change that need to be looked. WIth my queue of work and priorities I haven't had time to into this.

**Pull request closed without merging**
