### PR TITLE
Update google.golang.org/api to v.105.0

### PR DESCRIPTION
**Pull request by rlapin-pl**
Update dependencies.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
Bumping go api version
```

### CODE REVIEW

**Comment by slevenick** [comment]
Hey! Is there a particular library you want to bump here? It's typically easier to scope down changes to a single library rather than bump everything at once, as there may be hidden changes in there that we want to catch

**Comment by rlapin-pl** [comment]
> Hey! Is there a particular library you want to bump here? It's typically easier to scope down changes to a single library rather than bump everything at once, as there may be hidden changes in there that we want to catch

Hey. Yes I want to bump google.golang.org/api version to v0.105.0.

**Comment by slevenick** [comment]
> > Hey! Is there a particular library you want to bump here? It's typically easier to scope down changes to a single library rather than bump everything at once, as there may be hidden changes in there that we want to catch
> 
> Hey. Yes I want to bump google.golang.org/api version to v0.105.0.

Can you scope this PR down to only change that version and any necessary changes to accommodate that?

**Comment by rlapin-pl** [comment]
> > > Hey! Is there a particular library you want to bump here? It's typically easier to scope down changes to a single library rather than bump everything at once, as there may be hidden changes in there that we want to catch
> > 
> > 
> > Hey. Yes I want to bump google.golang.org/api version to v0.105.0.
> 
> Can you scope this PR down to only change that version and any necessary changes to accommodate that?

Done.

**Comment by slevenick** [comment]
Looks like this was done via https://github.com/GoogleCloudPlatform/magic-modules/commit/b441b7cf77ee152439eab48192da8cabf345e211

**Pull request closed without merging**
