### PR TITLE
Added support for redis instance data source

### PR DESCRIPTION
**Pull request by MounirKaroudEV**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_redis_instance`
```

### CODE REVIEW

**Comment by slevenick** [comment]
Awesome, looks like tests pass. Can you sign the CLA so I can merge this?

**Comment by MounirKaroudEV** [comment]
@googlebot I signed it!

**Comment by MounirKaroudEV** [comment]
`@googlebot I signed it!`

**Comment by MounirKaroudEV** [comment]
@googlebot I signed it!

**Comment by MounirKaroudEV** [comment]
I just squashed the commits in one and changed my email to the one which is supposed to have the cla signed for

**Comment by MounirKaroudEV** [comment]
@googlebot I signed it!

**Comment by slevenick** [comment]
Don't worry about the CLA, as all of the changes are within the `third_party` directory which is under a different license.

Can I have you add a couple of the other fields to the documentation? All of the fields that are on the `google_redis_instance` resource should be available as attributes on the datasource. You can find these here: https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/redis_instance.html.markdown#argument-reference

**Pull request merged**
