### PR TITLE
Rewrite example_config_body with Go

### PR DESCRIPTION
**Pull request by zli82016**
Rewrite ExampleConfigBody with Go

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by zli82016** [comment]
The diffs are only [new lines ](https://github.com/hashicorp/terraform-provider-google-beta/compare/main...ExampleConfigBody-diff), which are added [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/api/resource/examples.go#L236).

To remove the diffs, we can have a new function similar to `ExecuteTemplate`, without adding new line at end. Any thoughts?

**Comment by c2thorn** [comment]
> To remove the diffs, we can have a new function similar to `ExecuteTemplate`, without adding new line at end. Any thoughts?

Ah, we probably need to have a flag to the function to control when the newline is added or not.

**Comment by c2thorn** [comment]
@zli82016 would you mind adding that flag to reduce diffs?

**Comment by zli82016** [comment]
> @zli82016 would you mind adding that flag to reduce diffs?

I will do that

**Comment by zli82016** [comment]
The flag is added to the remove diffs.

**Review by c2thorn — APPROVED** [review]
thank you for adding the flag!

**Pull request merged**
