### PR TITLE
Prepared storage_upload_object snippet for inclusion on C.G.C.

### PR DESCRIPTION
**Pull request by cbonnie**
Prepared a storage_upload_object code snippet for inclusion on C.G.C.

Intending to use this snippet on the following page:
https://cloud.google.com/storage/docs/uploading-objects

```release-note:none
```

If this PR is for Terraform, I acknowledge that I have:

- [x ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like the .erb file needs to be renamed to storage_upload_file_to_bucket.tf.erb - the downstream build is currently failing with:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /mm-tf-cloud-docs-beta-head/mmv1/templates/terraform/examples/storage_upload_file_to_bucket.tf.erb
```

**Review by melinath — CHANGES_REQUESTED** [review]
The test is currently failing with:

```
Error: open ./two-dogs.jpg: no such file or directory
```

I'm not sure how other similar tests handle this offhand.

**Comment by cbonnie** [comment]
> The test is currently failing with:
> 
> ```
> Error: open ./two-dogs.jpg: no such file or directory
> ```
> 
> I'm not sure how other similar tests handle this offhand.

I think the test is failing because it's trying to upload an image called ./two-dogs.jpg but doesn't have one. Is there a way to disable the test from evaluating the resource? This is only meant as documentation and it's up to users to provide their own jpg file.

> 
> Additionally, the GA provider tests are failing with a lint error:
> 
> ```
> google/resource_cgc_snippet_generated_test.go:419:14: undeclared name: `testAccProvidersOiCS` (typecheck)
> 		Providers: testAccProvidersOiCS,
> ```
> 
> (I'm not sure if that's related to this PR.)

**Comment by cbonnie** [comment]
@betsy-lichtenberg Do you have insight into what this error means or how to fix it?

> Additionally, the GA provider tests are failing with a lint error:
> 
> ```
> google/resource_cgc_snippet_generated_test.go:419:14: undeclared name: `testAccProvidersOiCS` (typecheck)
> 		Providers: testAccProvidersOiCS,
> ```
> 
> (I'm not sure if that's related to this PR.)

**Comment by betsy-lichtenberg** [comment]
Can you change the source to:

gs://gcp-external-http-lb-with-bucket/two-dogs.jpg
gs://gcp-external-http-lb-with-bucket/three-cats.jpg

**Comment by cbonnie** [comment]
@c2thorn Hi! Would you mind taking a look again? I'm not sure what's causing the check failures.

**Comment by c2thorn** [comment]
@cbonnie We have overhauled our CI, do you have access to the logs for your test `TestAccCGCSnippet_storageUploadObjectExample` ? It should be given to Googlers.

Either way, it is failing with the error
```
Error: open gs://gcp-external-http-lb-with-bucket/two-dogs.jpg: no such file or directory
```

**Comment by cbonnie** [comment]
@c2thorn I don't have access to those logs. And to be honest, I'm new to Terraform and don't know where to begin debugging this. Do you have any ideas? It looks like the test is trying to load two-dogs.jpg, but that's just a placeholder example for what the user should load. Is there a way to make the test skip this?

**Comment by cbonnie** [comment]
@betsy-lichtenberg Do you know how I can make the test skip trying to load two-dogs.jpg?

**Comment by betsy-lichtenberg** [comment]
> @betsy-lichtenberg Do you know how I can make the test skip trying to load two-dogs.jpg?

> @betsy-lichtenberg Do you know how I can make the test skip trying to load two-dogs.jpg?

It looks like the "source" argument is optional, but if you exclude it you must use "content" instead. You can comment  out the "source" line with a comment saying something like



And the "content" argument with a string. I haven't tested this, but my guess is it would look like this:

```
# Uncomment and add valid path to an object.
# source = "path/to/your/object"

content = "this is my object"

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object

**Review by c2thorn — APPROVED** [review]
Failing test is unrelated.

**Pull request merged**
