### PR TITLE
Add `default_from_apis: true` to `service.spec.template.metadata.labels` in `cloudrun` resource

### PR DESCRIPTION
**Pull request by yanweiguo**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/15081.

Add `default_from_apis: true` to `service.spec.template.metadata.labels` in `cloudrun` resource. This is similar to `service.spec.template.metadata.annoations`, `service.metadata.labels`  and `service.metadata.annoations`. Cloud Run API could set some default system labels/annoations.  

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
cloudrun: fixed the bug where default system labels set in `service.spec.template.metadata.labels` were treated as a diff.
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
I don't believe this is the right fix. This field essentially becomes unmanageable through terraform. If we set these properties there will be a diff between the users set values and the apis set defaults.

ie, if I set
```
labels {
  terraform="true",
  resource = "gold",
  }
  ```
  
  The api will union these on return with its server generated values
  ```
  labels: { "terraform": "true", "resource": "gold", "server-side": "12.32.42"}
  ```
  
  Causing a diff at apply/plan time for sequential applies.
  
  We need to ignore these server values through a diff suppress, similar to
  https://github.com/GoogleCloudPlatform/magic-modules/blob/0e4db60289b170c0042727d1205476fd524d6444/mmv1/products/cloudrun/DomainMapping.yaml#L160-L168

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
I don't believe this is the right fix. This field essentially becomes unmanageable through terraform. If we set these properties there will be a diff between the users set values and the apis set defaults.

ie, if I set
```
labels {
  terraform="true",
  resource = "gold",
  }
  ```
  
  The api will union these on return with its server generated values
  ```
  labels: { "terraform": "true", "resource": "gold", "server-side": "12.32.42"}
  ```
  
  Causing a diff at apply/plan time for sequential applies.
  
  We need to ignore these server values through a diff suppress, similar to
  https://github.com/GoogleCloudPlatform/magic-modules/blob/0e4db60289b170c0042727d1205476fd524d6444/mmv1/products/cloudrun/DomainMapping.yaml#L160-L168

**Comment by yanweiguo** [comment]
> I don't believe this is the right fix. This field essentially becomes unmanageable through terraform. If we set these properties there will be a diff between the users set values and the apis set defaults.
> 
> ie, if I set
> 
> ```
> labels {
>   terraform="true",
>   resource = "gold",
>   }
> ```
> 
> The api will union these on return with its server generated values
> 
> ```
> labels: { "terraform": "true", "resource": "gold", "server-side": "12.32.42"}
> ```
> 
> Causing a diff at apply/plan time for sequential applies.
> 
> We need to ignore these server values through a diff suppress, similar to
> 
> https://github.com/GoogleCloudPlatform/magic-modules/blob/0e4db60289b170c0042727d1205476fd524d6444/mmv1/products/cloudrun/DomainMapping.yaml#L160-L168

Thanks for the suggestion. Will do.

**Comment by yanweiguo** [comment]
Added a suppress func.

BTW, I can't test it locally due to the following error from downstream repo:

```
google/transport/provider_handwritten_endpoint.go:77:22: undefined: ServiceUsageBasePathKey
google/transport/provider_handwritten_endpoint.go:97:22: undefined: PrivatecaBasePathKey
google/transport/config.go:563:62: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
google/transport/config.go:570:29: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
google/transport/config.go:590:47: c.DNSBasePath undefined (type *Config has no field or method DNSBasePath)
google/transport/config.go:605:47: c.KMSBasePath undefined (type *Config has no field or method KMSBasePath)
google/transport/config.go:623:51: c.LoggingBasePath undefined (type *Config has no field or method LoggingBasePath)
google/transport/config.go:637:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
google/transport/config.go:652:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
google/transport/config.go:675:69: c.SQLBasePath undefined (type *Config has no field or method SQLBasePath)
google/transport/config.go:675:69: too many errors
FAIL	github.com/hashicorp/terraform-provider-google/google [build failed]
FAIL
make: *** [GNUmakefile:15: testacc] Error 1
```

I have updated the downstream repo and magic-modules to the latest.

**Comment by ScottSuarez** [comment]
> Added a suppress func.
> 
> BTW, I can't test it locally due to the following error from downstream repo:
> 
> ```
> google/transport/provider_handwritten_endpoint.go:77:22: undefined: ServiceUsageBasePathKey
> google/transport/provider_handwritten_endpoint.go:97:22: undefined: PrivatecaBasePathKey
> google/transport/config.go:563:62: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
> google/transport/config.go:570:29: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
> google/transport/config.go:590:47: c.DNSBasePath undefined (type *Config has no field or method DNSBasePath)
> google/transport/config.go:605:47: c.KMSBasePath undefined (type *Config has no field or method KMSBasePath)
> google/transport/config.go:623:51: c.LoggingBasePath undefined (type *Config has no field or method LoggingBasePath)
> google/transport/config.go:637:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
> google/transport/config.go:652:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
> google/transport/config.go:675:69: c.SQLBasePath undefined (type *Config has no field or method SQLBasePath)
> google/transport/config.go:675:69: too many errors
> FAIL	github.com/hashicorp/terraform-provider-google/google [build failed]
> FAIL
> make: *** [GNUmakefile:15: testacc] Error 1
> ```
> 
> I have updated the downstream repo and magic-modules to the latest.

hmm, usually this happens if you don't run
```bash
git clean -fdx . 
```
on tpg/b before generating. We can work on making this experience smoothing for you!

**Comment by yanweiguo** [comment]
Tried running `git clean -fdx . ` in magic-modules repo and `terraform-provider-google` repo. Got the same error. Did I miss something?

**Comment by ScottSuarez** [comment]
In each repository, try to `git pull upstream main`. 

If you still run into issues feel free to ping me!!

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
> Added a suppress func.
> 
> BTW, I can't test it locally due to the following error from downstream repo:
> 
> ```
> google/transport/provider_handwritten_endpoint.go:77:22: undefined: ServiceUsageBasePathKey
> google/transport/provider_handwritten_endpoint.go:97:22: undefined: PrivatecaBasePathKey
> google/transport/config.go:563:62: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
> google/transport/config.go:570:29: c.ComputeBasePath undefined (type *Config has no field or method ComputeBasePath)
> google/transport/config.go:590:47: c.DNSBasePath undefined (type *Config has no field or method DNSBasePath)
> google/transport/config.go:605:47: c.KMSBasePath undefined (type *Config has no field or method KMSBasePath)
> google/transport/config.go:623:51: c.LoggingBasePath undefined (type *Config has no field or method LoggingBasePath)
> google/transport/config.go:637:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
> google/transport/config.go:652:29: c.StorageBasePath undefined (type *Config has no field or method StorageBasePath)
> google/transport/config.go:675:69: c.SQLBasePath undefined (type *Config has no field or method SQLBasePath)
> google/transport/config.go:675:69: too many errors
> FAIL	github.com/hashicorp/terraform-provider-google/google [build failed]
> FAIL
> make: *** [GNUmakefile:15: testacc] Error 1
> ```
> 
> I have updated the downstream repo and magic-modules to the latest.

I have a PR to fix this build issue
https://github.com/GoogleCloudPlatform/magic-modules/pull/8471

Sorry about that !!! Looks like it only happened when building a single product.

**Pull request merged**
