### PR TITLE
Upgrade Go 1.19

### PR DESCRIPTION
**Pull request by zli82016**
Upgrade Go 1.19

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by slevenick — COMMENTED** [review]
I think we're waiting on any CI changes until ~tomorrow, so I can review then

**Comment by zli82016** [comment]
> I think we're waiting on any CI changes until ~tomorrow, so I can review then

Yeah, sounds good.

**Review by slevenick — APPROVED** [review]

**Comment by rakeshmulugu** [comment]
- I recently opened an issue with the `terraform-google-provider` repository to upgrade the Go language version bundled with Terraform providers, as the older version was causing vulnerabilities. The issue has since been closed after the reported changes were made. 

- However, after rebuilding the images with the latest versions of Terraform (1.4.5) and Google providers (4.62.1), I have noticed that the vulnerabilities related to Go 1.18 still persist. It appears that the providers are still using the older Go version.

- Upon further investigation, I found that the `go-version` file in the repository still contains the Go version 1.18.1. This discrepancy might be the cause of the issue. I request the reopening of the issue to address this concern. 

- If you require any further details or clarification, please let me know, and I'll be happy to provide the necessary information. It is crucial that we resolve this issue to ensure the security and stability of our infrastructure.

MicrosoftTeams-image (3)

MicrosoftTeams-image (4)

**Pull request merged**
