### PR TITLE
Move iam member resources into .ci/infra

### PR DESCRIPTION
**Pull request by trodge**
This test is failing in VCR replaying after recording because of the iam member resources. Setting the permission on project level should be sufficient.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by zli82016 — CHANGES_REQUESTED** [review]
The test `TestAccComputeInstance_confidentialHyperDiskBootDisk` failed with the error 
```
Error: Reference to undeclared resource
        
          on terraform_plugin_test.tf line 32, in resource "google_compute_instance" "foobar":
          32:   depends_on = [google_kms_crypto_key_iam_member.crypto_key]
        
```

**Comment by trodge** [comment]
> The test `TestAccComputeInstance_confidentialHyperDiskBootDisk` failed with the error
> 
> ```
> Error: Reference to undeclared resource
>         
>           on terraform_plugin_test.tf line 32, in resource "google_compute_instance" "foobar":
>           32:   depends_on = [google_kms_crypto_key_iam_member.crypto_key]
>         
> ```

Whoops, I forgot to remove that. Should be fixed now.

We may also need to apply the terraform config. I'm not sure where to find the state file for it, but @roaks3 will know when he's back in-office.

**Comment by zli82016** [comment]
> > The test `TestAccComputeInstance_confidentialHyperDiskBootDisk` failed with the error
> > ```
> > Error: Reference to undeclared resource
> >         
> >           on terraform_plugin_test.tf line 32, in resource "google_compute_instance" "foobar":
> >           32:   depends_on = [google_kms_crypto_key_iam_member.crypto_key]
> >         
> > ```
> 
> Whoops, I forgot to remove that. Should be fixed now.
> 
> We may also need to apply the terraform config. I'm not sure where to find the state file for it, but @roaks3 will know when he's back in-office.

Sure. I don't know neither.

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks for fixing the test.

**Pull request merged**
