### PR TITLE
Add master authorized networks for CC to GA

### PR DESCRIPTION
**Pull request by kubasieron**
Add Cloud Composer master authorized networks support to GA.
Also go.provider version is increased to support the change.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
composer: promoted `config.master_authorized_networks_config` in `google_composer_environment` resource to GA.
```

### CODE REVIEW

**Comment by kubasieron** [comment]
Probably we need to wait until next Cloud Composer release to have full support for master authorized networks in Composer backend. So far DO NOT MERGE

**Comment by shuyama1** [comment]
@kubasieron Does it mean that we can not run the tests in GA since we are still waiting for the full support in Composer backend?

**Comment by kubasieron** [comment]
@shuyama1 Composer release is ready, this PR is unblocked

**Comment by shuyama1** [comment]
@kubasieron Thanks for letting me know!
Running GA tests for composer environment now. https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/296353

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
