### PR TITLE
reduce name prefix in compute resources

### PR DESCRIPTION
**Pull request by c2thorn**
fixes https://github.com/hashicorp/terraform-provider-google/issues/15374

conditionally use a shortened UUID prefix when provided a `name_prefix` of over 37 characters

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: changed the behavior of `name_prefix` in multiple Compute resources to allow for a longer max length of 54 characters. See the upgrade guide and resource documentation for more details.
```

### CODE REVIEW

**Comment by rileykarson** [comment]
@zli82016 could you follow up on the failed project deletions when you get a chance? (we may want to check the nightlies if they exist since the change was merged)

**Comment by zli82016** [comment]
> @zli82016 could you follow up on the failed project deletions when you get a chance? (we may want to check the nightlies if they exist since #11255 was merged)

Sure, I will check it.

**Comment by zli82016** [comment]
The tests `TestAccApikeysKey_*` also failed in the [GA nightly 6.0 major release testing](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_FEATUREBRANCHMAJORRELEASE6_0_0_GA_NIGHTLYTESTS_GOOGLE_PACKAGE_APIKEYS/218928?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildTestsSection=true&expandBuildDeploymentsSection=false&expandBuildChangesSection=true). They are DCL generated tests. I am going to fix them and others if any.

**Comment by zli82016** [comment]
The tests `TestAccApikeysKey_*` are going to be fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/11462

**Pull request merged**
