### PR TITLE
Fix incorrect reference to nonexistent resource

### PR DESCRIPTION
**Pull request by andrefilipemm**
The `time_resource` resource type doesn't exist in the time provider, the correct resource type should be `time_sleep` 

You can add more release note blocks if you want more than one CHANGELOG
entry for this PR.
-->
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Review by hao-nan-li — COMMENTED** [review]
Thanks for fixing this out. Could you sign the CLA as mentioned in the comments?

**Comment by andrefilipemm** [comment]
> Thanks for fixing this out. Could you sign the CLA as mentioned in the comments?

Done :)

**Review by hao-nan-li — COMMENTED** [review]
Could you do a rebase on main?

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
