### PR TITLE
Added new resource "Project Cloud Armor Tier"

### PR DESCRIPTION
**Pull request by matheusaleixo-cit**
Adds a new resource "google_compute_project_cloud_armor_tier" allowing the management Cloud Armor Tier configuration in a similar function as the "google_compute_project_default_network_tier" resource

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/17658

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_compute_project_cloud_armor_tier`
```

### CODE REVIEW

**Review by c2thorn — CHANGES_REQUESTED** [review]
Thank you for contributing this! I'm running our CI now. In the meantime, would you mind adding an example block? Instructions are here: https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-a-create-test

You've already added the update test which is usually more work, but that does not appear in the documentation like an example would. Thanks!

**Comment by matheusaleixo-cit** [comment]
> Tests passed during RECORDING mode: `TestAccComputeProjectCloudArmorTier_withProjectSet`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/recording/TestAccComputeProjectCloudArmorTier_withProjectSet.log)]
> 
> No issues found for passed tests after REPLAYING rerun.
> 
> Tests failed during RECORDING mode: `TestAccComputeProjectCloudArmorTier_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/build-log/recording_build/TestAccComputeProjectCloudArmorTier_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/recording/TestAccComputeProjectCloudArmorTier_basic.log)] `TestAccComputeProjectCloudArmorTier_modify`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/build-log/recording_build/TestAccComputeProjectCloudArmorTier_modify_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/recording/TestAccComputeProjectCloudArmorTier_modify.log)]
> 
> Please fix these to complete your PR. View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10698/artifacts/8c27f080-c096-4a11-8b3c-1dd3dac62ac1/recording) for each test

Hi @c2thorn! Can you show me the logs for the two tests that are failing? I can't access them and these tests are passing for me when I run them locally.

**Comment by c2thorn** [comment]
> Hi @c2thorn! Can you show me the logs for the two tests that are failing? I can't access them and these tests are passing for me when I run them locally.

```
        Error: Error waiting to create ProjectCloudArmorTier: Invalid value for field 'cloudArmorTier': 'CA_STANDARD'. Setting the managed protection tier for projects enrolled in Cloud Armor Enterprise Annual Subscription is currently not supported. Please use the cloud console instead.
```
It seems this is an issue with our specific test project. Since the update test works, I'm fine with skipping the actual test generation for these examples. You can add `skip_test: true` to these like in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/accessapproval/OrganizationSettings.yaml#L29

**Comment by c2thorn** [comment]
> Hi @c2thorn! Can you show me the logs for the two tests that are failing? I can't access them and these tests are passing for me when I run them locally.

```
        Error: Error waiting to create ProjectCloudArmorTier: Invalid value for field 'cloudArmorTier': 'CA_STANDARD'. Setting the managed protection tier for projects enrolled in Cloud Armor Enterprise Annual Subscription is currently not supported. Please use the cloud console instead.
```

Our test project probably needs to be enrolled for some other features. Could we just avoid testing `CA_STANDARD`?

**Comment by matheusaleixo-cit** [comment]
> > Hi @c2thorn! Can you show me the logs for the two tests that are failing? I can't access them and these tests are passing for me when I run them locally.
> 
> ```
>         Error: Error waiting to create ProjectCloudArmorTier: Invalid value for field 'cloudArmorTier': 'CA_STANDARD'. Setting the managed protection tier for projects enrolled in Cloud Armor Enterprise Annual Subscription is currently not supported. Please use the cloud console instead.
> ```
> 
> Our test project probably needs to be enrolled for some other features. Could we just avoid testing `CA_STANDARD`?

I changed the examples and the basic test to use the CA_ENTERPRISE_PAYGO value, but I think the subscription used in the test project wont allow setting this cloudArmorTier configuration at all. If the tests fail again I'l change this back and set the tests to be skipped since that is the only config this resource is handling.

**Comment by c2thorn** [comment]
> I changed the examples and the basic test to use the CA_ENTERPRISE_PAYGO value, but I think the subscription used in the test project wont allow setting this cloudArmorTier configuration at all. If the tests fail again I'l change this back and set the tests to be skipped since the cloud armor tier is the only config this resource is handling.

This looks like the way to go, we got another similar error:
```
Error waiting to create ProjectCloudArmorTier: Invalid value for field 'cloudArmorTier': 'CA_ENTERPRISE_PAYGO'. Setting the managed protection tier for projects enrolled in Cloud Armor Enterprise Annual Subscription is currently not supported. Please use the cloud console instead.
```

If the previous value was a better "example" value, feel free to change it back and then also add `skip_test` to the skippable examples. Appreciate it.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
