### PR TITLE
Removed the `automatic` field from the `google_secret_manager_secret` resource

### PR DESCRIPTION
**Pull request by abheda-crest**
Removed the `automatic` field from the `google_secret_manager_secret` resource.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
secretmanager: removed `automatic` field in `google_secret_manager_secret` resource
```

### CODE REVIEW

**Comment by abheda-crest** [comment]
This PR depends on the [existing PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/8838) to be merged.

**Comment by c2thorn** [comment]
Hi @abheda-crest,
This looks good on initial review. I understand that this also includes changes from https://github.com/GoogleCloudPlatform/magic-modules/pull/8838 that were just recently merged. I would like to wait for the feature branch to sync with `main` which should happen in the first half of this week before merging.

In the meantime, is there already an upgrade guide entry explaining the removal of `automatic` in favor of `auto`? If not, please refer to these steps:

https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#add-upgrade-guide-entries-to-the-main-branch-of-magic-modules

**Comment by abheda-crest** [comment]
> Hi @abheda-crest, This looks good on initial review. I understand that this also includes changes from #8838 that were just recently merged. I would like to wait for the feature branch to sync with `main` which should happen in the first half of this week before merging.

Yeah, I agree with you.

> In the meantime, is there already an upgrade guide entry explaining the removal of `automatic` in favor of `auto`? If not, please refer to these steps:
> 
> https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#add-upgrade-guide-entries-to-the-main-branch-of-magic-modules

I've updated the [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/8680) for the upgrade guide entry for the removal of the `automatic` field.

**Comment by c2thorn** [comment]
Thanks @abheda-crest. Soft LGTM for now. I will perform the branch sync tomorrow, then check this PR one more time. If it looks good, I will approve then merge both PR's.

**Comment by abheda-crest** [comment]
> Thanks @abheda-crest. Soft LGTM for now. I will perform the branch sync tomorrow, then check this PR one more time. If it looks good, I will approve then merge both PR's.

@c2thorn I've pulled the changes from `FEATURE-BRANCH-major-release-5.0.0` and resolved the merge conflicts. This PR is now ready.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
