### PR TITLE
Adding ipv6 support for bgp router peer, router interface and router.

### PR DESCRIPTION
**Pull request by Gorlami96**
Adding ipv6 support for bgp router peer, router interface and router. Related to b/309454013

**Release Note Template for Downstream PRs*

```release-note:enhancement 
compute: Adding support for ipv6 enhancements in google_compute_router, google_compute_router_interface and google_compute_router_peer
```

### CODE REVIEW

**Comment by Gorlami96** [comment]
hi @ScottSuarez. Not sure where the bot is dete3cting breaking change as the resource is untouched

**Comment by melinath** [comment]
apologies for the noise - I think this was caused by the trouble building the diff-processor. It should be resolved if you fix the compilation errors for the `google` provider - for example: https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/8368071024/job/22911569217

I've added an explicit service label, which should prevent the label noise. However, the breaking changes may continue to be detected until the compilation errors are resolved.

I'll look into fixing the issue separately; in the meantime I'd recommend fixing the compilation errors.

**Comment by ScottSuarez** [comment]
Hey @Gorlami96, sorry for the delay here!

Could you rebase this CL when you get a chance.

**Comment by ScottSuarez** [comment]
Looks like we have some failing tests.

```
  | Error: Error creating RouterBgpPeer: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[0].peerIpAddress': '10.0.0.3'. The IP version of Peer IP must not be disabled., invalid
  | 
  |   with google_compute_router_peer.peer,
  |   on terraform_plugin_test.tf line 97, in resource "google_compute_router_peer" "peer":
  |   97: resource "google_compute_router_peer" "peer" {
  | 
   test_terraform_path=/bin/terraform
2024-03-22T01:27:57.723Z [DEBUG] sdk.helper_resource: Stopping providers: test_terraform_path=/bin/terraform test_working_directory=/tmp/plugintest1545503077 test_name=TestAccComputeRouterBgpPeer_routerPeerRouterAppliance test_step_number=1
2024-03-22T01:27:57.724Z [ERROR] sdk.helper_resource: Unexpected error: test_name=TestAccComputeRouterBgpPeer_routerPeerRouterAppliance test_step_number=1 test_terraform_path=/bin/terraform
  error=
  | Error running apply: exit status 1
  | 
  | Error: Error creating RouterBgpPeer: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[0].peerIpAddress': '10.0.0.3'. The IP version of Peer IP must not be disabled., invalid
  | 
  |   with google_compute_router_peer.peer,
  |   on terraform_plugin_test.tf line 97, in resource "google_compute_router_peer" "peer":
  |   97: resource "google_compute_router_peer" "peer" {

```


Let me know if you need help investigating. If you `cmd+F` in the logs for `unexpected error` it will bring you to the error the application threw.

**Comment by Gorlami96** [comment]
Ack. Fixing tests on this.

**Comment by ScottSuarez** [comment]
Looks like there a is a merge conflict

mmv1/third_party/terraform/services/compute/resource_compute_router_bgp_peer_test.go

**Pull request closed without merging**
