### PR TITLE
resource_storage_bucket_object: migrated to cloud.google.com/go/storage

### PR DESCRIPTION
**Pull request by jaceq**
This resolves: https://github.com/hashicorp/terraform-provider-google/issues/9507
And is prerequisite for: https://github.com/hashicorp/terraform-provider-google/issues/8133

Migrated resource_storage_bucket_object to cloud.google.com/go/storage

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
storage: migrated `resource_storage_bucket_object` to cloud.google.com/go/storage
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
```
go generate  ./...
go: github.com/hashicorp/terraform-provider-google/google: package cloud.google.com/go/storage imported from implicitly required module; to add missing requirements, run:
	go get cloud.google.com/go/storage@v1.10.0
```

looks like this dependency needs to be added downstream to tpg and tpgb before this can go through

**Comment by ScottSuarez** [comment]
https://github.com/hashicorp/terraform-provider-google
https://github.com/hashicorp/terraform-provider-google-beta

**Comment by jaceq** [comment]
@ScottSuarez Anything for me to do here or is that something you can handle?

**Comment by ScottSuarez** [comment]
I'll take care of it, don't worry. Let me throw something on my calendar

**Comment by ScottSuarez** [comment]
Hi I haven't forgotten about this... thanks for your patience. In discussing this with my team unfortunately we don't use these higher level clients anywhere else. We're very used to working with the generated json clients and unless I am missing something this new library can't support anything the one we use doesn't.

https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L1712

Customer supplied encryption should be supported on the old client

**Comment by jaceq** [comment]
Hi @ScottSuarez 
I do not fully follow, in the package itself (and it's documentation) it says it's deprecated and to use the one I tried here:
https://github.com/googleapis/google-api-go-client/blob/ce146d9d069f4ccf74532ee4793995469f85ce68/storage/v1/storage-gen.go#L9

So... is it deprecated or not? and if it is what sense does it make to stay with it?

Anyway I admit that I missed somehow that old package also supports customer supplied encryption -> I will look into extending this.

**Comment by ScottSuarez** [comment]
Hey @jaceq,

I totally get where you are coming from and I know this can be confusing! The libraries we use are auto generated from the rest apis. While this may be deprecated in the sense that they have a higher level library available the library is still consistently getting generated. Switching to this new library could incur some behavior that could deviate from existing behavior. So it's a risk we don't really want to take if we can avoid it! If there ever is behavior that is not supported I agree it might be worth looking into migrating! 

I hope that makes sense!

**Pull request closed without merging**
