### PR TITLE
Chore: Update Google API to v0.188.0

### PR DESCRIPTION
**Pull request by spencer-p**
This PR updates the Google Go API dependency to the min version needed for Ray on GKE (#11145).

Produced with:

    go get -u google.golang.org/api/
    go mod tidy

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
none
```

### CODE REVIEW

**Review by trodge — APPROVED** [review]

**Comment by shuyama1** [comment]
@trodge Mind if I pass the review to you given you've already taken a look? Feel free to merge the PR if you think it's ready. Thanks!

**Comment by melinath** [comment]
@trodge @shuyama1 it looks like this has a bunch of failures - just want to confirm that they're not related to this PR?

**Comment by shuyama1** [comment]
> @trodge @shuyama1 it looks like this has a bunch of failures - just want to confirm that they're not related to this PR?

I haven't looked closely into the test failures in this PR, but it does seem that these tests have also been failed in VCR nightly for a while, at least since last Friday.

[VCR nightly run from last Friday](https://pantheon.corp.google.com/cloud-build/builds;region=global/4818fc0d-d480-4cc8-b6b3-11dacf6f7e57?e=-13802955&inv=1&invt=AbXjBg&project=graphite-docker-images)

**Comment by spencer-p** [comment]
@melinath This PR has the same set of failures that #11194 has, and that change is minimal. 

Looking through other PRs (merged and open) there's quite a few that are affected by these failures and are seemingly unrelated.

**Comment by melinath** [comment]
Thanks for confirming!

**Pull request merged**
