### PR TITLE
Composer GA update

### PR DESCRIPTION
**Pull request by kubasieron**
Move several fields to GA. Those fields are already supported by Cloud Composer API. Fields list:
* web_server_network_access_control,
* database_config,
* web_server_config,
* encryption_config.

It is just a preview of change, it should work on beta envs, but won't on GA envs until composer v2 fields are added to go API: https://pkg.go.dev/google.golang.org/api@v0.60.0/composer/v1

fixes hashicorp/terraform-provider-google/issues/10643

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloud_composer: Added GA support for following fields:  `web_server_network_access_control`, `database_config`, `web_server_config`, `encryption_config`.
```

### CODE REVIEW

**Comment by kubasieron** [comment]
Any updates/problems with that PR? In my opinion it should be straightforward

**Comment by ScottSuarez** [comment]
Can you update your note to follow the [Release Notes Guidelines](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md)?

**Review by ScottSuarez — APPROVED** [review]
looks good to me

**Pull request merged**
