### PR TITLE
add serverTLSpolicy to google_compute_region_target_https_proxy

### PR DESCRIPTION
**Pull request by maxi-cit**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/14980

It adds support for Server TLS policies to the Regional HTTPS proxy resource

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `server_tls_policy` field to `google_compute_region_target_https_proxy` resource
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Hi, I notice this changes is still in draft. Could you add a test for it and let me know when you would like a review?

**Comment by ScottSuarez** [comment]
> Error 400: project XXXX not allowed to access regional ServerTlsPolicy

Sounds like this feature may be whitelist only or in preview

**Comment by maxi-cit** [comment]
Hello @ScottSuarez, I came back to this one since I got news that this already was available.

However I am still getting following error:

```
{
  "error": {
    "code": 400,
    "message": "project xxxx not allowed to access regional ServerTlsPolicy",
    "status": "FAILED_PRECONDITION"
  }
}
```

**Comment by ScottSuarez** [comment]
Any idea how I can enable this for the project

**Comment by maxi-cit** [comment]
it seems like it, I also tried while using the gcloud command and it also failed.

**Comment by ScottSuarez** [comment]
> it seems like it, It also failed while using the gcloud command.

If it's whitelist only we'll need to either wait for the feature to launch fully or have the leads of the team advocate for this feature early with some kind of reasoning.

**Comment by ScottSuarez** [comment]
@melinath 

Not sure how to make the compute team aware of this PR.

I assigned a label that i thought was appropriate.

**Comment by pawelJas** [comment]
@ScottSuarez 
The problem is not really with compute. Server Tls Policy is a networksecurity resource. AFAIK it was enabled very recently (or might not yet). 
I think the problem might be with the testing project not having the networksecurity.googleapis.com enabled or the user not having the IAM permission to create there.

**Comment by pawelJas** [comment]
I got the official update:

The feature is still being rolled out and not officially supported. Please stay tuned for documentation updates (https://cloud.google.com/load-balancing/docs/mtls) to see when it's launched. You can try re-running the tests in the meantime but they might fail. If the issue persists after the documentation already mentions support for Regional Load Balancers, please let us know.

**Comment by ScottSuarez** [comment]
Thanks for the update @pawelJas.

Anyone, feel free to ping here when the feature is released and we can re-pull/re-test

**Comment by maxi-cit** [comment]
I ll be checking on this as well

**Comment by maxi-cit** [comment]
Hello @ScottSuarez sorry for the delay, could you re run the test please?

**Review by ScottSuarez — APPROVED** [review]

**Comment by gservat** [comment]
@ScottSuarez: is there any particular reason why you didn't add the `update_*` fields to support updating in-place via `PATCH`? As it seems like it's updateable:

https://cloud.google.com/compute/docs/reference/rest/v1/regionTargetHttpsProxies/patch#request-body

**Comment by gservat** [comment]
Filed https://github.com/GoogleCloudPlatform/magic-modules/pull/11184 to add support for updating `serverTlsPolicy` via `PATCH`.

**Pull request merged**
