### PR TITLE
Add copyright headers to files in the TPG/B downsteam repos that are generated via templates

### PR DESCRIPTION
**Pull request by SarahFrench**
# Context

HashiCorp has this dependabot-style system for asserting that copyright headers are present in their public repos: https://github.com/hashicorp/terraform-provider-google/pull/13624

If we merge these automated PRs the changes will be lost as soon as the next update is merged from Magic Modules.

Instead, we need to update the code generator to add these headers 'at source'.

# Description

This PR acts to enable copyright headers to be included in the TPG/TPGB downstream repos by adding Ruby methods that allow the copyright header to be included in templated files only if TPG/TPGB is being generated. This is achieved by:
- Mimicking the way that the generated code notices are made; see `mmv1/compile/core.rb` and `mmv1/templates/hashicorp_copyright_header.erb`
- Making a boolean available to templates to let them know if the downstream being generated is TPG/TPGB or not; see `mmv1/provider/file_template.rb` for how the value is made available to the templating process, and the new `generating_hashicorp_repo?` functions in the changed `mmv1/provider/terraform*.rb` files

In a separate PR I hope to address how headers can be added to non-templated files that are copied as-is into the TPG/TPGB codebase (e.g. files that are in the transport package).

This PR corresponds to # 2 in the list below:

>1. Adding hardcoded headers to handwritten files that are used in TPG/TPGB and not used in terraform-google-conversion
>2. Provide Magic Modules with knowledge of what downstream it is making when logic in the templates is being evaluated, and have HashiCorp copyright be templated in only if TPG/TPGB is being generated.
>3. Handle handwritten files, specifically util files and packages like `transport`, that are copied into their downstream repo as-is and don't benefit from templating to introduce logic. The only edits to these files I'm aware of is the changing of import paths when the private version of the provider is built, and that's done without templating.

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
It's a problem that the terraform validator repo is being affected - will need to investigate

**Comment by SarahFrench** [comment]
Force pushed after a rebase to address a merge issue.
Also, removed the commit that edited files in `/utils/` as it impacted downstream repos that aren't the Google provider.

**Comment by SarahFrench** [comment]
I removed the header from the tpgresource, transport, and verify packages for now because that code is used in the terraform-google-converter project. Those files will need to be edited during the downstream generation process (versus having the headers hardcoded) and they will need a different approach as templating isn't currently available in those files (.go versus .go.erb or .erb files)

**Comment by SarahFrench** [comment]
Following [this](https://github.com/GoogleCloudPlatform/magic-modules/pull/7504#issuecomment-1561368783) I removed the original and revert commits via a rebase and force push

**Comment by SarahFrench** [comment]
🎉 Now this PR's only impact on terraform-google-conversion is affecting the go.mod and go.sum files. Opening for PR review.

**Comment by SarahFrench** [comment]
Split this PR into two - moved edits to handwritten files into https://github.com/GoogleCloudPlatform/magic-modules/pull/8012

**Review by rileykarson — APPROVED** [review]

**Comment by SarahFrench** [comment]
Merging this now as part of this plan: https://github.com/hashicorp/terraform-provider-google/pull/13624#issuecomment-1562821920

**Pull request merged**
