### PR TITLE
Updated documentation for google_sql_user resource to prevent the setting of password or host field for IAM users and Service Account users.

### PR DESCRIPTION
**Pull request by ravisiddhu**
This PR is to address the issue mentioned in https://github.com/hashicorp/terraform-provider-google/issues/10946

Buganizer reference : (b/259900415): EXT: google_sql_user error when set password or host

Updated documentation for google_sql_user resource to prevent the setting of password or host field for "CLOUD_IAM_USER" and "CLOUD_IAM_SERVICE_ACCOUNT" users.

```release-note:enhancement
google_sql_user: Updated documentation for preventing setting of password or host field for IAM and Service account user types.
```

### CODE REVIEW

**Comment by ravisiddhu** [comment]
```release-note:enhancement
google_sql_user: Added validation for preventing setting of password or host field for IAM and Service account user types.
```

**Comment by shuyama1** [comment]
Is the API able to handle such validation or return clear error message to indicate that `password` or `host` can't be set up for certain user types. We tend to avoid such validation on the Terraform side, especially the ones during `terraform apply` time but not `terraform plan` time.

**Comment by ravisiddhu** [comment]
The APi returns "Error: Error, failure waiting for insertion of serviceAccount:clousql-user@xxxxxxxx.iam.gserviceaccount.com".

The error message returned by API (as shown above) is not a clear message, and terraform customers are not able to understand the reason for the error. Hence the issue : https://github.com/hashicorp/terraform-provider-google/issues/10946

Thus I have added the validation function before calling the API.

**Comment by shuyama1** [comment]
Thanks for the quick update @ravisiddhu! Then it sounds like it's better to ask API team to provider clear error message? I would suggest filing a bug against the API first. We mostly rely on API errors for any conditional validation, and mostly avoid any customize apply-time validation on the terraform side.

**Comment by ravisiddhu** [comment]
The API was not returning that error, it was actually from terraform.

The API returns:-
```
 "error": {
  "kind": "sql#operationErrors",
  "errors": [
   {
    "kind": "sql#operationError",
    "code": "INTERNAL_ERROR"
   }
  ]
 }
```

The below code segment is the terraform code responsible for the error meesage (inside google_sql_user resource)
```
err = sqlAdminOperationWaitTime(config, op, project, "Insert User", userAgent, d.Timeout(schema.TimeoutCreate))

    if err != nil {
        return fmt.Errorf("Error, failure waiting for insertion of %s "+
            "into %s: %s", name, instance, err)
    }
```

Since api returns an internal error object which would not have an error message, the variable err is “”(empty string), resulting in the error message to look like below:-
Error: Error, failure waiting for insertion of xxx@xxx.com into db—instance-xx-name: 

Would we need to change the api behaviour of returning a generic internal error for this? Isn’t it the terraform error message which is confusing the customers?

**Comment by shuyama1** [comment]
@ravisiddhu Thanks for the clear explanation! Letting the API error out when such fields are set together is usually how we handle such conditions. I think document it clearly in the [website docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user) should be good for user experience in this case. We generally copy the [API doc](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users) for our website documentation. So, while improving the Terraform doc (located at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/sql_user.html.markdown), I'd suggest also file a ticket against the API doc if possible.
However, if you think a terraform side validation is highly needed in this case, we have to make sure that it's not likely to be changed in the future+ we need to add unit tests/ acceptance tests on it!
Thank you so much and let me know if you have any questions!

**Review by shuyama1 — COMMENTED** [review]
@ravisiddhu Are we deciding to move forward with this validation in TF? If so, we still need to add unit tests/ acceptance tests on it, based on my previous comment. Plus, I just want to confirm if this restriction is not likely to be changed in the future.

**Comment by ravisiddhu** [comment]
I explored the API codebase and have realised that the error messages thrown during validations are not reflected to the end customer in the case of one-shot agents, but that is not the case with operational agents, but "Create User" is currently only being executed via one-shot agents in data-plane.

I also had a discussion with my team lead, and we were on an opinion that:-
1) We would create a bugaizer ticket for the bug in the API
2) We would have a validation in TF temporarily
3) We would also create one more buganizer ticket to remove the validation once if the bug is fixed in the API

What is your opinion on this? and how do we add test cases for this validations, since the existing test templates in magic modules is for successful creation & destroy of resourses for different configs?

**Comment by shuyama1** [comment]
Thanks for the update @ravisiddhu!
If the validation in TF is only planned to be temporary, I would suggest that we document it clearly in the [doc](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/sql_user.html.markdown) for both `password` and `host` fields that it can't be specified when type is set to `CLOUD_IAM_USER` or `CLOUD_IAM_SERVICE_ACCOUNT` (or whatever restriction it should follow) instead of adding a validation in TF now and then removing it later. Error out on the backend + clear documentation should be good for users to understand the correct use case. Please let me know your thoughts. Thanks!

**Comment by ravisiddhu** [comment]
Sounds good, will do that.

**Review by shuyama1 — APPROVED** [review]
Thank you!

**Comment by ravisiddhu** [comment]
I have also fixed the admin api to throw an user facing error
Submitted CL : cl/499811796

Now, the user gets meaningful error from the API
```
Error: Error, failed to insert user user12@google.com into instance mysql-inst-user2: googleapi: Error 400: Invalid request: For IAM users, password or hostname should not be specified.
```

I have also updated the terraform documentation in this PR.

**Comment by shuyama1** [comment]
@ravisiddhu Nice! Thank you so much!

**Pull request merged**
