### PR TITLE
Make tpgtools spit out working documentation.

### PR DESCRIPTION
**Pull request by ndmckinley**
In order for KCC to depend on a tpgtools resource, tpgtools needs to fix the longstanding-but-low-priority bug with documentation escaping.  It turns out not to be too hard since go doesn't have a whole lot of necessary escape sequences - just `"`, `\`, and newlines.  Made it a function that's easy to work with if we find more that we need to add, although I was going based on https://golang.org/ref/spec#String_literals so it should be pretty correct.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/9197.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by ndmckinley** [comment]
Another oom issue in TeamCity.  This diff is all just description stuff, am I okay to merge without running those tests or do I need to wait for them?

**Comment by ndmckinley** [comment]
Ah, might as well just go again.  /gcbrun

**Comment by slevenick** [comment]
> Another oom issue in TeamCity. This diff is all just description stuff, am I okay to merge without running those tests or do I need to wait for them?

I'd just go for it, the only danger here would be non-compiling resources but that would show up real quickly!

**Comment by ndmckinley** [comment]
Will do, thanks.  The test as it stands seems to prove that it does compile at least!

**Pull request merged**
