### PR TITLE
container: bump gcsfs to GA

### PR DESCRIPTION
**Pull request by DrFaust92**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
conatainer: bump `gcfs_config` to GA
```

### CODE REVIEW

**Comment by wyardley** [comment]
@BBBmau can we try and get #11272 (which has already been approved) through before this one? I suspect this may cause some conflicts there that would not be too fun to resolve.

**Comment by wyardley** [comment]
Side note: it's merged now, though there are now some conflicts.

**Comment by DrFaust92** [comment]
thanks [wyardley](https://github.com/wyardley), fixed

**Comment by wyardley** [comment]
One thing I'm noticing when looking at https://github.com/hashicorp/terraform-provider-google/issues/19482 is that it looks like _some_ of the `gcfs_config` stuff is already not inside guard clasues, but some of it is?

**Review by BBBmau — APPROVED** [review]
approving after running tests on PR through TeamCity: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CONTAINER/239420?buildTab=tests&expandedTest=build%3A%28id%3A239420%29%2Cid%3A2000000000

```hcl
------- Stdout: -------
=== RUN   TestAccContainerCluster_withNodePoolDefaults
=== PAUSE TestAccContainerCluster_withNodePoolDefaults
=== CONT  TestAccContainerCluster_withNodePoolDefaults
--- PASS: TestAccContainerCluster_withNodePoolDefaults (979.00s)
PASS
```

Thanks for this!

**Pull request merged**
