### PR TITLE
Promote tpu-topology to GA

### PR DESCRIPTION
**Pull request by vivianrwu**
Promote support for GKE 1VM TPU. 
- Promote `tpu_topology` field to GA in NodePool schema to support TPU machines.

Extension of GoogleCloudPlatform/magic-modules/pull/8271
Fixes hashicorp/terraform-provider-google/issues/15837

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted field `placement_policy.tpu_topology` in resource `google_container_node_pool` to GA
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Thanks for making the change! Are you able to run the test and get it passed locally against GA provider, since it's skipped?

**Comment by vivianrwu** [comment]
> Thanks for making the change! Are you able to run the test and get it passed locally against GA provider, since it's skipped?

Hi! Yes, please refer to internal bug 291813193 comment 4 and 5 for proof of acceptance test working and passing local testing. I produced terraform-provider-google then commented out t.Skip() and ran the acceptance test.

**Comment by shuyama1** [comment]
Don't think the failing test is related. /gcbrun

**Review by shuyama1 — APPROVED** [review]
Thank you for working on it! 
The test is not working in our testing environment so skipped it completely (VRC + nightly). More context at https://github.com/hashicorp/terraform-provider-google/issues/15254#issuecomment-1646277473

For GA test for this PR, it's confirmed passing locally. see b/291813193 for evidence

**Pull request merged**
