### PR TITLE
[CI Test - Do Not Merge] Test Branch - rewrite vcr_cassette_update in golang

### PR DESCRIPTION
**Pull request by shuyama1**
This upstream direct branch is created to test the change in https://github.com/GoogleCloudPlatform/magic-modules/pull/11148. This will be used in a temporary cloud build trigger to test the CI change in VCR nightly. Only the branch is needed, but the PR is not. I've only created this PR for visibility.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
Back up the main cassettes locally at this checkpoint in case the tests accidentally overwrite them.

**Comment by shuyama1** [comment]
Backed up the main cassettes locally at this checkpoint in case the tests accidentally overwrite them.

**Comment by shuyama1** [comment]
@iyabchen Sorry, I forgot to mention that I've copied the latest version of https://github.com/GoogleCloudPlatform/magic-modules/pull/11148 and trigger the build. vcr-nightly-temp-testing still failed. Looks like there's still error in uploading cassettes. Please let me know if there's anything I can help with, like SA permissions issues, etc.

**Comment by rileykarson** [comment]
Closing old do not merge PRs.

**Pull request closed without merging**
