### PR TITLE
Add EXTERNAL_MANAGED option to global forwarding rule and add example

### PR DESCRIPTION
**Pull request by AlexanderEllis**
This adds the EXTERNAL_MANAGED load balancing scheme option to the Global Forwarding Rule resource and adds an example that will generate tests.

This option was added in the DCL (the change was merged in a previous PR https://github.com/GoogleCloudPlatform/magic-modules/pull/5586), but I'm also adding it here so that it automatically generates the test and examples.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/10858

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added `EXTERNAL_MANAGED` as option for `load_balancing_scheme` in `google_compute_global_forwarding_rule` resource
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
Hi @AlexanderEllis! Would you mind following the instruction [here](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/tpgtools#new-resource-guide) to update resources coming from DCL. I believe running `make upgrade-dcl` and then `make serialize` should make changes generated. Thanks a lot!

**Comment by AlexanderEllis** [comment]
Hi @shuyama1 , sure thing! I thought I had done that before, but I don't think it ended up making any additional changes beyond the 4 files (the `go.mod` and `go.sum` files).

I tried running it again, but I think I may have ran into an issue with `make serialize`:

image

Not sure if this is related to my change, but happy to debug further.

**Comment by AlexanderEllis** [comment]
Ah OK I think I figured it out, I hadn't rebased with the other changes in magic-modules. I did so, and it looks like it still only generated the four files: https://github.com/GoogleCloudPlatform/magic-modules/pull/5611/commits/2582c989e906706b95dd923c2df0f82763a5d6b1

I believe I added the DCL right, and it looks like the auto import in the DCL repo included the samples: https://github.com/GoogleCloudPlatform/declarative-resource-client-library/commit/f92a0d28430ffb6eea59ff6666e6631e4c71f7dc . Am I missing something with the import?

**Comment by AlexanderEllis** [comment]
On further review, I think this was already propagated in a previous PR upgrading the version (https://github.com/hashicorp/terraform-provider-google-beta/pull/3987/files#diff-855513ce3d7fa58a1e5c7435ff810420698b528e20322f1b96dc8fd049b90b08), so I think this is already set

**Comment by shuyama1** [comment]
@AlexanderEllis Sorry for missing this. Somehow, it did not show up on my review list after you made the change. Really apologize for this. You are right. it looks like part of the code is already generated and pushed in a previous PR. 

One problem is that this a TF brownfield resource that we don't generate tests and documentation using tpgtools (DCL-based generator). So we have to manually add the tests and update the documentation in the handwritten files ([test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/terraform/tests), [docs](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/terraform/website/docs/r)). Would you mind making those changes against those files. Sorry about the extra work! Please let me know if you have any questions.

**Comment by shuyama1** [comment]
Also please re-request my review after you make the changes. Thanks a lot!

**Comment by AlexanderEllis** [comment]
Thanks again for your help, @shuyama1! I think I've updated it correctly here:

- Added the option in the `api.yaml` file
- Added an example with the new EXTERNAL_MANAGED option
- Added the example in the `terraform.yaml` file

I also updated the PR and description to better reflect these changes 👍

**Review by shuyama1 — APPROVED** [review]
@AlexanderEllis The tests passed! LGTM! I've changed a bit in the description and CHANGELOG. Can you confirm those changes are valid? Thank you so much!

**Comment by AlexanderEllis** [comment]
Changes LGTM, thanks again!

**Comment by shuyama1** [comment]
Great! Merging now! Thanks for the contribution :)

**Pull request merged**
