### PR TITLE
allow beta tests to use import

### PR DESCRIPTION
**Pull request by ScottSuarez**
closes https://github.com/hashicorp/terraform-provider-google/issues/7603
Enabling import for beta tests

- [x] https://github.com/hashicorp/terraform-provider-google/issues/9782
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9783
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9784
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9785
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9786
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9787
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9788
- [x] https://github.com/hashicorp/terraform-provider-google/issues/9789

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by rileykarson** [comment]
Ah, I didn't realise the (obvious in retrospect) outcome that these would fail in VCR too, causing noise on every subsequent PR until they're fixed. If it was 2-3 resources I'd say we should definitely just fix them here, but fixing 8 in one PR is pretty large.

@slevenick: Do you think it'd be abusing VCR opt-out to avoid needing to fix all these resources here, or should we use that? We can note to remove the opt-out in the test failure issues above.

**Comment by slevenick** [comment]
> Ah, I didn't realise the (obvious in retrospect) outcome that these would fail in VCR too, causing noise on every subsequent PR until they're fixed. If it was 2-3 resources I'd say we should definitely just fix them here, but fixing 8 in one PR is pretty large.
> 
> @slevenick: Do you think it'd be abusing VCR opt-out to avoid needing to fix all these resources here, or should we use that? We can note to remove the opt-out in the test failure issues above.

That could work. Or adding an opt-out for import specifically as that's what is failing

As long as we actually come back and fix it I wouldn't mind VCR opt-out

**Review by rileykarson — APPROVED** [review]
I think the VCR run exposed some timing problems in guest OS policies imports, we'll just need to apply `ImportStateVerifyIgnore` to the affected (presumably output-only) fields. If you have the time, mind fixing them up in a followup?

**Comment by ScottSuarez** [comment]
filed https://github.com/hashicorp/terraform-provider-google/issues/9955

**Pull request merged**
