### PR TITLE
Add certificate manager trust config resource

### PR DESCRIPTION
**Pull request by DanielRieske**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_certificate_manager_trust_config`
```

Closes: 
- https://github.com/hashicorp/terraform-provider-google/issues/15473 
- https://github.com/hashicorp/terraform-provider-google/issues/14984

### CODE REVIEW

**Comment by DanielRieske** [comment]
I removed the whitespaces and whiteline to pass the linter but I am a little stumped on why it believes there are no acceptance tests.

**Comment by DanielRieske** [comment]
@trodge could you share the test failure for `TestAccCertificateManagerTrustConfig_certificateManagerTrustConfigExample` I can't reproduce a failure in my own project.

**Comment by trodge** [comment]
This is the error:
```
2023-08-14T19:20:04.324Z [ERROR] sdk.helper_resource: Unexpected error: test_step_number=1 test_terraform_path=/bin/terraform test_working_directory=/tmp/plugintest1551355497
  error=
  | Error running pre-apply refresh: exit status 1
  | 
  | Error: Invalid function argument
  | 
  |   on terraform_plugin_test.tf line 9, in resource "google_certificate_manager_trust_config" "default":
  |    9:       pem_certificate = file("test-fixtures/certificatemanager/cert.pem")
  | 
  | Invalid value for "path" parameter: no file exists at
  | "test-fixtures/certificatemanager/cert.pem"; this function works only with
  | files that are distributed as part of the configuration source code, so if
  | this file will be created by a resource in this configuration you must
  | instead obtain this result from an attribute of that resource.
  | 
  | Error: Invalid function argument
  | 
  |   on terraform_plugin_test.tf line 12, in resource "google_certificate_manager_trust_config" "default":
  |   12:       pem_certificate = file("test-fixtures/certificatemanager/cert.pem") 
  | 
  | Invalid value for "path" parameter: no file exists at
  | "test-fixtures/certificatemanager/cert.pem"; this function works only with
  | files that are distributed as part of the configuration source code, so if
  | this file will be created by a resource in this configuration you must
  | instead obtain this result from an attribute of that resource.
   test_name=TestAccCertificateManagerTrustConfig_certificateManagerTrustConfigExample
```

**Comment by trodge** [comment]
> I removed the whitespaces and whiteline to pass the linter but I am a little stumped on why it believes there are no acceptance tests.

The missing test detector currently isn't seeing any tests because they've been moved to service packages.

**Comment by DanielRieske** [comment]
I will take a look tomorrow why `file("test-fixtures/certificatemanager/cert.pem")` can't be found.
At the moment I can't put my finger on it as it seems these fixtures do exist in the project and they are used for several other tests.

**Comment by DanielRieske** [comment]
I am going to close this PR and create a new one, I can't seem to fix the branch after rebasing it with main and the changes were relatively small so I will opt on making a new one.

Sorry for the unwanted noise everyone.

**Pull request closed without merging**
