### PR TITLE
Compute public advertised prefixes

### PR DESCRIPTION
**Pull request by slevenick**
Adds PublicAdvertisedPrefix and PublicDelegatedPrefix resources. These are immutable though they have a PATCH method in the API because the PATCH method is only allowed to act on members of the `publicDelegatedPrefixs` field which are better represented as their own resources.

Creating a PAP requires reverse DNS verification, so we use a special loopback IP range and special description (encrypted so as not to publicize this test-only value) to create a test resource. Because we use a specific IP range and quotas for PAPs are very low the tests are handwritten and run in serial to prevent conflict.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_compute_public_advertised_prefix`
```

```release-note:new-resource
`google_compute_public_delegated_prefix`
```

### CODE REVIEW

**Comment by slevenick** [comment]
As noted, tested fields aren't being captured correctly due to the handwritten tests. 

`is_live_migration` is not tested because I was unable to correctly set up a PDP with that flag configured. There are restrictions on enabling it, projects must be opted-in explicitly

**Review by shuyama1 — APPROVED** [review]
LGTM! Only small comments

**Comment by rileykarson** [comment]
@shuyama1: Want to pick this up while Sam's OOO? I can review the delta.

**Comment by shuyama1** [comment]
> @shuyama1: Want to pick this up while Sam's OOO? I can review the delta.

Sure! Taking a look now

**Review by rileykarson — APPROVED** [review]

**Comment by rileykarson** [comment]
FYI @slevenick I added backticks for the resource names: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md#unticked-resource-names

**Pull request merged**
