### PR TITLE
All parameters should be `required: true`

### PR DESCRIPTION
**Pull request by rambleraptor**
All parameters should be `required: true`

This will probably make some changes.

Should I change the api.yaml to get rid of redundant `required: true` values? I was going back and forth on this.

-----------------------------------------------------------------
# [all]
All parameters should be 'required: true'

### CODE REVIEW

**Comment by ndmckinley** [comment]
Amazingly, this seems to cause Terraform not to compile.  What do you think is going on there?

**Comment by ndmckinley** [comment]
Ah, I bet I know why Terraform doesn't compile - our parameters are mostly _not_ required - they can be set in the provider block in addition to in the resource block.

**Comment by ndmckinley** [comment]
Ah, it's `compute_disk` - good ol' `compute_disk`.  :(

**Comment by rileykarson** [comment]
Can this be closed as outdated?

**Comment by rambleraptor** [comment]
G

**Pull request closed without merging**
