### PR TITLE
terraform-provider-google: retry enable and read google_project_service

### PR DESCRIPTION
**Pull request by DeviaVir**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
google_project_service: retrying read and enable on backend errors (`returned error: googleapi: Error 500: Internal error encountered., backendError`) for configured duration
```

### CODE REVIEW

**Comment by DeviaVir** [comment]
We run into this one in one of our bigger terraform workspaces that manage multiple other projects, sometimes a 500 happens which means we need to restart the entire process. The `retryFunc` seems to retry on 500's as well so this should cover it.

**Comment by slevenick** [comment]
Tossing this to @emilymye who knows more about retries than I do

**Comment by emilymye** [comment]
We actually should be retrying these operations already - if you follow the sendF functions the batch request will call, they eventually lead to https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_google_project.go#L517

and https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_google_project.go#L551

I'm not sure it's a good idea to retry on top of the batch function, especially since it retries the whole batch function (add to batch and wait, send batch of services to enable, read to confirm enabled, try again per service when the batch fails). It could be that we are retrying but the timeout is actually too small. Can you confirm whether you're seeing the retry logs when running with `TF_LOG=DEBUG`? ("[DEBUG] Waiting for state to become...")

It could also be that it's a particular error that's escaping our retry predicates that we'd have to try on.

**Comment by DeviaVir** [comment]
Oof, disregard this one. We were (accidentally) using a pre-3.0.0 release.

**Pull request closed without merging**
