### PR TITLE
Shared reservation

### PR DESCRIPTION
**Pull request by simamGit**
Added shareSetting to enable SharedReservation  creation for compute.reservation.
ShareSetting includes two properties:
 -shareType: LOCAL and SPECIFIC_PROJECTS
 -project_map: a map of projectId and projectConfig.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added `shareSettings` in `google_compute_reservation`
```

### CODE REVIEW

**Comment by paul-hoang** [comment]
@melinath Could you also add me as a reviewer for this pull request? (I'm new to this process, so please feel free to let me know if this is not needed).

**Comment by melinath** [comment]
@paul-hoang I can't add you as a reviewer, but I think you may be able to provide a review regardless.

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like `TestAccComputeReservation_sharedReservationBasicExample` is failing with the following error:

```
Error: Error creating Reservation: googleapi: Error 412: Constraint constraints/compute.sharedReservationsOwnerProjects violated for project projects/<project-number>
Shared reservation can not be created in this project for your organization., conditionNotMet
```

Please [ensure that this test passes locally](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) & then re-request review.

**Comment by simamGit** [comment]
> It looks like `TestAccComputeReservation_sharedReservationBasicExample` is failing with the following error:
> 
> ```
> Error: Error creating Reservation: googleapi: Error 412: Constraint constraints/compute.sharedReservationsOwnerProjects violated for project projects/<project-number>
> Shared reservation can not be created in this project for your organization., conditionNotMet
> ```
> 
> Please [ensure that this test passes locally](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) & then re-request review.

I can locally run both reservation and sharedreservation tests successfully. using these two commands:
TF_LOG=DEBUG make testacc TEST=./google TESTARGS=' run=TestAccComputeReservation_sharedReservationBasicExample'

 TF_LOG=DEBUG make testacc TEST=./google TESTARGS='-run=TestAccComputeReservation_reservationBasicExample'

but it is also set the environment variables for these tests. specially project play key role for these tests. I set these three EVN variables:  GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_PROJECT , GOOGLE_REGION

**Comment by simamGit** [comment]
> It looks like `TestAccComputeReservation_sharedReservationBasicExample` is failing with the following error:
> 
> ```
> Error: Error creating Reservation: googleapi: Error 412: Constraint constraints/compute.sharedReservationsOwnerProjects violated for project projects/<project-number>
> Shared reservation can not be created in this project for your organization., conditionNotMet
> ```
> 
> Please [ensure that this test passes locally](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) & then re-request review.

Hi Stephen, 
I updated the sharedReservation test to cover all required environment setting/configuration for test. This test starts with creating two projects and set the org policy and finally creates sharedReservation. 

to create project and set org policy the user need to have these roles: Organization Administrator,  Organization Policy Administrator and Project Creator. 

also we need to set these environment variables 
 GOOGLE_PROJECT, GOOGLE_REGION, GOOGLE_ZONE,GOOGLE_BILLING_ACCOUNT. 
in my case since I used the gcloud authentication I also set GOOGLE_USE_DEFAULT_CREDENTIALS=true. 

It is passing successfully in my local machine but all these new changes are for Terraform environment. hopefully this time it can pass in Terrafom Environment.

**Comment by melinath** [comment]
I'm running the new test manually in Beta since it skips vcr: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/235485

**Comment by simamGit** [comment]
> I'm running the new test manually in Beta since it skips vcr: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/235485

Thanks, it seems the main tests sharedReservation and reservation are passing ( i do not see them in failing list). most of the tests which are failing does not look related. I am going to check the TestAccComputeInstance_reservationAffinities, TestAccComputeReservation_update to see if their failing is  due to my recent changes.

**Comment by melinath** [comment]
> I am going to check the TestAccComputeInstance_reservationAffinities, TestAccComputeReservation_update to see if their failing is due to my recent changes.

Thanks for pointing these out as potential issues; I've started a new run in Teamcity for just these tests as well: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/235487

**Comment by simamGit** [comment]
> > I am going to check the TestAccComputeInstance_reservationAffinities, TestAccComputeReservation_update to see if their failing is due to my recent changes.
> 
> Thanks for pointing these out as potential issues; I've started a new run in Teamcity for just these tests as well: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/235487

I ran locally the reservation related tests: 
TF_LOG=DEBUG make testacc TEST=./google TESTARGS='-run=TestAccComputeReservation_'
 just in case: 
TF_LOG=DEBUG make testacc TEST=./google TESTARGS='-run=TestAccComputeReservation_update'
all are passing.

**Review by melinath — CHANGES_REQUESTED** [review]
@simamGit +1 it looks like `TestAccComputeReservation_` is passing in CI as well. However, `TestAccComputeInstance_reservationAffinities` seems to be failing with a permadiff:

```
Terraform will perform the following actions:
# google_compute_reservation.reservation must be replaced
-/+ resource "google_compute_reservation" "reservation" {
+ commitment                    = (known after apply)
~ creation_timestamp            = "2021-12-23T11:32:06.647-08:00" -> (known after apply)
~ id                            = "projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
name                          = "tf-test-resaffinity-et2yep0tb1"
~ project                       = "project-id" -> (known after apply)
~ self_link                     = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
specific_reservation_required = true
~ status                        = "READY" -> (known after apply)
~ zone                          = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a" -> "us-central1-a"
- share_settings {
- share_type = "LOCAL" -> null
}
~ specific_reservation {
count        = 1
~ in_use_count = 0 -> (known after apply)
~ instance_properties {
machine_type     = "n1-standard-1"
+ min_cpu_platform = (known after apply)
}
}
}
```

The relevant part is:

```
- share_settings {
- share_type = "LOCAL" -> null
}
```

This means that the API returned a value for this field that Terraform didn't expect, so Terraform is trying to set it to `null`. I believe you can work around this by adding `default_from_api` to shareSettings and shareType in terraform.yaml - that will make Terraform accept whatever the API returns.

**Comment by simamGit** [comment]
> @simamGit +1 it looks like `TestAccComputeReservation_` is passing in CI as well. However, `TestAccComputeInstance_reservationAffinities` seems to be failing with a permadiff:
> 
> ```
> Terraform will perform the following actions:
> # google_compute_reservation.reservation must be replaced
> -/+ resource "google_compute_reservation" "reservation" {
> + commitment                    = (known after apply)
> ~ creation_timestamp            = "2021-12-23T11:32:06.647-08:00" -> (known after apply)
> ~ id                            = "projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
> name                          = "tf-test-resaffinity-et2yep0tb1"
> ~ project                       = "project-id" -> (known after apply)
> ~ self_link                     = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
> specific_reservation_required = true
> ~ status                        = "READY" -> (known after apply)
> ~ zone                          = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a" -> "us-central1-a"
> - share_settings {
> - share_type = "LOCAL" -> null
> }
> ~ specific_reservation {
> count        = 1
> ~ in_use_count = 0 -> (known after apply)
> ~ instance_properties {
> machine_type     = "n1-standard-1"
> + min_cpu_platform = (known after apply)
> }
> }
> }
> ```
> 
> The relevant part is:
> 
> ```
> - share_settings {
> - share_type = "LOCAL" -> null
> }
> ```
> 
> This means that the API returned a value for this field that Terraform didn't expect, so Terraform is trying to set it to `null`. I believe you can work around this by adding `default_from_api` to shareSettings and shareType in terraform.yaml - that will make Terraform accept whatever the API returns.

Thanks Stephen for update. I think I now how to fix it.

**Comment by simamGit** [comment]
> > @simamGit +1 it looks like `TestAccComputeReservation_` is passing in CI as well. However, `TestAccComputeInstance_reservationAffinities` seems to be failing with a permadiff:
> > ```
> > Terraform will perform the following actions:
> > # google_compute_reservation.reservation must be replaced
> > -/+ resource "google_compute_reservation" "reservation" {
> > + commitment                    = (known after apply)
> > ~ creation_timestamp            = "2021-12-23T11:32:06.647-08:00" -> (known after apply)
> > ~ id                            = "projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
> > name                          = "tf-test-resaffinity-et2yep0tb1"
> > ~ project                       = "project-id" -> (known after apply)
> > ~ self_link                     = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a/reservations/tf-test-resaffinity-et2yep0tb1" -> (known after apply)
> > specific_reservation_required = true
> > ~ status                        = "READY" -> (known after apply)
> > ~ zone                          = "https://www.googleapis.com/compute/v1/projects/project-id/zones/us-central1-a" -> "us-central1-a"
> > - share_settings {
> > - share_type = "LOCAL" -> null
> > }
> > ~ specific_reservation {
> > count        = 1
> > ~ in_use_count = 0 -> (known after apply)
> > ~ instance_properties {
> > machine_type     = "n1-standard-1"
> > + min_cpu_platform = (known after apply)
> > }
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The relevant part is:
> > ```
> > - share_settings {
> > - share_type = "LOCAL" -> null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This means that the API returned a value for this field that Terraform didn't expect, so Terraform is trying to set it to `null`. I believe you can work around this by adding `default_from_api` to shareSettings and shareType in terraform.yaml - that will make Terraform accept whatever the API returns.
> 
> Thanks Stephen for update. I think I now how to fix it.

I just update the compute_instance_test to fix the affinity error. so I think it should fix the error. I think we need one more run to check TestAccComputeInstance_reservationAffinities.

**Comment by melinath** [comment]
New beta test run for `TestAccComputeReservation_sharedReservationBasicExample| TestAccComputeInstance_reservationAffinities|TestAccComputeReservation_update`: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/239599

**Comment by melinath** [comment]
Mistyped the test names, trying again for `TestAccComputeReservation_sharedReservationBasicExample|TestAccComputeInstance_reservationAffinities|TestAccComputeReservation_update`: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/239605

**Review by melinath — CHANGES_REQUESTED** [review]
@simamGit please look into using default_from_api as I mentioned above. It would also be great to revert adding `share_type = "LOCAL"` to the tests - although this does get the tests passing, it masks the fact that this will create a permadiff for everyone using this resource (which would trigger a bug report and require additional work later.) go/dont-break-terraform

**Comment by simamGit** [comment]
> default_from_api
Thanks Stephen, I missed the default_from_api: true point earlier! I am going to add it and also remove the Local setting from update and other tests.

**Comment by melinath** [comment]
It looks like there's an issue on the API side; please re-request review once that's been resolved. I think everything here should be ready to go once that's finished. https://google.aip.dev/cloud/2510

**Comment by melinath** [comment]
Beta test run for just `TestAccComputeReservation_sharedReservationBasicExample|TestAccComputeInstance_reservationAffinities|TestAccComputeReservation_update`: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/242318

**Comment by melinath** [comment]
Per discussion, we're moving forward with ignore_read rather than fixing the API issue. ignore_read doesn't seem to work as expected inside the map object, so it has to be set to ignore reads on all of share settings.

**Comment by melinath** [comment]
Trying a beta run again - the last one failed for unrelated reasons: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/242816

**Review by melinath — APPROVED** [review]
This LGTM as long as the tests pass.

**Comment by paul-hoang** [comment]
LGTM.

**Comment by melinath** [comment]
new beta test run for `TestAccComputeReservation_sharedReservationBasicExample|TestAccComputeInstance_reservationAffinities|TestAccComputeReservation_update`: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/242833

I was running the other one in the wrong place which is why it was failing 🤦

**Pull request merged**
