### PR TITLE
Handle failed flex template job updates

### PR DESCRIPTION
**Pull request by andremarianiello**
This is the magic-modules version https://github.com/hashicorp/terraform-provider-google-beta/pull/3279

```release-note:bug
dataflow: fixed handling of failed `google_dataflow_flex_template_job` updates (beta)
```

### CODE REVIEW

**Comment by andremarianiello** [comment]
@googlebot I signed it!

**Comment by slevenick** [comment]
@melinath I think you've looked at this recently, do you have any input here?

**Comment by melinath** [comment]
@slevenick I think this approach seems reasonable, though I'm not familiar with the use of d.Partial().

**Comment by andremarianiello** [comment]
Here on the docs on Partial https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema#ResourceData.Partial (just to make them easier to find).

**Review by slevenick — APPROVED** [review]
Makes sense to me, thanks for the contribution!

**Pull request merged**
