### PR TITLE
Add configuration  for Authorization policy

### PR DESCRIPTION
**Pull request by maphad**
Add configuration for traffic director authorizationPolicy resource

part of https://github.com/hashicorp/terraform-provider-google/issues/14040

If this PR is for Terraform, I acknowledge that I have:

- [ x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_network_security_authorization_policy`
```

### CODE REVIEW

**Review by ScottSuarez — COMMENTED** [review]
Could join the GoogleCloudOrganization so our CI can detect you?
Join [GoogleCloudPlatform org](https://github.com/GoogleCloudPlatform) through go/github/orgs

I notice this is in draft state. Let me know if there is anything I can help with in the meantime while you work on this

**Comment by maphad** [comment]
> Could join the GoogleCloudOrganization so our CI can detect you? Join [GoogleCloudPlatform org](https://github.com/GoogleCloudPlatform) through go/github/orgs
> 
> I notice this is in draft state. Let me know if there is anything I can help with in the meantime while you work on this

Thanks, I am already part of the GoogleCloudOrg. Marked the PR as ready for review now.

**Comment by ScottSuarez** [comment]
Strange !! Our automation should be picking you your bit and running! Not sure why. I'll go ahead and manually approve

**Comment by ScottSuarez** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
ls: cannot access 'website/docs/**/*.md': No such file or directory
make: *** [GNUmakefile:26: vet] Error 2
google-beta/resource_container_cluster.go:5070:38: undefined: container.K8sBetaAPIConfig
google-beta/resource_container_cluster.go:4511:20: undefined: container.K8sBetaAPIConfig
google-beta/resource_container_cluster.go:4505:64: undefined: container.K8sBetaAPIConfig
google-beta/resource_container_cluster.go:3292:6: unknown field 'DesiredK8sBetaApis' in struct literal of type container.ClusterUpdate
google-beta/resource_container_cluster.go:2494:69: cluster.EnableK8sBetaApis undefined (type *container.Cluster has no field or method EnableK8sBetaApis)
google-beta/resource_container_cluster.go:2117:11: cluster.EnableK8sBetaApis undefined (type *container.Cluster has no field or method EnableK8sBetaApis)
# github.com/hashicorp/terraform-provider-google-beta/google-beta
go vet
````

compilation error... suspect you need to upgrade a package

**Comment by ScottSuarez** [comment]
> > Could join the GoogleCloudOrganization so our CI can detect you? Join [GoogleCloudPlatform org](https://github.com/GoogleCloudPlatform) through go/github/orgs
> > I notice this is in draft state. Let me know if there is anything I can help with in the meantime while you work on this
> 
> Thanks, I am already part of the GoogleCloudOrg. Marked the PR as ready for review now.

Does not look like you are apart of the organization.. https://github.com/orgs/GoogleCloudPlatform/people?query=maphad

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
