### PR TITLE
Fix FirebaseApp sweepers

### PR DESCRIPTION
**Pull request by roaks3**
These sweepers have been reporting that there are no sweepable resources, but there are resources accumulating and they have hit the limit. This makes a few changes to get the sweeper working as intended:

(One of the API specs for reference https://firebase.google.com/docs/reference/firebase-management/rest/v1beta1/projects.iosApps)
- Fix the field used from the list response to `apps`
- Fix the `remove` request to use POST
- Fix the sweeper sweepable field to be `displayName` instead of `name`, because name is server-generated
- Fix the `displayName`s used for FirebaseApp tests to include sweepable prefixes

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by roaks3** [comment]
Waiting to make sure the generated diffs look correct. Will also try running a sweeper locally.

**Review by trodge — COMMENTED** [review]
LGTM, adding Stephen for a second review.

**Review by melinath — APPROVED** [review]
lgtm

**Comment by roaks3** [comment]
I accidentally rebased main so had to force-push, but the only change is this: https://github.com/GoogleCloudPlatform/magic-modules/pull/7279/commits/448a78f54ae5b1200492b2ad4d671f94c8b027c1

The delete URLs in the sweeper were also incorrect, so this change fixes them.

Confirmed that the AppleApp sweeper correctly sweeps now, and the `tf-test` added here is necessary to identify the apps.

**Comment by melinath** [comment]
@roaks3 is there some way we can verify in CI that these are working properly now or do we need to test manually locally?

**Comment by roaks3** [comment]
@melinath  With our current setup, I don't think there is a way to automatically test these before merge. If we decided to build something to support it, you could potentially create fake resources with eg. gcloud, or make a test fail before cleanup, and then run the sweeper and verify the resource no longer exists. That's just one example, but basically, I think there are some options but they would probably introduce some complexity and a longer CI runtime.

**Comment by roaks3** [comment]
Oh and I guess to add to that, these sweepers in particular were not sweeping, but they did not produce an error or anything that might be easier to detect. Since they were looking in the wrong field of the response, they simple behaved as if there were no resources to sweep.

**Review by melinath — APPROVED** [review]

**Pull request merged**
