### PR TITLE
Fix permadiff when `edition` field is added to configuration of a `google_sql_database_instance` resource 

### PR DESCRIPTION
**Pull request by SarahFrench**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/15553

This PR adds a diff suppress that helps the provider handle a problem with the Cloud SQL API. If you create a database instance without specifying an edition it will default to ENTERPRISE. However the edition field is not returned in GET requests to the API. If you create the resource and specify the edition in the initial create action then the edition field _is_ returned as part of the API response. As a result `""` and `"ENTERPRISE"` are equivalent values of `edition` for a `google_sql_database_instance` resource.

See https://github.com/hashicorp/terraform-provider-google/issues/15553#issuecomment-1753045977 for more info.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
sql: Fixed a bug where adding the `edition` field to a `google_sql_database_instance` resource that already existed and used ENTERPRISE edition resulted in a permant diff in plans
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
I manually tested this by applying this with the latest provider version:

```tf
resource "google_sql_database_instance" "instance" {
  name                = "tf-test-sarah-12345"
  region              = "us-east1"
  database_version    = "POSTGRES_14"
  deletion_protection = false
  settings {
    # edition = "ENTERPRISE"
    tier = "db-custom-2-13312"
  }
}
```

To get the resource created with edition:"" in state, and then I would uncomment the edition field and check what plan and apply commands did to state when using a version of the provider with this PR's (latest) changes

**Comment by melinath** [comment]
Would it be useful to add a state migration as well?

**Review by melinath — APPROVED** [review]
Looking at this again, I'm a little uncertain whether the state upgrader is strictly necessary, since the flattener would hypothetically set state during refresh - but I am definitely able to upgrade without a diff. :-)

**Comment by SarahFrench** [comment]
I found using a version of the provider with just the flattener added would let the state be updated when operating on a resource that was already provisioned with the latest provider release - I removed the state upgrader

**Review by melinath — APPROVED** [review]
still able to upgrade without a diff :-)

**Pull request merged**
