### PR TITLE
Fix empty object behavior in the DCL

### PR DESCRIPTION
**Pull request by slevenick**
Issues I've found when making the GKEHub Feature resource. I wanted to separate it from the GKEHub PR though

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — APPROVED** [review]
This seems reasonable; is this something that it would be possible / make sense to unit test?

**Review by melinath — CHANGES_REQUESTED** [review]
looks like there are some build failures:

```
google/resource_dataproc_workflow_template.go:1919:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobs has no field or method Empty)
google/resource_dataproc_workflow_template.go:1963:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHadoopJob has no field or method Empty)
google/resource_dataproc_workflow_template.go:1996:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHadoopJobLoggingConfig has no field or method Empty)
google/resource_dataproc_workflow_template.go:2027:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHiveJob has no field or method Empty)
google/resource_dataproc_workflow_template.go:2058:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHiveJobQueryList has no field or method Empty)
google/resource_dataproc_workflow_template.go:2090:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJob has no field or method Empty)
google/resource_dataproc_workflow_template.go:2122:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJobLoggingConfig has no field or method Empty)
google/resource_dataproc_workflow_template.go:2148:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJobQueryList has no field or method Empty)
google/resource_dataproc_workflow_template.go:2180:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPrestoJob has no field or method Empty)
google/resource_dataproc_workflow_template.go:2212:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPrestoJobLoggingConfig has no field or method Empty)
google/resource_dataproc_workflow_template.go:2212:22: too many errors
```

**Comment by slevenick** [comment]
> This seems reasonable; is this something that it would be possible / make sense to unit test?

Hard to unit test as it is within generated code. Integration tests with DCL-based resources are the best way to test this, but the current resources don't work particularly well with this for a couple reasons.

Eventarc only has computed nested objects, which means we don't send them as empty to the DCL

Dataproc workflow template is input-only so update doesn't work on it.

The best way to test this is setting a field (especially a nested object) to a value during a test and then updating it to remove it. GKEHub feature will have some of these tests for sure, and I'd suggest adding them for any new DCL-based resource

**Comment by slevenick** [comment]
> looks like there are some build failures:
> 
> ```
> google/resource_dataproc_workflow_template.go:1919:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobs has no field or method Empty)
> google/resource_dataproc_workflow_template.go:1963:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHadoopJob has no field or method Empty)
> google/resource_dataproc_workflow_template.go:1996:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHadoopJobLoggingConfig has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2027:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHiveJob has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2058:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsHiveJobQueryList has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2090:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJob has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2122:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJobLoggingConfig has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2148:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPigJobQueryList has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2180:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPrestoJob has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2212:22: obj.Empty undefined (type *"github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc".WorkflowTemplateJobsPrestoJobLoggingConfig has no field or method Empty)
> google/resource_dataproc_workflow_template.go:2212:22: too many errors
> ```

Yeah, this will require updating the version of the DCL in the downstream repos, the Empty func was added recently. I'll take care of that before merging

**Review by melinath — APPROVED** [review]
LGTM given the updates mentioned above

**Pull request merged**
