### PR TITLE
Network Connectivity Hub 

### PR DESCRIPTION
**Pull request by c2thorn**
Part of https://github.com/hashicorp/terraform-provider-google/issues/10514

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_network_connectivity_hub`
```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Overall looks good to me, but a couple questions.

Is this resource worth releasing without the partner resource?

Do we need the DCL upgrade to add this? I believe there is a breaking change in an osconfig resource here: https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5574-old..auto-pr-5574#diff-10ce2c336edf0b7efb1851d634d178e963bcffcc179223e09c1d6e224f112ec7R706

**Comment by slevenick** [comment]
Huh, looks like a docs bug where we don't print both the `validate` & `enforce` block structures, so unrelated to this

**Review by slevenick — APPROVED** [review]

**Comment by c2thorn** [comment]
@slevenick 

> Is this resource worth releasing without the partner resource?

Not really, but at least the next review can be smaller in scope. Appreciate it the time!

> Do we need the DCL upgrade to add this? I believe there is a breaking change in an osconfig resource here: 

I missed that, and not sure why that appears in this PR. But I'll look into fixing the bug.

**Comment by c2thorn** [comment]
partner resource is ready, so I'm merging this

**Pull request merged**
