### PR TITLE
Fixed accesscontextmanager spec requirements

### PR DESCRIPTION
**Pull request by alx13**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/14612

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
accesscontextmanager: Fixed incorrect schema in spec for `google_access_context_manager_service_perimeter`. 
```

### CODE REVIEW

**Comment by alx13** [comment]
Basically inability to have empty status blocks, so in bridge perimeters you had to configure one of `resources`, `access_levels` or `restricted_services` to null.

And it was causing a constant drift between `[]` and `null` here:

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/vpc-sc/service-perimeters-bridge.tf#L38


Reference:
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/schema.go#L282

**Comment by megan07** [comment]
Ok. Were you able to test it out and see this fixed it? I'm just curious because these still exist on the `status` block:
https://github.com/GoogleCloudPlatform/magic-modules/pull/7952/files#diff-7a2e1e241b560b7faaa972c7294741d0b40cc943f61d55945cd3c0b1232ef483R155

I'm just wondering if that's correct or if we need to remove those?

**Comment by alx13** [comment]
We don't need to remove this. Just check how it's translated in the end:

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_access_context_manager_service_perimeter.go#L98

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_access_context_manager_service_perimeter.go#L434

`status` and `spec` are marked as optional, but as `spec` fields are referring to `status` it's glitching.

According to https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/schema.go#L282 :
> the syntax is "parent_block_name.0.child_attribute_name".

**Comment by megan07** [comment]
yup, yup! i agree this change is good, i just wanted to make sure it was solving the ultimate issue. thanks!

**Pull request merged**
