### PR TITLE
add `exclude_resource` in `add iam support` resource doc

### PR DESCRIPTION
**Pull request by BBBmau**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by BBBmau** [comment]
Should be ready to merge, just a simple update to the docs. Didn't include the `exclude_resource` in the IAM Policy portion when generating a resource.

**Review by melinath — CHANGES_REQUESTED** [review]
Rather than adding this to the MMv1 section, it should be added to the Handwritten section - MMv1-based resources will never use this, only Handwritten resources. (Something like IAP is rare and would be directed to follow the docs for Handwritten resources.)

**Comment by BBBmau** [comment]
gotcha @melinath, switched it over to the handwritten tab and included in the list of fields required to set.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
