### PR TITLE
Change the default value of unique_writer_identity in resource logging_project_sink to true.

### PR DESCRIPTION
**Pull request by pengq-google**
Change the default value of unique_writer_identity in resource logging_project_sink to true. unique_writer_identity = false is legacy behavior. New sinks should always set this field to be true.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
Change the default value of unique_writer_identity in resource logging_project_sink to true. unique_writer_identity = false is legacy behavior. New sinks should always set this field to be true.
```

### CODE REVIEW

**Comment by pengq-google** [comment]
@shuyama1 
I know this is a breaking change. however, if I keep `[pengq-google](https://github.com/pengq-google) wants to merge 1 commit into [GoogleCloudPlatform:main](https://github.com/GoogleCloudPlatform/magic-modules/tree/main) from [pengq-google:b9](https://github.com/pengq-google/magic-modules/tree/b9)`, it will only show 2 files changed.

If I change it to the 5.0.0 branch, will be 129 files changes, but i didn't do anything...

**Comment by pengq-google** [comment]
even with newly create clean branch, if I made a pr to 5.0.0, it will have many changed files, seems the user experience changed today. 
https://github.com/GoogleCloudPlatform/magic-modules/pull/8849

**Comment by trodge** [comment]
> even with newly create clean branch, if I made a pr to 5.0.0, it will have many changed files, seems the user experience changed today. #8849

Can you try rebasing on the 5.0.0 branch?

**Comment by pengq-google** [comment]
> 

I just made a new pr: https://github.com/GoogleCloudPlatform/magic-modules/pull/8875 and will close this one. Thanks!

**Pull request closed without merging**
