### PR TITLE
Use Patch instead of Create, even if creating

### PR DESCRIPTION
**Pull request by slevenick**
Otherwise we're getting "Error waiting for Create Service
Networking Connection: Error code 9, message: Cannot modify
allocated ranges in CreateConnection. Please use
UpdateConnection." if we're creating peerings to more than one
VPC (like two CloudSQL instances within one project, peered
with two clusters.)

This is a workaround for:
https://issuetracker.google.com/issues/131908322

Upstreams https://github.com/terraform-providers/terraform-provider-google-beta/pull/1240

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
`service_networking`: `google_service_networking_connection` uses patch instead of create even when creating. Fixes error when using multiple connections
```

### CODE REVIEW

**Comment by slevenick** [comment]
The API seems to accept PATCH requests to create service networking connections, but I'm not sure why.

**Comment by ndmckinley** [comment]
That is _extremely_ odd.  Let's figure out what's going on there before we merge - the release just went out, so we aren't delaying anything by waiting a little while to understand this.

**Comment by ndmckinley** [comment]
If you haven't been able to get in touch with anyone who understands the situation, make a big obvious comment in the docs / in api.yaml / in the code (any or all that make sense) and submit.

**Comment by ndmckinley** [comment]
Your comment as-is is fine with me, send it in if you think it ought to go.

**Comment by k0ffee** [comment]
@googlebot I fixed it.

**Comment by k0ffee** [comment]
@googlebot I consent.

**Pull request merged**
