### PR TITLE
docs: Document that the max allowed retention for Firestore backup schedules is 14 weeks

### PR DESCRIPTION
**Pull request by rwhogg**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by ZixuanLiuCanada — APPROVED** [review]

**Review by hao-nan-li — COMMENTED** [review]
Could you do a rebase on main? I think this error happened before and the fix is included not long ago.

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
