### PR TITLE
Remove Terraform support for game services

### PR DESCRIPTION
**Pull request by hao-nan-li**
Remove Terraform support for game services.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
gameservices: Remove Terraform support for `gameservices`
```

### CODE REVIEW

**Comment by c2thorn** [comment]
google-conversion is failing... are we expecting it to here?
```
/go/pkg/mod/github.com/modular-magician/terraform-provider-google-beta@v1.20.1-0.20230816180001-e7f5f0defd12/google-beta/provider/provider.go:895:58: undefined: gameservices
```
I can't see the line in the generated diff

**Comment by c2thorn** [comment]
Is there an upgrade guide entry PR?

**Comment by hao-nan-li** [comment]
> Is there an upgrade guide entry PR?

Not yet, I'll do that after lunch.

**Comment by hao-nan-li** [comment]
> google-conversion is failing... are we expecting it to here?
> 
> ```
> /go/pkg/mod/github.com/modular-magician/terraform-provider-google-beta@v1.20.1-0.20230816180001-e7f5f0defd12/google-beta/provider/provider.go:895:58: undefined: gameservices
> ```
> 
> I can't see the line in the generated diff

I need to double-check a bit, maybe there's something I missed during the removal.

**Review by c2thorn — APPROVED** [review]
added the label, don't remember if we need it for this branch.

**Pull request merged**
