### PR TITLE
Add Release Channel config for GKE

### PR DESCRIPTION
**Pull request by chrissng**
# Release Note for Downstream PRs (will be copied)
```releasenote
Add Release Channel config for GKE
```

### CODE REVIEW

**Comment by rambleraptor** [comment]
Hello! Thanks for your contribution. I'm adding @slevenick to do a review + running your PR through our CI system.

**Comment by slevenick** [comment]
Hey @chrissng 

Is this PR ready for review? It is marked as a draft, which typically means it is not ready for review yet

**Comment by chrissng** [comment]
Hello @slevenick, I'm still figuring out a good way to run tests locally, after that I would write some test for this.

**Comment by chrissng** [comment]
Hello @slevenick, pardon the delay. I have closed this PR as the master had moved on quite a bit and I decided to do a clean fork before continuing the work. This is the new PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/2414

**Pull request closed without merging**
