### PR TITLE
Docs: Prepared a tf snippet for creating a new Cloud Storage bucket

### PR DESCRIPTION
**Pull request by cbonnie**
Intending to use this snippet on the following page: https://cloud.google.com/storage/docs/creating-buckets#storage-create-bucket-console 

If this PR is for Terraform, I acknowledge that I have:

- [ x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by cbonnie** [comment]
Hi @ScottSuarez. Any ideas on how to resolve the unsuccessful checks (TerraformVCRCommunity (graphite-docker-imates) and beta-provider-vcr-test)?

**Comment by ScottSuarez** [comment]
Looks like this didn't generate any changes.. going to tag @c2thorn as this looks to be a scenario they covered recently.

**Comment by ScottSuarez** [comment]
aka adding a docs test where we don't use the mmv1 generation.. @c2thorn is there a solution on this end?

**Comment by c2thorn** [comment]
Yeah `google_storage_bucket` is part of a group of resources that don't support CGC snippets yet.

Need to figure out at least a temporary solution to https://github.com/hashicorp/terraform-provider-google/issues/10651 before this will be possible.

**Comment by cbonnie** [comment]
@c2thorn Did something change that enabled https://github.com/GoogleCloudPlatform/magic-modules/pull/5420/files to be submitted? That PR also adds a code sample to CGC.

**Comment by c2thorn** [comment]
@cbonnie The problem is that the `google_storage_bucket` resource in the provider is not managed by this `terraform.yaml` file. If you see the line https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/storage/terraform.yaml#L17, Magic Modules excludes Storage Bucket so your sample will not be read. This is because the `google_storage_bucket` code is handwritten here: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/resources/resource_storage_bucket.go.erb
And I haven't come up with a way to support CGC samples for handwritten resources yet.

As a workaround to get your snippet unblocked, we could try moving this "Example" block over to the `HmacKey` [Example section](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/storage/terraform.yaml#L128) and add the `skip_test` and `skip_docs` lines so it looks like this:
```
      - !ruby/object:Provider::Terraform::Examples
        name: "storage_new_bucket"
        primary_resource_id: "static"
        skip_test: true
        skip_docs: true
        vars:
          new_bucket: "new-bucket"
```

This will not add your sample to our tests or Hashicorp reference docs, but it will get your sample generated in https://github.com/terraform-google-modules/terraform-docs-samples so you can move forward.

**Comment by cbonnie** [comment]
@c2thorn Ah gotcha, thanks for the help. I don't think we'll plan to add this code sample to the HMAC key section. Would it be alright to keep this PR open until we can get it merged in the future?

**Comment by c2thorn** [comment]
@cbonnie Absolutely, I just wanted to provide some options at the very least. 

When https://github.com/hashicorp/terraform-provider-google/issues/10651 closes, I'll respond here and/or give you a ping.

**Comment by betsy-lichtenberg** [comment]
Hi Bonnie,

We can solve this with nested region tags.

We will have one set of outer region tags for [this entire sample](https://paste.googleplex.com/4808974189723648), and also add a set of more specific region tags for only the bucket resource.

For more info about nested region tags, see https://g3doc.corp.google.com/company/teams/cloud-devrel/dpe/samples/code_snippets_201.md?cl=head#nested-region-tags.

This assumes that we need to address b/209695244 before we address b/210478662.

Thanks,
Betsy

**Comment by cbonnie** [comment]
I'm confused - I think we should address this separately from the Host a Static Website sample.

**Comment by betsy-lichtenberg** [comment]
Hopefully https://github.com/hashicorp/terraform-provider-google/issues/10651 will get resolved soon, and we can move forward without confusing workarounds.

**Comment by c2thorn** [comment]
This was included in https://github.com/terraform-google-modules/terraform-docs-samples/pull/27
I'll close here, if further changes need to be made I recommend starting a new PR with the latest changes.

**Pull request closed without merging**
