### PR TITLE
Add import-only to KMS key

### PR DESCRIPTION
**Pull request by bdhess**
Similar to #5131, and probably also required for the same customer.
Apologies for the oversight.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
kms: added support for `import_only` to `google_kms_crypto_key`
```

### CODE REVIEW

**Comment by sshcherbakov** [comment]
Hello Everybody,
We are interested in the getting this PR through as soon as possible.
How can we help?

**Comment by melinath** [comment]
Hey all - sorry for the delay on this; I lost track of this PR. The best thing you can do if this happens again on a PR in the future is to press the "[Re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/)" button to make sure this is in the reviewer's actionable queue.

/gcbrun because the last one failed.

**Comment by melinath** [comment]
> We have an internal thread that suggests that the present failure is just a flake.

@bdhess the failure was definitely unrelated to this PR; do you mean that the test is also flakey?

**Comment by bdhess** [comment]
@melinath I mean flaky per the definition at go/flaky -- it fails nondeterministically with respect to the test inputs.

**Comment by melinath** [comment]
@bdhess great, thanks for confirming. We generally would prefer not to merge new flakey tests; is it at all possible to fix the test to not be flakey?

**Comment by bdhess** [comment]
@melinath and I discussed offline that I don't think any new flakiness is introduced with this PR

**Comment by melinath** [comment]
At least we're not aware of flakiness yet. :-) It looks like the new test failed in CI, but it could be a CI issue again. I'll do a rerun of just that test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/207210

**Comment by drebes** [comment]
I cloned your fork and tried to run your test, but it first failed:
```
$ make testacc TEST=./google TESTARGS='-run=TestAccKmsCryptoKey_importOnly'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccKmsCryptoKey_importOnly -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccKmsCryptoKey_importOnly
=== PAUSE TestAccKmsCryptoKey_importOnly
=== CONT  TestAccKmsCryptoKey_importOnly
    provider_test.go:270: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
       
        (map[string]string) (len=1) {
         (string) (len=29) "skip_initial_version_creation": (string) (len=5) "false"
        }
       
       
        (map[string]string) (len=1) {
         (string) (len=29) "skip_initial_version_creation": (string) (len=4) "true"
        }
--- FAIL: TestAccKmsCryptoKey_importOnly (86.85s)
FAIL
FAIL github.com/hashicorp/terraform-provider-google/google 87.364s
FAIL
make: *** [testacc] Error 1
```
This is actually expected because when we import the state to verify the resource was created correctly, "skip_initial_version" is [always set to false](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_kms_crypto_key.go#L414) since its value cannot be inferred from the object read from the API and we assume a safe default. But it's actually easy to fix, you just need to add this change to your test:
```
diff --git a/mmv1/third_party/terraform/tests/resource_kms_crypto_key_test.go b/mmv1/third_party/terraform/tests/resource_kms_crypto_key_test.go
index 251ea357f..52f6fa205 100644
--- a/mmv1/third_party/terraform/tests/resource_kms_crypto_key_test.go
+++ b/mmv1/third_party/terraform/tests/resource_kms_crypto_key_test.go
@@ -353,9 +353,10 @@ func TestAccKmsCryptoKey_importOnly(t *testing.T) {
                                Config: testGoogleKmsCryptoKey_importOnly(projectId, projectOrg, projectBillingAccount, keyRingName, cryptoKeyName),
                        },
                        {
-                               ResourceName:      "google_kms_crypto_key.crypto_key",
-                               ImportState:       true,
-                               ImportStateVerify: true,
+                               ResourceName:            "google_kms_crypto_key.crypto_key",
+                               ImportState:             true,
+                               ImportStateVerify:       true,
+                               ImportStateVerifyIgnore: []string{"skip_initial_version_creation"},
                        },
                        // Use a separate TestStep rather than a CheckDestroy because we need the project to still exist.
                        {
```
With that change, your `importOnly` and all other CryptoKey tests successfully pass for me:
```
$ make testacc TEST=./google TESTARGS='-run=TestAccKmsCryptoKey'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccKmsCryptoKey -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccKmsCryptoKeyIamBinding
=== PAUSE TestAccKmsCryptoKeyIamBinding
=== RUN   TestAccKmsCryptoKeyIamMember
=== PAUSE TestAccKmsCryptoKeyIamMember
=== RUN   TestAccKmsCryptoKeyIamPolicy
=== PAUSE TestAccKmsCryptoKeyIamPolicy
=== RUN   TestAccKmsCryptoKey_basic
=== PAUSE TestAccKmsCryptoKey_basic
=== RUN   TestAccKmsCryptoKey_rotation
=== PAUSE TestAccKmsCryptoKey_rotation
=== RUN   TestAccKmsCryptoKey_template
=== PAUSE TestAccKmsCryptoKey_template
=== RUN   TestAccKmsCryptoKey_destroyDuration
=== PAUSE TestAccKmsCryptoKey_destroyDuration
=== RUN   TestAccKmsCryptoKey_importOnly
=== PAUSE TestAccKmsCryptoKey_importOnly
=== CONT  TestAccKmsCryptoKeyIamBinding
=== CONT  TestAccKmsCryptoKey_template
=== CONT  TestAccKmsCryptoKey_basic
=== CONT  TestAccKmsCryptoKey_rotation
=== CONT  TestAccKmsCryptoKeyIamPolicy
=== CONT  TestAccKmsCryptoKey_destroyDuration
=== CONT  TestAccKmsCryptoKey_importOnly
=== CONT  TestAccKmsCryptoKeyIamMember
--- PASS: TestAccKmsCryptoKey_importOnly (105.83s)
--- PASS: TestAccKmsCryptoKey_basic (106.83s)
--- PASS: TestAccKmsCryptoKey_destroyDuration (107.13s)
--- PASS: TestAccKmsCryptoKeyIamPolicy (126.04s)
--- PASS: TestAccKmsCryptoKey_template (127.44s)
--- PASS: TestAccKmsCryptoKeyIamMember (140.07s)
--- PASS: TestAccKmsCryptoKey_rotation (144.87s)
--- PASS: TestAccKmsCryptoKeyIamBinding (177.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-google/google	177.601s
```

**Comment by melinath** [comment]
I can confirm that (now that CI was able to run the test) we're seeing that same error in CI.

Given that we're not able to set `skip_initial_version_creation` accurately, this seems like a reasonable fix.

**Comment by bdhess** [comment]
Thanks a bunch @drebes for the analysis!

**Comment by bdhess** [comment]
@melinath I don't see a [re-request review button](https://screenshot.googleplex.com/5FtdeFmrQqjqo6c) sadly.  Is that possibly limited to maintainers?

**Comment by melinath** [comment]
@bdhess I've already re-requested a review for myself, so the button is not available to me right now either. :-) you could check for it once I get a chance to do a review again.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
