### PR TITLE
uniqueWriterIdentity field added to logging_folder_sink

### PR DESCRIPTION
**Pull request by sanghaniJ**
uniqueWriterIdentity field added to logging_folder_sink along with test
fixes https://github.com/hashicorp/terraform-provider-google/issues/12660

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
logging: added `unique_writer_identity` field to `google_logging_folder_sink` resource
```

### CODE REVIEW

**Comment by sanghaniJ** [comment]
Hey @rileykarson , I've been working on adding this field but in create/update funcs, it is explicitly mentioned `The API will reject any requests that don't explicitly set 'uniqueWriterIdentity' to true.`  I've added the same to docs and schema description as well but wanted to ask do I need to add a validation in terraform if someone provides the value as False?

**Comment by sanghaniJ** [comment]
@rileykarson Could you please review this PR?

**Review by rileykarson — COMMENTED** [review]
Given we already set this to true all the time & the user's request was to be able to set the field to true, I din't think we need to make this change. I suspect the API either enforces we set it to true all the time (which is why that comment is there) or it doesn't do anything at this level. In either case we'd want to omit it in Terraform.

See https://github.com/hashicorp/terraform-provider-google/issues/12660#issuecomment-1355445299 for my breakdown.

**Comment by sanghaniJ** [comment]
Yes, omitting this field is fine. Closing this Pull Request.

**Pull request closed without merging**
