### PR TITLE
Deprecate google_sql_database_instance.settings.ip_configuration's require_ssl in favor of ssl_mode

### PR DESCRIPTION
**Pull request by feng-zhe**
Deprecate google_sql_database_instance.settings.ip_configuration's require_ssl in favor of ssl_mode.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:deprecation
sql: `settings.ip_configuration.require_ssl` is now deprecated within `google_sql_database_instance`. Please use `settings.ip_configuration.ssl_mode` instead.
```

### CODE REVIEW

**Comment by feng-zhe** [comment]
Hmmm, it is unclear to me why my changes affects the TestReadPlannedAssetsCoverage/example_google_cloudfunctions_function. Taking a look.

**Comment by feng-zhe** [comment]
I believe the above failure is due to PR #10313 and is irrelevant to this PR.

@NickElliot Hi Nick, please let me know if you'd like me to look into it further. Thanks.

**Comment by feng-zhe** [comment]
I see the above failure is:
```
        read_test.go:245: TestReadPlannedAssetsCoverage/example_google_datastream_stream_append_only diff(-want, +got):
        ...
                     						"ipv4Enabled":        bool(true),
            - 						"requireSsl":         bool(false),
            + 						"requireSsl":         nil,
              					},
```

I am not sure how the `example_google_datastream_stream_append_only` is generated because I didn't find this file. I only find the `./mmv1/third_party/tgc/tests/data/example_google_datastream_stream.json` and its `requireSsl` has been updated already to `null`.

**Review by NickElliot — CHANGES_REQUESTED** [review]
one last thing: can you also include making an entry in mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown? Thanks!

**Comment by feng-zhe** [comment]
@NickElliot Thanks, Nick. The `mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown` has already been updated for this breaking change via #10833 and its change has been included in both main and this branch. Please let me know if you want me to update other docs. Thanks!

**Review by NickElliot — APPROVED** [review]

**Comment by NickElliot** [comment]
all is well!

**Pull request merged**
