### PR TITLE
TeamCity: Update build step so tests only run if there are tests to run

### PR DESCRIPTION
**Pull request by SarahFrench**
This PR addresses this issue:

Screenshot 2023-10-11 at 21 38 58

This error is raised when there are no tests to run - either due to no test binary or a test prefix that filters out all tests and leaves none to be run.

Here is a build affected by this : [API GATEWAY FAILING BUILD](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_NightlyTests_GOOGLE_PACKAGE_APIGATEWAY/40306?buildTab=log&logView=flowAware)

Here is a build that shows the effects of the change in this PR: [API GATEWAY BUILD USING THIS PRS CHANGES](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_SarahManualTestingProject_GOOGLE_PACKAGE_APIGATEWAY/40903?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false) 

Screenshot 2023-10-11 at 21 41 34

Also, this PR fixes https://github.com/hashicorp/terraform-provider-google/issues/16226

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]
LGTM- this seems reasonable, although I've got no way to test it or anything!

**Comment by SarahFrench** [comment]
I manually tested the change in my test project here : https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_SarahManualTestingProject_GOOGLE_PACKAGE_APIGATEWAY?

Screenshot 2023-10-11 at 21 56 52

Those top two builds used the final version of the bash I was testing, and I used TeamCity's 'View as code' feature to make sure I got a Kotlin-compatible version of the bash (i.e. the weird handling of `$`s in `export TEST_COUNT=${'$'}(./test-binary -test.list=%TEST_PREFIX% | wc -l)`) 

Screenshot 2023-10-11 at 21 59 44

**Comment by SarahFrench** [comment]
I'll hold off merging this until Monday next week, as the builds in TeamCity are backed up and any potential issues resulting from this PR would negatively impact the release shepherd more

**Comment by SarahFrench** [comment]
👆 I tested this change in the `google` package in my testing project, here: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_Google_SarahManualTestingProject_GOOGLE_PACKAGE_GOOGLE

The failed build listed there is running a build with the old build config that fails because the google folder doesn't contain any go files, so fails to make the test binary and running tests.

The passing build contains this PR's updates to the the steps:

```
Step 5/6: Compile Test Binary (Command Line)

20:35:39   Starting: /opt/teamcity-agent/temp/agentTmp/custom_script10699591644129204066
20:35:39   in directory: /opt/teamcity-agent/work/5b6d7e499bff1f69/google
20:35:39   ls: cannot access './*_test.go': No such file or directory
20:35:39   Skipping compilation of test binary; no Go test files found
20:35:39   Process exited with code 0


Step 6/6: Run via jen20/teamcity-go-test (Command Line)

20:35:40   Starting: /opt/teamcity-agent/temp/agentTmp/custom_script11086220746786582905
20:35:40   in directory: /opt/teamcity-agent/work/5b6d7e499bff1f69/google
20:35:40   Skipping test execution; file ./test-binary does not exist.
20:35:40   Process exited with code 0
```

**Review by rileykarson — APPROVED** [review]
Good catch! LGTM w/ the same caveat about the quality of my review as before, but your test results are convincing.

**Comment by SarahFrench** [comment]
Merging now as any unforeseen issues won't affect/can be addressed before the next release cut

**Pull request merged**
