### PR TITLE
Compute serviceattachment dcl

### PR DESCRIPTION
**Pull request by trodge**
Moved google_compute_service_attachment from an mmv1 implementation to a DCL/tpgtools implementation.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by rileykarson** [comment]
I killed this VCR run as it was going to re-record hundreds of tests (which would then need to get re-re-recorded) due to this being on an old merge base pre`4.0.0`. @trodge: Do you mind rebasing?

**Comment by rileykarson** [comment]
Also, @ScottSuarez do you mind assigning me as a second reviewer on this once you've approved? I'd like to walk through a brownfield change myself.

**Comment by ScottSuarez** [comment]
> Also, @ScottSuarez do you mind assigning me as a second reviewer on this once you've approved? I'd like to walk through a brownfield change myself.

sure, will do. As a process note I recommended running the diffing tool before reviewing this pr. I am not sure where we can put that information that ensure this is followed though. I think this an important step when transitioning resources to the dcl.

https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#ensuring-no-plan-time-difference-to-latest-provider-release-optional

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
