### PR TITLE
Promote GKE Backup BackupPlan to GA

### PR DESCRIPTION
**Pull request by neha-vellanki12**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/13195

If this PR is for Terraform, I acknowledge that I have:

- [ X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
promoted `google_gke_backup_backup_plan` to ga (ga only)

```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
The build for the ga provider is failing.

google/resource_gke_backup_backup_plan_test.go:19:17: undefined: testAccProvidersOiCS


Could you try building the ga provider locally?

**Comment by neha-vellanki12** [comment]
I'm able to build the GA provider locally. If I remember correctly, that test  is a handwritten test, since update tests have to be handwritten. I remember from my last PR that testAccProvidersOiCS has something to do with Beta testing? Let me see if I update that provider and reupload if it fixes the issue

**Comment by neha-vellanki12** [comment]
@ScottSuarez I was able to run this test in GA and Beta provider. the error in the VCR test seems to be from another test. is this a test flake and we can re run vcr tests? or was there some breaking change and other tests are failing as well?
```
CONT  TestAccCloudIdentityGroupMembership_membershipDoesNotExist
    resource_cloud_identity_group_membership_test.go:199: Error creating service account: googleapi: Error 409: Service account tf-test-sa-dwn6z7le22 already exists within project projects/ci-test-project-188019.
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.ResourceInfo",
            "resourceName": "projects/ci-test-project-188019/serviceAccounts/tf-test-sa-dwn6z7le22@ci-test-project-188019.iam.gserviceaccount.com"
          }
        ]
        , alreadyExists
--- FAIL: TestAccCloudIdentityGroupMembership_membershipDoesNotExist (0.25s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2affdcf]
```

**Review by ScottSuarez — APPROVED** [review]
Looks good ! Thanks for the work

**Pull request merged**
