### PR TITLE
Release provider-defined functions

### PR DESCRIPTION
**Pull request by SarahFrench**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
provider: introduced support for provider-defined functions. This feature is in Terraform v1.8.0+.
```
```release-note:enhancement
provider: added provider-defined function `project_from_id` for retrieving the project id from a resource's self link or id
```
```release-note:enhancement
provider: added provider-defined functions `location_from_id`, `region_from_id`, and `zone_from_id` for retrieving the location/region/zone names from a resource's self link or id
```
```release-note:enhancement
provider: added provider-defined function `name_from_id` for retrieving the short-form name of a resource from its self link or id
```
```release-note:enhancement
provider: added provider-defined function `region_from_zone` for deriving a region from a zone's name
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
This PR is blocked until the merge conflicts above are addressed by syncing the main branch into the feature branch

**Comment by SarahFrench** [comment]
Just synced main into this branch but there are new merge conflicts shown above

**Comment by SarahFrench** [comment]
I just pushed directly to this branch to address the latest merge conflicts : 239b060

**Comment by SarahFrench** [comment]
After discussing the `build-downstreams (graphite-docker-images)` failure we determined that no resolution is needed as long as no more PRs will be created for merge into FEATURE-BRANCH-provider-functions

**Comment by SarahFrench** [comment]
The VCR failure seems to be due to a problem with an IAM resource somewhere:

```
    vcr_utils.go:152: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # google_dataproc_cluster_iam_policy.policy will be updated in-place
          ~ resource "google_dataproc_cluster_iam_policy" "policy" {
                id          = "projects/ci-test-project-188019/regions/us-central1/clusters/tf-test-iam-8m4aal42hz"
              ~ policy_data = jsonencode(
                  ~ {
                      + bindings = [
                          + {
                              + members = [
                                  + "serviceAccount:tf-test-dpiam-qc9gte7oc9@ci-test-project-188019.iam.gserviceaccount.com",
                                ]
                              + role    = "roles/editor"
                            },
                        ]
                    }
                )
                # (4 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by SarahFrench** [comment]
- CLA failure is false, as noted on sync PRs
- build-downstreams failure [doesn't need resolution](https://github.com/GoogleCloudPlatform/magic-modules/pull/10288#issuecomment-2021530908)
- VCR failure isn't related to provider functions

**Review by BBBmau — APPROVED** [review]

**Pull request merged**
