### PR TITLE
[Terraform] remove auto_healing_policies from tests

### PR DESCRIPTION
**Pull request by danawillow**
-----------------------------------------------------------------
# [all]
## [terraform]
Remove auto_healing_policies from tests

### CODE REVIEW

**Comment by rileykarson** [comment]
Why not delete it at Beta too? We test auto_healing_policies with a separate test, and I bet it just cropped up here by that one being copy pasted.

**Comment by rileykarson** [comment]
Looks like the tpgb changes are missing?

**Comment by danawillow** [comment]
Hmm I'm not sure whether the magician has the capability to add PRs after the initial set was generated, but I went ahead and opened it myself (since the branch was created successfully in the modular-magician fork). That'll probably be fine.

Also for context in case you're curious, https://github.com/terraform-providers/terraform-provider-google/pull/522 was the PR that added auto_healing_policies in the first place, and it was in order to test the fact that IGM was using beta APIs but backend services weren't. So it did have a good reason to be there (at least for one test). Actually now I've convinced myself that I should add it back for one test, since people might use TPG/TPGB together. Don't approve this yet.

**Comment by rileykarson** [comment]
Cool! I think we used https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb#L234 as a test for versions in general initially. Is this test specific to BackendService or would it better be homed there?

**Comment by danawillow** [comment]
It's specific to backendservice since it tests the URL inside of a set.

**Comment by danawillow** [comment]
Ok I un-convinced myself that we need that test, since the presence of a beta feature in a config no longer influences which API we call, so that test isn't actually going to test interplay between beta/GA.

**Comment by rileykarson** [comment]
Was it testing that we properly diffsuppress/guarded self links in a set maybe? I could see the value in keeping a test that does that & I thought that was what you meant. Let me know if you're still unconvinced & I should review as-is!

**Comment by danawillow** [comment]
auto_healing_policies is a beta feature, which means it only exists in the beta provider. however, it used to act as a toggle- if it was set, then we called the beta apis, otherwise we called the ga ones. since it doesn't act as a toggle anymore, it doesn't need to be in our tests. does that make sense?

**Pull request merged**
