### PR TITLE
Fix test TestAccDataprocClusterLabelsMigration_withRemoval

### PR DESCRIPTION
**Pull request by zli82016**
fixes https://github.com/hashicorp/terraform-provider-google/issues/16168

It is a known issue to upgrade to 5.0 and remove labels at the same time. We are unable to resolve it now because of the model we are using.  It needs to upgrade to 5.0 first and then remove the labels.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by zli82016** [comment]
Test passed https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleBeta_MmUpstreamTesting_GOOGLEBETA_PACKAGE_DATAPROC/41366?buildTab=tests&expandedTest=build%3A%28id%3A41366%29%2Cid%3A2000000002

**Review by melinath — CHANGES_REQUESTED** [review]
It seems like we could probably just remove `TestAccDataprocClusterLabelsMigration_withRemoval` at this point. It should be the same as `TestAccDataprocClusterLabelsMigration_withLabels_withoutChanges` plus a removal of the labels.

To put it another way, it's testing that removing labels works _within_ 5.0, but not testing that removing labels at the same time as upgrading works (because it doesn't). I assume we already have other tests that test removing labels with 5.0? If so, I think we could remove TestAccDataprocClusterLabelsMigration_withRemoval.

**Comment by zli82016** [comment]
> It seems like we could probably just remove `TestAccDataprocClusterLabelsMigration_withRemoval` at this point. It should be the same as `TestAccDataprocClusterLabelsMigration_withLabels_withoutChanges` plus a removal of the labels.
> 
> To put it another way, it's testing that removing labels works _within_ 5.0, but not testing that removing labels at the same time as upgrading works (because it doesn't). I assume we already have other tests that test removing labels with 5.0? If so, I think we could remove TestAccDataprocClusterLabelsMigration_withRemoval.

Yes, there is already a test that removes labels. I am going to delete this test.

**Review by melinath — APPROVED** [review]

**Pull request merged**
