### PR TITLE
Fix google_bigquery_data_transfer salesforce test parameter values

### PR DESCRIPTION
**Pull request by wj-chen**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/19067.

The parameters are now consistent with https://cloud.google.com/bigquery/docs/salesforce-transfer#bq.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by wj-chen** [comment]
@NickElliot Could you take a look?

**Comment by wj-chen** [comment]
@sachinpro @NickElliot - Please take a look and let me know if you have any questions

**Review by NickElliot — APPROVED** [review]
LGTM!

**Review by sachinpro — APPROVED** [review]

**Comment by wj-chen** [comment]
Thank you for the approvals. @NickElliot I believe this is ready to be merged.

**Pull request merged**
