### PR TITLE
Add PSQL 13 to docs and change defaults on SQL Version field

### PR DESCRIPTION
**Pull request by upodroid**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/7772
Fixes https://github.com/hashicorp/terraform-provider-google/issues/5212

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
sql: the default value for `database_version` of `google_sql_database_instance`has been changed to MYSQL_5_7 . Please update your configuration to match this.
```

### CODE REVIEW

**Comment by upodroid** [comment]
I'm aware that this change might cause issues for the 0.0001 % of terraform users who are using mysql5.6 and now need to set the field.

There is a fat warning here about the API being in beta and receiving backward incompatible changes. 
https://cloud.google.com/sql/docs/mysql/admin-api

I changed default because google is currently defaulting to to 5.7 which you can verify by running

```
echo '{"kind": "sql#instance", "name": "foo-11111", "project": "REDACTED", "region": "us-central", "settings": {"kind": "sql#settings", "pricingPlan": "PER_USE", "replicationType": "SYNCHRONOUS", "tier": "db-n1-standard-1"}}'| http POST https://sqladmin.googleapis.com/sql/v1beta4/projects/REDACTED/instances "Authorization: Bearer $(gcloud auth print-access-token)"

gcloud sql instances list --format yaml
```

**Comment by c2thorn** [comment]
Hey @upodroid this should be saved for the next major release. I've made an issue [here](https://github.com/hashicorp/terraform-provider-google/issues/7772) to track, and we can revisit this when it comes time.

**Comment by upodroid** [comment]
Fixes points to the correct issue now

**Comment by c2thorn** [comment]
@upodroid We will likely just make this field required instead of updating the default every time. Currently @shuyama1 is assigned, so she'll likely take that up. 

If you think that's acceptable, I think we can close this.

**Comment by upodroid** [comment]
Yeah, make it required. It makes the resource less fragile.

**Comment by c2thorn** [comment]
Thanks @upodroid.

**Pull request closed without merging**
