### PR TITLE
add network_url attribute in consumer_accept_list block of google_compute_service_attachment resource

### PR DESCRIPTION
**Pull request by laurensknoll**
This change adds the `network_url` attribute to the `consumer_accept_list`-block of the `google_compute_service_attachment` resource.

Note that because ExactlyOneOf is not available for lists, the `projectIdOrNum` attribute is made optional. Issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/470

Fixes:
- https://github.com/hashicorp/terraform-provider-google/issues/15203
- https://github.com/hashicorp/terraform-provider-google/issues/17116

An `service_attachment_explicit_networks` example is added to demonstrate the functionality and acts as an acceptance test.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added the `network_url` attribute to the `consumer_accept_list`-block of the `google_compute_service_attachment` resource.
```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Test is failing with a diff after apply. Were you able to run it successfully?

**Comment by laurensknoll** [comment]
> Test is failing with a diff after apply. Were you able to run it successfully?

Thanks for following up @slevenick .

While the `ga` test works, the `beta` test fails:

```
...
=== CONT  TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample
    vcr_utils.go:152: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # google_compute_service_attachment.psc_ilb_service_attachment will be updated in-place
          ~ resource "google_compute_service_attachment" "psc_ilb_service_attachment" {
                id                    = "projects/my-project/regions/us-west2/serviceAttachments/tf-test-my-psc-ilbg66dgg4vlb"
                name                  = "tf-test-my-psc-ilbg66dgg4vlb"
                # (13 unchanged attributes hidden)
        
              - consumer_accept_lists {
                  - connection_limit = 1 -> null
                  - network_url      = "https://www.googleapis.com/compute/beta/projects/my-project/global/networks/tf-test-psc-ilb-consumer-networkg66dgg4vlb" -> null
                }
              + consumer_accept_lists {
                  + connection_limit = 1
                  + network_url      = "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/tf-test-psc-ilb-consumer-networkg66dgg4vlb"
                }
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
```

Apparently the beta API returns the GA network url reference. Any thoughts to address this?

**Comment by slevenick** [comment]
I think you can add `diff_suppress_func: 'tpgresource.CompareSelfLinkOrResourceName'` to the field to handle the comparison

**Comment by laurensknoll** [comment]
> I think you can add `diff_suppress_func: 'tpgresource.CompareSelfLinkOrResourceName'` to the field to handle the comparison

Thanks for the pointer @slevenick . Combined with a custom `set_hash_func` the relative path comparisons prevent the (false positive) error.

Curious to know if a more generic `set_hash_func` is available. In the end we just want to hash the resource while including the diff suppress func logic.

**Comment by laurensknoll** [comment]
Hi @slevenick , the automated tests have passed. Could you re-review the changes?

**Comment by melinath** [comment]
@slevenick ping

**Review by slevenick — APPROVED** [review]
Sorry, I lost this!

**Pull request merged**
