### PR TITLE
feat(google_container_cluster): promote cost allocation to GA

### PR DESCRIPTION
**Pull request by bradhoekstra**
If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: Promote `enable_cost_allocation` field in `google_container_cluster` to GA
```

### CODE REVIEW

**Comment by bradhoekstra** [comment]
Looks like I have to wait for google.golang.org/api/container/v1 to pick up this field.

**Comment by slevenick** [comment]
Looks like this fails to compile with errors such as:
`undefined: container.CostManagementConfig`

Can you generate & compile the GA version of the provider locally?

**Comment by slevenick** [comment]
Oh, missed your comment, it depends on a new version of the client libraries to be released. Please re-request review once that is ready

**Review by slevenick — CHANGES_REQUESTED** [review]
Re-request review once the new client library is released.

This will also need the docs for this field to be updated to not say beta only

**Comment by slevenick** [comment]
Hm, something went wrong with the library upgrade, it wants `go mod tidy` to be run

**Comment by bradhoekstra** [comment]
Ya, I'm trying to figure that out. First time doing this though, so figuring everything out is slow :)

**Comment by bradhoekstra** [comment]
@slevenick : All checks are passing now.

**Review by bradhoekstra — COMMENTED** [review]
Fixed go modules.

**Comment by slevenick** [comment]
It looks like this field is missing documentation in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

Can you add it there? I would ask you to just remove the beta flag on it, but it seems like it was missed when it was initially added

**Comment by bradhoekstra** [comment]
Thanks for the pointer @slevenick, I've updated the docs now.

**Pull request merged**
