### PR TITLE
Make ipAddress field editable

### PR DESCRIPTION
**Pull request by selslack**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by selslack** [comment]
@googlebot I signed it!

**Comment by selslack** [comment]
@googlebot I signed it!

**Comment by selslack** [comment]
@googlebot I signed it!

**Comment by selslack** [comment]
@rambleraptor can you please take a look?

**Comment by rambleraptor** [comment]
Hello! I'll get this running through our CI system now.

**Comment by selslack** [comment]
@rambleraptor 

I've actually dig deeper into this and I found out that `ip_range` field actually used by GCP API to extract a local interface address.

```
IP address and range of the interface. The IP range must be in the RFC3927 link-local IP address space. The value must be a CIDR-formatted string, for example: 169.254.0.1/30.

NOTE: Do not truncate the address as it represents the IP address of the interface.
```

(see the NOTE)

I'm going to propose documentation improvements for `google_compute_router_interface` (which is outside of this repo) instead.

I'm still not sure if it makes sense to have this field editable. It's definitely not `[Output Only]` according to the API docs. How we can find out the actual meaning of `bgpPeers[].ipAddress` field? Will it override interface's `ip_range`?

**Comment by drebes** [comment]
Chiming in since [we discussed](https://github.com/GoogleCloudPlatform/magic-modules/pull/2434#discussion_r347684918) this as part of the PR that autogenerates BGP peer. The `ipAddress` is not configurable for Terraform when we specify the interface name, AFAIK. We could mark it as `input: true` in api.yaml and override to `false` for Terraform. If you still want to make it editable (for ansible?), I'd suggest adding some acceptance test adding an update of `ipAddress`.

**Pull request closed without merging**
