### PR TITLE
Promote `dns_config` of `google_container_cluster` to GA

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/10502

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted `dns_config` field of `google_container_cluster` to GA
```

### CODE REVIEW

**Comment by upodroid** [comment]
@marktru Comment here once the API is fixed.

**Comment by upodroid** [comment]
@ScottSuarez This is ready now, tests are passing

**Review by ScottSuarez — APPROVED** [review]

**Comment by todd-dsm** [comment]
I'm still only seeing this feature in beta. In which version do we expect to see this in GA?

```shell
% tf version 
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.3.0
+ provider registry.terraform.io/hashicorp/google-beta v4.3.0

Your version of Terraform is out of date! The latest version
is 1.3.0. You can update by downloading from            <- could upgrade
```

**Comment by ScottSuarez** [comment]
Hi Todd, 
It should be in GA.

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_container_cluster.go#L1233-L1261

**Comment by todd-dsm** [comment]
As of the versions posted above, I still can't access it unless I specify the `google-beta` provider. But, that answers my question for you guys. I'll check with the TF folks now.

TIA

**Pull request merged**
