### PR TITLE
Feature/gke backup agent config doc

### PR DESCRIPTION
**Pull request by shubhamkr619**
This PR is support the documentation for gke_backup_agent_config. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1450

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written  "part of {[url](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1450)}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- 
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by rileykarson** [comment]
Adding @zli82016 as initial reviewer

**Comment by zli82016** [comment]
LGTM. 

One minor notice is that we can add the release note to this PR.

**Review by zli82016 — APPROVED** [review]
LGTM.

One minor notice is that we can add the release note to this PR.

**Comment by zli82016** [comment]
Please wait for @rileykarson having follow-up review before merging this PR.

**Comment by rileykarson** [comment]
This duplicates https://github.com/GoogleCloudPlatform/magic-modules/pull/6898, so I'm closing this as obsolete.

@zli82016: Good callout! Release notes got covered in the other PR at https://github.com/GoogleCloudPlatform/magic-modules/pull/6898#pullrequestreview-1208983335, and referencing issues where possible is something we try to do (I'm about to go and fix up the other PR 🙂 ). You have a maintainer commit bit and can make those changes yourself as well, by editing the parent comment. For contributors off the team, I'll generally write the notes myself (covered as a maintainer respopnsibility at https://github.com/GoogleCloudPlatform/magic-modules/pull/6883#issuecomment-1330447313) and quickly check https://github.com/hashicorp/terraform-provider-google/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc for related issues, if any.

**Pull request closed without merging**
