### PR TITLE
fix error with missing zonal value for compute attached disk

### PR DESCRIPTION
**Pull request by NickElliot**
fixes https://github.com/hashicorp/terraform-provider-google/issues/16265

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed issue where `google_compute_attached_disk` would produce an error for certain zone configs
```

### CODE REVIEW

**Review by trodge — COMMENTED** [review]
Would it be possible to add a test that fails without this change and passes with it?

**Comment by NickElliot** [comment]
The test will be skipped in CI because the test precheck wants GOOGLE_ZONE and GOOGLE_REGION set -- but it fails while on current provider, succeeds with this PR's built one.

**Comment by trodge** [comment]
> The test will be skipped in CI because the test precheck wants GOOGLE_ZONE and GOOGLE_REGION set -- but it fails while on current provider, succeeds with this PR's built one.

What's the error you see when you don't skip the test in VCR?

**Review by trodge — APPROVED** [review]
LGTM

**Pull request merged**
