### PR TITLE
Upgrade DCL to v1.34

### PR DESCRIPTION
**Pull request by c2thorn**
If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
containerazure: added `azure_services_authentication` to `google_container_azure_cluster`
```

```release-note:deprecation
gkehub: deprecated `mesh.control_plane` in `google_gke_hub_feature_membership`. Use `mesh.management` instead (beta-only)
```

```release-note:enhancement
cloudbuild: added `peered_network_ip_range` field to `google_cloudbuild_worker_pool` resource
```

```release-note:enhancement
clouddeploy: added `multi_target` field to `google_clouddeploy_target` resource (beta-only)
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
LGTM - failing test seems unrelated. It looks like this also adds a couple other fields, which will need release notes:

- `google_azure_cluster.client`
- `google_cloudbuild_worker_pool.peered_network_ip_range`
  -  This resource has handwritten docs that need to be updated to include the new field.

**Comment by melinath** [comment]
it looks like there should also be a deprecation release note for gke_hub feature membership's `control_plane` field.

**Comment by c2thorn** [comment]
@melinath 
> * `google_azure_cluster.client`

Client went from required to optional

> * `google_cloudbuild_worker_pool.peered_network_ip_range`
>   
>   * This resource has handwritten docs that need to be updated to include the new field.

Good catch, added

> it looks like there should also be a deprecation release note for gke_hub feature membership's control_plane field (beta-only)

Added the actual deprecation override, and will add the release note

**Comment by melinath** [comment]
@c2thorn sorry, lost track of this one - it looks like there are a couple of conflicts but otherwise I imagine it's ready? If so could you make sure it's got review requested from me after the change?

**Comment by c2thorn** [comment]
@melinath there are no cloud workstation changes here, so the test seems unrelated

**Review by melinath — APPROVED** [review]
LGTM - one small thing: google_gke_hub_feature_membership docs seem to be handwritten, so the deprecation notice will need to be moved over manually.

**Comment by c2thorn** [comment]
> LGTM - one small thing: google_gke_hub_feature_membership docs seem to be handwritten, so the deprecation notice will need to be moved over manually.

Looks like it was never in the docs to begin with. I believe the field was added as a workaround for a specific case and not really meant for much widespread use. I'm opting to not add it to the docs just for it to be deprecated in favor of a field that's already included. Let me know if you think otherwise.

**Comment by melinath** [comment]
> I'm opting to not add it to the docs just for it to be deprecated in favor of a field that's already included.

Sounds like the right call - thanks!

**Pull request merged**
