### PR TITLE
Remove dataprofileresult and dataqualityresult

### PR DESCRIPTION
**Pull request by saurabh-net**
Fix import issue for Datascan Dataprofile scans with existing jobs.
The TopN value message was incorrectly encoded as a map instead of as a array.

Removing the dataprofileresult and dataqualityresult message entirely, since it's irrelevant in the context of the Terraform lifecycle of a resource.

We'd like to keep the YAML spec as simple as possible.

Part of https://github.com/hashicorp/terraform-provider-google/issues/15448

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
dataplex: removed `data_profile_result` and `data_quality_result` from `google_dataplex_scan`
```

### CODE REVIEW

**Comment by saurabh-net** [comment]
Had an earlier discussion on this PR at https://github.com/GoogleCloudPlatform/magic-modules/pull/8578

**Comment by saurabh-net** [comment]
Additional context for this change --
Currently import Datascan fails for Profile type datascans with existing jobs created against them.
This is because of a misconfigured output-only field in the API YAML.

I originally filed a PR fixing that field, but later realized that the entire job-result field is not useful in the context of Terraform.
Hence we are looking to remove the JobResult field.

This field stores the result of the latest Job that run under a given Datascan definition. It exists primarily for UX convenience, so that users executing a GET on the Datascan, can quickly look up the status of the most recent run. This is especially handy in our UI.

-----

The current broken import behavior is blocking a customer from adopting Datacan, since they have a workflow where they use Terraform import for some internal validation.

Current error:
```
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 231 [running]:
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFieldsProfileTopNValues(...)
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2239
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFieldsProfile({0x10570ed60?, 0x1400199d5f0}, 0x104d1d0e2?, 0x7?)
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2192 +0x5c0
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFields({0x1054e01e0?, 0x1400217b200?}, 0x104d1afaa?, 0x6?)
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2161 +0x2a8
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfile({0x10570ed60?, 0x1400199d590}, 0x104d1d0e2?, 0x7?)
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2142 +0x98
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResult({0x10570ed60?, 0x1400199d560}, 0x104d37527?, 0x11?)
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2123 +0x108
github.com/hashicorp/terraform-provider-google/google/services/dataplex.resourceDataplexDatascanRead(0x14001df5e80, {0x105b9e520?, 0x14001503200})
        github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:1138 +0xf64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x105be6e38?, {0x105be6e38?, 0x14001728e70?}, 0xd?, {0x105b9e520?, 0x14001503200?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140011d9ea0, {0x105be6e38, 0x14001728e70}, 0x140005d35f0, {0x105b9e520, 0x14001503200})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000204198, {0x105be6e38?, 0x14001728d50?}, 0x140007595c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x14001407a70, 0x14001407ad0, {0x1400162ba00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140014a32c0, {0x105be6e38?, 0x14001728330?}, 0x14001d6ac00)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105b22c80?, 0x140014a32c0}, {0x105be6e38, 0x14001728330}, 0x14000333880, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140017f94a0, {0x105beefa0, 0x14001070680}, 0x14001567680, 0x1400191ba70, 0x106f6fc70, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x140017f94a0, {0x105beefa0, 0x14001070680}, 0x14001567680, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.55.0/server.go:957 +0x16c

Error: The terraform-provider-google_v4.72.0_x5 plugin crashed!
```

**Comment by c2thorn** [comment]
Hi @saurabh-net 
I've read the context and it seems fine to remove. A couple of additional things from these steps: https://googlecloudplatform.github.io/magic-modules/develop/make-a-breaking-change/#removing-a-field

1. Can you make another PR on the main branch to deprecate the fields and write an entry in the 5.0.0 upgrade guide explaining? The YAML lines needed would be `Deprecated: <deprecation message`
2. Can you [file an issue](https://github.com/hashicorp/terraform-provider-google/issues/new/choose) to track this and mark this PR as closing it?

**Comment by saurabh-net** [comment]
Created a PR for deprecating these fields first here: https://github.com/GoogleCloudPlatform/magic-modules/pull/8593

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
