### PR TITLE
A new data source for fetching the details about a particular alloydb location

### PR DESCRIPTION
**Pull request by ravisiddhu**
This PR is for https://github.com/hashicorp/terraform-provider-google/issues/13812, and PR https://github.com/GoogleCloudPlatform/magic-modules/pull/7388 is for fetching the list of locations.

A new datasource `google_alloydb_location` for fetching the details about a particular alloydb location. It receives `project` and `location` as arguments and returns the details of the specified location.

I have added documentation and tested this new data source with unit tests.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-datasource
A new datasource for fetching the details about a particular alloydb location.
```

### CODE REVIEW

**Comment by slevenick** [comment]
Can you elaborate on why a user wants to get the details of a location? Is the metadata structured in a way that will be useful?

**Comment by ravisiddhu** [comment]
yes, A location contains the following fields 
```
{
  "name": string,
  "locationId": string,
  "displayName": string,
  "labels": {
    string: string,
    ...
  },
  "metadata": {
    "@type": string,
    field1: ...,
    ...
  }
}
```
The `metadata` can contain useful service-specific data. For example the available capacity at the given location.

This is why the projects.locations.get API (GET https://alloydb.googleapis.com/v1/{name=projects/*/locations/*}) exists.

We are extending this support to terraform also, so that terraform users can also use this API to get details regarding a location.

Ref: https://cloud.google.com/alloydb/docs/reference/rest/Shared.Types/ListLocationsResponse#Location

**Comment by slevenick** [comment]
How do you envision a user would want to use this data source? I'm not seeing the importance of having this information available from within a Terraform config.

Generally we would expect a field to be useful as an input into another Terraform resource, is that the case here?

**Pull request closed without merging**
