### PR TITLE
Add support for Identity Service in beta terraform google_container_cluster

### PR DESCRIPTION
**Pull request by nstogner**
Added an object field `identity_service_config` to `google_container_cluster` (beta) with a single nested field (`enabled`) following the [structure of the Cluster API object](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.IdentityServiceConfig).

NOTE: Acceptance tests have not been run yet.

fixes https://github.com/hashicorp/terraform-provider-google/issues/10730

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: Added field `identity_service_config` to `google_container_cluster` (beta)
```

### CODE REVIEW

**Comment by nstogner** [comment]
I am planning on running acceptance tests soon. Will update PR once they are successful.

**Comment by nstogner** [comment]
Ran acceptance tests in beta terraform provider:

```sh
make testacc TEST=./google-beta TESTARGS='-run=TestAccContainerCluster_withIdentityServiceConfig'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=TestAccContainerCluster_withIdentityServiceConfig -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccContainerCluster_withIdentityServiceConfig
=== PAUSE TestAccContainerCluster_withIdentityServiceConfig
=== CONT  TestAccContainerCluster_withIdentityServiceConfig
--- PASS: TestAccContainerCluster_withIdentityServiceConfig (954.33s)
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta 957.240s
```

**Comment by shuyama1** [comment]
Hey @nstogner! Thank you so much for your contribution and apologize for the delay in reviewing it! The PR looks good to me and also I run the test separately https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/234985?buildTab=tests&status=passed and it passed. I kicked the VCR tests run just in case, as the last time run got timed out. I will approve and merge the PR when tests pass (or no failing tests are related to this PR).

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
