### PR TITLE
switch service networking connection to use create on create rather than update

### PR DESCRIPTION
**Pull request by megan07**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/10830

I'm not sure if this is a breaking change or not? It's only on create so shouldn't break current configs? But functionality will change.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
servicenetworking: fixed bug where `google_service_networking_connection` would update if a service connection of the same type already exists.
```

### CODE REVIEW

**Comment by megan07** [comment]
It looks like we can't bootstrap the networks with these tests (as is), because once the service connection is deleted in a given network, it can no longer be recreated in that network - [unless we do a force update](https://cloud.google.com/sql/docs/mysql/configure-private-services-access#change-psa-config), which would of course defeat the purpose of this PR.

I will update the other tests that use the service networking connection.

**Comment by megan07** [comment]
It seems that the errors occur when running in parallel, the clone and replica tests work for me, locally, on their own. I hate to remove the ability to run in parallel since these tests take SO long, but i'm not sure what the other option is 😬

**Review by slevenick — COMMENTED** [review]
This feels fine to me, as it only changes the create behavior and it makes it more correct.

I'm a bit worried that the SQL private networking tests are failing, as those tests were changed in this PR. Are you able to get those to pass locally?

**Comment by megan07** [comment]
@slevenick sorry, i put this off for a bit, but yea, they pass locally, individually (at least 2 of them did), but i think the problem is when they are run alongside other tests, although, here, they still failed after i removed the `t.Parallel`.  But even then, I'm not sure that's a good idea because each one takes about a half hour, I think that's adding 2 more hours to our test runs, which I don't really love the idea of.

**Comment by rileykarson** [comment]
Changing from acquire -> error if already exists probably counts as a breaking change (and needing to change our tests is a good signal of that), I think?

**Pull request closed without merging**
