### PR TITLE
add support for available_secrets to google_cloudbuild_trigger

### PR DESCRIPTION
**Pull request by cgroschupp**
add support for available_secrets to google_cloudbuild_trigger.
https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#secrets

fixes https://github.com/hashicorp/terraform-provider-google/issues/8808

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudbuild: added support for available_secrets to google_cloudbuild_trigger
```

### CODE REVIEW

**Comment by cgroschupp** [comment]
@rileykarson Can you please look over this pr.

**Comment by rileykarson** [comment]
Sorry about that, I must have accidentally dismissed the notification! I've been a bit underwater on my email.

The test passes as-is, but given that the field supports update let's add an update test as well. https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/tests/resource_cloudbuild_trigger_test.go is a good file to reference- typically the most interesting test is to start with the value set, and then remove it eg:

```
    available_secrets {
      secret_manager {
        env          = "MY_SECRET"
        version_name = "projects/myProject/secrets/mySecret/versions/latest"
      }
    }
```

to

```
# intentionally blank
```

**Comment by cgroschupp** [comment]
@rileykarson ok, thanks for the hint. is it ok to add this to `TestAccCloudBuildTrigger_basic` test?

**Comment by msuarezd** [comment]
Hi @rileykarson, any news on this? It would be really helpful for us to get this merged.

**Comment by rileykarson** [comment]
Sorry, still super behind on email!

@cgroschupp: Would you mind adding a new case? We tend to try and keep `_basic` ones to a small set of core-to-the-resource fields, and this one is pretty additive.

**Comment by franzs** [comment]
@rileykarson Sorry for bothering you. Is there any time frame we can expect a review? We are desperately waiting for this feature.
:pray:

**Comment by franzs** [comment]
@rileykarson Meanwhile the feature branch was updated to match the upstream by @cgroschupp.
Could you please have a look at the PR again?

**Comment by rileykarson** [comment]
Sorry about the delay! Code LGTM on a first pass, running tests. These are VCR tests that work by replaying old API results- we expect the new tests (and some random unrelated ones) to fail on a first pass as they aren't recorded, I need to inspect the `RECORDING` results.

/gcbrun

**Review by rileykarson — APPROVED** [review]

**Comment by franzs** [comment]
@rileykarson Thanks a lot. :confetti_ball:

**Pull request merged**
