### PR TITLE
Add VCenter Credentials to Vmwareengine

### PR DESCRIPTION
**Pull request by swamitagupta**
Added support for Vcenter credentials datasource to vmwareengine.
VCenter credentials is a child resource of a Vmwareengine Private Cloud.

As the parent PC is an expensive resource and requires node reservation, the tests are merged into PC tests following the discussion in #9533 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_vmwareengine_vcenter_credentials`
```

### CODE REVIEW

**Comment by trodge** [comment]
I'm having trouble understanding how this test is now passing in `REPLAYING` mode when it never seems to have passed in `RECORDING`. Did it perhaps pass and get recorded when [the provider crashed](https://github.com/GoogleCloudPlatform/magic-modules/pull/9572#issuecomment-1837566791)?

**Comment by swamitagupta** [comment]
> I'm having trouble understanding how this test is now passing in `REPLAYING` mode when it never seems to have passed in `RECORDING`. Did it perhaps pass and get recorded when [the provider crashed](https://github.com/GoogleCloudPlatform/magic-modules/pull/9572#issuecomment-1837566791)?

Not sure, I think it timed out [here](https://ffb62c32216331f59227f84acc951685dde243e7d4409ff4445d90a-apidata.googleusercontent.com/download/storage/v1/b/ci-vcr-logs/o/beta%2Frefs%2Fheads%2Fauto-pr-9572%2Fartifacts%2Ff0842724-5881-4193-aa0c-cbfe8f847729%2Fbuild-log%2Frecording_test.log?jk=AanfhSAws-HvW1fqzCJDgpQTkL7yqzeMtEw3sBzBjLZD8zUQkqjgpAAHWlO_amdgNyMPIxKtdEOT0zmKRkBS5QOFUlVndkF9M_ueEi56NC6f3O2T_ceUERPOOJ7Mq53iYvTl9l2osRNPup46vqHrTgucDehaKcrrLDRSLuAxGqieveT7rb7Y0VnVDe_4ubJA91Bq1ksUIR0CI77s2t1AICY1ib-OpDTb-5JrrMm3IqWYKk-wP2vDdxkqF6FimzlTpYmbI2uyah2hLjx_7GXEwg-VaxmtVajOa-GSvMtD4YMpGWz9sKER_frQoOUwxu3Z7Z_kXDbLF07Y0KLQRVvOsvqMdCMKHbdqL8ZWUvp0Kn9EG24sQWFWhLQYE408clN9OQcOnLmxxqoxfXX2hGPaE4_1eKoBJkGI91U-5rRoOrJnIrBu_J8s2ffElZnf9yl7uvONp3p2JXrgeGQEIA_07j7bqerFx55gs73b7Z2EF_5eOCKURuN-SdHQ-dVmy1Mf9k1XVmlz_kS-U1tGbC0Cgzg1qk8AIW23aDWMi5DYPe6JcAYaAOV9ktl753HrYLCnYAR5JuaONciiIq70QwMxuI4ZJeYOxmLI79HHlGcrUH5V4B3U4qRndQU6MiulyPwDwTud0PzdEd2HRbzknrDM-28A4wn8J90hacCBJPop64neiPWsMvnpvbtD7bWLWgfJqanqgN2zBqzAy3orWXOUa6o7fWr_drvOKoFhnVaCqpv8Jc59EE7UVJ6kMZcpL0zHAjKb-flnI6CVAUr3RqcMuJIIcujdUvxXpGYNcEJHUGB2TNEw5kabp7oVgxPbLl3CVNQssJRnsylJCTdpdlR3-meanzP4Nyjg6fRMoaAkB3T3zxuavuvMpaextDnCicx2SJwfUSP9gOHlxmKZHHuYoTm_TIugCAol-Y8On1KMmfWyW0-Twzgwa3QUvIQDXx5DeB8_M2UZJMLy_f5R0_K5_m4zsttSt7FcXdNhAr7wvukKAYsNnw9Tf60Xv9tys3FhCD4aQJJQf3BEzTJvKot3nyBgutOLk5BTmsrXCvHTX6NVNopQUHM_9pLR963FLsgpFeIio_3o76gtEYhs01_yM3UmIhLBG95ufTDkpNhkCeUvgWE6_dhogfrxPyT3y2K0s-xcb_KyQorhq0rjMxvxp7Yt2kRN-USXfIAJcsLrpfeZ0Ahkddyt4apUu3FhyJk3CeEIIR5luhwOBaZ-rXU&isca=1#:~:text=panic%3A%20test%20timed%20out%20after%204h0m0s).

**Comment by trodge** [comment]
Ah, it looks like the test is now skipped in VCR. Is it passing locally?

**Comment by swamitagupta** [comment]
> Ah, it looks like the test is now skipped in VCR. Is it passing locally?

Yes all the tests are passing locally.

**Pull request merged**
