### PR TITLE
dns/api.yaml: add missing record types

### PR DESCRIPTION
**Pull request by rjw57**
Update the list of valid DNS record types to match the list documented at https://cloud.google.com/dns/docs/records.
In particular this was hurting people who were previously deploying DNSSEC key records via terraform.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/8897

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
dns: added missing record types to `google_dns_record_set` resource
```

### CODE REVIEW

**Comment by rjw57** [comment]
> If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know.

Due to internal funding procedures it would be a fiddle to set up a Google project which could create real resources.

**Comment by rjw57** [comment]
> Generated Terraform, and ran make test and make lint to ensure it passes unit and linter tests.

I get a lot of go fmt problems apparently unrelated to this PR so I suspect I may be doing this wrong.

```
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./google/resource_cloud_asset_folder_feed.go
./google/resource_dialogflow_intent_test.go
./google/resource_kms_secret_ciphertext.go
./google/resource_identity_platform_oauth_idp_config_generated_test.go
./google/resource_billing_budget_generated_test.go
./google/resource_os_config_patch_deployment_sweeper_test.go
./google/iam_pubsub_topic.go
./google/resource_compute_packet_mirroring_sweeper_test.go
./google/resource_sql_source_representation_instance_generated_test.go
./google/resource_notebooks_environment.go
./google/resource_compute_global_network_endpoint_group_sweeper_test.go
./google/resource_compute_autoscaler_sweeper_test.go
./google/resource_compute_router_nat.go
./google/resource_access_approval_folder_settings.go
./google/resource_cloud_asset_folder_feed_generated_test.go
./google/resource_compute_per_instance_config.go
./google/resource_monitoring_group_sweeper_test.go
./google/iam_tags_tag_key.go
./google/resource_redis_instance_generated_test.go
./google/resource_bigquery_data_transfer_config.go
./google/resource_kms_crypto_key.go
./google/resource_billing_budget.go
./google/resource_spanner_database_generated_test.go
./google/resource_os_login_ssh_public_key.go
./google/resource_compute_autoscaler.go
./google/iam_binary_authorization_attestor.go
./google/iam_cloud_run_service_generated_test.go
./google/resource_pubsub_topic_sweeper_test.go
./google/resource_compute_https_health_check_generated_test.go
./google/resource_game_services_realm_generated_test.go
./google/resource_compute_reservation_generated_test.go
./google/resource_notebooks_instance_sweeper_test.go
./google/resource_compute_target_ssl_proxy_sweeper_test.go
./google/resource_cloud_scheduler_job_sweeper_test.go
./google/resource_apigee_instance_attachment_generated_test.go
./google/resource_active_directory_domain_sweeper_test.go
./google/notebooks_operation.go
./google/resource_compute_health_check_test.go
./google/resource_game_services_realm_sweeper_test.go
./google/resource_apigee_organization_generated_test.go
./google/resource_dns_record_set_test.go
./google/resource_access_context_manager_gcp_user_access_binding_sweeper_test.go
./google/resource_compute_autoscaler_test.go
./google/config.go
./google/resource_cloud_build_trigger_generated_test.go
./google/iam_healthcare_consent_store.go
./google/resource_cloud_run_domain_mapping_generated_test.go
./google/resource_cloud_tasks_queue_generated_test.go
./google/resource_dialogflow_entity_type_test.go
./google/transport.go
./google/resource_cloud_scheduler_job_generated_test.go
./google/resource_dns_managed_zone_generated_test.go
./google/resource_deployment_manager_deployment_sweeper_test.go
./google/deployment_manager_operation.go
./google/resource_dns_resource_dns_record_set.go
./google/resource_google_service_account_iam_test.go
./google/resource_apigee_envgroup_sweeper_test.go
./google/resource_secret_manager_secret_version_test.go
./google/resource_identity_platform_oauth_idp_config_sweeper_test.go
./google/resource_dns_managed_zone_test.go
./google/resource_compute_node_group.go
./google/iam_data_catalog_tag_template_generated_test.go
./google/resource_iap_client_generated_test.go
./google/resource_big_query_dataset_access.go
./google/resource_billing_budget_sweeper_test.go
./google/resource_compute_backend_service_generated_test.go
./google/resource_compute_target_grpc_proxy_generated_test.go
./google/resource_compute_target_tcp_proxy.go
./google/resource_compute_target_grpc_proxy.go
./google/provider_test.go
./google/resource_tpu_node_generated_test.go
./google/resource_compute_disk_generated_test.go
./google/resource_compute_region_health_check.go
./google/resource_compute_backend_bucket_sweeper_test.go
./google/resource_app_engine_service_split_traffic.go
./google/resource_access_context_manager_access_policy.go
./google/resource_active_directory_domain_generated_test.go
./google/iam_source_repo_repository_generated_test.go
./google/resource_container_node_pool.go
./google/resource_cloud_asset_organization_feed_generated_test.go
./google/resource_sql_database_generated_test.go
./google/resource_pubsub_lite_topic_sweeper_test.go
./google/resource_cloud_identity_group_membership_generated_test.go
./google/resource_binaryauthorization_policy_test.go
./google/resource_compute_https_health_check_sweeper_test.go
./google/resource_sql_database_instance.go
./google/resource_firestore_document_generated_test.go
./google/resource_container_analysis_occurrence_sweeper_test.go
./google/resource_compute_vpn_gateway.go
./google/resource_pubsub_lite_topic.go
./google/iam_compute_subnetwork_generated_test.go
./google/resource_network_management_connectivity_test_resource.go
./google/resource_firestore_index.go
./google/iam_iap_app_engine_version_generated_test.go
./google/resource_cloud_build_trigger_sweeper_test.go
./google/resource_monitoring_notification_channel_sweeper_test.go
./google/resource_sql_database_instance_test.go
./google/resource_apigee_environment_sweeper_test.go
./google/resource_apigee_envgroup_attachment.go
./google/resource_dialogflow_intent_generated_test.go
./google/resource_identity_platform_tenant_oauth_idp_config_generated_test.go
./google/resource_compute_image.go
./google/resource_storage_hmac_key.go
./google/resource_identity_platform_inbound_saml_config_sweeper_test.go
./google/resource_identity_platform_tenant_inbound_saml_config.go
./google/resource_pubsub_subscription.go
./google/resource_cloud_run_service_sweeper_test.go
./google/resource_compute_target_grpc_proxy_sweeper_test.go
./google/iam_compute_disk.go
./google/resource_compute_disk.go
./google/resource_monitoring_uptime_check_config_sweeper_test.go
./google/iam_pubsub_topic_generated_test.go
./google/resource_apigee_envgroup_attachment_generated_test.go
./google/resource_compute_network_endpoint_test.go
./google/resource_compute_global_network_endpoint_group_generated_test.go
./google/resource_logging_metric_sweeper_test.go
./google/resource_compute_instance_template_test.go
./google/resource_compute_http_health_check_sweeper_test.go
./google/resource_sql_database.go
./google/resource_compute_resource_policy_generated_test.go
./google/resource_data_catalog_tag_template.go
./google/resource_kms_key_ring.go
./google/resource_bigquery_reservation_reservation.go
./google/resource_compute_global_address_generated_test.go
./google/resource_compute_resource_policy.go
./google/iam_healthcare_consent_store_generated_test.go
./google/resource_monitoring_group.go
./google/resource_compute_network_generated_test.go
./google/resource_compute_global_network_endpoint_test.go
./google/resource_compute_region_health_check_test.go
./google/resource_identity_platform_inbound_saml_config.go
./google/resource_compute_region_health_check_generated_test.go
./google/resource_compute_target_tcp_proxy_generated_test.go
./google/resource_source_repo_repository_sweeper_test.go
./google/resource_monitoring_metric_descriptor_generated_test.go
./google/resource_tags_tag_binding.go
./google/resource_compute_interconnect_attachment.go
./google/resource_cloud_run_domain_mapping.go
./google/resource_secret_manager_secret_sweeper_test.go
./google/resource_compute_url_map_generated_test.go
./google/iam_iap_web_backend_service_generated_test.go
./google/resource_apigee_organization_sweeper_test.go
./google/resource_data_loss_prevention_inspect_template_sweeper_test.go
./google/resource_binaryauthorization_attestor_test.go
./google/resource_compute_address_generated_test.go
./google/resource_access_context_manager_service_perimeter_resource.go
./google/resource_cloud_iot_device_sweeper_test.go
./google/resource_compute_global_address_sweeper_test.go
./google/resource_apigee_instance_sweeper_test.go
./google/resource_app_engine_firewall_rule_generated_test.go
./google/resource_filestore_instance.go
./google/resource_container_node_pool_test.go
./google/resource_apigee_instance_attachment_sweeper_test.go
./google/iam_compute_instance.go
./google/resource_compute_firewall_sweeper_test.go
./google/tpu_operation.go
./google/resource_compute_route_sweeper_test.go
./google/resource_manager_operation.go
./google/resource_game_services_game_server_cluster.go
./google/resource_compute_resource_policy_sweeper_test.go
./google/data_source_secret_manager_secret_version_test.go
./google/resource_compute_target_http_proxy_generated_test.go
./google/resource_resource_manager_lien.go
./google/resource_data_loss_prevention_deidentify_template.go
./google/iam_iap_web_type_app_engine.go
./google/resource_data_loss_prevention_stored_info_type.go
./google/resource_logging_metric.go
./google/resource_os_login_ssh_public_key_sweeper_test.go
./google/resource_healthcare_dataset_generated_test.go
./google/iam_cloud_functions_cloud_function_generated_test.go
./google/resource_compute_router_bgp_peer.go
./google/resource_compute_global_forwarding_rule_generated_test.go
./google/resource_tags_tag_key.go
./google/tags_operation.go
./google/resource_compute_vpn_gateway_generated_test.go
./google/resource_spanner_instance_generated_test.go
./google/resource_tpu_node_sweeper_test.go
./google/resource_compute_region_network_endpoint_group_generated_test.go
./google/resource_compute_snapshot_generated_test.go
./google/resource_app_engine_domain_mapping.go
./google/resource_bigquery_reservation_reservation_sweeper_test.go
./google/resource_container_analysis_note_generated_test.go
./google/common_diff_suppress.go
./google/resource_compute_external_vpn_gateway_sweeper_test.go
./google/resource_identity_platform_tenant_inbound_saml_config_generated_test.go
./google/resource_cloud_run_domain_mapping_sweeper_test.go
./google/resource_cloud_asset_project_feed_sweeper_test.go
./google/resource_iap_client.go
./google/iam_runtime_config_config_generated_test.go
./google/resource_cloud_asset_folder_feed_sweeper_test.go
./google/iam_data_catalog_tag_template.go
./google/resource_compute_instance_group_named_port_sweeper_test.go
./google/resource_compute_region_autoscaler_sweeper_test.go
./google/resource_compute_vpn_tunnel_generated_test.go
./google/resource_compute_instance_group_named_port.go
./google/resource_compute_reservation.go
./google/resource_healthcare_dicom_store.go
./google/resource_monitoring_alert_policy_sweeper_test.go
./google/resource_data_loss_prevention_deidentify_template_sweeper_test.go
./google/resource_tags_tag_key_sweeper_test.go
./google/resource_compute_subnetwork.go
./google/resource_pubsub_topic_generated_test.go
./google/resource_data_catalog_tag_template_generated_test.go
./google/resource_workflows_workflow_sweeper_test.go
./google/resource_dataproc_cluster_test.go
./google/resource_compute_managed_ssl_certificate_generated_test.go
./google/resource_kms_crypto_key_iam_test.go
./google/resource_bigquery_reservation_reservation_generated_test.go
./google/resource_healthcare_consent_store.go
./google/resource_compute_region_ssl_certificate.go
./google/resource_notebooks_environment_generated_test.go
./google/resource_compute_target_instance_sweeper_test.go
./google/resource_compute_backend_service_sweeper_test.go
./google/resource_compute_image_sweeper_test.go
./google/resource_identity_platform_default_supported_idp_config.go
./google/resource_notebooks_environment_sweeper_test.go
./google/iam_big_query_table_generated_test.go
./google/resource_game_services_game_server_deployment_rollout_sweeper_test.go
./google/resource_compute_image_generated_test.go
./google/datastore_operation.go
./google/resource_compute_global_forwarding_rule.go
./google/resource_data_loss_prevention_stored_info_type_sweeper_test.go
./google/resource_game_services_game_server_deployment_rollout_generated_test.go
./google/resource_app_engine_standard_app_version.go
./google/resource_compute_disk_resource_policy_attachment.go
./google/resource_compute_backend_service_signed_url_key_sweeper_test.go
./google/resource_compute_target_ssl_proxy.go
./google/iam_compute_image_generated_test.go
./google/resource_healthcare_hl7_v2_store.go
./google/iam_cloud_functions_cloud_function.go
./google/iam_iap_tunnel_instance_generated_test.go
./google/dataproc_cluster_operation.go
./google/resource_compute_region_disk_generated_test.go
./google/resource_compute_router_bgp_peer_sweeper_test.go
./google/resource_access_approval_project_settings.go
./google/resource_identity_platform_oauth_idp_config.go
./google/resource_compute_network_endpoint_group.go
./google/resource_binary_authorization_attestor.go
./google/iam_iap_web_generated_test.go
./google/resource_data_catalog_entry_sweeper_test.go
./google/resource_compute_subnetwork_generated_test.go
./google/resource_dataproc_autoscaling_policy_generated_test.go
./google/resource_compute_firewall_generated_test.go
./google/iam_iap_app_engine_service.go
./google/iam_compute_region_disk_generated_test.go
./google/resource_apigee_envgroup.go
./google/resource_bigtable_app_profile_generated_test.go
./google/resource_notebooks_instance_generated_test.go
./google/iam_big_query_table.go
./google/resource_apigee_instance_attachment.go
./google/resource_secret_manager_secret.go
./google/resource_data_loss_prevention_stored_info_type_generated_test.go
./google/resource_compute_vpn_tunnel.go
./google/resource_monitoring_notification_channel_generated_test.go
./google/resource_filestore_instance_sweeper_test.go
./google/iam_dataproc_job.go
./google/resource_identity_platform_tenant_oauth_idp_config.go
./google/vpc_access_operation.go
./google/spanner_operation.go
./google/resource_compute_backend_service_signed_url_key.go
./google/resource_compute_region_backend_service_test.go
./google/resource_monitoring_metric_descriptor.go
./google/resource_access_context_manager_access_levels.go
./google/resource_firestore_document.go
./google/resource_compute_node_template_sweeper_test.go
./google/resource_apigee_instance_generated_test.go
./google/resource_iam_binding.go
./google/resource_binary_authorization_policy.go
./google/resource_datastore_index_generated_test.go
./google/iam_iap_web_backend_service.go
./google/resource_compute_node_template_generated_test.go
./google/resource_cloud_identity_group_membership_test.go
./google/resource_compute_route.go
./google/resource_big_query_dataset.go
./google/resource_compute_network_sweeper_test.go
./google/resource_compute_backend_service.go
./google/iam_tags_tag_value.go
./google/resource_big_query_routine_generated_test.go
./google/resource_binary_authorization_attestor_generated_test.go
./google/resource_pubsub_subscription_generated_test.go
./google/resource_data_catalog_tag.go
./google/resource_redis_instance.go
./google/resource_source_repo_repository_generated_test.go
./google/iam_service_management_service.go
./google/game_services_operation.go
./google/iam_storage_bucket_generated_test.go
./google/resource_container_analysis_note.go
./google/resource_cloud_iot_device_registry_sweeper_test.go
./google/resource_compute_target_https_proxy_generated_test.go
./google/resource_compute_target_https_proxy.go
./google/resource_compute_network_endpoint.go
./google/node_config.go
./google/resource_compute_address_sweeper_test.go
./google/resource_data_loss_prevention_job_trigger_sweeper_test.go
./google/resource_compute_global_network_endpoint_group.go
./google/firestore_operation.go
./google/resource_compute_instance_group_named_port_generated_test.go
./google/resource_compute_managed_ssl_certificate.go
./google/resource_container_analysis_occurrence.go
./google/resource_access_context_manager_service_perimeter.go
./google/resource_apigee_environment_generated_test.go
./google/resource_sql_source_representation_instance.go
./google/iam_notebooks_instance.go
./google/resource_compute_security_policy_test.go
./google/resource_data_catalog_tag_sweeper_test.go
./google/resource_game_services_game_server_deployment_generated_test.go
./google/resource_healthcare_dicom_store_generated_test.go
./google/resource_compute_node_template.go
./google/resource_app_engine_domain_mapping_sweeper_test.go
./google/resource_workflows_workflow.go
./google/resource_identity_platform_tenant_sweeper_test.go
./google/resource_composer_environment.go
./google/resource_compute_url_map.go
./google/resource_notebooks_location.go
./google/resource_compute_region_autoscaler_generated_test.go
./google/iam_cloud_run_service.go
./google/ml_engine_operation.go
./google/resource_compute_snapshot_sweeper_test.go
./google/resource_compute_network_endpoint_group_generated_test.go
./google/resource_identity_platform_tenant_default_supported_idp_config_generated_test.go
./google/resource_access_context_manager_access_level.go
./google/resource_cloud_run_service.go
./google/resource_data_catalog_entry_generated_test.go
./google/resource_cloud_iot_device_registry_generated_test.go
./google/resource_storage_object_access_control_generated_test.go
./google/resource_compute_ha_vpn_gateway_sweeper_test.go
./google/resource_compute_ssl_certificate_sweeper_test.go
./google/resource_tpu_node.go
./google/iam_data_catalog_entry_group.go
./google/resource_compute_ssl_policy_generated_test.go
./google/resource_compute_target_tcp_proxy_sweeper_test.go
./google/resource_cloudfunctions_function_test.go
./google/iam_storage_bucket.go
./google/resource_compute_external_vpn_gateway_generated_test.go
./google/filestore_operation.go
./google/resource_dataproc_job_test.go
./google/resource_big_query_job.go
./google/iam_compute_instance_generated_test.go
./google/resource_data_catalog_entry_group_generated_test.go
./google/resource_secret_manager_secret_version.go
./google/resource_game_services_game_server_config.go
./google/resource_big_query_dataset_generated_test.go
./google/iam_service_management_service_generated_test.go
./google/resource_compute_health_check_generated_test.go
./google/resource_dialogflow_agent.go
./google/iam_notebooks_instance_generated_test.go
./google/access_context_manager_operation.go
./google/resource_cloud_identity_group_generated_test.go
./google/resource_dataproc_autoscaling_policy_sweeper_test.go
./google/iam_secret_manager_secret.go
./google/resource_cloud_iot_device.go
./google/resource_app_engine_firewall_rule.go
./google/resource_cloud_scheduler_job.go
./google/resource_monitoring_slo_sweeper_test.go
./google/resource_dns_managed_zone.go
./google/resource_data_catalog_tag_generated_test.go
./google/resource_os_login_ssh_public_key_generated_test.go
./google/resource_compute_global_forwarding_rule_test.go
./google/resource_game_services_game_server_cluster_generated_test.go
./google/resource_compute_url_map_sweeper_test.go
./google/resource_monitoring_service.go
./google/resource_cloud_asset_organization_feed.go
./google/resource_pubsub_subscription_sweeper_test.go
./google/resource_compute_forwarding_rule_generated_test.go
./google/resource_cloud_run_service_generated_test.go
./google/data_source_google_container_engine_versions.go
./google/active_directory_operation.go
./google/resource_redis_instance_test.go
./google/resource_iap_brand.go
./google/resource_compute_target_http_proxy_sweeper_test.go
./google/resource_cloud_asset_project_feed_generated_test.go
./google/resource_compute_packet_mirroring_generated_test.go
./google/compute_operation.go
./google/resource_compute_http_health_check_generated_test.go
./google/resource_healthcare_dataset.go
./google/resource_access_context_manager_access_policy_test.go
./google/iam_iap_tunnel_instance.go
./google/resource_cloud_iot_device_registry.go
./google/resource_composer_environment_test.go
./google/resource_compute_managed_ssl_certificate_sweeper_test.go
./google/resource_compute_router_sweeper_test.go
./google/resource_compute_global_network_endpoint.go
./google/resource_app_engine_flexible_app_version_generated_test.go
./google/resource_apigee_envgroup_generated_test.go
./google/resource_compute_subnetwork_sweeper_test.go
./google/resource_identity_platform_default_supported_idp_config_sweeper_test.go
./google/provider.go
./google/resource_monitoring_notification_channel.go
./google/resource_data_loss_prevention_inspect_template.go
./google/resource_monitoring_uptime_check_config.go
./google/resource_os_config_patch_deployment_generated_test.go
./google/resource_pubsub_lite_subscription.go
./google/iam.go
./google/iam_compute_disk_generated_test.go
./google/resource_compute_network_peering_routes_config_generated_test.go
./google/iam_iap_web_type_compute.go
./google/resource_compute_ha_vpn_gateway_generated_test.go
./google/resource_compute_region_autoscaler.go
./google/resource_kms_key_ring_import_job.go
./google/resource_spanner_database.go
./google/data_source_google_compute_resource_policy_test.go
./google/resource_compute_region_network_endpoint_group.go
./google/resource_healthcare_fhir_store.go
./google/resource_firestore_document_sweeper_test.go
./google/resource_monitoring_service_generated_test.go
./google/resource_game_services_game_server_deployment_sweeper_test.go
./google/resource_app_engine_application_url_dispatch_rules_generated_test.go
./google/resource_compute_external_vpn_gateway.go
./google/resource_compute_region_target_https_proxy.go
./google/iam_secret_manager_secret_generated_test.go
./google/iam_iap_tunnel_generated_test.go
./google/resource_dialogflow_intent.go
./google/resource_compute_route_generated_test.go
./google/resource_apigee_instance.go
./google/resource_compute_forwarding_rule_sweeper_test.go
./google/resource_cloud_asset_organization_feed_sweeper_test.go
./google/resource_compute_region_target_http_proxy_sweeper_test.go
./google/resource_filestore_instance_generated_test.go
./google/resource_game_services_game_server_cluster_sweeper_test.go
./google/resource_healthcare_consent_store_generated_test.go
./google/resource_cloud_identity_group_membership.go
./google/resource_compute_reservation_sweeper_test.go
./google/resource_compute_region_autoscaler_test.go
./google/resource_compute_region_network_endpoint_group_sweeper_test.go
./google/resource_compute_snapshot.go
./google/iam_compute_region_disk.go
./google/resource_redis_instance_sweeper_test.go
./google/resource_app_engine_standard_app_version_generated_test.go
./google/resource_monitoring_uptime_check_config_generated_test.go
./google/resource_data_loss_prevention_deidentify_template_generated_test.go
./google/resource_notebooks_location_sweeper_test.go
./google/resource_notebooks_instance.go
./google/data_source_google_iam_policy.go
./google/resource_compute_backend_bucket_generated_test.go
./google/resource_access_context_manager_gcp_user_access_binding.go
./google/resource_compute_region_target_http_proxy_generated_test.go
./google/resource_dialogflow_agent_generated_test.go
./google/resource_data_catalog_entry_group.go
./google/resource_compute_firewall.go
./google/resource_apigee_organization.go
./google/resource_tags_tag_value.go
./google/resource_vpc_access_connector_sweeper_test.go
./google/resource_app_engine_flexible_app_version.go
./google/resource_pubsub_topic.go
./google/resource_pubsub_lite_subscription_generated_test.go
./google/resource_compute_autoscaler_generated_test.go
./google/resource_compute_region_disk.go
./google/resource_vpc_access_connector.go
./google/resource_bigquery_data_transfer_config_sweeper_test.go
./google/resource_source_repo_repository.go
./google/resource_compute_vpn_tunnel_sweeper_test.go
./google/resource_game_services_realm.go
./google/resource_compute_ssl_policy_sweeper_test.go
./google/resource_container_analysis_note_sweeper_test.go
./google/resource_compute_region_target_https_proxy_sweeper_test.go
./google/resource_compute_interconnect_attachment_generated_test.go
./google/resource_monitoring_metric_descriptor_sweeper_test.go
./google/resource_compute_region_url_map_generated_test.go
./google/resource_pubsub_lite_subscription_sweeper_test.go
./google/resource_compute_network.go
./google/resource_spanner_instance.go
./google/resource_data_loss_prevention_job_trigger_generated_test.go
./google/resource_network_management_connectivity_test_resource_generated_test.go
./google/resource_compute_vpn_gateway_sweeper_test.go
./google/resource_game_services_game_server_config_sweeper_test.go
./google/resource_game_services_game_server_deployment.go
./google/resource_vpc_access_connector_generated_test.go
./google/resource_ml_engine_model_sweeper_test.go
./google/resource_cloud_asset_project_feed.go
./google/resource_compute_global_forwarding_rule_sweeper_test.go
./google/resource_storage_bucket_access_control_generated_test.go
./google/resource_compute_disk_test.go
./google/resource_compute_region_disk_resource_policy_attachment.go
./google/resource_healthcare_fhir_store_generated_test.go
./google/iam_iap_app_engine_version.go
./google/resource_sql_source_representation_instance_sweeper_test.go
./google/resource_data_catalog_entry_group_sweeper_test.go
./google/resource_healthcare_dataset_sweeper_test.go
./google/resource_storage_hmac_key_generated_test.go
./google/resource_compute_https_health_check.go
./google/resource_compute_ssl_certificate.go
./google/resource_monitoring_service_sweeper_test.go
./google/resource_data_catalog_entry.go
./google/resource_logging_metric_generated_test.go
./google/resource_compute_region_target_http_proxy.go
./google/service_usage_operation.go
./google/resource_app_engine_application_url_dispatch_rules.go
./google/resource_access_context_manager_service_perimeters.go
./google/resource_compute_health_check_sweeper_test.go
./google/resource_healthcare_consent_store_sweeper_test.go
./google/resource_spanner_instance_sweeper_test.go
./google/resource_compute_region_ssl_certificate_sweeper_test.go
./google/resource_active_directory_domain_trust.go
./google/resource_compute_region_url_map_sweeper_test.go
./google/iam_binary_authorization_attestor_generated_test.go
./google/resource_compute_router_nat_test.go
./google/resource_cloud_tasks_queue.go
./google/iam_iap_app_engine_service_generated_test.go
./google/resource_apigee_environment.go
./google/resource_storage_default_object_access_control.go
./google/redis_operation.go
./google/iam_iap_tunnel.go
./google/resource_compute_region_health_check_sweeper_test.go
./google/resource_compute_region_backend_service.go
./google/resource_compute_router_generated_test.go
./google/resource_cloud_identity_group.go
./google/resource_tags_tag_value_sweeper_test.go
./google/workflows_operation.go
./google/resource_dialogflow_entity_type.go
./google/resource_compute_ssl_policy.go
./google/resource_container_cluster.go
./google/resource_container_cluster_test.go
./google/iam_iap_web.go
./google/resource_identity_platform_tenant_default_supported_idp_config.go
./google/resource_dns_policy.go
./google/resource_cloud_tasks_queue_sweeper_test.go
./google/resource_cloud_build_trigger.go
./google/network_management_operation.go
./google/resource_active_directory_domain.go
./google/resource_compute_target_ssl_proxy_generated_test.go
./google/resource_compute_ssl_certificate_generated_test.go
./google/iam_iap_web_type_app_engine_generated_test.go
./google/resource_storage_object_access_control.go
./google/resource_compute_region_backend_service_sweeper_test.go
./google/resource_compute_target_https_proxy_sweeper_test.go
./google/resource_access_context_manager_access_level_condition.go
./google/iam_data_catalog_entry_group_generated_test.go
./google/apigee_operation.go
./google/resource_compute_region_ssl_certificate_generated_test.go
./google/resource_monitoring_group_generated_test.go
./google/resource_compute_network_peering_routes_config.go
./google/iam_compute_image.go
./google/resource_compute_node_group_generated_test.go
./google/resource_tags_tag_binding_sweeper_test.go
./google/resource_pubsub_lite_topic_generated_test.go
./google/resource_compute_target_instance.go
./google/resource_compute_network_endpoint_group_sweeper_test.go
./google/resource_compute_router.go
./google/resource_ml_engine_model_generated_test.go
./google/resource_ml_engine_model.go
./google/resource_compute_region_backend_service_generated_test.go
./google/resource_access_approval_organization_settings.go
./google/iam_runtime_config_config.go
./google/resource_identity_platform_tenant_inbound_saml_config_sweeper_test.go
./google/resource_compute_region_url_map.go
./google/resource_identity_platform_tenant.go
./google/resource_compute_url_map_test.go
./google/resource_compute_instance_template.go
./google/resource_compute_region_target_https_proxy_generated_test.go
./google/resource_compute_address.go
./google/resource_data_loss_prevention_job_trigger.go
./google/resource_identity_platform_inbound_saml_config_generated_test.go
./google/resource_bigtable_app_profile.go
./google/resource_compute_backend_bucket.go
./google/resource_firestore_index_generated_test.go
./google/resource_big_query_routine.go
./google/resource_network_management_connectivity_test_resource_sweeper_test.go
./google/resource_compute_target_instance_generated_test.go
./google/resource_game_services_game_server_deployment_rollout.go
./google/resource_dns_policy_generated_test.go
./google/resource_kms_key_ring_iam_test.go
./google/resource_data_loss_prevention_inspect_template_generated_test.go
./google/resource_compute_forwarding_rule.go
./google/resource_compute_global_address.go
./google/resource_compute_region_per_instance_config.go
./google/resource_compute_http_health_check.go
./google/iam_iap_web_type_compute_generated_test.go
./google/resource_compute_backend_bucket_signed_url_key_sweeper_test.go
./google/resource_compute_backend_service_test.go
./google/resource_big_query_job_generated_test.go
./google/resource_compute_packet_mirroring.go
./google/resource_compute_region_disk_resource_policy_attachment_generated_test.go
./google/resource_identity_platform_tenant_generated_test.go
./google/resource_cloud_iot_device_generated_test.go
./google/resource_game_services_game_server_config_generated_test.go
./google/resource_dataproc_cluster.go
./google/resource_dns_resource_dns_record_set_sweeper_test.go
./google/resource_workflows_workflow_generated_test.go
./google/resource_storage_bucket_access_control.go
./google/resource_kms_key_ring_import_job_sweeper_test.go
./google/resource_compute_backend_bucket_signed_url_key.go
./google/resource_compute_router_nat_sweeper_test.go
./google/resource_secret_manager_secret_version_generated_test.go
./google/resource_healthcare_hl7_v2_store_generated_test.go
./google/iam_compute_subnetwork.go
./google/resource_app_engine_domain_mapping_generated_test.go
./google/resource_monitoring_slo_generated_test.go
./google/resource_app_engine_service_split_traffic_generated_test.go
./google/resource_compute_ha_vpn_gateway.go
./google/resource_monitoring_alert_policy.go
./google/resource_big_query_routine_sweeper_test.go
./google/compute_instance_helpers.go
./google/resource_security_center_source.go
./google/resource_compute_health_check.go
./google/resource_compute_node_group_sweeper_test.go
./google/resource_dataproc_autoscaling_policy.go
./google/resource_datastore_index.go
./google/resource_os_config_patch_deployment.go
./google/resource_monitoring_slo.go
./google/resource_binary_authorization_attestor_sweeper_test.go
./google/resource_compute_disk_resource_policy_attachment_generated_test.go
./google/resource_storage_default_object_access_control_generated_test.go
./google/resource_secret_manager_secret_generated_test.go
./google/resource_compute_target_http_proxy.go
./google/resource_deployment_manager_deployment.go
./google/iam_source_repo_repository.go
./google/resource_identity_platform_tenant_oauth_idp_config_sweeper_test.go
You can use the command: `make fmt` to reformat code.
make: *** [GNUmakefile:23: fmtcheck] Error 1
```

**Comment by rjw57** [comment]
> > Generated Terraform, and ran make test and make lint to ensure it passes unit and linter tests.
> 
> I get a lot of go fmt problems apparently unrelated to this PR so I suspect I may be doing this wrong.

But once I run `make fmt`, `make` fails, again due to reasons which appear unrelated to the PR:

```
go install
# github.com/hashicorp/terraform-provider-google/google
google/compute_operation.go:11:2: imported and not used: "google.golang.org/api/compute/v0.beta" as computeBeta
google/config.go:20:2: imported and not used: "golang.org/x/oauth2/jwt"
google/config.go:33:2: composer redeclared as imported package name
        previous declaration at google/config.go:32:2
google/data_source_secret_manager_secret_version.go:7:2: imported and not used: "time"
google/deployment_manager_operation.go:8:2: imported and not used: "google.golang.org/api/compute/v0.beta" as computeBeta
google/iam_big_query_table.go:18:2: imported and not used: "log"
google/iam_big_query_table.go:19:2: imported and not used: "regexp"
google/iam_big_query_table.go:20:2: imported and not used: "strconv"
google/iam_big_query_table.go:21:2: imported and not used: "strings"
google/iam_binary_authorization_attestor.go:18:2: imported and not used: "log"
google/iam_binary_authorization_attestor.go:18:2: too many errors
make: *** [GNUmakefile:8: build] Error 2
```

**Comment by melinath** [comment]
There were a couple of build issues yesterday that were unrelated to this PR so let's do a new /gcbrun

**Review by melinath — APPROVED** [review]
LGTM in principle assuming tests pass :-)

**Pull request merged**
