### PR TITLE
Update mutex on google_apigee_instance_attachment to lock globally

### PR DESCRIPTION
**Pull request by xuchenma**
This PR updates the mutex on google_apigee_instance_attachment to create a global lock.
It solves https://github.com/hashicorp/terraform-provider-google/issues/11445.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
Update mutex on google_apigee_instance_attachment to lock on org_id.
```

### CODE REVIEW

**Comment by xuchenma** [comment]
I tested locally and it has worked. I cannot add a test case as in https://github.com/hashicorp/terraform-provider-google/issues/11445 because only paid ApigeeOrgs can create multiple instances, and paid ApigeeOrgs cannot be automatically created/deleted in CI/CD tests.

**Comment by melinath** [comment]
@xuchenma I don't think this is going to do exactly what you want it to. The mutex will be filled in by getting the `{{org_id}}` field from the terraform resource - but [`google_apigee_instance_attachment`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_instance_attachment) doesn't have that field. That means the mutex will end up being on an empty string. This does resolve the issue that you identified, but it does it by creating a global lock on instance attachments - not a lock per organization.

Unfortunately there may not be a better solution than a global lock, since the terraform resource only has access to organization and environment.

**Comment by xuchenma** [comment]
I see, thanks for the explanation! I updated it to lock on a hardcoded string. Tested locally, it worked for me.

**Review by melinath — CHANGES_REQUESTED** [review]
it would be good to add the resource name to the global mutex name; for now I think this is the only one but we should still namespace it to be future-proof.

**Comment by xuchenma** [comment]
Got it, updated!

**Review by melinath — APPROVED** [review]

**Pull request merged**
