### PR TITLE
Support for user_labels in google_monitoring_slo

### PR DESCRIPTION
**Pull request by etruong42**
Support for user_labels in google_monitoring_slo

part of https://github.com/hashicorp/terraform-provider-google/issues/11204

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
~~- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.~~
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
monitoring: support for user_labels in `google_monitoring_slo`

```

### CODE REVIEW

**Comment by etruong42** [comment]
The link to the section https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools doesn't seem to exist anymore.

Running

`$ TF_LOG=TRACE make testacc TEST=./google TESTARGS='-run=testAccMonitoringSlo_basic'`

Outputs `testing: warning: no tests to run`

**Comment by etruong42** [comment]
I think I need help understanding the VCR-test errors. The creation of the service/SLO objects report success. Then their deletion reports success. The only error I see is trying to retrieve the object after the logs indicate that they have been deleted. Perhaps I am missing something because I would expect the test to pass given those logs.

**Review by c2thorn — CHANGES_REQUESTED** [review]
The build log shows the following error: 
```
    provider_test.go:309: Step 3/4 error: After applying this test step, the plan was not empty.
...
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # google_monitoring_slo.primary will be updated in-place
          ~ resource "google_monitoring_slo" "primary" {
...
              ~ user_labels         = {
                  - "my_key"       = "my_value" -> null
                  - "my_other_key" = "my_other_value" -> null
                }
...
            }
```

which means at [step 3 here](https://github.com/GoogleCloudPlatform/magic-modules/blob/2618ae26433fef8b4012aba152845023f2f6a9bf/mmv1/third_party/terraform/tests/resource_monitoring_slo_test.go#L93) it tried to apply the config but had a diff with the user label field. The update config does not seem to be successful at removing the labels field. 

Are the labels updatable? I would suggest trying a `send_empty_value: true` so the provider knows to force send the empty label value to the API

**Comment by etruong42** [comment]
`send_empty_value: true` looks like precisely what I needed - thanks!

I'm noticing the following error 

`No such file or directory @ rb_sysopen - .release/release-metadata.hcl`

In the build step for generate-diffs. 

I also notice a recent addition of that file in https://github.com/GoogleCloudPlatform/magic-modules/pull/6068, so I tried to merge in master, but merging is blocked.

**Comment by etruong42** [comment]
It appears that TestAccMonitoringSlo_basic failure is actually due to a Service Monitoring API bug where an empty userLabels request field does not clear the userLabels. I'm reaching out to the API team about this issue.

**Comment by etruong42** [comment]
The Service Monitoring API has been resolved (I can now clear user labels by sending an empty userLabels field in the patch request). Can we rerun the tests?

**Pull request merged**
