### PR TITLE
Add deprecation messages for cloudiot resources

### PR DESCRIPTION
**Pull request by zli82016**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
docs: added deprecation message for resource `google_cloudiot_device` and `google_cloudiot_registry` and updated the 5.0.0 guide
```

### CODE REVIEW

**Review by c2thorn — COMMENTED** [review]
is the datasource deprecation already covered?

**Comment by zli82016** [comment]
Hello, @c2thorn , do you mean to deprecate the datasource `google_cloudiot_registry_iam_policy ` or add deprecation message for this datasource?

**Comment by c2thorn** [comment]
I meant add the deprecation message, assuming it's possible to do so. @zli82016

**Comment by zli82016** [comment]
`deprecation_message` is not supported in [iam_policy](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/api/resource/iam_policy.rb) now. I can add this property. Does it sound good?

**Comment by c2thorn** [comment]
I didn't catch that the datasource was generated by the IAM object specifically, sorry. If you have time to do so, it would be nice, but don't worry about it otherwise.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
