### PR TITLE
Added examples for Cloud SQL instance clones

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Planning to add these samples to this section:

https://cloud.google.com/sql/docs/mysql/clone-instance
https://cloud.google.com/sql/docs/postgres/clone-instance
https://cloud.google.com/sql/docs/sqlserver/clone-instance

```release-note:none
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Failing test on the new sample changes

```
=== RUN   TestAccCGCSnippet_sqlSqlserverInstanceCloneExample
=== PAUSE TestAccCGCSnippet_sqlSqlserverInstanceCloneExample
=== CONT  TestAccCGCSnippet_sqlSqlserverInstanceCloneExample
    provider_test.go:309: Step 1/2 error: Error running apply: exit status 1
        There are some problems with the CLI configuration:
        
        Error: The specified plugin cache dir /opt/teamcity-agent/work/2e51954ade9939a/.provider-cache cannot be opened: stat /opt/teamcity-agent/work/2e51954ade9939a/.provider-cache: no such file or directory
        
        
        As a result of the above problems, Terraform may not behave as intended.
        
        
        
        Error: Error, failed to create instance terraform-20220315212902539400000001: googleapi: Error 400: Missing parameter: Tier., required
        
          on terraform_plugin_test.tf line 2, in resource "google_sql_database_instance" "default":
           2: resource "google_sql_database_instance" "default" {
        
        
--- FAIL: TestAccCGCSnippet_sqlSqlserverInstanceCloneExample (4.55s)
FAIL

```

**Comment by ScottSuarez** [comment]
branch has merge conflicts

**Comment by betsy-lichtenberg** [comment]
redoing in a new PR

**Pull request closed without merging**
