### PR TITLE
Change GCP scope name up-to-date

### PR DESCRIPTION
**Pull request by ymotongpoo**
Creating Google Compute Engine instances fails because of the obsolete scope alias in the Terraform provider as I reported in the provider repository.
https://github.com/hashicorp/terraform-provider-google/issues/8495
https://github.com/hashicorp/terraform-provider-google/pull/8496

Because [the comment suggested](https://github.com/hashicorp/terraform-provider-google/pull/8496#issuecomment-784556342) to make the change in this repo, I do so.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
compute: Fixed service account scope alias to be updated.
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
commented on the original pr https://github.com/hashicorp/terraform-provider-google/pull/8496 removing cameron adding myself as a reviewer

**Comment by ymotongpoo** [comment]
@ScottSuarez I put another comment in the original thread. The latest commit reverts the removed aliases for backward compat.

**Review by ScottSuarez — APPROVED** [review]

**Review by rileykarson — APPROVED** [review]

**Comment by rileykarson** [comment]
Oh whoops, didn't notice this PR completely replaced the old one. @ScottSuarez want to spin out an issue to consider removing the deprecated ones in `4.0.0` once this is merged?

**Comment by ScottSuarez** [comment]
sure !

**Comment by ScottSuarez** [comment]
filed https://github.com/hashicorp/terraform-provider-google/issues/8545

**Comment by ymotongpoo** [comment]
@ScottSuarez Is this closed by mistake or any other reasons?

**Comment by ymotongpoo** [comment]
Any updates on this? Is there anything I can do on my end?

**Comment by ScottSuarez** [comment]
Hey @ymotongpoo, sorry lost track of this among other things last week! Thanks for the ping! merged :)

**Pull request merged**
