### PR TITLE
[Terraform] add souce repo support to cloud functions

### PR DESCRIPTION
**Pull request by danawillow**
Fixes https://github.com/terraform-providers/terraform-provider-google/issues/1289.

-----------------------------------------------------------------
# [all]
## [terraform]
add souce repo support to cloud functions

### CODE REVIEW

**Comment by susanjiang03** [comment]
hello @danawillow, does this source repository url have to be hosted in google cloud source? can it be a github repository?

**Comment by danawillow** [comment]
Yes, this resource is specifically for this product: https://cloud.google.com/source-repositories/

**Comment by susanjiang03** [comment]
> Yes, this resource is specifically for this product: https://cloud.google.com/source-repositories/

Thanks @danawillow ! it would be great if we could use github repo.

**Comment by danawillow** [comment]
Can you file a feature request at https://github.com/terraform-providers/terraform-provider-google? I don't think it makes sense to have a GCP source repository resource mean anything other than that specific product, but other resources we have support both GCP source repos and GitHub repos. It would be helpful to know exactly what your use case is- it's possible we already support it.

**Pull request merged**
