### PR TITLE
Test fixes for Instance + InstanceTemplate

### PR DESCRIPTION
**Pull request by rambleraptor**
I'm convinced that there's some broken tests. This should fix them.

-----------------------------------------------------------------
# [all]
Test fixes for Instance + InstanceTemplate

### CODE REVIEW

**Comment by rambleraptor** [comment]
@ndmckinley I'm very confused why we aren't putting these files into Chef (we aren't) and I'm even more confused why these tests are passing currently on Chef/Puppet.

Any ideas?

**Comment by ndmckinley** [comment]
Huh!  Let's see.

**Comment by ndmckinley** [comment]
We figured out it's because the tests for Chef don't run, and these tests for Puppet were never implemented.

**Comment by rambleraptor** [comment]
TL;DR for why these tests aren't failing:
Chef: #236 (Maigican doesn't run Chef tests)
Puppet: Complex objects (arrays + nested objects) aren't tested.

**Pull request merged**
