### PR TITLE
Vertex model deployment

### PR DESCRIPTION
**Pull request by trodge**
Add the following resources:
`google_vertex_ai_endpoint`
`google_vertex_ai_endpoint_traffic_split`
`google_vertex_ai_metadata_schema`
`google_vertex_ai_model`
`google_vertex_ai_model_deployment`
part of https://github.com/hashicorp/terraform-provider-google/issues/9298

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_vertex_ai_endpoint
google_vertex_ai_endpoint_traffic_split
google_vertex_ai_metadata_schema
google_vertex_ai_model
google_vertex_ai_model_deployment
```

### CODE REVIEW

**Review by rileykarson — CHANGES_REQUESTED** [review]
Can this be split into a few different PRs? Namely, a PR per resource, and a separate one for the ID function change (unless there's a strong requirement _for making that change_ that it's paired with a resource, which is sometimes the case).

Multi-resource reviews are hard to keep track of as a reviewer, and can have extremely long review cycles. If it's necessary we hold all the resources and release them at once we can use a branch, similar to use a diffbase internally. The litmus test I use personally is that each PR should so one thing- "add X resource", "add y feature", or "change z assumption/rule".

**Comment by melinath** [comment]
Closing this PR - seems like it's no longer relevant.

**Pull request closed without merging**
