### PR TITLE
Use Cloud Composer v1 API for google provider

### PR DESCRIPTION
**Pull request by anitakar**
fixes https://github.com/hashicorp/terraform-provider-google/issues/7250

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
call v1 API instead of v1beta1 API. Helps with synchronization issue occurring when environment is created with v1beta1 API.
```

### CODE REVIEW

**Comment by danawillow** [comment]
You'll also need to make changes in config.go.erb to create the client with the correct API version.

Also, I updated the release-note type to none since this isn't a user-visible change (in the same way adding a new field or fixing a bug is), but if there's a clear benefit that you'd like to express to our users via the CHANGELOG, feel free to change it over to enhancement and write up a message that follows the release notes guide.

**Comment by anitakar** [comment]
> You'll also need to make changes in config.go.erb to create the client with the correct API version.
> 
> Also, I updated the release-note type to none since this isn't a user-visible change (in the same way adding a new field or fixing a bug is), but if there's a clear benefit that you'd like to express to our users via the CHANGELOG, feel free to change it over to enhancement and write up a message that follows the release notes guide.

Thanks for review.
Marking as WIP as after running tests there are still some things to fix.

```TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccComposerEnvironment -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
# github.com/hashicorp/terraform-provider-google/google [github.com/hashicorp/terraform-provider-google/google.test]
google/resource_composer_environment.go:406:92: cannot use env (type *"google.golang.org/api/composer/v1".Environment) as type *"google.golang.org/api/composer/v1beta1".Environment in argument to config.clientComposer.Projects.Locations.Environments.Create
google/resource_composer_environment.go:469:64: cannot use res.Config (type *"google.golang.org/api/composer/v1beta1".EnvironmentConfig) as type *"google.golang.org/api/composer/v1".EnvironmentConfig in argument to flattenComposerEnvironmentConfig
google/resource_composer_environment.go:584:20: patchObj.Config.WebServerNetworkAccessControl undefined (type *"google.golang.org/api/composer/v1".EnvironmentConfig has no field or method WebServerNetworkAccessControl)
google/resource_composer_environment.go:584:59: config.WebServerNetworkAccessControl undefined (type *"google.golang.org/api/composer/v1".EnvironmentConfig has no field or method WebServerNetworkAccessControl)
google/resource_composer_environment.go:638:29: cannot use env (type *"google.golang.org/api/composer/v1".Environment) as type *"google.golang.org/api/composer/v1beta1".Environment in argument to config.clientComposer.Projects.Locations.Environments.Patch
FAIL	github.com/hashicorp/terraform-provider-google/google [build failed]
FAIL
make: *** [GNUmakefile:14: testacc] Error 2
```

**Comment by anitakar** [comment]
I have run all of the tests.
One test has failed on permission error.
All the other tests have failed on deleting VPC networks.
I am afraid my project is misconfigured for the test.
I am not worried for not being able to delete the network. It has also happened when I was testing previous changes to webServerConfig and databaseConfig.
What worries me is TestAccComposerEnvironment_withNodeConfig fail on Create IAM Members roles/composer.worker.

Would you help me with configuring my project for terraform tests or maybe run TestAccComposerEnvironment_withNodeConfig for this change to see if it is an actual error?


Here are the logs:
```
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccComposerEnvironment -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccComposerEnvironment_basic
=== PAUSE TestAccComposerEnvironment_basic
=== RUN   TestAccComposerEnvironment_update
=== PAUSE TestAccComposerEnvironment_update
=== RUN   TestAccComposerEnvironment_private
=== PAUSE TestAccComposerEnvironment_private
=== RUN   TestAccComposerEnvironment_withNodeConfig
=== PAUSE TestAccComposerEnvironment_withNodeConfig
=== RUN   TestAccComposerEnvironment_withSoftwareConfig
=== PAUSE TestAccComposerEnvironment_withSoftwareConfig
=== RUN   TestAccComposerEnvironment_withUpdateOnCreate
=== PAUSE TestAccComposerEnvironment_withUpdateOnCreate
=== CONT  TestAccComposerEnvironment_basic
=== CONT  TestAccComposerEnvironment_withUpdateOnCreate
=== CONT  TestAccComposerEnvironment_private
=== CONT  TestAccComposerEnvironment_withSoftwareConfig
=== CONT  TestAccComposerEnvironment_update
=== CONT  TestAccComposerEnvironment_withNodeConfig
    testing.go:674: Step 0 error: errors during apply:
        
        Error: Request "Create IAM Members roles/composer.worker serviceAccount:tf-test-996641278784555963@rstrack-gcf-test.iam.gserviceaccount.com for \"project \\\"rstrack-gcf-test\\\"\"" returned error: Error applying IAM policy for project "rstrack-gcf-test": Error setting IAM policy for project "rstrack-gcf-test": googleapi: Error 403: Policy update access denied., forbidden
        
          on /tmp/tf-test883355133/main.tf line 35:
          (source code not available)
        
        
--- FAIL: TestAccComposerEnvironment_withNodeConfig (89.62s)
=== CONT  TestAccComposerEnvironment_update
    testing.go:674: Step 1 error: errors during apply:
        
        Error: googleapi: Error 400: Invalid field mask. Updating the selected field(s) is not supported., badRequest
        
          on /tmp/tf-test645238085/main.tf line 5:
          (source code not available)
        
        
=== CONT  TestAccComposerEnvironment_withSoftwareConfig
    testing.go:735: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: Error waiting for Deleting Network: The network resource 'projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3032746794374840467' is already being used by 'projects/rstrack-gcf-test/global/firewalls/tf-test-composer-net-30327467943748404-sjzhmsbmwunov4hplfykobyt'
        
        
        State: google_compute_network.test:
          ID = projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3032746794374840467
          provider = provider.google
          auto_create_subnetworks = false
          delete_default_routes_on_create = false
          description = 
          gateway_ipv4 = 
          name = tf-test-composer-net-3032746794374840467
          project = rstrack-gcf-test
          routing_mode = REGIONAL
          self_link = https://www.googleapis.com/compute/v1/projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3032746794374840467
--- FAIL: TestAccComposerEnvironment_withSoftwareConfig (1173.74s)
=== CONT  TestAccComposerEnvironment_update
    testing.go:735: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: Error waiting for Deleting Network: The network resource 'projects/rstrack-gcf-test/global/networks/tf-test-composer-net-6862793811067245064' is already being used by 'projects/rstrack-gcf-test/global/firewalls/tf-test-composer-net-68627938110672450-sjzhmsbmwunov4hplfykobyt'
        
        
        State: google_compute_network.test:
          ID = projects/rstrack-gcf-test/global/networks/tf-test-composer-net-6862793811067245064
          provider = provider.google
          auto_create_subnetworks = false
          delete_default_routes_on_create = false
          description = 
          gateway_ipv4 = 
          name = tf-test-composer-net-6862793811067245064
          project = rstrack-gcf-test
          routing_mode = REGIONAL
          self_link = https://www.googleapis.com/compute/v1/projects/rstrack-gcf-test/global/networks/tf-test-composer-net-6862793811067245064
--- FAIL: TestAccComposerEnvironment_update (1182.01s)
--- PASS: TestAccComposerEnvironment_basic (1185.32s)
=== CONT  TestAccComposerEnvironment_private
    testing.go:735: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: Error waiting for Deleting Network: The network resource 'projects/rstrack-gcf-test/global/networks/tf-test-composer-net-2445545875582115325' is already being used by 'projects/rstrack-gcf-test/global/firewalls/tf-test-composer-net-24455458755821153-d37echhbe6mhhtksu2c7ioas'
        
        
        State: google_compute_network.test:
          ID = projects/rstrack-gcf-test/global/networks/tf-test-composer-net-2445545875582115325
          provider = provider.google
          auto_create_subnetworks = false
          delete_default_routes_on_create = false
          description = 
          gateway_ipv4 = 
          name = tf-test-composer-net-2445545875582115325
          project = rstrack-gcf-test
          routing_mode = REGIONAL
          self_link = https://www.googleapis.com/compute/v1/projects/rstrack-gcf-test/global/networks/tf-test-composer-net-2445545875582115325
--- FAIL: TestAccComposerEnvironment_private (1471.53s)
=== CONT  TestAccComposerEnvironment_withUpdateOnCreate
    testing.go:735: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during apply: Error waiting for Deleting Network: The network resource 'projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3521426335619383387' is already being used by 'projects/rstrack-gcf-test/global/firewalls/tf-test-composer-net-35214263356193833-d37echhbe6mhhtksu2c7ioas'
        
        
        State: google_compute_network.test:
          ID = projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3521426335619383387
          provider = provider.google
          auto_create_subnetworks = false
          delete_default_routes_on_create = false
          description = 
          gateway_ipv4 = 
          name = tf-test-composer-net-3521426335619383387
          project = rstrack-gcf-test
          routing_mode = REGIONAL
          self_link = https://www.googleapis.com/compute/v1/projects/rstrack-gcf-test/global/networks/tf-test-composer-net-3521426335619383387
--- FAIL: TestAccComposerEnvironment_withUpdateOnCreate (2389.02s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google/google	2389.210s
FAIL
make: *** [GNUmakefile:14: testacc] Error 1
```

**Comment by danawillow** [comment]
I ran the nodeconfig test separately and it failed with a different message than you got:
```
------- Stdout: -------
=== RUN   TestAccComposerEnvironment_withNodeConfig
=== PAUSE TestAccComposerEnvironment_withNodeConfig
=== CONT  TestAccComposerEnvironment_withNodeConfig
TestAccComposerEnvironment_withNodeConfig: testing.go:674: Step 0 error: errors during apply:
Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 9, message: Cloud Storage Assertions Failed: Unable to write to GCS bucket.
GCS bucket write check failed.
on /opt/teamcity-agent/temp/buildTmp/tf-test179768029/main.tf line 2:
(source code not available)
--- FAIL: TestAccComposerEnvironment_withNodeConfig (2690.54s)
FAIL
```

You can see the full debug logs at https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/146420?buildTab=artifacts, though it doesn't look like there's anything particularly useful in there aside from the error message. Is this an error you're familiar with? Let me know if you'd like me to run it again in case it's flaky.

**Comment by danawillow** [comment]
Hey Anita, if you join the GoogleCloudPlatform org with your GH account, that should be enough to get the VCR tests to run automatically. We don't let community members trigger it themselves since the tests that it runs create real GCP infra.

Now let's see if I can trigger it without it being a comment on its own: /gcbrun

**Comment by danawillow** [comment]
I re-ran all the composer environment tests against the generated GA provider, and 6 of them failed: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/148633. Can you take a look and see whether those failures look like regular flakiness or whether they could be specific to differences in the two API versions? If you click on the "artifacts" tab you can see the debug logs for each test which show the requests/responses to/from the API, so you can see whether the requests that are failing make sense to you.

**Comment by danawillow** [comment]
@anitakar are you still working on this?

**Comment by melinath** [comment]
Hi @anitakar - Dana has moved to a different team so I'm taking over review of this PR! Here's a /gcbrun for you :-)

**Review by melinath — CHANGES_REQUESTED** [review]
@anitakar I'm marking this as "Request changes" since it seems like you're still working on Dana's feedback. Please re-request review when it's ready for review! Or comment if there's anything you need from me. Thanks!

**Comment by melinath** [comment]
I'm closing this PR since it's been inactive for a long time now. Please open a new PR if you want to work on this issue.

**Pull request closed without merging**
