### PR TITLE
move ConfigureBasePaths to config.go

### PR DESCRIPTION
**Pull request by yukinying**
# Release Note for Downstream PRs (will be copied)
```releasenote
Make ConfigureBasePaths available to config.go
```

### CODE REVIEW

**Comment by yukinying** [comment]
This would fix #2133.

**Comment by yukinying** [comment]
I add the logic to generate basepath.go. But somehow I think I may have an invalid dev environment as some of the imports are not in the generated file. As my changes does not involve any of those, I am hoping the code would work in a more proper build env.

**Comment by yukinying** [comment]
It looks like basepath.go get populated to terraform-provider-google-beta and terraform-provider-google, which is unexpected. I will wait for #2194 getting merged instead and then take it from there.

**Comment by yukinying** [comment]
Added a couple changes: 

1. moved ConfigureBasePaths from provider.go to config.go, nothing more, nothing less.
2. expose `provider_handwritten_endpoint.go` to the generated code on validator. There are handwritten paths that need to be exposed. 

Tested in a local setup.

**Comment by rileykarson** [comment]
Ah, looks like I was wrong- do you mind rebasing?

**Comment by yukinying** [comment]
I pulled the latest commits and I hope it would work :)

**Comment by yukinying** [comment]
How do I rebase in the downstream PRs? If it does not work, I can create a new pull request here.

**Comment by rileykarson** [comment]
They're rebased automatically, updating this PR is all that's necessary.

**Pull request merged**
