### PR TITLE
Added missing fields in info_type_transformations data_loss_prevention_deidentify_template resource

### PR DESCRIPTION
**Pull request by JayS-crest**
added support for `redactConfig`, `fixedSizeBucketingConfig`, `bucketingConfig`, `timePartConfig` and `dateShiftConfig` in `infoTypeTransformations` in dlp `data_loss_prevention_deidentify_template` resource

fixes https://github.com/hashicorp/terraform-provider-google/issues/11378

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dlp: added `redact_config`, `fixed_size_bucketing_config`, `bucketing_config`, `time_part_config` and `date_shift_config`  fields to `google_data_loss_prevention_deidentify_template` resource
```

### CODE REVIEW

**Comment by JayS-crest** [comment]
I've added the necessary tests for missing attributes. Seems like that would work now.

**Comment by JayS-crest** [comment]
Hey @rileykarson, Could you please start the tests? It is awaiting approval on your end. Thanks!

**Comment by JayS-crest** [comment]
Hi, I mistakenly named the added `day_of_the_week_value` instead of `day_of_week_value` in the test. I've renamed the fields in all the three cases and looks like the tests will run now.

**Comment by rileykarson** [comment]
I'm continuing to get build errors- you should see them in the GH action.

**Comment by JayS-crest** [comment]
I tried checking GH actions but got `Forbidden Error 403`. But while manually checking the test case, I found that the name of the testcase function was different as it contained `day_of_the_week_value`. Hence, I've updated that and the fields would be detected now as the case is part for tests.

**Comment by rileykarson** [comment]
@ScottSuarez can you investigate I thought that was the intention behind using GHA.

**Comment by rileykarson** [comment]
@JayS-crest are you able to successfully run your test locally?

**Comment by JayS-crest** [comment]
@rileykarson Apart from that, I've noticed that if the Vcr Tests fail, we cannot see the failing test or logs. It shows permission denied there as well. Is there a way to check that ? And yes, the tests here will run fine now as the fields will be detected so whenever you can approve that. Thanks!

**Comment by JayS-crest** [comment]
> @JayS-crest are you able to successfully run your test locally?

Yes, as I changed the function name, the tests do pass locally. So, that was a mistake from my side and the tests should run here now.

**Comment by rileykarson** [comment]
VCR results contain private information that we are not able to share with non-Google employees or provider maintainers @ HashiCorp, sorry!

> Yes, as I changed the function name, the tests do pass locally. So, that was a mistake from my side and the tests should run here as well.

Can you share console output from a successful run?

**Comment by JayS-crest** [comment]
> VCR results contain private information that we are not able to share with non-Google employees or provider maintainers @ HashiCorp, sorry!
> 
> > Yes, as I changed the function name, the tests do pass locally. So, that was a mistake from my side and the tests should run here as well.
> 
> Can you share console output from a successful local run?

Yes, will be sharing that. Can you start the tests once while I run that locally again and share the console output?

**Comment by rileykarson** [comment]
I've already started them.

**Comment by JayS-crest** [comment]
I manually checked each config for tests and they were passing. But while running tests for the PR, I got an error in the `build-and-unit-test`. It mentioned wrong signature and while checking the tests closely, I found the test cases were named starting from capital, TestAcc instead of testAcc. I've done necessary changed for all the 13 cases that had such issue.

**Comment by ScottSuarez** [comment]
> @ScottSuarez can you investigate I thought that was the intention behind using GHA.

GHA's are visible to all users. They should of been able to access the results. You can open these links with incognito to verify.

**Comment by rileykarson** [comment]
> I manually checked each config for tests and they were passing

Can you please share output from the [`899c52c` (#7912)](https://github.com/GoogleCloudPlatform/magic-modules/pull/7912/commits/899c52c4d66beadaeded70d1fc9784cd66ff96f0) commit? The code that was pushed here could not have worked, due to the compilation error you just resolved. I'm not sure why that was the case.

**Comment by JayS-crest** [comment]
> > @ScottSuarez can you investigate I thought that was the intention behind using GHA.
> 
> GHA's are visible to all users. They should of been able to access the results. You can open these links with incognito to verify.

When I tried opening the build log, I was shown Forbidden Error. Even now if I try to open link, it is showing the same error. Any probable reason why it isn't working for me?

**Comment by JayS-crest** [comment]
> > I manually checked each config for tests and they were passing
> 
> Can you please share output from the [`899c52c` (#7912)](https://github.com/GoogleCloudPlatform/magic-modules/pull/7912/commits/899c52c4d66beadaeded70d1fc9784cd66ff96f0) commit? The code that was pushed here could not have worked, due to the compilation error you just resolved. I'm not sure why that worked locally for you, given that.

So, as per what I think, I tried running different configs manually and not the test cases(functions). Hence, that was probably the reason why I was not able to catch the errors. Currently, when you asked me for config logs, I ran the Tests and that is when I found the errors in `build-and-unit-test` and resolved that.

**Comment by ScottSuarez** [comment]
> > > @ScottSuarez can you investigate I thought that was the intention behind using GHA.
> > 
> > 
> > GHA's are visible to all users. They should of been able to access the results. You can open these links with incognito to verify.
> 
> When I tried opening the build log, I was shown Forbidden Error. Even now if I try to open link, it is showing the same error. Any probable reason why it isn't working for me?

correct. you cannot access the cloud build links. You can access the status check for build-and-unit-tests

**Comment by ScottSuarez** [comment]
> The GitHub actions are the build and test steps! @ScottSuarez we may need to make the part external contributors can/can't interact with more clear.

Could you make an issue so we can track? There is messaging we can definitely alternate. Ideally we will move everything to github actions eventually but I agree maybe there is some stopgap we can apply in the meantime.

**Comment by rileykarson** [comment]
Everything would be impossible- VCR cannot move to GHA

**Comment by ScottSuarez** [comment]
> Everything would be impossible- VCR cannot move to GHA

Yes, everything except VCR

**Comment by JayS-crest** [comment]
Hi @rileykarson, as the tests have passed now, could you please merge this PR? Thanks!

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
