### PR TITLE
Add missing guest_os_features enumeration values

### PR DESCRIPTION
**Pull request by manuelbernhardt**
This PR adds three missing enumeration values for the `type` of the `guest_os_features` block of the `google_compute_image` resource, resolving [this issue](https://github.com/hashicorp/terraform-provider-google/issues/14485).

I ran the modified provider in the environment in which the issue first appeared and it indeed fixes it.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added enumeration values `SEV_SNP_CAPABLE`, `SUSPEND_RESUME_COMPATIBLE`, `TDX_CAPABLE` for the `guest_os_features` of `google_compute_image`
```

### CODE REVIEW

**Comment by zli82016** [comment]
Hello, @manuelbernhardt, can you please sign the CLA by clicking the Details link next to cla/google in the failed checks? Thanks.

**Comment by manuelbernhardt** [comment]
Thanks @zli82016, just signed the CLA. I'm unsure what I can do about the failing VCR test, these don't seem to have much to do with the changes introduced by this PR

**Comment by zli82016** [comment]
> Thanks @zli82016, just signed the CLA. I'm unsure what I can do about the failing VCR test, these don't seem to have much to do with the changes introduced by this PR

The failed VCR tests are not related to this PR.

**Review by zli82016 — APPROVED** [review]
LGTM

**Pull request merged**
