### PR TITLE
Add new resource, google_logging_metric

### PR DESCRIPTION
**Pull request by JoeStanton**
Opening this as a draft PR, though I hope it won't kick off the build robot. I wanted to validate my approach early, and will finish over the next couple of days.

**Usage as follows**

```terraform
resource "google_logging_metric" "api_latency" {
  name        = "api-latency"
  filter      = "resource.type=\"k8s_container\" resource.labels.cluster_name=\"cluster\" resource.labels.namespace_name=\"default\" resource.labels.container_name=\"api\" jsonPayload.type=\"request\""
  description = "API latency"

  metric_descriptor = {
    metric_kind = "DELTA"
    value_type  = "DISTRIBUTION"

    labels = [
      {
        key         = "path"
        description = "The request path"
        value_type  = "STRING"
      },
    ]
  }

  value_extractor = "EXTRACT(jsonPayload.event.responseTimeMs)"

  label_extractors = {
    path = "EXTRACT(jsonPayload.event.url)"
  }

  bucket_options = {
    exponential_buckets = {
      num_finite_buckets = 64
      growth_factor      = 2
      scale              = 0.01
    }
  }
}

```

-----------------------------------------------------------------
# [all]
## [terraform]
Logs-based metrics support

### CODE REVIEW

**Comment by JoeStanton** [comment]
Just signed the CLA.

**Comment by chrisst** [comment]
Fixes https://github.com/terraform-providers/terraform-provider-google/issues/1236

**Comment by JoeStanton** [comment]
Hi @chrisst thanks for getting back to me. We are using this code to provision custom metrics in the project I'm working on, but I've been super busy so have not been able to tidy this up yet so it's ready for merge. Definitely needs more test coverage.

Could you point me in the right direction for the following:

* How can I specify that order doesn't matter, for key-value labels? Otherwise we end up with a diff after the changes have been applied. I've been looking for an example but none seem to apply.

* Would you recommend mirroring exactly the GCP API behind this? For example, the UI shows label extractors as a sub-field of the label itself, whereas the API specifies `labelExtractor` as a completely separate top-level field. Just curious if there is a rule-of-thumb here.

I think in the next week or two I should be able to finish this up. Beyond tests, do I need to consider all of the Ansible use-cases to make this mergeable?

**Comment by chrisst** [comment]
To ignore ordering you can look at using a Terraform TypeSet https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset which in MagicModules is created with `is_set: true`. I did a quick check and it doesn't look like we have any examples of KeyValue sets so this may be uncharted territory. If you find it doesn't generate the right code I'll be happy to help out.

Our general rule of thumb is to mirror the api as closely as possible. The API is committed to not making breaking changes whereas the UI doesn't have that guarantee. 

As for Ansible, we often add new resources here just for a single provider (Terraform) and will `exclude` the others. If there is sufficient demand for the other tools then we work with somebody who has more experience with those tools to help add that support. Just by adding this it gets us way closer to getting Ansible support so it's still a big step in the right direction.

**Comment by chrisst** [comment]
I double checked on the ordering, and MM will turn the `KeyValue` object into a `TypeMap` in Terraform which is already ordering agnostic. So you actually should be fine with what you have already. No need to use `is_set`

**Comment by bukzor** [comment]
What's next?

**Comment by chrisst** [comment]
@JoeStanton it looks like there is a lot of excitement for this to land so we'd love to get this in soon. If you have time this week to finish the PR please let us know, otherwise we might build off of what you have started so that we can get this out. Thanks!

**Comment by tysen** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/1702

**Pull request closed without merging**
