### PR TITLE
[Terraform] autogenerate Pubsub Topics/Subscriptions (+labels)

### PR DESCRIPTION
**Pull request by drebes**
-----------------------------------------------------------------
# [all]

Adds `labels` to Pubsub Topics & Subscriptions.
## [terraform]

Autogenerate Pubsub Topics & Subscriptions, including `labels` support. Fixes terraform-providers/terraform-provider-google#1500
## [inspec]

### CODE REVIEW

**Comment by rambleraptor** [comment]
Hello! Thanks so much for submitting this PR. Sorry we didn't notice it.

@rileykarson is going to help you out. If you could rebase the PR, we'll run it through our CI system and get this review going + merged as quickly as possible.

**Comment by drebes** [comment]
Rebased.

**Comment by rileykarson** [comment]
Thanks! Running the Magician now. At first glance the change seems good, I'll be able to do a full review with downstreams generated.

**Comment by rileykarson** [comment]
Seeing this error, I think that the variable was removed recently so you can likely blow it away:

> RuntimeError: Extraneous variable 'exports' in Topic<Api::Resource>

**Comment by drebes** [comment]
Sorry, should be good now.

**Comment by rileykarson** [comment]
Ah, Ansible requires fields to be separately versioned. You'll need to add versions for the field similar to this: https://github.com/GoogleCloudPlatform/magic-modules/blob/5c815839679fad719c7f3837777ecd94dfe0e6db/products/storage/ansible.yaml#L42

> ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: lib/ansible/modules/cloud/google/gcp_pubsub_subscription.py:0:0: E309 version_added for new option (labels) should be 2.8. Currently 0.0
ERROR: lib/ansible/modules/cloud/google/gcp_pubsub_topic.py:0:0: E309 version_added for new option (labels) should be 2.8. Currently 0.0

**Comment by drebes** [comment]
Sorry, missed that. Should be good now.

**Comment by rileykarson** [comment]
There we go! Reviewing Terraform now.

@rambleraptor @slevenick can you review your downstreams?

**Comment by rileykarson** [comment]
Reviewed in the downstream as it's a better context to comment in. Comment here when you'd like me to run the Magician again!

**Comment by drebes** [comment]
I had missed the subtlety of specifying the subscription and topic with the full names, the updated version should address that.

I've also added back the `path` field (and I think we should also add a `path` field to `Topic` so we don't need to refer to a topic in a different project by its `id`, but will let you comment on that).

I've also added a test to updates, but that seems to be broken. It appears that [despite the docs](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/patch), the v1 version of the API is not really supporting `PATCH` properly:

```
2019/02/17 19:39:47 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
PATCH /v1/projects/drebes-playground-alpha-5ae4/subscriptions/tf-test-sub-1eikx11dk2?alt=json&updateMask=labels HTTP/1.1
Host: pubsub.googleapis.com
User-Agent: Terraform/0.11.9 (+https://www.terraform.io) terraform-provider-google-beta/acc
Content-Length: 49
Content-Type: application/json
Accept-Encoding: gzip

{
 "ackDeadlineSeconds": 20,
 "labels": {
  "foo": "baz"
 }
}

-----------------------------------------------------
2019/02/17 19:39:47 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sun, 17 Feb 2019 18:39:48 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"ack_deadline_seconds\": Cannot find field.\nInvalid JSON payload received. Unknown name \"labels\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"ack_deadline_seconds\": Cannot find field."
          },
          {
            "description": "Invalid JSON payload received. Unknown name \"labels\": Cannot find field."
          }
        ]
      }
    ]
  }
}

-----------------------------------------------------
```
Note that the test has three steps, and fails when going from 1 to 2:

1. Create a subscription with a long name and label `foo = bar`
2. Update the subscription with a long name and label `foo = baz` (this should trigger a `PATCH`, which fails)
3. Update the subscription with a short name and label `foo = baz` (which should trigger a recreate as the name is an input field).

Commenting out the first step (skipping the `PATCH`), however, works:
```
$ make testacc TESTARGS='-run=TestAccPubsub'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccPubsub -timeout 240m -ldflags="-X=github.com/terraform-providers/terraform-provider-google-beta/version.ProviderVersion=acc"
?   	github.com/terraform-providers/terraform-provider-google-beta	[no test files]
=== RUN   TestAccPubsubSubscription_pubsubSubscriptionPullExample
=== PAUSE TestAccPubsubSubscription_pubsubSubscriptionPullExample
=== RUN   TestAccPubsubSubscriptionIamBinding
=== PAUSE TestAccPubsubSubscriptionIamBinding
=== RUN   TestAccPubsubSubscriptionIamMember
=== PAUSE TestAccPubsubSubscriptionIamMember
=== RUN   TestAccPubsubSubscriptionIamPolicy
=== PAUSE TestAccPubsubSubscriptionIamPolicy
=== RUN   TestAccPubsubSubscription_fullName
=== PAUSE TestAccPubsubSubscription_fullName
=== RUN   TestAccPubsubSubscription_update
=== PAUSE TestAccPubsubSubscription_update
=== RUN   TestAccPubsubTopic_pubsubTopicBasicExample
=== PAUSE TestAccPubsubTopic_pubsubTopicBasicExample
=== RUN   TestAccPubsubTopicIamBinding
=== PAUSE TestAccPubsubTopicIamBinding
=== RUN   TestAccPubsubTopicIamBinding_topicName
=== PAUSE TestAccPubsubTopicIamBinding_topicName
=== RUN   TestAccPubsubTopicIamMember
=== PAUSE TestAccPubsubTopicIamMember
=== RUN   TestAccPubsubTopicIamPolicy
=== PAUSE TestAccPubsubTopicIamPolicy
=== RUN   TestAccPubsubTopic_fullName
=== PAUSE TestAccPubsubTopic_fullName
=== CONT  TestAccPubsubSubscription_pubsubSubscriptionPullExample
=== CONT  TestAccPubsubTopicIamBinding
=== CONT  TestAccPubsubTopicIamPolicy
=== CONT  TestAccPubsubTopic_fullName
=== CONT  TestAccPubsubSubscription_fullName
--- PASS: TestAccPubsubTopic_fullName (5.43s)
--- PASS: TestAccPubsubSubscription_pubsubSubscriptionPullExample (11.68s)
=== CONT  TestAccPubsubSubscription_update
--- PASS: TestAccPubsubTopicIamPolicy (14.82s)
=== CONT  TestAccPubsubTopic_pubsubTopicBasicExample
--- PASS: TestAccPubsubSubscription_fullName (11.05s)
=== CONT  TestAccPubsubTopicIamMember
--- PASS: TestAccPubsubTopic_pubsubTopicBasicExample (4.12s)
=== CONT  TestAccPubsubTopicIamBinding_topicName
--- PASS: TestAccPubsubSubscription_update (15.39s)
=== CONT  TestAccPubsubSubscriptionIamMember
--- PASS: TestAccPubsubTopicIamBinding (29.13s)
=== CONT  TestAccPubsubSubscriptionIamBinding
--- PASS: TestAccPubsubTopicIamMember (16.77s)
=== CONT  TestAccPubsubSubscriptionIamPolicy
--- PASS: TestAccPubsubTopicIamBinding_topicName (17.35s)
--- PASS: TestAccPubsubSubscriptionIamPolicy (21.45s)
--- PASS: TestAccPubsubSubscriptionIamMember (28.31s)
--- PASS: TestAccPubsubSubscriptionIamBinding (44.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-google-beta/google-beta	73.532s
?   	github.com/terraform-providers/terraform-provider-google-beta/scripts/affectedtests	[no test files]
?   	github.com/terraform-providers/terraform-provider-google-beta/version	[no test files]
```
Can you regenerate the downstream PRs and also verify if the `PATCH` call looks good to you? If so we may need to remove update support and checkin internally (as this appears to be broken but untested before).

**Comment by drebes** [comment]
Actually, the `PATCH` from `gcloud` works, and contains the modified fields inside the subscription object: 
```
==== request start ====
uri: https://pubsub.googleapis.com/v1/projects/drebes-playground-alpha-5ae4/subscriptions/a-sub?alt=json
method: PATCH
== headers start ==
Authorization: --- Token Redacted ---
accept: application/json
accept-encoding: gzip, deflate
content-length: 149
content-type: application/json
user-agent: google-cloud-sdk x_Tw5K8nnjoRAqULM9PFAC2b gcloud/234.0.0 command/gcloud.pubsub.subscriptions.update invocation-id/1547efab192a4ca4a09cba70a36e36d0 environment/None environment-version/None interactive/True from-script/False python/2.7.15 (Macintosh; Intel Mac OS X 18.2.0)
== headers end ==
== body start ==
{"subscription": {"ackDeadlineSeconds": 30, "name": "projects/drebes-playground-alpha-5ae4/subscriptions/a-sub"}, "updateMask": "ackDeadlineSeconds"}
== body end ==
==== request end ====
---- response start ----
-- headers start --
-content-encoding: gzip
alt-svc: quic=":443"; ma=2592000; v="44,43,39"
cache-control: private
content-length: 339
content-type: application/json; charset=UTF-8
date: Sun, 17 Feb 2019 19:19:48 GMT
server: ESF
status: 200
transfer-encoding: chunked
vary: Origin, X-Origin, Referer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
-- headers end --
-- body start --
{
  "name": "projects/drebes-playground-alpha-5ae4/subscriptions/a-sub",
  "topic": "projects/drebes-playground-alpha-5ae4/topics/a-topic",
  "pushConfig": {
    "attributes": {
      "x-goog-version": "v1"
    }
  },
  "ackDeadlineSeconds": 30,
  "messageRetentionDuration": "604800s",
  "expirationPolicy": {
    "ttl": "2678400s"
  }
}

-- body end --
total round trip time (request+response): 1.489 secs
---- response end ----
```
How can I force it to update the modified fields inside the subscription object (and `updateMask` as field as well, not parameter)?

**Comment by drebes** [comment]
I added an `update_encoder` and now it all looks fine. 👍

**Comment by rileykarson** [comment]
Yep, an update encoder is the right tool for a case like that :+1:

Generating downstreams and making another pass once they're done.

**Comment by rileykarson** [comment]
Looks like a Magician update changed the branch we PR off of, these new downstreams will supersede the old ones.

**Comment by rileykarson** [comment]
Since the original downstreams are still getting updated, I commented on https://github.com/terraform-providers/terraform-provider-google-beta/pull/432 again.

While adding resource/product specific reference (`self_link`/`name`) validation is a good idea eventually, I don't think that handwriting it is the right balance of maintenance vs benefit. We can continue to reuse generic functions for handling short names / partial URIs / reference links & keep consistent with most existing resources; that'll make an eventual migration easier.

My apologies again for the fiddlyness of `name`-style references in MM, especially when converting handwritten resources. I'm passively thinking about how to improve the situation (https://github.com/GoogleCloudPlatform/magic-modules/issues/937), the problem is that many APIs have adopted _slightly_ different patterns vs the relative consistency of self links in the past.

**Comment by drebes** [comment]
I've pushed my changes. If you can regenerate the downstream PRs and give it a new look...

**Pull request merged**
