### PR TITLE
Fix import formats of Firebase apps

### PR DESCRIPTION
**Pull request by rainshen49**
* Use snake_case app_id
* Addresses an old issue with `google_firebase_webapp` import

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes). https://github.com/hashicorp/terraform-provider-google/issues/14606 https://github.com/hashicorp/terraform-provider-google/issues/7907
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
firebase: added additional import formats for app resources, removed the need to supply duplicate projects in some cases
```

### CODE REVIEW

**Review by rileykarson — COMMENTED** [review]
Have you confirmed these formats locally?

IIUC these all support `{{project}} {{name}}` and `{{name}}`, they're using https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/custom_import/self_link_as_name.erb

`{{name}}` is _technically_ `projects/{{project}}/webApps/{{app_id}}` (or the same form for the others), but the others won't work I think.

**Comment by rainshen49** [comment]
I just ran through all the formats locally and you're right: only the {{project}} {{name}} and {{name}} one works. All the other formats are wrong. In order for this to work, it looks like I'll need to change the self_link from `{{name}}` to the full `projects/{{project}}/*Apps/{{app_id}}` so that `app_id` is included in the url.

**Comment by rainshen49** [comment]
Fixed & tried out all formats locally. It looks like [self_link_as_name.erb](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/custom_import/self_link_as_name.erb) is no longer necessary this way.

**Review by rileykarson — APPROVED** [review]
Yep, by moving away from `{{name}}` we drop that custom code. Plus, we now handle `deletion_policy`'s default value slightly better.

**Pull request merged**
