### PR TITLE
Remove ForceNew from dns_config

### PR DESCRIPTION
**Pull request by chicocvenancio**
Fixes hashicorp/terraform-provider-google/issues/13285. Removed ForceNew from dnsConfig, allowing it to be updated. 

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: Allowed dns_config to be updated in `google_container_cluster`

```

### CODE REVIEW

**Comment by chicocvenancio** [comment]
Thanks for the comment @c2thorn. Tried to address it in [3f5d567](https://github.com/GoogleCloudPlatform/magic-modules/pull/7452/commits/3f5d5678a36c9b6e542b2d6658a0dcf21f8828b8).

**Comment by c2thorn** [comment]
The test failed with the error:
```
    Error: googleapi: Error 400: CloudDNS cannot be disabled on clusters with VPC scope DNS., badRequest
```

**Comment by chicocvenancio** [comment]
[Docs](https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-dns#disable-cloud-dns) seem to state it can be disabled 🤷. 

I guess we could still customDiff and get the behavior to fix https://github.com/hashicorp/terraform-provider-google/issues/13285, but seems like a smaller gain if its one way only.

**Comment by pib** [comment]
It definitely *can* be disabled on clusters with CLUSTER scope instead of VPC scope. I just did so manually on a cluster.

**Comment by pib** [comment]
I just checked this on a test cluster. Once you have set the dns scope to "VPC_SCOPE", the dnsConfig becomes immutable. 
image

With the scope set to "DNS_SCOPE_UNSPECIFIED" or "CLUSTER_SCOPE", I was able to chance the scope to any of the values, including "VPC_SCOPE" (after which point I couldn't change any of the dns config), and I was able to change clusterDns to any of "PROVIDER_UNSPECIFIED", "PLATFORM_DEFAULT", or "CLOUD_DNS".

**Comment by c2thorn** [comment]
This PR is fairly stale, so I'm opting to close it out. I'll comment a summary with @pib's findings in the github issue.

**Pull request closed without merging**
