### PR TITLE
feat: Add IAM resources for KMS EKM Connection

### PR DESCRIPTION
**Pull request by romanini-ciandt**
The goal of this PR is to introduce the following IAM Resources for EKM Connection resource:
`google_kms_ekm_connection_iam_member`
`google_kms_ekm_connection_iam_policy`
 `google_kms_ekm_connection_iam_binding`

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_kms_ekm_connection_iam_member`
```

```release-note:new-resource
`google_kms_ekm_connection_iam_policy`
```

```release-note:new-resource
`google_kms_ekm_connection_iam_binding`
```

### CODE REVIEW

**Comment by romanini-ciandt** [comment]
Hi @zli82016! Can you help with some guidance, please?

I'm seeing `modular-magician` reporting missing tests for this PR, but according to the [Add IAM support doc](https://googlecloudplatform.github.io/magic-modules/develop/resource/#add-iam-support) _"IAM support for MMv1-generated resources is configured within the ResourceName.yaml file, and will create [...] and **test files** for that resource target when an iam_policy block is present."_

- Shouldn't the tests files be auto-generated?;
- I can add it manually, but I'm not sure where/how it should look like; Is there any guide about that?

**Comment by zli82016** [comment]
> Hi @zli82016! Can you help with some guidance, please?
> 
> I'm seeing `modular-magician` reporting missing tests for this PR, but according to the [Add IAM support doc](https://googlecloudplatform.github.io/magic-modules/develop/resource/#add-iam-support) _"IAM support for MMv1-generated resources is configured within the ResourceName.yaml file, and will create [...] and **test files** for that resource target when an iam_policy block is present."_
> 
> * Shouldn't the tests files be auto-generated?;
> * I can add it manually, but I'm not sure where/how it should look like. I see some tests on `mmv1/third_party/terraform/services/`, others in `mmv1/templates/terraform/examples` following different approaches. Is there any guide about that?

The tests are not auto-generated because `skip_test` is added to the test example in the [yaml file](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/kms/EkmConnection.yaml#L39). The test example is used to auto-generate the tests for the resource and iam resources normally. 

I don't find any reasons that the test example is skipped in the original PR https://github.com/GoogleCloudPlatform/magic-modules/pull/10094

To auto-generate the tests, you can add another test example with `skip_docs` to the yaml file.
For example (some modifications may be needed)
```
  - !ruby/object:Provider::Terraform::Examples
    name: 'kms_ekm_connection_basic_test'
    primary_resource_id:
      'example-ekmconnection'
    skip_docs: true
    vars:
      ekmconnection_name: 'ekmconnection_example'
```

Inside the file `kms_ekm_connection_basic_test.tf.erb`, you can copy the [existing test](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/kms/resource_kms_ekm_connection_test.go#L44)

**Review by zli82016 — CHANGES_REQUESTED** [review]
Auto-generate the missing tests.

**Comment by romanini-ciandt** [comment]
> Auto-generate the missing tests.

@zli82016 auto-generated tests to `google_kms_ekm_connection` fails due to an incorrect auto-generated `hostname` attribute. That's why `skip-test` was set to `true` in the past... looks like there is a dedicated EKM cluster VM to test the resource, and it's used in `magic-module` by `external-uri` secret manager.

I added the tests for EKM IAM resource following the same existing test structure for the EKM resource. Let me know if it looks correct.

**Review by zli82016 — CHANGES_REQUESTED** [review]
Can you fix the test? Thanks.

**Comment by romanini-ciandt** [comment]
> Can you fix the test? Thanks.

@zli82016 it might pass now. Can you trigger the CI, please?

**Comment by romanini-ciandt** [comment]
@zli82016 can you provide the error message/logs from failing build, please?

For this test specifically, I can't run in my local to prevent errors here due to the hard-coded secret manager used for the EKM cluster. I tried to simulate the scenario in my local and I couldn't find additional errors.

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
