### PR TITLE
Update AlloyDB e2e tests and remove custom code for Public-IP feature

### PR DESCRIPTION
**Pull request by nancynh**
Removes the custom code that was in place for the[ Public-IP feature ](https://github.com/GoogleCloudPlatform/magic-modules/pull/10331) now that the API supports creating instances with public IP enabled. Users shouldn't see a change in the behavior on TF side - though on the API side we are now enforcing the user to have a complex password to enable public IP. I've also updated the AlloyDB e2e tests relating to the Public-IP feature since they were breaking for the past couple of days from the API change.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
alloydb: created the resource `google_alloydb_instance` directly with public IP enabled instead of creating the resource with public IP disabled and then enabling it
```

### CODE REVIEW

**Comment by nancynh** [comment]
FYI the VCR tests are failing due to hitting the quota based on the debug logs:

```
{
  "error": {
    "code": 429,
    "message": "Quota limit 'ClustersPerProjectPerRegion' has been exceeded. Limit: 50 in region us-central1.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.QuotaFailure",
        "violations": [
          {
            "subject": "project:1067888929963",
            "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 50 in region us-central1"
          }
        ]
      }
    ]
  }
}
```

Errors in the other logs:
```
            "subject": "project:1067888929963",
            "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 5 in region us-south1"
```

```
          {
            "subject": "project:1067888929963",
            "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 5 in region us-east1"
          }
```

```
          {
            "subject": "project:1067888929963",
            "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 5 in region us-east1"
          }
```

Project could be cleaned up

**Comment by zli82016** [comment]
> FYI the VCR tests are failing due to hitting the quota based on the debug logs:
> 
> ```
> {
>   "error": {
>     "code": 429,
>     "message": "Quota limit 'ClustersPerProjectPerRegion' has been exceeded. Limit: 50 in region us-central1.",
>     "status": "RESOURCE_EXHAUSTED",
>     "details": [
>       {
>         "@type": "type.googleapis.com/google.rpc.QuotaFailure",
>         "violations": [
>           {
>             "subject": "project:1067888929963",
>             "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 50 in region us-central1"
>           }
>         ]
>       }
>     ]
>   }
> }
> ```
> 
> Errors in the other logs:
> 
> ```
>             "subject": "project:1067888929963",
>             "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 5 in region us-south1"
> ```
> 
> ```
>           {
>             "subject": "project:1067888929963",
>             "description": "Quota 'ClustersPerProjectPerRegion' exhausted. Limit 5 in region us-east1"
>           }
> ```
> 
> Project could be cleaned up

Let me check.

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
