### PR TITLE
Promote enable_confidential_storage from beta to GA

### PR DESCRIPTION
**Pull request by Sneha-at**
**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promote `enable_confidential_storage` from `node_config` in `google_container_cluster` and `google_container_node_pool` to GA (ga)
```

### CODE REVIEW

**Comment by Sneha-at** [comment]
Thanks Stephen! I realized the API library is yet to be updated and should be ready by next. Will update the go.mod file once the field in updated in go api client.

**Comment by Sneha-at** [comment]
@melinath I have not made any changes related to `TestAccContainerCluster_withGatewayApiConfig` is this a known issue? I see other PRs are also failing the same test #9988 and #9964

**Comment by melinath** [comment]
@Sneha-at correct, those failures are unrelated.

**Comment by Sneha-at** [comment]
@melinath Do we have any ETA for the fix? We are little tight on deadline and will like to have this in the next release.

**Comment by melinath** [comment]
It's not a blocker for your PR. Everything looks good but I'm going to run the new tests in the GA provider. (You won't have access to this link, it's for my own reference.) https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CONTAINER/105366?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by melinath** [comment]
New GA test run: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CONTAINER/105811?hideTestsFromDependencies=false&hideProblemsFromDependencies=false

**Review by melinath — APPROVED** [review]
tests passed in GA - LGTM.

**Pull request merged**
