### PR TITLE
Prepared spot_instance_basic for inclusion in C.G.C. documentation

### PR DESCRIPTION
**Pull request by saqibkhanspeaks12**
Created sample for creating spot basic Spot VM for CGC
https://cloud.google.com/compute/docs/instances/create-use-spot#create

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by shuyama1** [comment]
Hey @saqibkhanspeaks12. Looks like the conflicts still exit would mind taking a look? Sorry about that. Please let me if you have any questions. Also we just promoted Spot VMs to GA recently in https://github.com/GoogleCloudPlatform/magic-modules/pull/5960. But it's totally your call if you want to add this in GA as well :)

**Comment by saqibkhanspeaks12** [comment]
@shuyama1 Thanks for letting me know. I wasn't aware of the update to GA. If it makes more sense, should I just close the beta PR and raise a new PR for GA provider itself? that way this remains more relevant. Looking for the best way to take this forward.

**Comment by shuyama1** [comment]
Simply removing `min_version: beta` in the terramform.yaml and `provider = google-beta` in your sample should generate the GA documentation and tests for both providers I believe! Sorry about the extra work!

**Pull request closed without merging**
