### PR TITLE
Manage services peered-dns-domains via terraform

### PR DESCRIPTION
**Pull request by DeviaVir**
https://cloud.google.com/sdk/gcloud/reference/services/peered-dns-domains/list hit GA a little while back, this is what allows you to configure private DNS access to a shared network (i.e. a private cloud build worker pool could use private DNS on a different GCP project). We're currently configured it using the `gcloud` binary, but would like to move this into terraform.
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_service_networking_peered_dns_domain`
```
```release-note:new-datasource
`google_service_networking_peered_dns_domain`
```

### CODE REVIEW

**Comment by DeviaVir** [comment]
Not too sure how to proceed with acceptance tests, if it's easy for you to run- please go ahead.

**Comment by DeviaVir** [comment]
> Tests failed during RECORDING mode: TestAccDataSourceGoogleCloudRunService_optionalProject|TestAccDataSourceComputeLbIpRanges_basic|TestAccDataSourceDNSKeys_noDnsSec|TestAccDataSourceCloudIdentityGroupMemberships_basic|TestAccDataSourceComputeNetworkEndpointGroup|TestAccDataSourceCloudIdentityGroups_basic|TestAccDataSourceGoogleCloudRunLocations_basic|TestAccDataSourceDNSKeys_basic|TestAccDataSourceDnsManagedZone_basic|TestAccComputeHealthCheckDatasource_basic|TestAccDataSourceGameServicesGameServerDeploymentRollout_basic|TestAccDataSourceGoogleCloudRunService_basic|TestAccDataSourceGoogleActiveFolder_default|TestAccDataSourceGoogleBillingAccount_byShortName|TestAccDataSourceGoogleAppEngineDefaultServiceAccount_basic|TestAccDataSourceGoogleBillingAccount_byFullNameClosed|TestAccDataSourceGoogleActiveFolder_dash|TestAccDataSourceGoogleBillingAccount_byDisplayName|TestAccDataSourceGoogleBillingAccount_byFullName|TestAccDataSourceGoogleActiveFolder_space|TestAccDataSourceGoogleClientConfig_basic|TestAccDataSourceGoogleClientOpenIDUserinfo_basic|TestAccDataSourceGoogleBigqueryDefaultServiceAccount_basic|TestAccDataSourceGoogleCloudFunctionsFunction_basic|TestAccDataSourceComputeGlobalAddress|TestAccDataSourceComputeBackendService_basic|TestAccDataSourceComposerImageVersions_basic|TestAccDataSourceComputeHaVpnGateway|TestAccDataSourceComputeImage|TestAccDataSourceComputeAddress|TestAccDataSourceGoogleForwardingRule|TestAccDataSourceComputeBackendBucket_basic|TestAccDataSourceGoogleComputeDefaultServiceAccount_basic|TestAccDataSourceComposerEnvironment_basic|TestAccDataSourceGoogleComputeInstanceGroup_basic|TestAccDataSourceComputeImageFilter|TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleComputeInstanceGroup_fromIGM|TestAccDataSourceGoogleComputeInstanceGroup_withNamedPort|TestAccInstanceTemplateDatasource_filter_mostRecent|TestAccInstanceTemplateDatasource_filter|TestAccComputeRegions_basic|TestAccDataSourceComputeInstance_basic|TestAccInstanceTemplateDatasource_name|TestAccDataSourceGoogleNetwork|TestAccDataSourceComputeRegionSslCertificate|TestAccDataSourceComputeResourcePolicy|TestAccDataSourceComputeNodeTypes_basic|TestAccDataSourceComputeRouter|TestAccContainerClusterDatasource_zonal|TestAccDataSourceGoogleSslPolicy|TestAccDataSourceGoogleSubnetwork|TestAccDataSourceGoogleVpnGateway|TestAccDataSourceComputeSslCertificate|TestAccComputeZones_filter|TestAccComputeZones_basic|TestAccContainerEngineVersions_basic|TestAccContainerClusterDatasource_regional|TestAccDataSourceGoogleFolderOrganizationPolicy_basic|TestAccContainerEngineVersions_filtered|TestAccDataSourceGoogleFolder_byFullName|TestAccDataSourceGoogleFolder_lookupOrganization|TestAccDataSourceGoogleFolder_byShortName|TestAccDataSourceGoogleFolder_byFullNameNotFound|TestAccDataSourceGoogleGlobalForwardingRule|TestAccDataSourceIAMRole|TestAccDataSourceGoogleIamTestablePermissions_basic|TestAccDataSourceGoogleMonitoringUptimeCheckIps_basic|TestAccDataSourceGoogleKmsCryptoKey_basic|TestAccDataSourceGoogleKmsCryptoKeyVersion_basic|TestAccDataKmsSecretCiphertext_basic|TestAccDataSourceGoogleKmsKeyRing_basic|TestAccDataSourceGoogleNetblockIpRanges_basic|TestAccDataSourceGoogleOrganization_byFullName|TestAccDataSourceGoogleOrganization_byShortName|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceGoogleProject_basic|TestAccDataSourceGoogleOrganization_byDomain|TestAccDataSourceGoogleProjectOrganizationPolicy_basic|TestAccDataSourceGoogleProjects_basic|TestAccDataSourceGoogleServiceAccountIdToken_basic|TestAccDatasourceGoogleServiceAccount_basic|TestAccDataSourceGoogleServiceAccountIdToken_impersonation|TestAccDatasourceGoogleServiceAccountKey_basic|TestAccDataSourceGoogleSQLCaCerts_basic|TestAccDataSourceGoogleStorageProjectServiceAccount_basic|TestAccDataSourceIAMBetaWorkloadIdentityPool_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleStorageTransferProjectServiceAccount_basic|TestAccDataSourceIAMBetaWorkloadIdentityPoolProvider_basic|TestAccIapClient_Datasource_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNoDisplayNameOrType|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceMonitoringService_AppEngine|TestAccDataSourceGooglePubsubTopic_optionalProject|TestAccDataSourceGooglePubsubTopic_basic Please fix these to complete your PR

My test is not in this list, does that mean it was successful? Can I do something about these failed tests? @melinath

**Comment by melinath** [comment]
Hm, I'm seeing that test failing; there might be something wrong with how we're collecting test failures (or maybe it just doesn't handle the volume well.) 

Here's the error message I'm seeing:

```
Error: InternalValidate
Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:
1 error occurred:
  * resource google_project_service_peered_dns_domain: All fields are ForceNew
or Computed w/out Optional, Update is superfluous
```

I'm seeing that for all the failed tests, so this is probably not related to you. Maybe try rebasing? This may be an issue that was resolved on master.

**Comment by DeviaVir** [comment]
Huh, I removed the `Update` since it didn't do anything (had it pointed at an empty function first).

**Comment by DeviaVir** [comment]
```
$ gcloud services peered-dns-domains list --network=test-network --project=tf-test-h-4767669441283761299
ERROR: (gcloud.services.peered-dns-domains.list) NOT_FOUND: Producer tenant project not found for service: 'servicenetworking.googleapis.com' consumer network 'projects/1026758588270/global/networks/test-network'.
Help Token: Ae-hA1Oi9cA7na3Es9RzXyKvAfpr18SJBvUO_hSXMSpAF7QzA1R_3-Bb35U1jyznUq_kmyVX1CW_4ynjpSrpxkIYPT5uY1495fAsLEKw5WFy4WEqvHb6ZQ8=
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=907026&service=servicenetworking.googleapis.com&network=projects/1026758588270/global/networks/test-network
    type: googleapis.com
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: servicenetworking.googleapis.com
  metadata:
    network: projects/1026758588270/global/networks/test-network
    service: servicenetworking.googleapis.com
  reason: SN_PRODUCER_TENANT_PROJECT_NOT_FOUND
```
close, but not sure what I might be missing... will spend another few hours on this when I have the chance

**Review by melinath — COMMENTED** [review]
Leaving a comment review to remove this from my review queue. Please [re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/) when it's ready for another look! By the way, if this is a fairly standard resource, it may be possible to implement via an [`api.yaml`](https://github.com/GoogleCloudPlatform/magic-modules#making-changes-to-resources) file rather than handwriting. You may have already considered that but I wanted to mention it in case :-)

**Comment by DeviaVir** [comment]
Interesting, I'm getting this 500 error:
```
=== RUN   TestAccServiceNetworkingPeeredDNSDomain_basic
=== PAUSE TestAccServiceNetworkingPeeredDNSDomain_basic
=== CONT  TestAccServiceNetworkingPeeredDNSDomain_basic
    provider_test.go:270: Step 1/2 error: Error running apply: exit status 1

        Error: googleapi: Error 500: An internal exception occurred.
        Help Token: Ae-hA1PJHN8yTxrovZTwAc4_mHpzinJpS-ZB1HUJosqjCEoolTLUdl6tIudu4o-MPEAVXZktVhWbLhUZTpmfZ6pSdzZkBuaokkwOoApdrivwNSKWxX4=, backendError

          with google_service_networking_peered_dns_domain.test,
          on terraform_plugin_test.tf line 85, in resource "google_service_networking_peered_dns_domain" "test":
          85: resource "google_service_networking_peered_dns_domain" "test" {

--- FAIL: TestAccServiceNetworkingPeeredDNSDomain_basic (482.31s)
```

I added the same terraform in a project, and used the gcloud command to set up the peered-dns without trouble. Perhaps it's an API call issue, but I wonder if there are logs associated with the Help Token?

**Comment by melinath** [comment]
@DeviaVir Try [adding TF_LOG=TRACE](https://www.terraform.io/docs/internals/debugging.html) to your test run - that will give you full access to the API requests & responses, which may help you debug the issue.

**Comment by DeviaVir** [comment]
```
PATCH /v1/services/servicenetworking.googleapis.com/connections/-?alt=json&force=true&prettyPrint=false&updateMask=reservedPeeringRanges HTTP/1.1
Host: servicenetworking.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/1.0.7 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/acc
Content-Length: 115
Content-Type: application/json
X-Goog-Api-Client: gl-go/1.17.1 gdcl/20210830
Accept-Encoding: gzip

{
 "network": "projects/779747013501/global/networks/test-network",
 "reservedPeeringRanges": [
  "private-ip-alloc-host"
 ]
}
```

finally had this response:

```
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Wed, 29 Sep 2021 15:27:48 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
 "name": "operations/pssn.p24-779747013501-12bae60a-7b46-46f0-b700-6a42d751cc9b",
 "done": true,
 "error": {
  "code": 13,
  "message": "An internal exception occurred.\nHelp Token: Ae-hA1Oo-e-saiy9oFuhp4_IrYBLCzsID_twr71EY0DXxHpqG_nHAeKs0RFXgEvnptLL55XDmvC99YB9VuWkD-mX0V-lvYM2GqHPoOnGJE4JDEfrTf8j",
  "details": [
   {
    "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
    "violations": [
     {
      "type": "googleapis.com",
      "subject": "1"
     }
    ]
   },
   {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "reason": "INTERNAL",
    "domain": "servicenetworking.googleapis.com"
   }
  ]
 }
}
```

**Comment by DeviaVir** [comment]
```
make testacc TEST=./google TESTARGS='-run=TestAccServiceNetworkingPeeredDNSDomain_basic'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccServiceNetworkingPeeredDNSDomain_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccServiceNetworkingPeeredDNSDomain_basic
=== PAUSE TestAccServiceNetworkingPeeredDNSDomain_basic
=== CONT  TestAccServiceNetworkingPeeredDNSDomain_basic
--- PASS: TestAccServiceNetworkingPeeredDNSDomain_basic (377.77s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   377.794s
```

```
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
=== PAUSE TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
=== CONT  TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
--- PASS: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic (328.71s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   328.730s
```

🥳

**Comment by DeviaVir** [comment]
```
$ make testacc TEST=./google TESTARGS='-run=TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
=== PAUSE TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
=== CONT  TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic
--- PASS: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic (422.86s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   422.872s

$ make testacc TEST=./google TESTARGS='-run=TestAccServiceNetworkingPeeredDNSDomain_basic'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccServiceNetworkingPeeredDNSDomain_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccServiceNetworkingPeeredDNSDomain_basic
=== PAUSE TestAccServiceNetworkingPeeredDNSDomain_basic
=== CONT  TestAccServiceNetworkingPeeredDNSDomain_basic
--- PASS: TestAccServiceNetworkingPeeredDNSDomain_basic (386.43s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   386.446s
```

Seems fine for me now, not sure why it's still breaking?

**Comment by melinath** [comment]
@DeviaVir TLDR TerraformVCRCommunity is marked as "failed" if it doesn't need to run, but you're fine because beta-provider-vcr-test has succeeded for you already. I'll take a look at the PR later today.

**Review by melinath — APPROVED** [review]

**Pull request merged**
