### PR TITLE
Adding support for multi-NIC network in GKE cluster and node pool.

### PR DESCRIPTION
**Pull request by soumyapani**
This PR is to add terraform support for multi-NIC network for GKE cluster and node pools.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
GKE: Add multi-NIC network for GKE clyster and node pool.
```

### CODE REVIEW

**Comment by soumyapani** [comment]
> 

fixed.

**Comment by trodge** [comment]
It looks like the fields you're adding aren't implemented in the container library yet. Any idea when they will be?

**Comment by soumyapani** [comment]
> It looks like the fields you're adding aren't implemented in the container library yet. Any idea when they will be?

Hi Thomas.
Yes, those APIs are not yet implemented and we are waiting on GKE networking team to release those APIs in the beta go package. So for now the PR is blocked on that.
ETA from GKE networking team is end of june.

**Comment by trodge** [comment]
Looks like this was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/8385

**Pull request closed without merging**
