### PR TITLE
feat: add location certificate map and entry

### PR DESCRIPTION
**Pull request by adriantr**
Solves https://github.com/hashicorp/terraform-provider-google/issues/19437

**Release Note Template for Downstream PRs (will be copied)**
```release-note:enhancement
certificatemanager: added `location` field to `google_certificate_manager_certificate_map` resource
```
```release-note:enhancement
certificatemanager: added `location` field to `google_certificate_manager_certificate_map_entry` resource
```

### CODE REVIEW

**Comment by adriantr** [comment]
@rileykarson hey, any take on this PR?🙏

**Comment by rileykarson** [comment]
Sorry- I've been very behind on reviews (and email, so it's taken a bit to identify the ones I need to take action on). Rolled a new reviewer.

**Comment by Hamzawy63** [comment]
Hi @adriantr, 

Thanks for your contribution, I hope it gets reviewed soon from Terraform team!

For the issue you mentioned though, I don't think this PR will fix https://github.com/hashicorp/terraform-provider-google/issues/19437 . Please refer to my comment to the issue https://github.com/hashicorp/terraform-provider-google/issues/19437#issuecomment-2413785588 and let me know if you have any questions.

**Review by roaks3 — COMMENTED** [review]
Per @Hamzawy63 's note, it looks like this may not actually work (as in, any location other than "global" would fail). Hamza is a member of the Certificate Manager service team.

@adriantr if you'd like to try to move this forward / confirm it is not possible, you'd need to do a few things:
1. Modify your changes to work with our Go generator (we are moving away from Ruby). See https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/. It should be relatively straightforward, but you will need to manually make some edits to get things working again. Apologies that this step is necessary, and let me know if you need help.
2. Add at least one test with a location other than "global". As of now, this PR does not attempt to use a different location, and while I would expect it to fail, it's possible we've missed something.

**Pull request closed without merging**
