### PR TITLE
Fix PubSub-to-BigQuery push configuration example

### PR DESCRIPTION
**Pull request by soar**
API expects a dot instead of a colon for "fully-qualified" BigQuery table name

```release-note:none
```

### CODE REVIEW

**Comment by soar** [comment]
@shuyama1 I can't open these log files - Forbidden Error 403

**Comment by shuyama1** [comment]
@soar The failing test is unrelated, please ignore it! Sorry for the noise.

About this change, do you run into any issues with the previous documented format? We changed from `.` to `:` a few months ago to fix https://github.com/hashicorp/terraform-provider-google/issues/12318 as `.` does not create the resource with correct delivery type.

**Comment by soar** [comment]
If I use `:` in the configuration, Terraform tries to change it from `.` (returned from the API) to `:` again and again.

**Comment by soar** [comment]
After some investigations, it looks like I found an issue:
1. Both cases (with dot and with colon) work fine from Terraform; a resource can be created, deleted, and updated; no drifts appear if you don't change the configuration; the string is saved to the API as is (dot/colon) without conversions;
2. If you create or update a subscription manually via UI, it is saved with a dot, and it will be returned from the API as a string with a dot. In this case, if you have a colon in the Terraform configuration, it will result in a drift in the state. With a dot, it will work fine.

**Comment by shuyama1** [comment]
Thanks @soar for the investigations. I've also tested and it seems that the API issue got fixed - with `.` in the config it also creates the resource with correct delivery type (while only `:` did in the past ), and API does return the path with dot after some manual modification outside Terraform no matter what format used initially with Terraform. So let's change back to `.` then. Would you mind rebasing your PR to kick in some new CI changes?

**Comment by shuyama1** [comment]
Let's move forward with this PR! Would you mind rebasing it?

**Review by shuyama1 — APPROVED** [review]
Thank you!

**Pull request merged**
