### PR TITLE
Add support for `google_compute_vpn_tunnel` to TGC

### PR DESCRIPTION
**Pull request by dvfons**
fixes b/337857591

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by zli82016** [comment]
on hold with the pending discussion with the service team.

**Comment by zli82016** [comment]
We will go forward with this PR after the tests are fixed. I updated the title and release note for this PR. 

The title should follow the format "Add support for {{resource}} to TGC" i.e. "Add support for google_compute_url_map to TGC".

The changelog (release note) should be typed none and left blank.


Please see more details in [this comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/10540#pullrequestreview-2044173640).

**Review by zli82016 — CHANGES_REQUESTED** [review]
The tests need to be fixed.

**Comment by zli82016** [comment]
Hello, @dvfons, do you mind reopening this PR to check the specific errors?

**Comment by zli82016** [comment]
@dvfons , can you please first resolve the conflicts? Thanks.

**Comment by dvfons** [comment]
@zli82016  i beleve that every thing ok

**Review by zli82016 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
