### PR TITLE
Update compute_security_policy documentation for type field 

### PR DESCRIPTION
**Pull request by NickElliot**
The documentation for the type field in this resource is out of sync with the [API docs](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies) and has been updated to be in sync.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by c2thorn — APPROVED** [review]
Was there a github tracking issue for this?

**Comment by NickElliot** [comment]
Not that I could see from searching through, I was given this issue through Buganizer.

**Comment by c2thorn** [comment]
> Not that I could see from searching through, I was given this issue through b/247000435.

@NickElliot no worries then! You have merge access right?

**Comment by NickElliot** [comment]
I have not been given it yet

**Comment by c2thorn** [comment]
@NickElliot I think you need access to https://github.com/orgs/GoogleCloudPlatform/teams/terraform-team via @rileykarson

**Comment by rileykarson** [comment]
Added to https://github.com/orgs/GoogleCloudPlatform/teams/terraform-collaborators/members (the team group is used for some review assignments so let's hold on that for now)

**Pull request merged**
