### PR TITLE
networksecurity/AddressGroup: remove unused custom code

### PR DESCRIPTION
**Pull request by LucaPrete**
Removes unused custom code in networksecurity/AddressGroup, as per [this discussion](https://github.com/GoogleCloudPlatform/magic-modules/pull/9800#discussion_r1451424324).

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
networksecurity: remove unused custom code from `google_network_security_address_group`
```

### CODE REVIEW

**Comment by LucaPrete** [comment]
@melinath FYI

**Review by NickElliot — APPROVED** [review]
from checking over the discussion in the referenced PR all looks good for this update, will go ahead with a merge soon

**Comment by LucaPrete** [comment]
Hi @NickElliot ! I still see the PR open but I don't see any merge button. Should we go ahead and merge?

**Comment by LucaPrete** [comment]
No worries at all and thanks for the review!

Il giorno lun 5 feb 2024 alle 19:43 Nick Elliot ***@***.***>
ha scritto:

**Pull request merged**
