### PR TITLE
Add new resource for creating Whistle Mapping, Reconciliation and Backfill Pipeline Jobs for Healthcare Data Engine

### PR DESCRIPTION
**Pull request by ashwinsshetty**
Add support for creating Whistle Mapping, Reconciliation and Backfill Pipeline for Healthcare Data Engine

Link: https://cloud.google.com/healthcare-api/healthcare-data-engine/docs/reference/rest/v1/projects.locations.datasets.pipelineJobs/create

Fixes https://github.com/hashicorp/terraform-provider-google/issues/19412

```release-note:new-resource
`google_healthcare_pipeline_job`
```

### CODE REVIEW

**Review by c2thorn — CHANGES_REQUESTED** [review]
Hi @ashwinsshetty 
The Magic Modules repository has recently migrated from Ruby to Go. You can view more details about this in our announcement here: https://github.com/hashicorp/terraform-provider-google/issues/19583 (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)

This open pull request has become incompatible due to most YAML and .erb files converting to Go-compatible files.

Our team (Magic Modules repository maintainers) has tooling to automatically convert changes to the new language, and we can prepare a new commit for this pull request that is compatible with the migration.

In order to push the new changes to your pull request, we would need to <ins>force push the commit to your fork's branch</ins>. Our tooling saves a backup branch before converting, so we could rollback or open a new pull request if needed. We would also work with you and the PR reviewer in the event additional changes are needed.

You also have the option to update the pull request yourself. You can view [updated documentation](https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/) related to the migration changes.

We will take no action until we have your explicit permission to push changes to your fork's branch used for this pull request. Let me or your reviewer know if you have any further questions!

**Comment by ashwinsshetty** [comment]
> updated documentation

Thanks for the note @c2thorn

Please go ahead with your process to force push the changes to my fork.

Please do let me know if any additional action would be required from my side on this.

cc @melinath @trodge

**Comment by c2thorn** [comment]
Got it converted, should be good to resume

**Comment by ashwinsshetty** [comment]
> Got it converted, should be good to resume

Thanks @c2thorn!

@melinath Please let me know if anything else would be required to get this merged.

**Review by melinath — COMMENTED** [review]
@ashwinsshetty how is this different than https://github.com/GoogleCloudPlatform/magic-modules/pull/11677? It looks like the same resource is being added.

**Comment by melinath** [comment]
oh, that was reverted.

**Comment by melinath** [comment]
Moving review to trodge as reviewer of the previous iteration.

**Review by trodge — APPROVED** [review]

**Comment by canuck3141** [comment]
Hey @ashwinsshetty - please see [Issue 24246](https://github.com/hashicorp/terraform-provider-google/issues/24246) as the PipelineJob tests are failing and blocking 20+ PRs due to failing tests like `TestAccHealthcarePipelineJob_healthcarePipelineJobBackfillExample`.  Can you help with a fix?  Does this PipelineJob resource even exist under healthcare any more (it does *not*, AFAICT)?  Any ideas how to fix?

cc: @trodge as original approver

**Pull request merged**
