### PR TITLE
Add WEIGHTED_MAGLEV to localityLbPolicy enum, and update associated docstrings.

### PR DESCRIPTION
**Pull request by uberferg**
This PR adds WEIGHTED_MAGLEV to the enum for localist_lb_policy, resolving b/272540261 and unblocking NetLB Weighted Load Balancing GA.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:enhancement
compute: added `WEIGHED_MAGLEV` to `locality_lb_policy` enum for backend service resources.
```

### CODE REVIEW

**Review by roaks3 — COMMENTED** [review]
Changes look good to me (and sorry for the delay).

The one thing I wanted to check in on before approving: can you help me understand which parts of this are beta-only? I was expecting either:
1. All additions being GA
2. The new enum being marked in the description as "beta only" in some way

**Comment by roaks3** [comment]
Ah ok, yep, the `min_version: beta` line means that a test will only be generated for the beta version of the provider. So in this case, the test you've added would not be run for the regular `terraform-provider-google`, which is probably not ideal. If you can remove that line and have this test run for both providers, you'll also want to remove `provider = google-beta`, as it is only needed to ensure the beta version of the resource is used.

**Comment by roaks3** [comment]
Oh also, now that I'm seeing the conflict, we made a project-wide change that will require you to move the config you have in `terraform.yaml` to the `RegionBackendService.yaml`, after a rebase.

**Comment by uberferg** [comment]
Thanks for the explanation. In hindsight, it makes sense to me that `min_version: beta` would exclude GA, since beta > GA, but at the time, for some reason I thought the opposite, haha.

Think I made all the requested changes, and included the updated changes from main. PTAL.

**Comment by uberferg** [comment]
Just fixed the test. Sorry about that, I was negligent and didn't re-run tests after the merge yesterday.

**Review by roaks3 — APPROVED** [review]
Oh no worries, thanks for fixing. LGTM

**Pull request merged**
