### PR TITLE
Remove unneeded Optional schema behaviour in `email` field of `google_project_service_identity`

### PR DESCRIPTION
**Pull request by SarahFrench**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/13227

In the `google_project_service_identity` resource the email is computed but the field has `Optional: true` set in the schema. 

I added this mistakenly in https://github.com/GoogleCloudPlatform/magic-modules/pull/6192 when I changed the resource to handle scenarios when the API did not return a value for the email field

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
serviceusage: removed unneeded Optional schema behaviour from `email` field in `google_project_service_identity` (beta)
```

### CODE REVIEW

**Comment by SarahFrench** [comment]
> If you believe this detection to be incorrect please raise the concern with your reviewer.

This field was never able to be set from the config and was only ever computed - this PR is fixing a mistake in the schema

**Review by slevenick — APPROVED** [review]

**Comment by SarahFrench** [comment]
I'm going to save merging this until Feb 20th onwards because I'm about to go on PTO and I'd like to be around just in case this change causes questions to be raised when cutting a new release.

**Comment by SarahFrench** [comment]
Going to merge now :shipit:

**Pull request merged**
