### PR TITLE
Handwrite sweepers for networkConnectivity hubs and spokes

### PR DESCRIPTION
**Pull request by hao-nan-li**
fixes [17420](https://github.com/hashicorp/terraform-provider-google/issues/17420)
Tested locally and the new sweeper cleans up the resource

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by melinath — APPROVED** [review]

**Comment by melinath** [comment]
LGTM but why is this change needed exactly?

**Comment by hao-nan-li** [comment]
> LGTM but why is this change needed exactly? Like, what was the core change needed?

These resources are not swept properly, and compute networks could not be deleted because they are used by networkConnectivity spokes.

**Comment by melinath** [comment]
@hao-nan-li right, but why were they not getting swept properly? What did you change to make them get swept properly?

**Comment by hao-nan-li** [comment]
> @hao-nan-li right, but why were they not getting swept properly? What did you change to make them get swept properly?

These resources were generated from DCL, and the generated sweeper was not sending the delete request. I've overridden the sweepers.

**Pull request merged**
