### PR TITLE
Improve Datastream Stream creation doc

### PR DESCRIPTION
**Pull request by sagiyosefia**
Improve Datastream Stream creation configuration example, by adding an example to configure multiple include objects
b/307440603

```release-note:none

```

### CODE REVIEW

**Comment by roaks3** [comment]
@sagiyosefia this seems reasonable, but I'm curious if there is an associated internal or external ticket. Why are we making this change? Perhaps the "multiple objects" config is not clear for users?

**Comment by sagiyosefia** [comment]
> @sagiyosefia this seems reasonable, but I'm curious if there is an associated internal or external ticket. Why are we making this change? Perhaps the "multiple objects" config is not clear for users?

We have an internal ticket, to update our API & TF docs with this example. I wasn't sure how/if to add the ticket to here

**Comment by roaks3** [comment]
@sagiyosefia Ok, sounds good. We include "b/XXXX" links on GitHub regularly to reference internal tickets, and I think it would be helpful to add that here (as reviewers, it helps us understand what we are reviewing).

Approving in the meantime because this seems fine based off of your rationale alone.

**Review by roaks3 — APPROVED** [review]

**Comment by sagiyosefia** [comment]
Add the ticket.
Why the "merge" button is still doesn't appear after your approval?

**Comment by roaks3** [comment]
👍 after approval, the reviewer is responsible for merging the PR. I just merged, so this should make in the next release.

**Pull request merged**
