### PR TITLE
Promote InstanceSettings compute resource to GA.

### PR DESCRIPTION
**Pull request by arungantasala**
Background: Support for Instance Settings resource in beta has been added in PR #9313 . This resource has been recently promoted to GA.  

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: promoted `google_compute_instance_settings` to GA
```

### CODE REVIEW

**Comment by shuyama1** [comment]
@arungantasala Sorry, there's an issue in our CI. Would you mind rebasing your PR to catch the latest fix? Thank you!

**Review by NickElliot — APPROVED** [review]
verified GA update, LGTM

**Pull request merged**
