### PR TITLE
Add a vacation for trodge

### PR DESCRIPTION
**Pull request by trodge**
Adds my vacation from Saturday Aug 24 to Monday Sep 2

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Review by slevenick — APPROVED** [review]
Not sure why the contributor checker failed?

**Comment by trodge** [comment]
> Not sure why the contributor checker failed?

Probably because I rejected the downsteam generation, since this is a CI-only change.

**Review by melinath — APPROVED** [review]

**Comment by shuyama1** [comment]
> > Not sure why the contributor checker failed?
> 
> Probably because I rejected the downsteam generation, since this is a CI-only change.
> 
> Edit- speaking of this being a CI change, @shuyama1 @c2thorn

Thanks for flagging! Should be good.

**Comment by shuyama1** [comment]
Looks like 6.0 merge will be starting soon, Let's wait until it's finished to merge this PR if it's not urgent.

**Comment by trodge** [comment]
> Looks like 6.0 merge will be starting soon, Let's wait until it's finished to merge this PR if it's not urgent.

It's not urgent, I'll just re-assign if I get review requests next week.

**Comment by melinath** [comment]
We should definitely merge this before then; you are not responsible for reassigning reviews while on vacation :-)

**Comment by trodge** [comment]
> We should definitely merge this before then; you are not responsible for reassigning reviews while on vacation :-)

In that case we'd need to merge https://github.com/GoogleCloudPlatform/magic-modules/pull/11445 as well, and confirm that what I did [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/11445/files#r1718962621) actually works.

**Pull request merged**
