### PR TITLE
Ansible modules: rename _facts -> _info

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes generator side of ansible/ansible#57277.

I haven't found out how to adjust the integration tests (they still use `_facts`). Also, parts of the generated code are formatted differently than in Ansible itself (`argument_spec`, `ANSIBLE_METADATA`); that was already the case before I modified anything.

### CODE REVIEW

**Comment by felixfontein** [comment]
I don't think I can sign the CLA since I don't have a Google account. You will have to do the renaming yourself, then. The main modifications you can find in this PR or in other rename PRs such as ansible/ansible#57668

Modules added for 2.9 only need to be renamed, older modules need the additional nodes/code. For older modules, there should also be a symlink `_name_facts.py` pointing to `name_info.py`. This will ensure the old name can still be used, and that Ansible knows the old name is deprecated. (A documentation stub will be created for it.)

If you have any questions, feel free to ping me here or on IRC (Freenode).

**Comment by felixfontein** [comment]
(Also, a changelog fragment and a porting guide entry is needed for the commit in ansible/ansible; see ansible/ansible#57668 or ansible/ansible#57651 for how that should look like)

**Comment by rambleraptor** [comment]
Thanks a lot for doing this! I'll go ahead and make the changes from here.

**Comment by felixfontein** [comment]
You're welcome! :)

BTW, not all _facts modules have to be renamed to _info. This is only about _facts modules which do not return `ansible_facts`, or which return something which is not specific to the host where the module runs on. Which means that in particular all cloud _facts modules should be _info modules.

**Pull request closed without merging**
