### PR TITLE
Fix patching in stateful disks1

### PR DESCRIPTION
**Pull request by askubis**
Add possibility to remove Stateful Disks by using Null Values.
resolves https://github.com/hashicorp/terraform-provider-google/issues/10266

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:bug
compute: added possibility to remove `stateful_disks` in `compute_instance_group_manager` and `compute_region_instance_group_manager`.
```

### CODE REVIEW

**Comment by hao-nan-li** [comment]
@askubis We've made an update to fix some potential security issue. That most likely caused the build to fail. Could you do a rebase on the main branch?

**Comment by askubis** [comment]
@hao-nan-li I did that, PLMK if I should do something more.

**Comment by hao-nan-li** [comment]
LGTM in general as the logic for disk deletion matches what's for the stateful_ips.
* Don't worry for the failing VCR-test
* Could you change the release note to follow the format in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md? Thanks!

**Comment by askubis** [comment]
Updated the release note, thanks!

**Comment by hao-nan-li** [comment]
Thanks for updating the release note. There's still some slight modification to do to match the format, don't worry I'll edit it.
LGTM in general. 

Add @zli82016 to sign off since she helped to review the stateful_ips

**Review by zli82016 — APPROVED** [review]
LGTM

**Review by hao-nan-li — APPROVED** [review]

**Pull request merged**
