### PR TITLE
Add Ansible to supported providers in README

### PR DESCRIPTION
**Pull request by rosbo**

### CODE REVIEW

**Comment by nelsonjr** [comment]
Should we also add details on how to test (or at least link to the other section)?

**Comment by rosbo** [comment]
I will add "make test" and "make testacc" for terraform. 

@rambleraptor what is the command to run tests inside the Ansible folder?

**Comment by rambleraptor** [comment]
Two commands for running tests on Ansible:

`ansible-test sanity --docker --python 2.7` for running linters + the like
`ansible-test integration -v <module_name>` for running integration tests.

**Comment by rambleraptor** [comment]
<module name> refers to a GCP resource.

Examples: gcp_compute_address, gcp_compute_backend_service, etc.

**Pull request merged**
