### PR TITLE
bigquery table - add `reference_file_schema_uri`

### PR DESCRIPTION
**Pull request by DrFaust92**
If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery_table - add `reference_file_schema_uri`
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
I took a sample but I can try to generate fake one line

**Comment by DrFaust92** [comment]
@c2thorn done, ive generated and tested locally with this code:

```
df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
df.to_parquet('df.parquet.gzip',
              compression='gzip')  
```

**Comment by c2thorn** [comment]
@DrFaust92 Can you unzip the file? Apologies as I can't get it to uncompress on my test machine

**Comment by DrFaust92** [comment]
@c2thorn this a binary file. Not sure what you want uncompress, what are you trying to achieve?

**Comment by DrFaust92** [comment]
@c2thorn i can recreate the same file without gzip but i dont think its relevant. it was genrated with python as ive mentioned here https://github.com/GoogleCloudPlatform/magic-modules/pull/7084#issuecomment-1374397960

**Comment by c2thorn** [comment]
> @c2thorn i can recreate the same file without gzip but i dont think its relevant. it was genrated with python as ive mentioned here [#7084 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/7084#issuecomment-1374397960)

Thanks for the highlighting that, I completely missed that comment. I was able to confirm the contents with `pd.read_parquet('test.parquet.gzip')` in python

**Comment by c2thorn** [comment]
running the test in a separate build as I don't think the new file retriggered a VCR recording

**Review by c2thorn — APPROVED** [review]
test passed and LGTM. thanks again for your contribution and patience!

**Pull request merged**
