### PR TITLE
adding support for Cloud Dataplex Entry Type resource.

### PR DESCRIPTION
**Pull request by avijain25**
Adding Terraform support for a Dataplex Entry Type resource.
Tracking issue: https://github.com/hashicorp/terraform-provider-google/issues/18146

```release-note:new-resource
`google_dataplex_entry_type`
```

### CODE REVIEW

**Review by SarahFrench — COMMENTED** [review]
Hi @avijain25, thanks for your PR! The tests look comprehensive and are passing, but before approving I would usually compare API documentation to the contents of `mmv1/products/dataplex/EntryType.yaml` to check for errors. I can find any public-facing documentation for this new resource - is any available?

Note: I'm going to ignore [the missing test detector message here](https://github.com/GoogleCloudPlatform/magic-modules/pull/10757#issuecomment-2123424921) about IAM-related resources; those tests are generated so aren't in scope for this PR.

**Comment by avijain25** [comment]
> Hi @avijain25, thanks for your PR! The tests look comprehensive and are passing, but before approving I would usually compare API documentation to the contents of `mmv1/products/dataplex/EntryType.yaml` to check for errors. I can find any public-facing documentation for this new resource - is any available?
> 
> Note: I'm going to ignore [the missing test detector message here](https://github.com/GoogleCloudPlatform/magic-modules/pull/10757#issuecomment-2123424921) about IAM-related resources; those tests are generated so aren't in scope for this PR.

Similar PRs for the same GA release(just for reference):
https://github.com/GoogleCloudPlatform/magic-modules/pull/10721
https://github.com/GoogleCloudPlatform/magic-modules/pull/10751
https://github.com/GoogleCloudPlatform/magic-modules/pull/10756

Looking to find public documentation.

**Comment by avijain25** [comment]
@SarahFrench Thanks for the review. We are still working on the public documentations for the feature. 

However, [this](https://github.com/googleapis/google-cloud-java/blob/main/java-dataplex/google-cloud-dataplex/src/main/java/com/google/cloud/dataplex/v1/CatalogServiceClient.java) is our client library reference.

We want to merge the PR by end of this week, so that terraform integration can make it to our GA release(May end).

**Review by SarahFrench — APPROVED** [review]
Approving based on tests passing 🚢

**Pull request merged**
