### PR TITLE
Fix client request only properties.

### PR DESCRIPTION
**Pull request by rohitjangid**
Fix client request only properties to ignore read from api. Update examples to match actual usage.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Review by SarahFrench — COMMENTED** [review]
Thanks @rohitjangid ! This PR looks ok to merge, but I wanted to check: is this fixing a user-facing issue?

I want to make sure the release note is accurate. If this PR just changes tests and internals of the resource in a way that's not noticeable to users I'd remove the release note. If there is a bug that's fixed by this PR I can update the release note to describe it

**Comment by rohitjangid** [comment]
@SarahFrench This resource is not yet released in the latest terraform provide version. Since this is not being used by any users, there is no user impact.

**Review by SarahFrench — APPROVED** [review]
Looks good - I've set the release note to `none` as I understand this isn't fixing a user-facing issue

**Pull request merged**
