### PR TITLE
feat: Add ssl_mode option to google_sql_database_instance.

### PR DESCRIPTION
**Pull request by feng-zhe**
This PR adds support for the new field ssl_mode to google_sql_database_instance. This new field is only available for google.golang.org/api v0.148.0 or after. Acctests are added for each database types and they all passed.

This is almost the same as the previous [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/9316) but this one adds `Computed: true` to the `ssl_mode` field so that its old value will be used in requests.

Tested the following tests which were broken by the previous PR but they are passing in this PR:

- TestAccDatastreamConnectionProfile_update
- TestAccSqlDatabaseInstance_Smt

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
sql: added `ssl_mode` field to `google_sql_database_instance` resource
```

### CODE REVIEW

**Comment by NickElliot** [comment]
passing review to @roaks3 as a followup of previous iteration of this PR

**Comment by roaks3** [comment]
Confirmed that `TestAccDatastreamConnectionProfile_update` passed locally, which is an unrelated test that had previously failed due to this change.

Will wait for VCR tests, but this should be ready for merge otherwise.

**Review by roaks3 — APPROVED** [review]

**Comment by shiva0010** [comment]
Im not able to use ssl_mode inside google_sql_database_instance module.
Getting below error
 Error: Unsupported argument
│
│   on main.tf line 52, in resource "google_sql_database_instance" "default":
│   52:     ssl_mode                                      = "ENCRYPTED_ONLY"
│
│ An argument named "ssl_mode" is not expected here.
Screenshot 2023-12-30 at 1 14 04 AM

**Comment by roaks3** [comment]
@shiva0010 could you please open an issue if you are experiencing a problem with the field? That will make it much easier to track discussion and resolution.

**Pull request merged**
