### PR TITLE
Change to Required API Call from Percentage to Percent

### PR DESCRIPTION
**Pull request by invalidbassist**
This resolves issue: https://github.com/hashicorp/terraform-provider-google/issues/7612

Where API calls to the OS config patch api is incorrect in the provider

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Bug:** fixing google_os_config_patch_management resource

```release-note:bug
rollout block: updated expected `disruption_budget` key from `percentage` which the API does not expect to `percent` which the API does expect
```

### CODE REVIEW

**Comment by invalidbassist** [comment]
@googlebot I signed it!

**Comment by invalidbassist** [comment]
@googlebot I fixed it!

**Comment by invalidbassist** [comment]
@googlebot I fixed it!

**Review by rileykarson — COMMENTED** [review]
It looks like you've got two emails associated with your commits. The one in this patch is missing a CLA: https://github.com/GoogleCloudPlatform/magic-modules/commit/9290a6d66144a8a7dcdf458fb4997eaafcd44e93.patch

**Comment by invalidbassist** [comment]
Fixing author issues on commit to comply with CLA

**Pull request closed without merging**
