### PR TITLE
Promote PSC global access to GA

### PR DESCRIPTION
**Pull request by hao-nan-li**
Promote PSC global access to GA

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
compute: promoted `allowPscGlobalAccess` field to GA for resource `google_compute_forwarding_rule`
```

### CODE REVIEW

**Comment by hao-nan-li** [comment]
[psc.log](https://github.com/GoogleCloudPlatform/magic-modules/files/11559624/psc.log)

**Comment by ScottSuarez** [comment]
Is there an associated bug for this? Wondering how you came across/triaged it.

**Comment by hao-nan-li** [comment]
> Is there an associated bug for this? Wondering how you came across/triaged it.

https://b.corp.google.com/issues/281743258

**Comment by ScottSuarez** [comment]
Should all the tests be updated to run in GA. Doesn't seem there are any beta properties left.

**Comment by hao-nan-li** [comment]
> Should all the tests be updated to run in GA. Doesn't seem there are any beta properties left.

Looks like `TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate` is auto-generated with provider `google-beta` even if I promote the test `TestAccComputeForwardingRule_forwardingRuleVpcPscExample` to GA. You can see the PR history as these tests were failing. Any suggestion on how to fix them?

**Comment by hao-nan-li** [comment]
> > Should all the tests be updated to run in GA. Doesn't seem there are any beta properties left.
> 
> Looks like `TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate` is auto-generated with provider `google-beta` even if I promote the test `TestAccComputeForwardingRule_forwardingRuleVpcPscExample` to GA and changing the provider from `google-beta` to `google`. You can see the PR history as these tests were failing. Any suggestion on how to fix them?

I think I found out a solution overnight, will make the change shortly.

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
Looks like unit tests / ga build are failing

**Comment by hao-nan-li** [comment]
> Looks like unit tests / ga build are failing

Thanks for pointing it out, I'm currently checking what's wrong locally.

**Comment by ScottSuarez** [comment]
Why remove an update test?

**Review by ScottSuarez — APPROVED** [review]

**Pull request merged**
