### PR TITLE
If not specified, a default Workstations service agent SA is returned

### PR DESCRIPTION
**Pull request by bschaatsbergen**
Closes #7411 

According to the API spec:

> Email address of the service account that will be used on VM instances used to support this config. This service account must have permission to pull the specified container image. If not set, VMs will run without a service account, in which case the image must be publicly accessible.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
workstations:  fixed if `service_account` in  `google_workstations_workstation_config` isn't set, a default is set.
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Quick question:

The field `serviceAccount` now has `input:true`, the API spec suggests it's rather an optional field as a default will be set if the attribute isn't set. Should we remove the `input:true` ?

**Review by hao-nan-li — COMMENTED** [review]
`input:true` means this field is not updatable. I would rather leave it as it is.
Don't worry about the failed test.
Could you update the release note based on https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md? Thanks!

**Comment by bschaatsbergen** [comment]
> `input:true` means this field is not updatable. I would rather leave it as it is. Don't worry about the failed test. Could you update the release note based on https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md? Thanks!

Fixed!

**Comment by hao-nan-li** [comment]
LGTM, adding @roaks3 to sign off as this PR referenced one of his PR.

**Comment by roaks3** [comment]
Looks good! Two requests from me:
1. Since this is intending to fix the test, would you mind reversing https://github.com/GoogleCloudPlatform/magic-modules/pull/7415/files and including that in this PR? That should also allow it to be triggered in the VCR tests for this PR (where we can then run it more than once to make sure it records/replays properly).
2. I think this PR should close https://github.com/hashicorp/terraform-provider-google/issues/13923 instead of my draft PR. If everything looks good in this PR's VCR, and other PRs after it's merged, I can just close that draft PR on my own.

**Comment by bschaatsbergen** [comment]
Fixed, could you `/gcbrun` this PR @roaks3 :) ?

**Comment by roaks3** [comment]
Looks like this timed out at 90 mins and I'm not really sure why. Going to re-run to see if it was a one-off.

**Comment by roaks3** [comment]
Re-running once more to verify`TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample` is properly recorded and replayed.

**Comment by roaks3** [comment]
@bschaatsbergen it looks like your change has the test passing now, but it continues to be re-tried on every gcbrun (which will cause it to run for all new PRs unnecessarily). I think there are probably 2 options:
1. Wrap up this changeset more quickly by adding `skip_vcr: true` where `skip_test` used to be. The test will run in the nightly tests, but not in PRs until we fix that piece.
2. Try to fix the VCR runs to record properly. My best guess so far is that https://github.com/GoogleCloudPlatform/magic-modules/pull/7411 will fix the issue or perhaps get us closer, so you could try making that change in this PR.

**Comment by bschaatsbergen** [comment]
@roaks3, I've removed the rotation_period as suggested in your 2nd option.

**Review by roaks3 — APPROVED** [review]
Looks resolved since the test did not have to be recorded on the second run above. We can probably let the checks finish, but for me it is ready to merge 👍

**Pull request merged**
