### PR TITLE
Update to go 1.21

### PR DESCRIPTION
**Pull request by SarahFrench**
Closes https://github.com/hashicorp/terraform-provider-google/issues/17481

To be merged in coordination with:
- https://github.com/GoogleCloudPlatform/magic-modules/pull/10175
- https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/2043
    - See also : https://github.com/hashicorp/terraform-provider-google/issues/17480

---

This PR bumps the Google providers to using Go 1.21. We tend to keep 1 version behind the latest Go version and [Go 1.22 was releases on 6 Feb 2024](https://go.dev/blog/go1.22).

This upgrade unblocks a dependency bump that requires Go 1.21 : https://github.com/GoogleCloudPlatform/magic-modules/pull/10109#discussion_r1511757636

Through doing this PR I will use the experience to document the steps needed when bumping the Go version.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by SarahFrench** [comment]
I've created this PR in TGC which is linked to this PR by the automation/CI updates : https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/2043

**Comment by SarahFrench** [comment]
I think checks have failed due to a knock-on effect of the evil build killer:

>  Error: A branch or tag with the name 'auto-pr-10169' could not be found

**Comment by SarahFrench** [comment]
I'm separating out the changes to Dockerfiles to a separate PR

**Comment by ScottSuarez** [comment]
Notice, Make sure to update all github workflows as well before merging this
https://github.com/GoogleCloudPlatform/magic-modules/blob/a6ceb9e3c35210af4ecfaee801958eb7b79ac377/.github/workflows/test-tgc.yml#L83

**Review by ScottSuarez — CHANGES_REQUESTED** [review]
Please update any github workflow GO versions
https://github.com/GoogleCloudPlatform/magic-modules/blob/a6ceb9e3c35210af4ecfaee801958eb7b79ac377/.github/workflows/test-tgc.yml#L83

**Comment by SarahFrench** [comment]
@ScottSuarez I can't see the problem in /test-tgc.yml like in your review, but I found a different missing spot where the version wasn't updated

**Comment by SarahFrench** [comment]
(Addressing merge conflicts with main)

**Comment by SarahFrench** [comment]
Seeing the `  Error: A branch or tag with the name 'auto-pr-10169' could not be found` problem again - /gcbrun

**Pull request merged**
