### PR TITLE
Adds repository field to git_file_source and source_to_build of googl…

### PR DESCRIPTION
**Pull request by mariomachado94**
…e_cloudbuild_trigger resource

Adds repository field to git_file_source and source_to_build of google_cloudbuild_trigger resource

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note: enhancement
cloudbuild: added `git_file_source.repository` and `source_to_build.repository` fields to `google_cloudbuild_trigger` resource (beta)
```

### CODE REVIEW

**Comment by c2thorn** [comment]
Hi @mariomachado94 what was the difference between the last two pushes? What caused `TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample` to pass this time?

**Comment by mariomachado94** [comment]
Hey @c2thorn, I had to apply a visibility label (GCB_ALPHA) to the test project. Then repushed a no-diff change just to retest.

**Comment by c2thorn** [comment]
@mariomachado94 So users trying to use this field without the flag won't be successful either?
Judging from the initial test result, it looks like without the flag there is a perma-diff instead of an error indicating that it is an Alpha-only field. If I wasn't able to figure it out, how can we expect users? Should it at least be labelled as such in the documentation?

**Comment by mariomachado94** [comment]
I hear you. I should mention that this visibility label should be removed any day now. I suppose we should just wait until that change is in the backend.

When that is done, Ill re-push since I should probably remove the "google-beta" block in the test as I dont need to set the user_project_override.

provider "google-beta" {
    user_project_override = true
}

**Comment by c2thorn** [comment]
@mariomachado94 I think that is a solid plan, thanks for clearing it up!

**Comment by mariomachado94** [comment]
@c2thorn this is ready to go if it looks good to you.

**Review by c2thorn — APPROVED** [review]

**Pull request merged**
