### PR TITLE
Bq capacity commitment

### PR DESCRIPTION
**Pull request by DrFaust92**
Closes https://github.com/hashicorp/terraform-provider-google/issues/6694

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_bigquery_reservation_capacity_commitment
```

### CODE REVIEW

**Comment by slevenick** [comment]
Test fails with         Error: Error creating ReservationCapacityCommitment: googleapi: Error 400: slot_count must be positive.

**Comment by slevenick** [comment]
Failing with: 
          # google_bigquery_reservation_capacity_commitment.commitment will be updated in-place
          ~ resource "google_bigquery_reservation_capacity_commitment" "commitment" {
              + plan                   = "FLEX"
              ~ slot_count             = 0 -> 100
                # (4 unchanged attributes hidden)
            }

Looks like slot_count isn't coming back from the API or something like that? Are you seeing this pass locally?

**Comment by DrFaust92** [comment]
@slevenick have an issue testing as it might incur very high costs /:

**Comment by slevenick** [comment]
> @slevenick have an issue testing as it might incur very high costs /:

Yeah, can you change the slot_count to 1? I'm assuming that makes this more or less expensive to run in CI.

I looked at the logs, it seems like we need to change `create_url: projects/{{project}}/locations/{{location}}/capacityCommitments?capacityCommitmentId={{capacityCommitmentId}}` -> `create_url: projects/{{project}}/locations/{{location}}/capacityCommitments?capacityCommitmentId={{capacity_commitment_id}}`

We are currently creating with no commitment ID, so it gets a random one and then we don't call GET correctly.

**Pull request closed without merging**
