### PR TITLE
Improve VCR logging

### PR DESCRIPTION
**Pull request by shuyama1**
- pre install Terraform
- changed content type to `text/plain`
- added direct link to test log

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
I think we use terraform 0.12.31 in the official team city tests. I could be wrong though

**Comment by shuyama1** [comment]
Let me double check. Thanks for reviewing it @ScottSuarez

**Comment by shuyama1** [comment]
Looks we have `env.TF_VERSION` set to 0.14.8 in team city VCR tests.
https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr?buildTypeTab=buildTypeSettings#all-projects

**Comment by ScottSuarez** [comment]
Hmm `TF_INSTALL` is set to 0.12.30 while `TF_VERSION` is set to 0.14.8 ... not sure what the discrepancy is here.

@megan07  could you confirm which version of terraform we are utilizing in teamcity.

**Comment by rileykarson** [comment]
If anything we should see if `1.1.8` works imo (but checking a few diff. versions may yield different results re: speed)

**Comment by megan07** [comment]
Going off memory I remember we updated to use `0.14.8` in Team City, so I'm inclined to say that `TF_VERSION` is the variable we key off of. I'm not sure what `TF_INSTALL` is used for.
I would agree that we should use `1.1.8`, I think the only reason we're not in Team City is because we haven't taken the time to update it, but I can do that whenever.

**Pull request merged**
