### PR TITLE
Add SHARED_LOADBALANCER_VIP purpose to regional addresses.

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7652

The docs are all over the place.

`gcloud compute addresses create foo --purpose SHARED_LOADBALANCER_VIP --project REDACTED --region europe-west6 --subnet default  --log-http` works so I have made all 3 available at GA level.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added SHARED_LOADBALANCER_VIP as a valid option for `google_compute_address.purpose`
```

### CODE REVIEW

**Comment by upodroid** [comment]
Forgot about that, pushed a commit now.

**Review by rileykarson — COMMENTED** [review]
We'll also have to strip this line: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/templates/terraform/examples/address_with_shared_loadbalancer_vip.tf.erb#L2

**Comment by upodroid** [comment]
bump

**Review by rileykarson — APPROVED** [review]
Sorry! I get notified on comments but not pushes (they're extremely noisy in practice) so I missed this. LGTM.

**Review by rileykarson — APPROVED** [review]
Sorry about the delay on my part! LGTM

**Pull request merged**
