### PR TITLE
Stateful ips ga

### PR DESCRIPTION
**Pull request by askubis**
This promotes Stateful IPs functionalities to GA . Modifies (Region)InstanceGroupManagers and (Region)PerInstanceConfigs. 
fixes #10908

If this PR is for Terraform, I acknowledge that I have:

 Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
 Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
 [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [make test and make lint](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
 [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
While running the tests one of them fails (TestAccInstanceGroupManager_waitForStatus), but it does not use the new field and it simply times out.
 Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.
Release Note Template for Downstream PRs (will be copied)

```release-note:enhancement
compute: promoted `internal_ip` and `external_ip` fields in resources `google_compute_instance_group_manager` and `google_compute_region_instance_group_manager` to GA
```
```release-note:enhancement
compute: promoted `internal_ip` and `external_ip` fields in resources `google_compute_per_instance_config` and `google_compute_region_per_instance_config` to GA
```

### CODE REVIEW

**Review by roaks3 — APPROVED** [review]
LGTM assuming tests pass. I've also tweaked the release note to be more consistent with our other GA promotions

**Comment by askubis** [comment]
I have added all changes I noticed to go.sum in the terraform-provider-google, PLMK if this isn't the way to do this correctly.

Regards,
Adam

**Comment by roaks3** [comment]
Ah yep, I didn't get around to sharing the build error, but it does look like a go.sum issue. I'll re-run tests to see if that fixes it.

**Comment by roaks3** [comment]
```
Step #22 - "gcb-tpg-vcr-test": go: updates to go.mod needed; to update it:
Step #22 - "gcb-tpg-vcr-test": 	go mod tidy
```

Looks like you'll need to run `go mod tidy` and try again with the updated go.sum

**Comment by askubis** [comment]
I've fixed the go.sum, thanks for your help!
I think the "Breaking Change(s) Detected" notice is wrong. I don't see the changes it sais are there.

**Review by roaks3 — APPROVED** [review]
LGTM, thanks for working through the dependency issues

**Pull request merged**
