### PR TITLE
[Datastream] BigQuery data staleness defaults to '900s'

### PR DESCRIPTION
**Pull request by marblejenka**
For https://github.com/hashicorp/terraform-provider-google/issues/18693

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
datastream: BigQuery data staleness defaults to '900s'
```

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Error: "Property 'default_value' is 'Integer' instead of 'String' (RuntimeError)"

**Comment by slevenick** [comment]
Please see https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes/#field-level-breaking-changes

This could potentially be made in the 6.0.0 release which is coming up, but you will need to target that branch instead of main

**Review by slevenick — CHANGES_REQUESTED** [review]
See previous comment

**Comment by marblejenka** [comment]
@slevenick I think if we put  `override-breaking-change` for this PR, it can be merged.

**Comment by slevenick** [comment]
Unfortunately we missed the window for breaking changes for 6.0.0. I was OOO when you switched to the 6.0 branch and the window was closed by the time I came back. Sorry about this! We won't be able to make this change until 7.0.0 now

**Pull request closed without merging**
