### PR TITLE
Add Logging Sink data source.

### PR DESCRIPTION
**Pull request by averbuks**
New data source `google_logging_sink` added. It allows retrieving information about a Log Sink. The main use case to get Log Sink writer identity to grant it with permissions on the destination or to put the identity into VPCSC access level (for org, folder or billing account sinks). 

Internal reference: b/268081935
Related external issue: https://github.com/hashicorp/terraform-provider-google/issues/12083 

If this PR is for Terraform, I acknowledge that I have:

- [ x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
`google_logging_sink`
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Hi, could you pull in the latest changes from main.. We had some CI changes recently that are needed

**Comment by averbuks** [comment]
> Hi, could you pull in the latest changes from main.. We had some CI changes recently that are needed

Done

**Comment by ScottSuarez** [comment]
Hmm, strange.. I'm not seeing your test running in the list of failed test `TestAccDataSourceGoogleLoggingSink_basic` Since we don't have a recording for this test I would expect it to be there.

**Comment by averbuks** [comment]
> Hmm, strange.. I'm not seeing your test running in the list of failed test `TestAccDataSourceGoogleLoggingSink_basic` Since we don't have a recording for this test I would expect it to be there.

Not sure I understand, `TestAccDataSourceGoogleLoggingSink_basic` is not in the list of failed tests because it's passing fine. Recording shows only one failing test which is `TestAccDataSourceDnsManagedZone_basic`, I see it's failing in every PR and related to the domain validation. 
Maybe I just misunderstood.

**Review by ScottSuarez — APPROVED** [review]
Ack, makes sense to me. No concerns.. Ran test locally. Everything looks green here

**Pull request merged**
