### PR TITLE
Adresssing Terraform provider issue 8732

### PR DESCRIPTION
**Pull request by thomascrowley**
https://github.com/hashicorp/terraform-provider-google/issues/8732

I am raising this to address the issue in the terraform provider [8732](https://github.com/hashicorp/terraform-provider-google/issues/8732)
I originally raised [this PR](https://github.com/hashicorp/terraform-provider-google/pull/8734) against the TF provider but have been advised to make this change. 

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

### CODE REVIEW

**Comment by c2thorn** [comment]
@ThomasAntoniusCrowley Hey thanks for taking the time to do this. I see this is still set as a Work In Progress, so feel free to ping me when it is ready. Also, if you have a chance to take a look at the CLA too that would be great!

**Comment by thomascrowley** [comment]
@googlebot I signed it!

**Comment by thomascrowley** [comment]
hey, @c2thorn apologise for the noob question, but this is my first contribution. I'm having trouble running the tests, could you give me some pointers on what I should be running?

**Comment by c2thorn** [comment]
To build the provider you'll want to checkout this section: https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools
Then you'll want to follow these steps to run the tests: https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests
The test you'll want to run is `TestAccComputeRegionTargetHttpProxy_regionTargetHttpProxyBasicExample`

**Comment by thomascrowley** [comment]
Hey @c2thorn thanks for your help, I managed to run the tests. I also ran `make lint` against the terraform code but it flagged things unrelated to my change is that ok?

**Review by c2thorn — APPROVED** [review]
This looks great, and the test passed on our end. Thanks!

**Pull request merged**
