### PR TITLE
Fixed a problem in which only ConfigId was calculated first when the API parameter was set to Known After Apply

### PR DESCRIPTION
**Pull request by oshiro3**
If certain attributes such as protoc_output_base64 are modified, the config_id is pre-computed, but if these attributes are (known after apply) at plan time and there is no diff as a result of apply, the plan result will not match, Error: Provider produced inconsistent final plan.
Therefore, if these attributes are modified and their values are non-deterministic, the config_id is now also calculated at apply time.

The added test case has the dependency endpoints <- key2 <- key1, and the attribute of key2 is used in grpc_config of endpoints.
If the attribute of key2 referenced in endpoints is known after apply for some reason, and as a result there is no diff in the attribute of key2, only the config_id will be changed, but in that case it will not be applied and ` Provider produced inconsistent final plan` error happened.

As a specific case, we have confirmed the occurrence of this problem in the product code in cases where grpc-config, protoc-descriptor, etc. are obtained through multiple resources such as local_file, etc. and external files obtained by null_resource.

I have [closed P/R](https://github.com/GoogleCloudPlatform/magic-modules/pull/8853) and newly opened because discovering that the previous P/R had many incorrect modified source code, corrections, tests, etc.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/11776

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
servicemanagement: fixed issue in `google_endpoints_service` where an inconsistent plan would be created when certain fields had computed values 
```

### CODE REVIEW

**Comment by oshiro3** [comment]
@NickElliot 
I apologize for the inconvenience, but have you had a chance to review this P/R?
If you have any problems or questions, or if you think this P/R should be closed, I would greatly appreciate your comments to that effect.

**Review by NickElliot — COMMENTED** [review]
Mostly LGTM! The logic makes sense and the new test fulfills the conditions of the computed fields no longer producing errors. Would it be possible to add another test that verifies for openapi_config in addition to the other two currently covered fields?

**Comment by oshiro3** [comment]
@NickElliot 
Thanks for the appropriate review.
I was able to extend the test for the open_api_config and grpc_config parameters, but could not come up with a good way to make `protoc_output_base64` known_after_apply without changing the content.
I believe this can be reproduced during testing by using `local_file`, `null_resource`, etc. or by creating a temporary file, but if you have a better way, please let me know.

**Review by NickElliot — APPROVED** [review]
This should be fine as is. Thanks for the contribution!

**Pull request merged**
