### PR TITLE
Added version information for deletion_protection_enabled

### PR DESCRIPTION
**Pull request by 4TT1L4**
The deletion_protection_enabled support was recently added. It makes sense to make this explicitly visible in the documentation.

As proposed in the following comment:
 - https://github.com/hashicorp/terraform-provider-google/issues/13398#issuecomment-1398752774
 
```release-note:none
sql_database: Improved the documentation of `deletion_protection_enabled` setting for `sql_database_instance`.
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Apologies, we won't add version information for specific fields. It's not something we currently do for any other parameters.

**Comment by 4TT1L4** [comment]
>  It's not something we currently do for any other parameters.

I understand, but there is some [confusion around this specific new feature](https://github.com/hashicorp/terraform-provider-google/issues/13398#issuecomment-1398752774). Especially since the naming is a bit unfortunate as well.

There is the newly added [deletion_protection_enabled](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection_enabled) and an older [deletion_protection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection) setting.

There is definitely room for improvement around the documentation of this feature.

**Comment by ScottSuarez** [comment]
I would say let's try to centralize the note like this. What do you think? I don't like the idea of adopting the practice overall but its a good place we can put this information for now.


```
This flag only protects instances from deletion within Terraform. To protect your instances from accidental deletion across all surfaces (API, gcloud, Cloud Console and Terraform), use the API flag `settings.deletion_protection_enabled` added in <VERSION>.
```


What do you think?

**Comment by 4TT1L4** [comment]
@ScottSuarez 
> What do you think? I don't like the idea of adopting the practice overall but its a good place we can put this information for now.

I do agree that a new highlighted note is definitely an overkill, but since the version information belongs to the `deletion_protection_enabled` setting, I think it should appear there.

I have updated my PR accordingly. Please have a look at the current state. Thank you.

**Comment by ScottSuarez** [comment]
I think this is acceptable.. Could you sign the CLA in accordance with the googlebot?

**Comment by 4TT1L4** [comment]
> Could you sign the CLA in accordance with the googlebot?

Done. I just had to trigger a re-scan. 👍

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
Could you pull in latest changes? Seems like there are some conflicts

**Comment by 4TT1L4** [comment]
@ScottSuarez 
> Seems like there are some conflicts

I have resolved the conflicts. Somebody has meanwhile tried to clarify the wording a bit. 

Please merge the PR, if you also find the current state appropriate.

Thank you very much.

**Pull request merged**
