### PR TITLE
Parallelize mmv1 build time

### PR DESCRIPTION
**Pull request by ScottSuarez**
Local testing decreased build time from 663 seconds to 280 seconds. (11m to 5m)

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Looks like cloud build is going from 5:15 -> 3:30 (s). So it's a 1.5x speedup in cloud build

**Review by c2thorn — APPROVED** [review]
seems cool :)

**Pull request merged**
