### PR TITLE
Add confidential nodes support to node pools

### PR DESCRIPTION
**Pull request by rnicoll**
This adds support for the "confidential_nodes" configuration at the node pool level, where previously they were only available at cluster level.

As part of this, code required for the confidential nodes configuration is migrated from the cluster file to the node_config.go.erb file.

fixes {https://github.com/hashicorp/terraform-provider-google/issues/13127}

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added `node_config.confidential_compute` field to `google_container_node_pool` resource
```

### CODE REVIEW

**Comment by ScottSuarez** [comment]
Hi, I notice this PR is in draft, let me know when it's ready for review.

**Comment by rnicoll** [comment]
Thanks Scott, will do! It should be ready for review this week or early next.

**Comment by rnicoll** [comment]
@ScottSuarez this is ready for review now

**Comment by rnicoll** [comment]
Unclear why this continues to show as lacking an acceptance test, but if I've missed something do let me know.

**Comment by rnicoll** [comment]
@ScottSuarez Quick nudge on this. Although if there's something I've missed which is causing the Modular Magician to think there isn't an acceptance test, do let me know. I have presumed it's the tool, not me, but was wondering if I've missed something subtle.

**Comment by ScottSuarez** [comment]
Ah thanks for the nudge ! This looks good at a glance. Let me see

**Review by ScottSuarez — APPROVED** [review]

**Comment by ScottSuarez** [comment]
Oh ! one follow up change @rnicoll. We'll need to add this to the documentation for this resource

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_node_pool.html.markdown

**Comment by ScottSuarez** [comment]
Tag me on the change and I can review

**Pull request merged**
