### PR TITLE
Added ForceNew on labels

### PR DESCRIPTION
**Pull request by edwardmedia**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/9000

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
logging: fixed `metric_descriptor.labels` can't be updated on 'google_logging_metric'
```

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
From the [docs](https://cloud.google.com/logging/docs/logs-based-metrics/labels) it looks like description  can be modified without recreating the resource - perhaps `input` should just be on `key` and `valueType`?

It would be great to have a test that would have caught this.

**Comment by edwardmedia** [comment]
The issue on the `labels` field, not on description.

**Comment by melinath** [comment]
yes, the issue is not with description - it should be safe to update description without recreating the resource. With the current PR, it seems like updating the description would be a change to the label, which would cause the entire resource to be recreated. Is that correct?

I think we only need to recreate if a label key or valueType changes; we shouldn't recreate if a label description changes.

**Comment by edwardmedia** [comment]
I see what you mean now. Thank you. @melinath  Updating the PR

**Comment by edwardmedia** [comment]
@melinath I added a test on updating description

**Review by melinath — CHANGES_REQUESTED** [review]
The test should be making sure that changing the label key works (rather than the description), since changing the label key was the original trigger of the bug.

**Comment by edwardmedia** [comment]
Changes in key and/or value triggers recreation. There is nothing we can do in test for these two fields

**Review by melinath — APPROVED** [review]

**Comment by melinath** [comment]
per discussion:

- not adding a regression test because it would be slow (and ForceNew means that it will always succeed, so we don't test that kind of update because tests are slow.)
- The description test isn't strictly related to the bug but it doesn't hurt anything either and it's doing a useful thing.

**Pull request merged**
