### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

# Release Note for Downstream PRs (will be copied)
```releasenote

```

This is roughly a magical-rebase of terraform-providers/terraform-provider-google#4235

### CODE REVIEW

**Comment by jsoref** [comment]
@danawillow

**Comment by jsoref** [comment]
Note: I haven't actually run my tooling on this repository directly. I'll eventually run it against this repository directly and probably make a new PR (there are some other items that weren't in terraform-providers-google).

**Comment by jsoref** [comment]
@danawillow: if I have additional changes and things haven't yet been merged, should I just tack them into this PR?

**Comment by danawillow** [comment]
I was going to go ahead and merge this, but I can hold off until tomorrow. Let me know when it's ready!

**Comment by jsoref** [comment]
@danawillow: Sorry, I'm done. If you'd rather I put those into a new PR, I can. It's trivial for me to do so.

**Comment by jsoref** [comment]
(Sorry, dirty file snuck into commit)

**Pull request merged**
