### PR TITLE
make datapath_provider ForceNew

### PR DESCRIPTION
**Pull request by edwardmedia**
Fixes https://github.com/hashicorp/terraform-provider-google/issues/12676

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
container: fixed unable to update `datapath_provider` on `google_container_cluster` so that modifying the `datapath_provider` field will recreating the resource now
```

### CODE REVIEW

**Review by shuyama1 — COMMENTED** [review]
I was reading the API Doc and it seems the field `datapath_provider` is updatable based on [doc here](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.DatapathProvider), but you probably already tried this. Plus, based on the current behavior of this field (silently ignore the update without any errors), I wonder if adding forcenew to this field will be considered as a breaking change.

**Comment by edwardmedia** [comment]
@shuyama1 I had that question too (whether it is a breaking-change or now).

**Comment by edwardmedia** [comment]
b/254123801

**Review by shuyama1 — APPROVED** [review]
I modified the release note a bit. Please let me know if that makes sense.

**Comment by edwardmedia** [comment]
Looks good to me. Thanks @shuyama1

**Pull request merged**
