### PR TITLE
Add field `traffic.tag` and `traffic.url` to Cloud Run

### PR DESCRIPTION
**Pull request by ybourgery**
Fixes [hashicorp/terraform-provider-google#8654](https://github.com/hashicorp/terraform-provider-google/issues/8654)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrun: added `traffic.tag` and `traffic.url` fields to `google_cloud_run_service`
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Can you use the `tag` field in one of the preexisting tests?

**Comment by ybourgery** [comment]
I added the `tag` field in one of the tests

**Comment by george-oakling** [comment]
This one looks good!

**Comment by acazacu** [comment]
I was on my way to making this exact change, but then I discovered this PR 🎉. Making the `tag` field available in the `google` Terraform  providers would significantly ease my life.

@rileykarson, insofar that I can see, the pipeline looks green. Is there anything missing in this PR so that it can be merged?

**Comment by rileykarson** [comment]
Sorry! Lost email on my part, I'll fix the Magician message to provide a call-to-action. @ybourgery: Do you mind rebasing this? We've changed part of our CI, and it partially draws from the config at the merge base.

**Comment by ybourgery** [comment]
@rileykarson I did the rebase

**Comment by rileykarson** [comment]
This seems to cause an issue when health checking for both tests affected by the changed config, here's the error:

```
Error: Error waiting to create Service: resource is in failed state "Ready:False", message: Cloud Run error: Internal error occurred while performing container health check.

  on terraform_plugin_test.tf line 2, in resource "google_cloud_run_service" "default":
   2: resource "google_cloud_run_service" "default" {
```

I'm not super familiar with Cloud Run configuration in-depth, but a read of https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration#tags suggests that we probably need a second untagged traffic block, in order to receive traffic and pass the health check.

**Comment by rileykarson** [comment]
Cool! Thanks for figuring that out.

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
