### PR TITLE
Fix Ansible spurious diffs

### PR DESCRIPTION
**Pull request by rambleraptor**
Ansible has some spurious diffs. Let's fix them.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

### CODE REVIEW

**Comment by ndmckinley** [comment]
Hi!  I'm the modular magician, I work on Magic Modules.
I see that this PR has already had some downstream PRs generated. Any open downstreams are already updated to your most recent commit, 8247b979afd5c4a437be92c9aadac365e9a328e9. 
## Pull request statuses
terraform-provider-google-beta already has an open PR.
No diff detected in terraform-google-conversion.
No diff detected in terraform-provider-google.
Ansible already has an open PR.
No diff detected in Inspec.
## New Pull Requests
I didn't open any new pull requests because of this PR.

**Comment by ndmckinley** [comment]
Hi!  I'm the modular magician, I work on Magic Modules.
I see that this PR has already had some downstream PRs generated. Any open downstreams are already updated to your most recent commit, 9bbb0b141074e4c555694408cd10155f721594fe. 
## Pull request statuses
**WARNING**: The following files changed in commit 9bbb0b141074e4c555694408cd10155f721594fe may need corresponding changes in third_party/validator:
* third_party/terraform/resources/resource_compute_instance.go

terraform-provider-google-beta already has an open PR.
No diff detected in terraform-google-conversion.
Ansible already has an open PR.
No diff detected in Inspec.
## New Pull Requests
I built this PR into one or more new PRs on other repositories, and when those are closed, this PR will also be merged and closed.
depends: https://github.com/terraform-providers/terraform-provider-google/pull/4898

**Comment by ndmckinley** [comment]
Hi!  I'm the modular magician, I work on Magic Modules.
I see that this PR has already had some downstream PRs generated. Any open downstreams are already updated to your most recent commit, 7ab84fee48e2774c28c189b413e9b998dd294e40. 
## Pull request statuses
No diff detected in terraform-provider-google-beta.
No diff detected in terraform-google-conversion.
No diff detected in terraform-provider-google.
Ansible already has an open PR.
No diff detected in Inspec.
## New Pull Requests
I didn't open any new pull requests because of this PR.

**Comment by rambleraptor** [comment]
thanks for the review @danawillow!

**Pull request merged**
