### PR TITLE
add standard type vmwareengine network

### PR DESCRIPTION
**Pull request by swamitagupta**
Added support for STANDARD type VMwareEngine Network resource and datasource.
Promoted the Network resource from Beta to GA

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
vmwareengine: added `STANDARD` type support to `google_vmwareengine_network` resource
```

```release-note:new-resource
`google_vmwareengine_network` (ga)
```

### CODE REVIEW

**Comment by rileykarson** [comment]
Just noting that I'm waiting for this to exit draft before reviewing! Let me know if you'd like a pass before that.

**Comment by swamitagupta** [comment]
> Just noting that I'm waiting for this to exit draft before reviewing! Let me know if you'd like a pass before that.

Hi Riley, 
Still finishing up the PR, will exit draft once done to kickoff the review procedure.

**Comment by swamitagupta** [comment]
Hi @rileykarson,
I am unable to figure out whats causing `TestAccLoggingProjectSink_updatePreservesCustomWriter` to fail. Could you please check it once?

**Review by rileykarson — COMMENTED** [review]
`TestAccLoggingProjectSink_updatePreservesCustomWriter` doesn't look related, we can ignore it. Changes LGTM- just got a merge conflict to resolve to merge.

**Comment by swamitagupta** [comment]
> `TestAccLoggingProjectSink_updatePreservesCustomWriter` doesn't look related, we can ignore it. Changes LGTM- just got a merge conflict to resolve to merge.

Resolved the merge conflict.

**Review by rileykarson — APPROVED** [review]

**Pull request merged**
