### PR TITLE
Added optional field `jwks_json` to `workloadidentityprovider`

### PR DESCRIPTION
**Pull request by EZIOJQ**
fixes https://github.com/hashicorp/terraform-provider-google/issues/14786

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: Added optional field `jwks_json` to `workloadidentityprovider`
```

### CODE REVIEW

**Comment by EZIOJQ** [comment]
The test failure in beta provider is due to google internal changes. Trying to resolve internally

**Comment by megan07** [comment]
@EZIOJQ sounds good, thanks! I don't see this field [documented](https://cloud.google.com/iam/docs/reference/rest/v1/projects.locations.workloadIdentityPools.providers#Oidc), do you have any documentation I can see?

**Comment by EZIOJQ** [comment]
Hey @megan07, this field currently is on preview, you can check it here https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers

**Comment by megan07** [comment]
From what I can see, this looks good to me! The test passes in GA, it looks like the field isn't returned in the beta API. Once that is worked out, we can re-run the test and we can merge. Thanks!

**Review by megan07 — APPROVED** [review]

**Comment by EZIOJQ** [comment]
Alright, I fixed it internally and my local run passed, do you know how to re-trigger the test here? @megan07

**Comment by EZIOJQ** [comment]
Sorry the fix is not reflected publicly. I'll post here once the fix is fully deployed

**Comment by EZIOJQ** [comment]
Hey @megan07, looks like all tests are happy now. 
`TestAccComputeFirewallPolicyRule_multipleRules` failed due to quota exceeds. I don't think it's related to my change.

**Review by megan07 — APPROVED** [review]
LGTM! Tests pass, thanks!

**Pull request merged**
