### PR TITLE
Skip VCR tests for resources converted to the plugin-framework

### PR DESCRIPTION
**Pull request by roaks3**
Related to https://github.com/hashicorp/terraform-provider-google/issues/14158

These tests seem to be doing something that the VCR doesn't like, so skipping them for now to reduce noise in PRs

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

### CODE REVIEW

**Comment by roaks3** [comment]
@megan07 adding you to weigh in on this. We don't need to merge it if you have something else in mind, but I think this would help for other PRs, and we can investigate these specific test failures in a dedicated PR where they are unskipped.

**Comment by megan07** [comment]
I'm fine with this for now and will try to pick up the issue in the next week or so if i have the chance - unless we want it sooner?

**Comment by roaks3** [comment]
No, I think that timeframe makes sense. These tests are still running and passing in our nightly tests, but they just seem to have a problem with VCR specifically. Since they appear to fail consistently in VCR, they won't alert us to regressions for incoming PRs, and skipping them will reduce the noise while we work it out. I think we definitely want to get them added back in later, but it doesn't seem urgent.

**Review by hao-nan-li — APPROVED** [review]
LGTM

**Pull request merged**
