### PR TITLE
Add Intercept resources to Network Security.

### PR DESCRIPTION
**Pull request by duvni**
This PR is a promotion from google-private provider.
Removal CL: https://cloud-internal-review.git.corp.google.com/c/cloud-graphite-eng/magic-modules-private-overrides/+/49230

All Intercept resources are bundled together in one PR because they're dependent on one another and cannot be tested separately.

```release-note:new-resource
`google_network_security_intercept_deployment`, `google_network_security_intercept_deployment_group`, `google_network_security_intercept_endpoint_group_association`, `google_network_security_intercept_endpoint_group`
```

### CODE REVIEW

**Comment by shuyama1** [comment]
I'll be out for a week and won't have time to review this PR before my leave. Reassigning to another reviewer. 

@modular-magician reassign-reviewer

**Comment by shuyama1** [comment]
@modular-magician reassign-reviewer

**Review by zli82016 — CHANGES_REQUESTED** [review]
It is adding four new resources in one PR. Can you split the PR into 4 PRs? Each PR will add a new resource.

**Comment by duvni** [comment]
> It is adding four new resources in one PR and hard to review. Can you split the PR into 4 PRs? Each PR will add one new resource.

As specified in the description, these resources are dependent on each other so they cannot be tested separately, meaning the PRs will have to be stacked, and in case we need to rollback we will have to rollback all of the PRs as rolling back just one has the risk of breaking the others. If you still think this is the way to go let me know.

**Comment by zli82016** [comment]
> As specified in the description, these resources are dependent on each other so they cannot be tested separately, meaning the PRs will have to be stacked, and in case we need to rollback we will have to rollback all of the PRs as rolling back just one has the risk of breaking the others. If you still think this is the way to go let me know.

This PR is really large. It is really easy to miss something and introduce bugs.

There are dependencies among the resources, then we can split the PR based on the dependencies.
PR1 will add `google_network_security_intercept_deployment_group`
PR2 will add `google_network_security_intercept_deployment`.
PR3 will add `google_network_security_intercept_endpoint_group`.
PR4 will add `google_network_security_intercept_endpoint_group_association`.
PR2 and PR3 can be opened in parallel. 

Feel free to let me know if you have any questions.

**Pull request closed without merging**
