### PR TITLE
Promote Confidential GKE Nodes to GA

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/10236

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted `confidential_nodes` field in `google_container_cluster` to GA
```

### CODE REVIEW

**Comment by upodroid** [comment]
You coded this feature the first time round in #4136. I think the tests are overkill given the field is ForceNew. It is also a very slow and sequential test given how GKE API behaves.

**Comment by melinath** [comment]
Sorry for the delayed review; we've been working on 4.0.0 so non-critical PRs were on hold. It looks like there may be a file conflict to resolve, but in the meantime: /gcbrun

**Comment by melinath** [comment]
🤦  the run failed due to the file conflict.

**Comment by upodroid** [comment]
Fixed conflicts

**Comment by melinath** [comment]
It looks like the failures are unrelated. Here's a GA run of the specific new test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/215959

**Review by melinath — APPROVED** [review]
tests passed, lgtm

**Pull request merged**
