### PR TITLE
pulls external providers for TestAccCGCSnippet_sqlDatabaseInstanceSql…

### PR DESCRIPTION
**Pull request by megan07**
…serverExample

Fixes https://github.com/hashicorp/terraform-provider-google/issues/11825

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
sql: updated `google_sql_user.sql_server_user_details` to be read only. Any configuration attempting to set this field is invalid and will cause the provider to crash during plan time.
```

### CODE REVIEW

**Comment by megan07** [comment]
non vcr test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/305415

**Comment by shuyama1** [comment]
Looks like the failed test `TestAccSqlUser_mysqlDisabled` is related.

**Comment by megan07** [comment]
@shuyama1 - I think we're finally good on tests assuming you verify that `sql_server_user_details` is read-only. Thanks!

**Review by shuyama1 — COMMENTED** [review]
Confirmed with the service team that `SqlServerUserDetails` is an output-only field. However, changing the field to output-only is a breaking change and we may need to wait until next major release.

**Comment by slevenick** [comment]
I believe this will fix https://github.com/hashicorp/terraform-provider-google/issues/11891 as the current behavior for SQLSERVER users is that the provider crashes during plan time as it attempts to set a field that doesn't exist in the schema. Because of that, I think we can mark this as computed even though it would technically be breaking. The existing functionality is much more breaking than the fix will be

**Comment by megan07** [comment]
2 of the tests skipped by VCR (specifically the password policy one since that was added since): https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/343440

**Comment by shuyama1** [comment]
@megan07 I modified the changelog a bit to include the current behavior of this field to justify why we are making this breaking change.

**Comment by shuyama1** [comment]
VCR skipped test `TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample` passed: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/343444?buildTab=tests&status=passed

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
