### PR TITLE
Fix licenses that "assertain" to MM files. 

### PR DESCRIPTION
**Pull request by emilymye**
* Replace `if false` with erb comment blocks.
* Use a word that is real/easier to spell than "assertains"

-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by rambleraptor** [comment]
Hi, you're my favorite person.

Can you un-commit the changes to the `build/` directory? Otherwise, this is probably good to go!

**Comment by rambleraptor** [comment]
Huh, would you look at that? I should fix that one weird Ansible file.

**Comment by rileykarson** [comment]
Would you mind making an event in your calendar ~a week out to run whatever script you ran again? Just in case we committed old-format ones in the interim.

**Comment by emilymye** [comment]
@rileykarson  👍

**Pull request merged**
