### PR TITLE
Add better import for spanner, allow underscore in database names

### PR DESCRIPTION
**Pull request by emilymye**
Redo of #587

-----------------------------------------------------------------
# [all]

### CODE REVIEW

**Comment by sudoforge** [comment]
Note that this closes #583.

**Comment by chrisst** [comment]
@emilymye looks like you're breaking due to `testAccSpannerDatabase_basicWithInitialDDL` being declared twice:

```google/resource_spanner_database_test.go:156:84: testAccSpannerDatabase_basicWithInitialDDL redeclared in this block```

**Comment by emilymye** [comment]
@chrisst sorry, the fix fixed it but I need approval on this PR :(

**Comment by chrisst** [comment]
You closed the beta PR but it looked like it had a combo of legit changes in addition to pulling in something else.

**Comment by emilymye** [comment]
Ack, reopened beta PR. Should have just waited to do this PR.

**Pull request merged**
