### PR TITLE
Added DNS Managed zone support files

### PR DESCRIPTION
**Pull request by palani-ram-google-partner**
Added DNS Managed zone support files

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement

```

### CODE REVIEW

**Comment by palani-ram-google-partner** [comment]
@melinath Please review this PR

**Comment by palani-ram-google-partner** [comment]
@melinath It's corresponding TFV PR is
https://github.com/GoogleCloudPlatform/terraform-validator/pull/371

**Comment by melinath** [comment]
@ScottSuarez do you want to take this one since it was randomly assigned to you anyway?

**Comment by ScottSuarez** [comment]
@melinath , do you think you could review and I can watch? I haven't made many changes in this area so I want to learn what to look for.

**Comment by melinath** [comment]
👍  sure

**Review by melinath — CHANGES_REQUESTED** [review]
It looks like downstream generation is failing with this error:

```
/mm-terraform-validator-ga-head/mmv1/provider/core.rb:152:in `block (2 levels) in copy_file_list': /go/src/github.com/GoogleCloudPlatform/terraform-validator/converters/google/resources/dns_managed_zone.go was already modified during this run.
```

This is because the dns_managed_zone.go is already being autogenerated - it should be enough to add it to resource_converters.go.erb (unless there's a specific need to handwrite it?)

**Comment by palani-ram-google-partner** [comment]
@melinath As dns_managed_zone.go is autogenerated, I have added in resource_converters.go.erb . Please review it.

**Review by melinath — APPROVED** [review]
LGTM

**Pull request merged**
