### PR TITLE
Instance templates can't be updated.

### PR DESCRIPTION
**Pull request by ndmckinley**
https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates shows delete, get, and insert only.

-----------------------------------------------------------------
# [all]
Remove non-existent update feature from instance templates.

### CODE REVIEW

**Comment by ndmckinley** [comment]
Hm!  That's what it says in "`api.yaml` decoded", our little sheet for supplemental docs - but puppet, ansible, and chef are blank.  How would you set a resource as 'needs delete / recreate instead of update'?

**Comment by ndmckinley** [comment]
Ooh... That seems to indicate that this *isn't* the way you'd do it in puppet.  Shoot!  How would you do it?

**Comment by danawillow** [comment]
@rambleraptor, do you know what _is_ the intended use for `input: true`? I was told "properties that are only set on creation time", which to me, means "properties such that if they were to change, you would have to recreate the resource".

**Comment by ndmckinley** [comment]
My current belief is that you can't do it in puppet.  I'm trying to verify.

**Comment by ndmckinley** [comment]
Yep, can't do it in puppet!  We'll rectify that.  :)

**Pull request merged**
