### PR TITLE
Beginning the Puppet/Chef removal

### PR DESCRIPTION
**Pull request by rambleraptor**
This is the first of what will be many Puppet/Chef removal PRs.

This gets rid of the big stuff. There's some left over code that I inevitably missed + some stuff that we'll want to refactor with all of this gone.

-----------------------------------------------------------------
# [all]
Removing Puppet + Chef. End of an era.

### CODE REVIEW

**Comment by rambleraptor** [comment]
I'd like to get as many +2s as possible on this since I'm deleting 34k lines of code

**Comment by ndmckinley** [comment]
I don't really have any concerns about this at all - LGTM.  :)  The `api/type.rb` changes are the ones I'm focused on.

**Comment by emilymye** [comment]
This seems fine to me, as long as compiler works - I don't think I have any input for deletion of files. Can you run the compiler and paste the output in here just as a extra precaution/proof-of-verification?

**Comment by danawillow** [comment]
@emilymye if the compiler didn't work, wouldn't the magician have failed?

**Comment by emilymye** [comment]
Good point!

**Pull request merged**
