### PR TITLE
fix: notification_config & dns_cache_config ga

### PR DESCRIPTION
**Pull request by ericyz**
fixes: https://github.com/hashicorp/terraform-provider-google/issues/11681

If this PR is for Terraform, I acknowledge that I have:

- [ X ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ X ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ X ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ X  ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ X ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: promoted `notification_config` and `dns_cache_config` on `google_container_cluster`
```

### CODE REVIEW

**Comment by ericyz** [comment]
Could you please share the CB logs or grant view permissions to zhaoe@

**Comment by megan07** [comment]
Hi @ericyz! Thank you for contributing!

There are a few more places you're going to want to move the `dns_cache_config` block from to include it in the GA provider.
In the Schema definition [[here](https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L328)]
In the expand function [[here](https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L3120)]
In the flatten function [[here](https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L3794)]

Similar sentiment for `notification_config`, however, that's a root level attribute, so instead of expand/flatten functions, you'll see it in the Create and Read functions.

Our tests that auto-run only run beta tests, so I'll have to run this against the GA provider manually. When you've made the above changes, I'll run those and copy the results back here.

Thanks so much!

**Comment by ericyz** [comment]
Thanks for your pointers @megan07 . I have patched as required and also attempted to run local test, but failed on the following error messages

```
google/resource_bigquery_data_transfer_config.go:37:36: undefined: context
google/resource_bigquery_job.go:36:26: undefined: regexp
google/resource_bigquery_job.go:37:26: undefined: regexp
google/resource_billing_budget.go:1284:39: undefined: context
google/resource_cloud_run_service.go:35:34: undefined: context
google/resource_cloud_run_service.go:44:41: undefined: regexp
google/resource_cloud_run_service.go:61:49: undefined: regexp
google/resource_cloud_run_service.go:74:36: undefined: regexp
google/resource_cloud_scheduler_job.go:35:28: undefined: context
google/resource_cloudbuild_trigger.go:34:33: undefined: context
google/resource_cloudbuild_trigger.go:34:33: too many errors
make: *** [testacc] Error 2
```

**Comment by megan07** [comment]
@ericyz odd, I'm getting this error, and so was the builder:
```
google/resource_container_cluster.go:1303:23: undefined: expandNotificationConfig
google/resource_container_cluster.go:1648:41: undefined: flattenNotificationConfig
google/resource_container_cluster.go:2298:32: undefined: expandNotificationConfig
```
You'll need to remove the blocks from these spots too - sorry I must have missed these before?:
[Expand Notification Config](https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L3372)
[Flatten Notification Config](https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L3692)

I think this still needs to be pulled out as well?
https://github.com/GoogleCloudPlatform/magic-modules/blob/911982502213d611878b0ca5ddbf05b8ee8acb80/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L3794

I'd look for references to both notification config and dns cache config and just make sure they're pulled out from the blocks that are beta-only.

**Comment by ericyz** [comment]
Thanks for your pointer @megan07 . I have patched accordingly

**Comment by megan07** [comment]
Looks great! And one last thing I just thought about (sorry, I forgot about this earlier) - would you mind updating the tests as well, please? After that I'll run these against our GA provider tests and, assuming they're good to go, we'll merge! Thanks!

[NotificationConfig](https://github.com/GoogleCloudPlatform/magic-modules/blob/13548b053863f6313efc8faa94957f66be7f0c4c/mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb#L2940) and [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/13548b053863f6313efc8faa94957f66be7f0c4c/mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb#L2940)

[DnsCacheConfig](https://github.com/GoogleCloudPlatform/magic-modules/blob/13548b053863f6313efc8faa94957f66be7f0c4c/mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb#L2824)

**Comment by ericyz** [comment]
Thanks @megan07 for your help. I have updated the tests as guided.

**Comment by megan07** [comment]
@ericyz  - something looks like it didn't merge well? would you mind rebasing?

**Review by megan07 — APPROVED** [review]
Looks good! I ran it locally and was able to get it to pass with this one add on. Thanks!

**Comment by ericyz** [comment]
Hi @megan07 - It seems the downstream terraform-provider doesn't merge the change yet. What is the process to publish the change to the next release? Thanks.

**Comment by megan07** [comment]
Hi @ericyz, sorry for the confusion, it looks like it just missed the cut off for the previous release and should be in the next release (which is scheduled for this week - holidays shift our release schedules a bit). Thanks for understanding!

**Pull request merged**
