### PR TITLE
Added new resource Job in Data Loss Prevention

### PR DESCRIPTION
**Pull request by abheda-crest**
Added support for `google_data_loss_prevention_job` resource.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_data_loss_prevention_job`
```

### CODE REVIEW

**Comment by abheda-crest** [comment]
@trodge Could you please review this PR?

**Comment by trodge** [comment]
We generally avoid implementing job resources because they don't fit the terraform model. The behavior of most job resources is to delete themselves once the job is completed, and this conflicts with terraform's assumption that the resource will continue to exist until deleted.

**Comment by abheda-crest** [comment]
@trodge Any thoughts?

**Comment by trodge** [comment]
> @trodge Any thoughts?

It looks like we still want to avoid implementing this resource. Finished job resources are usually cleaned up by the API eventually, leaving terraform with an inconsistent state.

**Pull request closed without merging**
