### PR TITLE
increase google cloud netapp create storagePool timeout to 45 mins

### PR DESCRIPTION
**Pull request by Mehul3217**
**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:enhancement
netapp: increased timeouts of `google_netapp_storage_pool ` resource to 45 mins
```

### CODE REVIEW

**Comment by okrause** [comment]
Hello @shuyama1 , please hold back from merging this. We like to set this timeout to 45min instead of 30min. @Mehul3217 will send an updated PR the next few days.

**Comment by shuyama1** [comment]
> Hello @shuyama1 , please hold back from merging this. We like to set this timeout to 45min instead of 30min. @Mehul3217 will send an updated PR the next few days.

Sure. Thanks for the heads up. I'll convert this PR to draft for now and please mark it as ready to review when it's ready. Thank you!

**Comment by Mehul3217** [comment]
> > Hello @shuyama1 , please hold back from merging this. We like to set this timeout to 45min instead of 30min. @Mehul3217 will send an updated PR the next few days.
> 
> Sure. Thanks for the heads up. I'll convert this PR to draft for now and please mark it as ready to review when it's ready. Thank you!


Done, ready for review now. Thanks

**Review by shuyama1 — APPROVED** [review]

**Pull request merged**
